### ISSUE TITLE
This SVG can't be parsed

### ISSUE THREAD

**Issue by Kreijstal** [ManimCommunity/manim#100]
well, we know already that SVG has problems with arcs but this error is different, (from discord help)
https://cdn.discordapp.com/attachments/669259565941915723/715235727386083499/RC.svg

**Comment by bkorecic** [comment]
I think it is expecting a specific SVG format or something like that, because i've also had errors when saving svgs with Inkscape.

Before it is fixed, one fix is to use cairosvg, first install it with pip, then run

`cairosvg RC.svg -o RCnew.svg`

then the RCnew.svg file should work as expected.

**Comment by yoshiask** [comment]
One reason why this SVG isn't being displayed properly is because it uses `<line>` for pretty much everything, and Manim doesn't currently support that SVG element.

**Comment by leotrs** [comment]
@yoshiask how hard is it to have manim support `<line>`?

**Comment by yoshiask** [comment]
@leotrs Pull request #108 already adds support for `<line>`, but the parser has other issues too

**Comment by leotrs** [comment]
Can the original offending SVG be parsed now that <line> is supported?

**Comment by yoshiask** [comment]
It's closer, but the parser doesn't put shapes in the correct location. A lot more work has to be done before this SVG works as expected.

**Comment by leotrs** [comment]
As we have currently no one working on improving SVG support, and it is not one of our current priorities, I am closing this issue for the time being.

This issue will be reopened when someone takes on the challenge to improve SVG support.

All issues (open or closed) related to SVG support can be found [in the SVG project board](https://github.com/ManimCommunity/manim/projects/8#card-49797664).
