### ISSUE TITLE
Using \raggedright{} gives latex errors with TextMobject

### ISSUE THREAD

**Issue by baljeetrathi** [ManimCommunity/manim#1007]
I have the following text inside a TextMobject:
```
TextMobject(r"\raggedright{The value of variable is \\ easily determined as}", r"1923")
```

This should have aligned the multi-line text on the left side. However, it just gives me a LaTex compilation error. Am I doing it wrong or is there some other problem?

Thanks.

**Comment by behackl** [comment]
Hello, please use the Issue template when reporting bugs. From the information you have given me, it is impossible to tell whether you are using the community version of Manim, and it is also impossible to tell what kind of error exactly occurs.

For me, your code compiles:

![RR](https://user-images.githubusercontent.com/11851593/107119464-04c82a80-6888-11eb-9c74-034d5932d67d.png)

so I cannot reproduce this issue.
