### ISSUE TITLE
Cannot display Chinese Characters in Title

### ISSUE THREAD

**Issue by ArtanisWongWWW** [ManimCommunity/manim#1009]
## Description of bug / unexpected behavior

I tried to create a title that contains Chinese characters and it wasn't successful.
The error is  ValueError: latex error converting to dvi.

## Expected behavior

The Chinese characters should display normally and there would be no error.

## How to reproduce the issue

<details><summary>Code for reproducing the problem</summary>

```py
class TitleChinese(Scene):
    def construct(self):
        title = Title("生命游戏", font = "sans-serif")
        self.add(title)
```

</details>

## Additional comments
Could you explain why this happens and how to solve this problem? Thank you very much!

**Comment by behackl** [comment]
Whenever there is an error of the form `ValueError: latex error converting to dvi`, the log also mentions a file ending in `.log`, could you share the contents of that file as well?

It seems like LaTeX is unhappy about what you are trying to do, the `.log` file will help us to identify the precise problem.

**Comment by ArtanisWongWWW** [comment]
[0db7e4bbef7829de.log](https://github.com/ManimCommunity/manim/files/5939027/0db7e4bbef7829de.log)

**Comment by ArtanisWongWWW** [comment]
In .log file it says "! Package inputenc Error: Unicode character 生 (U+751F) (inputenc) not set up for use with LaTeX.", is that because Title inherits from Tex so it cannot display unicode characters?

**Comment by behackl** [comment]
Have a look at https://docs.manim.community/en/v0.3.0/reference/manim.mobject.svg.tex_mobject.html?highlight=latex#latextemplatelibrary -- you probably need to add `tex_template=TexTemplateLibrary.ctex` as a keyword argument to `Title`.

**Comment by ArtanisWongWWW** [comment]
Thanks!
