### ISSUE TITLE
A guide for people migrating from 3B1B shaders branch to Manim Community.

### ISSUE THREAD

**Issue by baljeetrathi** [ManimCommunity/manim#1011]
I am guessing there will be a lot of breaking changes when people go from 3B1B shaders branch to Manim community and most of the code their won't run.

Is there a guide to help people figure out the changes that they need to make in the code to make it run with ManimCommunity?

Also, a dumb question but what is the difference between cloning the 3B1B manim repository and installing the community manim using `pip install`? Are there any specific advantages?

Thanks.

**Comment by huguesdevimeux** [comment]
Hi! 

> Is there a guide to help people figure out the changes that they need to make in the code to make it run with ManimCommunity?

I'm afraid there is no such thing. There are a few breaking changes but most of the manim CE is backward compatible (there are `DepreciationWarning`). It shouldn't be too hard to migrate some scenes too. 

> what is the difference between cloning the 3B1B manim repository and installing the community manim using pip install? Are there any specific advantages?

3b1B mabim and manim community (=manimCE) are two differents repositories. You can install manimCE with pip install manim, there is no such thing with 3b1B version.

> Also, a dumb question

there is no dumb questions !

**Comment by baljeetrathi** [comment]
Thanks @huguesdevimeux :)

I meant to ask what kind of things does ManimCE does different than 3b1b. Is there a focus on adding more features or making the codebase more standardized etc?

Can I run ManimCE by just cloning it repository as well or will it only work it I install it using `pip install manim`?

If ManimCE works in both these cases, then is there any specific advtanges of going the `pip` route instead of cloning the repository?

Thanks. :)

**Comment by huguesdevimeux** [comment]
> I meant to ask what kind of things does ManimCE does different than 3b1b. Is there a focus on adding more features or making the codebase more standardized etc?

Well, there are a lot of things, but it's mainly about everything else except the graphical units (we have touched a little to the graphical code base compared to everything else). That being said, manim CE goal is to make more user friendly, stable, etc. 
You can take a look at the change log to see everying that has changed since the fork in May 2020. 

> Can I run ManimCE by just cloning it repository as well or will it only work it I install it using pip install manim?
Both will work! pip is maybe simpler if you don't have git or you don't want to bother cloning it.

**Comment by baljeetrathi** [comment]
Thanks @huguesdevimeux for clearing all my doubts. :)
