### ISSUE TITLE
How can I use Custom fonts in ManimCommunity?

### ISSUE THREAD

**Issue by baljeetrathi** [ManimCommunity/manim#1012]
With the 3B1b version, I could modify the `ctex_template.tex` file in order to change the font by adding the line below:

```
\setprimaryfont{Custom Font}
```

However, there is no `ctex_template.tex` file in ManimCommunity so I am stuck.

I read the documentation and it says that I can use custom fonts by making changes like this:

```
Tex(r"Some Text", r"More text", tex_template=TexTemplateLibrary.ctex)
```

However, it gives me errors about `xelatex error converting to dvi`. Am I supposed to do something else as well besides making this change?

Thanks. :)

**Comment by jsonvillanueva** [comment]
Hi @baljeetrathi,

Please include more information about your system and the code you're running as this makes it easier to debug. If you haven't already seen [this in the docs](https://docs.manim.community/en/latest/reference/manim.mobject.svg.tex_mobject.html#extra-latex-packages), you can add to the preamble of the TexTemplateLibrary, but also use your own [textemplate file](https://docs.manim.community/en/latest/reference/manim.utils.tex.html).

The issue you might be facing is either related a missing package, or that you're missing xelatex (this is [default tex compiler for TexTemplateLibrary.ctex](https://github.com/ManimCommunity/manim/blob/master/manim/utils/tex_templates.py#L45)), or change it to latex, pdflatex, lualatex, or whatever you have installed...

**Comment by jsonvillanueva** [comment]
Closing as the author has acknowledged the last comment, and this is more of a usage issue rather than a library bug.
