### ISSUE TITLE
Create teams

### ISSUE THREAD

**Issue by PgBiel** [ManimCommunity/manim#102]
We should create GitHub teams in the ManimCommunity organization, which function like Discord's roles, albeit in GH. One can simply ping the team, e.g., for docs to review docs in a PR, and so on.

Note that teams are freely assignable, i.e., if you want to join a team (or more than one!), feel free to say so.

This will better divide and establish the roles of each participant of the project.

**Comment by leotrs** [comment]
As a first pass, I propose we create the following teams: docs, tests, code reviewer, issue wrangler. The last team is for people who bump old issues, close stale issues, label issues, etc. Issues accumulate quickly and it's very difficult to keep on top of them all. Also, this last team can be for members of the community outside of the core dev team, so other members (and even beginners) can have a concrete way of contributing to the maintenance of the package.

**Comment by PgBiel** [comment]
LGTM, we can add/change teams later on as we find necessary

**Comment by leotrs** [comment]
Yeah, this doesn't have to be set in stone. Also, is there any benefit in creating a team for all core devs? I think so.

**Comment by PgBiel** [comment]
Might be a good idea as well

**Comment by leotrs** [comment]
There are now teams for core, docs, and tests. There is also a team for "contributors", who are outside of the core dev team.
