### ISSUE TITLE
instantiation kwarg `stroke_width` does not actually change stroke width

### ISSUE THREAD

**Issue by MrMallIronmaker** [ManimCommunity/manim#1020]
## Description of bug / unexpected behavior

The cross should have wide bars.

## Expected behavior

The cross has thin bars.

## How to reproduce the issue

<details><summary>Code for reproducing the problem</summary>

```py
class TempScene(Scene):
    def construct(self):
        rect = Rectangle()
        cross = Cross(rect, stroke_color=RED, stroke_width=20)
        self.add(rect)
        self.add(cross)
        self.wait()
```

</details>

## Additional media files

<details><summary>Images/GIFs</summary>

</details>

## Logs
<details><summary>Terminal output</summary>

```
PASTE HERE OR PROVIDE LINK TO https://pastebin.com/ OR SIMILAR
```

</details>

## System specifications

<details><summary>System Details</summary>

- OS (with version, e.g Windows 10 v2004 or macOS 10.15 (Catalina)):
- RAM:
- Python version (`python/py/python3 --version`):
- Installed modules (provide output from `pip list`):
```
PASTE HERE
```
</details>

<details><summary>LaTeX details</summary>

+ LaTeX distribution (e.g. TeX Live 2020):
+ Installed LaTeX packages:

</details>

<details><summary>FFMPEG</summary>

Output of `ffmpeg -version`:

```
PASTE HERE
```
</details>

## Additional comments

The problem is really simple - the kwarg `stroke_width` is overwritten when `VMobject.__init__` is called. However, it's not clear to me where the fix should go. I would think this is an issue much larger than this specific example, if the value is really being overwritten in the initialization function.

Because I've spent so much time sitting with the SVG files, perhaps something like CSS might make sense for configuring these properties?

**Comment by AntonBallmaier** [comment]
This should be closed as it is no longer a bug.
![image](https://user-images.githubusercontent.com/26899845/116494195-9b612200-a8a0-11eb-9cd6-29835ac8acc0.png)
