### ISSUE TITLE
New "max-width" option for media output in jupyter notebooks.

### ISSUE THREAD

**Issue by kolibril13** [ManimCommunity/manim#1025]
When using jupyter notebooks, currently a lot of space is occupied by the output images, and sometimes it is nice to have things a bit tighter together.
Here a current screenshot (even with the lowest quality):
![image](https://user-images.githubusercontent.com/44469195/107761257-5c084800-6d2b-11eb-8025-488cd7797777.png)
For comparison:
The standard output size for matplotlib is 375 × 248 pixel in jupyter notebooks:
![image](https://user-images.githubusercontent.com/44469195/107761402-97a31200-6d2b-11eb-86ed-29b30989f2b6.png)

An additional benefit from this would be even faster rendering.

**Comment by jsonvillanueva** [comment]
Does this actually require a new CLI flag? If the issue isn't an issue with storage size/quality video quality being too high, then the issue you're actually referring to might just be the html/css provided instead.
https://github.com/ManimCommunity/manim/blob/master/manim/utils/ipython_magic.py#L106

**Comment by Darylgolden** [comment]
@kolibril13 I plan to work on this, can you clarify whether you prefer a new flag or changing the max-width?

**Comment by kolibril13** [comment]
> @kolibril13 I plan to work on this, can you clarify whether you prefer a new flag or changing the max-width?

@Darylgolden : Thanks a lot, that will be a great addition.
I think that changing the max-width is the way to go here.
