### ISSUE TITLE
Repeating Matrix objects only show once, when using VGroup

### ISSUE THREAD

**Issue by ammar-faifi** [ManimCommunity/manim#1027]
## Description of bug / unexpected behavior

I found this weird, but I am not sure whether this is correct or wrong approach
when I use `VGroup` to group the same `Matrix` objects more than one, it looks that only the last one is appearing, and the other one not, its place is empty

## Expected behavior

it works for me when I add `.cop()` method to  like so, 

## How to reproduce the issue

<details><summary>Code for reproducing the problem</summary>

```py
matrix_r = Matrix([["x"], ["y"]])

lambda_condition_eq = VGroup(
            MathTex("Mr = \lambda r"),
            right_arrow,
            matrix_M,
            matrix_r,
            equal_sign,
            MathTex(r"\lambda"),
            matrix_r,
        ).arrange(RIGHT)
```
here the last `matrix_r` is only appeared 

```py
matrix_r = Matrix([["x"], ["y"]])

adding `.copy()`
lambda_condition_eq = VGroup(
            MathTex("Mr = \lambda r"),
            right_arrow,
            matrix_M,
            matrix_r.copy(),
            equal_sign,
            MathTex(r"\lambda"),
            matrix_r,
        ).arrange(RIGHT)
```
</details>

## Additional media files

<details><summary>Images/GIFs</summary>

originally 
<img width="586" alt="Screen Shot 2021-02-13 at 17 22 17" src="https://user-images.githubusercontent.com/65354445/107852433-ba175700-6e21-11eb-905a-bb37868dd2dc.png">

with `.copy()`
<img width="591" alt="Screen Shot 2021-02-13 at 17 22 54" src="https://user-images.githubusercontent.com/65354445/107852440-c13e6500-6e21-11eb-97af-615113df35b5.png">

</details>

## Logs
<details><summary>Terminal output</summary>

```
PASTE HERE OR PROVIDE LINK TO https://pastebin.com/ OR SIMILAR
```

</details>

## System specifications

<details><summary>System Details</summary>

- OS (macOS Big Sur 11.1):
- RAM: 8GB
- Python version (`python/py/python3 --version`): 3.9
- Installed modules (provide output from `pip list`):
```
PASTE HERE
```
</details>

<details><summary>LaTeX details</summary>

+ LaTeX distribution (e.g. TeX Live 2020):
+ Installed LaTeX packages:

</details>

<details><summary>FFMPEG</summary>

Output of `ffmpeg -version`:

```
PASTE HERE
```
</details>

**Comment by MrMallIronmaker** [comment]
Thanks for filing an issue, this is helpful.

As you said, I think it's the wrong approach - the mental model of VGroups I have is that they are lazy, ad-hoc groupings that don't copy data. 

However, I see where you're coming from. Perhaps there should be a warning if the same object is added to a Group twice? Something like:

`Warning: The same Mobject (<mobject_str_or_repr_call>) was added to a Group more than once. Repeated adds are ignored.`

----

(For future reference, a full reprex is below)
```
from manim import *

class TestScene(Scene):
    def construct(self):
        matrix_r = Matrix([["x"], ["y"]])
        matrix_M = Matrix([["M_0"], ["M_1"]])
        equal_sign = MathTex("=")
        right_arrow = Arrow(start=LEFT, end=RIGHT)

        lambda_condition_eq = VGroup(
                    MathTex("Mr = \lambda r"),
                    right_arrow,
                    matrix_M,
                    matrix_r,
                    equal_sign,
                    MathTex(r"\lambda"),
                    matrix_r, #.copy(),
                ).arrange(RIGHT)

        self.add(lambda_condition_eq)
        self.wait()
```

**Comment by indujaaaa** [comment]
I think repeated adds get ignored because Python passes arguments by reference. It works as intended when you pass the Mobjects by value into `VGroup()` as below. 

It might be common for users to pass them by reference, as @ammar-faifi did. So I think it'll be more useful to copy the repeated adds as we encounter them while adding the Mobjects to the VGroup. 

I'm new to contributing, so please let me know if I went wrong anywhere😅 
I'd like to help with this too, can I take this issue up?

<details>
<summary>When arguments are passed by value</summary>

``` py
class TestScene(Scene):
    def construct(self):
        """
        matrix_r = Matrix([["x"], ["y"]])
        matrix_M = Matrix([["M_0"], ["M_1"]])
        equal_sign = MathTex("=")
        right_arrow = Arrow(start=LEFT, end=RIGHT)
        """

        lambda_condition_eq = VGroup(
                    MathTex("Mr = \lambda r"),
                    Arrow(start=LEFT, end=RIGHT),
                    Matrix([["M_0"], ["M_1"]]),
                    Matrix([["x"], ["y"]]),
                    MathTex("="),
                    MathTex(r"\lambda"),
                    Matrix([["x"], ["y"]]),
        ).arrange(RIGHT)

        self.add(lambda_condition_eq)
        self.wait()
```
![passed by value](https://user-images.githubusercontent.com/53386868/131293775-87eab28f-a220-4444-94b0-6f0e56dda83b.png)
</details>


<details>
<summary>Possible way to handle arguments</summary>

```
for mobject in mobjects
    if mobject is in vgroup_obj
        vgroup_obj += mobject.copy() 
    else
        vgroup_obj += mobject
```

</details>
