### ISSUE TITLE
Documentation guidelines

### ISSUE THREAD

**Issue by PgBiel** [ManimCommunity/manim#103]
We should finish and apply the documentation guidelines on all existing and future PRs (see the Wiki).

Please suggest any changes and ideas for it below.

**Comment by yoshiask** [comment]
The README should have a link to (or at least mention) the GitHub Wiki documentation.

**Comment by leotrs** [comment]
@yoshiask this sounds like an easy PR :)

**Comment by leotrs** [comment]
Closing this as the wiki now contains some guidelines.
