### ISSUE TITLE
Further ideas for the jupyter notebook support

### ISSUE THREAD

**Issue by kolibril13** [ManimCommunity/manim#1034]
Here we can collect some ideas we find useful for jupyter notebook support:
From my side:
* Option to scale the output size (see https://github.com/ManimCommunity/manim/issues/1025)
* Removal of the red output message cell:
![image](https://user-images.githubusercontent.com/44469195/107982212-ec60ba00-6fc3-11eb-86fc-627de818d853.png)
* at the moment, the `-p` flag has no meaning in the jupyter notebook context, as the output is shown all the time. Maybe this can be changed in a way, so that it is even possible to suppress the output

**Comment by behackl** [comment]
We do have scaling, at least for videos (and for images there is a separate issue); the STDERR-area unfortunately can't be removed (but should be suppressed when not using a progress bar), and I don't see a non-confusing way to re-use the `-p` flag.
