### ISSUE TITLE
Including an SVG parsing library?

### ISSUE THREAD

**Issue by markromanmiller** [ManimCommunity/manim#1040]
The SVG engine has been a thorny subject, not least owing to the incredible complexity of the SVG specification, and the endless list of edge cases and rarely used features. One approach is to integrate our SVG parsing engine with an external SVG parser, letting us work with points instead of text commands.

The front-runner for this role is the library `svgelements` (https://github.com/meerk40t/svgelements).

Some initial questions are:
1. What SVG parsers are out there?
2. What can an SVG parser allow us to do?
3. Do we want the added dependency, etc, etc.

cc @kilacoda

**Comment by Aathish04** [comment]
Considering that Manim is now much better at handling SVGs without making use of any 3rd party parsing libraries, can we close this issue?

**Comment by Darylgolden** [comment]
> Considering that Manim is now much better at handling SVGs without making use of any 3rd party parsing libraries, can we close this issue?

I have to strongly disagree with closing the issue; there is still a lot in SVG that Manim does not handle, and handling SVG parsing manually takes a lot more work than with a library. Moreover, manual parsing is much harder to maintain.

**Comment by behackl** [comment]
+1, porting over https://github.com/3b1b/manim/pull/1731 seems like a good idea; the implementation looks significantly cleaner.

**Comment by MrMallIronmaker** [comment]
a quick skim gives me the sense this library is the right way to go. just be sure to minimize or document breaking changes (I would presume there are some quirks in the different ways of handing SVGs that some people have come to rely on and would be surprised to see change)

**Comment by behackl** [comment]
This has been resolved a while ago, we are now also using `svgelements`.
