### ISSUE TITLE
Broken source links on the stable version of the documentation

### ISSUE THREAD

**Issue by Darylgolden** [ManimCommunity/manim#1045]
## Description of bug / unexpected behavior
Source links on the stable version of documentation does not work. It links to something like this: https://github.com/ManimCommunity/manim/blob/stable/manim/mobject/changing.py which is a 404 error. 

## Expected behavior
Source links should link to a file containing source code for the stable version. 

## How to reproduce the issue
On the documentation website, switch the version to stable. Navigate to and click the source link of any class. 

## Additional comments
Perhaps this is an access rights issue, which explains why it evaded detection from community devs for so long?

**Comment by kilacoda** [comment]
The `stable` branch does not exist, that's why it showing the 404. @ManimCommunity/docs ?

**Comment by behackl** [comment]
Indeed, an oversight after getting rid of the `stable` branch. Can be fixed similarly to what is done here: https://github.com/ManimCommunity/manim/blob/6744c48c228c866c8f2256a7a2cd461bde6d411e/docs/source/conf.py#L118 -- possibly also just by linking to master, so adding `or ... == "stable"` to that line.

Sounds like an easy PR, does anyone here want to take care of it? :-)

**Comment by Eugemo** [comment]
I would like to do the PR (i am learning)
allow me?

**Comment by behackl** [comment]
> I would like to do the PR (i am learning)
> allow me?

Of course, please go ahead! :-)

**Comment by Eugemo** [comment]
I am not part of the project, is that why it does not allow me to do the PR? (sorry if I bother, I'm just learning and wanted to do my first PR)
![image](https://user-images.githubusercontent.com/68663197/108603885-2f86a880-7389-11eb-9964-62ec313fd5a4.png)

**Comment by behackl** [comment]
Please don't worry! Usually, the workflow with Github is a bit different: you create a pull request from your fork of the `ManimCommunity/manim` repository.

To create your fork, head to https://github.com/ManimCommunity/manim and look for the fork button on the top right of the page.

**Comment by Eugemo** [comment]
and from the fork I do the PR?

**Comment by behackl** [comment]
> and from the fork I do the PR?

Exactly. You can then choose to PR from your fork to the master branch of this repository.

**Comment by Eugemo** [comment]
can do it! also I was missing the title (it's my first time)
you are so friendly.  thank you very much for your help. I learned from this experience :)

**Comment by jsonvillanueva** [comment]
I believe you accidentally made the PR to 3b1b/manim's master branch instead of ManimCommunity/manim's master branch:
![image](https://user-images.githubusercontent.com/29168469/108613270-20155880-73a5-11eb-975a-22a2b808c994.png)

thus there's a lot of merge conflicts (since 3b1b's version of manim is different). You should close the PR to 3b1b and make sure you're trying to merge your commmits into ManimCommunity:master.

**Comment by Eugemo** [comment]
Is right. thanks for warning and sorry for the confusion

**Comment by Eugemo** [comment]
I apologize, especially to @behackl, whoever gave me the opportunity to do the PR. but I can't do it correctly. I'm going to let someone with more experience than me do it. sorry for the loss of time and inconvenience.

**Comment by behackl** [comment]
>  I apologize, especially to @behackl, whoever gave me the opportunity to do the PR. but I can't do it correctly. I'm going to let someone with more experience than me do it. sorry for the loss of time and inconvenience. I must study more github

Is there anything we can do to help you with getting started?

**Comment by Eugemo** [comment]
surely forget some step, because I can not do it.
I can see again what would be the steps to follow
