### ISSUE TITLE
Show helpful error message instead of FileNotFound

### ISSUE THREAD

**Issue by dipamsen** [ManimCommunity/manim#1052]
## Enhancement proposal
When we create a Manim Scene without any animations, and use `-p` flag, Manim saves the output as an image (since you cannot create a video of 1 frames), but then tries to open the video in system viewer, and throws `FileNotFoundError`. This is a very confusing error, to debug, we could instead show a different error when there are 0 animations and `-p` is used.

eg:
```shell
[MM/DD/YY HH:MM:SS] INFO                                                     scene_file_writer.py:549
                             File ready at path\to\project\media\
                             images\scene\SceneName.png

                    INFO     Rendered SceneName                                          scene.py:175
                             Played 0 animations
Error: You cannot preview video without any animations. Try using --save-as-image or add self.wait() 
to your scene.
```

**Comment by jsonvillanueva** [comment]
I agree with the confusing error, there's a very long list of users who succumb to the issue of using `manim file.py -pql` with no animations. @kilacoda has probably dealt with issues related to videos with no animations at least a few dozen times and it is a very common pitfall. I think the error message can be improved greatly and this should be done prior to my next suggestion. (e.g.
```
Error: Your Scene contains no animations and a video could not be created. Try adding self.wait(), or self.play() animations to your scene before rerunning your command, or use the -s flag  to render the Mobjects added to your scene as an image.
to your scene.
```

Although this error doesn't account for errors where neither animations, nor mobjects, were added to the scene.


<details open>
<summary>My suggestion for the future:</summary>
<br>
I believe the optimal default user experience with the `-p` flag provided would be:
1. If there aren't animations, create an image to preview. If there aren't any Mobjects to render on the screen (i.e. the Scene fails to call ` self.add()`, render a blank image with the background's color.
2. If there are animations, default to creating a video to preview.

I think the source of confusion is not only the preview flag itself, but how Manim creates files based on the quality flags/`-s`. But a dynamic default would seems to be best.
</details>

**Comment by dipamsen** [comment]
Here is a different situation due to the same pitfall:

Consider the scenario where I run `manim file.py -pql` on a `Scene` _with animations_.
After running the scene, I change the code to have _no animations_. I run `manim file.py -pql`.

What happens here is Manim creates the image file (since no animations), and since there is `-p -ql`, Manim tries to open the video file `\media\scene\480p15\file.mp4` which happens to have the previously generated video for the previous code.

Even though this is due the same problem as the above, this is more confusing, as it won't throw any error. It will keep opening the previously generated video.

That said, @jsonvillanueva's suggestion addresses this issue.

**Comment by PhilippImhof** [comment]
I fully agree with @jsonvillanueva: The user should not have to use a different flag. Manim should adapt to what is being created. Nothing to show? Show nothing! No animation? Show an image! Animation? Show it!

The `-s` flag is still useful, because sometimes one has an animation, but is only interested in the last frame. (And we all are when it comes to tests...)
