### ISSUE TITLE
Manim example.py SquareToCircle

### ISSUE THREAD

**Issue by Shantanu-Manim** [ManimCommunity/manim#1054]
#### Preliminaries

- [ ] I have followed the latest version of the
      [installation instructions](https://docs.manim.community/en/latest/installation.html).
- [ ] I have checked the [troubleshooting page](https://docs.manim.community/en/latest/installation/troubleshooting.html) and my problem is either not mentioned there,
      or the solution given there does not help.

## Description of error
-l deprecated and no scenes in module

## Installation logs
 WARNING  Option -l is deprecated please use the --quality/-q flag.                     utils.py:137

(process:10476): GLib-GIO-WARNING **: 01:19:57.924: Unexpectedly, UWP app `20815shootingapp.AirFileViewer_1.4.10.0_x64__xcg28tkrsnqww' (AUMId `20815shootingapp.AirFileViewer_xcg28tkrsnqww!App') supports 316 extensions but has no verbs
                    ERROR                                                                              module_ops.py:65
                                There are no scenes inside that module 

```
```
![manim_example py_issue](https://user-images.githubusercontent.com/79604276/109060346-491e4c00-770b-11eb-8d84-a9bce263f5e1.png)

</details>

## System specifications

<details><summary>System Details</summary>

- OS  Windows 10 
- RAM: 8
- Python version (`python/py/python3 --version`):Python 3.9.2 (tags/v3.9.2:1a79785, Feb 19 2021, 13:44:55) [MSC v.1928 64 bit (AMD64)] on win32
- Installed modules (provide output from `pip list`):
- C:\>pip list
Package           Version
----------------- -------
asgiref           3.3.1
attrs             20.3.0
Automat           20.2.0
backcall          0.2.0
cffi              1.14.4
click             7.1.2
colorama          0.4.4
colour            0.1.5
commonmark        0.9.1
constantly        15.1.0
cycler            0.10.0
decorator         4.4.2
Django            3.1.7
Flask             1.1.2
glcontext         2.3.2
hyperlink         21.0.0
idna              3.1
incremental       17.5.0
ipython           7.20.0
ipython-genutils  0.2.0
itsdangerous      1.1.0
jedi              0.18.0
Jinja2            2.11.3
kiwisolver        1.3.1
manim             0.3.0
ManimPango        0.2.3
mapbox-earcut     0.12.10
MarkupSafe        1.1.1
matplotlib        3.3.4
moderngl          5.6.4
moderngl-window   2.3.0
mpmath            1.2.1
multipledispatch  0.6.0
networkx          2.5
numpy             1.20.1
pandas            1.2.2
parso             0.8.1
pickleshare       0.7.5
Pillow            8.1.0
pip               21.0.1
ply               3.11
prompt-toolkit    3.0.16
pyasn1            0.4.8
pycairo           1.20.0
pycparser         2.20
pycryptodomex     3.10.1
pydub             0.24.1
pygame            2.0.1
pyglet            1.5.15
Pygments          2.8.0
PyHamcrest        2.0.2
pymunk            6.0.0
PyOpenGL          3.1.5
pyparsing         2.4.7
pyreadline        2.1
pyrr              0.10.3
pysmi             0.3.4
python-dateutil   2.8.1
pytz              2021.1
PyYAML            5.4.1
rich              6.2.0
scipy             1.6.1
screeninfo        0.6.7
setuptools        49.2.1
six               1.15.0
sqlparse          0.4.1
sympy             1.7.1
tensor-analysis   1.0.1
tqdm              4.57.0
traitlets         5.0.5
typing-extensions 3.7.4.3
validators        0.18.2
wcwidth           0.2.5
Werkzeug          1.0.1
zope.interface    5.2.0
![pipllist1](https://user-images.githubusercontent.com/79604276/109061402-a2d34600-770c-11eb-8de4-3c1465733520.png)
![piplist2](https://user-images.githubusercontent.com/79604276/109061418-a6ff6380-770c-11eb-9a4c-e2d051849fcc.png)

```
```
</details>

<details><summary>LaTeX details</summary>

+ LaTeX distribution (e.g. TeX Live 2020): i have no idea how to check it
+ Installed LaTeX packages:
<C:\>tlmgr list --only-installed
'tlmgr' is not recognized as an internal or external command,
operable program or batch file.>

<details><summary>FFMPEG</summary>

Output of `ffmpeg -version`:
ffmpeg version 4.3.2-2021-02-20-essentials_build-www.gyan.dev Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 10.2.0 (Rev6, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-lzma --enable-zlib --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-sdl2 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-libass --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libgme --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libtheora --enable-libvo-amrwbenc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-librubberband
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
Unrecognized option '-version'.
Error splitting the argument list: Option not found
![ffmpeg](https://user-images.githubusercontent.com/79604276/109061013-188ae200-770c-11eb-93d2-e72d000d0ff5.png)

```

**Comment by kilacoda** [comment]
What's in `example_scenes.py`? Send the file or a pastebin link of the contents.

**Comment by Shantanu-Manim** [comment]
When we install Manim. File
For checking whether we have installed correct or not
python -m manim example_scenes.py -pl

**Comment by kilacoda** [comment]
How did you install manim?

**Comment by Shantanu-Manim** [comment]
From Git cloning

**Comment by Shantanu-Manim** [comment]
Actually when we install manim we get bunch of files in that there is a
example_scences.py file

**Comment by Darylgolden** [comment]
Did you clone this repo or 3blue1brown's?

**Comment by Shantanu-Manim** [comment]
3blue 1 browns

**Comment by kilacoda** [comment]
Please open an issue there then. Closing.

**Comment by Shantanu-Manim** [comment]
Then please tell me na how to download from here

**Comment by Shantanu-Manim** [comment]
Sir I have downloaded from here only sir.

**Comment by Shantanu-Manim** [comment]
Thanks sir Thanks finally short out I don't know why I gone for there but
now it's all ok.
You can close it sir Thanks Thanks
Thanks & Regards sir
