### ISSUE TITLE
MarkupText: Use Cairo to handle gradients

### ISSUE THREAD

**Issue by PhilippImhof** [ManimCommunity/manim#1062]
## Enhancement proposal

When using gradients in `MarkupText` we have Pango render the text to an SVG. We then load the SVG into a `SVGMobject` and apply the gradient to the characters. This has two major drawbacks:

 - the gradient is done on a per-character basis, i.e. every character has one solid color; the quality of the gradient therefore depends largely on the length of the text to which it is applied
 - with ligatures, the number of paths does not correspond to the number of characters, so the user will have to specify an offset to compensate for this, e.g. `fl` counts for two characters but might be rendered as a single glyph
 - similar problems arise with underline, double underline, overline and strikethrough, because those lines will also be sub-paths of the `SVGMobject`

**Comment by naveen521kk** [comment]
I would like to have this issue in the other repo https://github.com/ManimCommunity/ManimPango, and the issue here should be about `SVGMobject` supporting them.

**Comment by PhilippImhof** [comment]
OK fine for me, because in this case (contrary to the other one) we will probably not need to change the markup class. I will take care of it later.

**Comment by PhilippImhof** [comment]
Closing the issue. It is moved to https://github.com/ManimCommunity/ManimPango/issues/33

**Comment by naveen521kk** [comment]
you could have used `Transfer Issue` button :)

**Comment by PhilippImhof** [comment]
Oh that's neat. Didn't even notice it. They should have made it even smaller :)
