### ISSUE TITLE
Code Coverage Metrics

### ISSUE THREAD

**Issue by MrMallIronmaker** [ManimCommunity/manim#1068]
Tests and code coverage indicators are part of the maturing process of a software library - and I think it's time for Manim to have some. In my mind, code coverage will highlight the parts of the library that are mostly untested and make writing tests a more salient contribution to the library.

As @naveen521kk mentioned in https://github.com/ManimCommunity/manim/issues/193, a good choice is [coverage.py](https://coverage.readthedocs.io/), but I am not tied to any particular toolset.

To me, the next steps forward are:
- Discussing the priorities of the code coverage tool. For example, @eulertour mentioned that it'd be really nice to also test the in-between frames of animations, and @leotrs mentioned that it should cover both regular tests and doctests. 
- Deciding upon the toolset.
- Integrating code coverage into the Github workflow to run on master and PRs.

For reference, I ran coverage.py over the current master branch and about 60% of the library's sloc is run during tests (either pytest or doctests).

**Comment by naveen521kk** [comment]
Did a PR recently on the ManimPango repo, https://github.com/ManimCommunity/ManimPango/pull/35 I could help setting it up if required.

**Comment by huguesdevimeux** [comment]
I have no idea how all of this could work with the graphical unit tests, but i'm 100% in favor.

**Comment by MrMallIronmaker** [comment]
Just formed a PR in https://github.com/ManimCommunity/manim/pull/1071 using coverage.py
