### ISSUE TITLE
Make hovering over example text in docs give a button to copy link

### ISSUE THREAD

**Issue by Darylgolden** [ManimCommunity/manim#1087]
## Enhancement proposal
Currently, when hovering over the title of an example scene in docs, a tooltip linking to the example appears. This isn't particularly helpful as it just links the user to something they're already looking at. It would be better if clicking on the tooltip copied the link into the clipboard instead.

**Comment by kilacoda** [comment]
Is it really that difficult to just copy the link from the address bar?

**Comment by Darylgolden** [comment]
It is a really minor issue, but if it can be improved, why not?

**Comment by kolibril13** [comment]
I am partially against this feature because it is not really needed.
In other docs, there is as well only this one tooltip, see e.g. https://scikit-image.org/docs/stable/api/skimage.data.html#astronaut
that changes the URL.
Having 2 tooltips seems to be a bit overkill for me.

**Comment by Darylgolden** [comment]
To clarify, I was suggesting replacing the tooltip entirely.

**Comment by kolibril13** [comment]
Ok, but still I think this is feature is more confusing than beneficial, so in my opinion, we should not implement this.

**Comment by kolibril13** [comment]
I just had a look at some other docs, and they use it the same way like here, see e.g.:
https://scikit-image.org/docs/dev/auto_examples/transform/plot_radon_transform.html
Therefore, I am closing this issue.

**Comment by WampyCakes** [comment]
I think this should be reopened. When the user clicks the little button that adjusts the URL, why not copy it to the clipboard if possible?

**Comment by Darylgolden** [comment]
I agree, but it seems to be standard across most python library docs to have the tooltip be a link rather than copying the link to the user's clipboard. Perhaps it's worth an issue/PR to Sphinx.

**Comment by WampyCakes** [comment]
I think it should still modify the URL, but also additionally copy it to the clipboard. Would you mind making the PR? All it should require is seeing where the functionality for that button is defined and then there's probably already the updated URL stored in a variable (to update the address bar). I'm guessing it's as simple as then copying it.

**Comment by behackl** [comment]
> I think it should still modify the URL, but also additionally copy it to the clipboard. Would you mind making the PR? All it should require is seeing where the functionality for that button is defined and then there's probably already the updated URL stored in a variable (to update the address bar). I'm guessing it's as simple as then copying it.

I fear that it's not quite as simple as that: copying something to the clipboard programmatically is more complicated than one might think in the first moment -- and then there is still the question of UX design: how should the user be notified that whatever they clicked on has been copied to the clipboard?

I'm not saying this is impossible, but I do think that it requires a fair amount of work.

**Comment by WampyCakes** [comment]
The UX question is fair, though not unusual. Regarding copying, isn't it as simple as [something like this](https://www.w3schools.com/howto/howto_js_copy_clipboard.asp)?

**Comment by behackl** [comment]
> The UX question is fair, though not unusual. Regarding copying, isn't it as simple as [something like this](https://www.w3schools.com/howto/howto_js_copy_clipboard.asp)?

The method from the link you are suggesting is [deprecated](https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand). I came in touch with a similar problem like one or two years ago, and it was difficult to ensure consistent behavior across browsers at the time. Things might have improved recently, that's of course possible.

**Comment by WampyCakes** [comment]
Oh, it didn't say that :/ Might still be worth an issue then
