### ISSUE TITLE
Changelog Creation

### ISSUE THREAD

**Issue by jsonvillanueva** [ManimCommunity/manim#1091]
Creating a release in ManimCommunity should be made an easier process. The problem we face now is in manually creating changelogs on time for releases (combination of more PRs made and/or poorly written PR titles). The process should be automatic, requiring no manual intervention at the time of release. In a [recent poll](https://discord.com/channels/581738731934056449/737402086899056690/818213528020058153), there has been slight interest in two automated options. 

These options are suggestions ([towncrier](https://github.com/twisted/towncrier), [python script](https://github.com/numpy/numpy/blob/main/tools/changelog.py)), but beyond the usefulness of a changelog generator, the main issue at hand is to ensure changelogs don't delay the release.

**Comment by naveen521kk** [comment]
I am setting up towncrier for user-facing changelog (it isn't possible to do for this release so, this is from the next release), where PR authors write a change in a file and also bring in the [python script](https://github.com/numpy/numpy/blob/main/tools/changelog.py) for dev facing changelog, (dev facing changelog will not be in docs), finally use something like [invoke](https://www.pyinvoke.org/index.html), where the release can do `invoke changelog` to run towncrier as well as the python script to create changelog.

**Comment by jsonvillanueva** [comment]
I'm currently rewriting contributing.rst (and related files) for `pre-commit`. I'm curious why the need for invoke? Why not just use towncrier to generate the file from the fragments that the PR authors write with `towncrier build`?

**Comment by naveen521kk** [comment]
I would be making a PR adding the python script soon.
