### ISSUE TITLE
Interpolating Mobjects in a way that Transform looks smoother.

### ISSUE THREAD

**Issue by kolibril13** [ManimCommunity/manim#1093]
Sometimes, Transformations executed by `self.play(Transform(a,b))` really do not look very smooth, as you can see for example here (resources to reproduce this video at the bottom):

https://user-images.githubusercontent.com/44469195/110913502-8ee73100-8315-11eb-90e8-70258c5e122c.mp4

So my idea is a function `InterpolateFromTop` that can be used for closed curves to rearrange their points and make the Transform look nicer.
For example like this `a2= InterpolateFromTop(a,200)` which would execute the following:
1. take the Mobject a and find the top point
2. go clockwise on the line and count the length of the curve
3. Redistribute 200 points on this curve, which will be returned as the new Mobject a2

When this is done for Mobject a and Mobject b, I have the theory that it would look much smoother.

# Resources
```py
class ABCD(Scene):
    def construct(self):
        self.camera.background_color= LOGO_WHITE
        br1 = SVGMobject("no3.svg")
        br2 = MathTex(r"\}").set_color(BLACK).scale(4)
        self.play(Transform(br1,br2), run_time=4)
```
Download of the svg:
<a href='https://svgshare.com/s/Uy0' ><img src='https://svgshare.com/i/Uy0.svg' title='' /></a>

**Comment by kolibril13** [comment]
Additional idea:
An external tool, which will load two Mobjects and lets you define regions of the Mobject, e.g. like this:
A script could e.g. look like this:
```py
class ScenePreparation(Scene):
    def construct(self):
        br1 = SVGMobject("no3.svg")
        br2 = MathTex(r"\}").set_color(BLACK).scale(4)
        self.open_interpolator(mobj1= br1, mobj2 = br2)
```
![abcddddd](https://user-images.githubusercontent.com/44469195/110920548-cfe34380-831d-11eb-985b-37c2aaf908b5.png)
and it will print this message, which can then be copied to the main scene.
```py
a2 = InterpaolateMobject(
    a,
    region1=[2, 5],
    region2=[30, 35],
    region3=[50, 55],
    region4=[70, 85],
    region5=[95, 99],
    new_total_points=200,
)
b2 = InterpaolateMobject(
    b,
    region1=[12, 13],
    region2=[33, 39],
    region3=[61, 67],
    region4=[99, 102],
    region5=[109, 130],
    new_total_points=200,
)
```

**Comment by WampyCakes** [comment]
Rather than `InterpolateFromTop`, why not accept a direction like `InterpolateFrom(BLAH, BLAH, DOWN)`?

**Comment by tfglynn** [comment]
I was able to make the transformation look nicer by messing with the Mobjects directly:
```python
import numpy as np
from manim import *
from manim.communitycolors import LOGO_WHITE

class ABCD(Scene):
    def construct(self):
        self.camera.background_color = LOGO_WHITE
        br1 = SVGMobject("no3.svg")
        br2 = MathTex(r"\}").set_color(BLACK).scale(4)

        points = br1.submobjects[0].points
        # If you comment the next line, the "front" of the bracket
        # trades places with the "back".
        points = np.flip(points, axis=0)
        # For this next line, 26 can be replaced with 70, 114, 158, etc.
        # You can add any multiple of 44 because br1 has 44 x 4 = 176 points.
        points = np.roll(points, 26*4, axis=0)
        br1.submobjects[0].points = points

        self.play(Transform(br1,br2), run_time=4)
```

https://user-images.githubusercontent.com/37965944/111562256-e2b5a800-8763-11eb-82e5-9add640f261b.mp4

**Comment by kolibril13** [comment]
Wow, this is a clever idea and looks really really nice!
Maybe we can even add this idea to the docs, to show how mobject points can be shifted

**Comment by kolibril13** [comment]
I've now added a chapter here that covers the idea of flip and roll:
https://github.com/ManimCommunity/manim/pull/1210
