### ISSUE TITLE
ShowIncreasingSubsets does not seem to work

### ISSUE THREAD

**Issue by WasMachtDerBT** [ManimCommunity/manim#1095]
## Description of bug / unexpected behavior
The elements are just statically animated. See
https://docs.manim.community/en/stable/reference/manim.animation.creation.ShowIncreasingSubsets.html

## Expected behavior
The Elements of a VGroup are shown one after another

## How to reproduce the issue
See link

**Comment by MrMallIronmaker** [comment]
Thanks for filing this issue - sorry it fell through the cracks. It does look like it was corrected in commit cdd3ed99 and made it in to the v0.5.0 release (https://docs.manim.community/en/v0.5.0/reference/manim.animation.creation.ShowIncreasingSubsets.html).

Feel free to leave a comment here or reopen the issue if it's still unresolved.
