### ISSUE TITLE
Add Physics Simulation Support in Manim CE

### ISSUE THREAD

**Issue by ArtanisWongWWW** [ManimCommunity/manim#1098]
## Background
Currently, manimce does not have an engine for running physics simulation, and if we want to run such scenes we need to use a lot of updaters. When the simulation is very complicated, it is nearly impossible to do that only by updaters.

## Description of proposed feature

So I propose adding a physics simulation support by integrating Pymunk (a 2D rigid-body simulation library) into manimce. 

## How can the new feature be used?

The new feature can help manimce users create more complicated physics scenes without struggling using many updaters.

## Additional comments

In 3b1b/manim, there was also a PR about adding such support by integrating pymunk into manim, 
https://github.com/3b1b/manim/pull/1184

**Comment by kolibril13** [comment]
Very nice idea! 
This would be a really great addition!
Are you interested in working on this, @ArtanisWongWWW?

**Comment by ArtanisWongWWW** [comment]
Yes but I am busy preparing for the university entrance exam, would like to help after the exam finishes (late May)😃

**Comment by Aathish04** [comment]
I believe that this would work much better as a Plugin than as a part of core manim.

How exactly will this be implemented? Looking at 3b1b#1184 , it seems like it would be enough to simply write some Physics related mobjects based off of Pymunk and simply import them.
Everything that 3b1b#1184 does can be done if the physics simulation part was made into a plugin as well.

**Comment by PhotonSpheres** [comment]
> I believe that this would work much better as a Plugin than as a part of core manim.

I was actually thinking the same thing.

**Comment by GameDungeon** [comment]
I think this needing to be a plugin, means we need to close this issue.

**Comment by Aathish04** [comment]
Fair enough. So long as we're all in agreement that the integration with pymunk should be implemented as a plugin.

**Comment by leotrs** [comment]
AGreed this should be a plugin.
