### ISSUE TITLE
Mobjects add_to_back is missing sanity checks

### ISSUE THREAD

**Issue by AntonBallmaier** [ManimCommunity/manim#1099]
## Description of bug / unexpected behavior
the Mobject.add method contains sanity checks to make sure, no submobject gets added twice and self is not in self.submobjects.
Mobjext.add_to_back is missing this functionality.

## Expected behavior
Adding self should produce a ValueError: Mobject cannot contain self.
Addin a Mobject multiple times should result in it beeing just once in self.submobjects

## How to reproduce the issue
<details><summary>Code for reproducing the problem</summary>

```py
a = Mobject()
b = Line()
a.add_to_back(a)
a.add_to_back(b,b)
print(a.submobjects)
# results in [Mobject, Line, Line]
```

</details>

**Comment by MrMallIronmaker** [comment]
Thanks for the tip! Sorry it took so long for one of us to respond.

If you'd like to tackle this problem, feel free to, and let me know by commenting. In the mean time I'll tag it as a good first issue.
