### ISSUE TITLE
Create a test to certify a clean install

### ISSUE THREAD

**Issue by leotrs** [ManimCommunity/manim#11]
_Originally posted by @eulertour in https://github.com/ManimCommunity/manim/issues/9#issuecomment-631002056_

> Basically something to dry-run a Scene, ensure that the bare minimum to render successfully is actually installed, and give a helpful error like LaTeX/FFmpeg isn't installed, media directory isn't writable, etc.

Having done this, the correct way to install manim would be `pip install manim`, and then `pytest test_install.py`. (Or the equivalent in the testing library that we end up using.)

This would flag issues about system dependencies such as latex, ffmpeg, etc.

**Comment by PgBiel** [comment]
Could probably be automated with travis or something as well

**Comment by huguesdevimeux** [comment]
As @leotrs  pointed out,  we will have to be aware in the tests that Latex is optional. See #11

**Comment by huguesdevimeux** [comment]
Closed since #28 #97 are on this (and more up-to-date)

**Comment by leotrs** [comment]
@huguesdevimeux While this can be done with what we currently have, I don't think this has been _implemented_. To clarify, I meant a "test to certify a clean install" that a user could run after installation, and it would be part of the installation instructions. So the installation instructions would have this as the last instruction: _"Finally, run `some_command` on your terminal. If it finishes without error, then your install of manim is complete. If it shows an error, then please refer to the FAQ/Troubleshooting section"._

So I guess all that's missing in order to get that is documentation.

**Comment by huguesdevimeux** [comment]
@leotrs Oh ok I see, this is a good idea. 
But is your idea to do it with `pytest` ? If yes I think this _will_ be implemented soon.
If not,  I think that just telling the user to run `SquareToCircle` might be enough.
But you're totally right, at least a mention of a such command (potentially with `SquareToCircle`, I don't know) is missing in the `Readme`.

**Comment by eulertour** [comment]
I have to agree with @leotrs that this isn't finished yet, and it would ideally be something done through pytest. It'd be much better to have a command which gives clear error messages and covers as many potential pitfalls as it can than to run SquareToCircle. As an example, the latter wouldn't test latex.

**Comment by naveen521kk** [comment]
Will a *batch/shell* script do? Or it should be done with purest?

**Comment by leotrs** [comment]
@naveen521kk all tests should be done via pytest, as much as possible.

**Comment by huguesdevimeux** [comment]
> @naveen521kk all tests should be done via pytest, as much as possible.

Hmm are you sure about that ? I mean, this test is meant to be run by a standard user, not a contributor. 
I think a shell script is better as there is much more trouble to set up.

What do you think ?

**Comment by leotrs** [comment]
So in the PR I just requested (#324), there are instructions embedded in the installation instructions to certify the installation is clean. For example, after installing latex, it instructs the reader to try it out by executing `latex` on the console. Would this be a poor man's fix for this issue?

**Comment by Aathish04** [comment]
Why can't we ask them to use pytest, like you suggested?

Heck, we could have a script in `/scripts/` install pytest for them, run the tests, make sure they're fine, and uninstall pytest on the way out.

**Comment by leotrs** [comment]
I mean, we can :man_shrugging:

**Comment by leotrs** [comment]
I think this issue went off the rails a little bit. The original idea is to provide a way for _end users_ to test whether or not their installation is clean. They usually don't have pytest installed. I think having a script that ships with the library, or even a subcommand `manim certify-install` is the way to go.

OTOH, the documentation already includes instructions on how to certify the installation of each dependency. I think it's safe to close this issue for now. @Aathish04 ?

**Comment by leotrs** [comment]
I think the current documentation does a good job at guiding the user through the whole installation process.

I think this issue has ran its course.
