### ISSUE TITLE
Manim examples snippets folder

### ISSUE THREAD

**Issue by kolibril13** [ManimCommunity/manim#111]
My idea is to have a snippets folder with lots of manim examples in .md files.
 There are already amazing Tutorials, like [**talkingphysics**](https://talkingphysics.wordpress.com/author/talkingphysics/) , [**Elteoremadebeethoven/AnimationsWithManim**](https://github.com/Elteoremadebeethoven/AnimationsWithManim/blob/master/English/6a_plots_2D/scenes.md),https://eulertour.com/docs/ and the [**manim docs**](https://manim.readthedocs.io/en/latest/about.html).
 The community repo is a place, where all these examples could be provided in a structured and easy to find way.
My first idea is to have folders (just like [**from ToB**](https://github.com/Elteoremadebeethoven/AnimationsWithManim/blob/master/English/6a_plots_2D/scenes.md)), containing:
* .md files with python code, as well as the rendered example
* each .md has a corresponding folder containing its gifs and pngs. 
To get started, I would do this manual, but in the long run it might be also possible to put the results on another website and even automate the .md creation. 
That was e.g. done before by https://manim.flipdot.org/

**Comment by leotrs** [comment]
I'm all for this idea, but I would rather this live inside the `docs` folder so that it can be parsed with sphinx and hosted directly on the future ReadTheDocs website.

**Comment by kolibril13** [comment]
Making a sphinx project sounds good!
Is there anyone here, who already is doing something in this direction?
Meanwhile, I came up with the first .md example:
https://github.com/ManimCommunity/manim/blob/kolibril/example_scenes/snippets/updater/updater.md
and the corresponding folder structure [here](https://github.com/ManimCommunity/manim/tree/kolibril/example_scenes/snippets/updater).

Are there already any details planned for making the docs website?
Cause I would love to start to collect examples.

**Comment by leotrs** [comment]
@PgBiel is in charge of writing guidelines for documentation. I'm not sure anyone is "in charge" of the sphinx project as of right now, though I'd say that is the next big step we need to take.

**Comment by PgBiel** [comment]
I can help with the sphinx project as well since I can just import configuration from a project from earlier this year

**Comment by PgBiel** [comment]
> Cause I would love to start to collect examples.

That'd be awesome!

**Comment by kolibril13** [comment]
Thanks, @PgBiel for your offer!
I just had a look on the sphinx website to get a feeling of how the documentation site could look like.
After looking at a few different themes, I find the [sphinx-modern-theme](https://sphinx-themes.org/html/sphinx-modern-theme/sphinx_modern_theme/basic.html)  appealing for manim.
As the Scene examples will have lots of colors, it would be great to have a monochrome background documentation site, and further, it does not have lots of buttons and the sidebar menu is only visible when you are at the top of the page.
For me, this helps me to get focused on the important context, which is the code and the rendered scene.

**Comment by leotrs** [comment]
I agree the sphinx-modern-theme looks good. However, can we keep the discussion on this issue about the example snippets folder? I think there's a bunch of configs for sphinx that we should discuss in a separate issue.

**Comment by PgBiel** [comment]
it can be a subfolder of `docs`

**Comment by kolibril13** [comment]
A suggestion for the structure:
For each topic a separate folder:
e.g. 
"Running Manim"
"Basic Shapes"
"Text"
"2DPlots"
"3DPlots"
"Using Updater"
"Useful Constructs"
"Basics Example scenes"
"Advanced Example scenes"
But this can be elaborated in the creation process.

Now comes the question, how the examples can be added in a smooth workflow.
Here is my idea:
![image](https://user-images.githubusercontent.com/44469195/83408936-c08cac80-a413-11ea-99c6-347b7263e1d1.png)
So there is one markdown file that has references to the scenes that should be shown and one can add here text to describe the scene. I would say we make a few and long documents because they can be searched very quickly with Crtl+F.
The markdown script in the middle could be called shapes_raw.md and the one one the right shapes_rendered.md
The Compiler Script could be a python script or a makefile, what would you recommend?
And where does the Compiler Script run?
I would prefer locally because then it's possible to get quick feedback about how the result looks like.
Here you can edit the chart:
https://drive.google.com/file/d/1nUy4dbo28Btz2j48uvTtTXOWzkeEaOOr/view?usp=sharing

**Comment by PgBiel** [comment]
See [this](http://web.archive.org/web/20200122130046/https://manim-tb-manual.000webhostapp.com/tree/animations/creation.html) for reference

**Comment by kolibril13** [comment]
@PgBiel that already looks very good!
Can you give me some ideas, of whats the workflow?

**Comment by PgBiel** [comment]
We should find methods that work with mobjects somehow and add sample videos to them

**Comment by leotrs** [comment]
Hi @kolibril13, what's the status of this? If you are not working on this anymore, please kindly close this issue. Thanks.

**Comment by kolibril13** [comment]
Thanks for waking me up on this, @leotrs .
Actually, I would like to start collecting examples and to add them to a nice documented way.
But what is the current status of the sphinx project? 
It would be unfortunate when there is some work doubled.

**Comment by leotrs** [comment]
I just started a basic sphinx setup in the `sphinx-setup` branch, which should be merged later this week. When it's merged, you're welcome to create any folders/documents/examples there!

**Comment by kolibril13** [comment]
Perfect, then I will close this by now! :)

**Comment by leotrs** [comment]
@kolibril13, #249 has been merged ;)
