### ISSUE TITLE
ShowCreation should be deprecated and renamed to Create

### ISSUE THREAD

**Issue by jsonvillanueva** [ManimCommunity/manim#1112]
## Enhancement proposal
Not much of an enhancement but a better name for a command that was discussed (and[ voted on](https://discord.com/channels/581738731934056449/581738732646957057/779498399091130379)) a while back, but never acted on.

## Additional comments
Should be a relatively straightforward PR. It's similar to #1110, except we want to also introduce the new `Create` class and change any instance/mention of `ShowCreation` in the documentation as well.

**Comment by Alexis-Lionel** [comment]
Does look fairly straightforward indeed. I'll see and try to refactor it this evening.

**Comment by Alexis-Lionel** [comment]
Skimmed through the relevant class definitions, but still not sure if I'm correct in my understanding that all that needs to be done is replacing every `ShowCreation` to `Create` using a good old directory-wide recursive find-and-replace. This way all documentation mentions will also be renamed accordingly, from what I understand, so I'll go ahead and try that. Please let me know if I'm missing something.

**Comment by jsonvillanueva** [comment]
> Skimmed through the relevant class definitions, but still not sure if I'm correct in my understanding that all that needs to be done is replacing every `ShowCreation` to `Create` using a good old directory-wide recursive find-and-replace. This way all documentation mentions will also be renamed accordingly, from what I understand, so I'll go ahead and try that. Please let me know if I'm missing something.

Yes, that's pretty much all that is needed (project-wide). But we still need to keep (deprecate) it around for a bit so that people have time to update their existing code to use the new name.

**Comment by Alexis-Lionel** [comment]
Turns out I was completely in the dark regarding what deprecate meant, thanks for the reply! Just to be clear then - I have to:
1. Keep the original `ShowCreation` class definition as is for deprecation purposes
2. Duplicate its functionality into a new `Create`  class 
3. Change every other `ShowCreation` call and mention to `Create` by find-and-replace

Apologies for my incessant questions regarding such a straightforward thing.

**Comment by kilacoda** [comment]
Also, add a warning in `ShowCreation`. See items in the [deprecation project board](https://github.com/manimcommunity/manim/projects/9) for examples on how to do that.

**Comment by Alexis-Lionel** [comment]
Thank you for the advice, @kilacoda! I did include the logger warning in my [PR](https://github.com/ManimCommunity/manim/pull/1124).
