### ISSUE TITLE
GraphScene/coordinate_systems refactoring

### ISSUE THREAD

**Issue by hydrobeam** [ManimCommunity/manim#1141]
## Enhancement proposal

The current graphing logic is a little convoluted and involves lots of code duplication among `Axes`, `GraphScene` and `NumberPlane`. I suggest transferring the bulk of `GraphScene`'s useful methods over to Axes to make the logic clearer. This would also involve switching the current `x_min, x_max` initialization and instead using  `np.array([Minimum, maximum, step size])`, which makes more sense intuitively (and requires altering `ParametricFunction` too). Ultimately, the graphing process would be similar to the upstream version.

The summary of the changes to graphing from the upstream version can be seen here: https://3b1b.github.io/manim/getting_started/whatsnew.html

## Additional comments

This seems like a much needed change since it's currently stalling the documentation for graphing and the implementation of new features.

I am willing to take on this refactoring. It'd mostly be in the same vein as the changes made in the upstream version (linked above), but if someone else has other ideas of how it should be done I'd be happy to hear them out.

**Comment by behackl** [comment]
Thank you for writing this idea up, I fully agree with this proposal. If you are willing to port the changes from 3b1b/manim to the community edition: please go ahead!

I feel there is a lot of potential for simplifying the plotting of graphs; and personally I'd be fine if you approached it as a sort of two-step process: first, extend the capabilities of `Axes`, and then in a second step, `GraphScene` should be deprecated.

**Comment by GameDungeon** [comment]
I chose a horrible time to start writing a graphing library 😃 I do support these changes though, and they would help me with my project.

**Comment by GameDungeon** [comment]
This can be closed now @behackl as it's PR was merged

**Comment by hydrobeam** [comment]
The issue is still ongoing actually as #1472 is active + `GraphScene` has yet to be deprecated

**Comment by GameDungeon** [comment]
I would argue that this issue and what it asks for is complete and the above is a completely different issue, but feel free to keep this open.
