### ISSUE TITLE
Specify FPS from commandline

### ISSUE THREAD

**Issue by WampyCakes** [ManimCommunity/manim#1142]
## Description of proposed feature
You should be able to specify what frame rate to use when rendering from the commandline. Something like `--fps 30`

## How can the new feature be used?
Setting fps without modifying the manim script

**Comment by leotrs** [comment]
Not saying this is a replacement for the requested feature, but you can set FPS independently of quality using a config file.

**Comment by behackl** [comment]
I've always been wondering why the fps couldn't be set from the CLI -- thanks for opening an issue. It should be easy to add a flag; but we shouldn't do so before #1013  is merged.

**Comment by WampyCakes** [comment]
@leotrs The problem is that quality sets both resolution and fps. I think we should be able to use quality flags _and_ also be able to independently set fps and resolution from the commandline. I am in a situation atm where that would be helpful, and as it pertains to rendering, it belongs as an option in the command. You don't always want to have to modify your config or script for quality.

**Comment by leotrs** [comment]
Yeah that's fair. I think in this case it is warranted. However, I would advise against the proliferation of CLI flags in general...

**Comment by jsonvillanueva** [comment]
Agreed, this 

> 
> 
> I've always been wondering why the fps couldn't be set from the CLI -- thanks for opening an issue. It should be easy to add a flag
Agreed it would be easier -- in fact, I've *already* [done work for that](https://github.com/jsonvillanueva/manim/blob/e9c979d401c463bab761a71131f09125b4cf5b7c/manim/cli/render/commands.py#L201-L207) because it didn't make sense to have `--webgl_updater_fps` and not a general fps for each renderer.

**Comment by jsonvillanueva** [comment]
Click isn't in the spirit of freedom with the CLI. It's supposed to standardize the CLI to make intuitive sense with other POSIX compliant CLIs. In some cases, it would be very against Click's design to implement it like Argparse currently does -- so instead I opted to break the CLI's API and do some housekeeping/reorganization. The flags should all be there and if there was a test case written for it, it should still work.

`fps` is one example where it doesn't work and I'd have to write a video test or something to ensure proper functionality in the future

**Comment by jsonvillanueva** [comment]
This is now fixed in Cairo rendering in #1013
