### ISSUE TITLE
Remove background_color commandline flag

### ISSUE THREAD

**Issue by WampyCakes** [ManimCommunity/manim#1143]
## Enhancement proposal
I think that the background_color flag should be removed from manim. It's the odd option in the bunch, and it does not seem like something that belongs there. Colors of every mobject are set in the script, and I think the background color belongs there too.

**Comment by WampyCakes** [comment]
cc @jsonvillanueva this may be of interest to you with your click update

**Comment by jsonvillanueva** [comment]
If there's enough interest, sure; I'm not opposed. I've currently left this in the click PR under the `manim render` subcommands. It's organized under "Render Options".

**Comment by WampyCakes** [comment]
It seems most are in favor of removing it 
![image](https://user-images.githubusercontent.com/9156604/112043885-8665d600-8b1f-11eb-9096-87d9c5fde649.png)
