### ISSUE TITLE
JSONFormatter.format() & Mobject.set() Rename

### ISSUE THREAD

**Issue by GameDungeon** [ManimCommunity/manim#1148]
Format and Set are both python builtins and having class functions named after them violates Flake8 A003. If we do implement flake, this need to be fixed.

**Comment by leotrs** [comment]
Note we don't *need* to change this as A003 can simply be turned off for these classes.

**Comment by GameDungeon** [comment]
I guess you make a point, I'll do that for now. It still is bad practice though.

**Comment by leotrs** [comment]
> It still is bad practice though.

I don't mean to sound contrarian :sweat_smile: , but I think that naming methods with keywords is not necessarily/automatically bad practice.

We should have a conversation about whether we can find better names for these methods though, and change them *if* we find better alternatives. Any suggestions? I'm particularly hesitant about changing `set` :thinking:

**Comment by GameDungeon** [comment]
format can be changed to format_text
set can be set_attr

**Comment by GameDungeon** [comment]
On this issue. It can either be closed or I'll create a pull. Need input

**Comment by friedkeenan** [comment]
I really don't think `Mobject.set` should be renamed, and furthermore `str.format` is a thing and that's obviously just fine, so I don't think our `format` method needs to be renamed either, so I'm closing this
