### ISSUE TITLE
Graph Scene 293 Invalid Escape

### ISSUE THREAD

**Issue by GameDungeon** [ManimCommunity/manim#1149]
Both testing and Flake8 says that (Graph Scene.py Ln 293) "y_axis_label=r"Concentration [\%]" has an invalid escape sequence. The issue is that this is needed for docs to display properly.

**Comment by kilacoda** [comment]
It's not invalid though? Seems like it's just being escaped to a latex macro (i.e. `\\%` to `\%`) within a raw string. Also, the line you're referring to seems to be line 293 in the current master, which is weird...
https://github.com/ManimCommunity/manim/blob/30f00d546b18d7684240bd7ef030a4a8919babf1/manim/scene/graph_scene.py#L293-L294

**Comment by GameDungeon** [comment]
I have a slightly modified source that explains the line difference. I know it's not invalid, but both tests and Flake say it is.

**Comment by kilacoda** [comment]
While I don't particularly care about what Flake8 says, tests on my end from the latest `master` don't show me any such warning?

**Comment by GameDungeon** [comment]
It's strange. Sometimes it triggers and sometimes it does not. It seems almost random.
