### ISSUE TITLE
Mobject is_off_screen method doesn't work

### ISSUE THREAD

**Issue by la6ki** [ManimCommunity/manim#1158]
## Description of bug / unexpected behavior

I have objects which are clearly off screen but calling obj.is_off_screen() returns False. Looking at the source code, I think the problem is a conceptual bug:

```py
    def is_off_screen(self):
        if self.get_left()[0] > FRAME_X_RADIUS:
            return True
        if self.get_right()[0] < -FRAME_X_RADIUS:
            return True
        if self.get_bottom()[1] > FRAME_Y_RADIUS:
            return True
        if self.get_top()[1] < -FRAME_Y_RADIUS:
            return True
        return False
```

The conditions in the left/bottom tests should be swapped with those for right/top, respectively, because get_left() and get_bottom() return negative numbers. 

```py
    def is_off_screen(self):
        if self.get_left()[0] < -FRAME_X_RADIUS:
            return True
        if self.get_right()[0] > FRAME_X_RADIUS:
            return True
        if self.get_bottom()[1] < -FRAME_Y_RADIUS:
            return True
        if self.get_top()[1] > FRAME_Y_RADIUS:
            return True
        return False
```

Or they should just be replaced with absolute value tests. I hope I'm not missing anything...

**Comment by behackl** [comment]
I'm not sure I see a problem with the current implementation. An mobject is declared to be off screen, if its left border is past the right end of the frame, or if its right border is past the left end of the frame; or if its upper border is past the lower end of the screen; or if its lower border is past the upper end of the frame.

Your suggestion, on the other hand, would return `True` as soon as any part of the mobjects bounding box is outside of the frame.

Can you give some more details about your situation and why you think the implementation is incorrect?

**Comment by la6ki** [comment]
Seems like I misunderstood the intent of this method. I was assuming it should return True if any part of the object is off screen. This is a useful thing to know, since it can be used for things like adaptive scaling in case your object gets too big and doesn't fit inside the screen. The way it's currently implemented, it will only return True if no part of the object is visible.

**Comment by behackl** [comment]
I think it would make sense to have another method which checks whether a mobject is fully contained in the screen (maybe `is_fully_on_screen`?) which can be used for purposes like this.

(In addition, the current `is_off_screen` method should also be better documented.)

Something like that would be a good feature for a first contribution, in case you are interested. :-)

**Comment by la6ki** [comment]
Yeah, your suggestion makes sense. I'm going to try to make some time for it soon (haven't done any PRs on Github yet and need to figure out the procedure). Thanks for your suggestion (and the clarification on the original issue)!

**Comment by la6ki** [comment]
By the way, do you think it would be too dirty if we parameterize this method, instead of creating a new one?

**Comment by behackl** [comment]
> Yeah, your suggestion makes sense. I'm going to try to make some time for it soon (haven't done any PRs on Github yet and need to figure out the procedure). Thanks for your suggestion (and the clarification on the original issue)!

Sounds good. In case you need any support, feel free to use this issue -- or simply ask in one of the text channels for development on our [Discord](https://discord.gg/mMRrZQW).

> By the way, do you think it would be too dirty if we parameterize this method, instead of creating a new one?

That could also be a valid approach, sure. I guess it is less a question of actual implementation, but more of proper documentation.
