### ISSUE TITLE
OpenGL get_bounding_box_point function does not work as expected

### ISSUE THREAD

**Issue by TRoboto** [ManimCommunity/manim#1162]
## Description of bug / unexpected behavior

The OpenGL [get_bounding_box_point](https://github.com/ManimCommunity/manim/blob/39351b02026350d5bd3adaccd2718a2e76253afe/manim/mobject/opengl_mobject.py#L985) function does not change its value when the object is moving.

Playing this scene with OpenGL renderer produces the following video.

```py
class OpenGLTest(Scene):
    def construct(self):
        squares = OpenGLVGroup()
        for _ in range(9):
            squares.add(OpenGLSquare(1, stroke_opacity=0).set_fill(WHITE, 0.5))
        squares.arrange_in_grid(3, 3, buff=0)

        def line():
            print(squares.get_corner(UL))
            return OpenGLLine(ORIGIN, squares.get_corner(UL))

        self.add(always_redraw(line))
        self.play(squares.animate.to_edge(UP))
        self.play(squares.animate.to_edge(DR))
        self.play(squares.animate.shift(LEFT * 10))
        self.wait()
```

https://user-images.githubusercontent.com/11293921/112231169-dc7d6b00-8c3e-11eb-8779-6bc1f09fb6a3.mp4

## Expected behavior
When I play the same scene with Cairo renderer, it works like so:

https://user-images.githubusercontent.com/11293921/112231250-0a62af80-8c3f-11eb-9916-cc3b8c5cd78b.mp4

Cairo scene
```py
class Test(Scene):
    def construct(self):
        squares = VGroup()
        for _ in range(9):
            squares.add(Square(1, stroke_opacity=0).set_fill(WHITE, 0.5))
        squares.arrange_in_grid(3, 3, buff=0)

        def line():
            print(squares.get_corner(UL))
            return Line(ORIGIN, squares.get_corner(UL))

        self.add(always_redraw(line))
        self.play(squares.animate.to_edge(UP))
        self.play(squares.animate.to_edge(DR))
        self.play(squares.animate.shift(LEFT * 10))
        self.wait()
```

**Comment by MrMallIronmaker** [comment]
Reopened because the PR was reverted in #1191

**Comment by eulertour** [comment]
The proper solution to this is to update the bounding box when the change is made. `get_critical_point` was intentionally replaced upstream for performance reasons.

There's an attribute `works_on_bounding_box` floating around `mobject.py` to keep track of this, but since the `.animate` syntax uses a generic transform it probably doesn't keep track of what animations can and can't preserve the bounding box.

Deciding on a proper solution is sort of tricky since it requires tracking all changes to the points array. We should see how/if this is handled in the upstream version and go from there.

**Comment by Darylgolden** [comment]
Revisiting, and the problem appears to have resolved itself:

```py
from manim import *
from manim.opengl import *
class Test(Scene):
    def construct(self):
        squares = OpenGLVGroup()
        for _ in range(9):
            squares.add(Square(1, stroke_opacity=0).set_fill(WHITE, 0.5))
        squares.arrange_in_grid(3, 3, buff=0)

        def line():
            print(squares.get_corner(UL))
            return Line(ORIGIN, squares.get_corner(UL))

        self.add(always_redraw(line))
        self.play(squares.animate.to_edge(UP))
        self.play(squares.animate.to_edge(DR))
        self.play(squares.animate.shift(LEFT * 10))
        self.wait()
```

produces

https://user-images.githubusercontent.com/9102529/150104602-4e271ef8-a5f1-48db-b7de-69b5ff33aeb2.mp4
