### ISSUE TITLE
Using z-order to define layer for Mobjects

### ISSUE THREAD

**Issue by kolibril13** [ManimCommunity/manim#117]
Matplotlib has a very nice method to define in which layer objects are shown on the screen with a parameter `zorder`.
![image](https://user-images.githubusercontent.com/44469195/71835887-05095b80-30b3-11ea-9a68-7da6253c6312.png) 
When working with manim, it's sometimes a little tricky to get the layers right, so what about an implementation, where you can write:
```py
d=Dot()
self.add(d, zorder= 1)
```
Furthermore, there could be defaults like:
* Dots at the first layer
* Text & Equations at the second layer
* Shapes on the third layer
* Functions and graphs on the fourth layer.

When I posted this text to the discord server, @eulertour wrote:
> I don't think it would require anything more than sorting scene.mobjects by z-index before rendering each frame
and since its already possible to assign arbitrary attributes to mobjects it may end up being a one-line change

**Comment by leotrs** [comment]
Sounds good to me.

Relatedly, I was under the impression that `mobject.get_z_index_reference_point` had something to do with this, but now I'm not sure what it's supposed to be doing.

**Comment by Tony031218** [comment]
See:
https://github.com/manim-kindergarten/manim/commit/dde65b49a61144f4615040031d687038f07e7b64
https://github.com/manim-kindergarten/manim/commit/94675142995b8e9212ec9b784dee1c1da8fb3cc1

just sort `self.mobjects`

**Comment by eulertour** [comment]
The name feels a little opaque to me. Maybe it's because I've worked with CSS some, but I find z_order or z_index to make more sense. Thoughts?

**Comment by PgBiel** [comment]
I'd preder `z_index` as well
