### ISSUE TITLE
Issue in handling "scale" transform during SVG processing

### ISSUE THREAD

**Issue by ksachdeva** [ManimCommunity/manim#1171]
## Description of bug / unexpected behavior

This report describes the issue first discussed (in passing) in this issue https://github.com/ManimCommunity/manim/pull/1159

It seems that after parsing the usage of scale transform is not working properly.

## Expected behavior
The displayed image in a manim scene should be "similar" to the SVG

## How to reproduce the issue

<details><summary>Code for reproducing the problem</summary>

The test SVG can be obtained from here -
https://gist.github.com/ksachdeva/86131136e4b9ab240f69534e90618472

```py
class TestScaleTransform(bb.Scene):
    def construct(self):
        s = bb.SVGMobject(
            '<path_to_the_above_mentioned_svg>'
        )
        self.add(s)
        self.wait()
```

```bash
manim <path_to_script_containing_above_scene> -ps -c white
```

This code will fail/crash on manim 0.4 or even master. 

You first have to include my changes introduced in this pull request - 
https://github.com/ManimCommunity/manim/pull/1159

</details>

## Additional media files
<details><summary>Images/GIFs</summary>

After including the changes from https://github.com/ManimCommunity/manim/pull/1159 that will enable the parsing of transforms to work you would see the output as -

![TestMultipleTransform_ManimCE_v0 4 0](https://user-images.githubusercontent.com/127006/112515688-7d197b00-8d64-11eb-9323-55909e827f31.png)

As you can see that the coordinates of this test SVG are not put in the proper position i.e. the generated image is not similar to that of SVG. 

</details>

## System specifications

<details><summary>System Details</summary>

- OS (with version, e.g Windows 10 v2004 or macOS 10.15 (Catalina)):macOS 11.2..3
- RAM:
- Python version (`python/py/python3 --version`): 3.8
- Installed modules (provide output from `pip list`):
```
PASTE HERE
```
</details>

<details><summary>LaTeX details</summary>

+ LaTeX distribution (e.g. TeX Live 2020):
+ Installed LaTeX packages:

</details>

<details><summary>FFMPEG</summary>

Output of `ffmpeg -version`:

```
PASTE HERE
```
</details>

**Comment by Kiran-Raj-Dev** [comment]
Closing as it was fixed in #1159
