### ISSUE TITLE
Missing key code (e.g. Class Create) when pip install manim 0.4.0

### ISSUE THREAD

**Issue by zheng95z** [ManimCommunity/manim#1175]
#### Preliminaries

- [x] I have followed the latest version of the
      [installation instructions](https://docs.manim.community/en/latest/installation.html).
- [x] I have checked the [troubleshooting page](https://docs.manim.community/en/latest/installation/troubleshooting.html) and my problem is either not mentioned there,
      or the solution given there does not help.

## Description of error

I followed the instruction in [installation instructions](https://docs.manim.community/en/latest/installation.html). 
After `pip install manim`, I runed the example code below:
```python
from manim import *
class SquareToCircle(Scene):
    def construct(self):
        circle = Circle()                   # create a circle
        circle.set_fill(PINK, opacity=0.5)  # set the color and transparency
        self.play(Create(circle))     # show the circle on screen
```

And then there was an error:
```powershell
Traceback (most recent call last):
  File "c:\python39\lib\site-packages\manim\__main__.py", line 95, in main
    scene.render()
  File "c:\python39\lib\site-packages\manim\scene\scene.py", line 169, in render
    self.construct()
  File "D:\manim_projects\project\scene.py", line 6, in construct
    self.play(Create(circle))     # show the circle on screen
NameError: name 'Create' is not defined
```

Then I went to `creation.py`, trying to find the `Create`. And there is none:
```python
__all__ = [
    "ShowPartial",
    "ShowCreation",
    "Uncreate",
    "DrawBorderThenFill",
    "Write",
    "ShowIncreasingSubsets",
    "AddTextLetterByLetter",
    "ShowSubmobjectsOneByOne",
    "AddTextWordByWord",
]
```

So I changed the `Create` to `ShowCreation`, and it just worked.

I also tried to `pip install` from this repo, then the `Create` worked fine.

## Installation logs

<details><summary>Terminal output</summary>

```powershell
Traceback (most recent call last):
  File "c:\python39\lib\site-packages\manim\__main__.py", line 95, in main
    scene.render()
  File "c:\python39\lib\site-packages\manim\scene\scene.py", line 169, in render
    self.construct()
  File "D:\manim_projects\project\scene.py", line 6, in construct
    self.play(Create(circle))     # show the circle on screen
NameError: name 'Create' is not defined
```

</details>

## System specifications

<details><summary>System Details</summary>

- OS (with version, e.g Windows 10 v2004 or macOS 10.15 (Catalina)): Windows 10

**Comment by naveen521kk** [comment]
It's because you are referring to a unreleased version, in the docs.

**Comment by behackl** [comment]
Indeed, you should always consult the documentation directly associated to the version you are using: `latest` only applies to the current development version.

Can you remember which link lead you to the latest version of the documentation?

**Comment by zheng95z** [comment]
> Indeed, you should always consult the documentation directly associated to the version you are using: `latest` only applies to the current development version.
> 
> Can you remember which link lead you to the latest version of the documentation?

Sorry for my mistake! It's Line 42 in README.md (just Below 'Installation') in this repo that led me to latest doc.

**Comment by Darylgolden** [comment]
The installation instructions link in the issue template also links to the latest version.

**Comment by naveen521kk** [comment]
I think we should change latest to something like `devel` and `latest` should point to the latest release.

**Comment by behackl** [comment]
> > Indeed, you should always consult the documentation directly associated to the version you are using: `latest` only applies to the current development version.
> > Can you remember which link lead you to the latest version of the documentation?
> 
> Sorry for my mistake! It's Line 42 in README.md (just Below 'Installation') in this repo that led me to latest doc.

No, don't worry -- it's our job to make navigating the documentation easy. Maybe this situation can be improved a bit.

Anyhow, as this issue should be resolved, I'll close it. Feel free to keep commenting if you have further remarks or troubles; I'll reopen it if it makes sense.

**Comment by leoncyao** [comment]
> I think we should change `latest` to something like `devel` and `latest` should point to the latest release.

Yea I just followed the first one on the repo and had this problem, kinda confusing

**Comment by Kiran-Raj-Dev** [comment]
Hmm, the link in the repo points to `stable` and not `latest`.
What problem were you facing?
