### ISSUE TITLE
Origin Tick Mark Persistent

### ISSUE THREAD

**Issue by alembcke** [ManimCommunity/manim#1180]
## Description of bug / unexpected behavior
When creating ThreeDAxes I want to start the x-axis at 5 (or any other positive number), but the tick mark for 0 is always part of the axes animation.  I have gone through the source code and tried all the configuration variables (leftmost_tick, center_point, exclude_zero_from_default_numbers, etc), but nothing works.

## Expected behavior
The expected behavior is that there should be some way to have an axis without a tick mark for zero.  I think the issue is with the file manim/coordinate_systems.py, in the get_lines_parallel_to_axis method where it starts drawing from zero:

<details><summary>get_lines_parallel_to_axis</summary>

```py
    ranges = (
            np.arange(0, axis_perpendicular_to.x_max, step),
            np.arange(0, axis_perpendicular_to.x_min, -step),
        )
        for inputs in ranges:
            for k, x in enumerate(inputs):
                new_line = line.copy()
                new_line.shift(unit_vector_axis_perp_to * x)
                if k % ratio_faded_lines == 0:
                    lines1.add(new_line)
                else:
                    lines2.add(new_line)
        return lines1, lines2</summary>
```

</details>

I could be wrong, but when going through the source code it appears to me that this starts drawing tick marks from the origin.

## How to reproduce the issue
Here is some code which causes the issue:

<details><summary>Sample code</summary>

```py
from manim import *
import numpy as np

class ThreeDGraph(ThreeDScene):
    def construct(self):
        self.set_camera_orientation(phi=80 * DEGREES, theta=-80 * DEGREES) 
        
        axes = ThreeDAxes(
                x_min=2, 
                x_axis_config={
                    'leftmost_tick': 2,
                    'include_tip': False},
                num_axis_pieces=1                    
                )
        
        def flat_surface(u, v):                   
                x = u
                y = v                     
                z = 0                                            
                return np.array([x, y, z])

        surface = ParametricSurface(    
                flat_surface,
                resolution=(32, 32),                      
                v_min=-2,
                v_max=+2,
                u_min=+2,
                u_max=+4, 
        ) 
        
        stuff = VGroup(axes.x_axis, surface)
        stuff.shift(LEFT * 2)
        
        self.play(Write(axes))
        self.play(Write(surface))      
        self.wait(3)
```

</details>

## Additional media files

A GIF of the output of the code above.  Note the tick mark to the left, which marks 0 even though the x-axis should start at 2.

<details><summary>Images/GIFs</summary>

![ThreeDGraph_ManimCE_v0 4 0](https://user-images.githubusercontent.com/79891353/112741409-70e71680-8f3a-11eb-84fd-573f1c372662.gif)

</details>

Edit:  Updated the sample code to be complete in showing the issue.

Edit 2:  Added GIF

**Comment by MrMallIronmaker** [comment]
Hello and welcome to Github!

Thanks for filing this issue. I agree that the tick shouldn't be displayed in that case.

Do you have an interest in making that change to the code yourself? I think your guess for to the root of the problem is a good one.

**Comment by alembcke** [comment]
Sure, I would be happy to make the change.  It will give me a reason to get setup to contribute to Manim, which will likely lead to me getting more involved with this project.

**Comment by MrMallIronmaker** [comment]
Great! Discord (https://discord.gg/mMRrZQW) is probably the best place for help and tips; or feel free to post on this issue for now.

**Comment by alembcke** [comment]
So I went through the instructions on how to install Manim for contribution and made the change and.....it didn't change anything.  Hours of plugging away to find out why and it turns out that I had overlooked one variable that defaults to 0:
`numbers_with_elongated_ticks = [0]`

Changing that variable to the x_min fixes the issue completely.  This code does the trick:

```py
from manim import *
import numpy as np

class ThreeDGraph(ThreeDScene):
    def construct(self):
        self.set_camera_orientation(phi=80 * DEGREES, theta=-80 * DEGREES)
        
        axes = ThreeDAxes(
                x_min=2,
                x_axis_config={
                    'leftmost_tick': 2,
                    'numbers_with_elongated_ticks': [2],
                    'include_tip': False}
                )
        
        def flat_surface(u, v):
                x = u
                y = v
                z = 0
                return np.array([x, y, z])

        surface = ParametricSurface(
                flat_surface,
                resolution=(32, 32),
                v_min=-2,
                v_max=+2,
                u_min=+2,
                u_max=+4,
        )
        
        stuff = VGroup(axes.x_axis, surface)
        stuff.shift(LEFT * 2)
        
        self.play(Write(axes))
        self.play(Write(surface))
        self.wait(3)
```

The result is this output:


https://user-images.githubusercontent.com/79891353/112777692-ae5da980-8ff7-11eb-91fb-075c40679115.mp4

Explaining all of this so that the next person to experience this issue can find this answer and save themselves hours of needless effort.  Closing the bug report.

**Comment by MrMallIronmaker** [comment]
Good eye. However, just because it's possible to fix it with the arguments we have now, I don't think it's good to leave it as is. I think it makes more sense for the NumberLine constructor to check if `numbers_with_elongated_ticks` passed in are within a range that makes sense. If you'd like, you can make that change.

**Comment by alembcke** [comment]
Sure, I will try to make that change in the coming days and will update this thread.

**Comment by alembcke** [comment]
I have made the change to check whether `numbers_with_elongated_ticks` are on the number line or not, by adding this code to manim/mobject/number_line.py:

```py
        self.numbers_with_elongated_ticks = []
        for number in numbers_with_elongated_ticks:
            if number > self.x_min and number < self.x_max:
                self.numbers_with_elongated_ticks.append(number)
```

Replacing the line that just assumes the tick marks are on the number line:

```py
        self.numbers_with_elongated_ticks = numbers_with_elongated_ticks
```

This is a video from before the change:

https://user-images.githubusercontent.com/79891353/113535704-0ca30300-9589-11eb-8c1c-097ddbd0ee25.mp4

And this is a video made after the change:

https://user-images.githubusercontent.com/79891353/113535721-13317a80-9589-11eb-9318-a0f00f6f6996.mp4

The only issue is that now the graph_scene test fails, but the diff doesn't show the difference:

![TestFailure](https://user-images.githubusercontent.com/79891353/113535523-81297200-9588-11eb-90ba-e62e1603e6d2.png)

@MrMallIronmaker can you see the difference, or know what I can do to pinpoint the issue?

**Comment by MrMallIronmaker** [comment]
Do you have a branch I can check out to see what might be happening?

**Comment by alembcke** [comment]
I forked the manim code and made the change to the master branch of the fork here:  https://github.com/alembcke/manim.git

**Comment by alembcke** [comment]
@MrMallIronmaker , I have done some testing by modifying the test code and viewing it as a video:

```py
from manim import *

class PlotFunctions(GraphScene):
    def __init__(self, **kwargs):
        GraphScene.__init__(
            self,
            graph_origin=ORIGIN,
            function_color=RED,
            axes_color=GREEN,
            x_labeled_nums=range(-10, 12, 2),
            x_axis_config = {'numbers_with_elongated_ticks': [-12, -5, -2, 6, 9, 13]},
            **kwargs
        )

    def construct(self):
        self.x_min = -10
        self.x_max = 10.3
        self.y_min = -1.5
        self.y_max = 1.5

        constants.TEX_TEMPLATE = TexTemplate()
        self.setup_axes()
        f = self.get_graph(lambda x: x ** 2)

        self.play(Animation(f))
        self.wait(3)
```

Note the values for `numbers_with_elongated_ticks`.  This code produces this video, where you can clearly see that the elongated tick marks are there for the numbers on the number line and not there for the ones that fall outside of `x_min` and `x_max`:


https://user-images.githubusercontent.com/79891353/113656022-d54b5980-964f-11eb-9b1d-498fc2cf93d7.mp4


So I am not sure what is going on with the test failing.

**Comment by MrMallIronmaker** [comment]
Correct! You didn't change the behavior for 0.

It turns out the difference in the test is with the elongated tick at -10. The test expects it to be elongated, but the code you provided doesn't elongate it.

Really, the graphical unit tester should have made this easily visible - but as it currently goes, it draws green over red, but it should draw red pixels over green. I made a change in the graphical testing code to locate the issue, so I'll submit a PR myself soon.

**Comment by alembcke** [comment]
Thanks @MrMallIronmaker .  And my code wasn't correct as I did `<` instead of `<=`, and likewise for `>` and `>=`.  I made that change and pytest runs smoothly, as do visual inspections.  I created a draft pull request here [#1305](https://github.com/ManimCommunity/manim/pull/1305).  Is there anything missing in the draft or that needs further explanation?
