### ISSUE TITLE
Brace Annotation with text cause list index out of range 

### ISSUE THREAD

**Issue by Sunlight-qwq** [ManimCommunity/manim#1181]
## Description of bug / unexpected behavior

`Windows 10, Python 3.9, Manim 4.0`
`python.exe -m manim P:\Manim\community\Example\BraceAnnatation.py -s`
When I run the example "BraceAnnotation" which is copied from the documentation, it produce an error "list index out of range"

## Expected behavior

I expect to add text below the brace (like what is shown in the documentation), but it cause to an error

## How to reproduce the issue

`b1text = b1.get_text("Horizontal distance")`
Any nonempty string in the bracket will cause this error.
However, with an empty string, the file can output successfully, with no text under the brace.
Additionally, tex will not produce this error.
<details><summary>Code for reproducing the problem</summary>

```py
from manim import *


class BraceAnnotation(Scene):
    def construct(self):
        dot = Dot([-2, -1, 0])
        dot2 = Dot([2, 1, 0])
        line = Line(dot.get_center(), dot2.get_center()).set_color(ORANGE)
        b1 = Brace(line)
        b1text = b1.get_text("Horizontal distance")
        b2 = Brace(line, direction=line.copy().rotate(PI / 2).get_unit_vector())
        b2text = b2.get_tex("x-x_1")
        self.add(line, dot, dot2, b1, b2, b1text, b2text)
        self.wait()
```

</details>

## Additional media files

<details><summary>Images/GIFs</summary>

With empty string:
![BraceAnnotation_ManimCE_v0.4.0.png](https://i.loli.net/2021/03/27/CMcjLwnZT6dBVRm.png)

</details>

## Logs
<details><summary>Terminal output</summary>

My manim is installed in virtual environment, which is at P:\manim\community\.venv.

```
Traceback (most recent call last):
  File "P:\Manim\community\.venv\lib\site-packages\manim\__main__.py", line 95, in main
    scene.render()
  File "P:\Manim\community\.venv\lib\site-packages\manim\scene\scene.py", line 169, in render
    self.construct()
  File "P:\Manim\community\Example\BraceAnnatation.py", line 10, in construct
    b1text = b1.get_text("Horizontal distance")
  File "P:\Manim\community\.venv\lib\site-packages\manim\mobject\svg\brace.py", line 98, in get_text
    text_mob = Tex(*text)
  File "P:\Manim\community\.venv\lib\site-packages\manim\mobject\svg\tex_mobject.py", line 506, in __init__
    MathTex.__init__(
  File "P:\Manim\community\.venv\lib\site-packages\manim\mobject\svg\tex_mobject.py", line 392, in __init__
    self.break_up_by_substrings()
  File "P:\Manim\community\.venv\lib\site-packages\manim\mobject\svg\tex_mobject.py", line 434, in break_up_by_substrings
    sub_tex_mob.move_to(self.submobjects[last_submob_index], RIGHT)
IndexError: list index out of range
```

</details>

## System specifications

<details><summary>System Details</summary>

- Windows 10 2004 build 19041
- Python version: Python 3.9

</details>

<details><summary>LaTeX details</summary>

</details>

<details><summary>FFMPEG</summary>

</details>

**Comment by MrMallIronmaker** [comment]
Thanks for submitting this report.

Unfortunately, I'm not able to replicate this problem on Ubuntu 18.04.5 / Manim 0.4.0 (or master) / Python 3.7.

Are there any warnings before the error? 

@ManimCommunity/windows are any of you able to replicate it?

**Comment by Darylgolden** [comment]
I'm using Windows, can't replicate.

**Comment by naveen521kk** [comment]
I am also using Windows, manim-latex choco package, can't replicate it.

**Comment by behackl** [comment]
Hello!

This is a well-known issue, please try the following: Open the MiKTeX console, install the `cm-super` LaTeX package, then delete the media directory that can be found where you ran manim, and then try to compile the example again.

**Comment by behackl** [comment]
I'm closing this issue for now, please report if the solution above does not work for you.
