### ISSUE TITLE
Command line "version" option

### ISSUE THREAD

**Issue by ManuelMendozaUPM** [ManimCommunity/manim#1182]
it seems it is not possible to get the version of manim you are running. I think it would be great to add this option

**Comment by behackl** [comment]
Hello!

I think since `v0.2.0` or so, `manim --version` does print the installed version of manim. If that doesn't work for you, you are either on a older version -- or don't have the community version installed.

**Comment by WampyCakes** [comment]
Going off what behackl said, depending on your installation method, you can alternatively check the version via `pip list`

**Comment by WampyCakes** [comment]
Closing as this functionality does already exist in manim. Feel free to reach out if you have further issues with it
