### ISSUE TITLE
no attribute 'camera_frame'

### ISSUE THREAD

**Issue by stevenwalton** [ManimCommunity/manim#1189]
When trying to reproduce the [Valentines Tweet](https://github.com/ManimCommunity/manim-tweets/blob/main/2021_02_14_valentines.py) I'm getting the error `AttributeError 'ValentineScene' object has no attribute 'camera_frame'`. I asked on the community discord and found another user that was getting the same error, leading me to believe that it might be an update that broke the code. To reproduce just run the tweet code.

**Comment by behackl** [comment]
`camera_frame` has actually been removed with `v0.4.0` in #1000. Instead, `self.camera.frame` should work.

**Comment by stevenwalton** [comment]
Thanks! That seems to resolve the problem. (Now hopefully this is googleable for others that face the issue)
