### ISSUE TITLE
New default: Pull request from ManimCommunity to ManimCommunity

### ISSUE THREAD

**Issue by kolibril13** [ManimCommunity/manim#119]
At the moment, when you do a pull request, GitHub wants to merge it into 3b1b s original repo by default:
![abc](https://user-images.githubusercontent.com/44469195/83349135-bcd52900-a332-11ea-802c-304ad697f515.png)
Maybe this can be changed so that the manim community master branch is the place where manim community subbranches are merged into, otherwise, it can happen that one accidently tries to merge a community subbranch to 3b1bs master branch (happend to me)

**Comment by leotrs** [comment]
I looked into this before but the fix is not simple: https://stackoverflow.com/questions/31573448/how-to-set-default-fork-for-pull-requests

**Comment by PgBiel** [comment]
Yeah... not kinda feasible

**Comment by kolibril13** [comment]
ok!
