### ISSUE TITLE
New idea for method: `get_middle_point`

### ISSUE THREAD

**Issue by kolibril13** [ManimCommunity/manim#1198]
Currently, there are a few methods to get positions like  `get_start`, `get_end` and `get_center` To get the middle of a line, it would be very convenient to have a method `get_middle_point` as well. It could look something like this:
```py
class Test(Scene):
    def construct(self):
        theta_tracker=ValueTracker(1)
        line1 = Line( LEFT, RIGHT)
        line2 = Line( LEFT, RIGHT ).rotate(theta_tracker.get_value()*DEGREES)

        a= Angle(line1, line2, radius=0.5, other_angle=False)
        def get_middle_point():
            po= a.get_points()
            return po[int(len(po)/2)]
        print(a.get_start())
        print(a.get_end())
        print(a.get_center())
        print(get_middle_point())
```
```console
[0.5 0.  0. ]
[0.49992385 0.0087262  0.        ]
[0.49996192 0.0043631  0.        ]
[0.49998096 0.00436327 0.        ]
```

**Comment by friedkeenan** [comment]
`mob.point_from_proportion(0.5)` could probably be used for this, right? Though for VMobject `point_from_proportion` works a little awkwardly because it doesn't take into account the length of each bezier curve..

**Comment by kolibril13** [comment]
And I just realized: For parametric functions, that would not work eighter because there is no equal spacing:
```py
class Test(Scene):
    def func(self, t):
        return np.array((np.cos(t), np.sin(t), 0))*(1-t*0.05)

    def construct(self):
        a = ParametricFunction(self.func, t_min=0, t_max = 2*TAU, fill_opacity=0).set_color(RED)
        self.add(a.scale(3))
        def get_middle_point():
            po= a.get_points()
            return po[int(len(po)/2)]
        print(a.get_start())
        print(a.get_end())
        print(a.get_center())
        print(get_middle_point())
        print(a.point_from_proportion(0.5))
        self.add(Dot(a.get_center()).set_color(GREEN))
        self.add(Dot(get_middle_point()).set_color(YELLOW).scale(3))
        self.add(Dot(a.point_from_proportion(0.5)).set_color(BLUE).scale(2))
        self.add(*[Dot(x) for x in a.get_points()[::200]])
```
![image](https://user-images.githubusercontent.com/44469195/113067500-bdda1f80-91bc-11eb-8d62-944832166af9.png)

**Comment by kolibril13** [comment]
So my idea right now:
adding the function
```py
def get_middle_point(self):
    return self.point_from_proportion(0.5)
```
to `mobject.py`

**Comment by friedkeenan** [comment]
I think a better name would be `get_middle` to be in line with `get_start` etc.

**Comment by jsonvillanueva** [comment]
I'm personally fond of `get_midpoint`.

**Comment by kolibril13** [comment]
nice, I've now opened a pr:
See #1234

**Comment by behackl** [comment]
Don't preemptively close issues as long as the corresponding PRs are not merged. (Issues can be closed automatically when merging the associated PR.
