### ISSUE TITLE
Create a Quickstart guide

### ISSUE THREAD

**Issue by leotrs** [ManimCommunity/manim#120]
Quickstart guides are intended to provide a minimal example end-to-end. For us this means a precise, hand-holding, not-detailed tutorial from the moment manim is installed to the moment where the user can render and watch their first scene. Quickstart guides are usually not longer than 1 or 2 pages.

**Comment by leotrs** [comment]
This will have to go on `docs/` somewhere and be hosted on the ReadTheDocs site. @ManimCommunity/docs do we have anyone who is in charge of the sphinx project?

**Comment by PgBiel** [comment]
I can certainly help with it

**Comment by kolibril13** [comment]
I can help with the example too!
@PgBiel : When are you planning to start the sphinx project?

**Comment by PgBiel** [comment]
> @PgBiel : When are you planning to start the sphinx project?

The first step is to work on docs. We should work on sphinx config & stuffs either during or after it

**Comment by Tony031218** [comment]
I am thinking about whether the documentation and getting started manual should be stored in this repo.  
Perhaps it would be better to open a repo specifically for ManimCommunity to place the documentation, and give a link in the manim README.

**Comment by leotrs** [comment]
@Tony031218 this is a good question. I think the strongest argument for having the quickstart/tutorial and other documentation documents inside the manim repo is that we will also be generating documentation from docstrings. So by keeping all docstrings as well as quickstart/tutorial in the same repo it will be much easier to build everything in a single sphinx command.

**Comment by Tony031218** [comment]
Yes, but you may be able to use .gitignore to ignore the docs folder in the manim repo and then link to a new repo in the docs folder.
Putting the docs folder in the manim repo may be a little messy, but it is indeed the most convenient way now.

**Comment by leotrs** [comment]
This was created by #249
