### ISSUE TITLE
Update/Clarify our Documentation Guidelines

### ISSUE THREAD

**Issue by jsonvillanueva** [ManimCommunity/manim#1203]
The documentation guidelines that have been transferred from the GitHub Wiki to the sphinx docs are outdated with our practices in some respects. In particular, @behackl has noted in #1137:

- https://github.com/ManimCommunity/manim/pull/1137#discussion_r604287102
- https://github.com/ManimCommunity/manim/pull/1137#discussion_r604287886
- https://github.com/ManimCommunity/manim/pull/1137#discussion_r604289847

The clearer we can be on how we expect contributions regarding documentation, the easier reviews on documentation will go.

**Comment by Nikhil0504** [comment]
I think this can be closed now.
