### ISSUE TITLE
Remove Cairo Renderer

### ISSUE THREAD

**Issue by GameDungeon** [ManimCommunity/manim#1205]
Remove Cairo Renderer and Replace it with OpenGL. Checklist before this can happen (Comment below to add to it):

- [ ] Add More Test For OpenGL
- [ ] Svg Support
- [ ] Text Support
    - [ ] LaTeX Support
- [ ] Graph Support

**Comment by huguesdevimeux** [comment]
I think we can decline the most of the tests to also used the OpenGL renderer. 

(For the non graphical one, at least)
