### ISSUE TITLE
Seemingly broken creation animations

### ISSUE THREAD

**Issue by WampyCakes** [ManimCommunity/manim#1221]
## Description of bug / unexpected behavior
It seems to me that the following animations are broken. Rather than doing what the class name suggests, they all just add the mobjects passed to them to the scene.

- `AddIncreasingSubsets`
- `AddTextLetterByLetter`
- `ShowSubmobjectsOneByOne`
- `AddTextWordByWord` - this one is known to be broken per the comment in manim's code

Likely, `AddIncreasingSubsets` is broken and caused the others to break.

## Additional comments
It's _possible_ that I am trying to use these wrong, but I'm 90% sure that isn't the case. It would be helpful if someone could confirm that they're broken.

**Comment by friedkeenan** [comment]
https://docs.manim.community/en/latest/reference/manim.animation.creation.html#module-manim.animation.creation does indeed show the animations as broken

**Comment by WampyCakes** [comment]
I compared against there before and also tried using a few of them with the Manimator bot as a control. We really need a way to test animations 😬
