### ISSUE TITLE
Remove argparse from setup.py

### ISSUE THREAD

**Issue by naveen521kk** [ManimCommunity/manim#123]
https://github.com/ManimCommunity/manim/blob/cf8c5b9938abafba9f6c2c1aeff9e15c8edbfdd1/setup.py#L17
Remove `argparse` from setup.py as it is a default library and need not be mentioned in `requirements.txt` and `setup.py`.

**Comment by leotrs** [comment]
Agreed, it should be removed. @naveen521kk would you like to submit a PR?
