### ISSUE TITLE
Inform Manim Community Users when using an out of date version

### ISSUE THREAD

**Issue by jsonvillanueva** [ManimCommunity/manim#1230]
## Enhancement proposal

This came up in a discussion on [discord](https://discord.com/channels/581738731934056449/581738732646957057/827411746318843924), it would be nice to let users know when a new released version is available -- or just that they're no longer up to date with the most recent tagged/stable version -- just like pip does.

I'm not sure how this would be implemented for versions prior to v0.5.0, but ideally this warning/message would be made on each execution of the `manim` commmand. Additionally, the user should be able to silence this warning/label via the config files if they really don't want to update for whatever reason.

**Comment by naveen521kk** [comment]
I am marking it as a good first issue as this is simple to implement.

**Comment by RickyC0626** [comment]
I'd like to give this a shot.

**Comment by naveen521kk** [comment]
assigned you @RickyC0626
