### ISSUE TITLE
Add contributing Guidelines

### ISSUE THREAD

**Issue by naveen521kk** [ManimCommunity/manim#124]
As this is a fork and normally Github thinks that the user contributes to the main repo, this cause issue for the contributors. 
Add the article from StackOverFlow about contributing to a fork like the below one in the ReadMe File for helping out the contributors.
https://stackoverflow.com/questions/14383212/git-pulling-a-branch-from-another-repository

**Comment by leotrs** [comment]
This sounds good to me. @naveen521kk would you like to submit a PR?

**Comment by kolibril13** [comment]
My contribution workflow is at the moment the following:
1. pull and merge updates from manim community
2. make a new branch
3. write code and commit
4. when in the manim community was updated in the meantime, go back to the master branch and pull and merge updates from manim community.
5. merge the master in the development branch
6. push the development branch
7 make a pull request to master
This works quite well, but do you have some improvements to this workflow?

**Comment by leotrs** [comment]
@kolibril13 see what is being recommended at #127
