### ISSUE TITLE
Removing CairoText

### ISSUE THREAD

**Issue by naveen521kk** [ManimCommunity/manim#1250]
It's long that Pango is working with no or very few bugs and it's time to remove `CairoText`. We have deprecated it long back and it should be fine to remove it in the next release. See https://github.com/ManimCommunity/manim/projects/9#card-56126541

## Additional comments
Marking it as a good first issue.

**Comment by erik-tastepe** [comment]
I can take this if it hasn't been addressed yet. I'm assuming this is referring to the `CairoText` class inside `manim.mobject.svg.text_mobject`?

**Comment by naveen521kk** [comment]
Yes. I'm assigning you!
