### ISSUE TITLE
Polar version of `NumberPlane`

### ISSUE THREAD

**Issue by ralphieraccoon** [ManimCommunity/manim#1264]
## Description of proposed feature
While it's possible to create a polar grid using `prepare_for_nonlinear_transform` and `apply_function` on a `NumberPlane`, then adding an extra `Line` to split it into quadrants, it's not the most elegant method. Considering how commonly a polar grid might be used, I think it would be worth having something purpose built.

## How can the new feature be used?
As a `NumberPlane` with polar gridlines.

## Additional comments
I'm willing to have a crack at this myself (unless someone else already is) but I was wondering how best to manage the class hierarchy. Would it be best to have it as a subclass of `Axes` or `NumberPlane`? Looking at the code I think I can work with both, though I'm not completely sure.

**Comment by MrMallIronmaker** [comment]
I think this is a good feature to add.

Perhaps the best option is adding a feature to `NumberPlane` where some transform can be passed in at creation time (if there isn't something already) and then `PolarPlane` (if that's the best name...) is a subclass of `NumberPlane` with the right defaults.

Then it's also a lot easier for someone else to merely specify the transform function for a different transform, and the mess of `prepare_for_nonlinear_transform` and `apply_function` is applied under the hood rather than in the user's script.

**Comment by ralphieraccoon** [comment]
Thanks, I'll subclass it as such. I thought this might be the answer since I can't imagine many people would use a polar number plane with complex numbers.

I like `PolarPlane` for the alliteration, I guess `PolarNumberPlane` is more descriptive, whatever is preferred.

Unfortunately, a simple transformation of `NumberGrid` doesn't result in the desired outcome. The "faded" lines are fine, but the y axis collapses into nothing, as would be expected. What I think I'd like to do is have an `apply_function` that only works on the faded lines and keeps the axes intact, as most polar plots look.

```python
class PolarTransform(Scene):

    def construct(self):

        pplane = NumberPlane(y_max=PI, y_min=0, x_line_frequency=PI/4)
        pplane.prepare_for_nonlinear_transform()
        self.play(pplane.animate.apply_function(lambda p: np.array([p[0] * np.sin(p[1]), p[0] * np.cos(p[1]), 0])))
        self.wait(1)
```

https://user-images.githubusercontent.com/25301457/114269543-b0fccd80-99ff-11eb-9556-0e6cf3bbbd4e.mp4

Also as can be seen from the video, any transition animation is going to look a bit "weird" (it looks even stranger when `x > π`). I'm wondering if there's a better way to animate a transformation between cartesian and polar, but so far I haven't thought of anything.

**Comment by MrMallIronmaker** [comment]
I see more of the complexity now. 

Considering the common parameterization of the polar plane as $(r, \theta)$, would it make sense to have the unit circle as the second 'axis'? This design would claim the axes exist to indicate the parameterization of the space.

The transform would have to take that into account - either the theta-axis would have to be at r=1, or the transform would have to add one to whatever value becomes r. I'm not sure if that breaks some other kind of logic like positioning points, but it would give the right visual effect.

If you wantted to add a horizontal and vertical axis to polar background lines, then perhaps it'd be best served by creating a PolarPlane with hidden axes (so you only get background lines), and then adding in an Axes object. (Is that possible?)

At this stage these are more suggestions, let me know what might work / might not work about that approach.
