### ISSUE TITLE
Flake8 chapter in docs

### ISSUE THREAD

**Issue by kolibril13** [ManimCommunity/manim#1271]
As we enforce currently Flake8 as code formatting, I think there should be a bit of information on why we chose flake 8 and how it can be applied (e.g. a recommended IDE plugin for pycharm or VS Code) and that it is also now part of the pre-commit.
At the moment, the docs do not mention it at all :https://docs.manim.community/en/latest/contributing/development.html#for-first-time-contributors
EDIT:
here are two good video resources that could be embedded into the docs:

For the general purpose of flake8:
https://www.youtube.com/watch?v=TDUf93vqq3g
For VS Code:
https://www.youtube.com/watch?v=eMIxokGhFHM
I actually don't know how to copyright situation of embedding youtube videos on websites is.

**Comment by Nikhil0504** [comment]
“Code style: We use the code style imposed by Black. The pipeline makes sure that the (Python) files changed in your pull request also adhere to this code style. If this step of the pipeline fails, fix your code style by running black <file or directory> to automatically format your files.”

This is given in the documentation. So that could be the reason for not mentioning flake8

**Comment by jsonvillanueva** [comment]
Also:
> This will ensure during development that each of your commits are properly formatted against our linter and formatters, black, flake8, and isort.

I don't think we need a chapter saying; however, I am open to changing the line @Nikhil0504 mentioned where instead of specifically mentioning black, it's changed to mention isort, flake8, and black.

**Comment by Nikhil0504** [comment]
Ok I checked the document again, and found out the we have mention it in **For first-time contributors** but under **Polishing Changes and Submitting a Pull Request** only `black` was mentioned and a code line for how to use it, so I was thinking of including the usage of `flake8` and `isort` also (but the suggested one would still be `black`).
