### ISSUE TITLE
flake8 check by pre-commit.ci and flake8 check in our normal pipeline don't yield same result

### ISSUE THREAD

**Issue by behackl** [ManimCommunity/manim#1273]
## Description of bug / unexpected behavior

As requested by @kolibril13, I have enabled pre-commit.ci for this repository. It seems that the flake8 check we run usually in our pipeline, and the check run by pre-commit.ci are configured differently: compare

https://results.pre-commit.ci/run/github/265122478/1617749086.1i_sQPmmTjeknEIW3BXU8A

with

https://github.com/ManimCommunity/manim/pull/1262/checks?check_run_id=2282701850

Also, on a related note: if we have the status check by pre-commit.ci, do we still need to run our custom back/isort/flake8 pipelines, or could they be removed then? CC @naveen521kk.

## Expected behavior

`flake8` should be run with the same configuration in both cases, except if there is a good reason not to do so.

**Comment by RickyC0626** [comment]
Maybe the old flake pipeline checks this file, while the new one doesn't.
https://github.com/ManimCommunity/manim/blob/4331817879dfee1c5b273a28e7329c913c9e53f5/.flake8#L1-L24

**Comment by naveen521kk** [comment]
There is a simple difference between the two. Github Actions checks only for the `manim` folder and pre-commit checks for all the python files.

**Comment by kolibril13** [comment]
Ok, I just looked at other prs,
isort is only checking the changes: https://github.com/ManimCommunity/manim/pull/1275/commits/3e47251a8d764b578b666b91d2ad0a0a832c52c8isort is black is only checking the changes:
https://github.com/ManimCommunity/manim/pull/1122/commits/58b4f9508f2cd4a7f44a9eb0a045bac1ed4abf38
so it is only flake8 that considers all files.
I will investigate this.

**Comment by behackl** [comment]
It's fine when pre-commit.ci checks all files, I don't think that we have to change that. But we need a PR fixing the failing files.

**Comment by kolibril13** [comment]
https://github.com/ManimCommunity/manim/pull/1276
