### ISSUE TITLE
"There are no scenes inside that module"

### ISSUE THREAD

**Issue by Eeno29** [ManimCommunity/manim#1287]
Whenever I try to run manim, no matter what class I am using, I always get the error "There are no scenes inside that module". I even tried running code only containing the exact example code here "SquaretoCircle." Still doesn't work.

My exact error on terminal:
```
Media will be written to /Users/admin/Documents/media/. You can change this behavior with the --media_dir flag.
There are no scenes inside that module
```

**Comment by behackl** [comment]
The message indicates that you are mixing different versions of manim.

1) How did you install manim?
2) What are the contents of the file you are trying to render?
3) What command are you using to render the file?

**Comment by Eeno29** [comment]
1. I installed following the instructions in the community page https://docs.manim.community/en/v0.4.0/installation/mac.html
2. I am rendering this simple code:
```
from manim import *


class SquareToCircle(Scene):
    def construct(self):
        circle = Circle()
        square = Square()
        square.flip(RIGHT)
        square.rotate(-3 * TAU / 8)
        circle.set_fill(PINK, opacity=0.5)

        self.play(Create(square))
        self.play(Transform(square, circle))
        self.play(FadeOut(square))
```
3. The command I am using is `manim test.py SquaretoCircle -pql`

I think I know what you are talking about different versions of manim. I downloaded manimlib as well as manim, but now whenever I delete it I get a different error

**Comment by behackl** [comment]
> I think I know what you are talking about different versions of manim. I downloaded manimlib as well as manim, but now whenever I delete it I get a different error

Can you run `which manim` in your terminal? I think `manim` corresponding to `manimlib` is called, which would make the scene not work.

You should be able to run manim as well by running `python -m manim -p -ql test.py SquareToCircle` (replace `python` by whatever version of python you have installed manim to on your machine), that should definitely choose the correct version.

**Comment by Eeno29** [comment]
It worked!

Thank you very much :)
