### ISSUE TITLE
Get rid of docker

### ISSUE THREAD

**Issue by leotrs** [ManimCommunity/manim#13]
Docker was intended to give users a full environment ready to run manim with: ffmpeg, cairo, latex, the right python, and the up to date code, among other things.

However, it ended up being too technical for most people. Also, it seems like most of the installation problems are coming from cairo, which may be replaced soon. Docker doesn't seem to be the right fix for that.

**Comment by PgBiel** [comment]
Should probably remain as an option, but not mandatory by any means

**Comment by leotrs** [comment]
Yes, totally fair! Never really used Docker this way though, so would we still need a dockerfile at the top level directory even if it is optional?

**Comment by eulertour** [comment]
I'd prefer to get rid of it completely, so that we aren't expected to maintain it.

**Comment by PgBiel** [comment]
> I'd prefer to get rid of it completely, so that we aren't expected to maintain it.

Fair; it could probably be a separate repo/project maintained by whoever is willing to keep it alive

**Comment by Kreijstal** [comment]
bring back docker, it works wonder when you have a completely clean enviroment and you want to set up manim without bothering to configure your machine everytime you want to install it.

**Comment by PhilipEnchin** [comment]
I realize I'm late to the party here, but rather than opening a new issue...

I'd like to see Docker back too, for the same reason as @Kreijstal.

I found using Docker with 3b1b's manim (with the provided `Dockerfile` and `docker-compose.yml`) to be a bit troublesome, but I've written my own that are more straightforward (to me) so I can get away with using Manim without installing anything at all on my system (with the exception of Docker and Docker Compose, of course).

The command I'm using differs from that of a system-installed Manim only slightly:
```bash
docker-compose run manim basic.py SquareToCircle -l
```

Additionally, I've been able to switch easily between `pip`-installed `manimce` and `manimlib`, as well as a community version built straight from this repo. Using Docker lets me do this without having to uninstall one version before installing the other, and I'm able to build all of them with a single `docker-compose build` command, without having to bother with installing all the dependencies as I go.

I'm curious as to what was making it "too technical for most people" (@leotrs), and whether those difficulties can be overcome so as to make it an easy enough option for people to use without frustration.

**Comment by leotrs** [comment]
> I realize I'm late to the party here, but rather than opening a new issue...

Thanks for bringing this back to our attention :) This is the community version after all, so if the community as a whole decides to go with docker, we want to know about it.

What it really comes down to right now is this: right now we are focusing on refactoring the library so it is more robust and welcoming to newcomers. The former is being achieved by adding lots of tests and refactoring a lot of classes, and the latter is being achieved by adding documentation in the form of docstrings and tutorials. We are also adding new features little by little but the main effort is in the former two.

I'm not sure if this is the right time to implement and support a dockerfile. Having one more way to install manim means one more thing that we have to support and one more thing that can go wrong and one more set of instructions/documentations/troubleshooting and so on. It's one more thing to balance, and I'm not sure it is worth it, or that we have time to do that. There are alternative ways of installing manim that are being worked on right now, see #165 for example.

Having said that, if a member of the community wanted to implement and support a dockerfile consistently and reliably, we would be happy to onboard them. Note however that the words "consistently" and "reliably" are doing a lot of work here... we can't really implement it once only to abandon it and then we will go back to the situation that originated this issue where we have a useless dockerfile sitting around. So if someone wanted to dedicate time and really commit to maintaining that, I think we could make the chance, though my personal stance is that it is not the right time to do it. I think I would be more open to that in the future. Perhaps after a v1.0 release.

> Additionally, I've been able to switch easily between `pip`-installed `manimce` and `manimlib`, as well as a community version built straight from this repo. Using Docker lets me do this without having to uninstall one version before installing the other, and I'm able to build all of them with a single `docker-compose build` command, without having to bother with installing all the dependencies as I go.

This is also possible with virtual environments, no? Currently, 3b1b manim and manim-ce use the same system dependencies, and even most of the same python dependencies. So switching virtual environments would also allow you to use them side by side.

> I'm curious as to what was making it "too technical for most people" (@leotrs), and whether those difficulties can be overcome so as to make it an easy enough option for people to use without frustration.

The point is that manim tends to attract people who do not have a ton of programming background. A lot of people watch 3b1b videos and are eager to learn how to use manim. And this is awesome, they are of course welcome to! The problem is that asking to install and run docker to someone with minimal knowledge of programming/python/etc is a bit too much in general. There is no problem with asking programmers to to this of course.

**Comment by naveen521kk** [comment]
Not to mention, I have create a chocolatey package to install Manim. 
https://chocolatey.org/packages/manim

**Comment by leotrs** [comment]
Yes! I was looking that up as I was writing my response above and I couldn't find it :sweat_smile: (BTW, that package is not in the installation instructions https://manimce.readthedocs.io/en/latest/installation.html)

**Comment by naveen521kk** [comment]
> BTW, that package is not in the installation instructions
I will soon add it. Maybe make a new issue and assign.

**Comment by PhilipEnchin** [comment]
> Having said that, if a member of the community wanted to implement and support a dockerfile consistently and reliably, we would be happy to onboard them. Note however that the words "consistently" and "reliably" are doing a lot of work here... we can't really implement it once only to abandon it and then we will go back to the situation that originated this issue where we have a useless dockerfile sitting around. So if someone wanted to dedicate time and really commit to maintaining that, I think we could make the chance, though my personal stance is that it is not the right time to do it. I think I would be more open to that in the future. Perhaps after a v1.0 release.
>
> ...
> 
> The point is that manim tends to attract people who do not have a ton of programming background. A lot of people watch 3b1b videos and are eager to learn how to use manim. And this is awesome, they are of course welcome to! The problem is that asking to install and run docker to someone with minimal knowledge of programming/python/etc is a bit too much in general. There is no problem with asking programmers to to this of course.


I've been using Manim with Docker since I got started here (I had trouble installing the system dependencies), so I'm inclined to say that I'd be able to (consistently and reliably) volunteer my time for that. Following the pattern in 3b1b's repo, I've made a few Dockerfiles for easy access to different Manim versions, and a YAML for Docker Compose to facilitate building and using them all. I have what I think is a super straightforward process for building and using the containers to crunch Manim/Python code into video. No system-level installs required (other than Docker and Docker Compose...).

It needs a wee bit of work still to be more friendly to users that aren't myself, but I'll plan on putting together a PR with this stuff eventually. I know Docker may not be everyone's cup of tea, but for me at least, it's been a nice option, and it might be for some others too. Personally, I think a dev container for VS Code would be pretty nifty :)

**Comment by leotrs** [comment]
> I'm inclined to say that I'd be able to (consistently and reliably) volunteer my time for that

This is very good news indeed! There is one more thing that bothers me: the fact that only _one_ person from the community is willing and able to maintain the docker installation puts too much pressure on that person. What happens if, say, a year from now you stop being able to volunteer your time? In that case, none of the other current devs will be able to keep supporting Docker, and users that depended on it will lose access to the software. So it's not in general a good idea to have a single point of failure. We would much rather have at least two people committed to it.

But then again, I don't have final say here, the community does. So if others chime in and there seems to be a consensus about supporting Docker, then by all means let's do it. @eulertour thoughts?

> Personally, I think a dev container for VS Code would be pretty nifty :)

I'm unfamiliar with VS Code. What does a manim containar for manim for VS Code mean?

**Comment by PhilipEnchin** [comment]
> > I'm inclined to say that I'd be able to (consistently and reliably) volunteer my time for that
> 
> This is very good news indeed! There is one more thing that bothers me: the fact that only _one_ person from the community is willing and able to maintain the docker installation puts too much pressure on that person.

...only one _so far_! The interest in using Docker seems to be sparse... But perhaps @Kreijstal would be interested in helping here? (Please??)

> > Personally, I think a dev container for VS Code would be pretty nifty :)
> 
> I'm unfamiliar with VS Code. What does a manim containar for manim for VS Code mean?

I'm relatively new to Docker, and haven't played with this particular VS Code feature much yet, but my understanding is that someone could create a configuration file such that when opening the repo in VS Code, the editor would take care of installing all the dependencies, the library itself, and any other useful extensions as defined by the container creator (such as a linting tool). Also, this would all exist in a Docker container (and not on the user's system) which the user wouldn't actually need to directly deal with.

The appeal here for me is that it would provide a way for a new Manim user to get up and running without having to follow any installation instructions at all really. Just open it up and (after a few minutes) start coding.

**Comment by leotrs** [comment]
That's interesting. I'm not a VS Code user but it does look useful. @naveen521kk thoughts?

**Comment by naveen521kk** [comment]
> That's interesting. I'm not a VS Code user but it does look useful. 

Neither I, I really don't know about that.

**Comment by leotrs** [comment]
@ManimCommunity/core anyone work on VS Code?

**Comment by kilacoda** [comment]
Me. I don't use docker though.

**Comment by kilacoda** [comment]
https://code.visualstudio.com/docs/containers/overview

Just putting this here in case anybody finds it useful.

**Comment by Kreijstal** [comment]
the point of docker is that you don't have to keep up with dependency hell, so that would make easier to use, not harder, besides, the dockerfile is like 10 lines?

**Comment by behackl** [comment]
@Kreijstal The issue is outdated, we are in the process of making docker a documented option to use the community version of manim with, see https://hub.docker.com/r/manimcommunity/manim
