### ISSUE TITLE
Boolean Operations for VMobjetcs

### ISSUE THREAD

**Issue by AntonBallmaier** [ManimCommunity/manim#1310]
## Description of proposed feature
[Boolean operations](https://inkscape-manuals.readthedocs.io/en/latest/boolean-operations.html) (Union, Difference, Intersection) are an essential part of vector graphics. 

## How can the new feature be used?
The feature could be used as follows:
```
Union(Circle(), Square())
Difference(Circle(), Square())
Intersection(Circle(), Square)
```

## Additional comments
Without external libraries this is far to hard to implement. One might take a look at [livarot](http://livarot.sourceforge.net/), a C++
 library used by [inkscape](https://gitlab.com/inkscape/inkscape/-/blob/master/src/path/path-boolop.cpp) for this purpose.

**Comment by huguesdevimeux** [comment]
That seems intersting. Given that the mobjects are all bezier curves, it shouldn't be hard to implement if we have the right algorithm for splitting bezier curves along intersections. 

Nevertheless, I don't see any case where this could be useful for the average user. Do you have an idea?

**Comment by AntonBallmaier** [comment]
Many a bit more complex shapes could be easily created with this feature.
I myself have come across multiple situations where this feature would have helped a lot: Imagine trying to highlight sections of a Venn diagram... Another a bit more exotic one is trying to build a free space diagram (frechet distance) where I would have needed to cut ellipses with squares.

**Comment by WampyCakes** [comment]
Yeah I really like this idea. This is common in graphical graphics software

**Comment by Nikhil0504** [comment]
Maybe we could try something like this

[https://github.com/typemytype/booleanOperations](url)

This person has these operations written in python, but he hasn’t updated in a while and if we use it we might need to make a lot of changes for it.

**Comment by AntonBallmaier** [comment]
...your link is broken, here is a working one :)
https://github.com/typemytype/booleanOperations

**Comment by AntonBallmaier** [comment]
Here is a proposal on how the interface of this feature could be structured:

```py
class VMobject(Mobject):

    #somewhere in the VMobject class:
    def intersect(
        self,
        *vmobjects: VMobject,
    ) -> VMobject:
        """Intersect the mobject with others.

        Changes the shape of the mobject to it's intersection with all the given mobjects.
        This will remove this shape entirely if not all given mobjects overlap at some points.

        Returns
        -------
        :class:`VMobject`
            Returns self.
        """
        self.become(Union(self, *vmobjects))
        # or something similar. Should definitely use the corresponding class.

    #analogous for unite() and subtract()
``` 

And in a new module `manim.mobject.boolean_ops`:
```py
class Union(VMobject):
    def __init__(self, *vmobjects:VMobject, **kwargs):
        if len(vmobjects) < 2:
            raise ValueError("Requires at least two VMobjects to unite.")
        super().__init__(**kwargs)
        self.become(vmobjects[0].copy())
        self.remove(*self.submobjects)
        for mob in vmobjects:
            pass # TODO implement

 #analogous for classes Intersection and Difference
``` 
This module could also contain all the needed helper functions. These dont need to be exported from the module.

I also thought quite a bit about how to work with submobjects. First I thought It would be a good idea to use use the following two optional boolean keyword parameters to the `VMobject` methods:

- `apply_to_submobjects=False` => Whether to apply this opearation to own submobjetcs
- `include_parameter_submobjects=False` => Whether to use submobjetcs of given mobjetcs as shapes for the intersection.

However, I couldn't think of any scenario where I would use True for any of these flags. Therefor I don't think we should add them.

Please let me hear what you think about this :slightly_smiling_face:

**Comment by Nikhil0504** [comment]
Can’t we just make a general function for all the operations together and then make a class for segregating the types?

**Comment by Nikhil0504** [comment]
I was trying something from that booleanOperations thing but it didn't work

```python
from manim import *
from booleanOperations import BooleanOperationManager

manager = BooleanOperationManager()


class Test(Scene):
    def construct(self):
        s = Square(color=WHITE)
        t = Triangle(color=WHITE).shift(UP)
        self.add(s)
        self.add(t)
        result = manager.union(s, t)
        result = Mobject(result)
        self.remove(s, t)
        self.add(result)
        print(result)
```
Output:
![Test_ManimCE_v0 5 0](https://user-images.githubusercontent.com/34582615/115324523-a84a8b00-a1a7-11eb-9a7c-000010acf11a.png)

**Comment by AntonBallmaier** [comment]
> Can’t we just make a general function for all the operations together and then make a class for segregating the types?

I don't think it is a good idea to bundle all of the code, just to separate it somewhere else.

**Comment by AntonBallmaier** [comment]
> I was trying something from that booleanOperations thing but it didn't work

Manims Mobjects don't just simply match the format the `BooleanOperationManager` uses - There is definitly a bit more code required...

**Comment by Darylgolden** [comment]
Done!
