### ISSUE TITLE
Fix performance issues based on the new implementation of `point_from_proportion`

### ISSUE THREAD

**Issue by AntonBallmaier** [ManimCommunity/manim#1314]
## Enhancement proposal
Since #1274 the method `point_from_proportion` has linear run time in the number of points on the curve. This change most noticeably affects the run time of `get_arc_length`, which in turn uses a linear amount of calls to `point_from_proportion`. Linked to this are a few other performance problems, which I want to fix.

## Additional comments
I noticed this problem when trying to render a `StreamLines` object, which took a few seconds PER LINE (and contained roughly 1000 lines...). Basically, `StreamLines` with `color_by_arc_length=True` isn't usable at the moment.

**Comment by friedkeenan** [comment]
`get_arc_length` could be changed to get the length in a similar way as `point_from_proportion` does which would probably help, but I'm not sure how `point_from_proportion` could be changed to not be O(n) while preserving taking curve length into account

**Comment by friedkeenan** [comment]
Oh that's basically what you did in your PR, sorry. Let me review that
