### ISSUE TITLE
Coloring subexpressions in Tex Objects

### ISSUE THREAD

**Issue by nioate** [ManimCommunity/manim#1317]
## Description of proposed feature

I was trying to create a formula like $\sqrt{x+y}$ with e.g. "x" using color=RED, "y" using color=BLUE.

Without sqrt, this is no problem:
`t=Tex("$x$","$+$","$y$"); t[0].set_color(RED); t[2].set_color(BLUE)`

However, trying<br>
`t=Tex("$\\sqrt{$","$x$","$+$","$y}$")`
<br>results in TeX error messages, probably because each part has to be TeX-compiled by itself.

## Additional comments

Probably this would require some major change of the way Tex-Objects are converted to images. But maybe some solution can be found using the \color command?

**Comment by MrMallIronmaker** [comment]
The current recommended workaround is to have an unsplit tex mobject and then use `index_labels` (currently an undocumented debug function) and coloring the particular submobject using its index.

Let me know if that makes sense; I can't provide a example atm because I'm on my phone.

**Comment by nioate** [comment]
MrMallIronmaker, that sounds useful. However, I cannot find `index_labels` in the source code (neither in `Tex` nor in its superclasses) and therefore I don't know how to use it. I am using the community version 0.4.0 - maybe that was added later?

**Comment by cobordism** [comment]
> I was trying to create a formula like $\sqrt{x+y}$ with e.g. "x" using color=RED, "y" using color=BLUE.

You can try 
```
t = Tex("$\sqrt{x+y}$") ; t[0][1].set_color(RED) ; t[0][3].set_color(BLUE)
```

> t=Tex("$\\sqrt{$","$x$","$+$","$y}$")
> results in TeX error messages, probably because each part has to be TeX-compiled by itself.

Your analysis is correct. This would try to compile just `$\sqrt{$` on its own which inevitably fails.

**Comment by nioate** [comment]
Great, that solves my problem. Only the sqrt seems to consist of 2 parts, so I have to use t[0][2] and t[0][4].

**Comment by cobordism** [comment]
> Great, that solves my problem. Only the sqrt seems to consist of 2 parts, so I have to use t[0][2] and t[0][4].

ah yes. I remember it's two parts... and this is indeed typical.. a lot of trial[2] and[7] error[2] involved[0][4] :)
