### ISSUE TITLE
The global config object is mean

### ISSUE THREAD

**Issue by Peilonrayz** [ManimCommunity/manim#1318]
Hey, I think you have a typo in the docs;

> The global `config` object is mean to be the single source of truth for all config options. 
> —Configuration, [The ManimConfig class](https://docs.manim.community/en/stable/tutorials/configuration.html#the-manimconfig-class)

> The global `config` object is meant to be the single source of truth for all config options.

**Comment by huguesdevimeux** [comment]
Good catch ! 

Do You mind doing a PR ?

**Comment by kilacoda** [comment]
Here's the file to be edited btw: https://github.com/ManimCommunity/manim/edit/master/docs/source/tutorials/configuration.rst

**Comment by Peilonrayz** [comment]
Thanks @kilacoda. Yeah I'll open a PR in a minute
