### ISSUE TITLE
What typehint should coordinates have?

### ISSUE THREAD

**Issue by kolibril13** [ManimCommunity/manim#1337]
For example `Dot(point = [1,2,3])` has the coordinates  [1,2,3].
But what type hint should these coordinates have?
There are currently two coexisting strategies in recent prs:
1. Union[np.ndarray, List]
2. Sequence[float]

What do you think is the best approach here?

Here is a script to test the behaviour with mypy:

```python
from typing import Union, List, Sequence

import numpy as np  # type: ignore


def f(x:Union[np.ndarray, List]):
    print(x)

def g(x:List):
    print(x)
def h(x:Sequence[float]):
    print(x)

good1 = [1,2,3]
good2 = np.array([1,2,3])
bad1 = (1,2,3)
bad2 = range(1,100)

f(good1)
g(good1)
h(good1)

f(good2)
g(good2)
h(good2)

f(bad1)
g(bad1)
h(bad1)

f(bad2)
g(bad2)
h(bad2)

import os
from pathlib import Path
if __name__ == "__main__":
    script_name = f"{Path(__file__).resolve()}"
    os.system(f"mypy {script_name}")
```
```terminal
basic.py:28: error: Argument 1 to "g" has incompatible type "Tuple[int, int, int]"; expected "List[Any]"
basic.py:32: error: Argument 1 to "g" has incompatible type "range"; expected "List[Any]"
```

**Comment by cobordism** [comment]
Going by
https://docs.python.org/3/library/collections.abc.html
A Sequence is anything with 
`__getitem__, __len__,__contains__, __iter__, __reversed__, index, count`

Some points to consider:
 - If we use `Sequence`, we don't need to worry about whether it comes from a list or from a numpy array.
 - If we use `Sequence[float]` and `Sequence[Int]` we can be more precise about the contents.

**Comment by kolibril13** [comment]
Sounds good!
So do we want to ditch the `Union[np.ndarray, List]` syntax then? E.g. here:
https://github.com/ManimCommunity/manim/blob/808c35fa3f31a1dc98ee87f11567ff9359ccb1b5/manim/mobject/mobject.py#L2006
And I just tested: Sequence[Int] is a subset of Sequence[float], which means with Sequence[float] we can also use sequences of ints. Right now, I can not think of any case where coordinates should be ints only.

**Comment by cobordism** [comment]
Sounds good.

I also think that `Sequence[float]` reads a lot better than `Union` types. Furthermore it is in line with Python's ethos of Duck typing. `Sequence` doesn't tell you the exact type, it just tells you the methods the type must implement.

**Comment by cobordism** [comment]
Also cross linking issue 1212 https://github.com/ManimCommunity/manim/issues/1212 so that all our type hint discussions are interlinked.

**Comment by kolibril13** [comment]
I think this can be closed then.
Result of the discussion:
keep `Sequence[float]`
get rid of  `Union[np.ndarray, List]`
