### ISSUE TITLE
Replace getters and setters (where possible) by property or direct access

### ISSUE THREAD

**Issue by PgBiel** [ManimCommunity/manim#134]
We should replace getters and setters, which [are an antipattern in Python](https://docs.quantifiedcode.com/python-anti-patterns/correctness/implementing_java-style_getters_and_setters.html) (as exposed on https://github.com/ManimCommunity/manim/pull/122#discussion_r433565784). Most of them can be replaced either by:

1. The use of `@property` (which allows custom code to run when access is attempted or an assignment is done);
2. Direct access to the attribute (i.e. just delete the get and set functions where they don't do anything at all besides just getting or setting).

As I exposed in https://github.com/ManimCommunity/manim/pull/122#issuecomment-637222475, rather than having a `set` function for each attribute, we should (also) implement a general `set` function for dataclasses, which allows us to set multiple attributes at a time (and also to animate such setting), like so:

`mobj.set(x=5, y=6, z_index=50, ...)`

Setter functions which require more than one parameter could be kept anyways, and then simply invoked by `.set` when required.

Suggestions? Ideas?

Relevant PRs and comments (if there are more, please tell me or just edit this post): https://github.com/ManimCommunity/manim/pull/122#discussion_r433565784, https://github.com/ManimCommunity/manim/pull/122#issuecomment-637222475, https://github.com/ManimCommunity/manim/pull/116, https://github.com/ManimCommunity/manim/pull/114

**Comment by leotrs** [comment]
Can we have here a clear distinction/guidelines for when to use just an attribute and when to use a property? Also, should we do this after the dataclass/attr refactor? So as to not duplicate efforts...

**Comment by PgBiel** [comment]
> Can we have here a clear distinction/guidelines for when to use just an attribute and when to use a property?

In general, you will only use a property when the action of getting or setting requires extra code other than simply retrieving an attribute.

> Also, should we do this after the dataclass/attr refactor? So as to not duplicate efforts...

Also, yes, I'm just not sure about whether we should do it _during_ the refactor or _after_, but perhaps we can do it after

**Comment by leotrs** [comment]
This issue was left open only because it depended on the implementing of attrs/dataclasses. But latest developments in #7 sound like that will never happen.

Besides, I have already gotten rid of some get/set methods in some classes.

**Comment by PgBiel** [comment]
@leotrs but are we going to implement it? If so, it should be left open, no?
