### ISSUE TITLE
-o doesn't write relative to current directory

### ISSUE THREAD

**Issue by eulertour** [ManimCommunity/manim#136]
The `-o` flag writes a file relative to the resolution directory rather than the current one. For example, `manim example_scenes/basic.py SquareToCircle -plo ./vid.mp4` writes to ` /path/to/pwd/media/videos/basic/480p15/./vid.mp4`.

**Comment by leotrs** [comment]
Is the desired behavior to just completely bypass the folder directory discussed in #66?

**Comment by eulertour** [comment]
On second thought I think this way is more consistent, although I thought it used to bypass the directory structure.
