### ISSUE TITLE
Removing `TexMobject` and `TextMobject`

### ISSUE THREAD

**Issue by naveen521kk** [ManimCommunity/manim#1369]
## Enhancement proposal
It's been a long since `TexMobject` and `TextMobject` is deprecated. See https://github.com/ManimCommunity/manim/pull/391. It's time to remove the compatibility layer of the Depreciation warning and remove it.

## Additional comments
Marking it as a Good First Issue as it is easy to do so.

**Comment by Nikhil0504** [comment]
Just removing the 2 functions is enough right?

**Comment by RickyC0626** [comment]
We can close this since the issue has been solved.

**Comment by naveen521kk** [comment]
Yeah, forgot to link this issue. Fixed in https://github.com/ManimCommunity/manim/pull/1370
