### ISSUE TITLE
Overhaul of the `animation.indication` module interfaces

### ISSUE THREAD

**Issue by AntonBallmaier** [ManimCommunity/manim#1377]
## Enhancement proposal
The `indication` module contains some of the most frequently utilized Animations. However, there are quite some problems with this module:

- Naming inconsistencies (for example `ShowCreationThenDestruction` instead of `CreateThenUncreate`)
- Generally useless classes (why would you use 
`AnimationOnSurroundingRectangle(mob, AnyAnimation)` instead of 
`AnyAnimation(SurroundingRectangle(mob))` ?)
- Overall somewhat confusing

Therefor I suggest to overhaul the indication classes to move towards a more user-friendly Manim :slightly_smiling_face: 

Specifically I suggest the following changes (we should support all changed classes as deprecated for a while):

- `FocusOn`: Looks good to me :slightly_smiling_face: 
- `Indicate`: The name should be changed. This entire module is about indication. However, I haven't come up with a good name yet.
- `Flash`: this animation has parameters `flash_radius` and `line_length`. The confusing part is that `flash_radius` defines the outer radius of the animation, so `flash_radius > line_length` must be true or the animation will look really weird. 
- `ApplyWave` It might be nice to give a bit more options to this class, but overall its good. I thought about if it should be renamed to `Wave`, but I don't feel like it is necessary.
- `ShowPassingFlash` I feel like `FlashAlong` would fit our naming scheme a bit better, but again, not a necessary change.
- `ShowCreationThenDestruction`: This class should probably be removed. One could simply use `Succession(Create(mob), Uncreate(mob))` (this will not look exacly the same until #841) or `ShowPassingFlash(time_with=2)`. If we keep this class it should be renamed to `CreateThenUncreate`.
- `ShowCreationThenFadeOut` Again, why would we need a specialized class for  `Succession(Create(mob), FadeOut(mob))`? ...and it should be called `CreateThenFadeOut`.
- `AnimationOnSurroundingRectangle` using the class doesn't even save you time... `AnimationOnSurroundingRectangle(mob, AnyAnimation)` is quite a bit longer than `AnyAnimation(SurroundingRectangle(mob))`. This class should be removed.
- `ShowPassingFlashAround`, `ShowCreationThenDestructionAround`, `ShowCreationThenFadeAround`, `CircleIndicate` These 4 classes are all pretty similar: surround your mobject with something, show that something and remove it again. Therefor I think these classes should be combined into one: `Circumscribe` (explanation below) This would even increase the flexibility of this feature.
- `WiggleOutThenIn` should simply be called `Wiggle`. Nice class I would have liked to learn about earlier :smile: 
- `TurnInsideOut` seems to just flip simple mobjects. I don't know if this is intended behavior. If it is, rename this class to `Flip`, otherwise fix it. For text it looks funky...
 

**Explanation of `Circumscribe`:**
_...which could also be called `Encompass`, I like both names..._

```py
class Circumscribe(Animation):
    def __init__(
        self, 
        mobject: Mobject,
        shape: "rectangular", #the only other allowed value is "circular"
        fade_in = False,
        fade_out = False,
        time_width = 0.3, #gets ignored if (fade_in or fade_out)
        buff: float = SMALL_BUFF,
        color: Color = YELLOW
    )
```
This could be used to create the current animations as follows:
```py
ShowPassingFlashAround(mob)             => Circumscribe(mob)
ShowCreationThenDestructionAround(mob)  => Circumscribe(mob, time_width=2)
ShowCreationThenFadeAround(mob)         => Circumscribe(mob, fade_out=True)
CircleIndicate(mob)                     => Circumscribe(mob, "circular", True, True)
```
`Circumscribe` would simply be a lot more versatile. Also I think it is easier to learn Manim if there are a few less classes to do practically the same.  

## Additional comments
Videos in case you don't know all of the animations above:
<details>
<summary>Click to expand</summary>

https://user-images.githubusercontent.com/26899845/115420679-a0b4d180-a1fb-11eb-9005-b6bcb582714c.mp4

https://user-images.githubusercontent.com/26899845/115420694-a4e0ef00-a1fb-11eb-8ab9-bdee0009223e.mp4

https://user-images.githubusercontent.com/26899845/115420713-a8747600-a1fb-11eb-8d05-8ddc4f6ea562.mp4

https://user-images.githubusercontent.com/26899845/115420740-aca09380-a1fb-11eb-86f6-d105da62295f.mp4

https://user-images.githubusercontent.com/26899845/115420761-b1654780-a1fb-11eb-909b-0d18bf308b3d.mp4

https://user-images.githubusercontent.com/26899845/115420781-b629fb80-a1fb-11eb-85f9-752daaa13c86.mp4

https://user-images.githubusercontent.com/26899845/115420810-bd510980-a1fb-11eb-89f4-7d5f464fe55e.mp4

https://user-images.githubusercontent.com/26899845/115420897-cfcb4300-a1fb-11eb-9f31-02ca036eb1e2.mp4

https://user-images.githubusercontent.com/26899845/115420879-cc37bc00-a1fb-11eb-91d2-5bb58fefabcd.mp4

</details>

**Comment by behackl** [comment]
Some comments:

- I like the idea of a versatile `Circumscribe` method. Assuming that it is well-documented, I'd also be in favor of deprecating all of the other animations that can be replaced by it. I think that would not only improve maintainability (assuming that the implementation wouldn't be too difficult), but it would also make it easier for users to find functionality.
- Regarding `XThenY`-type animations I'm a bit on the fence; mainly because `Succession` (and `AnimationGroup` in general) is a gigantic mess, and I'm not sure we should actively encourage people to use them. (They *will* run into issues sooner or later.) As soon as that is more stable, I'd be all for removing them though.

Overall, I think
- removing useless / complicated / broken indication animations is a good idea,
- pulling together functionality of similar animations in a new, more general class is a good idea,
- improving the interface of existing animations is a good idea,
- and adding more documentation/examples to the animations is also a good idea.
