### ISSUE TITLE
Restructuring the contribution page

### ISSUE THREAD

**Issue by kolibril13** [ManimCommunity/manim#1392]
Currently, the contribution page looks like this:
![image](https://user-images.githubusercontent.com/44469195/115752883-d47a2d80-a39a-11eb-8484-2320f5a4ade6.png)

It's say, It could also look like this:
Contributing
* Manim Development Process
    * manim_directive
* Docs: Adding Docstrings  
* Docs: Adding References  
* Docs: Adding Examples
* Docs: Adding Typehints
* Adding Tests

**Comment by jsonvillanueva** [comment]
Additionally, each page should have its own separate table of contents (ToC) at the beginning of the page to quickly navigate to the corresponding sections of the page. A few pages already do this sort of ToC but since these pages are just being transitioned from GitHub wiki, they don't.

**Comment by Nikhil0504** [comment]
Should I do this?

**Comment by Nikhil0504** [comment]
> * Docs: Adding Docstrings
> * Docs: Adding Typehints

I think we should put them in the same page as they are related to each other and we use them side by side so we can just omit some lines and change the examples accordingly to accommodate typehints also. This way the contributor can know all the information in one page.
