### ISSUE TITLE
Addition of typestring parser checker

### ISSUE THREAD

**Issue by Nikhil0504** [ManimCommunity/manim#1394]
## Description of proposed feature

This particular package can actually check what type of typestring you should be using in your functions while writing the documentations. This could be really useful for the beginners like me and others or even contributors who write docs a lot as they can directly check it in the IDE.

## How can the new feature be used?

So first we have to download it via pip using `pip install typestring-parser` then we could use it as illustrated in the example given below.

For example:
```python
>>> from typestring_parser import parse
>>>
>>> parse('int')
<class 'int'>
>>> parse('int or str')
typing.Union[int, str]
>>> parse('list of str or str')
typing.Union[typing.List[str], str]
>>> parse('list of (int, str)')
typing.List[typing.Tuple[int, str]]
```

I was thinking if we could could have included in the manim package and include the usage in our docs

## Additional comments

See https://github.com/Dominik1123/typestring-parser for more info about this.

**Comment by MrMallIronmaker** [comment]
Conversation from Discord I'm posting here for reference:

Nikhil0504 — Today at 6:14 PM
at-mrmallironmaker can you check my new issue ?
[6:14 PM]
It’s related to documentation

mrmallironmaker — Today at 6:16 PM
looks like a decently useful tool but I don't see how it belongs in Manim. Perhaps as a note when talking about typestrings in the contributions guide?

Nikhil0504 — Today at 6:17 PM
Yes
[6:17 PM]
That was the intention
[6:22 PM]
For making the note we need to include it in the package

mrmallironmaker — Today at 6:23 PM
ah then yes, go ahead with it and make a PR
