### ISSUE TITLE
Fix the installation of or completely replace cairo

### ISSUE THREAD

**Issue by XorUnison** [ManimCommunity/manim#14]
As many, or rather probably most of us know personally, and have seen on the Discord channel too, the installation of cairo regularly causes problems (at least on windows.)

As of now the documentation refers to installing dependencies via the requirements.txt in the Directly section:
```
# Install python requirements
python3 -m pip install -r requirements.txt
```
Although there is a Directly(Windows) section, if the original Directly doesn't work on windows, then we'd want to write that properly as in Directly(Mac, Linux) or whatever, if we already can't streamline the process across platforms.

While this requirements.txt is in principle a great and convenient idea, pycairo (and to a lesser degree opencv-python) were often a source of issues. Recently the version numbers have been removed from the requirements.txt, which helps, but pycairo is still a unique case, as just trying to install it like this will always fail, and if that isn't bad enough, will actually ask for a Microsoft Visual C++ installation.
If you haven't tried it yet, that's a huge amount of overhead **and** also doesn't really make the pip pycairo install work reliably either. Highly frustrating to users.

The documentation goes on to mention downloading pycairo files (https://www.lfd.uci.edu/~gohlke/pythonlibs/#pycairo), but `For most users, pycairo‑1.18.0‑cp37‑cp37m‑win32.whl will do fine.` and `Make sure that pycairo==1.17.1 is changed to pycairo==1.18.0 in requirements.txt.` are also deprecated comments. The manual file installs are tied to the python version, so someone with 3.8 will not be able to install pycairo cp37 if I remember correctly. All in all this installation is just unreasonably stacked with pitfalls and will throw off most casual users with ease. Talking of python 3.8, manim can be installed on it and we probably should roll on with that too.

So what we should do is, at least dramatically clean-up the documentation, or at best find a way to either streamline the windows pycairo installation or replace it altogether.
Though I'm raising the issue I don't have any great idea for how to implement one of the better solutions.

**Comment by safinsingh** [comment]
I'm running manim on Python 3.8.2 and it works fine.

**Comment by safinsingh** [comment]
Maybe we can create an install script that pulls the cairo package?

**Comment by PgBiel** [comment]
> I'm running manim on Python 3.8.2 and it works fine.

It works if you install it manually... atm pip won't handle it entirely

**Comment by XorUnison** [comment]
We... should be able to, yeah. Question is if we want to commit to that option as it would mean stuff like checking the python and sys version, then grabbing the according file.

**Comment by yoshiask** [comment]
I thought we had already decided that the rendering engine would be kept modular, and that manim would only ship with OpenGL rendering?

**Comment by xy-23** [comment]
Hi, replacing cairo is probably not a good idea, because `Text` rely on it to generate svg.

Maybe we should try to switch into cairocffi? But it's installation is also annoying in Windows, but at least it doesn't require Microsoft Visual C++ installation

**Comment by xy-23** [comment]
I have make a PR to cairocffi already to let it support some cairo behavior so that manim can switch pycairo simply by ```import cairocffi as cairo```. Although my PR to cairocffi has been merged, they doesn't update their release so far, so we probably need to wait for sometime...

**Comment by PgBiel** [comment]
> Hi, replacing cairo is probably not a good idea, because `Text` rely on it to generate svg.

Note that it's _replacing_, not _removing_, so we'll simply have a different renderer do all the `Text` work and more.

> Maybe we should try to switch into cairocffi? But it's installation is also annoying in Windows, but at least it doesn't require Microsoft Visual C++ installation

The intention is to avoid those installation issues, but `cairo` should remain an option with our proposed addon API

**Comment by xy-23** [comment]
Also, using cairocffi has a another advantage which pycairo can't offer. Using cairocffi can let Windows user to use pango/pangocairo easily. As we all know, the built-in text layout engine in cairo(both cairocffi and cairo) are not well support some languages like Bengali. Currently I'm trying to let `Text` to use pango/pangocairo to let it have a better utf-8 support, and this need us to switch pycairo into cairocffi

**Comment by PgBiel** [comment]
This should be resolved with future rendering options, such as JS

**Comment by xy-23** [comment]
> This should be resolved with future rendering options, such as JS

You mean the electron app that EulerTour is working on?

**Comment by PgBiel** [comment]
yes

**Comment by xy-23** [comment]
But it can't convert text into svg paths and lost the many animating abilities...

**Comment by PgBiel** [comment]
it's not done yet

**Comment by xy-23** [comment]
I agree with you that the draing frames function should let other package to do it rather than cairo.

**Comment by yoshiask** [comment]
The current plain that @eulertour and I have formulated is to ship OpenGL as the default rendering backend (replacing Cairo entirely in the base library), while allowing other backends (such as DirectX, WebGL, and Cairo) to be used via addons.
