### ISSUE TITLE
Copyediting of documentation

### ISSUE THREAD

**Issue by Darylgolden** [ManimCommunity/manim#1401]
## Enhancement proposal
As I look through the docs, I'll make a list here of pages that could do with some copyediting. Most of these pages are relatively well-written and only need some minor corrections. I think it'll be a good task for new contributors who are proficient with English.

- [ ] `installation/win`
- [ ] `installation/troubleshooting`
- [ ] `installation/for_dev` Last section seems incomplete
- [ ] `installation/plugins` Some commas can be semicolons
- [ ] `tutorials/building_blocks` "Mobjects are the basic building block**s**; probably other minor issues as well
- [ ] `tutorials/configuration` Some awkward phrasing
- [ ] `contributing/development` One `flake8` word isn't formatted correctly
- [ ] `contributing/internationalization` I copyedited this once as part of my review, but it could still do with another pass.

This is by no means an exhaustive list. Hopefully this helps new contributors with a keen eye for grammar and style find some ideas for ways to contribute.

## Additional comments
I was going to make a more exhaustive list, but I realized that almost every page in the documentation would be listed here if I were nitpicky enough.

**Comment by RickyC0626** [comment]
I can spend some time working on this.

**Comment by Darylgolden** [comment]
Reopening because it was far too broad to have been solved by that single PR. Besides, there are many new files that need some checking.

**Comment by netwizard22** [comment]
[Numberline docs](https://docs.manim.community/en/stable/reference/manim.mobject.number_line.NumberLine.html)
> size (font) – The size of the label mobjects. Defaults to 36.
Replace `size (font)` with `font_size`. Numberline doesn't have `size` attribute.

**Comment by Pow3r5** [comment]
Hey, im new to open source and think this would be a good starting place for me. I noticed some simple errors within "tutorials/configuration" that I should be able to help fix.
