### ISSUE TITLE
`Union[float, int]` should be just `float`

### ISSUE THREAD

**Issue by Darylgolden** [ManimCommunity/manim#1409]
## Enhancement proposal
Per https://www.python.org/dev/peps/pep-0484/#the-numeric-tower , the `Union[float, int]` type hint should just be replaced with `float`. There are 4 cases of this type hint in `value_tracker.py`; this can be fixed with a simple find and replace.

**Comment by kamilczerwinski22** [comment]
I will take this one

**Comment by Darylgolden** [comment]
> 
> 
> I would like to take this one

Feel free to open a PR!
