### ISSUE TITLE
Allow background rectangles to be added in `Vector.coordinate_label`

### ISSUE THREAD

**Issue by hydrobeam** [ManimCommunity/manim#1423]
## Enhancement proposal

Following the refactoring of `vector_coordinate_label` to `geometry.py`  in #1407, @behackl suggested that the method should allow the user to add background rectangles (via `Matrix`) to the coordinate label, perhaps through a keyword parameter. 

## Additional comments

This would be a good first issue for anyone interested in carrying out this change.

**Comment by akbhuker** [comment]
hey, can I have this issue?
I'm quite new to this so I might need some guidance

**Comment by behackl** [comment]
> hey, can I have this issue?
> I'm quite new to this so I might need some guidance

Hey @akbhuker – sure, feel free to work on this and send a pull request. (There is no need to ask for permission first.)

**Comment by Rudransh24** [comment]
Hi @behackl
I am new to open source and wanted to try my hand at this issue. From what I have understood I just need to add one Boolean parameter in the function Vector.coordinate_label which allows user the choice whether to have a rectangle or not in a digit's background.

**Comment by behackl** [comment]
> Hi @behackl
> I am new to open source and wanted to try my hand at this issue. From what I have understood I just need to add one Boolean parameter in the function Vector.coordinate_label which allows user the choice whether to have a rectangle or not in a digit's background.

Hey! Yes, as far as I can remember this is more or less right. We already have some mobjects that add a `BackgroundRectangle`, so you should be able to find some inspiration for how to add this to `Vector.coordinate_label`.

**Comment by Rudransh24** [comment]
> > Hi @behackl
> > I am new to open source and wanted to try my hand at this issue. From what I have understood I just need to add one Boolean parameter in the function Vector.coordinate_label which allows user the choice whether to have a rectangle or not in a digit's background.
> 
> Hey! Yes, as far as I can remember this is more or less right. We already have some mobjects that add a `BackgroundRectangle`, so you should be able to find some inspiration for how to add this to `Vector.coordinate_label`.

Thank you! I will start working on it.

**Comment by Rudransh24** [comment]
Hi @behackl 
I have added a PR for this issue. Please do let me know in case of any suggestions or improvements.

**Comment by hickmott99** [comment]
Is this issue still open @Darylgolden  Should I work on it?

**Comment by behackl** [comment]
Hey @hickmott99 – I just checked; this issue has already been resolved via #2138 a while ago, we just forgot to close it. Nothing left to do here!
