### ISSUE TITLE
Out of frame Mobject for line graph example

### ISSUE THREAD

**Issue by Darylgolden** [ManimCommunity/manim#1428]
## Enhancement proposal
As can be seen [here](https://docs.manim.community/en/latest/reference/manim.mobject.coordinate_systems.Axes.html?highlight=axes#manim.mobject.coordinate_systems.Axes), the line graph example has a line out of the frame. It should be replaced with a point that fits within the frame. In addition, I think the line graph can be made to look more visually appealing, making use of the dimensions of the axes rather than just being confined to the top right quadrant.

**Comment by hydrobeam** [comment]
Looking at the line graph right now, it looks fine. Maybe it was addressed in #1430 ?

**Comment by Darylgolden** [comment]
Yep, seems like it.
