### ISSUE TITLE
`Dot3D` should have a coordinate parameter

### ISSUE THREAD

**Issue by Darylgolden** [ManimCommunity/manim#1429]
## Enhancement proposal
`Dot3D` should mirror the functionality of `Dot` and have a parameter to specify its coordinates. I think the best way to do this is to add a kwarg to `Sphere` that would also change its position, and then pass in the coordinate from `Dot3D` to the superclass init method.

**Comment by PhotonSpheres** [comment]
Was thinking the same thing a while ago, seems like a good idea to me.
