### ISSUE TITLE
Gaps in VMobject created by a list of points

### ISSUE THREAD

**Issue by PhotonSpheres** [ManimCommunity/manim#1432]
## Description of bug / unexpected behavior

When creating a VMobject via a list of points, four of those points get grouped together and a cubic-bezier curve is created. The next curve then uses the next for points. so the new starting point is not the endpoint of the previous curve. I cannot tell whether this is intentional but I wouldn't expect this behavior like this I think. If this is intentional, a `connect_points` function would maybe be a good idea to get rid of those gaps (maybe this already exists?).

## How to reproduce the issue

```py
class Test(Scene):
    def construct(self):
        para = VMobject(
            stroke_color=RED,
            stroke_width=4,
        )
        points = [
            *[(k*k, k, 0) for k in linspace(-2,2,40)]
        ]
        para.append_points(points)
        self.add(para)
```

## Additional media files

![image](https://user-images.githubusercontent.com/44864613/116780357-893bdb00-aa7c-11eb-82d6-159403494afc.png)

**Comment by naveen521kk** [comment]
>  cannot tell whether this is intentional but I wouldn't expect this behavior like this I think. If this is intentional

I think it is intentional because `VMobject` is rendered this way in the Camera.
https://github.com/ManimCommunity/manim/blob/6d8e8a5bcf6eb6df9b4942a953104ce21f98bc4c/manim/camera/camera.py#L623-L655

> If this is intentional, a connect_points function would maybe be a good idea to get rid of those gaps (maybe this already exists?).

I don't know about this but most likely there should be one.

**Comment by huguesdevimeux** [comment]
This is seemingly an expected behavior according to me. 
The bezier curves are composed of four points, so the arrays you gave are split in subsets of four points giving 10 different subsets of points, separated by some space.

**Comment by abhi3019** [comment]
> If this is intentional, a `connect_points` function would maybe be a good idea to get rid of those gaps (maybe this already exists?).

Yeah it does exist - `VMobject.set_points_as_corners`
https://github.com/ManimCommunity/manim/blob/6d8e8a5bcf6eb6df9b4942a953104ce21f98bc4c/manim/mobject/types/vectorized_mobject.py#L627

**Comment by PhotonSpheres** [comment]
Cheers @abhi3019, `set_points_as_corners` does exactly that. I guess this can be closed then.
