### ISSUE TITLE
Preview in a python window

### ISSUE THREAD

**Issue by Tams-Tams** [ManimCommunity/manim#1433]
## Description of proposed feature
I thought the preview of manim should not open in the default video-opener-application, but in a separate window in python.
This may be good, because;
-  The main idea is that most of the time, you're looking the video file just to see how well you've done, meaning you don't need a fullscreen window for it. (For me, as I'm not that good at manim yet, for a decent project, I am testing it ca. 20 times)
-  If the video file previews in python, you can resize it to a smaller window, remove the taskbar, maybe pause when you click on it and you can look at it while your programming.
- If you're really finished, then you can open the file in the systems video opener or add an -f flag to preview it in python, but fullscreen.

What do you think about it?

## Additional comments
If this is a good idea, I would love to make a pull request myself.

**Comment by naveen521kk** [comment]
There exists an Opengl previewer or WebGL renderer which should support real-time rendering.

**Comment by Tams-Tams** [comment]
@naveen521kk I didn't think of real-time rendering. Just a preview after writing-to-a-file has finished.

**Comment by e4coder** [comment]
Are you talking about the video preview being played inside of the terminal?

**Comment by kilacoda** [comment]
couldn't you just resize your video player window though?

**Comment by Tams-Tams** [comment]
@kilacoda No, a new window

**Comment by Tams-Tams** [comment]
@kilacoda No, didn't work with the vcl video player from windows.

**Comment by behackl** [comment]
Implementing (or adding a new dependency for) a cross-platform video viewer that opens in a Python window seems like a lot of work to me. I am not sure this is worth it.

I'm closing this issue for now, if there is a more detailed proposal of how this could be solved we can definitely reopen it.
