### ISSUE TITLE
Choose a timeline for deprecation

### ISSUE THREAD

**Issue by leotrs** [ManimCommunity/manim#145]
There are several features that will be deprecated, both currently (#74, #114, #134), and in the future. The consensus seems to be that these features are deprecated instead of outright removed. In this case, we need to determine a timeline for these to be removed.

**If we deprecate them in ManimCommunity version 1.0.0, when will these features be entirely removed?**

**Comment by yoshiask** [comment]
In general, the major version of the library is incremented when there are breaking changes. We should wait to remove them until v2.0.0

**Comment by leotrs** [comment]
OTOH, I think we are assuming that manimCE 1.0.0 will be fully backwards compatible to 3b1b. Is this the case?

**Comment by yoshiask** [comment]
I don't think we came to an explicit agreement, but this would make the most sense. We should make the initial version of Manim CE backwards compatible so that most scenes can use it out-of-the-box.

**Comment by leotrs** [comment]
I don't think this issue is useful anymore. Development is moving forward by issuing DeprecationWarnings as much as possible. I guess whatever is deprecated in version v1.0 will be eliminated in v2.0. Closing for now.
