### ISSUE TITLE
Dont import `hilite_me` and `insert_line_numbers_in_html` with `from manim import *`

### ISSUE THREAD

**Issue by kolibril13** [ManimCommunity/manim#1450]
https://github.com/ManimCommunity/manim/blob/199424d713c77fca6f59de58ba0f8eb3955bfab1/manim/mobject/svg/code_mobject.py#L6

The functions `hilite_me` and `insert_line_numbers_in_html` are currently imported with `from manim import *` , and I think that is not necessary.
Further the question:
Why are they defined outside the Code class?

**Comment by naveen521kk** [comment]
>  Why are they defined outside the Code class?

Maybe a mistake.

Marking this as a "good first issue" as it is as simple as removing those two lines from `__all__`.
