### ISSUE TITLE
Add some output example to README

### ISSUE THREAD

**Issue by kilacoda-old** [ManimCommunity/manim#1455]
## Enhancement proposal

Currently our README only *talks* about manim, but doesn't *show* what it's capable to do. Adding a few example videos/gifs might make using the library more attractive to newcomers.

## Additional comments

An argument may be made that "oh well, all the 3b1b videos are examples aren't they?" and while I agree, it's better to have something on the front page of the repo, instead of sending someone off to youtube.

**Comment by behackl** [comment]
I agree (although we'll have to think about how exactly we do that -- maybe we can link to videos generated in the documentation?)!

On a related note, I would also like to improve our landing page https://www.manim.community in a similar way, eventually. I like how https://reanimate.github.io have a simple but nonetheless impressive showcase featured.

**Comment by Nikhil0504** [comment]
I like the `Reanimate` website too, maybe we could use the same methodology and make some kind of a showcase that shows the most viewed examples with some short descriptions. 

But I think we will have to keep the video files rendered before hand and keep them in a folder somewhere. Correct me if I am wrong about this though.

**Comment by behackl** [comment]
The website has been improved, and I think it is not a bad idea to keep the readme somewhat simple. Closing.
