### ISSUE TITLE
Implement `-q[l|m|h|p|k]` to specify render quality

### ISSUE THREAD

**Issue by leotrs** [ManimCommunity/manim#146]
Forked from #65.

Instead of `-l` being the abbreviation of `--low_quality`, we should have `-ql`, and similarly so for medium/high/production/4k quality. Also, we should have a `--production_quality` flag.

**Comment by leotrs** [comment]
This is a fairly easy PR now that #98 has been merged. Any takers?

**Comment by jvdoorn** [comment]
I can take a look at this, I assume that `production_quality` is higher quality than `fourk_quality`?

**Comment by leotrs** [comment]
Thanks @jvdoorn for volunteering! You can see what each quality means in `https://github.com/ManimCommunity/manim/blob/master/manim/config/default.cfg`. The "production" quality is defined under the [CLI] section, as frame_rate = 60 pixel_height = 1080, pixel_width = 1920. The other four have their own sections [low_quality], etc.

**Comment by naveen521kk** [comment]
Is this fixed?

**Comment by jvdoorn** [comment]
Yes except for the `-qp` flag, however since that is default behavior I personally don't see a use for it. It could however be implemented very easily if you want. Otherwise this issue is done and dusted.

**Comment by MysaaJava** [comment]
It is useful, beccause you can't predict if the default behavior may change in the future. If you make yourself a script that auto-renders or anything, you may want to "force" production resolution

**Comment by eulertour** [comment]
It would actually be good to have a `-qp` flag, if only to say that it's the default in the help menu (currently it's not clear that high quality isn't the default).

**Comment by jvdoorn** [comment]
Got it, will create a PR for that probably later today.

Also, slightly unrelated, but shouldn't production quality be the highest possible quality? Since "production quality" often refers to the quality for the end-user which should be the highest right? But I don't know how you guys interpret production quality.

**Comment by MysaaJava** [comment]
I agree, i would suggest more explicit names, like -qHD -qFHD -q2K -q4K. We can take the names from the wikipedia page : https://en.wikipedia.org/wiki/List_of_common_resolutions?wprov=sfla1
To every referenced resolution is associated a name. We could even create a file containing a association map with Name->resolutionData. And then allow the user to create his own "resolutiondata" and use -qMyRes freely. What do you think ?

**Comment by eulertour** [comment]
I think that'd be overcomplicating it a bit, especially since these can already be set from the config file.

**Comment by jvdoorn** [comment]
I implemented the `qp` flag in #529. If that is merged we should be able to close this issue.

**Comment by leotrs** [comment]
Pro tip: if you want your PR to automatically close an issue, just add a commit on that branch that includes "fix #146" or "close #146".

**Comment by jvdoorn** [comment]
Good one, looks like you can also put it in your PR message so I'll do that next time!
