### ISSUE TITLE
Jupyterlab Manim help

### ISSUE THREAD

**Issue by Viasis** [ManimCommunity/manim#1474]
## Description of error
I've installed manimCE onto anaconda navigators, and the prompt says that Manim is already detected. But whenever i try to run manim on JupyterLab, it says that no module named "manim". I've posted a similar problem last year and they say to wait awhile for manim to be incorporated into jupyter.

Is there a reason why jupyter cant detect manim, thanks 

## Installation logs

```
Manim Community v0.6.0

Usage: manim [OPTIONS] COMMAND [ARGS]...

  Animation engine for explanatory math videos

Options:
  --version  Show version and exit.
  --help     Show this message and exit.

Commands:
  render*  Render SCENE(S) from the input FILE.
  cfg      Manages Manim configuration files.
  plugins  Manages Manim plugins.

  Made with <3 by Manim Community developers.

```

<details><summary>Terminal output</summary>

```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-2-002cc46713e5> in <module>
----> 1 from manim import *

ModuleNotFoundError: No module named 'manim
```

**Comment by kilacoda** [comment]
Are you using jupyter from a virtual environment? Might be that it's using the wrong interpreter

**Comment by Viasis** [comment]
> Are you using jupyter from a virtual environment? Might be that it's using the wrong interpreter

Im launching jupyter from the anaconda navigator. Is that the proper way to launch it?

**Comment by kolibril13** [comment]
put
```terminal
comupter $  source projects/manimenv/bin/activate
(manimenv) comupter $ jupyterlab
```
 in your terminal, where `projects/manimenv/bin/activate` points to your manim environment.
You might have to install jupyter a second time in this environment, but then it should work

**Comment by Viasis** [comment]
> put
> 
> ```
> comupter $  source projects/manimenv/bin/activate
> (manimenv) comupter $ jupyterlab
> ```
> 
> in your terminal, where `projects/manimenv/bin/activate` points to your manim environment.
> You might have to install jupyter a second time in this environment, but then it should work

Alright it works now! Thanks so much for your help. Closing the thread now
