### ISSUE TITLE
Idea: new `Heart` Mobject

### ISSUE THREAD

**Issue by kolibril13** [ManimCommunity/manim#1478]
From time to time, one might need a Heart for an animation.
What do you think about an HeartMobject?
Implementation could look like this:
https://mathworld.wolfram.com/HeartCurve.html

**Comment by naveen521kk** [comment]
Rather than naming it `HeartMobject` just `Heart` should be fine, imo.

**Comment by WampyCakes** [comment]
This seems like one of those items best left out of core manim. This seems like a good use case of something along the lines of #914.

**Comment by kolibril13** [comment]
Good idea!
In this plugin, I would further add a section of some sound assets.

**Comment by kolibril13** [comment]
As we also have Objects like star right now, I think Heart could also be in the core.
Here is the code for it:
```
class HeartScene(Scene):
    def construct(self, **kwargs):
        x=1
        y=1
        el1= CubicBezier([x,y,0],[x,y-.3,0],[x-.5,y-.3,0],[x-0.5,y,0])
        el2= CubicBezier([x-.5,y,0],[x-.5,y+.3,0],[x,y+0.35,0],[x,y+0.6,0])
        el3= CubicBezier([x,y+.6,0],[x,y+.35,0],[x+.5,y+.3,0],[x+.5,y,0])
        el4= CubicBezier([x+.5,y,0],[x+.5,y-.3,0],[x,y-.3,0],[x,y,0])

        self.add(VGroup(el1,el2,el3,el4).rotate(180*DEGREES))
```
![image](https://user-images.githubusercontent.com/44469195/120335432-c00e4680-c2f1-11eb-8114-67af4dc5a838.png)

**Comment by Darylgolden** [comment]
Removing the good first issue label as it needs discussion.

**Comment by WampyCakes** [comment]
I'm in favor of closing this issue.

**Comment by kolibril13** [comment]
ok

**Comment by Darylgolden** [comment]
Aren't you supposed to be on a break :p

**Comment by kolibril13** [comment]
I still get E-Mails when issues are getting answered, and these things don't require a lot of time ;)

**Comment by JINAILAB** [comment]
```python
        heart = ParametricFunction(
            lambda t: np.array([
                16 * np.sin(t) ** 3,
                13 * np.cos(t) - 5 * np.cos(2 * t) - 2 * np.cos(3 * t) - np.cos(4 * t),
                0
            ]),
            t_range=[0, TAU],
            color=WHITE,
            fill_opacity=1,
            fill_color=PINK,
        ).scale(0.1).move_to(ORIGIN)
``` 
i made a heart like this.
