### ISSUE TITLE
Just see blank screen when add the image

### ISSUE THREAD

**Issue by leminhnguyen** [ManimCommunity/manim#1482]
## Description of bug / unexpected behavior

I have followed the [Manim tutorial | 7 - Add sounds, svgs and images](https://www.youtube.com/watch?v=tsMGRN3ZfAg) tutorial. I'tried to add SVG image like the author, when running the code no error message was thrown and every things looked like to work correctly. But I just see a video (about 2s) with blank screen

<details><summary>Code for reproducing the problem</summary>

```py
class ImageTest(Scene):
    def construct(self):
        image = SVGMobject("assets/images/finger.svg")
        self.play(DrawBorderThenFill(image))
        self.wait()
```

</details>

## Additional media files
- The SVG image was used
![image](https://user-images.githubusercontent.com/43167455/117559803-96774c00-b0b2-11eb-9b6d-1c6a4811844b.png)

- The result video
![image](https://user-images.githubusercontent.com/43167455/117559870-261cfa80-b0b3-11eb-8455-a661f7216d15.png)

## System specifications

<details><summary>System Details</summary>

- OS (Ubuntu 20.04):
- RAM: 8G
- Python version (3.8):

**Comment by Nikhil0504** [comment]
```py
class ImageTest(Scene):
    def construct(self):
        image = SVGMobject("assets/images/finger.svg")
        self.play(DrawBorderThenFill(image, rate_func=linear))
        self.wait()
```
We’ve had this same issue before in discord, so please check it over there for more information but this code so work now.

**Comment by jsonvillanueva** [comment]
Your SVG file is black on a black background. Either edit your SVG, or edit your video's background color.
