### ISSUE TITLE
Remove duplicate imports on examples

### ISSUE THREAD

**Issue by Skaft** [ManimCommunity/manim#1483]
## Enhancement proposal

Some docstring examples include redundant imports which could be removed. This is because any example under the `.. manim::` directive get an automatic `from manim import *` added.

## Additional comments

I haven't done an exhaustive search, but these are two examples:
[mobject.mobject](https://docs.manim.community/en/v0.6.0/reference/manim.mobject.mobject.html#animationoverrideexample)
[mobject.graph.Graph](https://docs.manim.community/en/v0.6.0/reference/manim.mobject.graph.Graph.html#tree)

**Comment by meispi** [comment]
How do I have to send a PR to this? A python file (.py) or a jupyter notebook file (.ipynb).

**Comment by M87K452b** [comment]
Can I take this up? 
Also, the links in the Issue proposal lead to the docs of release v0.6.0. But it is still present in v0.8.0. I can go through the reference manual to find and fix any duplicates like this. Thanks!

**Comment by Darylgolden** [comment]
Sure!
