### ISSUE TITLE
Testing examples for consistency

### ISSUE THREAD

**Issue by Skaft** [ManimCommunity/manim#1484]
## Description of proposed feature

In short, tests for the docstring examples to ensure consistency. They can currently get duplicate imports (#1483), or vary in code style. A layer of CI that checks for oddities like the unwanted imports and enforces `black` formatting could help with examples looking off.

## How can the new feature be used?

Ideally, I suppose, the tests would be run through a pre-commit hook to nip it in the bud.

## Additional comments

Naveen mentioned [blacken-docs](https://github.com/asottile/blacken-docs) which looks useful in regards to formatting.

**Comment by kolibril13** [comment]
This is in general a good idea!
In practice, I think the pre-commit strategy is the way to go here.

**Comment by MrDiver** [comment]
- #1485
