### ISSUE TITLE
Links to Discord in the docs should point to the new URL on the website

### ISSUE THREAD

**Issue by Darylgolden** [ManimCommunity/manim#1497]
## Enhancement proposal
Per consensus on the Discord, links to Discord in the docs should now point to the new URL at (https://www.manim.community/discord/). This can be done by simply finding and replacing the old URL (https://discord.gg/mMRrZQW) with the new one.

**Comment by NikhilSharma03** [comment]
I have updated the link. Can you please check the pull request. Thankyou
