### ISSUE TITLE
Enhance naming for the jupyter video outputs

### ISSUE THREAD

**Issue by kolibril13** [ManimCommunity/manim#1501]
Currently, the jupyter videos have keys to identify them, however, when one made multiple cells, and clicks the download button, the video names are a bit cryptic:
![image](https://user-images.githubusercontent.com/44469195/118003632-0999f000-b349-11eb-9edc-2072360342ef.png)
# Filenames:
![image](https://user-images.githubusercontent.com/44469195/118003613-043ca580-b349-11eb-8783-c3523ae7d468.png)
Therefore, I suggest that we have a better naming strategy for them.
I suggest:
`SceneName_DATE-OF-RENDER_TIME-OF-RENDER`
When the time is in seconds, I think this will also generate a name that is unique, while more user friendly to read.

**Comment by behackl** [comment]
Done via #1649
