### ISSUE TITLE
Suggestions for the visual look of the docs.

### ISSUE THREAD

**Issue by hydrobeam** [ManimCommunity/manim#1503]
## Enhancement proposal

# Motivation
I have some issues with the new look of the docs, with a particular focus on the light mode version. Although, quite a few of these points are general.

Here's a general summary ✍

## Top of page
![image](https://user-images.githubusercontent.com/70682032/118077549-4d5d1b80-b382-11eb-90aa-28743119348c.png)
![image](https://user-images.githubusercontent.com/70682032/118081808-13901300-b38a-11eb-9437-e8c2b65ac9b1.png)
### 1. Display of default variables:
   - **NEW**: they are written without styling and are greyed out against the beige background, making them hard to read.
   - **OLD**: **bold** and *italics* improving visibility
   - **Suggestion**: Restore previous styling

### 2. Styling of subtitles
   - **NEW**: subtitles are written in uppercase and have no distinction against regular text
   - **OLD**:  Subtitles are **bold** and appear larger than accompanying text, written in title-case
   - **Suggestion**: restore old look

### 3. Path to class
![image](https://user-images.githubusercontent.com/70682032/118078162-8b0e7400-b383-11eb-8ae0-bd34b9f7d4a3.png)
   - **NEW**: Does not exist
   - **OLD**: Exists
   -  **Suggestion**: This would be helpful to have for easier navigation  

### 4. Example Subtitle
![image](https://user-images.githubusercontent.com/70682032/118081295-0d4d6700-b389-11eb-829b-6657a9b45ead.png)
![image](https://user-images.githubusercontent.com/70682032/118081316-19392900-b389-11eb-84e0-d943cf4fc7f6.png)
   - **NEW:** `Example: EllipseExample` with no styling
   - **OLD:** `EllipseExample` emboldened and larger text
   - **Suggestion:** Styling + larger text is a must. I also prefer the subtitle without `Example:` since most examples already contain this.

### 5. Example
![image](https://user-images.githubusercontent.com/70682032/118081935-505c0a00-b38a-11eb-923b-44a86e9d32d0.png)
![image](https://user-images.githubusercontent.com/70682032/118081950-55b95480-b38a-11eb-9179-e5d92e50fae6.png)
   -  **OLD:** kind of bad, but: colour for numbers.
   -  **NEW:** better, but no colour for numbers.
   -  **Suggestion:** change the default colour for numbers to something more visually appealing.

### 6. Display of attributes and methods
![image](https://user-images.githubusercontent.com/70682032/118082419-2bb46200-b38b-11eb-8c95-0988cab42b9f.png)
![image](https://user-images.githubusercontent.com/70682032/118082450-35d66080-b38b-11eb-8a1f-8396c9ae4c2c.png)
   - **NEW:** uses a table and the mono-space looks odd when not coloured
   - **OLD:** uses separation between the term and description. 
   -  **Suggestion:** re-implement the separation look. Colour might be more difficult since it's tied to mono-space.

### 7. End cards
![image](https://user-images.githubusercontent.com/70682032/118084241-5f44bb80-b38e-11eb-9d6f-fd3cbef6abde.png)
![image](https://user-images.githubusercontent.com/70682032/118084272-6ec40480-b38e-11eb-8834-b3f5d853d83c.png)
   -  **NEW:** Not enclosed in a box. 
   -  **OLD:** Enclosed in a box.
   -  **Suggestion:** Enclose the directions in a box
   - Sidenote, overlaps in mobile:
       -  ![image](https://user-images.githubusercontent.com/70682032/118084696-23f6bc80-b38f-11eb-896c-1b2a44ca9ab9.png)
       - ![image](https://user-images.githubusercontent.com/70682032/118084706-2822da00-b38f-11eb-8125-1244d9dee70e.png)

### 8. Reference:
   - **NEW:** bundle of file paths that are hard to navigate
   - **OLD:** grouped into digestible chunks.
   - **Suggestion:** revert/reintroduce the old way.

### 9. Text Size
   - **NEW**: smaller overall due to the docs taking up less space on the screen 
   -  **OLD**: larger text size
   -  **Suggestion**: smaller text size makes it more difficult overall to use the docs, especially for people with impaired vision. I'd suggest a larger font size.

## Additional comments

This was pretty long and all opinion. Please let me know what you think 🙇‍♀️ 🙇

(maybe restore white background too?)

**Comment by eulertour** [comment]
I think these are all good criticisms. I think we got the look and feel of the old docs mostly for free so nobody has much knowledge on how to update them now. The best approach to tidying them up now is probably to just make the changes and people will likely just accept them (I would at least).

FWIW, our docs seem to be especially ugly among projects that use the furo theme. [Other](https://www.attrs.org/en/stable/overview.html) [projects](https://www.psycopg.org/psycopg3/docs/) [look](https://urllib3.readthedocs.io/en/latest/) much more similar to the old design.
