### ISSUE TITLE
Running script from Standart Input

### ISSUE THREAD

**Issue by naveen521kk** [ManimCommunity/manim#1506]
## Description of the proposed feature
Allowing input standard input should be a nice feature, where users can just pipe the script and manim would run. For, example
```sh
cat test.py | manim
```
or even better
```sh
curl -sL https://github.com/ManimCommunity/manim/raw/master/example_scenes/basic.py |  manim
```
but it isn't possible to do so currently, and it might be a nice feature to implement.

**Comment by Aathish04** [comment]
You can do this by supplying the file name as `-`.

For example:

`curl -sL https://github.com/ManimCommunity/manim/raw/master/example_scenes/basic.py |  manim -p -ql -a -`

**Comment by naveen521kk** [comment]
Ah, forgot that it exists.
