### ISSUE TITLE
Jupyter notebook cells should also show videos rendered with the `-t`flag (.mov)

### ISSUE THREAD

**Issue by kolibril13** [ManimCommunity/manim#1517]
Currently, when cells are rendered with the `-t` flag for transparent videos, it results in `.mov` files.
This can currently not be shown:
![image](https://user-images.githubusercontent.com/44469195/118362314-5838cb80-b58f-11eb-88b7-4ddd8c175672.png)
But this can be fixed easily, see here as a reference:
https://stackoverflow.com/questions/12521849/how-to-embed-a-mov-file-in-html

**Comment by ryanmccauley211** [comment]
I was trying to get the .mov files working, the suggestion in the link doesn't seem to work. I was reading that .mov aren't supported in html5? https://stackoverflow.com/questions/29732946/how-can-i-embed-my-own-mov-in-to-a-web-page.

Also tried using embed but also fails with "No video with supported format and MIME type found":

```
<embed id="embed1" src="media/jupyter/f9c39aa3c37ea1de10b2764a128af7ed070939d9.mov" type="video/quicktime" style="width:320px;height:240px;">
  <noembed>Your browser does not support this media object or the embed element.</noembed>
</embed>
```

**Comment by kolibril13** [comment]
Thanks for trying this, @ryanmccauley211 !
Maybe some JavaScript might be possible?
Or is this maybe browser dependent?
I am really not an expert in this.

**Comment by ryanmccauley211** [comment]
> Thanks for trying this, @ryanmccauley211 !
> Maybe some JavaScript might be possible?
> Or is this maybe browser dependent?
> I am really not an expert in this.

Yea it seems to be browser dependent, I had more success with using webm format that supports an alpha channel, it worked on firefox and chrome, but not on safari

**Comment by kolibril13** [comment]
Hmm, that is unfortunate with Safari, but still a good beginning.
I think a support for a few browsers is better than a support of no browser at all.
So feel free to make a pr with the changes in the ipymagic! :)

**Comment by ryanmccauley211** [comment]
> Hmm, that is unfortunate with Safari, but still a good beginning.
> I think a support for a few browsers is better than a support of no browser at all.
> So feel free to make a pr with the changes in the ipymagic! :)

Yes I will try to create a PR once ready, do you think we should add an alternative path for creating a .webm file instead of .mov when using jupyter, or create the .mov and then convert it to .webm in the magic class? I have only figured out how to do the latter so far but I am sure both ways are possible

**Comment by kolibril13** [comment]
Do we currently have a flag that creates an .webm file?
I remember that I once tried to upload animations to wikipedia, and the convention from mp4 to webm took minutes for relatively short videos, see also https://stackoverflow.com/questions/43612424/ffmpeg-convert-mp4-to-webm-very-slow
Both solutions that you suggest do not sound optimal for me, as I think that people would anticipate .mov files when using the -t flag.

**Comment by ryanmccauley211** [comment]
> Do we currently have a flag that creates an .webm file?
> I remember that I once tried to upload animations to wikipedia, and the convention from mp4 to webm took minutes for relatively short videos, see also https://stackoverflow.com/questions/43612424/ffmpeg-convert-mp4-to-webm-very-slow
> Both solutions that you suggest do not sound optimal for me, as I think that people would anticipate .mov files when using the -t flag.

I don't see any flags for that, what I was thinking is to use .mov by default when transparent is set, but if it is being launched through jupyter we encode it as a .webm file? As .mov isn't any use with jupyter. I was able to figure out how to create the webm instead of converting to webm, and yes it is very slow

**Comment by kolibril13** [comment]
> but if it is being launched through jupyter we encode it as a .webm file?
 I think that `-t` should always produce ".mov" files, as this could cause confusion for people when they see `.mov` files.
 Instead, I think there should be a new flag `-webm` that produces `.webm` files.
 The benefit would be:
 * jupyter cells with transparent outputs would be possible
 * Easy producing of webm files in the classical ide manim use (e.g. for producing animations for wikipedia)

**Comment by ryanmccauley211** [comment]
> > but if it is being launched through jupyter we encode it as a .webm file?
> > I think that `-t` should always produce ".mov" files, as this could cause confusion for people when they see `.mov` files.
> > Instead, I think there should be a new flag `-webm` that produces `.webm` files.
> > The benefit would be:
> 
> * jupyter cells with transparent outputs would be possible
> * Easy producing of webm files in the classical ide manim use (e.g. for producing animations for wikipedia)

Oh ok I get you, so adding the flag means we can also use .webm files in other contexts outside of jupyter, makes sense
