### ISSUE TITLE
Example for Annulus in documentation

### ISSUE THREAD

**Issue by kolibril13** [ManimCommunity/manim#1519]
This example still has no example for the documentation:
https://docs.manim.community/en/stable/reference/manim.mobject.geometry.Annulus.html#manim.mobject.geometry.Annulus
A submission for an example is greatly appreciated, and on top some more documentation of the parameters would be nice as well.

**Comment by JeroSQ** [comment]
Hey, I'd like to help with this. I made a quick example, which follows all the guidelines. Regarding the parameters, I think `mark_paths_closed` should be removed since it's not used for anything. I'm not sure how to submit an example and documentation of the parameters. Do I just post it here?

**Comment by Nikhil0504** [comment]
> Regarding the parameters, I think `mark_paths_closed` should be removed since it's not used for anything.

Hey check https://github.com/ManimCommunity/manim/pull/1552

**Comment by Darylgolden** [comment]
Fixed by #1599
