### ISSUE TITLE
Wait-animation adds an empty Mobject to the Scene

### ISSUE THREAD

**Issue by AntonBallmaier** [ManimCommunity/manim#1524]
## Description of bug / unexpected behavior
Playing a `Wait` animation (and therefore using `Scene.wait` adds an empty `Mobject` to the Scene:

```py
class WaitExample(Scene):
    def construct(self):
        print(self.mobjects) # []
        self.wait()
        print(self.mobjects) # [Mobject]
        self.play(Wait())
        print(self.mobjects) # [Mobject, Mobject]
```
The underlying problem is, that Animations without Mobects cannot exist right now - if they get non they create one themselves. This is definitely where the added Mobject comes from - I already tested that by giving that Mobject a special name...

Probably that should be fixed as a whole - `Wait` should not require a Mobject internally.

## Additional comments
I already tried simply pasing Wait the `remover=True` keyword and removing it's `clean_up_from_scene` method, but that didn't fix it.

**Comment by huguesdevimeux** [comment]
Moved to #3040
