### ISSUE TITLE
CLI output does not point to the right file/folder when rendering in a non-mp4 format

### ISSUE THREAD

**Issue by Darylgolden** [ManimCommunity/manim#1532]
## Description of bug / unexpected behavior
```
C:\Users\Daryl\manim-videos\manim-videos>manim --format gif circletest.py
Manim Community v0.6.0

[05/17/21 17:47:53] INFO     Animation 0 : Partial movie file written in {'C:\\Users\\Daryl\\m scene_file_writer.py:401
                             anim-videos\\manim-videos\\media\\videos\\circletest\\1080p60\\pa
                             rtial_movie_files\\CircleTest\\450974505_3098578322_3198892316.mp
                             4'}
[05/17/21 17:47:54] INFO                                                                       scene_file_writer.py:585
                             File ready at C:\Users\Daryl\manim-videos\manim-videos\media\vide
                             os\circletest\1080p60\CircleTest.mp4

                    INFO     Rendered CircleTest                                                           scene.py:217
                             Played 1 animations
```
The output points to `CircleTest.mp4` while it should actually be `CircleTest_ManimCE_v0.6.0.gif` (also the name is different, not sure if this is intended). `--format png` also points to the same wrong place when it should point to `media\images\circletest`. 

## How to reproduce the issue

<details><summary>Code for reproducing the problem</summary>

```py
from manim import *

class CircleTest(Scene):
    def construct(self):
        a = Circle()
        self.play(Create(a))
```

</details>

## Additional media files

<details><summary>Images/GIFs</summary>

</details>

## Logs
<details><summary>Terminal output</summary>

```
PASTE HERE OR PROVIDE LINK TO https://pastebin.com/ OR SIMILAR
```

</details>

## System specifications

<details><summary>System Details</summary>

- OS (with version, e.g Windows 10 v2004 or macOS 10.15 (Catalina)):
- RAM:
- Python version (`python/py/python3 --version`):
- Installed modules (provide output from `pip list`):
```
PASTE HERE
```
</details>

<details><summary>LaTeX details</summary>

+ LaTeX distribution (e.g. TeX Live 2020):
+ Installed LaTeX packages:

</details>

<details><summary>FFMPEG</summary>

Output of `ffmpeg -version`:

```
PASTE HERE
```
</details>

**Comment by ryanmccauley211** [comment]
I could start looking at this issue if nobody else is? What is the expected behaviour for --format "png"? I can see setting this format means that it does save frames as images in the 'media\images\circletest' but will still output an mp4 video based on the 'write_to_movie' flag.

**Comment by Darylgolden** [comment]
I believe the expected behavior should just be to output PNGs. It doesn't make sense to also output an mp4, IMO.

**Comment by ryanmccauley211** [comment]
I agree, but having a flag 'write_to_movie' seems redundant when there is --format mp4, and having both the option to write_to_movie and setting the format to png or gif makes it less clear what the user wants to do. Are there any objections to deprecating write_to_movie and using --format mp4 instead?

It seems that adding the version only to gif filenames was intentional as gifs can't have the manim version set as metadata [984](https://github.com/ManimCommunity/manim/pull/984)
