### ISSUE TITLE
Installation of miktex and ffmpeg on Travis/windows

### ISSUE THREAD

**Issue by huguesdevimeux** [ManimCommunity/manim#154]
Not an issue with the code itself, but more about setting up of tests with travis.

Basically the title. I'm building a bunch of tests with pytest (#133), that are working fine. 
The problem is with travis, and more particularly with the Windows environment.

It seems to be impossible to install both miktex and FFmpeg on travis/windows. 

- For miktex, `miktexsetup` (the miktex setup utility, see https://docs.miktex.org/manual/miktexsetup.html) does not work and constantly returns `miktexsetup.exe: MiKTeX encountered an internal error.` See the travis build log : https://travis-ci.org/github/huguesdevimeux/trytravis-manim/builds/697200289 . 
I think that we tried literally everything to fix that (see the others travis build of the repository). I surrender, but if you have an idea how to fix it, please say it. But my opinion is that this is related to the windows environment, and not miktex. 

- Concerning Ffmpeg : The problem is more serious since without Ffmpeg any end-to-end test is impossible. The error is : `AVICAP32.dll: cannot open shared object file: No such file or directory`. Note that the dll name changes when using either the chocolatey version, the shared or static version. That's why I think the issue is related to the windows environment that Travis provides and not ffmpeg itself. See the travis log for more info : https://travis-ci.org/github/huguesdevimeux/trytravis-manim/builds/697950048

So far I see two possibilities : 
- Either a genius, a god, a legend knows how to fix this mess and everything would go fine. 
- Or we just skip the end-to-end tests on windows. 

Feel free to react :)

**Comment by PhilippImhof** [comment]
Stupid question, but have you thought about installing TeXLive instead of Miktex?

**Comment by Aathish04** [comment]
> Stupid question, but have you thought about installing TeXLive instead of Miktex?

@PhilippImhof Ha, what a coincidence. I'm trying to get that functioning right now.

**Comment by PhilippImhof** [comment]
w.r.t. ffmpeg, I just found the following, but you might have seen it already:

https://travis-ci.community/t/make-running-gui-multimedia-apps-available-in-windows/1557

**Comment by leotrs** [comment]
I vote we skip these tests on Windows. It's not even officially supported by Travis in any case.

**Comment by huguesdevimeux** [comment]
> Stupid question, but have you thought about installing TeXLive instead of Miktex?

(Not stupid at all :) ) . Yes, I thought about that **but** I don't see the utility since if FFmpeg does not work, we won't use latex in any way since no end-to-end test can be run. Pinging @Aathish04 . 


> w.r.t. ffmpeg, I just found the following, but you might have seen it already:
> 
> https://travis-ci.community/t/make-running-gui-multimedia-apps-available-in-windows/1557

Well, I didn't read that! Thank you. So if I correctly understood it is impossible to run FFmpeg on windows server, isn't it?

If yes, I think we should simply skip those tests on windows.

**Comment by Aathish04** [comment]
> > https://travis-ci.community/t/make-running-gui-multimedia-apps-available-in-windows/1557
> 
> Well, I didn't read that! Thank you. So if I correctly understood it is impossible to run FFmpeg on windows server, isn't it?
> 
> If yes, I think we should simply skip those tests on windows. 

Correct me if I'm wrong, but that thread only spoke about trying to install and use GUI applications right?

Since FFMPEG is wholly command line based, we should have no problem installing it...

**Comment by huguesdevimeux** [comment]
@Aathish04 I think that the article is also about multimedia apps - as ffmpeg

**Comment by PhilippImhof** [comment]
The thread speaks about GUI and multimedia apps. I found that feature request thread while reading this one:

https://travis-ci.community/t/any-chance-of-providing-an-environment-with-desktop-experience/1024/5

> I’m trying to test a project that depends on FFmpeg. Unfortunately, FFmpeg doesn’t seem to work on the Windows image

**Comment by huguesdevimeux** [comment]
@PhilippImhof Ok so it's basically impossible to use ffmpeg on travis/windows. So I will skip these tests. 
Thank you very much !
