### ISSUE TITLE
Camera issues in class with GraphScene, MovingCameraScene

### ISSUE THREAD

**Issue by christosk92** [ManimCommunity/manim#159]
If you have a class that inherits both a GraphScene and MovingCameraScene, you cannot call:
`self.camera_frame.set_width,1`
You have to call the camera using:
`self.camera.frame.set_width(1) `
Example:

```
from manimlib.imports import *

class class_name(GraphScene, MovingCameraScene):`
    def construct(self):
        self.camera_frame.set_width,1
```
will throw an error:
`AttributeError: 'class_name' object has no attribute 'camera_frame'`

**Comment by kilacoda** [comment]
Try adding a `setup` method which calls `MovingCameraScene.setup()` and `GraphScene.setup()`, like this:
```py
def setup(self):
    GraphScene.setup()
    MovingCameraScene.setup()
```

**Comment by leotrs** [comment]
@christosk92, were you able to try out kilacoda's suggestion?

**Comment by christosk92** [comment]
@leotrs I'm sorry sorry for not responding. 

Last time I used manim was over a month ago. I'm fairly certain I fixed the issue from kilacoda's response.

**Comment by leotrs** [comment]
Thanks for getting back to us :)
