### ISSUE TITLE
Deprecate `Annulus` in favor of calling it `Disc`

### ISSUE THREAD

**Issue by WampyCakes** [ManimCommunity/manim#1600]
## Enhancement proposal

Title says it. Annulus is a name that a lot of people don't know for a shape everyone knows. I think Disc makes more sense. By calling it Annulus, a legitimately useful feature will see less use as people who see the word in the docs will pass right by it.

**Comment by behackl** [comment]
I'd rather stick with annulus as the mathematically correct notion. A disc -- at least in the terminology I am familiar with -- usually refers to a circle together with its interior.

I still agree with the problem you mention: currently, a lot of shapes can't be discovered easily. To address this, I'd like to generously refactor the module structure of the library. (But that's a separate discussion.)

**Comment by WampyCakes** [comment]
Hmm, I see how it could be either shape. I think of a disc like a CD (compact _disc_) where it's defined by an inner and outer radius. But I could also see how it's like the shape of a frisbee.

**Comment by behackl** [comment]
Now I see how you got to disk. :-)

In any case, that doesn't change the fact that disk is a well-established mathematical term -- see httpss://en.m.wikipedia.org/wiki/Disk_(mathematics) -- and as a mathematical animation library, I'd find it odd if we didn't stick to that.

(Just my 2 cents though, further opinions are welcome!)

**Comment by WampyCakes** [comment]
I would be okay with staying with the mathematically correct term if we have satisfactory plans to resolve the main problem of ease of discovery in manim. @behackl, how would you propose we "generously refactor the module structure of the library" to solve the problem?

**Comment by behackl** [comment]
Basically, the `mobject` module is a gigantic mess. I'll work on a detailed suggestion soon, but I think this particular situation would already be improved by a lot by splitting up the `geometry` module and moving all basic shapes into `mobject.shapes` or something like that.

After restructuring, the second thing we could do to expose these modules better is either introducing a separate menu for the sidebar for polished module documentations, or going one step further and directly selling them as tutorials, such that the sidebar entry "Tutorial: Shapes" would link to what is currently <https://docs.manim.community/en/stable/reference/manim.mobject.geometry.html#module-manim.mobject.geometry> (but that would need to be extended of course).

**Comment by WampyCakes** [comment]
Closing as I think that's a better solution to the problem, however eventual it may be
