### ISSUE TITLE
Ticks on axes not symmetrical with certain range and step values

### ISSUE THREAD

**Issue by ryanmccauley211** [ManimCommunity/manim#1604]
## Description of bug / unexpected behavior

When using the Axes class, the ticks are created based on the x_range / y_range and the steps. The steps default to 1 and for certain ranges the ticks will not be symmetrical across the x and y-axis. I am not sure if this is a bug I am reporting or if this is expected, but I think it would be an improvement to have the ticks be symmetrical across the axes.

## Expected behavior

When determining the tick locations, to adjust their positions regardless of the step to be symmetrical across the axes. In this example I was using pi for min and max values for each axis, with the default step size of 1.

## How to reproduce the issue

<details><summary>Code for reproducing the problem</summary>

```py
class AxesExample(Scene):

    def construct(self):
        axes = Axes(
            x_range=[-PI, PI],
            y_range=[-PI, PI]
        )
        self.add(axes)
```

</details>

## Additional media files

<details><summary>Images/GIFs</summary>

![AxesExample_ManimCE_v0 5 0](https://user-images.githubusercontent.com/32387857/120207746-b539b000-c224-11eb-9fc1-231e9505b5eb.png)

</details>

## Logs
<details><summary>Terminal output</summary>

```
Manim Community v0.5.0

[05/31/21 15:26:27] INFO                                scene_file_writer.py:585
                             File ready at /Users/ryan/                         
                             PycharmProjects/manim-comm                         
                             unity/manim/media/images/i                         
                             ntegrals/AxesExample_Manim                         
                             CE_v0.5.0.png                                      
                                                                                
                    INFO     Rendered AxesExample                   scene.py:220
                             Played 0 animations                                
                    INFO     Previewed File at: /Users/ryan/Pych file_ops.py:101
                             armProjects/manim-community/manim/m                
                             edia/images/integrals/AxesExample_M                
                             animCE_v0.5.0.png 
```

</details>

## System specifications

<details><summary>System Details</summary>

- OS (with version, e.g Windows 10 v2004 or macOS 11.2.3 (Big Sur)):
- RAM: 8gb
- Python version (`python/py/python3 --version`): 3.7.4
- Installed modules (provide output from `pip list`):
```
Package             Version
------------------- -----------
arrow               0.17.0
attrs               20.3.0
cairocffi           1.2.0
certifi             2020.12.5
cffi                1.14.4
chardet             4.0.0
click               7.1.2
click-default-group 1.2.2
cloup               0.7.0
colorama            0.4.4
colour              0.1.5
commonmark          0.9.1
decorator           4.4.2
ffprobe             0.5
glcontext           2.3.3
idna                2.10
importlib-metadata  3.1.0
iniconfig           1.1.1
Jinja2              2.11.2
jinja2-time         0.2.0
make                0.1.6.post2
manim               0.5.0
manimce             0.1.0
ManimPango          0.2.4
mapbox-earcut       0.12.10
MarkupSafe          1.1.1
moderngl            5.6.4
moderngl-window     2.3.0
multipledispatch    0.6.0
networkx            2.5
numpy               1.19.4
packaging           20.7
pangocairocffi      0.4.0
pangocffi           0.8.0
Pillow              6.1.0
pip                 20.3.3
pluggy              0.13.1
progressbar         2.5
py                  1.9.0
pycairo             1.20.0
pycparser           2.20
pydub               0.24.1
pyglet              1.5.15
Pygments            2.7.2
pyparsing           2.4.7
pyrr                0.10.3
pytest              6.1.2
python-dateutil     2.8.1
requests            2.25.1
rich                6.2.0
scipy               1.5.4
setuptools          50.3.2
six                 1.15.0
toml                0.10.2
tqdm                4.54.0
typing-extensions   3.7.4.3
urllib3             1.26.4
watchdog            2.1.2
zipp                3.4.0
```
</details>

<details><summary>LaTeX details</summary>

+ LaTeX distribution (e.g. TeX Live 2020):
+ Installed LaTeX packages:

</details>

<details><summary>FFMPEG</summary>

Output of `ffmpeg -version`:

```
ffmpeg version 4.3.1-tessus  https://evermeet.cx/ffmpeg/  Copyright (c) 2000-2020 the FFmpeg developers
built with Apple clang version 11.0.0 (clang-1100.0.33.17)
configuration: --cc=/usr/bin/clang --prefix=/opt/ffmpeg --extra-version=tessus --enable-avisynth --enable-fontconfig --enable-gpl --enable-libaom --enable-libass --enable-libbluray --enable-libdav1d --enable-libfreetype --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libmysofa --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopus --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvmaf --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-version3 --pkg-config-flags=--static --disable-ffplay
libavutil      56. 51.100 / 56. 51.100
libavcodec     58. 91.100 / 58. 91.100
libavformat    58. 45.100 / 58. 45.100
libavdevice    58. 10.100 / 58. 10.100
libavfilter     7. 85.100 /  7. 85.100
libswscale      5.  7.100 /  5.  7.100
libswresample   3.  7.100 /  3.  7.100
libpostproc    55.  7.100 / 55.  7.100
```
</details>

**Comment by PaulCMurdoch** [comment]
Adjusting the code to be an integer multiple of pi or divided by an integer appears to fix the asymmetry.

```py
class Axe(GraphScene):
    def construct(self):
        axes = Axes(
            x_range=[-PI,PI,PI/8],
            y_range=[-PI,PI,PI/3]
        )
        self.add(axes)  
```
![scriptoutput.png](https://user-images.githubusercontent.com/76829691/120230318-12316800-c21d-11eb-901e-70d6a3c303c0.png)

**Comment by PaulCMurdoch** [comment]
I gather that currently Axes steps up from an endpoint and steps up until it is past the other endpoint. To fix the symmetry it would have to step forward from 0 to an endpoint then step backwards. Which if someone could implement I think that would look good.

Another way would be to automatically adjust the step size based on the bounds but that would not work if the bounds were asymmetric/didn't have an easy pattern to them.

**Comment by ryanmccauley211** [comment]
> I gather that currently Axes steps up from an endpoint and steps up until it is past the other endpoint. To fix the symmetry it would have to step forward from 0 to an endpoint then step backwards. Which if someone could implement I think that would look good.
> 
> Another way would be to automatically adjust the step size based on the bounds but that would not work if the bounds were asymmetric/didn't have an easy pattern to them.

Yes it currently operates across the whole axis so wouldn't take the origin into consideration.

`return np.arange(self.x_min, x_max, self.x_step)`

I was playing around with it and tried your' first suggestion - going from the origin to each endpoint. It seems to work well so far, I could raise a PR for it when I have tested it more

**Comment by PaulCMurdoch** [comment]
> I was playing around with it and tried your' first suggestion - going from the origin to each endpoint. It seems to work well so far, I could raise a PR for it when I have tested it more

That sounds great.
