### ISSUE TITLE
Improve TransformMatchingAbstractBase to support different types of objects

### ISSUE THREAD

**Issue by JeroSQ** [ManimCommunity/manim#1609]
## Enhancement proposal

The first line of `TransformMatchingAbstractBase __init__()` method contains an `assert` keyword to make sure the `mobjects` are of the same type. This implementation makes using the class with submobjects of `Tex` or `MathTex` a bit difficult and it just doesn't look right. Here's what I mean: 

I've made this class:

```py
class TransformTest(Scene):
    def construct(self):
        text1 = Tex("What's that? ", "the ", "morse code")
        text2 = Tex("Look! ", "here come dots").next_to(text1, DOWN)

        self.add(text1, text2[0])
        self.wait(0.5)
        #self.play(TransformMatchingShapes(text1[1:], text2[1])) **This does not works (throws assertion error)**
        self.play(TransformMatchingShapes(text1[1:], text2[1:])) #**This does**
```
The line that is commented throws an `assertion error` because the first object is a `VGroup` and the second one is a `SingleStringMathTex`. But the line after that does work. So basically that `assert` statement is preventing the user from making certain transforms which are (and should be IMO) possible. If some extra logic is added to `TransformMatchingAbstractBase`, this kind of issue would be solved.

Here's another example:

```py
class TransformTest(Scene):
    def construct(self):

        text3 = Tex("Result", "eleven", " plus", " two", color=RED).next_to(text2, DOWN)
        text4 = Tex("twelve plus one", color=RED).next_to(text3, DOWN)

        self.add(text3, text4[0])
        self.wait(0.5)
        #self.play(TransformMatchingShapes(text3[1:], text4)) **This doesn't work**
        self.play(TransformMatchingShapes(text3[1:], text4[:])) #**This does**
        self.wait(0.5)
```

Clearly the Transfroms are possible, but I don't think the user should need to add weird syntax that isn't necessary just so the program doesn't spit out an error.

## Additional comments

I'm using `TransformMatchingShapes` here but of course this also affects `TransformMatchingTex` since they share the same parent class.

**Comment by behackl** [comment]
I agree, the assertion checking that both mobjects are of the same type can probably just be removed. For `TransformMatchingTex` we have a separate check in place anyways.
