### ISSUE TITLE
Improving travis.yml

### ISSUE THREAD

**Issue by huguesdevimeux** [ManimCommunity/manim#161]
As pointed out as a suggestion in #133, we could shorten and improve `travis.yml`, by moving some instructions into `.sh` (or `.bat`) files. 
This has already been done for the Linux jobs, see `linux.sh`. It is executed with 
```
before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then chmod +x ./.travis/osx.sh; sh ./.travis/osx.sh; fi
```

We should to that for both osx and windows.

**Comment by naveen521kk** [comment]
Look into https://travis-ci.com/github/ManimCommunity/manim/jobs/352635549#L46
Environmental variables are already defined by choco.
You can remove the lines at 
https://github.com/ManimCommunity/manim/blob/4b6492b0e7e7e4ae7e35938662571ad765027f3c/.travis.yml#L97
Also, we should test 32 bit also!

**Comment by huguesdevimeux** [comment]
Feel free to submit a PR :)

**Comment by safinsingh** [comment]
@naveen521kk apparently sometimes chocolatey doesn't update the PATH on the python install, so I had to add it manually. I think we should keep it there as a safety measure

**Comment by naveen521kk** [comment]
If you check out the line I pointed above in log and
  https://travis-ci.com/github/ManimCommunity/manim/jobs/352635549#L51
You could understand what I meant @safinsingh

**Comment by leotrs** [comment]
@naveen521kk instead of saying things like "read this to understand what I mean", could you please kindly say here exactly what you mean? It's quite the hassle to have to read half a dozen past comments, and then navigate to another URL in order to understand what you mean. Let's try to keep the discussion here as self-contained as possible.

**Comment by eulertour** [comment]
This is now obsolete with #196.
