### ISSUE TITLE
CoordinateSystem method: get_line_from_axis_to_point() not working.. 

### ISSUE THREAD

**Issue by bikashsinghgurung** [ManimCommunity/manim#1612]
## Description of bug / unexpected behavior
I wanted to draw a horizontal line and vertical line from a point to axes. 
I tried with the method get_line_from_axis_to_point() to draw.
But this didn't work.
`
class AxesEx(Scene):        
    def construct(self):
        myAxis = Axes(
            x_range=[-3, 5],
            y_range=[-4, 5],
            axis_config={
                'include_numbers':True,
            }
        )
        dot = Dot(color=ORANGE)
        dot.move_to(myAxis.c2p(3,4))
        self.add(myAxis, dot)

        hline = myAxis.get_line_from_axis_to_point(0, myAxis.c2p(3,4))
        self.add(hline)
        vline = myAxis.get_line_from_axis_to_point(1, myAxis.c2p(3,4))
        self.add(vline)`

OUTPUT:
![AxesEx_ManimCE_v0 6 0](https://user-images.githubusercontent.com/85176984/120341990-18a40a80-c317-11eb-8f00-1c5892aae6de.png)

I rechecked calculating the point of projection by a given point on the axes using
method: get_projection(point) which is not giving correct result.
 
I tried checking get_projection() method on a Line() and also on a NumberLine(). It worked perfectly..
But same method didn't work on axes of Axes().

![issue2](https://user-images.githubusercontent.com/85176984/120339036-7be06d80-c314-11eb-9913-e4226aef5ba1.png)

CAN SOMEBODY HELP???
I am new to manim as well as this github

**Comment by abhi3019** [comment]
Hi @bikashsinghgurung, looks like you are using the version `v0.6.0`? This issue no longer exists on `v0.7.0` (which was released just yesterday I believe). Please upgrade to `v0.7.0` (`pip install -U manim` if you've installed manim via `pip`) and it should work fine.

**Comment by bikashsinghgurung** [comment]
Thanks @abhi3019 . It worked after upgrading to v0.7.0
![AxesEx_ManimCE_v0 7 0](https://user-images.githubusercontent.com/85176984/120464811-0f6d7900-c3bd-11eb-8d0c-21f148544a55.png)
