### ISSUE TITLE
Use "color = XXX" to set color for SVGMobject does not work

### ISSUE THREAD

**Issue by Matheart** [ManimCommunity/manim#1615]
## Description of bug / unexpected behavior

I try to use "color = xxx" to set the color of svg file but it fails, only black background is displayed  
`good = SVGMobject(path + "good.svg", color=WHITE)`
![image](https://user-images.githubusercontent.com/47732475/120418011-66aa2400-c392-11eb-9626-fa4ce6817731.png)

But while I use set_color method to set the color, it works
`good = SVGMobject(path + "good.svg").set_color(WHITE)`
![5)TR5W8BXR17FN2Y069NS9Y](https://user-images.githubusercontent.com/47732475/120418158-98bb8600-c392-11eb-8886-ff8d9577c3bb.png)

## Additional comments
Is this because the parameters of SVGMobject do not contain "color"? 
To solve this issue, I think the solution is adding color as one of the parameters in SVGMobject, and pass the parameter to VMobject in: `        VMobject.__init__(
            self, fill_opacity=fill_opacity, stroke_width=stroke_width, **kwargs
        )`

**Comment by kilacoda** [comment]
Could you share the SVG so others can test it out?

**Comment by Matheart** [comment]
[good.txt](https://github.com/ManimCommunity/manim/files/6589658/good.txt)
I try to upload the svg file but github says it does not support .svg, so I change .svg to .txt lol, during testing you should change it back to .svg

**Comment by friedkeenan** [comment]
I believe [this line](https://github.com/ManimCommunity/manim/blob/e85599e9829460948ac63f620a9bc737e8b7a5c7/manim/mobject/types/vectorized_mobject.py#L134) may be the culprit. Seems to me like it should just be `if propagate_colors:`

**Comment by friedkeenan** [comment]
Or actually I'm not so sure, it should be passed along by `family=propagate_colors` in the function calls above that line

**Comment by ryanmccauley211** [comment]
This issue seems more widespread than just SVGMobject:

Going by the this code it seems the color should set both fill and stroke:

```py
        self.set_fill(
            color=self.fill_color or self.color,
            opacity=self.fill_opacity,
            family=propagate_colors,
        )
        self.set_stroke(
            color=self.stroke_color or self.color,
            width=self.stroke_width,
            opacity=self.stroke_opacity,
            family=propagate_colors,
        )
```

Using `color` only sets the stroke:

```py
class Example(Scene):
    def construct(self):
        rect = Rectangle(color=GREEN)
        self.add(rect)
```

![Example_ManimCE_v0 6 0](https://user-images.githubusercontent.com/32387857/121774028-ce712380-cb77-11eb-934d-9f366714568a.png)

Using `fill_color` doesn't work neither:

```py
class Example(Scene):
    def construct(self):
        rect = Rectangle(fill_color=GREEN)
        self.add(rect)
```

![Example_ManimCE_v0 6 0](https://user-images.githubusercontent.com/32387857/121774055-109a6500-cb78-11eb-85c4-73854c20c3a2.png)

**Comment by ryanmccauley211** [comment]
Actually ignore above, the rectangle not filled is because the opacity still defaults to 0 when fill is set. I think I found what is causing this issue, I will try to raise a PR soon. It is because in style_utils the svg gets default values so `color` gets ignore:

```
SVG_DEFAULT_ATTRIBUTES: Dict[str, str] = {
    "fill": "black",
    "fill-opacity": "1",
    "stroke": "none",
    "stroke-opacity": "1",
}
```
