### ISSUE TITLE
Adding setting up new test instruction 

### ISSUE THREAD

**Issue by huguesdevimeux** [ManimCommunity/manim#162]
Now that #133 will be merged soon, we have to think of how to explain to future contributors how to set up tests if a new functionality is added. 

But I don't know where/how to do it. Maybe in the wiki ?

**Comment by Aathish04** [comment]
I would suggest mentioning adding tests in https://github.com/ManimCommunity/manim/blob/master/CONTRIBUTING.md
and https://github.com/ManimCommunity/manim/blob/master/README.md

And adding detailed steps in the Wiki.

**Comment by leotrs** [comment]
Does #155 close this?

**Comment by huguesdevimeux** [comment]
Yes !
