### ISSUE TITLE
Changing name of Manim community 

### ISSUE THREAD

**Issue by huguesdevimeux** [ManimCommunity/manim#163]
I don't see an issue about that here, so I open one. 

We have been talking about changing the name of this fork for something more explicit, like `manim-ce`. 
Since this is quite an important change, we have to reach a consensus here. 

So, what do you think ?

Related to #149

**Comment by Aathish04** [comment]
I would suggest mentioning adding tests in https://github.com/ManimCommunity/manim/blob/master/CONTRIBUTING.md
and https://github.com/ManimCommunity/manim/blob/master/README.md

And adding detailed steps in the Wiki.

**Comment by huguesdevimeux** [comment]
@Aathish04 Thank you, but I think you're in the wrong issue. Maybe you want #162 ;)

**Comment by Aathish04** [comment]
> @Aathish04 Thank you, but I think you're in the wrong issue. Maybe you want #162 ;)

Ah, GitHub mobile messed up...

I'll move it over.

**Comment by kolibril13** [comment]
For me, it feels like this is not very pretty:
```py
from manim_ce import *

class Test(Scene):
    def construct(self):
        dot = Dot()
        self.add(dot)
        self.wait(1)

from pathlib import Path
if __name__ == "__main__":
    script = f"{Path(__file__).resolve()}"
    os.system(f"manim_ce  -l -p " + script )
```
Also the PEP 8 says:
> Modules should have short, all-lowercase names. Underscores can be used in the module name if it improves readability.
Python packages should also have short, all-lowercase names, although the use of underscores is discouraged.
https://www.python.org/dev/peps/pep-0008/#package-and-module-names

Can't we just leave it with manim, or is then the risk of confusing it with Grant's version?
Other ideas: manimce, manimy ,manimp (last two would have the advantage of characters that are not on the same levels as the others, and therefore easy to distinct.
But in case everyone else is fine with `manim_ce` we can leave it like that.

**Comment by leotrs** [comment]
I believe the library itself should be called manim. However, the package could (should?) be called something else, at least as long as 3b1b's version and ours coexist side-by-side.

**Comment by Aathish04** [comment]
The `manimce` name is open and is "owned" by us, so we can use that.
Honestly, I was thinking we could make a separate package `manim3b1b` for Grants fork and use the `manim` or `manimlib` name for this repo.

**Comment by leotrs** [comment]
Related to this: how are we going to refer to the library in official documentation?

+ Manim
+ manim
+ manimCE
+ manim-ce
+ Manim Community Edition
+ ?

**Comment by Aathish04** [comment]
I think we can just use `Manim`, since 3b1b's manim doesn't have much documentation to speak of anyway, and there's little to no chance of people confusing the two.

**Comment by leotrs** [comment]
Ok so how about this. When there is a possible ambiguity, let's use manim CE. When there is no ambiguity possible, let's just use manim.

**Comment by leotrs** [comment]
Feel free to reopen if you disagree :)
