### ISSUE TITLE
include_numbers does not consider step size

### ISSUE THREAD

**Issue by ryanmccauley211** [ManimCommunity/manim#1653]
## Description of bug / unexpected behavior

When using NumberLine the step size is not taken into consideration when adding numbers, as decimal config defaults to 0 decimal places it results in axis with duplicate numbers:

![AxesExample_ManimCE_v0 6 0](https://user-images.githubusercontent.com/32387857/121186653-3adde100-c85f-11eb-9be3-334fb1907995.png)

## Expected behavior

I would expect NumberLine to consider the step size when outputting numbers, as a user is unlikely to use a step size of 0.5 but still want the numbers to be output with 0 decimal places

## How to reproduce the issue

Leave the decimal config to the default values, set the include_numbers flag to True and step size to a decimal value.

<details><summary>Code for reproducing the problem</summary>

```py
class AxesExample(Scene):

    def construct(self):
        axes = Axes(
            x_range=[-2, 2, 0.5],
            y_range=[-2, 2, 1],
            x_length=10,
            axis_config={"color": GREEN},
            x_axis_config={
                "include_numbers": True
            },
            y_axis_config={
                "include_numbers": True
            },
            tips=False,
        )
        self.add(axes)
```

</details>

## Additional media files

<details><summary>Images/GIFs</summary>

</details>

## Logs
<details><summary>Terminal output</summary>

```
PASTE HERE OR PROVIDE LINK TO https://pastebin.com/ OR SIMILAR
```

</details>

## System specifications

<details><summary>System Details</summary>

- OS (with version, e.g Windows 10 v2004 or macOS 10.15 (Catalina)):
- RAM:
- Python version (`python/py/python3 --version`):
- Installed modules (provide output from `pip list`):
```
PASTE HERE
```
</details>

<details><summary>LaTeX details</summary>

+ LaTeX distribution (e.g. TeX Live 2020):
+ Installed LaTeX packages:

</details>

<details><summary>FFMPEG</summary>

Output of `ffmpeg -version`:

```
PASTE HERE
```
</details>

**Comment by JeroSQ** [comment]
The easy fix for this would be dynamically setting the `num_decimal_places` default but there's a comment that is kind of against that. So maybe it's intended: 
```py
# avoid mutable arguments in defaults
if decimal_number_config is None:
    decimal_number_config = {
        "num_decimal_places": 0,
        ...
```

**Comment by hydrobeam** [comment]
That purpose of the comment was to explain why values are being initialized in that manner (setting them in the `__init__` and not the class definition). My editor was raising some warning about it and I looked into it a bit and it can in theory cause some issues (not sure if they're applicable to manim though). 

Having `num_decimal_places` default to the number of decimal places in the `x_step` would be a good idea.

**Comment by ryanmccauley211** [comment]
Ok great, I will raise a PR for this soon
