### ISSUE TITLE
'include_numbers' displaces objects in coordinate plane

### ISSUE THREAD

**Issue by ryanmccauley211** [ManimCommunity/manim#1662]
## Description of bug / unexpected behavior

In Axes the config `include_numbers` seems to affect positioning of objects. Position of the vector is as expected when not using `include_numbers`

```py
class Example2(Scene):

    def construct(self):
        axes = Axes()
        f_vec = Vector(axes.coords_to_point(np.cos(45 * PI / 180), np.sin(45 * PI / 180)))
        f_vec.set_stroke(width=2.0)

        self.add(axes, f_vec)
```

![Example2_ManimCE_v0 6 0](https://user-images.githubusercontent.com/32387857/121412320-7ad6be00-c95c-11eb-9e1f-c95b6c2e3eb9.png)

If I change the code to include numbers the vector is now displaced:

```py
class Example2(Scene):

    def construct(self):
        axes = Axes(axis_config={'include_numbers': True})
        f_vec = Vector(axes.coords_to_point(np.cos(45 * PI / 180), np.sin(45 * PI / 180)))
        f_vec.set_stroke(width=2.0)

        self.add(axes, f_vec)
```

![Example2_ManimCE_v0 6 0](https://user-images.githubusercontent.com/32387857/121412483-ace82000-c95c-11eb-9218-445261b04164.png)

## Expected behavior

I would expect to be able to change config without it affecting the positions of objects in the coordinate plane that have been resolved with `coords_to_point`

## How to reproduce the issue

<details><summary>Code for reproducing the problem</summary>

```py
class Example2(Scene):

    def construct(self):
        axes = Axes(axis_config={'include_numbers': True})
        f_vec = Vector(axes.coords_to_point(np.cos(45 * PI / 180), np.sin(45 * PI / 180)))
        f_vec.set_stroke(width=2.0)

        self.add(axes, f_vec)
```

</details>

## Additional media files

<details><summary>Images/GIFs</summary>

![Example2_ManimCE_v0 6 0](https://user-images.githubusercontent.com/32387857/121412483-ace82000-c95c-11eb-9218-445261b04164.png)
</details>

## Logs
<details><summary>Terminal output</summary>

```
PASTE HERE OR PROVIDE LINK TO https://pastebin.com/ OR SIMILAR
```

</details>

## System specifications

<details><summary>System Details</summary>

- OS (with version, e.g Windows 10 v2004 or macOS 10.15 (Catalina)):
- RAM:
- Python version (`python/py/python3 --version`):
- Installed modules (provide output from `pip list`):
```
PASTE HERE
```
</details>

<details><summary>LaTeX details</summary>

+ LaTeX distribution (e.g. TeX Live 2020):
+ Installed LaTeX packages:

</details>

<details><summary>FFMPEG</summary>

Output of `ffmpeg -version`:

```
PASTE HERE
```
</details>

## Additional comments

I am also thinking is there a way of improving the integration of other mobjects into coordinate planes? Such as adding them as submobjects and automatically resolving their position to the correct coordinates?

**Comment by hydrobeam** [comment]
I opened #1664 to address this. But after some testing, I think c2p is just broken rn...

**Comment by ryanmccauley211** [comment]
Great nice work! I tried playing with your branch locally and seems to be working really well now!
