### ISSUE TITLE
Write Change Log

### ISSUE THREAD

**Issue by naveen521kk** [ManimCommunity/manim#167]
It would be great if we write changelog in a file after each commit so we and also other could know what really changed out.

**Comment by leotrs** [comment]
I want to bump this -- we should take this more seriously now that config and tests are up and running.

**Comment by leotrs** [comment]
Update: please also remember to use the [`..deprecated` directive](https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#directive-deprecated) in your docstrings if your changes require it. In this way, it will be easier to generate the changelog later.

**Comment by leotrs** [comment]
Awesome! Now we just have to remember (and remind each other) to add lines to the changelog on each PR merge.

**Comment by naveen521kk** [comment]
> add lines to the changelog on each PR merge.

Maybe a bot or something?
