### ISSUE TITLE
Allow non-numerical values to be passed into `add_numbers`

### ISSUE THREAD

**Issue by hydrobeam** [ManimCommunity/manim#1672]
## Description of proposed feature

Sometimes you want more than just numbers to be added to a set of `Axes` or `NumberPlane`. For example, days of the week (Monday, Tuesday, Wednesday). 

I think this could be done by passing a dictionary consisting of a point on the `NumberLine` with the  label that is at that point. `{1: "Monday", 2: "Tuesday"}`

## How can the new feature be used?

Expands the functionality of a `NumberLine` which extends over into `coordinate_systems.py`. Would also be useful for adding dates to a particular axis and showing change over that period (`2021-03-01, 2021-03-02`) which is currently not possible. 

## Additional comments

This functionality could be added to a new function.

**Comment by icedcoffeeee** [comment]
This is a good feature! One thing I'd like to add: maybe make latex symbol of pi be at the intervals whenever the step given is pi? since those sort of graphs are common. I can see that coming from this feature also.

**Comment by hydrobeam** [comment]
That'd be a little challenging to handle automatically since `PI` just refers to an actual number. I'd prefer if the user just handled it on their own.
