### ISSUE TITLE
Add support for Inkscape SVGs

### ISSUE THREAD

**Issue by cobordism** [ManimCommunity/manim#168]
**Situation:**
I have a maths paper. I run pdf2svg or dvisvgm. I modify the svg with inkscape just minimally (for example I change the grouping of elements). I try to load it with SVGMobject. This fails.

**Cause of the Problem:**
Manim does not expect `g` and `defs` tags to have an `id`. 
They have no id on dvisvgm output, but they do when saving the same svg from Inkscape.

**Solution** in `svg_mobject.py` replace `get_all_childNodes_have_id` with 
```
    def get_all_childNodes_have_id(self, element):
        all_childNodes_have_id = []
        if not isinstance(element, minidom.Element):
            return
        if element.hasAttribute('id') and (
                not element.tagName == "g"
                and
                not element.tagName == "defs"
                ):
            return [element]
        for e in element.childNodes:
            all_childNodes_have_id.append(self.get_all_childNodes_have_id(e))
        return self.flatten([e for e in all_childNodes_have_id if e])
```

**Comment by homotopycolimit** [comment]
Context: I've been using this here:
https://gitlab.com/co-bordism/manim/

see for example: 
https://gitlab.com/co-bordism/manim/-/blob/3c1e79810f4ef7c20c54764933a6d9e024c0e6a6/manimlib/mobject/svg/svg_mobject.py

**Comment by yoshiask** [comment]
Looks good to me, I'll get this change made in the `svg_parser` branch

**Comment by Mike-san-k** [comment]
[svg_mobject.zip](https://github.com/ManimCommunity/manim/files/5245997/svg_mobject.zip)
I tried to fix the the ink scape svgs, and here's the file, but it doesn't support other svgs apart from inkscape svgs, you may have a look at this, although I know you guys might have already done a much better job, but just sharing it :)

**Comment by cobordism** [comment]
My specific inkscape problem is solved with a small change included in https://github.com/ManimCommunity/manim/pull/457

but in general SVG support probably needs a lot of work(?) I can't judge this

**Comment by leotrs** [comment]
Yes it needs a lot of work, but thanks for closing this one. cc @yoshiask
