### ISSUE TITLE
Default head size of arrow 3d seems uncanny

### ISSUE THREAD

**Issue by Iced-Tea3** [ManimCommunity/manim#1684]
## Enhancement proposal

I feel like the default size arrow 3d is unrealistic to use in a 3D scene, comparing it to geogebra's 3d grapher, which looks way better, makes manim's arrow look weird, and quite cumbersome to change at every call. this issue is just to ask whether it's just me that feels that way, or should it be changed?

**Comment by PhotonSpheres** [comment]
Could you include a picture of what the arrowhead should look like? I agree that it does look somewhat unaesthetic now.

**Comment by Iced-Tea3** [comment]
Sure,
![ArrowExample_ManimCE_v0 7 0](https://user-images.githubusercontent.com/83535735/121834744-1459f300-cd02-11eb-967b-66658ec55386.png)
 the yellow arrow is default. and the blue is a modified and better imo. Maybe it's just me comparing it to geogebra 3d
 
![image](https://user-images.githubusercontent.com/83535735/121836108-6a7c6580-cd05-11eb-9c18-2b03ab72e389.png)

**Comment by PhotonSpheres** [comment]
I do like the smaller one more, I guess it is a taste thing though. The options probably are to add the other option in the code and let the end-user toggle between the options or change the shape for good or do nothing at all. Maybe a vote would help.

**Comment by WampyCakes** [comment]
Can't this be resolved by setting more sensible defaults for `height` and `base_radius` in `Arrow3D`?

**Comment by Iced-Tea3** [comment]
> Maybe a vote would help.

True. Might do a poll on discord

> Can't this be resolved by setting more sensible defaults

Do you mean local? Sure, i could do that, but if a majority fixes it themselves, might as well make it a common.

**Comment by WampyCakes** [comment]
No, I don't mean having everyone change it for themselves. I mean just change the default in manim

**Comment by Iced-Tea3** [comment]
>  I mean justchange the default in manim

I initially wanted to open a pr, but then i thought that it was a matter of aesthetic. As of now, i think i will open a pr and link this issue. if the devs disagree, i'll close both.

**Comment by WampyCakes** [comment]
I think a change is warranted. We want to have sensible defaults in Manim anyhow.
