### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by cobordism** [ManimCommunity/manim#169]
https://github.com/ManimCommunity/manim/blob/master/manim/animation/transform.py#L155 

"configuration of the transform itslef"
should be
"configuration of the transform itself"

**Comment by huguesdevimeux** [comment]
Feel free to submit a PR :)

**Comment by leotrs** [comment]
I believe @co-bordism is not a github user, so anybody who is reading, please feel free to submit a PR :)

**Comment by co-bordism** [comment]
manual pull request: I request that you pull my 'typofix' branch  :D

`git remote add cobordism https://gitlab.com:co-bordism/manim.git `
`git pull cobordism typofix`

**Comment by co-bordism** [comment]
I have added two more typo fixes to that branch.

**Comment by leotrs** [comment]
Didn't work:
```
$ git remote add cobordism https://gitlab.com:co-bordism/manim.git
$ git pull cobordism typofix
fatal: unable to access 'https://gitlab.com:co-bordism/manim.git/': Port number ended with 'c'
```
Perhaps I should try with SSH?

**Comment by cobordism** [comment]
its / instead of :

https://gitlab.com/co-bordism/manim.git

**Comment by leotrs** [comment]
Just pushed your typofixes! Thanks much! I think this manual PR will work. Next time please make sure to include the same two lines of instructions ;)
