### ISSUE TITLE
Make `BarChart` inherit from `Axes` instead of using `Line`

### ISSUE THREAD

**Issue by Nikhil0504** [ManimCommunity/manim#1703]
## Enhancement proposal

The `BarChart` right now uses `Line` to draw the axes which doesn't have much flexibility. But `Axes` can be used for this as it can be easier and more flexible for the users to use this class and also get more features.
https://github.com/ManimCommunity/manim/blob/375d9bb0b8713f4d804361767f9d426278e81bee/manim/mobject/probability.py#L278-L280

**Comment by hydrobeam** [comment]
Sounds like a good idea

**Comment by LedMeExplain** [comment]
I think the same as you. Barchart should inherit from Axes. I'll try to fix this and make a PR

**Comment by icedcoffeeee** [comment]
Done via #2387
