### ISSUE TITLE
New Debugging method : `print_on_scene`

### ISSUE THREAD

**Issue by kolibril13** [ManimCommunity/manim#1704]
Similar to the python `print` function, 
we could add a print_on_scene function, that prints values of variables on the scene for debugging purposes.
These debug prints could e.g. auto-fadeout after 2 seconds

**Comment by WampyCakes** [comment]
Or update as the value changes :eyes:

**Comment by WampyCakes** [comment]
@huguesdevimeux Did your debugging stuff you were working on already do this?

**Comment by huguesdevimeux** [comment]
> @huguesdevimeux Did your debugging stuff you were working on already do this?

Yes, that's pretty much it. 
The PR is not active though (see #982). 

I can't give any guarantee on whether I will finish it.

**Comment by MrDiver** [comment]
- https://github.com/ManimCommunity/manim/pull/982
This issue is not being worked on anymore
