### ISSUE TITLE
Change of community font to standart

### ISSUE THREAD

**Issue by phiofi** [ManimCommunity/manim#1718]
Hello everyone. Experimenting with community version, I suddenly realized that I would like to create not only ```TeX```, but also ```Text``` using ```Computer Modern```, i.e. standard TeX font.  What I mean is:
![image](https://user-images.githubusercontent.com/86015493/123116558-ae7c1280-d449-11eb-80b6-0b5ac480e7b3.png)
Instead of:
![image](https://user-images.githubusercontent.com/86015493/123116773-dd928400-d449-11eb-8bf6-d78ac24b7429.png)
Furthermore, I'd be grateful if the solution, should there be one, includes the same for other languages, in my case, ukrainian, which I have encorporated so far using:
```   
myTemplate = TexTemplate()
myTemplate.add_to_preamble(r"\usepackage[english, ukrainian]{babel}")
 ```

**Comment by behackl** [comment]
Hello!

`Text` uses an entirely different typesetting system, so having properly typeset Computer Modern with it is not possible I'm afraid. But I'm also not sure why you would want that: you can simply use `Tex` to write LaTeX, and for that you can use the very same template you define in the snippet above.
