### ISSUE TITLE
MASSIVE MathTex Bug

### ISSUE THREAD

**Issue by Polydynamical** [ManimCommunity/manim#1721]
MathTex has bug where if you enclose a single variable in curly brackets, it combines the tex files incorrectly. Observe:

This is the important code:
```python3
i = 2
eq = MathTex("\\frac{1}{1^{" + str(i) + "}}", "+ \\frac{1}{2^{" + str(i) + "}}")
```

The individual Tex files render correctly: ```Writing "\\frac{1}{1^{2}}"``` and ```Writing "+ \\frac{1}{2^{2}}"```.

But when it tries to combine the two files, it doesn't close the opening curly bracket after the power sign:
```Writing "\\frac{1}{1^{2 + \\frac{1}{2^{2}}}}"```

**Comment by behackl** [comment]
Hello! Which version of Manim are you using? I can't reproduce the problem you are reporting:

```py
>>> eq = MathTex("\\frac{1}{1^{" + str(i) + "}}", "+ \\frac{1}{2^{" + str(i) + "}}")
[06/24/21 20:58:02] INFO     Writing "\frac{1}{1^{2}} + \frac{1}{2^{2}}" to media/Tex/1499497d7c67d270.tex                                                                                tex_file_writing.py:83
[06/24/21 20:58:03] INFO     Writing "\frac{1}{1^{2}}" to media/Tex/f70c142f693430aa.tex                                                                                                  tex_file_writing.py:83
[06/24/21 20:58:04] INFO     Writing "+ \frac{1}{2^{2}}" to media/Tex/fa29ea2389271fac.tex                                                                                                tex_file_writing.py:83
```

**Comment by Polydynamical** [comment]
Not sure but once I updated it, it is miraculously working now

**Comment by behackl** [comment]
> Not sure but once I updated it, it is miraculously working now

Double braces in TeX strings (`{{ ... }}`) are special syntax in Manim, they are used to indicate where TeX strings should be broken up. In older versions, this was somewhat buggy and would explain why the string rendered incorrectly for you before (see #1304).

Glad to hear it works now!

**Comment by Polydynamical** [comment]
OHH I see. How would I escape them?

**Comment by behackl** [comment]
> OHH I see. How would I escape them?

What do you want to escape?

**Comment by Polydynamical** [comment]
How would I escape two consecutive curly brackets to be used in Latex?

**Comment by behackl** [comment]
> How would I escape two consecutive curly brackets to be used in Latex rather than a special Manim syntax?

As long as there is no pair of double braces `{{ ... }}`, you don't need to worry about it at all. And if you run into one of the rare situations where double opening braces are required, you can disable the syntax by adding a space between either the opening or the closing braces: `{ { ... } }`.
