### ISSUE TITLE
Update tutorial to use .animate

### ISSUE THREAD

**Issue by WampyCakes** [ManimCommunity/manim#1725]
## Enhancement proposal

[This tutorial](https://docs.manim.community/en/stable/tutorials/building_blocks.html#animating-methods) should show using the .animate syntax over ApplyMethod.

**Comment by jephianlin** [comment]
I am new to the community.  If possible, I would like to take this issue as my first try.

**Comment by behackl** [comment]
Sure, go ahead! Let us know if you need any help.
