### ISSUE TITLE
Integration with powerpoint

### ISSUE THREAD

**Issue by erwindenboer** [ManimCommunity/manim#1737]
Because this project is set up to ease teaching mathematics using animations, I would think an integration with PowerPoint is beneficial. In PowerPoint, video's can be copy-pasted into the slideshow. However, it isn't possible to rewind, go forward in the video. Especially in teaching, it is mandatory to rewind a bit if a small change has occurred. For that reason, integration would be, in my opinion, essential for teaching. I do hope some people share my opinion and can add for extra features to enhance this integration with PowerPoint.

**Comment by Darylgolden** [comment]
Does [manim-presentation](https://pypi.org/project/manim-presentation/) do what you're thinking of? As for integration with Microsoft Powerpoint itself, we're likely not going to do it as it is proprietary software (not everyone pays for MS Office licenses).

**Comment by erwindenboer** [comment]
@Darylgolden That is exactly what I was looking for. Thank you. I understand that an integration with PowerPoint won't be executed. Unfortunately, for my work I have no other choice than to use PowerPoint. I'll have to figure out how to make it work together. Thanks again for your suggestion. I am grateful!
