### ISSUE TITLE
NumberPlane x_range is not working properly

### ISSUE THREAD

**Issue by MiltonCobo** [ManimCommunity/manim#1755]
## Description of bug / unexpected behavior
In NumberPlane set x_range = [x_min, xmax, x_step].
Setting x_length doesn't prevent vertical lines of the grid continue to appear after x_max until the end of space. 
Also x_step sets the step of the grid in the x-axis BUT also in the y-axis. 

## Expected behavior
The gridlines should be restricted to the square [x_min, x_max] \times [y_min, y_max].
Also the behaviour of the grid should be different. The x_step AND the y_step should be used to setup the grid. 
Apparently only the x-step determines the frequence of gridlines in both axis.

## How to reproduce the issue
class G4(Scene):
  def construct(self):
    grid = NumberPlane(
      x_range = (10, 20, 5),
      y_range = (0, 15, 1),
      x_length = 8,
      y_length = 6,
      axis_config= dict(include_numbers= True, decimal_number_config = dict(color = BLACK, num_decimal_places = 0))
    )

    self.add(grid)

![image](https://user-images.githubusercontent.com/44674476/124385651-108c1180-dcad-11eb-9c95-595531934934.png)

</details>

## Logs
<details><summary>Terminal output</summary>

```
PASTE HERE OR PROVIDE LINK TO https://pastebin.com/ OR SIMILAR
```

</details>

## System specifications

<details><summary>System Details</summary>

- OS (with version, e.g Windows 10 v2004 or macOS 10.15 (Catalina)):
- RAM:
- Python version 3.9.6
- Installed modules (provide output from `pip list`):
```
PASTE HERE
```
</details>

<details><summary>LaTeX details</summary>

+ LaTeX distribution (e.g. TeX Live 2020):
+ Installed LaTeX packages:

</details>

<details><summary>FFMPEG</summary>

Output of `ffmpeg -version`:

```
PASTE HERE
```
</details>

**Comment by PhotonSpheres** [comment]
see PR #1744
