### ISSUE TITLE
Automatically choose Scene when there is only one Scene.

### ISSUE THREAD

**Issue by kolibril13** [ManimCommunity/manim#176]
![image](https://user-images.githubusercontent.com/44469195/86739929-8e83f100-c036-11ea-835f-064101e05a0f.png)
I have a python file called "HelloWorld", with only one scene class "Hello".
But when I run `manim -p HelloWorld.py" without further defining the Scene, it gives me a list, where I can choose my scene from.
This is in he current manim-cm edition. A few weeks ago, it would render the scene Hello automatically. Was that canged on purpose, or do we want to change it back, so that one does not have to make this extra step in the terminal?
This list is:
```sh
1: GraphScene
2: Hello
3: LinearTransformationScene
4: MovingCameraScene
5: ReconfigurableScene
6: SampleSpaceScene
7: SpecialThreeDScene
8: ThreeDScene
9: VectorScene
10: ZoomedScene

Choose number corresponding to desired scene/arguments.
(Use comma separated list for multiple entries)
Choice(s): 
```

**Comment by kolibril13** [comment]
Just realized: Same issue as #171

**Comment by leotrs** [comment]
Closing as duplicate. Let's discuss on #171
