### ISSUE TITLE
coloring the axis doesn't work in NumberPlane.

### ISSUE THREAD

**Issue by MiltonCobo** [ManimCommunity/manim#1768]
## Description of bug / unexpected behavior
Coloring the axis in NumberPlane() doesn't work. The color property is passed to NumberLine() in the axis_config argument.
Strangely other parameter passed to NumberLine() as stroke_width are working.

## Expected behavior
The axis on NumberPlane should have the color given in the axis_config dictionary.

## How to reproduce the issue
```py
class NP(Scene):
    def construct(self):
        axes = NumberPlane(x_range=[-1, 6], y_range=[-1,4], x_length=7, tips = False, y_length=4,
                    background_line_style=dict(stroke_color = LIGHT_GRAY),
                    x_axis_config = dict(include_numbers = False, stroke_width = 20, **color = RED**))

        self.add(axes)
```

## Additional media files

<details><summary>Images/GIFs</summary>

![image](https://user-images.githubusercontent.com/44674476/124618369-1b31dc80-de4e-11eb-9d12-e75cd4c2b30b.png)

## Logs
<details><summary>Terminal output</summary>

```
PASTE HERE OR PROVIDE LINK TO https://pastebin.com/ OR SIMILAR
```

</details>

## System specifications

<details><summary>System Details</summary>

- OS (with version, e.g Windows 10 v2004 or macOS 10.15 (Catalina)):
- RAM:
- Python version (`python/py/python3 --version`):
- Installed modules (provide output from `pip list`):
```
PASTE HERE
```
</details>

<details><summary>LaTeX details</summary>

+ LaTeX distribution (e.g. TeX Live 2020):
+ Installed LaTeX packages:

</details>

<details><summary>FFMPEG</summary>

Output of `ffmpeg -version`:

```
PASTE HERE
```
</details>

**Comment by LedMeExplain** [comment]
A temporary solution could be something like this:
```py
class NP(Scene):
    def construct(self):
        axes = NumberPlane(x_range=[-1, 6], y_range=[-1,4], x_length=7, tips = False, y_length=4,
                    background_line_style=dict(stroke_color = LIGHT_GRAY),
                    x_axis_config = dict(include_numbers = False, stroke_width = 20, color = RED))
        axes.get_axes().set_color(RED)
        self.add(axes)
 ```
 
![image](https://user-images.githubusercontent.com/86895183/125149162-f7e08900-e0fc-11eb-9aeb-39740aba1852.png)

**Comment by LedMeExplain** [comment]
Just realized this may not be a bug. Take a look at this code.
```py
class NP(Scene):
    def construct(self):
        axes = NumberPlane(x_range=[-1, 6], y_range=[-1,4], x_length=7, tips = False, y_length=4,
                    background_line_style=dict(stroke_color = LIGHT_GRAY),
                    x_axis_config = dict(include_numbers = False, stroke_width = 20, stroke_color = RED))
        self.add(axes)
```
Instead of `color` use `stroke_color`
![image](https://user-images.githubusercontent.com/86895183/125251685-30c75c00-e2bd-11eb-92d0-1a4d883e57ae.png)

```py
class NP(Scene):
    def construct(self):
        axes = NumberPlane(x_range=[-1, 6], y_range=[-1,4], x_length=7, tips = False, y_length=4,
                    background_line_style=dict(stroke_color = LIGHT_GRAY),
                    y_axis_config = dict(include_numbers = False, stroke_width = 20, stroke_color = BLUE))
        self.add(axes)
```
![image](https://user-images.githubusercontent.com/86895183/125251780-4b99d080-e2bd-11eb-827f-b0fbb985fae7.png)

**Comment by MiltonCobo** [comment]
Oh Maybe your right, using Stroke_color makes sense. Thanks!
