### ISSUE TITLE
Issue with video_dir in "default.cfg"

### ISSUE THREAD

**Issue by kolibril13** [ManimCommunity/manim#177]
The "default.cfg" file looks really nice!
Thanks a lot for making this, it has really great potential.

When testing it, I run into an issue:

In the old manim version, I ran my programms with `manim  -l -p  --video_dir ~/Downloads/  HelloWorld.py`
But now, I want to define the video_dir in "default.cfg".

Here, I found in line 70-71:
```cfg
# # --video_dir
# video_dir = %(MEDIA_DIR)s/videos
```
and changed it to:
```cfg
# # --video_dir
video_dir = ~/Downloads/
```

But the video output dir is unchanged, here the output of the script:
```sh
[10:29:50] INFO     Read configuration files: ['/home/kolibril config.py:416 
                    /projects/manim-community/manim/default.cfg']               
[10:29:50] INFO     Read configuration files: ['/home/kolibril config.py:416 
                    /projects/manim-community/manim/default.cfg']               
[10:29:51] INFO                                        scene_file_writer.py:531 
                    File ready at /home/kolibril/pr                          
                    ojects/manim-community/lala/media/                          
                    videos/hi/480p15/HelloWorld.mp4                             
           INFO     Played 1 animations                            scene.py:110 
```

**Comment by leotrs** [comment]
Thanks @kolibril13. You can see in https://github.com/ManimCommunity/manim/blob/master/manim/config.py#L117 that the vide_dir, tex_dir, and text_dir are now always subdirectories of media_dir. This is in accordance with #66. The --media_dir flag is still available to you to change the output directories.

**Comment by leotrs** [comment]
This is related to #132 

@kolibril13 I'm closing this for now as wontfix because this is intentional. Following my latest comments on #132, if you wish to change this behavior, please let's make a separate issue to implement such a change. Thanks :)
