### ISSUE TITLE
Reduce the resolution of `Dot3D`

### ISSUE THREAD

**Issue by Darylgolden** [ManimCommunity/manim#1771]
## Enhancement proposal
Currently, `Dot3D` uses the default `Sphere` resolution of (12, 24). Running a scene with lots of `Dot3D`s, like a scene with polyhedra, takes incredibly long because of the high resolution. I think a resolution of (8, 8) is a good balance between speed and visual looks. After changing the resolution, the control data for some tests have to be regenerated.

**Comment by joybh98** [comment]
Hi! Can I pick up this issue ? I am a newbie to this project and would like to contribute whatever I can!

**Comment by hydrobeam** [comment]
Sure! I've assigned to this issue 👍
