### ISSUE TITLE
Delete deprecated classes and methods with the tag "until=0.8.0"

### ISSUE THREAD

**Issue by Darylgolden** [ManimCommunity/manim#1772]
## Enhancement proposal
This should be done together with #1665 as no one got around to doing that between 0.7.0 and 0.8.0.

**Comment by AnaOddles** [comment]
Hi! I am a beginner and would love to work on this!

**Comment by Darylgolden** [comment]
Just a couple of minutes too late! #1773 is already fixing this I'm afraid. However, there are still other good first issues to work on! #1613 is probably the easiest (requires just adding a word in the documentation).

**Comment by AnaOddles** [comment]
Thank you! I will check out #1613
