### ISSUE TITLE
Issue with SurroundingRectangle not surrounding the text that it is supposed to

### ISSUE THREAD

**Issue by TheInfinityUser** [ManimCommunity/manim#1788]
I have run into a major issue with SurroundingRectangle when I was animating with manim community edition.
So, I have a piece of code here,
```py
from manim import *


class Test(Scene):
    def construct(self):
        t = MathTex(r"\sqrt", r"[", r"n", r"]{", r"x^4\sqrt{x^{-5}\sqrt{x^6}}",
                    r"}=", r"\left(x^4\sqrt{x^{-5}\sqrt{x^6}}\right)", r"^{1 \over ", r"n", r"}")
        t.move_to(np.array([0, -0.75, 0]))
        fb = SurroundingRectangle(t[4])
        self.add(t, fb)
```
This is supposed to surround `x^4\sqrt{x^{-5}\sqrt{x^6}}` with the SurroundingRectangle `fb`. However, the SurroundingRectangle does not surround it properly. 
![Test_ManimCE_v0 8 0](https://user-images.githubusercontent.com/67455129/125186433-08e9e100-e248-11eb-9788-e4c581e3b63a.png)
I tested with `t[4]` and I observed that it does show the correct part of the equation
```py
from manim import *


class Test(Scene):
    def construct(self):
        t = MathTex(r"\sqrt", r"[", r"n", r"]{", r"x^4\sqrt{x^{-5}\sqrt{x^6}}",
                     r"}=", r"\left(x^4\sqrt{x^{-5}\sqrt{x^6}}\right)", r"^{1 \over ", r"n", r"}")
        t.move_to(np.array([0, -0.75, 0]))
        tt = MathTex(t[4].get_tex_string())
        self.add(tt)
```
![Test_ManimCE_v0 8 0](https://user-images.githubusercontent.com/67455129/125186448-14d5a300-e248-11eb-9558-05d04846461e.png)
I have come here after consulting this in the discord server and it appears to be a bug. If it is not, please provide me with a solution to this. If it is, I might need an alternative to this.

**Comment by icedcoffeeee** [comment]
I would suggest rendering the `index_labels` for the tex first:
```py
class Test(Scene):
    def construct(self):
        t = MathTex("""
            \\sqrt[n]{x^4\\sqrt{x^{-5}\\sqrt{x^6}}}
            =\\left(x^4\\sqrt{x^{-5}\\sqrt{x^6}}\\right)^{1 \over n}
        """)
        t.move_to(ORIGIN)
        self.add(t, index_labels(t[0]))
```
![image](https://user-images.githubusercontent.com/83535735/126441607-6e7ec1aa-9fdb-4fe2-9c6c-297337f189aa.png)

And then use the indexing to form a `SurroundingRectangle`
```py
class Test(Scene):
    def construct(self):
        t = MathTex(
            """
            \\sqrt[n]{x^4\\sqrt{x^{-5}\\sqrt{x^6}}}
            =\\left(x^4\\sqrt{x^{-5}\\sqrt{x^6}}\\right)^{1 \over n}
            """
        )
        t.move_to(ORIGIN)
        self.add(t, SurroundingRectangle(t[0][3:14]))
```
![image](https://user-images.githubusercontent.com/83535735/126441862-59f31a4e-f584-43c7-9c64-359b079447ca.png)

This way, you can see the individual pieces and make it reliable. But the main problem is still a bug itself. I hope this helps and I hope the partitioning bug is solved soon.

**Comment by TheInfinityUser** [comment]
> I would suggest rendering the `index_labels` for the tex first:
> 
> ```python
> class Test(Scene):
>     def construct(self):
>         t = MathTex("""
>             \\sqrt[n]{x^4\\sqrt{x^{-5}\\sqrt{x^6}}}
>             =\\left(x^4\\sqrt{x^{-5}\\sqrt{x^6}}\\right)^{1 \over n}
>         """)
>         t.move_to(ORIGIN)
>         self.add(t, index_labels(t[0]))
> ```
> 
> ![image](https://user-images.githubusercontent.com/83535735/126441607-6e7ec1aa-9fdb-4fe2-9c6c-297337f189aa.png)
> 
> And then use the indexing to form a `SurroundingRectangle`
> 
> ```python
> class Test(Scene):
>     def construct(self):
>         t = MathTex(
>             """
>             \\sqrt[n]{x^4\\sqrt{x^{-5}\\sqrt{x^6}}}
>             =\\left(x^4\\sqrt{x^{-5}\\sqrt{x^6}}\\right)^{1 \over n}
>             """
>         )
>         t.move_to(ORIGIN)
>         self.add(t, SurroundingRectangle(t[0][3:14]))
> ```
> 
> ![image](https://user-images.githubusercontent.com/83535735/126441862-59f31a4e-f584-43c7-9c64-359b079447ca.png)
> 
> This way, you can see the individual pieces and make it reliable. But the main problem is still a bug itself. I hope this helps and I hope the partitioning bug is solved soon.

Yes, I figured this out on the discord a while ago. But thank you for replying.
