### ISSUE TITLE
More geometric tools for Manim

### ISSUE THREAD

**Issue by torannn** [ManimCommunity/manim#1789]
I think we should have more geometric tools to makes the construction of geometry figures easier. With the current tools, it's hard and exhausted to construct anything involved with tangent or perpendicular stuff as you have to calculate the tangent vectors yourself. With the aim to reduce the construction time and makes it easier for Manim user to construct a geometry figure, I suggest adding some more tools as follow:

1. **Perpendicular tools:**
+ Perpendicular line from a point to a line: given a point and a line; return the line that connects that point and its projection on the line.
+ Perpendicular line from a point to a plane: given a point and a plane; return the line that goes through the point and perpendicular to the plane.
+ Perpendicular plane from a point to a line: given a point and a line; return the plane that goes through the point and perpendicular to the line.

2. **Parallel tools:**
+ Parallel line from a point to a line: given a point and a line; return the line that goes through the point and parallel to the line.
+ Parallel line from a point to a plane: given a point and a plane; return the line that goes through the point and parallel to the plane.
+ Parallel plane from a point to a plane: given a point and a plane; return the plane that goes through the point and parallel to the given plane.

3. **Bisector tools:**
+ Angle bisector of two lines: Given two lines; return the angle bisector of the two lines.
+ Perpendicular bisector of a segment (lines with `put_start_and_end_on` in Manim language): given a segment; return the perpendicular bisector of that segment.

4. **Tangent tools:**
+ Tangent line from a point to a parametric curve: given a parametric curve and a point lies on it; return the tangent lines at that point of the parametric curve.
+ Tangent plane from a point to a parametric surface: given a parametric surface and a point lies on it; return the tangent plane
Then we can have a similar tangent tool for circle and sphere maybe?

Some advanced tools we can talk about are the intersection between two parametric curves or surfaces.

**Comment by MrDiver** [comment]
- #1798
