### ISSUE TITLE
Misleading -h CLI flag in documentation

### ISSUE THREAD

**Issue by RainbowwPhoenixx** [ManimCommunity/manim#1796]
Some documentation pages mention the `-h` command line option in order to get the help messages. However this option does not exist and is instead `--help`. 
It is in particular at the very bottom of [this page](https://docs.manim.community/en/v0.8.0/tutorials/configuration.html), but might be in others too.

**Comment by rootonchair** [comment]
@Darylgolden I think I can help on this one

**Comment by Darylgolden** [comment]
> 
> 
> @Darylgolden I think I can help on this one

Feel free to!

**Comment by Darylgolden** [comment]
Fixed in #1819.
