### ISSUE TITLE
AnimationGroup changes the order of objects

### ISSUE THREAD

**Issue by simonrouse9461** [ManimCommunity/manim#1804]
## Description of bug / unexpected behavior

Using AnimationGroup will change the already set order of existing objects.

## Expected behavior

AnimationGroup is used for generating animation. It is not supposed to reorder the objects.

## How to reproduce the issue

<details><summary>Code for reproducing the problem</summary>

```py
class TwoCircles(Scene):
    def construct(self):
        r = Circle(color=RED, fill_opacity=1).shift(RIGHT)
        g = Circle(color=GREEN, fill_opacity=1)
        self.add(r)
        self.add(g)
        self.play(r.animate.shift(LEFT))
        self.play(AnimationGroup(r.animate.shift(LEFT)))
```

</details>

## Additional media files

https://user-images.githubusercontent.com/10589586/125889725-b0d1c0ad-2874-4a54-ae8c-9f81f494ebb0.mp4

**Comment by simonrouse9461** [comment]
This is also true for LaggedStart.

**Comment by JeroSQ** [comment]
What do you mean by order? Which object is in front and which in the back?

**Comment by simonrouse9461** [comment]
@JeroSQ Yeah, in the example I gave, the red circle should stay behind the green circle

**Comment by JeroSQ** [comment]
Both circles have the same `z_index`. To get deterministic behaviour, set the `z_index` of the object you want to stay in front higher. Like so:
g = Circle(color=GREEN, fill_opacity=1, z_index=10)

**Comment by simonrouse9461** [comment]
@JeroSQ That solves my problem, thanks!
