### ISSUE TITLE
Packaging Manim with Conda

### ISSUE THREAD

**Issue by Darylgolden** [ManimCommunity/manim#1809]
## Description of proposed feature
Currently, the difficulty of installing Manim remains as one of the largest roadblocks for new users. A well created conda package should help alleviate some of that difficulty.

**Comment by gauranshkumar** [comment]
Hi, @Darylgolden that's actually a great idea, I would like to work on it.

**Comment by Darylgolden** [comment]
Assigned you, go for it!

**Comment by gauranshkumar** [comment]
Thanks for assigning, Will try to do it ASAP 👍🏼

**Comment by gauranshkumar** [comment]
A Quick update: Added [screeninfo](https://anaconda.org/conda-forge/screeninfo) dependency to conda-forge

**Comment by Darylgolden** [comment]
That's great! Thanks for the update!

**Comment by MrDiver** [comment]
Stale

**Comment by MrDiver** [comment]
Stale
