### ISSUE TITLE
Grant Voice TTS Module

### ISSUE THREAD

**Issue by FlyMyPG** [ManimCommunity/manim#1810]
## Description of proposed feature

Videos created with Manim Community lack the Grant Sanderson Voice.  Please add a TTS module for "Grant Voice".

## How can the new feature be used?

Totally rip-off Grant's clear enunciation.  Make "deep fakes" of 3b1b videos.  Listen to Grant swear.

## Additional comments

I would add further context, but it would need to be in Grant Voice, and I can't do that yet.

**Comment by Darylgolden** [comment]
Closing as it is not within scope of the library and is somewhat unethical.

**Comment by FlyMyPG** [comment]
;^)
