### ISSUE TITLE
bug in meth:get_riemann_rectangles()     in ThreeDAxes

### ISSUE THREAD

**Issue by anantpatel7895** [ManimCommunity/manim#1818]
## How to reproduce the issue

<details><summary>Code for reproducing the problem</summary>

```py
Paste your code here.
```

</details>

## Additional media files

<details><summary>Images/GIFs</summary>

</details>

## Logs
<details><summary>Terminal output</summary>

```
PASTE HERE OR PROVIDE LINK TO https://pastebin.com/ OR SIMILAR
```

</details>

## System specifications

<details><summary>System Details</summary>

- OS (with version, e.g Windows 10 v2004 or macOS 10.15 (Catalina)):
- RAM:
- Python version (`python/py/python3 --version`):
- Installed modules (provide output from `pip list`):
```
PASTE HERE
```
</details>

<details><summary>LaTeX details</summary>

+ LaTeX distribution (e.g. TeX Live 2020):
+ Installed LaTeX packages:

</details>

<details><summary>FFMPEG</summary>

Output of `ffmpeg -version`:

```
PASTE HERE
```
</details>

## Additional comments

``from manim import*
import numpy as np

class Testing(ThreeDScene):

    def curve(self,t):
        return np.array([2*np.cos(t),2*np.sin(t),0.5*8*np.cos(t)*np.sin(t)**2])

    def construct(self):
        axes = ThreeDAxes()

        specialcurve = ParametricFunction(
            lambda t: axes.c2p(*self.curve(t)),
            t_range=[0,PI/2]
        ).set_stroke(color=ORANGE, opacity=1)

        
        rieman = axes.get_riemann_rectangles(
            graph = specialcurve,
            x_range=[0,1]

        )

        self.add(axes)
        self.wait()
        self.move_camera(phi = 75*DEGREES, theta = 30*DEGREES)
        self.wait()
        self.play(Create(specialcurve))
        self.wait()
        self.play(Create(rieman))
        self.wait()

**Comment by anantpatel7895** [comment]
i am trying to add riemann rectangle between 3D parametric curve and xy plane in ThreeD .....but it show
bug....please fix it in the next version

showing:     ValueError: Alpha -6 not between 0 and 1.

**Comment by hydrobeam** [comment]
The issue seems to be in the ParametricFunction, you cannot pass in a function that returns an iterable of points into ParametricFunction. It needs to point to a single coordinate
