### ISSUE TITLE
Use Github actions over Travis

### ISSUE THREAD

**Issue by eulertour** [ManimCommunity/manim#182]
[Github has a built-in method of handling CI/CD](https://docs.github.com/en/actions) which has tighter Github integration and seems to be easier than Travis. I would recommend switching to it while we reevaluate how to handle testing.

**Comment by huguesdevimeux** [comment]
If it's possible, I completly agree.


I basically hate travis

**Comment by leotrs** [comment]
No opposition here.

**Comment by safinsingh** [comment]
I'll try to look into this and spin up some config
