### ISSUE TITLE
there is a bug in meth:input_to_graph_point()..... in ThreeDAxes() 

### ISSUE THREAD

**Issue by anantpatel7895** [ManimCommunity/manim#1822]
## How to reproduce the issue

<details><summary>Code for reproducing the problem</summary>

```from manim import*
import numpy as np

class Testing(ThreeDScene):

    def curve(self,t):
        return np.array([2*np.cos(t),2*np.sin(t),0.5*8*np.cos(t)*np.sin(t)**2])

    def construct(self):
        axes = ThreeDAxes()

        specialcurve = ParametricFunction(
            function=lambda t: np.array([2*np.cos(t),2*np.sin(t),0.5*8*np.cos(t)*np.sin(t)**2]),
            t_range=[-PI/2,PI/2]
        ).set_stroke(color=ORANGE, opacity=1)

        self.add(axes)
        self.move_camera(phi = 75*DEGREES, theta = 30*DEGREES)
        self.wait()

        self.play(Create(specialcurve))
        self.wait()

        self.add(Dot3D(axes.coords_to_point(0,2,0)))
        self.wait()

        self.add(Dot3D(axes.input_to_graph_point(0,specialcurve)))
        self.wait(2)
```

</details>

## Additional media files

<details><summary>Images/GIFs</summary>

</details>

## Logs
<details><summary>Terminal output</summary>

```
PASTE HERE OR PROVIDE LINK TO https://pastebin.com/ OR SIMILAR
```

</details>

## System specifications

<details><summary>System Details</summary>

- OS (with version, e.g Windows 10 v2004 or macOS 10.15 (Catalina)):
- RAM:
- Python version (`python/py/python3 --version`):
- Installed modules (provide output from `pip list`):
```
PASTE HERE
```
</details>

<details><summary>LaTeX details</summary>

+ LaTeX distribution (e.g. TeX Live 2020):
+ Installed LaTeX packages:

</details>

<details><summary>FFMPEG</summary>

Output of `ffmpeg -version`:

```
PASTE HERE
```
</details>

## Additional comments

``

**Comment by anantpatel7895** [comment]
there is a problem in last two line of code

**Comment by anantpatel7895** [comment]
i am trying the meth:input_to_graph_point().....on the 3D ParametricFunction()......in ThreeDAxes() this show me error

**Comment by hydrobeam** [comment]
Closing since it seems like user error and not enough details were provided.
