### ISSUE TITLE
Do dependencies need to installed in addition to `pip install manim`?

### ISSUE THREAD

**Issue by alexdriedger** [ManimCommunity/manim#1831]
It's unclear from the [installation docs](https://docs.manim.community/en/stable/installation.html) if [dependencies](https://docs.manim.community/en/stable/installation/win.html) are needed to use the library, or if someone can just do a `pip install manim` and then follow the quickstart guide.

Just a slight addition to the docs would clear up that confustion

**Comment by WampyCakes** [comment]
What exactly is confusing? The page you linked states:
> Manim has a few dependencies that need to be installed before it can be used. The following pages have instructions that are specific to your system. Once you are done installing the dependencies, come back to this page to install manim itself.
