### ISSUE TITLE
Allow `Cross` to be initialized without being based on an existing Mobject.

### ISSUE THREAD

**Issue by hydrobeam** [ManimCommunity/manim#1838]
## Enhancement proposal

Currently Cross needs a mobject passed to it, I think it should be reworked to not necessarily require this. Also maybe easily specifying the length of the cross in the `__init__` too?

Current `Cross` code:
```py
class Cross(VGroup):
    def __init__(self, mobject, stroke_color=RED, stroke_width=6, **kwargs):
        VGroup.__init__(
            self,
            Line(UP + LEFT, DOWN + RIGHT),
            Line(UP + RIGHT, DOWN + LEFT),
        )
        self.replace(mobject, stretch=True)
        self.set_stroke(color=stroke_color, width=stroke_width)
```

## Additional comments

replacing `VGroup.__init__` with `super().__init__` too

**Comment by asjadaugust** [comment]
I could take this up, if its not an urgent fix.

PS: It would be my first contribution.

**Comment by hydrobeam** [comment]
Sure, it's not urgent! I've assigned you to it👍
