### ISSUE TITLE
Impossible to use a custom manim.cfg when NOT running from CLI

### ISSUE THREAD

**Issue by huguesdevimeux** [ManimCommunity/manim#184]
Basically the title. When rendering the scene from python itself (that's what is done in the actual tests), it is impossible to load a `manim.cfg` in the working directory as we can when doing from CLI. 

IMO t's because of these lines (and more particular the else statement): 

```python
if _from_command_line():
    args = _parse_cli(sys.argv[1:])
    if args.config_file is not None:
        if os.path.exists(args.config_file):
            config_files.append(args.config_file)
        else:
            raise FileNotFoundError(f"Config file {args.config_file} doesn't exist")
    else:
        script_directory_file_config = os.path.join(os.path.dirname(args.file), 'manim.cfg')
        if os.path.exists(script_directory_file_config):
            config_files.append(script_directory_file_config)

else:
    # In this case, we still need an empty args object.
    args = _parse_cli([], input=False)
    # Need to populate the options left out
    args.file, args.scene_names, args.output_file = '', '', ''
```

We have discussed that previously on discord with @leotrs and @XorUnison , sorry if I missed something ;).

**Comment by leotrs** [comment]
Ah you're right! I guess that inner `else` clause should also be outside, so that manim always checks for a local file, regardless of how it's being called. Sounds like an easy PR ;)
