### ISSUE TITLE
Add test for AnimationGroup with remover=True

### ISSUE THREAD

**Issue by behackl** [ManimCommunity/manim#1846]
This change should be tested.

_Originally posted by @behackl in https://github.com/ManimCommunity/manim/pull/1722#discussion_r680471433_

**Comment by gauranshkumar** [comment]
Hi @behackl, I would like to work on this issue and write the test for #1722

**Comment by Darylgolden** [comment]
> 
> 
> Hi @behackl, I would like to work on this issue and write the test for #1722

Feel free too! There's no need to ask for permission to work on issues.

**Comment by behackl** [comment]
Unassigning due to inactivity.

**Comment by ycechungAI** [comment]
Now that i think about it, I believe the test should be placed in tests/test_graphical_units but which file most likely will be added or changed?  Also how would I test it?

**Comment by Darylgolden** [comment]
Seems to have been resolved by #2318.
