### ISSUE TITLE
Need a Dict object just like VGroup to access elements by keys

### ISSUE THREAD

**Issue by nilaybhatia** [ManimCommunity/manim#186]
[Feature request]
Consider the following case: 
Someone wants to make a complex shape composed of  a circle, square, and some other mobjects. If they use a `VGroup`, they will be able to do it. But `VGroup` provides access to submobjects only by index. Now if you want to change the color of the circle in your shape, you don't know what its index is. With a proposed `Dict` object, they can access it by a key(something like a string label for the mobject)
Edit: PR for this issue here:- #190

**Comment by leotrs** [comment]
Would love to see this implemented
