### ISSUE TITLE
Improvements for Quickstart tutorial

### ISSUE THREAD

**Issue by behackl** [ManimCommunity/manim#1863]
## Enhancement proposal

While coming up with a [new version of our interactive worksheet](https://mybinder.org/v2/gh/ManimCommunity/jupyter_examples/HEAD?filepath=First%20Steps%20with%20Manim.ipynb) I noticed that our quickstart tutorial could use some love.

- The first scene in the tutorial is called `SquareToCircle` when it actually is just the creation of a circle. The scene should be renamed.
- I think that we should also add some information about positioning Mobjects, as well as the `.animate` syntax.

**Comment by ask09ok** [comment]
Hi, I was looking at the quickstart guide and thought I'd take a crack at this. Would you mind if I also rewrote the prose to be easier to read?

**Comment by behackl** [comment]
> Hi, I was looking at the quickstart guide and thought I'd take a crack at this. Would you mind if I also rewrote the prose to be easier to read?

It would be much appreciated. I recently spent some time on https://try.manim.community, you could draw some inspiration from there -- or not, however you like. :-)

**Comment by vvolhejn** [comment]
Hi, @ask09ok did you get around to doing this? If not, I could help with this.

**Comment by ask09ok** [comment]
@behackl would you mind taking a look at this to see if the content looks right? I don't know how to format the link to manimMagic so I would also appreciate some pointers there too, if possible. Thanks, and apologies again for taking so long.
