### ISSUE TITLE
NameError: name 'Unwrite' is not defined

### ISSUE THREAD

**Issue by GDOR-11** [ManimCommunity/manim#1870]
## Description of bug / unexpected behavior
well i can't use the function Unwrite(), but i can use Write(), while i should be capable of using both of them without errors

## How to reproduce the issue
<h3>hot to reproduce the issue</h3>
make a file named bug.py and put this code:<br>
from manimlib import *<br>
class Bug(Scene):<br>
&nbsp;&nbsp;&nbsp;&nbsp;def construct(self):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;text = Text("some text :)")<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.play(Write(text))<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.wait(1)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.play(Unwrite(text, reverse = False))<br>
<br>
and on cmd run: manimgl bug.py Bug

## System specifications

<details><summary>System Details</summary>

- OS Windows 10 v2004:
- RAM: 8GB (7.89GB usable)
- Python version: python 3.9.6:
- Installed modules:
    backcall          0.2.0
    colorama          0.4.4
    colour            0.1.5
    cycler            0.10.0
    decorator         5.0.9
    glcontext         2.3.4
    ipython           7.26.0
    ipython-genutils  0.2.0
    jedi              0.18.0
    kiwisolver        1.3.1
    manimgl           1.1.0
    ManimPango        0.3.0
    mapbox-earcut     0.12.10
    matplotlib        3.4.2
    matplotlib-inline 0.1.2
    moderngl          5.6.4
    moderngl-window   2.4.0
    mpmath            1.2.1
    multipledispatch  0.6.0
    numpy             1.21.1
    parso             0.8.2
    pickleshare       0.7.5
    Pillow            8.3.1
    pip               21.2.2
    prompt-toolkit    3.0.19
    pydub             0.25.1
    pyglet            1.5.18
    Pygments          2.9.0
    PyOpenGL          3.1.5
    pyparsing         2.4.7
    pyreadline        2.1
    pyrr              0.10.3
    python-dateutil   2.8.2
    PyYAML            5.4.1
    scipy             1.7.1
    screeninfo        0.7
    setuptools        56.0.0
    six               1.16.0
    sympy             1.8
    tqdm              4.62.0
    traitlets         5.0.5
    validators        0.18.2
    wcwidth           0.2.5
```
PASTE HERE
```
</details>

<details><summary>LaTeX details</summary>

+ LaTeX distribution: MiKTeX
+ Installed LaTeX packages: https://miktex.org/pkg/az (i don't know if this is exactly what you mean by packages page)

</details>

<details><summary>FFMPEG</summary>

Output of `ffmpeg -version`:
    ffmpeg version 2021-08-04-git-3b298640e1-full_build-www.gyan.dev Copyright (c) 2000-2021 the FFmpeg developers
    built with gcc 10.3.0 (Rev5, Built by MSYS2 project)
configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libdav1d --enable-libzvbi --enable-librav1e --enable-libsvtav1 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libglslang --enable-vulkan --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
    libavutil      57.  3.100 / 57.  3.100
    libavcodec     59.  4.100 / 59.  4.100
    libavformat    59.  4.101 / 59.  4.101
    libavdevice    59.  0.100 / 59.  0.100
    libavfilter     8.  1.103 /  8.  1.103
    libswscale      6.  0.100 /  6.  0.100
    libswresample   4.  0.100 /  4.  0.100
    libpostproc    56.  0.100 / 56.  0.100
</details>
<br><br><br><br><br>
if you need aditional information tell me, and sorry if i put wrong info, i'm new here :)

**Comment by hydrobeam** [comment]
You're importing from `manimlib` which is from 3b1b/manim and doesn't have `Unwrite`. If you're using manimce you have to do
```py
from manim import *
```

but if you're using manimgl then either that animation does not exist, or it's a manimgl bug, and you'll have to handle it in the other repo.
