### ISSUE TITLE
-n option doesn't recognize n_1

### ISSUE THREAD

**Issue by jschoete** [ManimCommunity/manim#1872]
## Description of bug / unexpected behavior

From `manim render* --help` on the option `-n:`

`Start rendering from n_0 until n_1. If n_1
                                  is left unspecified, renders all scenes
                                  after n_0.
`

When trying `manim -n 1 2` I get:

`INFO     No end scene number specified in -n option. Rendering from 1 onwards...    
 ERROR 2 is not in the script `

although I've at least 30 scenes. 
When trying `manim -n_0 1 -n_1 2` I get:

`ERROR    Couldn't determine a range for -n option.`

How would I go about telling which slides I want to execute? Starting from some slide works fine with `manim -n 1` but I cannot seem to add an end slide number.

## How to reproduce the issue

<details><summary>Code for reproducing the problem</summary>

```py
Paste your code here.
```

</details>

## Additional media files

<details><summary>Images/GIFs</summary>

</details>

## Logs
<details><summary>Terminal output</summary>

```
PASTE HERE OR PROVIDE LINK TO https://pastebin.com/ OR SIMILAR
```

</details>

## System specifications

<details><summary>System Details</summary>

- OS (with version, e.g Windows 10 v2004 or macOS 10.15 (Catalina)):
- RAM:
- Python version (`python/py/python3 --version`):
- Installed modules (provide output from `pip list`):
```
PASTE HERE
```
</details>

<details><summary>LaTeX details</summary>

+ LaTeX distribution (e.g. TeX Live 2020):
+ Installed LaTeX packages:

</details>

<details><summary>FFMPEG</summary>

Output of `ffmpeg -version`:

```
PASTE HERE
```
</details>

**Comment by WampyCakes** [comment]
`-n 1,2`

**Comment by jschoete** [comment]
Oh ok, my bad if this is standard.
