### ISSUE TITLE
file_writer_config and config mixed up for text_dir and tex_dir

### ISSUE THREAD

**Issue by huguesdevimeux** [ManimCommunity/manim#188]
In `config.py`, tex_dir is defined inside `config ` (config['tex_dir']), same for 'text_dir'.

**But** in `tex_file_writer.py`, l32, it is `file_writer_config['tex_dir']`, that is used (not config).

This is in fact a very easy fix. I thought to add it within #185. 

Pining @leotrs

**Comment by huguesdevimeux** [comment]
My question was, should we put those in `config `or in `file_writer_config `? Imo obviously in the latter

**Comment by leotrs** [comment]
`tex_dir` are set to the variable `config` that is local to `_parse_file_writer_config`. Then, all of that is set to `file_writer_config` on L419. So there is no problem here.

I think the only problem is ambiguity. Perhaps we should change the variable inside `_parse_file_writer_config` to `file_writer_config` throughout to avoid confusion.

**Comment by huguesdevimeux** [comment]
I don't think you get my point. 

The issue is that `text_dir `is contained within `config`, and `tex_dir `in `file_writer_config`

**Comment by leotrs** [comment]
lolwut. They should both be in file_writer_config

**Comment by huguesdevimeux** [comment]
Yes, but they are not see https://github.com/ManimCommunity/manim/blob/ea79842b17ccb7e0a5eb33be5edc5abb4ce60b50/manim/config.py#L125

They are both in `config`

**Comment by leotrs** [comment]
But that's what I meant! The line you just cited in inside `_parse_file_writer_config`. So the `config` that is set in that line is local to that function. Once that function finishes, its return value (the local `config`) is set to the global `file_writer_config` on line 419. So I think both live in `file_writer_config`. (They are not overwriting the global `config` at any time.)

Regardless of who is right, we should change the `config` variable inside `_parse_file_writer_config` to be called `file_writer_config`. Could you please do that?

**Comment by huguesdevimeux** [comment]
God damnit, I'm stupid. 



> Regardless of who is right, we should change the `config` variable inside `_parse_file_writer_config` to be called `file_writer_config`. Could you please do that?

I will do that !

**Comment by leotrs** [comment]
> we should change the config variable inside _parse_file_writer_config to be called file_writer_config.

@huguesdevimeux did you push this change? If not, I can do it real quick.

**Comment by huguesdevimeux** [comment]
> @huguesdevimeux did you push this change? If not, I can do it real quick.

I didn't. Please do if you can :D

**Comment by huguesdevimeux** [comment]
Maybe you could fix #184 at the same time

**Comment by leotrs** [comment]
Closed by latest commit of 2s ago.
