### ISSUE TITLE
Use `self.attr` as opposed to `self.data["attr"]` for OpenGL files.

### ISSUE THREAD

**Issue by hydrobeam** [ManimCommunity/manim#1883]
## Enhancement proposal

Throughout the codebase for opengl files: `opengl_mobject.py` `svg_path.py`, `opengl_surface.py`, `opengl_vectorized_mobject.py`, `opengl_renderer.py`. They use a dict to store some information such as `points`, when it could just be accessed as an attribute instead (like how it's done in the regular mobjects).

This is probably a relic from porting over from 3b1b and should be changed to how someone would normally expect attributes to work.

**Comment by ryanmccauley211** [comment]
Seems that there are some cases where data info is treated as a group separate from other attributes like in `opengl_mobject.py`

```py
    def reverse_points(self):
        for mob in self.get_family():
            for key in mob.data:
                mob.data[key] = mob.data[key][::-1]
        return self
```

So would still need a way to group them?

**Comment by hydrobeam** [comment]
That's fair, I took a deeper look an it seems like it stores quite a few values, (only lists) such as in `init_data`:

```py
    def init_data(self):
        self.data = {
            "points": np.zeros((0, 3)),
            "bounding_box": np.zeros((3, 3)),
            "rgbas": np.zeros((1, 4)),
        }
```

And there are quite a few methods which work on every value in `self.data`, so it does still need to be grouped 🤔.Maybe we could hold on to `self.data`, and instead use a `_Data()` object to store this information when the contents of `self.data` need to be accessed directly? Something along the lines of this:

```py

import numpy as np

class _Data: 
    def __init__(self, parent, key_name:str, array:np.ndarray):
        self.parent = parent
        self.key_name = key_name
        self.parent.data[self.key_name] = array
    
    def __repr__(self) -> str:
        return f"{self.key_name}: {self.parent.data[self.key_name]}"

    def __getitem__(self, index:int) -> int:
        return self.parent.data[self.key_name][index]

    def __setitem__(self, index:int, value):
        self.parent.data[self.key_name][index] = value
    
    def __get__(self):
        return self.parent.data[self.key_name]
    
    def __set__(self, array:np.ndarray):
        self.parent.data[self.key_name] = array

class Myclass:
    def __init__(self):
        self.data = {}
        self.points = _Data(self, "points", np.arange(1, 5))

mc = Myclass()

print(mc.points) # __get__ + __repr__
mc.points = np.arange(0,10) # __set__
print(mc.points[2]) # __getitem__
mc.points[3] = 3 # __setitem__
```

I can work on implementing this if you think this is a decent solution.
