### ISSUE TITLE
All links in the inheritance graph are broken

### ISSUE THREAD

**Issue by kolibril13** [ManimCommunity/manim#1885]
All links in the inheritance graph are broken:
https://docs.manim.community/en/stable/reference_index/animations.html
Also in 0.9.0:
https://docs.manim.community/en/v0.9.0/reference_index/animations.html
Last time working in 0.7.0:
https://docs.manim.community/en/v0.7.0/reference.html#mobject-inheritance-graph

![image](https://user-images.githubusercontent.com/44469195/128701716-45e2f9ef-a39a-433b-81a1-e9695ae25b2f.png)
![image](https://user-images.githubusercontent.com/44469195/128701726-7a793ecf-5589-493b-8055-b56b95351372.png)

**Comment by behackl** [comment]
This is odd, and I don't fully understand why it behaves the way it does. As far as I can tell, the easiest way to fix this would be to move the diagrams to a file contained in `docs/source` – and there have been discussions about moving the diagrams to somewhere else anyways.

So, what should we do with them?
