### ISSUE TITLE
How to debug the manim in pycharm ? 

### ISSUE THREAD

**Issue by woshichuanqilz** [ManimCommunity/manim#1897]
I want to see how the manim works. 

Here is the settings of my project interpreter: 
![](https://media.discordapp.net/attachments/582403919754297363/875213748934164541/unknown.png?width=895&height=468)

but it can run normally but can't debug.

Debug will get the error. 

> C:\Python\python.exe -m manim "C:\Program Files\JetBrains\PyCharm Community Edition 2021.1.1\plugins\python-ce\helpers\pydev\pydevd.py" --multiproc --qt-support=auto --client 127.0.0.1 --port 6336 --file D:/python_project/ManimProject/scene.py -pql
Manim Community v0.9.0
Usage: python -m manim render [OPTIONS] FILE [SCENE_NAMES]...
Try 'python -m manim render --help' for help.
Error: No such option: --multiproc
Process finished with exit code 2

So how to debug the project in pycharm?

**Comment by TobiasLe** [comment]
I think debugging in pycharm it is much easier if you don't use the manim command line interface. You can also render your scene simply by calling `scene.render()`

for example:
```python
import manim
from manim.utils.file_ops import open_file as open_media_file


class MyScene(manim.Scene):
    def construct(self):
        example_text = manim.Tex("example")
        self.add(example_text)
        self.wait(2)


scene = MyScene()
scene.render()
open_media_file(scene.renderer.file_writer.movie_file_path)
```

This way you only need to execute this single file and you can debug it like you would with any other python file.
