### ISSUE TITLE
Global config system

### ISSUE THREAD

**Issue by Darylgolden** [ManimCommunity/manim#1908]
## Description of proposed feature
Currently, Manim only really supports a folder-specific configuration system well, where a file named `manim.cfg` is placed in the same location as the terminal when running a file. While it's possible to modify a "global config" in the source code (if installed through pip, at `Python{version}\Lib\site-packages\manim\_config`, this is not at all obvious and not ideal as it would get overwritten if the package was upgraded. It would be great to have a global configuration system that:

- is persistent through version upgrades
- can easily be modified through the CLI.

## How can the new feature be used?
Some examples where this would be useful would be in setting key bindings for the OpenGL interactive window, changing the default renderer, turning off the prompt to upgrade manim (annoying if you're working on a project and don't want to upgrade yet), setting the default media width for all Jupyter notebooks, and more.

## Additional comments
Edit: I just found out that `manim cfg` is a thing, but it needs better documentation (I have no idea how to use it to write a configuration option).

**Comment by naveen521kk** [comment]
Manim already reads a user wide config, see https://docs.manim.community/en/stable/tutorials/configuration.html#the-user-config-file
