### ISSUE TITLE
Transfer troubleshooting installation related snippets from Discord to the documentation

### ISSUE THREAD

**Issue by Darylgolden** [ManimCommunity/manim#1910]
## Enhancement proposal
In our [Discord server](https://www.manim.community/discord/index.html), we've began collecting solutions to common problems as snippets (send `?sp` in the Discord to see a list of them). While some of these are Discord specific, the snippets that contain troubleshooting instructions should be moved to the troubleshooting section where they can be seen by more people.

**Comment by snowmoss10** [comment]
Hello, I am new to github and I would like to help you on this project but I am not sure how I can do this?
