### ISSUE TITLE
Default command line help does not make mention of the subhelp pages

### ISSUE THREAD

**Issue by Darylgolden** [ManimCommunity/manim#1912]
## Enhancement proposal
Running `manim --help` gives the following:

```
Manim Community v0.9.0

Usage: manim [OPTIONS] COMMAND [ARGS]...

  Animation engine for explanatory math videos

Options:
  --version  Show version and exit.
  --help     Show this message and exit.

Commands:
  render*  Render SCENE(S) from the input FILE.
  cfg      Manages Manim configuration files.
  init     Sets up a project in current working directory with default...
  new      Create a new project or insert a new scene.
  plugins  Manages Manim plugins.

  Made with <3 by Manim Community developers.
```

It should also mention the existence of subhelp pages that can be obtained through `manim render --help`, `manim cfg --help`, etc.

**Comment by joybh98** [comment]
I'm picking up this issue

**Comment by jsonvillanueva** [comment]
I'd rather they be obtained with the program (/command) name alone. Cloup/Click both have the `no_args_is_help=True` option which is more convenient (e.g. `manim` produces the main help page, `manim render` the help page for render command, etc.). I agree though that the mention of command help pages is warranted for beginners.

As this is a simple 2 line fix (adding `no_args_is_help` to render command and updating epilog entry to __main__.py), I've added this to #1975.

**Comment by Darylgolden** [comment]
Unassigned due to inactivity.

**Comment by joybh98** [comment]
hey @Darylgolden if this issue is still open I'd like to take another crack at it

**Comment by hickmott99** [comment]
New to the Manim community and looking for my first issue to get started on. @Darylgolden is this issue still open? Or do you have any other suggestions?

**Comment by jbalpert** [comment]
@Darylgolden if you could look at the changes that would be great. There is something slightly off about the formatting, but I'm not too sure how to resolve them. It seems as if there are two newlines that occur, I'm not sure if that's a problem though
