### ISSUE TITLE
Wording problem in Colab installation docs

### ISSUE THREAD

**Issue by Darylgolden** [ManimCommunity/manim#1913]
## Enhancement proposal
The [docs](https://docs.manim.community/en/stable/installation/colab.html) currently says "You can install Colab by running the following in a cell" but it should be changed to "You can install Manim in a [Google Colaboratory](colab.research.google.com/) environment by running the following in a cell".

**Comment by RhnSharma** [comment]
I would like to take this one.

**Comment by RhnSharma** [comment]
I would like to take this one.
