### ISSUE TITLE
Add a new VMobject `DissipatingTracedPath`

### ISSUE THREAD

**Issue by leleogere** [ManimCommunity/manim#1920]
## Description of proposed feature

The `TracedPath` object is quite useful to draw any kind of shapes. But imo, it misses a dissipating parameter, which would make the path progressively disapear after some time (or some distance).

## How can the new feature be used?

It could be implemented with a lower and lower opacity, like in this [Visualization 101 video](https://www.youtube.com/watch?v=R3Az7Zd_nys) (code [here](https://github.com/fajrulfx/visualization101/blob/2876876873d34a32225a38c1587177b944518ca3/double_pendulum.py#L98-L119))
[![Double Pendulum video](https://img.youtube.com/vi/R3Az7Zd_nys/0.jpg)](https://www.youtube.com/watch?v=R3Az7Zd_nys)

Or it could be implemented with a lower and lower stroke_width like in this 
[3b1b video](https://www.youtube.com/watch?v=r6sGWTCMz2k) (code [here](https://github.com/3b1b/videos/blob/8977b0bd181a80ca8e2e319d862b7f19cb0f753f/_2019/diffyq/part2/fourier_series.py#L167-L179))
[![Fourier Series video](https://img.youtube.com/vi/r6sGWTCMz2k/0.jpg)](https://www.youtube.com/watch?v=r6sGWTCMz2k)

**Comment by behackl** [comment]
Closed via #1980.
