### ISSUE TITLE
Custom tip shapes for CurvedArrow and CurvedDoubleArrow are broken

### ISSUE THREAD

**Issue by behackl** [ManimCommunity/manim#1928]
## Description of bug / unexpected behavior

Passing `tip_shape` to `CurvedArrow`, or passing `tip_shape_start`/`tip_shape_end` to `CurvedDoubleArrow` results in an error.

## How to reproduce the issue

<details><summary>Code for reproducing the problem</summary>

```py
class DoubleArrowTest2(Scene):
    def construct(self):
        R=3
        angle_measure = CurvedDoubleArrow(
            start_point=[R,0,0],
            end_point=[0,R,0],radius=R,
            tip_shape_end=ArrowCircleFilledTip,
            tip_shape_start=ArrowCircleFilledTip
            )
        self.play(Create(angle_measure))
        self.wait()
```

</details>

## Additional comments

This should not be very difficult to fix: in https://github.com/ManimCommunity/manim/blob/463975455de51463acc1bbb3ed2b4a3a932573d0/manim/mobject/geometry.py#L453, `tip_shape` is passed to the parent of `CurvedArrow` in the `kwargs`, which it shouldn't. Doing something like
```py
tip_shape = kwargs.pop("tip_shape", ArrowTriangleFilledTip)
super().__init__(start_point, end_point, **kwargs)
self.add_tip(tip_shape=tip_shape)
```
in `CurvedArrow.__init__` should fix this.

**Comment by avani-031** [comment]
Can you assign this issue to me please?

**Comment by behackl** [comment]
Sure, go ahead!
