### ISSUE TITLE
`Rotate` breaks when rotating multiples of 2pi

### ISSUE THREAD

**Issue by Darylgolden** [ManimCommunity/manim#1935]
## Description of bug / unexpected behavior
```py
class RotationAnim(Scene):
    def construct(self):
        a = Circle().move_to(RIGHT)
        self.play(Rotate(a, 2*PI, about_point=ORIGIN), run_time=5)
```

gives:

https://user-images.githubusercontent.com/9102529/130183273-e101d2fe-65cc-42af-80ee-82d3adb0c732.mp4

`Rotating` works, but does not take into account the `rate_func` (and according to @behackl, is probably intentional)? Perhaps the best way to fix this is to use the method used for `Rotating`, just taking into account the `rate_func` (and maybe `Rotating` can inherit from `Rotate` and simply ignore the rate_func).

## How to reproduce the issue

<details><summary>Code for reproducing the problem</summary>

```py
Paste your code here.
```

</details>

## Additional media files

<details><summary>Images/GIFs</summary>

</details>

## Logs
<details><summary>Terminal output</summary>

```
PASTE HERE OR PROVIDE LINK TO https://pastebin.com/ OR SIMILAR
```

</details>

## System specifications

<details><summary>System Details</summary>

- OS (with version, e.g Windows 10 v2004 or macOS 10.15 (Catalina)):
- RAM:
- Python version (`python/py/python3 --version`):
- Installed modules (provide output from `pip list`):
```
PASTE HERE
```
</details>

<details><summary>LaTeX details</summary>

+ LaTeX distribution (e.g. TeX Live 2020):
+ Installed LaTeX packages:

</details>

<details><summary>FFMPEG</summary>

Output of `ffmpeg -version`:

```
PASTE HERE
```
</details>

**Comment by behackl** [comment]
If I had to guess, my money would be on this line here causing the breakage:

https://github.com/ManimCommunity/manim/blob/232bb85338331c18ba5ca3c8b8c2bbbe9346a08f/manim/utils/paths.py#L45

I don't think it is worthwhile to change the implementation so that it looks similar to `Rotating`; it rather seems the way `path_arc` is processed is not robust when integer multiples of $2\pi$ are passed.
