### ISSUE TITLE
`--save_last_frame` option does not work for the OpenGL renderer

### ISSUE THREAD

**Issue by Darylgolden** [ManimCommunity/manim#1936]
## Description of bug / unexpected behavior
Running

```py
from manim import *

class Example(Scene):
    def construct(self):
        self.play(Create(Circle()))
```

with `manim --renderer=opengl -s --write_to_movie examplescene.py` does not produce any image file.

## How to reproduce the issue

<details><summary>Code for reproducing the problem</summary>

```py
Paste your code here.
```

</details>

## Additional media files

<details><summary>Images/GIFs</summary>

</details>

## Logs
<details><summary>Terminal output</summary>

```
PASTE HERE OR PROVIDE LINK TO https://pastebin.com/ OR SIMILAR
```

</details>

## System specifications

<details><summary>System Details</summary>

- OS (with version, e.g Windows 10 v2004 or macOS 10.15 (Catalina)):
- RAM:
- Python version (`python/py/python3 --version`):
- Installed modules (provide output from `pip list`):
```
PASTE HERE
```
</details>

<details><summary>LaTeX details</summary>

+ LaTeX distribution (e.g. TeX Live 2020):
+ Installed LaTeX packages:

</details>

<details><summary>FFMPEG</summary>

Output of `ffmpeg -version`:

```
PASTE HERE
```
</details>

**Comment by hydrobeam** [comment]
Does it produce an error?

**Comment by ryanmccauley211** [comment]
I tried it and didn't get an error. I just think it needs to be implemented, don't think there is a way to currently output images with opengl. 

In cairo renderer we have:

```py
    def scene_finished(self, scene):
        # If no animations in scene, render an image instead
        if self.num_plays:
            self.file_writer.finish()
        elif config.write_to_movie:
            config.save_last_frame = True
            config.write_to_movie = False
        else:
            self.update_frame(scene)

        if config["save_last_frame"]:
            self.update_frame(scene)
            self.file_writer.save_final_image(self.camera.get_image())
```

In opengl:

```py
    def scene_finished(self, scene):
        self.file_writer.finish()
```
