### ISSUE TITLE
In-code alternative to `-n`

### ISSUE THREAD

**Issue by sudgy** [ManimCommunity/manim#1953]
Description of proposed feature: an alternative to `-n` that allows you to specify when to start and stop rendering the scene at that point in the code.

Here's an example: let's say we have something like this scene:
```python
class ExampleScene(Scene):
    def construct(self):
        ...Lots of calls to self.play() and the like...
        self.play(...) # Animation A
        ...Lots more of calls to self.play() and the like...
```
Currently, if we just wanted to only render Animation A, we would have to use `-n` and either laboriously count all calls to animation-producing functions or make an educated guess.  I propose adding something like `scene.start_rendering()` and `scene.stop_rendering()` to allow for something like this:
```python
class ExampleScene(Scene):
    def construct(self):
        scene.stop_rendering()
        ...Lots of calls to self.play() and the like...
        scene.start_rendering()
        self.play(...) # Animation A
        scene.stop_rendering()
        ...Lots more calls to self.play() and the like...
```
Then running manim with this scene will only render Animation A.

I'm not attached to the exact names or method of doing this, but some way of specifying in the code what parts of a scene to render would be extremely useful.

**Comment by JeroSQ** [comment]
I would find this useful, since I don't always know the animation number, and counting the lines to see from which animation to start rendering, and in which to stop isn't practical.
