### ISSUE TITLE
Rendering DecimalNumber (SingleStringMathTex) with updater takes a long time to render, and gets slower over time

### ISSUE THREAD

**Issue by JeroSQ** [ManimCommunity/manim#1959]
## Description of bug / unexpected behavior
When a `DecimalNumber` has an updater to become a `DecimalNumber` with the current `ValueTracker` value, it renders very slowly. It starts quickly, as expected, but gets slower and slower over time (as you can see in the video below). In the title I wrote `SingleStringMathTex` because I've found that this happens with classes that end up creating a `SingleStringMathTex` (`Text`, `Tex`, `MathTex`, `Integer`, `DecimalNumber`, ...). At first, I thought that the `become()` method was causing issues, leaving unreachable objects that the Garbage Collector couldn't delete, or something similar. But after running some tests with the Garbage Collector, the ammount of unreachable objs didn't seem to increase dramatically, while the render time did. (See code below to see this test). 

_If you are facing the same issue and can't afford having this long render times, checkout the partial solution in Edit 2, at the end of the Issue_

https://user-images.githubusercontent.com/68753500/130679100-253cf3c5-af79-4f2a-8e9b-417e0e5b5db7.mp4

Check _Additional Comments_ section for more odd behaviour I've noticed.

## Expected behavior
I expect the rendering to be faster, and remain constant.

## How to reproduce the issue

**Video 1 Original Code**

```py
from manim import *

config.tex_template = TexTemplate()
config.disable_caching = True

class Bug(Scene):

    def construct(self):

        angle_tracker = ValueTracker(0)

        label = DecimalNumber(0).scale(0.5)

        label.add_updater(
            lambda m: m.become(
                DecimalNumber(round(angle_tracker.get_value(), 2)).scale(0.5)
            )
        )

        self.add(label)
        self.wait(0.5)
        self.play(angle_tracker.animate.set_value(360), run_time=2)
        self.wait(0.5)
```

**Garbage Collector test Original Code**

```py
from manim import *
import gc

config.tex_template = TexTemplate()
config.disable_caching = True

class Bug(Scene):

    def construct(self):

        def get_decimal_num_and_print_unreachable():
            print("Unreachable:", gc.collect())
            return DecimalNumber(round(angle_tracker.get_value(), 2)).scale(0.5)

        angle_tracker = ValueTracker(0)

        label = DecimalNumber(0).scale(0.5)

        label.add_updater(
            lambda m: m.become(
                get_decimal_num_and_print_unreachable()
            )
        )

        self.add(label)
        self.wait(0.5)
        self.play(angle_tracker.animate.set_value(360), run_time=2)
        self.wait(0.5)
```

</details>

## Additional media files

<details><summary>Images/GIFs</summary>

![image](https://user-images.githubusercontent.com/68753500/130680233-a63a385b-b9a0-4635-83ee-61117e5b224a.png)

</details>

## Logs
<details><summary>Terminal output</summary>

```
PASTE HERE OR PROVIDE LINK TO https://pastebin.com/ OR SIMILAR
```

</details>

## System specifications

<details><summary>System Details</summary>

- OS (with version, e.g Windows 10 v2004 or macOS 10.15 (Catalina)):
- RAM:
- Python version (`python/py/python3 --version`):
- Installed modules (provide output from `pip list`):
```
PASTE HERE
```
</details>

<details><summary>LaTeX details</summary>

+ LaTeX distribution (e.g. TeX Live 2020):
+ Installed LaTeX packages:

</details>

<details><summary>FFMPEG</summary>

Output of `ffmpeg -version`:

```
PASTE HERE
```
</details>

## Additional comments

Some extra behaviour I've noticed:

- The 'slowness' seems to pile up. In this animation, there's a second `ValueTracker` animation, and you can clearly see that the second one doesn't start as fast as the first one. Instead it starts with the same speed the previous one ended. This doesn't only happen to `ValueTracker` animations, all other animations will be slowed-down in some way.

https://user-images.githubusercontent.com/68753500/130680309-a99fd787-050f-45ef-8bb1-edb2816b1294.mp4

Edit:

I've done some more investigating and it seems like the number of points of the `VMobject` increases throughout the rendering. When rendering starts, the object has ~120 points, and after 120 frames, it has 1600 points. Something in the `align_points()` method in `vmobject.py` is causing the number of points to increase. This explains the 'slowness piling up' thing mentioned above, since the object keeps the same numbers of points throughout rendering, so when the second animation starts, the mobject has 1600 points, and this number keeps increasing.
My knowledge ends at the bezier curves stuff, so I don't really know where to go from here. I will point out though that commenting these two lines (1271 & 1272 in ` vmobject.py` ) keeps the number of points constant and thus the animation renders fast, but it breaks things:

```
sp1 = self.insert_n_curves_to_point_list(diff1, sp1)
sp2 = self.insert_n_curves_to_point_list(diff2, sp2)
```

When I say it breaks things I say it because when using ` Transform` having those lines commnted, it spits out an error like this:
` ` ` ValueError: operands could not be broadcast together with shapes (80,3) (72,3)` ` ` 
Since those 2 commented lines make the number of points (?) or curves (?) _(I don't really know)_ equal, the program has some trouble when this number doesn't coincide between the objects.

Edit 2 **PARTIAL SOLUTION**: In case you are having the same issue and want to render faster, I have a hacky (and very far from perfect) solution that will increase render speeds dramatically. So far, I haven't had any issue with it, but it's very likely that it breaks something in very specific situations. Basically, I'm setting a max number of points a vmboject can have while aligning, so it doesn't keep increasing indefinitely. I have found that ~200 points is enough for most objects to render properly, and it allows render time to remain constant (and fast).

In the for-loop in `align_points()` I've added a condition and indented the two lines that call `self.insert_n_curves_to_point_list()` as such:

```py
for n in range(n_subpaths):
      sp1 = get_nth_subpath(subpaths1, n)
      sp2 = get_nth_subpath(subpaths2, n)
      diff1 = max(0, (len(sp2) - len(sp1)) // nppcc)
      diff2 = max(0, (len(sp1) - len(sp2)) // nppcc)
      if max(len(sp1), len(sp2)) < 215: # new condition
          sp1 = self.insert_n_curves_to_point_list(diff1, sp1) # indented lines
          sp2 = self.insert_n_curves_to_point_list(diff2, sp2)
      new_path1 = np.append(new_path1, sp1, axis=0)
      new_path2 = np.append(new_path2, sp2, axis=0)
```

This will increase rendering speed drastically. I say it's far from perfect because even though I haven't had any problems with it so far, I can imagine `VMobject`s with lots of points may be rendered incorrectly.

**Comment by Ivan091** [comment]
Can it happens because at the end of your animation you just have to render more digits?
I mean, to render `0.00` is much easier than `360.00`.

**Comment by Darylgolden** [comment]
No, that's not just it. I tried changing it from `100.00` to `999.99` and saw similar slowdowns.

**Comment by JeroSQ** [comment]
Nope, my tests showed that rendering still slows down while the number of digits remains constant.

**Comment by BorisTheBrave** [comment]
I've reviewed this bug.

You are 100% correct, the issue is in align_points. It causes the amount of points in a vmobject to grow unboundedly.

Firstly, i note that you don't really need `become` here. I got a similar effect using `DecimalNumber.set_value` and it works very fast as it doesn't trigger this bug.

---

But in terms of diagnosis, here's my thoughts:

`align_points` is designed to add extra points to each object to ensure they have the same amount for each "subpath". But subpaths are a fiddly concept.

Suppose are initial object `O` has suppath lengths [10]. And we alternate aligning with objects `A`, `B` with subpath lengths [20], and [10, 10]. (A and B are created fresh each time, like in the xample)

My understanding is the following:

Align 1:
* starts at O=[10], aligning with A=[20], so add 10 points to O in suppath 1, to get [20]
Align 2:
* starts at O=[20], aligning with B=[10, 10], so add 10 dummy points to O for subpath 2 to get [20, 10]. Also update B to [20, 10]
Align 3:
* starts at O=[20, 10], aligning with A=[20]. Nothing needs doing to O, but A needs 10 dummy points added at suppath 2.
Align 4:
* starts at O=[30] (!), aligning with B=[10, 10]. So add 10 dummy points to O to get [30, 10]. Also add 20 points to B.

("dummy" points occur when createing a new path entirely. Each dummy is a curve with start/end/control points all at the same value)

You can see it's gone wrong at align 4. O has 30 points in suppath 1, despite never aligning with anything of that length! The problem is how subpaths are determined. At the end of align 3, we added dummy points to A. Then between align 3 and align 4, we copy all of A's points to O (this is what `become` does). But then when we ask O what subpaths it has, it can no longer tell that the dummy points where *intended* to be part of subpath 2, it just counts them as part of subpath 1.

This repeats ad infinitum. We'll keep adding points to pad subpath 2 when aligning with A. Then that is forgotten, with the poitns becoming part of suppath 1.

---

As for fixing it, it looks tricky to fiddle too much with how subpaths or dummy points work.

I propose stripping dummy points from the end of each subpath before doing alignment, stopping them growing indefinitely.

**Comment by behackl** [comment]
This is a very fine and precise analysis, kudos and thank you! Your suggestion seems like a good idea.

**Comment by JeroSQ** [comment]
Thanks for the comment! Your explanation makes a lot of sense. ManimCE is still mostly Grant's old code, which isn't perfect.
If you take a look at the current 3b1b/manim repository, he's changed most of that stuff and the code seems much more solid now, and I doubt this issue exists.

A major re-design is in order, to make sure we don't have fiddly stuff. But well, that's hard. Maybe once we fully transition to OpenGL (if that ever happens), the whole tool will be much better.

**Comment by BorisTheBrave** [comment]
> he's changed most of that stuff and the code seems much more solid now, and I doubt this issue exists.

While the code isn't identical, it looks similar to me.

https://github.com/3b1b/manim/blob/master/manimlib/mobject/types/vectorized_mobject.py#L680

**Comment by JeroSQ** [comment]
Ýes you are correct. But take a look at the `insert_n_curves_to_point_list` function, which is the function that ultimately adds the points (I think). Grant seems to have implemented some extra logic in the middle. 
I'm not exactly sure what his code is doing since I'm not an expert on the subject, but the commit in which he modified the function is titled: _Rewrite insert_n_curves_to_point_list to be faster and more even._ https://github.com/3b1b/manim/commit/4b827adfee50f3d6a9b023eabae3e100d22b2e04

Maybe this fixes the issue with the dummy points?

**Comment by BorisTheBrave** [comment]
Interesting. I think that doesn't fix things, but it should probably be ported anyway. I did mentally note that that method looked slighty off when i was reviewing this code.
