### ISSUE TITLE
Support Prospector

### ISSUE THREAD

**Issue by GameDungeon** [ManimCommunity/manim#1969]
Add support for https://github.com/PyCQA/prospector

Please discuss if we want to use this.

**Comment by behackl** [comment]
In how far does Prospector compare to https://lgtm.com, which we already use?

I am reluctant to add more and more code quality checks to the library. They increase the entry barrier for new contributors.

**Comment by hydrobeam** [comment]
We seem to have made flake8 a little more strict these days, so `lgtm` might not even be as needed at this point.

**Comment by GameDungeon** [comment]
As far as I can tell we don't really use lgtm as it has plenty of issues noted on it no one has fixed. My argument for prospector is that it's customizable and has a pre-commit hook.

**Comment by behackl** [comment]
LGTM has been added to our CI pipeline, we *do* use it – independent of whether there are open issues that it detected; new PRs are processed with it.

But anyhow, this did not answer my question yet: in how far is the functionality of LGTM comparable to Prospector? Why should we add it? In how far does the library benefit from it; what can it do that we can't do with flake already?

**Comment by GameDungeon** [comment]
Never mind it seems to do some weird bundling of tools. I'll close this unless anyone has anything else to add.
