### ISSUE TITLE
Enforce linting and formatting with CI

### ISSUE THREAD

**Issue by eulertour** [ManimCommunity/manim#197]
After #196 is merged it will be easy to add a job to run `black --check` for example and block merging if it fails. This will make for a future-proof solution to #172 and #174.

**Comment by leotrs** [comment]
#172 is using autopep8, but you mention black. Did we ever reach consensus on this?

Also, #196 is merged now ;)

**Comment by kilacoda** [comment]
Seems to have been discussed in #43 with a consensus on black.

**Comment by eulertour** [comment]
Black is pep8 compliant; in other words valid black code is a strict subset of valid pep8 code.

**Comment by safinsingh** [comment]
In that case, I think black is a better option.

**Comment by leotrs** [comment]
If that's the case then let's close #172 ?

**Comment by leotrs** [comment]
We chose 88 as line length in #174. Can we get black within our CI asap? (I don't want to keep saying "please leave a space after this comma" during code reviews :D)

**Comment by Aathish04** [comment]
> Can we get black within our CI asap? (I don't want to keep saying "please leave a space after this comma" during code reviews :D)

@leotrs
Would using [a readymade GitHub Action](https://github.com/marketplace/actions/black-code-formatter) be ok?

**Comment by leotrs** [comment]
I have no familiarity with GH Actions. I believe @eulertour has experience there.

**Comment by eulertour** [comment]
This seems really small to warrant a packaged action; it really only needs to run `black --check`.

I should be able to get this in before the weekend ends.

**Comment by eulertour** [comment]
This actually isn't finished since CI currently only enforces formatting but not linting.

**Comment by leotrs** [comment]
I was hoping that the restyled bot would fix this but it ended up being more annoying than anything. Do we want to add a linter to our CI?

**Comment by naveen521kk** [comment]
> This actually isn't finished since CI currently only enforces formatting but not linting.

This is done by #478 and restyled bot does that work. Closing this issue.
