### ISSUE TITLE
"Japanese" text in documentation seems like gibberish

### ISSUE THREAD

**Issue by Darylgolden** [ManimCommunity/manim#1978]
## Enhancement proposal
The text [here](https://github.com/ManimCommunity/manim/blob/c7f8e15ef3c44e492f687d3550ed00085076673a/manim/mobject/svg/text_mobject.py#L368) seems completely indecipherable and is probably gibberish.

**Comment by darigovresearch** [comment]
@Darylgolden thanks for raising this, it appears that the text is Chinese and not Japanese as well. Does the extra parameter `, t2c={"見 角 言": BLUE}`  just change the colour of the words `見 角 言` to be blue?

Happy to make a pull request to change the text if the above is the case

**Comment by darigovresearch** [comment]
@Darylgolden pull request https://github.com/ManimCommunity/manim/pull/1979 has been made & makes the correction in both locations of Japanese text in the file and should resolve this issue
