### ISSUE TITLE
Manim installation page for windows with Chocolaty says install old manimce instead of manim

### ISSUE THREAD

**Issue by jaysonpowers** [ManimCommunity/manim#2000]
#### Preliminaries

- [x] I have followed the latest version of the
      [installation instructions](https://docs.manim.community/en/stable/installation.html).
- [x] I have checked the [troubleshooting page](https://docs.manim.community/en/stable/installation/troubleshooting.html) and my problem is either not mentioned there,
      or the solution given there does not help.

## Description of error
Website for windows installation with Chocolaty displays installing manimce package instead of manim

## Installation logs
'font_size' type error

## System specifications

<details><summary>System Details</summary>

- OS (with version, e.g Windows 10 v2004 or macOS 10.15 (Catalina)): Win11
- RAM: 32Gig
- Python version (`python/py/python3 --version`): installed with choco manimce package
- Installed modules (provide output from `pip list`):
```
PASTE HERE
```
</details>

<details><summary>LaTeX details</summary>

+ LaTeX distribution (e.g. TeX Live 2020):
+ Installed LaTeX packages:
MikTex
</details>

<details><summary>FFMPEG</summary>

Output of `ffmpeg -version`:

```
PASTE HERE
```
</details>

## Additional comments
This caused an error with font_size that I had trouble figuring out where the issue was after uninstalling via pip and reinstalling via pip error persisted unstill I uninstalled via choco the 'manimce' package and installed in choco 'manim' package.

**Comment by jaysonpowers** [comment]
![image](https://user-images.githubusercontent.com/1857352/131751898-5e2c71c9-cb2b-4352-a11b-cc541f803194.png)

from

https://docs.manim.community/en/stable/installation/windows.html

**Comment by behackl** [comment]
The chocolatey packages *is* called `manimce`, this is intended. I assumed that you used `pip` to install manim when you commented on #1694, this is why my instructions might have been a bit contradictory. To clear things up:

- `choco install manimce` is correct, and
- `pip install manim` is correct.

Both `choco install manim` and `pip install manimce` do not install the latest version of Manim.

The issue with Chocolatey might be that the latest version -- `v0.10.0` --, which we have released about an hour ago is not available there yet, that will take some more time. Your options are either:

- Use the `basic.py` file from `v0.9.0`, see https://github.com/ManimCommunity/manim/blob/v0.9.0/example_scenes/basic.py, 
- or wait a bit until the new version is also available via Chocolatey, then run `choco upgrade manimce` and use the latest version of `basic.py`.
