### ISSUE TITLE
Add a manim cfg-show sub command

### ISSUE THREAD

**Issue by leotrs** [ManimCommunity/manim#201]
With the new cascading config system, there will usually not be a single file that contains the final, actual, config that will be loaded into manim. It would be convenient to have a command, say `manim cfg-show` that parses the cascading files and then either (a) prints the final, actual, config options on screen, or (b) opens them as a new file.

Originally from [here](https://github.com/ManimCommunity/manim/issues/179#issuecomment-656275030)

I'm partial to (a) since (b) might give the false impression that one is editing "the" final config file. But there is no final config file, there are cascading files. In fact, running `manim cfg-show` from different folders will give different results since the config file with lowest priority is folder-wide.

Ties in with #151 @Aathish04 is there an issue for the general config-chooser command you are working on?

**Comment by XorUnison** [comment]
I would do it different. A final concatenated config showing option, and one opening the user configs should be clearly different options with different goals, so that'd be (a) and (b). So to clarify the (b) I'm talking about should just open and initialize the user config file, **_not_** show the concatenated final config.
So `manim cfg-show` and `manim user-cfg-edit` or something.

**Comment by Aathish04** [comment]
> Ties in with #151 @Aathish04 is there an issue for the general config-chooser command you are working on?

@leotrs Considering that after #151, there'll be a few changes to how config works, I'll work on the manim-cfg show after it's merged, if that's fine by you.

Can we keep `manim-cfg` as the base command and make everything config related subcommands of it?

`manim-cfg write --user` to write the config for the current user; `manim-cfg write --dir` for the current working directory and so on.
`manim-cfg show --user` to show the config for the current user; `manim-cfg show --dir` for the current working directory and so on.

We could have a `manim-cfg export <output dir>` to export the final config at the current working directory to another file at <output dir>, so on and so forth.

**Comment by leotrs** [comment]
> @leotrs Considering that after #151, there'll be a few changes to how config works, I'll work on manim-cfg show after it's merged, if that's fine by you.

It will *always* be fine by me for you to take things off my plate ;)

> Can we keep manim-cfg as the base command and make everything config related subcommands of it?

So `argparse` gives really convenient ways of using subcommands of the type `manim cfg --some_flags`. I'd rather keep everything under the same command (`manim`). For example, since we also want to support `manim-ce`, we would have to implement `manim-ce-cfg` as well. However, using the argparse system, we only need to implement the `cfg` subcommand once and it will work with both `manim` and `manim-ce` out of the box.

I like all of your ideas too. With the system I'm proposing, the specification might look like this:

`manim cfg <action> --<level>`

where <action> is just a single CLI argument that has to be one of `write, show, export`, etc. Regardless of what the action is, the other argument can be one of `user` or `cwd`.

Ultimately, the actual final specification is up to y'all, but I do feel fairly strongly about using `manim cfg` as the subcommand instead of creating a new command `manim-cfg`. Open to discussion here, as always :)

**Comment by Aathish04** [comment]
@leotrs @XorUnison 
Friendly reminder that I think I've addressed all your suggestions in #212 and that it's ready for review :)
