### ISSUE TITLE
Change mobjects' color by an option of ManimConfig

### ISSUE THREAD

**Issue by HACHEDOSO** [ManimCommunity/manim#2019]
## Description of proposed feature
Hi everyone! When I'm using a light background it's a bit uncomfortable changing color of many mobjects, if I don't do that, I cannot see any text, obviously due to default text color is white and my background is also white.

## How can the new feature be used?
`config["mobjects_color"] = YOURCOLOR` or anything similar to this :)

## Additional comments
I'm in love with this amazing project, thanks so much for making this community!

**Comment by Ivan091** [comment]
You can just use the default python dictionary for this. 

```py
config = {
    "stroke_color" = RED
}
```

Then just pass it as `**kwargs` into your `MObject`.

**Comment by behackl** [comment]
The latest release, `v0.11.0` includes #2075, which allows changing default keyword arguments for a class permanently without having to pass the option via the new `set_default` method; so I think this issue is actually closed via #2075.
