### ISSUE TITLE
Package Name On PyPI

### ISSUE THREAD

**Issue by Aathish04** [ManimCommunity/manim#202]
As we get closer to completing our goals for Release version 1.0.0 (see #148), we need to come to a consensus as to what exactly the PyPI name for this library should be.

So far, on Discord, we have discussed the possibility of using a variety of names, including:

manimlib [1](https://discordapp.com/channels/581738731934056449/712140817200054294/712151581201793026), [2](https://discordapp.com/channels/581738731934056449/712140817200054294/712151682263547924)

manim-com, manimc [1](https://discordapp.com/channels/581738731934056449/712140817200054294/712323457966407730), [2](https://discordapp.com/channels/581738731934056449/712140817200054294/712323572600668260), [3](https://discordapp.com/channels/581738731934056449/712140817200054294/712409888638369792), [4]()

manimcm,manim-cm, manim_cm [1](https://discordapp.com/channels/581738731934056449/712140817200054294/712873941663875073)
[2 (poll)](https://discordapp.com/channels/581738731934056449/712140817200054294/713088119750000671)

manim [1 (poll)](https://discordapp.com/channels/581738731934056449/712140817200054294/712888829547380766), [2](https://discordapp.com/channels/581738731934056449/712140817200054294/712887684455989298)

This ties in with #6 and #165.

@eulertour has filed a PEP 541 request [here](https://github.com/pypa/pypi-support/issues/450) to try and get the name `manim`. It has been 4 weeks since and we have not heard back. PEP 541 gives the admins 6 weeks to contact the owner of the repo, so I suppose we should look back in about 2 weeks time.

In the event that we are not successful in getting the name `manim`, what other name would be ideal? It would be very easy to use the name `manimlib` for this repository, and rename Grant's package to `manim-3b1b` or something similar. As of now, we also have access to the name `manimcm`, so that too can be used with not much effort.

**Comment by eulertour** [comment]
Did you mean to close this?

**Comment by Aathish04** [comment]
Yeah, it's a duplicate of https://github.com/ManimCommunity/manim/issues/163. At least, I think it is.
