### ISSUE TITLE
No such option: -h | magic cell commands in jupyter notebook

### ISSUE THREAD

**Issue by hoosmalhoos** [ManimCommunity/manim#2040]
### cannot execute magic cell code

so basically i tried to copy the code of [online version in jupyter notebook](https://mybinder.org/v2/gh/ManimCommunity/jupyter_examples/HEAD?filepath=basic_example_scenes.ipynb) and tried to download it to see if it works , of course the online version works fine ,but my local jupyter notebook shows <em>NoSuchOption: No such option: -h</em>
and some erorrs like  <em> NoSuchOption: No such option: -h</em>

## How to reproduce the issue

simply by run the code in jupyter notebook

<details><summary>Code for reproducing the problem</summary>

```py
Paste your code here.
```

</details>

## Additional media files
[basic example scenes.zip](https://github.com/ManimCommunity/manim/files/7147653/basic.example.scenes.zip)

<details><summary>Images/GIFs</summary>

![Screenshot1](https://user-images.githubusercontent.com/38074334/132945636-b6d52773-1f08-4e43-a8fb-ca9cc01610d0.png)

![Screenshot 2](https://user-images.githubusercontent.com/38074334/132945645-ef5d7c8c-22c0-4cd9-83d8-78b782e85070.png)

</details>

## Logs
<details><summary>Terminal output</summary>

```
NoSuchOption: No such option: -h

```

</details>

## System specifications

<details><summary>System Details</summary>

- OS (Linux 20.04.1-Ubuntu):
- RAM: 4.00 G
- Python version (`python/py/python3 --version`):
- Installed modules (provide output from `pip list`):
```
PASTE HERE
```
</details>

<details><summary>LaTeX details</summary>

+ LaTeX distribution (e.g. TeX Live 2020):
+ Installed LaTeX packages:

</details>

<details><summary>FFMPEG</summary>

Output of `ffmpeg -version`:

```
PASTE HERE
```
</details>

## Additional comments

i'm still reading the docs to figure out how might works

**Comment by Darylgolden** [comment]
Where do you see `manim -h`? The notebook you linked correctly uses `manim --help`. `manim -h` not working is known and partially intentional.

**Comment by kolibril13** [comment]
You can also use the "!" syntax:
![image](https://user-images.githubusercontent.com/44469195/134762528-d2c28285-edba-4087-be6d-1234fd2098c7.png)

**Comment by hoosmalhoos** [comment]
Yeah it works now thanks y'all
