### ISSUE TITLE
Make positioning easier when using `Mobject.become`

### ISSUE THREAD

**Issue by behackl** [ManimCommunity/manim#2048]
## Description of proposed feature

In some situations when using `become`, it is annoying to first take care of positioning as well: for example,
```py
t = Text("A wild circle appears!").shift(UP)
self.play(t.animate.become(Text("foo")))
```
does the correct thing by changing `t` to the text foo (but centered at the origin instead of at the location of the old mobject). However, sometimes users want to make simple "in-place/position" changes without moving the target mobject manually.

A keyword argument `move_center` / `match_center` / something along these lines for `become` could be a good way of making this a bit easier.

## How can the new feature be used?

```py
t = Text("A wild circle appears!").shift(UP)
self.play(t.animate.become(Text("foo"), match_center=True))
```
moves the new mobject first to the center of the old one, and then proceeds to change the original mobject.

**Comment by leleogere** [comment]
Parameters like `match_width` and `match_width` could also be useful!

**Comment by Narfee** [comment]
Hey all! I made a [PR](https://github.com/ManimCommunity/manim/pull/2128) for this issue. Let me know if it looks alright, or if there's something that I should add.

**Comment by Narfee** [comment]
@behackl I think this issue can be closed now. 

Thanks for providing an opportunity for people new to manim to contribute! It's greatly appreciated.

**Comment by behackl** [comment]
> @behackl I think this issue can be closed now.
> 
> Thanks for providing an opportunity for people new to manim to contribute! It's greatly appreciated.

Indeed, this is now fixed. Thank **you** for contributing -- help in any form is very much welcome. :-)
