### ISSUE TITLE
Class `Cross` should have the parameter `color`

### ISSUE THREAD

**Issue by kolibril13** [ManimCommunity/manim#2053]
https://docs.manim.community/en/stable/reference/manim.mobject.shape_matchers.Cross.html?highlight=Cross
```
class Example(Scene):
    def construct(self):
        mob= Cross(stroke_color = YELLOW)
```
right now, there is only the parameter `stroke_color`.
I think `color` should be supported as well.

**Comment by Ivan091** [comment]
What do you mean by `color`? We have here `fill_color` and `stroke_color`. I don't think `Cross` should have any background.

**Comment by kolibril13** [comment]
I mean fill_color
