### ISSUE TITLE
Graph.add_edges and add_vertices don't take List inputs

### ISSUE THREAD

**Issue by Ulthran** [ManimCommunity/manim#2054]
## Description of bug / unexpected behavior

The [documentation](https://docs.manim.community/en/stable/reference/manim.mobject.graph.Graph.html#manim.mobject.graph.Graph.add_edges) shows add_edges taking List[Tuple[Hashable, Hashable]] and add_vertices taking List[Hashable] but inputting these types yields a TypeError: unhashable type: 'list'.

## Expected behavior

Methods take List inputs

## How to reproduce the issue

<details><summary>Code for reproducing the problem</summary>

```py
class GraphTestScene(Scene):
    def construct(self):
        g = Graph([1, 2], [(1,2)])

        g.add_vertices([3, 4])
        g.add_edges([(1,3), (3,4)])
```

</details>

## Additional media files

<details><summary>Images/GIFs</summary>

</details>

## Logs
<details><summary>Terminal output</summary>

```
PASTE HERE OR PROVIDE LINK TO https://pastebin.com/ OR SIMILAR
```

</details>

## System specifications

<details><summary>System Details</summary>

This is being done on the provided [Docker image](https://docs.manim.community/en/stable/installation/docker.html)

- OS (with version, e.g Windows 10 v2004 or macOS 10.15 (Catalina)):
- RAM:
- Python version (`python/py/python3 --version`):
- Installed modules (provide output from `pip list`):
```
PASTE HERE
```
</details>

<details><summary>LaTeX details</summary>

+ LaTeX distribution (e.g. TeX Live 2020):
+ Installed LaTeX packages:

</details>

<details><summary>FFMPEG</summary>

Output of `ffmpeg -version`:

```
PASTE HERE
```
</details>

**Comment by behackl** [comment]
Indeed, the type hints are wrong according to PEP484; the vertices and edges are starred arguments, you can pass

```py
        g.add_vertices(3, 4)
        g.add_edges((1,3), (3,4))
```

which is consistent with some other parts of the library (like `Group`s etc.).

**Comment by Ulthran** [comment]
Thanks @behackl that fixes it. Is this something that should be changed in the docs though?

**Comment by behackl** [comment]
> Thanks @behackl that fixes it. Is this something that should be changed in the docs though?

According to PEP 484 it seems that the type hints should actually be `Tuple[Hashable, Hashable]` for the `*edges` parameter in `add_edges`, and `*vertices` in `add_vertices` should be `Hashable`. It would be a good first issue to fix! :-)

**Comment by Ulthran** [comment]
#2055
