### ISSUE TITLE
Ability to set the default font

### ISSUE THREAD

**Issue by Timmmm** [ManimCommunity/manim#2074]
It should be possible to set a global default font, rather than having to explicitly set it in every `Text` object.

If that is already possible somehow then it should be documented, because I could figure it out even after reading the source code.

**Comment by behackl** [comment]
We currently don't have a mechanism for setting/changing default values; but you can always create a custom subclass

```py
class MyText(Text):
    def __init__(self, *args, font=..., **kwargs):
        super().__init__(*args, font=font, **kwargs)
```

Also, feel free to join the discussion for a feature like that over at #2075.

**Comment by Timmmm** [comment]
Yeah unfortunately that still means I have to go around changing every `Text`. Thanks for the link to the PR though - I'll check it out.

**Comment by behackl** [comment]
You could do something like

```
OldText = Text
Text = NewText
```

after subclassing. Not pretty, not great to maintain, but it will work.

**Comment by Timmmm** [comment]
Yeah eek. It seems like some things like `Integer` don't even let you set the font anyway. Thanks for the suggestion though!

**Comment by Darylgolden** [comment]
This seems like something #2075 would be perfect for :)
