### ISSUE TITLE
issue in add_highlighted_cell

### ISSUE THREAD

**Issue by TheBlapse** [ManimCommunity/manim#2078]
## Description of bug / unexpected behavior

I created a 4*4 table and want to highlight different cells with different colours here is the code

## Expected behavior

The rectangles must fit in the cells, but they are not fitting

## How to reproduce the issue

<details><summary>Code for reproducing the problem</summary>

```py
def construct(self):
       table_1 = Table(
            [["1", "2"],
            ["4","3"]], include_outer_lines=True)

       table_1.add_highlighted_cell((1,1), color=RED)    
       table_1.add_highlighted_cell((1,2), color=YELLOW)    
       table_1.add_highlighted_cell((2,1), color=BLUE)  
       table_1.add_highlighted_cell((2,2), color=RED)  
       self.play(Create(table_1))
       self.wait()
```

</details>

## Additional media files

<details><summary>Images/GIFs</summary>

https://user-images.githubusercontent.com/76247922/134737123-3fe9cdc0-66de-4323-af9c-52e6a828d2e6.mp4

</details>

**Comment by kolibril13** [comment]
This is caused by the 
```
stretch_to_fit_height(cell.get_height())
```
function, but is easy to fix. I will make a pr.
