### ISSUE TITLE
Update Poetry Installer to New Version

### ISSUE THREAD

**Issue by GameDungeon** [ManimCommunity/manim#2100]
The old poetry installer has been deprecated for a while now, but we still use it. In my short (but not perfect) testing, it appears to me that the old installer will have issues on 3.10  (Which as of the creation of this issue is 6 days from launch )

This will require large changes to our CI that I have struggled to do on my own, hence the issue.

**Comment by alembcke** [comment]
@GameDungeon does #2376 fix this issue?

**Comment by GameDungeon** [comment]
I'm not really sure. I don't see anything about the installer in that PR. I also write this over two years ago, so I'm forgetting the context.

**Comment by alembcke** [comment]
What about this comment?  Is it not referring to updating the Poetry installer?  I only know the basics of Poetry, so could be completely wrong, in which case apologies for wasting your time.

https://github.com/ManimCommunity/manim/pull/2376#issuecomment-1001115469

**Comment by GameDungeon** [comment]
I didn't see it because of the way they did it. Yep, that's it. Thanks for pointing it out.
