### ISSUE TITLE
Getting error while running the "hello world" example file. 

### ISSUE THREAD

**Issue by alapan24** [ManimCommunity/manim#2107]
## Description of bug / unexpected behavior
I installed the manimlib following the instructions given by "Flammable Maths " youtube channel. While testing the installation, I tried running the test file , which basically animates the phrase "Hello World". But it is giving the the following error:
**TypeError: DrawBorderThenFill only works for vectorized Mobjects**

Can anyone give any idea why this is happening ?

My code was:
from manimlib.imports import *

class TestScene(Scene):
  def construct(self):
    t = TextMobject("Hello manim!")
    t.scale(2)

    self.play(Write(t))
    self.wait()

And the output is:
![Screenshot (1)](https://user-images.githubusercontent.com/91590223/135217331-c5b87953-92c5-4004-90d1-4c8c4248987d.png)
![Screenshot (2)](https://user-images.githubusercontent.com/91590223/135217370-b3a21bf9-a3cc-40ad-b34a-7b243ff50199.png)

**Comment by Darylgolden** [comment]
Flammable Math's video is for an outdated version of Manim. Please use our [documentation](https://docs.manim.community/en/stable/).

**Comment by alapan24** [comment]
Thanks .
Can you tell me what will be the modified code if I want the same output in manimce?
Original code is this:
class TestScene(Scene):
def construct(self):
t = TextMobject("Hello manim!")
t.scale(2)

self.play(Write(t))
self.wait()
