### ISSUE TITLE
Make `Difference` accept multiple args; Deprecate `Cutout`

### ISSUE THREAD

**Issue by icedcoffeeee** [ManimCommunity/manim#2109]
## Enhancement proposal

They basically do the same thing. Well, not exactly the same; as Cutout can accept multiple args as removed objects, while Difference can't, resulting in messy code like this:
```py
class Test(Scene):
    def construct(self):
        s1 = Square().scale(2.5)
        s2 = Triangle().shift(DOWN + RIGHT).scale(0.5)
        s3 = Square().shift(UP + RIGHT).scale(0.5)
        s4 = RegularPolygon(5).shift(DOWN + LEFT).scale(0.5)
        s5 = RegularPolygon(6).shift(UP + LEFT).scale(0.5)
        c = Difference(s1, s2)
        c = Difference(c, s3)
        c = Difference(c, s4)
        c = Difference(c, s5, fill_opacity=1, color=BLUE, stroke_color=RED)
        self.add(c)
```
While the same result can be obtained more easily with Cutout:
```py
class Test(Scene):
    def construct(self):
        s1 = Square().scale(2.5)
        s2 = Triangle().shift(DOWN + RIGHT).scale(0.5)
        s3 = Square().shift(UP + RIGHT).scale(0.5)
        s4 = RegularPolygon(5).shift(DOWN + LEFT).scale(0.5)
        s5 = RegularPolygon(6).shift(UP + LEFT).scale(0.5)
        c = Cutout(s1, s2, s3, s4, s5, fill_opacity=1, color=BLUE, stroke_color=RED)
        self.add(c)
```

![Test_ManimCE_v0 10 0](https://user-images.githubusercontent.com/83535735/135287509-cbf2189e-df03-4c21-aacf-c8d984a70313.png)

**Comment by WampyCakes** [comment]
What's the performance difference between Cutout and multiple Differences?

**Comment by icedcoffeeee** [comment]
@WampyCakes 
Comparing render times,
Difference: `0.013011693954467773 seconds`
Cutout: `0.0009982585906982422 seconds`

But that's probably because I haven't implemented it properly.

I might also add that now I realize how they are quite different themselves. 
Code:
```py
class Test(Scene):
    def construct(self):
        c1 = Circle().shift(LEFT * 0.5)
        c2 = Circle().shift(RIGHT * 0.5)
        c = Cutout(c1, c2, fill_opacity=1)
        self.add(c)
```
```py
class Test2(Scene):
    def construct(self):
        c1 = Circle().shift(LEFT * 0.5)
        c2 = Circle().shift(RIGHT * 0.5)
        c = Difference(c1, c2, fill_opacity=1)
        self.add(c)
```
It's very unintuitive how the left is Cutout and the right is Difference.
![image](https://user-images.githubusercontent.com/83535735/135315140-bfc4ddb4-8af5-4b9d-ab4b-6a8d0c57c216.png)

**Comment by naveen521kk** [comment]
@icedcoffeeee Please don't mark any issue as Good First Issue without discussion.

> I might also add that now I realize how they are quite different themselves.

I think what `Difference` did is correct, that is to subract `c2` from `c1`. Also, it only accepts two vmobjects because difference isn't commutative which could possibly create confusion.

**Comment by icedcoffeeee** [comment]
> Please don't mark any issue as Good First Issue without discussion.

Ah, my bad. I thought it was simple deprecation. Turns out it's more complicated. 

> difference isn't commutative which could possibly create confusion.

I see.. that makes sense i guess.

**Comment by icedcoffeeee** [comment]
Since both Cutout and Difference are used differently and get different results, does this mean both can stay in the library? If so, I can close this issue.
