### ISSUE TITLE
Is it wanted, that Tex + MathTex have submobjects of submobjects? 

### ISSUE THREAD

**Issue by kolibril13** [ManimCommunity/manim#2125]
E.g. to access letter W, one has to write:
```py
class Example(Scene):
    def construct(self):
        s = MathTex("HelloWorld").set_color(YELLOW).scale(2)
        x=s.submobjects[0].submobjects[0]
        self.add(x)
```
![image](https://user-images.githubusercontent.com/44469195/135671040-00692f00-6103-409b-808c-5bc2c4274c85.png)

Is this intended behavior?

**Comment by PaulCMurdoch** [comment]
A simpler way to write it is:
```py
!m
class Example(Scene):
    def construct(self):
        s = MathTex("HelloWorld").set_color(YELLOW).scale(2)
        x=s[0][0]
        self.add(x)  
```

To access W it would be [0][5]. The first index accesses the submobject the second one access the letter of the submobject.

**Comment by kolibril13** [comment]
Thank you for the compact writing! 
However, I am still searching for the reason why this extra nesting of submobjects is needed, and why can it not simply be `x= s[5]` ?

**Comment by PaulCMurdoch** [comment]
> Thank you for the compact writing! 
> However, I am still searching for the reason why this extra nesting of submobjects is needed, and why can it not simply be `x= s[5]` ?

Ah I think it's useful to have it that way because you can put multiple arguments into Tex. So knowing which submobject corresponds to a word is useful if you have long text. And it would also be useful if you apply some formatting to Tex or some other argument in there.

**Comment by kolibril13** [comment]
> you can put multiple arguments into Tex

Makes now total sense!  Thanks for your explanation!
