### ISSUE TITLE
Changing existing Mobjects

### ISSUE THREAD

**Issue by XorUnison** [ManimCommunity/manim#213]
As agreed on in the Discord call here's the issue on what to do about changing existing Mobjects.

Right now when creating Mobjects kwargs can be passed to instantly get a certain desired appearance:
```python
c_config={"stroke_width": 10,"stroke_color": RED,"fill_opacity": 1,"color": BLUE}
c=Circle(**c_config)
```
So far so good.
The issue starts when you have an object like...
```python
c=Circle()
```
...and you want to change it afterwards. For instance the Tiling class I worked on takes a prototype tile, and replicates it, so instantiating objects the way they have to look is not an option, the attributes have to be adjusted after creation. For my big tiling video I then had to make a function changing the color of all tiles depending on position. This was okay for 1 color, but if I would've had to change multiple values things would've gotten very ugly, very quickly with manim as of today.
Currently to affect these attributes we have to do stuff like:
```python
c.set_fill(RED)
c.set_stroke...
```

And while...
```python
digest_config(c,c_config)
```
...is a thing, we want to first get rid of `digest_config`, and second it only works for *some* attributes. `digest_config` like this will apply stroke width and presumably some other attributes, but not colors. They all have to be applied separately in their own statement. And third separate `set_...` methods are _also_ undesired and should be kept to a necessary minimum. So this is all very very messy.

So the goal, aside from ditching the current way config works also has to be to streamline how attributes of existing objects are changed:
So what currently is impossible but should be possible is something like this...
```python
c_config={"stroke_width": 10,"stroke_color": RED,"fill_opacity": 1,"color": BLUE}
c=Circle()
c.change_attributes(**c)
```
yielding the same result as this:
```python
c_config={"stroke_width": 10,"stroke_color": RED,"fill_opacity": 1,"color": BLUE}
c=Circle(**c_config)
```
`change_attributes` or whatever we call it should then ideally be one, singular and central method to change the appearance of Mobjects, deprecating most/all of these `set_...` methods in turn, and also not relying on `digest_config`. As for how to best implement that... I don't know, so that's for sure a point of discussion.

**Comment by huguesdevimeux** [comment]
I see now. I don't think I did understand well when we talked about that on Discord, so thank you very much for this issue. 

This will be discussed when we will migrate towards dataclasses, no ? 

And I think implementing that is easy. See https://stackoverflow.com/questions/30212361/setting-multiple-object-attributes-at-once

**Comment by XorUnison** [comment]
> This will be discussed when we will migrate towards dataclasses, no ?

I assume it should go along with that, yes. 
> And I think implementing that is easy. See https://stackoverflow.com/questions/30212361/setting-multiple-object-attributes-at-once

Right, but you can simply overwrite the outward attributes now like that too, but actually applying colors for drawing is a lot more complicated. I don't know it actually has to be, but currently it is.

**Comment by leotrs** [comment]
Agreed with all your points. CONFIG, digest_config, and the set_ methods are most likely going away soon. But it would still be desirable to change many members at once.

Can you please clarify why setattrs is not going to work in the case "applying colors for drawing"?

**Comment by XorUnison** [comment]
> Can you please clarify why setattrs is not going to work in the case "applying colors for drawing"?

I don't actually know if setattrs would work. That's part of the attributes PR, right? In any case, my instinctual answer is that even if setattrs doesn't work for that yet, it's probably the right function for the task, so we should make it work like that. I'm a bit concerned about the structure of group class with submobjects and how setattrs or other functions would work in those cases.

**Comment by leotrs** [comment]
Python has native `[setattr](https://docs.python.org/3/reference/datamodel.html#object.__setattr__)`, and the answer [here](https://stackoverflow.com/a/38159655) is basically just iterating that. I agree, doing something like this should be the way to go in order to have a `digest_config` alternative but Done Right (TM).

> I'm a bit concerned about the structure of group class with submobjects and how setattrs or other functions would work in those cases.

This is a good point, anyone know how it would work?

**Comment by XorUnison** [comment]
I dug around a little in the color set methods and a few levels deeper there are `.setattr`s already, so my hunch is there's no issue with that. If anything we should be able to massively simplify the application of colors. Eventually.

**Comment by leotrs** [comment]
Related to #258 

@XorUnison were you able to look into this?

**Comment by XorUnison** [comment]
> Related to #258
> 
> @XorUnison were you able to look into this?

Not until you mentioned that and me here anyway what with me being so annoyingly busy, I don't get to sift issues indiscriminately.

But yeah, I ran into more of these issues, and they're exactly the tangential issues that also need to be fixed when changing existing Mobjects. There are _so_ many schisms in manim between attributes, setters and getters, and we should clean them all up eventually. #258 is just raising attention on one of the specific issues.

**Comment by behackl** [comment]
I think that this is actually resolved with the introduction of the `.set` compatibility layer. Further progress should be made into dynamically changing keyword argument default values.
