### ISSUE TITLE
Create a color class to handle different color formats

### ISSUE THREAD

**Issue by k4pran** [ManimCommunity/manim#2141]
## Enhancement proposal

Currently we have different color settings such as fill, stroke, and opacity. It would be good to have a class that we can use across manim for consistency, as atm we are handling strings, `Color` objects and lists containing either of these. It means we have a lot to keep track of, and with opengl we also use numpy arrays. I think we should have a class dedicated to handling these, that takes in any of these formats and can be used as a consistent format across manim

**Comment by behackl** [comment]
Done, we have `ManimColor` in v0.18.0. 👍
