### ISSUE TITLE
Meaning of max_quads for ImplicitFunction

### ISSUE THREAD

**Issue by Morinator** [ManimCommunity/manim#2169]
The current explanation "The maximum number of quads to use." on https://docs.manim.community/en/stable/reference/manim.mobject.functions.ImplicitFunction.html is not useful imo.

Also when googling something like "function quads", I found results regarding the quadrizeps-muscle, so I guess it's not THAT easy to find it out yourself.

**Comment by Darylgolden** [comment]
I think the note there states the practical effect on rendering pretty clearly. Is there anything you would add?
