### ISSUE TITLE
Width & Height for Text can't be float

### ISSUE THREAD

**Issue by moritz-gross** [ManimCommunity/manim#2170]
![grafik](https://user-images.githubusercontent.com/25711926/136423938-10315c73-acc5-4f13-8a57-bd2b5a312fd2.png)

The expected type is Optional[int], but from my understanding, any non-negative float value should be allowed

**Comment by Darylgolden** [comment]
> 
> 
> @Darylgolden would you mind assigning this to me? I'd love to help out!

Sure, I assigned you! And there's no need to be formally assigned before working on an issue.

**Comment by caffeinatedMike** [comment]
@Darylgolden PR opened. I realize I didn't need to be explicitly assigned, but with hacktoberfest afoot I find it better when a task is clearly divvied out to a person instead of two people potentially working on the same issue.
