### ISSUE TITLE
Only the first parts of an equation are rendered with `Write`.

### ISSUE THREAD

**Issue by Felix-Petersen** [ManimCommunity/manim#2195]
## Description of bug / unexpected behavior
Only the first parts of an equation are rendered with `Write`.

## Expected behavior
The entire equation to be displayed 

## How to reproduce the issue
Manim Community v0.11.0

```py
class TestWrite(Scene):
    def construct(self):
        text=MathTex(
            "&", " x", r"=0 \\& \texttt{while }", " x", r"\le 10:", r"\\&\qquad", " x", "=", " x", "+1"
        )
        self.play(Write(text))
        self.wait()
```

## Output

![output img](https://pasteboard.co/MHF5tPp2OpxW.png)
https://pasteboard.co/MHF5tPp2OpxW.png

**Comment by citrusmunch** [comment]
I've also found that lower render qualities make it further into the animation.
