### ISSUE TITLE
Add minimal tests

### ISSUE THREAD

**Issue by leotrs** [ManimCommunity/manim#22]
Before starting any major changes (including high priority ones such as #6), we need a way of testing that our changes do not break the basic functionality of the library. Simply put, I'm afraid to move or touch some files as it is unclear to me whether something will break.

For this, I suggest we start with minimal tests that consist in compiling a handful of scenes, put them in a new file called `test/test_example_scenes.py`, and we run the test by manually running manim over them. If the scenes look the way they should, then we are good to go. These scenes can be the ones that currently live in `sample_scenes.py`, for example.

Of course, this is no replacement for a full testing framework, but it should at least be a minimal guarantee that our coming changes are not completely screwing up the library.

**Comment by eulertour** [comment]
> Simply put, I'm afraid to move or touch some files as it is unclear to me whether something will break.

Manim has never had any tests and is pretty much always broken. That's just the way we've been doing it so far. Not to say that it makes any sense at all, but if the code sort of looks reasonable to you it's already up to the current manim standard, so you shouldn't feel too scared to change it.

That said those tests would be a big help.

**Comment by huguesdevimeux** [comment]
That's a great idea. I take care of that

**Comment by eulertour** [comment]
#28 doesn't improve the testing situation over running the example scenes manually. The goal is to write a suite which can be run in pytest, nose2, or the like in order to ensure basic functionality.

**Comment by leotrs** [comment]
As per #86, there is now a (very very minimal) set of tests in place with pytest. I will close this in favor of all the other issues already mentioning tests.
