### ISSUE TITLE
`self.play(Write(MathTex))` with string split and `\\sqrt`

### ISSUE THREAD

**Issue by HACHEDOSO** [ManimCommunity/manim#2241]
## Description of bug / unexpected behavior
Hi guys. I had a problem. I had a problem with the animation Write. When I split strings on MathTex and one of these contains `\\sqrt` or `\\sqrt{` (I know if there is one of these strings, that represents two indexes), the mobject is written as you can see in the next video.

## How to reproduce the issue

<details><summary>Code and video for reproducing the problem</summary>

https://user-images.githubusercontent.com/87504717/139559939-a2ec55cb-ba97-4259-a872-e88f533a33e5.mp4

```py
from manim import *

class Video(Scene):
    def construct(self):
        limit = MathTex("\\lim_{", "x", "\\to", "-\\infty}", "{", "\\sqrt{", "x", "^2", "+", "1}", "\\over", "x}").scale(2)
        limit[1].set_color(ORANGE)
        limit[6].set_color(ORANGE)
        limit[11].set_color(ORANGE)
        forsolve = Text("Para resolver este límite", font="Orbitron", weight=BOLD, color=BLACK).to_edge(UP)
        rec1 = SurroundingRectangle(forsolve, color=ORANGE, stroke_color=WHITE, fill_opacity=1.0, buff=0.3)
        self.play(Write(limit), DrawBorderThenFill(rec1), run_time=2)
        self.play(FadeIn(forsolve, shift=UP))
```

</details>

## Additional media files
However, when I do the same thing with `self.add`, it's working fine.

![Thumbnail_ManimCE_v0 11 0](https://user-images.githubusercontent.com/87504717/139559928-35a77e2b-9fe6-4420-90a6-183709cf6a00.png)

```py
from manim import *

class Thumbnail(Scene):
    def construct(self):
        title = Text("Calcula el siguiente límite",
        font="Orbitron",
        weight=BOLD,
        color=BLACK).to_edge(UP)
        rec = SurroundingRectangle(title,
        color=ORANGE,
        stroke_color=WHITE,
        fill_opacity=1.0,
        buff=0.3)
        limit = MathTex("\\lim_{", "x", "\\to", "-\\infty}", "{", "\\sqrt{", "x", "^2", "+", "1}", "\\over", "x}").scale(2)
        limit[1].set_color(ORANGE)
        limit[6].set_color(ORANGE)
        limit[11].set_color(ORANGE)
        svg = SVGMobject("deafness.svg").to_corner(DR)
        text = Tex("Video inclusivo", color=ORANGE).scale(1.5).to_edge(DOWN)
        self.add(rec, title, limit, svg, text)
```

</details>

**Comment by Viicos** [comment]
Does not fix the issue, but you could use `tex_to_color_map` instead:

```py
limit = MathTex(
    r"\lim_{x\to-\infty}\frac{\sqrt{x^2+1}}{x}",
    tex_to_color_map={
        'x': ORANGE
    }
)
```
Which interestingly raises a LaTeX error: `ERROR    LaTeX compilation error: Argument of \align* has an extra }.` (isn't happening without `tex_to_color_map`). Maybe playing with the `tex_environment` parameter could help.

Other solution:

```py
limit = MathTex(r"\lim_{x\to-\infty}\frac{\sqrt{x^2+1}}{x}")
limit[0][3].set_color(ORANGE)
limit[0][9].set_color(ORANGE)
limit[0][14].set_color(ORANGE)
```

**Comment by kasztan2** [comment]
Same applies to exponentiation and logarithm, probably every expression that takes two arguments has this bug.


https://user-images.githubusercontent.com/21148090/173068933-1e25e95e-2e80-4b77-9bcd-537ae86f8028.mp4

```python
from manim import *

class Test(Scene):
    def construct(self):
        m=MathTex(r"a^b", substrings_to_isolate=["a", "b"])
        m2=MathTex(r"{{a}}^{{b}}").next_to(m, DOWN)
        m3=MathTex(r"a", r"^", r"b").next_to(m2, DOWN)
        m4=MathTex(r"a^b").next_to(m3, DOWN)
        self.play(Write(m), Write(m2), Write(m3), Write(m4))
        self.wait()
```

No matter which way I separate the terms, it only writes "a".

```add``` and ```FadeIn``` work normally and show the whole expression.

The way I'm able to get around this is that I simply iterate over every submobject instead of applying ```Write``` on the whole MathTex object:
```python
for i in m:
    self.play(Write(i))
self.wait()
```
