### ISSUE TITLE
GraphScene examples not working

### ISSUE THREAD

**Issue by Jibanul** [ManimCommunity/manim#2263]
I found out that GraphScene is not available anymore. But quite a few examples in the manim community website still use it. What do I make this code work taken from the website. Btw Dot() is not available too. Thanks.
Link: https://docs.manim.community/en/v0.1.0/examples/plots.html

class Plot3DataPoints(GraphScene):
    CONFIG = {
        "y_axis_label": r"Concentration [\%]",
        "x_axis_label": "Time [s]",
        }

    def construct(self):
        data = [1, 2, 2, 4, 4, 1, 3]
        self.setup_axes()
        for time, dat in enumerate(data):
            dot = Dot().move_to(self.coords_to_point(time, dat))
            self.add(dot)

**Comment by behackl** [comment]
Can you link to where you have this from? This is certainly not from the current version of the documentation.

**Comment by Jibanul** [comment]
3rd example in this link. All the examples here use GraphScene.
https://docs.manim.community/en/v0.1.0/examples/plots.html

**Comment by behackl** [comment]
> 3rd example in this link. All the examples here use GraphScene.
> https://docs.manim.community/en/v0.1.0/examples/plots.html

See the note block at the top of this page. :-)

**Comment by Jibanul** [comment]
The link in the note is broken.

**Comment by behackl** [comment]
Sort of, the page has been moved at some point and we don't have a redirect setup.

Anyhow, here is a page from our current reference manual: <https://docs.manim.community/en/v0.12.0/reference/manim.mobject.coordinate_systems.CoordinateSystem.html#manim.mobject.coordinate_systems.CoordinateSystem> -- make sure that you have the latest version of Manim installed before trying to run examples. The fact that you mention that `Dot` is not available makes me wonder which version you have currently installed.

**Comment by Jibanul** [comment]
Thanks for the info. I also found the examples I need from the updated version. I'm using v0.11. My visual studio code indicates Dot() is not defined. I'm gonna look into this. Thanks.

**Comment by behackl** [comment]
> Thanks for the info. I also found the examples I need from the updated version. I'm using v0.11. My visual studio code indicates Dot() is not defined. I'm gonna look into this. Thanks.

Make sure you set the Python interpreter that VS Code uses (see left-hand side in the status bar on the bottom of the window) is the same that you installed Manim to. It should work then.

Good luck!

**Comment by Jibanul** [comment]
> > Thanks for the info. I also found the examples I need from the updated version. I'm using v0.11. My visual studio code indicates Dot() is not defined. I'm gonna look into this. Thanks.
> 
> Make sure you set the Python interpreter that VS Code uses (see left-hand side in the status bar on the bottom of the window) is the same that you installed Manim to. It should work then.
> 
> Good luck!

Thanks for the tip. Appreciate it.
