### ISSUE TITLE
Refactoring tests :

### ISSUE THREAD

**Issue by huguesdevimeux** [ManimCommunity/manim#227]
I was thinking about tests enhancements : 

## Testing videos 
So I think two things should be tested: video metadata about the video and the hash of the video. 
Concerning the video's metadata, I propose using `ffprobe` (by default installed with FFmpeg) : 
` ffprobe -v error -select_streams v:0 -show_entries stream=width,height,nb_frames,duration,avg_frame_rate,codec_name -print_format json test1.mp4 `
Output : 
```json
{
   "programs":[

   ],
   "streams":[
      {
         "codec_name":"h264",
         "width":854,
         "height":480,
         "avg_frame_rate":"15/1",
         "duration":"2.000000",
         "nb_frames":"30"
      }
   ]
}
```
For the video hash: FFmpeg has a built-in functionality allowing to compute it :
`FFmpeg -i test1.mp4 -f hash -hash md5 hash.md5 -format_whitelist hash -loglevel error`
Output the hash in a file. **Note** the latter is independent of the container-format ([see](https://twitter.com/FFmpeg/status/1060662187448950784). 

I know, only the hash would be sufficient as metadata are contained within it, but doing these two tests will make debugging easier. 

**My question is: for the metadata, I only kept on purpose these 6 elements. Do you think it's enough? what other things should we test ?**   

## Tests directories 
I thought to refactor the whole architecture into something like that : 
```
tests/
    conftest.py
    test_graphical_units/
        pre_rendered_frames/
            .. Here will be the content of tests_data.. (i.e the pre-rendered frames)
        test_creation.py
        test.geometry.py 
        ....
    test_logging/
        expected_logs/
            ... Pretty self-explanatory
        ... Here will the tests of what manim logs. 
    test_CLI/
        ... Here will be tested all the CLI flags. We will use videos tests here (see above)/.
        ... In fact, these are more end-to-end tests.
        pre_rendered_data/
            ... the information concerning the prerendered videos (i.e their hash and metadata). NOTE: No videos will be there, only hash and JSON.
    test_CONFIG/
            ... Here we will test the config. The idea is to use custom config in both CLI and from the file.
    utils/
        graph_unit_tests.py #Actual testing_utils.py. Contains all the functions used to test graphical units.
        logging_tests.py # Will Contain functions used to test logs (e.g functions used to get the log, to get the pre-generated logs, etc)
        CLI_tests.py # Same as above, except for the CLI tests.
        videos_tests # This will contain all the functions used to test a video (e.g. comparing hash and metadata) 
        dev_utils.py # not sure about this. Meant to contains all the functions and stuff to set new tests up.
```
Do you agree with this?
I would particularly like to get opinions about the fact that no videos will be contained, only hashes. One disadvantage of that is that as there a no visual proof of a mismatch the debugging could be quite harder (although rendering the scene with the master branch will be enough to get the original video).

**EDIT :** Added test CONFIG folder

**Comment by leotrs** [comment]
1. All of these depend on `ffmpeg`. Did we ever get it installed on Windows?

2. 
> I know, only the hash would be sufficient as metadata are contained within it, but doing these two tests will make debugging easier.

Agreed, good call there.

3.
> My question is: for the metadata, I only kept on purpose these 6 elements. Do you think it's enough? what other things should we test ?

What are the other options?

4. I like the folder structure you propose. The only thing I don't like is the names `pre_rendered_frames/`, `expected_logs/`, `pre_rendered_data/`. All of these seem to be doing similar things (they contain things that tests will compare against). So I'd rather call them something that sounds similar, or that reminds the dev/user that they have similar roles. `cache/` is one idea, but not descriptive enough. Perhaps `cached_frames/`, `cached_logs/`, and `cached_data/`?

5. Are we getting rid of pixel-perfect tests for now?

**Comment by huguesdevimeux** [comment]
> 1. All of these depend on `ffmpeg`. Did we ever get it installed on Windows?

Yes. There was a PR about this, I don't remember the # .

> What are the other options?

Sorry, I forget to tell this : Here they are : 
```
{
    "index": 0,
    "codec_name": "h264",
    "codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
    "profile": "High",
    "codec_type": "video",
    "codec_time_base": "1/30",
    "codec_tag_string": "avc1",
    "codec_tag": "0x31637661",
    "width": 854,
    "height": 480,
    "coded_width": 864,
    "coded_height": 480,
    "closed_captions": 0,
    "has_b_frames": 2,
    "pix_fmt": "yuv420p",
    "level": 30,
    "chroma_location": "left",
    "refs": 1,
    "is_avc": "true",
    "nal_length_size": "4",
    "r_frame_rate": "15/1",
    "avg_frame_rate": "15/1",
    "time_base": "1/15360",
    "start_pts": 0,
    "start_time": "0.000000",
    "duration_ts": 30720,
    "duration": "2.000000",
    "bit_rate": "11784",
    "bits_per_raw_sample": "8",
    "nb_frames": "30",
    "disposition": {
        "default": 1,
        "dub": 0,
        "original": 0,
        "comment": 0,
        "lyrics": 0,
        "karaoke": 0,
        "forced": 0,
        "hearing_impaired": 0,
        "visual_impaired": 0,
        "clean_effects": 0,
        "attached_pic": 0,
        "timed_thumbnails": 0
    },
```


> 1. `cache/` is one idea, but not descriptive enough. Perhaps `cached_frames/`, `cached_logs/`, and `cached_data/`?

The problem is that they are not properly cached data IMO, so this could be misleading. Why not somthing like `control_data` ?

  

> 2\. Are we getting rid of pixel-perfect tests for now?

I'm opposed to that. The refactoring I propose is not meant to replace them in any way and I'm still convinced that pixel-perfect tests are really useful.

**Comment by PhilippImhof** [comment]
> > 1. `cache/` is one idea, but not descriptive enough. Perhaps `cached_frames/`, `cached_logs/`, and `cached_data/`?
> 
> The problem is that they are not properly cached data IMO, so this could be misleading. Why not somthing like `control_data` ?


IMO cache would be very misleading. How about reference_data?

**Comment by leotrs** [comment]
Doesn't #335 close this?

**Comment by leotrs** [comment]
@huguesdevimeux :point_up:

**Comment by huguesdevimeux** [comment]
Sorry. Yes, it closed this !
