### ISSUE TITLE
Can i use docker container as Root?

### ISSUE THREAD

**Issue by wryorange** [ManimCommunity/manim#2270]
## Enhancement proposal
I am gratefully using docker container.
But i can't login as Root. so i can't use vim and others.
can i login as root in my docker container?

**Comment by behackl** [comment]
Hello! Sure you can: see [docker's documentation](https://docs.docker.com/engine/reference/run/#user); you can run the container with `docker run --user root -it manimcommunity/manim:stable /bin/bash` to spawn a shell as root in the container.

**Comment by wryorange** [comment]
> Hello! Sure you can: see [docker's documentation](https://docs.docker.com/engine/reference/run/#user); you can run the container with `docker run --user root -it manimcommunity/manim:stable /bin/bash` to spawn a shell as root in the container.

I'm not familiar to using docker. Thank you for help!
