### ISSUE TITLE
Operator overloading for Mobject "Integer"

### ISSUE THREAD

**Issue by kolibril13** [ManimCommunity/manim#2275]
Already possible:
```py
num= Integer(0)
num.set_value(2)
``` 
Nice to have:
```py
num= Integer(0)
num += 2
```

**Comment by Darylgolden** [comment]
This should be done for `DecimalNumber`, which is the base for `Integer`.

**Comment by peaceheis** [comment]
I submitted a modification supporting these operators - everything goes through the set_value() method so all should be well with it functioning properly.

**Comment by MrDiver** [comment]
Stale and already has a PR
- https://github.com/ManimCommunity/manim/pull/2311
