### ISSUE TITLE
New example for multiline text

### ISSUE THREAD

**Issue by kolibril13** [ManimCommunity/manim#2281]
The text tutorial should get one example for multiline text:
E.g
```
   VGroup(
          Text("Lorem ipsum dolor sit amet,"),
          Text(" consectetuer adipiscing elit."),
          Text("Aenean commodo ligula eget dolor. "),
      )
      .arrange(DOWN)
```
 Maybe even more advanced with automatic line break and left aligned text.

**Comment by naveen521kk** [comment]
There exists `Paragraph` for doing that right (rather than a VGroup of Texts.)?

**Comment by MrDiver** [comment]
Closing due to previous comment. Seems outdated by now
