### ISSUE TITLE
PowerPoint-like UI for Manim Editor

### ISSUE THREAD

**Issue by suhailsherif** [ManimCommunity/manim#2282]
## Description of proposed feature

I propose a change to the UI of the Manim Editor so that it looks more like the UI of a PowerPoint presentation. Specifically, the left panel should have only a few user-specified points to jump to, with the video between two consecutive points in the panel being made up of multiple sections.

The usefulness of this is most stark in the use case when one is giving a presentation using the current Manim Editor:
- In such a scenario, each section would ideally be a single animation or so, so that the presenter can describe the new content before moving on at their own convenience.
- However, if an audience member were to ask the presenter to go back to a particular slide, these single animation sections will be a pain to browse through.

A similar problem would also arise if someone wants to take a look at your presentation and wants to jump to a specific point.

**Comment by christopher-besch** [comment]
Oh, you created the Issue here. Could you move it over to the [Manim Editor Issue page](https://github.com/ManimEditorProject/manim_editor/issues) please?
For now the project isn't under the official umbrella of the Manim organisation (yet).

**Comment by suhailsherif** [comment]
Moved to the Manim Editor project.
