### ISSUE TITLE
Fraction color-change error

### ISSUE THREAD

**Issue by vilasopher** [ManimCommunity/manim#2296]
## Description of bug / unexpected behavior

When animating a color change for part of a fraction in a MathTex mobject inside of a concurrent animation, the fraction bar does not change color.

## Expected behavior

If the color of the '\over' piece of the TeX is animated to change color in a concurrent animation, the color should actually change.

## How to reproduce the issue

<details><summary>Code for reproducing the problem</summary>

```py
class FractionTest(Scene):
  def construct(self):
    fraction = MathTex(r'1', r'\over', r'2')
    self.add(fraction)
    self.play(fraction.animate.set_color_by_tex(r'1', RED))
    self.play(fraction.animate.set_color_by_tex(r'\over', RED),
              fraction.animate.set_color_by_tex(r'2', RED))
```

</details>

## Additional media files

<details><summary>Images/GIFs</summary>

</details>

## Logs
<details><summary>Terminal output</summary>

```
PASTE HERE OR PROVIDE LINK TO https://pastebin.com/ OR SIMILAR
```

</details>

## System specifications

<details><summary>System Details</summary>

- OS (with version, e.g Windows 10 v2004 or macOS 10.15 (Catalina)):
- RAM:
- Python version (`python/py/python3 --version`):
- Installed modules (provide output from `pip list`):
```
PASTE HERE
```
</details>

<details><summary>LaTeX details</summary>

+ LaTeX distribution (e.g. TeX Live 2020):
+ Installed LaTeX packages:

</details>

<details><summary>FFMPEG</summary>

Output of `ffmpeg -version`:

```
PASTE HERE
```
</details>

**Comment by vilasopher** [comment]
### Update

This bug doesn't just apply to fractions, that's just where I first saw it. I think it actually happens whenever multiple Tex.animate.set_color_by_tex() calls are combined in one self.play() call; only the last animation in the list will actually happen.

**Comment by behackl** [comment]
> ### Update
> This bug doesn't just apply to fractions, that's just where I first saw it. I think it actually happens whenever multiple Tex.animate.set_color_by_tex() calls are combined in one self.play() call; only the last animation in the list will actually happen.

This is actually not surprising: if you want to use `.animate` to apply multiple changes to a mobject in a single play call, then you need to chain these method calls [as instructed in the documentation](https://docs.manim.community/en/stable/reference/manim.mobject.mobject.Mobject.html#manim.mobject.mobject.Mobject.animate); i.e.,

```py
class FractionTest(Scene):
  def construct(self):
    fraction = MathTex(r'1', r'\over', r'2')
    self.add(fraction)
    self.play(fraction.animate.set_color_by_tex(r'1', RED))
    self.play(fraction.animate.set_color_by_tex(r'\over', RED).set_color_by_tex(r'2', RED))
```

**Comment by vilasopher** [comment]
Ah, ok, that makes sense. Thanks! I'll close the issue.
