### ISSUE TITLE
Replace miktex with pylatex

### ISSUE THREAD

**Issue by leotrs** [ManimCommunity/manim#23]
This would reduce the number of non-python dependencies (i.e. packages that cannot be installed via pip and therefore could cause problems during manual installation).

Anyone wants to volunteer?

**Comment by PgBiel** [comment]
I don't think this will be possible or desired. It seems to me that PyLaTeX does not have support for the packages that manim imports. Regardless, MikTeX is of manageable size; TeXLive is the issue. However, it is quite hard to replace it for our purposes.

**Comment by leotrs** [comment]
Am I wrong in thinking that a majority of potential users of manim (who are, presumably, knowledgeable in math), already have some sort of latex distribution on their machines and thus would not care about texlive?

**Comment by PgBiel** [comment]
Probably (this was my case at least; already had it installed)
Still sucks for LaTeX overall that we need this massive... thing... to use it, though 😔

**Comment by leotrs** [comment]
Fair. So if we want to use LaTeX, we will depend on a LaTeX distribution, such as TeXLive. So there is literally nothing to be done here it seems?

**Comment by PgBiel** [comment]
For now, seems like it, yes

If there's something we can do, is make such installation optional, that way users can restrict themselves to Text if needed

**Comment by kilacoda** [comment]
There are smaller alternatives for MiKTeX and TeX Live like [tinytex](https://yihui.org/tinytex/) and [BasicTeX](https://www.tug.org/mactex/morepackages.html) which we could recommend users to use if they only really want to use LaTeX for manim

**Comment by PgBiel** [comment]
> There are smaller alternatives for MiKTeX and TeX Live like [tinytex](https://yihui.org/tinytex/) and [BasicTeX](https://www.tug.org/mactex/morepackages.html) which we could recommend users to use if they only really want to use LaTeX for manim

that's also correct, yes

**Comment by Aathish04** [comment]
> Fair. So if we want to use LaTeX, we will depend on a LaTeX distribution, such as TeXLive. So there is literally nothing to be done here it seems?

Yes. It seems any LaTeX distribution will work, as long as certain package requirements are fulfilled.

**Comment by leotrs** [comment]
I'm all for small latex distributions, as long as we can guarantee that they are installable in Windows/MacOS/Linux.

Also, very much agree that LaTeX should be optional. This should go in the README somewhere.

**Comment by Aathish04** [comment]
Okay:

I've been using BasicTeX on MacOS for almost the entire time ive been using Manim on MacOS and it works flawlessly, except for a few missing packages here or there that were manually installed.

@eulertour 's website has a documentation page that shows install instructions for Linux.
This suggested installing the packages

 ```texlive texlive-latex-extra texlive-fonts-extra texlive-latex-recommended texlive-science texlive-fonts-extra tipa```

Which seem to be enough for Manim.

IMHO, MiKTeX is the best LaTeX distro on Windows for now, as it is the only one with truly automated on the fly package installations.

**Comment by yoshiask** [comment]
> Am I wrong in thinking that a majority of potential users of manim (who are, presumably, knowledgeable in math), already have some sort of latex distribution on their machines and thus would not care about texlive?

@leotrs Unfortunately, many people who are new to Manim haven't even used the command line before. (Source: past and some current GitHub issues in the 3blue1brown/manim repo)

**Comment by yoshiask** [comment]
After some investigation of the PyLaTeX repo, you'd still have to have a LaTeX compiler installed on your machine. It looks like PyLaTeX is just a way of communicating, not necessarily compiling LaTeX without any external dependencies.

**Comment by leotrs** [comment]
Yeah that's fair. I think there's a deeper debate here about what is the target audience of manim. I would love to encourage people with zero technical background to create math videos and content, but at this stage that seems near impossible.

**Comment by Tony031218** [comment]
What about this: https://github.com/ManimCommunity/manim/issues/24#issuecomment-631765727

For those who don’t want to install LaTeX, maybe it is a good choice to use online rendering.

**Comment by yoshiask** [comment]
@Tony031218 I was thinking about that, but then you'd have to have an internet connection every time you want to render a new LaTeX document.

But if we do go with server-side rendering, there is this:
https://latex.codecogs.com/svg.latex?x=\frac{4}{5}

**Comment by PgBiel** [comment]
> @Tony031218 I was thinking about that, but then you'd have to have an internet connection every time you want to render a new LaTeX document.

Indeed, this would require a ton of requests (one for each TexMobject!), plus people would end up installing BasicTeX or similar simply out of convenience.

**Comment by leotrs** [comment]
I think this thread went on a tangent for a bit (I think I derailed it?) My current understanding of the "can we replace miktex" issue is: no, unless we make requests to a private server.

I think making requests a private server would be very very very bad design. Not to mention the requirement of internet an connection.

**Comment by PgBiel** [comment]
I think we can close this issue in favor of #24 or smth

**Comment by leotrs** [comment]
Agreed.
