### ISSUE TITLE
Running the test suite changes space.svg

### ISSUE THREAD

**Issue by eulertour** [ManimCommunity/manim#230]
Running `pytest` edits `tests/tests_cache/writing/TextTest/Text/space.svg`, but the change isn't intentional.

**Comment by leotrs** [comment]
I was hoping that the restyled bot would fix this but it ended up being more annoying than anything. Do we want to add a linter to our CI?

**Comment by leotrs** [comment]
@huguesdevimeux do you have any idea if #335 is going to fix this? If not, maybe we can add `space.svg` to .gitignore for the time being.

**Comment by huguesdevimeux** [comment]
Yes, it will, as now the test cache is using a tempdir ;)
