### ISSUE TITLE
Axes x_step and y_step behave in odd ways

### ISSUE THREAD

**Issue by bth5032** [ManimCommunity/manim#2306]
## Description of bug / unexpected behavior

The only way to control tick marks seems to be with the `x_range` and `y_range` parameters in an Axes() call. However, these parameters are not well documented (at least not on the [Axes page](https://docs.manim.community/en/stable/reference/manim.mobject.coordinate_systems.Axes.html)). They seem to also somehow change how the curve is sampled or something? I can't be sure what's going on, but if I set them to be larger than the axes length in order to create Axes with no ticks, my curves are wrong. 

I provide an example below that plots `1/x**4`.

## How to reproduce the issue

<details><summary>Code for reproducing the problem</summary>

```py
class BuggyScene(Scene):
  def construct(self):
    axes = Axes(
      x_range=[0, 20, 1e-1],
      y_range=[0, 1, 1e-1],
      # x_length=10,
      axis_config={"color": GREEN},
      tips=False,
    )
    self.add(axes)
    f = lambda x: min(1/(x**4 + 1e-7), 10) #need the min() call because otherwise manim creates oscillations when the value gets large
    g = axes.plot(f)
    self.play(Create(g), run_time=3)
    self.wait(2)

    self.play(FadeOut(axes), FadeOut(g), run_time=1)
    #Plot with no ticks

    axes2 = Axes(
      x_range=[0, 20, 100],
      y_range=[0, 1, 100],
      # x_length=10,
      axis_config={"color": GREEN},
      tips=False,
    )
    self.add(axes2)
    g = axes2.plot(f)
    self.play(Create(g), run_time=3)
    self.wait(2)
    t = Text("What is this??")
    t.scale(0.5)
    t.move_to(2*UP + 2*RIGHT)
    self.play(Create(t), run_time=3)
    
```

</details>

## Additional media files

<details><summary>Images/GIFs</summary>

![output](https://user-images.githubusercontent.com/6195617/142402475-c69dfcd1-cd08-476d-a6cf-4d46b045eb3d.gif)

</details>

**Comment by icedcoffeeee** [comment]
Thanks for opening the issue, this is quite an odd interpretation

> these parameters are not well documented

Are the meanings of `x_step` and `y_step` confusing in the documentation? How would you prefer it to be worded instead?

> somehow change how the curve is sampled or something

Yes this is true. If you require more samples, you can pass in the `x_step` between samples with the `x_range` parameter in the `.plot` method.

>  create Axes with no ticks,

You can pass an `axis_config` parameter into `Axes` with a dictionary for kwargs of `NumberLine` like so:
```py
Axes([0, 10], [0, 10], axis_config={"include_ticks":False})
```

**Comment by bth5032** [comment]
Hi, thanks for the quick reply, and the tip on how to get rid of ticks. 

I guess I am confused as to why the tick distances have anything to do with what the function looks like. Shouldn't those things be separate? And if they are not, there is nowhere that explains what's going on. 

I achieved this interpretation from [this reddit thread](https://www.reddit.com/r/manim/comments/p5yoob/how_to_change_tick_frequency_on_axes/) I found from googling.

In any case, the issue is not just one of documentation. You can see in the example that the plot is totally wrong if the step is larger than the axes length... Are you saying this is because we don't have any samples and this is just a random curve that manim likes to draw if it has no data?? That's pretty odd behavior, but I guess not strictly a bug.

**Comment by hydrobeam** [comment]
The docs for the [`plot`](https://docs.manim.community/en/stable/reference/manim.mobject.coordinate_systems.CoordinateSystem.html#manim.mobject.coordinate_systems.CoordinateSystem.plot) method might offer some insight into what's going on and how to handle it. `.plot` does rely on the `x_step` of the axes, and you can manually adjust the sampling rate of `.plot` via the `x_range` parameter you pass into it. 

> I guess I am confused as to why the tick distances have anything to do with what the function looks like. Shouldn't those things be separate? And if they are not, there is nowhere that explains what's going on.

The tick distance and function rely on the `x_step` of the `Axes`, so they're in fact intertwined.

> In any case, the issue is not just one of documentation. You can see in the example that the plot is totally wrong if the step is larger than the axes length... Are you saying this is because we don't have any samples and this is just a random curve that manim likes to draw if it has no data?? That's pretty odd behavior, but I guess not strictly a bug.

Unexpected interactions like the step being longer than the max value of the axis are bound to produce weird behaviour. We don't check for reasonable inputs into `Axes` (at least for now). But there almost always ways to solve problems without needing to do that.

**Comment by bth5032** [comment]
Closing since it seems dev think this is desired behavior
