### ISSUE TITLE
Mention that Manim does not work with Python 3.10 yet in our installation documentation

### ISSUE THREAD

**Issue by Darylgolden** [ManimCommunity/manim#2308]
## Enhancement proposal
Unfortunately, due to dependencies not yet supporting Python 3.10, Manim also cannot work with Python 3.10 yet. I thought this would be resolved quickly, but it seems like there are still problems.

**Comment by lucasricci** [comment]
I would like to take care of that if possible!

**Comment by hydrobeam** [comment]
Addressed by #2310
