### ISSUE TITLE
Adding a log that shows which scene is rendered

### ISSUE THREAD

**Issue by huguesdevimeux** [ManimCommunity/manim#232]
Basically the title. 
This is useful when rendering several scenes at once (with `-a`)

Very easy PR! Feel free :D

**Comment by kilacoda** [comment]
Is something like this ok?
![image](https://user-images.githubusercontent.com/65204531/89121248-e2b9ae00-d4da-11ea-9729-cc6d7bb0db40.png)


or should I put them in separate `logger.info` calls?

**Comment by huguesdevimeux** [comment]
My idea was to put this also at the beginning of the rendering process. But like this is good to me :D

**Comment by kilacoda** [comment]
Ok I'll open a PR soon then.

**Comment by kilacoda** [comment]
Done in #236.
