### ISSUE TITLE
Attribute not updated when animated with `.animate` 

### ISSUE THREAD

**Issue by hydrobeam** [ManimCommunity/manim#2324]
## Description of bug / unexpected behavior

Mobject attributes are not updated when animated with `.animate`, but are successfully changed when done outside of animations

## Expected behavior

The attribute should be updated.

## How to reproduce the issue

```py
class TS(Scene):
    def construct(self):
        c1 = Circle(fill_color=BLUE, fill_opacity=1)

        c1.set_stroke(PURPLE)
        # stroke is changed here, then becomes white 
        c1.set_stroke(WHITE)

        self.add(c1)
        self.play(c1.animate.set_stroke(color=RED)) # visually becomes red, but attribute does not match

        if c1.stroke_color == RED: # stroke_color  attr is `WHITE` not `RED`, so nothing is animated.
            a = Rectangle().to_edge(UP)
            self.play(DrawBorderThenFill(a))
        
        breakpoint()
```

**Comment by citrusmunch** [comment]
maybe related to #2320?

**Comment by BorisTheBrave** [comment]
It's not related to #2320.

If I've understood correctly, `c1.animate.set_stroke(...)` works by cloning `c1` into `c1.target`, then calling set_stroke on the target. The animation then Tranforms from `c1` to `c1.target`, but never actually edits `c1` beyond that.

I would propose a decent fix would be to that `c1.animate.set_stroke` should call `c1.set_stroke` at the appropriate time, possibly during the `finish` step of the animation.
