### ISSUE TITLE
-f flag broken on windows

### ISSUE THREAD

**Issue by huguesdevimeux** [ManimCommunity/manim#233]
I think it would be cool to have such option, so it would avoid the user to spend 10 minutes to look for the generated video. 
It would open the file location with the file browser of the os, so the user will be able to directly get the video file.

This is possible on windows, but I don't know about the other OS (`as os.startfile` is only available on Windows).

**Comment by kilacoda** [comment]
There's already an `-f` option, but I don't think it works on WIndows.
![image](https://user-images.githubusercontent.com/65204531/89120244-6e7b0c80-d4d2-11ea-8018-86ae67550cc7.png)

**Comment by huguesdevimeux** [comment]
I'm an idiot, I did see it was obviously implemented. 

Btw it's broken on windows. Its a very easy fix, I will PR asap !
