### ISSUE TITLE
Text - Changing colors, styles, etc does not work as expected

### ISSUE THREAD

**Issue by buffos** [ManimCommunity/manim#2330]
## Description of bug / unexpected behavior

When you create Text object and use the t2c, t2s etc or use the functions set_color_by_t2c for example, the result is not the expected
and the results are shifted

## Expected behavior

For example

Text("this is the end of the world",  t2c={"end": RED} )

you expect end to be in RED but you see of t in RED.

It seems that the find_indexes finds the indexes in the original text but probably these are not compatible with the chars array?
## How to reproduce the issue

<details><summary>Code for reproducing the problem</summary>
```
    Text("this is the end of the world",  t2c={"end": RED} )
```
</details>

**Comment by PhilippImhof** [comment]
In  the meantime, you could also solve the problem by using `MarkupText` instead of `Text`. This avoids the `t2c` syntax (that I personally find cumbersome) and uses markup similar to basic HTML instead.
