### ISSUE TITLE
Animation stutters when looping through an axes object

### ISSUE THREAD

**Issue by amole-arup** [ManimCommunity/manim#2367]
## Description of bug / unexpected behavior

I am looping through transforming a curve to simulate a ground wave.

## Expected behavior

When I was just modelling the curve, the animation was smooth. However, when I added an offset (prior to 
using get_area to generate soil), the animation started to stutter towards the end.
I am doing this on Google Collaboratory following the manim instructions.

## How to reproduce the issue

I have provided the code below. If you change the depth variable to 3, the animation stutters at the end.
<details><summary>Code for reproducing the problem</summary>

```py
# This is for simulating an earthquake surface wave
# It could be animated by transforming the curve at time t into
# the curve at time t + dt, and putting it into a loop.

from math import sin, cos, pi, exp

def a_func(x, t, v_theta = 5, L_theta = 10, zeta=0.05):
    """x is the position of measurement, t is the time
    v_theta is the speed of the wave, L_theta is the 
    length of the wave, zeta is the damping coefficient"""
    bump = lambda x: 0.5 * (1 - cos(2*pi*(x)/L_theta)) if 0 < x < L_theta else 0
    return bump(x + L_theta - v_theta * t) * exp(-zeta * t)


class EQ(Scene):
    def construct(self):
        # Create equation objects
        a = 1.3
        L = 10 # the length of the field
        L1 = 3
        T1 = 2
        v_theta = 5
        L_theta = 10
        zeta = 0.45
        depth = 0   # HERE ** stutters with value of 3 **
        y1 = lambda x,t: a * sin(2*pi*x/L1 + 2*pi*t/T1)
        
        def the_func(t):
            # return a function of position x
            return lambda x: depth + y1(x, t) * a_func(x, t, v_theta, L_theta, zeta) 

        x_range = (0,L)
        y_range=(-6,6)
        ax = Axes(x_range=x_range, y_range=y_range)
        curve = ax.plot(the_func(0), color=WHITE)
        self.add(curve)
        
        # Loop to generate animation
        for t in range(1, 40):
            # set curve_new equal to the graph at a new time t + dt
            curve_new = ax.plot(the_func(0.1*t), color=WHITE)
            self.play(Transform(curve, curve_new, lag_ratio=0.9, run_time=0.1))
          
        self.wait(2)
```

</details>

## Additional media files

<details><summary>Images/GIFs</summary>

No stutter (depth = 0)
https://user-images.githubusercontent.com/77268469/145170188-7e3ef3bd-aeb0-4bd6-aa35-a8a7fe174960.mp4

Stutter at end (depth = 3)
https://user-images.githubusercontent.com/77268469/145170246-ee0a1085-ab6c-4dd1-b902-ed42c1d0a359.mp4

</details>

## Logs
<details><summary>Terminal output</summary>

```
PASTE HERE OR PROVIDE LINK TO https://pastebin.com/ OR SIMILAR
```

</details>

## System specifications

<details><summary>System Details</summary>

- OS (with version, e.g Windows 10 v2004 or macOS 10.15 (Catalina)):
- RAM:
- Python version (`python/py/python3 --version`):
- Installed modules (provide output from `pip list`):
```
PASTE HERE
```
</details>

<details><summary>LaTeX details</summary>

+ LaTeX distribution (e.g. TeX Live 2020):
+ Installed LaTeX packages:

</details>

<details><summary>FFMPEG</summary>

Output of `ffmpeg -version`:

```
PASTE HERE
```
</details>

**Comment by behackl** [comment]
Just tried to render locally, does not stutter for me. Cannot reproduce.
