### ISSUE TITLE
Documentation example typo

### ISSUE THREAD

**Issue by netwizard22** [ManimCommunity/manim#2389]
## Description of bug / unexpected behavior

Rotate without () [here](https://docs.manim.community/en/stable/reference/manim.mobject.types.vectorized_mobject.VMobject.html#changeofdirection)
Found by WichoTutorialesYT

```py
class ChangeOfDirection(Scene):
    def construct(self):
        ccw = RegularPolygon(5)
        ccw.shift(LEFT).rotate
        cw = RegularPolygon(5)
        cw.shift(RIGHT).reverse_direction()
        self.play(Create(ccw), Create(cw),
        run_time=4)
```

**Comment by behackl** [comment]
Thank you for reporting! Would you like to try and submit a patch for fixing this yourself? It would be a good first contribution, and it should be possible to do it all from the website:

The source for this example can be found here:  https://github.com/ManimCommunity/manim/blob/main/manim/mobject/types/vectorized_mobject.py#L1643

**Comment by netwizard22** [comment]
@behackl the thing is we need to edit the docs too. Are they autogenerated from the code you've provided? If so, how can I preview the changes I have made?

**Comment by Darylgolden** [comment]
> @behackl the thing is we need to edit the docs too. Are they autogenerated from the code you've provided? If so, how can I preview the changes I have made?

Yes, they are.

**Comment by lucasricci** [comment]
@netwizard22 I took this issue because it hasn't been any update for more than 2 weeks, so I decided to fix it, hope it don't disturb you. And if so, sorry.
