### ISSUE TITLE
What about "Manim.js" in javascript !?

### ISSUE THREAD

**Issue by NavpreetDevpuri** [ManimCommunity/manim#241]
It will be great if there is a library in javascript that can make the exact same video that manim in python does. 

I checked [this](https://github.com/isaacvr/manim-js) but it not able to perform that transformation between SVG files and even not able to perform the same writing animations.

Manim.js library will also use for manipulating SVG files in HTML page, that will be great. It will be very easy to use because it will be easy to setup. It will be cross-platform. It will can be used with other awesome libraries to even more creative works with it.

I just started it [here](https://github.com/NavpreetDevpuri/Manim.js) but I am very confused about how should I start it? 

Any guidance/help will be very appreciable.

**Comment by leotrs** [comment]
@eulertour

**Comment by eulertour** [comment]
I'm currently working on a javascript frontend to manim in [this repo](https://github.com/eulertour/manim-renderer). There's a compatible version of manim on [this branch](https://github.com/ManimCommunity/manim/tree/renderer-integration).

If you want any help setting it up get in touch with me on [the discord](https://discord.gg/mMRrZQW).
