### ISSUE TITLE
ManimCE violates the GNU GPL license

### ISSUE THREAD

**Issue by marcin-serwin** [ManimCommunity/manim#2418]
Firstly, I am _not_ a lawyer and this is only my understanding.

ManimPango is [licensed](https://github.com/ManimCommunity/ManimPango/blob/main/LICENSE) under the GPLv3. As per the license terms this means that the program linking to it must be released under the GPL license (see [FAQ](https://www.gnu.org/licenses/gpl-faq.html#IfLibraryIsGPL)). Manim uses ManimPango, thus it should be licensed under the GPLv3, but it [isn't](https://github.com/ManimCommunity/manim/blob/main/LICENSE.community).

As I see it (again, I am _not_ a lawyer), there are three ways to resolve it:
- Remove ManimPango from the project - this is the most straightforward path.
- Relicense the ManimCE to GPLv3 - since the rest of the code is under GPL-compatible licenses (to my knowledge), it should be possible for the current maintainers to simply change the license of the project accordingly.
- Change the license of ManimPango to a license without strong copyleft (LGPL?) - this requires for all the copyright holders of ManimPango code (contributors, I think) to release their code under an appropriate chosen license.

**Comment by behackl** [comment]
I think this is a valid concern.

@naveen521kk  @PhilippImhof what do you think?

**Comment by GameDungeon** [comment]
It would not be hard to change ManimPango, as it only has like 6 contributors, and if any don't respond you can always overwrite their small changes.

**Comment by PhilippImhof** [comment]
Removing ManimPango does not seem to be very straightforward for me, because we would lose all non-LaTeX text functionality.

However, I am absolutely fine with changing the license. @naveen521kk has contributed much more than I, but I think he would not mind either.

For me, any license is fine.

**Comment by marcin-serwin** [comment]
> Removing ManimPango does not seem to be very straightforward for me, because we would lose all non-LaTeX text functionality.

By straightforward I've only meant the restoring of compliance with GPL. The first two proposed resolutions have far reaching consequences for users of ManimCE. Thus in that regard the third one is actually the most straightforward.

**Comment by naveen521kk** [comment]
> Change the license of ManimPango to a license without strong copyleft (LGPL?) - this requires for all the copyright holders of ManimPango code (contributors, I think) to release their code under an appropriate chosen license.

Yeah, I am fine with that. I have written most of the code there and it's fine for me to relicense to something like LGPL. I faintly remember making a private conversation with @PhilippImhof about this a long time ago.

> I would suggest converting it to MIT

If I understand the licenses correctly I think ManimPango can't be licensed under something which isn't GPL or LGPL based because Pango has been licensed under LGPL, right? I would be happy to release under BSD or MIT licenses if I'm allowed to, but I'm not sure.

**Comment by PhilippImhof** [comment]
I have had a look at the commits. As I can see, we have @jsonvillanueva who contributed [one commit](https://github.com/ManimCommunity/ManimPango/commit/651bfb0bf5e35de65c2496df91e290e4ef171d1d) related to the code of conduct. As we are mainly talking about the code's license, this is not important. I still tagged them, so we can get their stance on the issue.

We also have @leotrs who did some (very minor) change to the docstrings in ManimCommunity/ManimPango#10. I tagged him anyhow, because it is a good opportunity to greet him :) 

Next is @RickyC0626 with [three commits](https://github.com/ManimCommunity/ManimPango/commits?author=RickyC0626). Could they please tell whether they agree with a change of license with or without reservation?

And finally, we have @marcin-serwin. As they raised the issue and suggested a change of license, I believe they have nothing against it?

I think it is best to ask the folks over at Pango whether ManimPango can be licensed as MIT or BSD, but as @naveen521kk says, I also think LGPL will be the way to go. However, I am by no means an expert for licensing questions.

**Comment by PhilippImhof** [comment]
IIRC it's only bindings, but I'd rather wait for @naveen521kk to confirm...

**Comment by naveen521kk** [comment]
> Is it just bindings or does it contain any Pango code. If the former it can be MIT if the latter then it has to be GPL.

It's just the bindings. Can you show an example where the binding is licensed under MIT while the main library is LGPL? I am asking this so that I will not be bothered to change the license of that code again.

**Comment by GameDungeon** [comment]
BTW LGPL is not compatible with GPL2, nor is GPL3. The search terms copyright and binding give too much noise so I don't know.

**Comment by GameDungeon** [comment]
Uggggg

> However, when the interpreter is extended to provide “bindings” to other facilities (often, but not necessarily, libraries), the interpreted program is effectively linked to the facilities it uses through these bindings. So if these facilities are released under the GPL, the interpreted program that uses them must be released in a GPL-compatible way. The JNI or Java Native Interface is an example of such a binding mechanism; libraries that are accessed in this way are linked dynamically with the Java programs that call them. These libraries are also linked with the interpreter. If the interpreter is linked statically with these libraries, or if it is designed to link dynamically with these specific libraries, then it too needs to be released in a GPL-compatible way.
> 
> Another similar and very common case is to provide libraries with the interpreter which are themselves interpreted. For instance, Perl comes with many Perl modules, and a Java implementation comes with many Java classes. These libraries and the programs that call them are always dynamically linked together.
> 
> A consequence is that if you choose to use GPLed Perl modules or Java classes in your program, you must release the program in a GPL-compatible way, regardless of the license used in the Perl or Java interpreter that the combined Perl or Java program will run on

**Comment by GameDungeon** [comment]
"14. If you wish to incorporate parts of the Library into other free
programs whose distribution conditions are incompatible with these,
write to the author to ask for permission."

**Comment by RickyC0626** [comment]
I'm fine with a license change, whichever decision best benefits the community. Since Pango is using the old LGPLv2 license, and not LGPLv2.1, it would not be compatible with GPL, but it would offer more freedom of use.

**Comment by marcin-serwin** [comment]
@GameDungeon The cited passages refer to GPL, but Pango (and Cairo) are released under LGPL. To be more precise [Pango is under LGPL 2.0](https://gitlab.gnome.org/GNOME/pango/-/blob/main/COPYING), section 6 of this license states (emphasis mine):
>  As an exception to the Sections above, you may also compile or link a "work that uses the Library" with the Library to produce a work containing portions of the Library, and **distribute that work under terms of your choice**, provided that the terms permit modification of the work for the customer's own use and reverse engineering for debugging such modifications. 

There are other requirements for use, but my basic understanding is that ManimPango and Manim can be released as MIT provided that they contain license text and mention the usage of LGPL content somewhere.

On a related note it may be a good idea to create some main document (e.g. `ACKNOWLEDGEMENTS.md`) with the copyright notices of all dependencies (since most of them require attribution anyway) and print them when manim is invoked with `--copyright` or `--license` flags (similar to python's `copyright` and `license` commands).

**Comment by GameDungeon** [comment]
Ah I though Pango was GPLv2 my bad.

**Comment by naveen521kk** [comment]
> There are other requirements for use, but my basic understanding is that ManimPango and Manim can be released as MIT provided that they contain license text and mention the usage of LGPL content somewhere.

So changing the license of ManimPango to MIT, should work right? And mention somewhere (in the README and wheels) probably that it contains LGPL code from Pango, should work right?

**Comment by naveen521kk** [comment]
I have made https://github.com/ManimCommunity/ManimPango/pull/72

**Comment by marcin-serwin** [comment]
> So changing the license of ManimPango to MIT, should work right? And mention somewhere (in the README and wheels) probably that it contains LGPL code from Pango, should work right?

Again, I am not a lawyer, but my understanding is that we need to mention that LGPL code is used and attach full license text.

**Comment by naveen521kk** [comment]
> Again, I am not a lawyer, but my understanding is that we need to mention that LGPL code is used and attach full license text.

I have already attached the full license text in the wheels for a long time now: see https://github.com/ManimCommunity/ManimPango/blob/main/packing/LICENSE.bin and I think that should be fine on ManimPango's part I guess, right? I am wondering where it should be mentioned in manim though. Even pycairo/cairo is LGPL and we haven't mentioned it anywhere.

Should we email FSF for clarification (I think they should help out right?)?

**Comment by PhilippImhof** [comment]
I suggest we'd rather ask the people over at Pango (and maybe Cairo). It's their software, so they could also just grant an exception if it is not 100% correct but does not bother them.
