### ISSUE TITLE
Checking rules are too tight (unnecessary tight) ! I suggest to accept more then one standard.

### ISSUE THREAD

**Issue by NavpreetDevpuri** [ManimCommunity/manim#242]
As I am trying to open a this https://github.com/ManimCommunity/manim/pull/198 PR 

Rules are too tight(unnecessary tight) for example I am using prettifier in visual studio code and it puts `a:5` as `a: 5` but checker want it to be `a : 5` instead of `a: 5`, I think that's wrong and it will slow development process. Remove those checks or make them loose, so that it can accept both formats. 

![chrome_Pvt9tHDemk](https://user-images.githubusercontent.com/30471072/89190844-ac099380-d5bf-11ea-9b68-cec1a8981cb0.png)

See even Grammarly is saying this its wrong
![ENk1Dvv8YF](https://user-images.githubusercontent.com/30471072/89191468-99dc2500-d5c0-11ea-9e20-a8ce09b6533a.png)

I just mean to say its too tight roles, so much that it's(the little things) not that necessary. I suggest accepting more standard formats. I mean if this is possible then please add a condition or something that checks for multiple standards and if any of the standard matches then it should accept the code.

**Comment by leotrs** [comment]
The reason for changing `a: 5` to `a : 5` is explained [here](https://black.readthedocs.io/en/stable/the_black_code_style.html#slices). `black` is using the same amount of space around the colon `:` operator when it appears within a slice.

I completely agree with `black`'s decision here, and see no reason to change it.

Please stop quoting what Grammarly says. Grammarly is **NOT** a tool meant to check code.

**Comment by NavpreetDevpuri** [comment]
I think we should somehow auto formate code before merge if possible. what do you think? 🤔

**Comment by leotrs** [comment]
You can run `black` locally and it will autoformat your code before you submit a PR.

**Comment by kilacoda** [comment]
Just use <kbd>Shift</kbd>+<kbd>Alt</kbd>+<kbd>F</kbd> if you're using VSCode and select the `black` option from the list that follows

**Comment by kilacoda** [comment]
> Then developers can use their favorite formats or sometimes they are compelled to use some specific formates and then they don't need to worry about `black`

You can use whatever format you want to use while writing your code, just format it with black once before committing.

**Comment by NavpreetDevpuri** [comment]
Thanks, @leotrs, and @kilacoda. it helped and works! 😀
