### ISSUE TITLE
`get_quadratic_approximation_of_cubic` should also use `bezier` and `classic_bezier` should be removed

### ISSUE THREAD

**Issue by behackl** [ManimCommunity/manim#2427]
The implementation of `get_quadratic_approximation_of_cubic` caused some headache: when I tried to replace the current implementation of `bezier`, a test using `get_quadratic_approximation_of_cubic` started to fail because the points  used in that function are not just 1d-numpy arrays as usual, but instead 2d ones. If someone wants to take a stab at fixing this, please go ahead -- then this `classic_bezier` function could also just be removed.

_Originally posted by @behackl in https://github.com/ManimCommunity/manim/pull/2421#discussion_r777780913_

**Comment by chopan050** [comment]
PR #3829 had the side effect of removing calls to `bezier`. Thus, in the future, if someone wants to continue with PR #2421, they should now be able to rewrite the `bezier` function without having to move the old code into `classic_bezier`.

Closing this issue.
