### ISSUE TITLE
Docs' Tutorial: Redundant command

### ISSUE THREAD

**Issue by AnonymoZ** [ManimCommunity/manim#2434]
The command **self.add(square)** is redundant and must be removed since it is ignored because of the next **FadeIn** command, and also the command does not achieve our goal for this script which is to demonstrate an animation. We have no need to statically place the square we created on the screen before fading it in.

https://docs.manim.community/en/stable/tutorials/building_blocks.html#someanimations

```
class SomeAnimations(Scene):
    def construct(self):
        square = Square()
        self.add(square) 🚨 🚨 🚨

        # some animations display mobjects, ...
        self.play(FadeIn(square))

        # ... some move or rotate mobjects around...
        self.play(Rotate(square, PI/4))

        # some animations remove mobjects from the screen
        self.play(FadeOut(square))

        self.wait(1)
```

By the same token, there is a typo of `sqaure` at:

https://docs.manim.community/en/stable/tutorials/building_blocks.html#animating-methods

**Comment by behackl** [comment]
Very well spotted, thank you! Are you interested in patching this yourself? The corresponding file would be here: https://github.com/ManimCommunity/manim/blob/main/docs/source/tutorials/building_blocks.rst

**Comment by AnonymoZ** [comment]
Whew! All that was very scary, but I managed to do it, thanks to you! I could submit the pull request!

**Comment by behackl** [comment]
We usually leave issues open until the corresponding pull request has been merged, but in this case it doesn't really make a difference. Thanks for contributing!
