### ISSUE TITLE
Add Manim Project Creating Subcommand

### ISSUE THREAD

**Issue by naveen521kk** [ManimCommunity/manim#244]
How about a sub command for example, `manim new project`, which will create a folder with some scripts assets folder and also a config file. This would be helpful for new users and we can make the users use uniform folder structure. This would surely be helpful while debugging and the users can keep the projects organised and not like I usually do.
PS. I got the idea from [chocolatey](https://chocolatey.org).

**Comment by leotrs** [comment]
I like this idea. I'd suggest the command be `manim init`. What do you think this command should do? What directories should it create? How will the config file be generated? Etc. Let's flesh this out a bit more :)

**Comment by naveen521kk** [comment]
```
├───assets
│   ├───codes
│   ├───images
│   └───sounds
├───logs
└───media
    ├───Tex
    ├───texts
    └───videos
```
This command should create should project structure. The config file can be generated as a copy of `default.cfg` and later the users can edit it using the command introduced by #212 . This need to be discussed a lot.

**Comment by leotrs** [comment]
Yes, we'd have to discuss if we want to force/suggest a particular folder structure for the input files (what you called `assets/`). The output files (`media/`) are already enforced.

**Comment by Aathish04** [comment]
> we'd have to discuss if we want to force/suggest a particular folder structure for the input files

`assets/` is already the places where Manim looks for images, audio files etc.

https://github.com/ManimCommunity/manim/blob/70c0d53a01ee6cd1da9a74c0338ed404f67b9123/manim/mobject/svg/code_mobject.py#L146-L149

https://github.com/ManimCommunity/manim/blob/70c0d53a01ee6cd1da9a74c0338ed404f67b9123/manim/mobject/svg/svg_mobject.py#L49-L54

https://github.com/ManimCommunity/manim/blob/70c0d53a01ee6cd1da9a74c0338ed404f67b9123/manim/utils/images.py#L12

https://github.com/ManimCommunity/manim/blob/70c0d53a01ee6cd1da9a74c0338ed404f67b9123/manim/utils/sounds.py#L28

**Comment by leotrs** [comment]
Oh? Ok in that case we should document that somewhere in the mythical quickstart guide. 

In that case, I'm leaning toward making a quick-and-dirty `manim init` command!

**Comment by Aathish04** [comment]
> In that case, I'm leaning toward making a quick-and-dirty `manim init` command!

I just want to clarify that manim will search for `assets` from the current working directory, not from wherever the actual animation script is.

Before we implement `manim init` I think we should first ensure that manim also checks for the presence of `assets` folders next to the actual animation script and not just the cwd, like we are doing for the `cfg` file.

And like the cfg file, we could make the `assets` folder next to the file have the greatest priority, and the one in the `cwd` have the next greatest and so on.

**Comment by azarzadavila** [comment]
I'd like to contribute to this if nobody is on it. So that it gives a first idea of what it could look like.

**Comment by Aathish04** [comment]
> I'd like to contribute to this if nobody is on it. So that it gives a first idea of what it could look like.

@azarzadavila 
From my side, I'd just like to inform you that I'll be working on making it easier to add subcommands (adding notes, clearing up confusing code etc) and fixing some bugs in how subcommands are selected. I should take a PR doing this by this Sunday (I hope).

Please don't feel as if I'm restricting you, I'd just like to say that there will be a few changes to the code that will make it just a tiny bit easier to do this sort of stuff . You can still work on this in the meantime should you wish to.

**Comment by azarzadavila** [comment]
> > I'd like to contribute to this if nobody is on it. So that it gives a first idea of what it could look like.
> 
> @azarzadavila
> From my side, I'd just like to inform you that I'll be working on making it easier to add subcommands (adding notes, clearing up confusing code etc) and fixing some bugs in how subcommands are selected. I should take a PR doing this by this Sunday (I hope).
> 
> Please don't feel as if I'm restricting you, I'd just like to say that there will be a few changes to the code that will make it just a tiny bit easier to do this sort of stuff . You can still work on this in the meantime should you wish to.

@Aathish04 
Ah okey great. There really is no rush so I think I'll wait.

**Comment by Aathish04** [comment]
> Ah okey great. There really is no rush so I think I'll wait.

@azarzadavila The PR I was talking about has been merged. You can implement `manim init` now!

**Comment by leotrs** [comment]
@azarzadavila are you interested in implementing this? :)

**Comment by cobordism** [comment]
Hi everyone,
I think this is a great idea.

A few thoughts:
You don't have to create the `/media` folder because 
(a) manim will create it anyway when you compile the scene 
(b) but the media directory will be created somewhere else entirely if the user supplies the --media-dir cli flag, or changes it in the .cfg file and the we'd be left with empty and unused directories here.

> manim new project, which will create a folder with some scripts assets folder and also a config file

If we are going to generate a bunch of directories, then this is how we would do it.
If however we take a more lightweight approach and generate only a python file and a config file then we don't need to create an entire directory.
We could do something like: `manim new name` and generate a name.py file with scaffolding for a scene (also called name) and a name.cfg file, and nothing more.
It's quick. it's clean. We don't need to worry about assets subfolders or the order in which they are search....  and it is probably enough for almost all users almost all of the time. no?

**Comment by leotrs** [comment]
I like the idea of keeping it short and to the point. Any more functionality sounds like we will hit a situation of diminishing returns. Especially because every new functionality will require new tests and more maintenance etc.

**Comment by jsonvillanueva** [comment]
This should be implemented after #1013 is merged

**Comment by WampyCakes** [comment]
I think that when this command is called it also ought to include on the first line of the generated script:
```
# Manim Community vX.Y.Z
```
If the user doesn't want it, they can just delete the line once and it'll never be there again. Otherwise, they now can look back at the script later and tell what version they used (or others can tell).

**Comment by e4coder** [comment]
Can I get assigned?
I have some ideas. 

The 'project' subcommand will create a folder <name> and a subfolder 'assets'. and it will also generate a config file and a main.py. I was thinking that in each manim project there has to be one python file that will import all scenes from within the project.
```
manim new project <name>
```

The 'scene' subcommand will create a new file with a new scene. this scene may automatically be imported in the main.py file as well as config.cfg file. I was also thinking of scene templates. where the user may give an additional argument naming the template that he wants to use or subcommand can prompt another input demanding the name of the template. if the user does not provide a name then the default template will be used for the new file generation.


```
manim new scene <filename> <scene_name>
```

**Comment by e4coder** [comment]
We can also implement a `manim init` command this command will be similar to `new project` command but `manim` init will prompt input for the project name.

**Comment by jsonvillanueva** [comment]
Assigned you! ... although I'm not sure if this is actually a `good first issue` since we've recently transitioned from argparse to click, our GitHub Wiki on adding subcommands is out of date, and there's currently no replacement documentation on how to actually do this. Do message out here, or (preferably) on Discord if you run into any issues in creating the subcommand, or any of the logic for this.

**Comment by e4coder** [comment]
Thank you! ill reach out if I get stuck anywhere.

**Comment by e4coder** [comment]
Hey guys,

The code for these commands is about 200 lines.
I was thinking maybe I should add 1 command per PR. I think this will help in the review process.

**Comment by e4coder** [comment]
I have opened up a pull request #1418
