### ISSUE TITLE
Refactor `manim/mobject` into grouped directories.

### ISSUE THREAD

**Issue by hydrobeam** [ManimCommunity/manim#2445]
## Enhancement proposal

There was some discussion on making the codebase easier to digest and moving away from having dangling files in `manim/mobject`.

Here are some suggestions for how modules can be grouped

```
graphing
├── coordinate_systems.py
├── functions.py
├── number_line.py
├── probability.py
└── scale.py
```

```
text
├── code_mobject.py
├── numbers.py
├── tex_mobject.py
└── text_mobject.py
```

by splitting apart `geometry.py`:
```
geometry/
├── line.py
├── polygram.py
├── tipable.py
└── tips.py
```

```
opengl
├── opengl_compatibility.py
├── opengl_mobject.py
├── opengl_point_cloud_mobject.py
├── opengl_surface.py
├── opengl_three_dimensions.py
└── opengl_vectorized_mobject.py
```

This would entail moving some files around out of other files.

Here's the full overview of `/mobject` after these changes

```
.
├── boolean_ops.py
├── changing.py
├── frame.py
├── geometry
├── graphing
├── graph.py
├── __init__.py
├── logo.py
├── matrix.py
├── mobject.py
├── mobject_update_utils.py
├── opengl
├── shape_matchers.py
├── svg
├── table.py
├── text
├── threed
├── types
├── value_tracker.py
└── vector_field.py
```

There were some modules that I wasn't sure how to group, so were just left hanging in the directory. `table.py`/`matrix.py`/`graph.py` feel ""vaguely"" related? but i'm not sure if that's my brain scrambling for connections to try to group more files. Also, `mobject.py/vectorized_mobject.py` should probably be together.

**Comment by Darylgolden** [comment]
We could put the remaining files in a `special` folder as well.
