### ISSUE TITLE
AssertionError on test_logging.py solved by strip()

### ISSUE THREAD

**Issue by azarzadavila** [ManimCommunity/manim#245]
I have an assertion error on `logs == expected, logs` on the last line of test_logging.py when running pytest.
I think it is simply an issue with trailing spaces as replacing the end of the file by
```python
logs = logs.strip()
expected = expected.strip()
assert logs == expected, logs
```
yields a test success.

**Comment by Aathish04** [comment]
Is this the latest version of the master branch?

If so, I think @huguesdevimeux will have some reservations about stripping whitespace from the logs, as they need to be _exactly_ the same for testing purposes...

**Comment by azarzadavila** [comment]
I ran the tests on a newly cloned version of the repository but I see the tests work on the CI setup. Do you think it may be a local issue ? I have run `pip install .` just before testing so I am what could be wrong.

**Comment by Aathish04** [comment]
I _don't_ think it's a local issue. I think it's just an edge case not caught by my regex, which will be scrapped as soon as I can get the time to work on it.

Could you please post the exact AssertionError? And also state which version of `rich` you're using?

**Comment by azarzadavila** [comment]
The exact assertion error is :
```
E       AssertionError:            INFO     Read configuration files:
                                                                                                                                     config.py:
E                    INFO
                                                                                                           scene_file_writer.py:
E                             File ready at

E
E       assert '           I...           \n' == '           I...           \n'
E         Skipping 760 identical leading characters in diff, use -v to show
E         Strings contain only whitespace, escaping them using repr()
E         - '          \n

           \n'
E         + '          \n'

tests/test_logging/test_logging.py:58: AssertionError

```
I am running `rich` on version 3.3.2.

**Comment by Aathish04** [comment]
> I am running `rich` on version 3.3.2.
Could you please try running the same test on a Rich version _above_ `4.2.1`? I recommend that you use the latest, rich `5.0.0`.

The reasons for this are detailed in this issue: https://github.com/willmcgugan/rich/issues/190

**Comment by behackl** [comment]
I had the same issue, running the test again with rich `5.0.0` fixes the issue.

Maybe `rich>=4.2.1` should be specified in `requirements.txt`?

**Comment by azarzadavila** [comment]
It indeed solves the issue for me

**Comment by leotrs** [comment]
Interesting. Can we please fix the Rich version in the requirements.txt
file?
