### ISSUE TITLE
`Uncreate` does not work as expected when overriding the default argument for `rate_func`

### ISSUE THREAD

**Issue by Darylgolden** [ManimCommunity/manim#2469]
## Description of bug / unexpected behavior
When passing any argument for `rate_func` to the `Uncreate` animation, the result is exactly the same as would be seen from using the `Create` animation. For instance,

```py
class Bug(Scene):
    def construct(self):
      s = Square()
      self.add(s)
      self.play(Uncreate(s), rate_func=smooth)
      self.wait()
```

produces:

https://user-images.githubusercontent.com/9102529/150136839-6073c3be-01cb-4bf7-8931-3968a468aa49.mp4

Currently, `Uncreate` just inherits from `Create` and overrides the default `rate_func` argument. This is a poor implementation; it should either inherit directly from `ShowPartial`, or a general method to reverse animations should be implemented. The `Uncreate` animation will then just be a special case of a reversed animation.

## How to reproduce the issue

<details><summary>Code for reproducing the problem</summary>

```py
Paste your code here.
```

</details>

## Additional media files

<details><summary>Images/GIFs</summary>

</details>

## Logs
<details><summary>Terminal output</summary>

```
PASTE HERE OR PROVIDE LINK TO https://pastebin.com/ OR SIMILAR
```

</details>

## System specifications

<details><summary>System Details</summary>

- OS (with version, e.g Windows 10 v2004 or macOS 10.15 (Catalina)):
- RAM:
- Python version (`python/py/python3 --version`):
- Installed modules (provide output from `pip list`):
```
PASTE HERE
```
</details>

<details><summary>LaTeX details</summary>

+ LaTeX distribution (e.g. TeX Live 2020):
+ Installed LaTeX packages:

</details>

<details><summary>FFMPEG</summary>

Output of `ffmpeg -version`:

```
PASTE HERE
```
</details>

**Comment by tutacat** [comment]
`rate_func=lambda t, inflection=10.0: smooth((1-n), t=t)`

**Comment by Darylgolden** [comment]
That's a workaround, but still doesn't resolve the unexpected behavior.
