### ISSUE TITLE
CLI doesn't use correct formats when using `-a`

### ISSUE THREAD

**Issue by pavelzw** [ManimCommunity/manim#2470]
## Description of bug / unexpected behavior
When using `manim -a` on a file that contains videos, but also images, all scenes that are rendered after the image is rendered are also rendered as an image.

## Expected behavior
Manim should render the correct format for each scene separately.

## How to reproduce the issue
When executing `manim -a test.py`, it should create `media/videos/test/1080p60/Scene1Video.mp4`, `media/videos/test/1080p/Scene3Video.mp4`, `media/images/test/Scene2Image.png`.

Instead, it creates `media/videos/test/1080p60/Scene1Video.mp4`, `media/images/test/Scene3Video.png`, `media/images/test/Scene2Image.png`.

<details><summary>Code for reproducing the problem</summary>

`test.py`:
```py
from manim import Scene, Circle, Create


class Scene1Video(Scene):
    def construct(self):
        self.play(Create(Circle()))


class Scene2Image(Scene):
    def construct(self):
        self.add(Circle())


class Scene3Video(Scene):
    def construct(self):
        self.play(Create(Circle()))
```

</details>

## System specifications

<details><summary>System Details</summary>

- OS (with version, e.g Windows 10 v2004 or macOS 10.15 (Catalina)): Windows 10 21H2
- RAM: 32GB
- Python version (`python/py/python3 --version`): 3.8.10
- Installed modules (provide output from `pip list`):
```
Package             Version
------------------- -----------
certifi             2021.10.8
charset-normalizer  2.0.7
click               8.0.3
click-default-group 1.2.2
cloup               0.7.1
colorama            0.4.4
colour              0.1.5
commonmark          0.9.1
decorator           5.1.0
glcontext           2.3.4
idna                3.3
isosurfaces         0.1.0
manim               0.14.0
ManimPango          0.4.0.post0
mapbox-earcut       0.12.10
moderngl            5.6.4
moderngl-window     2.4.0
multipledispatch    0.6.0
networkx            2.6.3
numpy               1.21.2
Pillow              8.3.2
pip                 21.3.1
pycairo             1.20.1
pydub               0.25.1
pyglet              1.5.21
Pygments            2.10.0
pyrr                0.10.3
requests            2.26.0
rich                10.12.0
scipy               1.7.1
screeninfo          0.6.7
setuptools          58.2.0
six                 1.16.0
skia-pathops        0.7.1
srt                 3.5.0
tqdm                4.62.3
urllib3             1.26.7
watchdog            2.1.6
```
</details>

**Comment by Kiran-Raj-Dev** [comment]
From what I've tested so far, the rendering pipeline breaks if a class that has a `self.add()` calls gets rendered after or before classes with `self.play()` calls. Here's what I mean, let's say you have the following script:
```py
class <your-class1>(Scene):
    def construct(self):
        # ---- Lots of animations ----
        self.play(anims)
# .
#--- More animation classes
# .
class cluprit(Scene):
    def construct(self):
        # ---- Lots of mobjects ----
        self.add(mobjects)
# .
#--- More animation classes
# .
class <your-class1>(Scene):
    def construct(self):
        # ---- Lots of animations ----
        self.play(anims)
```
the above code will have videos for the classes rendered before `culprit` and only images after that, but if you place the culprit such that it is rendered at the start or the end then it does work as expected.

EIther like this:-
```py
class cluprit(Scene): # <-- rendered first
    def construct(self):
        # ---- Lots of mobjects ----
        self.add(mobjects)
# .
#--- More animation classes
# .
class <your-class1>(Scene):
    def construct(self):
        # ---- Lots of animations ----
        self.play(anims)
# .
#--- More animation classes
# .

class <your-class1>(Scene):
    def construct(self):
        # ---- Lots of animations ----
        self.play(anims)
```
Or like this:-
```py
class <your-class1>(Scene):
    def construct(self):
        # ---- Lots of animations ----
        self.play(anims)
# .
#--- More animation classes
# .

class <your-class1>(Scene):
    def construct(self):
        # ---- Lots of animations ----
        self.play(anims)
# .
#--- More animation classes
# .

class cluprit(Scene): # <-- rendered last
    def construct(self):
        # ---- Lots of mobjects ----
        self.add(mobjects)
```

Also the classes are rendered in alphabetical order apparently, so this placing first, last and interleaved business should actually be taken care of in the class naming and not their placement in the manim script file.

I wasn't able to track down what was causing this though :(
