### ISSUE TITLE
Trying to hadling Colors for SVGMobject. It automatically make value to default value "white" for all submobjects. Please help me to troubleshoot this.  

### ISSUE THREAD

**Issue by NavpreetDevpuri** [ManimCommunity/manim#248]
Check code [here](https://github.com/NavpreetDevpuri/manim/blob/colored-svg/manim/mobject/svg/svg_mobject.py) 

When i try to print `fill_color` value for a submobject at line 87 `# print(temp[0].get_fill_color())` it prints values as expected but when we initialize any SVGMobject containing colors then try to print `print(svgMobject[0].get_fill_color())` it shows different color always show "WHITE".
I tried following `example.svg` SVG file 
```xml
<?xml version="1.0" encoding="utf-8"?>
<!-- Generator: Adobe Illustrator 24.2.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 viewBox="0 0 493.9 493.9" style="enable-background:new 0 0 493.9 493.9;" xml:space="preserve">
<style type="text/css">
	.st0{fill:#3CD4A1;}
</style>
<g id="Layer_2_1_">
	<path class="st0" d="M259.6,73.3l-0.1,224.8l-1.3,1.2c-6.8,6.1-19.7,13.7-33.8,13.7c-9.2,0-18.1-3.4-25-9.5l-0.3-0.3l-4.5-4.7
		c-7.2,0.7-30.9,1.6-45.1-13.2c-9.4-9.9-12.5-24.6-9.1-43.7c-4.5-4.2-15.7-16.4-15.7-31.6c0-10.4,5.3-19.9,15.6-28.2l1.2-1
		c-2.6-7.1-8.3-26.1-0.5-39.9c4.5-7.9,12.5-12.6,23.8-14h0.1c0.1-15.8,6.5-41.4,31.4-44.1h0.3h1.5c2.5-5.8,9.6-19.1,23.1-22.9
		c11.1-3.1,23.6,1,37,12.2L259.6,73.3z"/>
</g>
</svg>
```
And tried the following example 
```python
from manim import *

class example(Scene):
    def construct(self):
        example = SVGMobject("example", stroke_width=0).scale(1.6)
        print(str(example[0].get_fill_color()) + ": From example class.")
```
It outputted following 
 ```
#3cd4a1: From svg_mobject.py at line 87.
white: From example class.
```

**Comment by yoshiask** [comment]
This is one of the behaviors that I'm investigating in #108

**Comment by NavpreetDevpuri** [comment]
Check this https://github.com/3b1b/manim/pull/1071#issuecomment-630563969 there is a lot to do.

**Comment by NavpreetDevpuri** [comment]
@yoshiask I want to say one thing 
"We should somehow use some libraries from the source code of `inkscape`, I am sure they definitely have great SVG parsers, gadling special cases...etc. We just need to use pre-build tools instead of wasting so much time for inventing the same things in manim"

**Comment by leotrs** [comment]
If this is subsumed by #108, can we close this issue then?

**Comment by yoshiask** [comment]
I don't see why not
