### ISSUE TITLE
Document in Chinese

### ISSUE THREAD

**Issue by cauliyang** [ManimCommunity/manim#2497]
## Enhancement proposal

Hi, I know about manim recently and I think that this is a pretty cool project especially you would like to share something with others. 

I notice that there are different languages for documents. Hence, Could we add a Chinese version to the document? 
I hope more people know about this project and use that! 

I can work on this change and submit a pull request. If you think this is an enhancement.

**Comment by naveen521kk** [comment]
Have a look at https://docs.manim.community/en/stable/contributing/internationalization.html
