### ISSUE TITLE
Modifying the font weight or font face after a Text type object is created.

### ISSUE THREAD

**Issue by Ammar34** [ManimCommunity/manim#250]
Hi, I have grown a fondness for the Text class. However, soon I realized that after such an object is created, I could change the color of the object but I was not able to change the font-weight or cant even change the font used. It seems that the constructor for Text object changes these properties and once created cant be modified.  I am a new learner so I am not sure. I want something like the following:
``text` = Text("But what is...",font="Minion Pro")
text.set_font_(font="Berolina").set_weight("bold")
``
Is this possible? I hope I am not asking for too much!

Any help would be much appreciated.

**Comment by leotrs** [comment]
This is a well-known missing feature in some classes in manim. For now, I suggest you try creating two different Text objects, with the same text but different fonts (or weights), and transform one to the other. Would that be a good workaround for your purposes?

**Comment by Ammar34** [comment]
> This is a well-known missing feature in some classes in manim. For now, I suggest you try creating two different Text objects, with the same text but different fonts (or weights) and transform one into the other. Would that be a good workaround for your purposes?

It will have to. Seems like I don't have any choice. But I am going to implement this soon. It's way more convenient to have methods do it than creating two instances. Let's see if someone can beat me to it. I Will let the issue stay open a while.

**Comment by leotrs** [comment]
I believe @XorUnison is working on this.

**Comment by Ammar34** [comment]
> I believe @XorUnison is working on this.

Great!

**Comment by Ammar34** [comment]
Great!

**Comment by XorUnison** [comment]
> I believe @XorUnison is working on this.

Am I...? I'm not really working on text stuff. If you mean the generalized way of applying such stuff like .settattrs (which would apply in this case too) then no, I'm not working on that, I've just discussed the format. I would assume it's also the cfg/attr people who would subsequently work on that. If needed I can look into these things as well, but not until I'm done with #210 at the earliest.

**Comment by Ammar34** [comment]
I have added a custom method to help with handling fonts. I have been doing some testing and so far it works without any issues. I will PR once I am satisfied. Here is an example.

```
class TestingTextClass(Scene):
    def construct(self):
        some_text = Text("This is some text",
                         font = "PWChalk",
                        text_case = "upper",
                        size = 2
                        )
        self.play(DrawBorderThenFill(some_text))
        self.play(some_text.set_font_attributes,{"font": "Minion Pro",
                                                 "text_case":"title"})
![TestingTextClass](https://user-images.githubusercontent.com/12208432/89738410-b29d7c80-da91-11ea-86fa-7dc921a4b7a8.gif)

```

**Comment by leotrs** [comment]
@Ammar34 this looks good to me. Please remember to close this issue when/if your PR is merged.

**Comment by Ammar34** [comment]
Sure thing.
