### ISSUE TITLE
Option to play a sound after animation has finished rendering

### ISSUE THREAD

**Issue by JeroSQ** [ManimCommunity/manim#2506]
## Description of proposed feature
Add a flag that the user can enter when running the manim command to render a scene, which plays a sound (like a chime) once it has finished rendering.

## How can the new feature be used?
Most of the time the scenes I render take some time, and I may go do other things like browsing stuff or leave the computer rendering while I do other irl stuff. In my opinion, it would be useful to have an option to play a sound once the rendering is done (like many video editors allow you to play a sound once exporting has finished).

## Additional comments
This may be regarded as too specific, and isn't 100% necessary, since you can just have a look every couple minutes and check if it has finished.

However, I think this would be very easy to implement. In fact, I think the hard part would be finding a good sound to play xD.

There could even be a different sound if there's an error during rendering.

I'd love to hear your comments.

**Comment by naveen521kk** [comment]
If I remember correctly this feature was one of the first things we removed from the core library when we formed ManimCommunity 😄 .

**Comment by huguesdevimeux** [comment]
For reference, see #511

**Comment by JeroSQ** [comment]
Oh, I see. I'll guess I'll have to make my own implementation 😆
