### ISSUE TITLE
Sphinx Mobject page content 

### ISSUE THREAD

**Issue by kolibril13** [ManimCommunity/manim#253]
I just had a look on the sphinx site docs/build/html/mobject.html, and it looks like this:
![ccc](https://user-images.githubusercontent.com/44469195/89406921-2ea86500-d71e-11ea-9c47-2292c7dde908.png)
This does not look very appealing to me.
Maybe we can find there some simpler way to explain the objects.
e.g. remove the "Bases" link.
A documentation page I find really appealing is the one from sklearn, example: 
https://scikit-learn.org/stable/modules/generated/sklearn.cluster.KMeans.html#sklearn.cluster.KMeans
Maybe we can get inspired by that.

**Comment by leotrs** [comment]
I agree it looks terrible for now. If you have more concrete suggestions, please feel free to leave them here.

Note that #249 will be merged regardless of what the docs look like, as it's just meant to add sphinx scaffolding for others to write documentation. Look&feel will be handled later, and will most likely undergo quite a few tweaks before it's ready.

Lastly: I think the classes that an object inherits from should always be visible, though the current link does look ugly.

**Comment by PgBiel** [comment]
We didn't define the theme yet. There are more themes to explore.
And `Bases` has to be there, it indicates the parent classes.

**Comment by leotrs** [comment]
I think this issue has ran its course. Let me open another one for discussion about the theme.
