### ISSUE TITLE
removing edges from Graph in an animatoin

### ISSUE THREAD

**Issue by vilasopher** [ManimCommunity/manim#2575]
## Description of bug / unexpected behavior

If g is a Graph, calling g.animate.remove_edges(...) does not actually play an animation.
Instead, the edges will all be removed instantaneously.

## How to reproduce the issue

<details><summary>Code for reproducing the problem</summary>

```py
class Test(Scene):
  def construct(self):
    g = Graph([1,2,3], [(1,2), (2,3), (3,1)])
    self.add(g)
    self.wait()
    self.play(g.animate.remove_edges((1,2),(2,3)))
    self.wait()
```

</details>

## Additional comments

I think that the problem has to do with [this line of code](https://github.com/ManimCommunity/manim/blob/63b43ebf82e4a0fcbd79137dae2e27810b21b07e/manim/mobject/graph.py#L999).
It seems like in the animation override method, the original method is called, which removes the edges before creating the animations.

**Comment by behackl** [comment]
The line you mention only removes the edges from the graph, not from the scene. I have identified and fixed the issue via #2576. :-)
