### ISSUE TITLE
set_color(COLOR) (and some other methods mostly used for manipulating the size, position etc. of objects on canvas) dont change the attributes associated with the object.

### ISSUE THREAD

**Issue by Ammar34** [ManimCommunity/manim#258]
I don't know if this is intentional but the setting methods especially those used for manipulating the position/color of objects on manim canvas don't actually change these attributes. For example, here I am trying to change the color of the TextMobject using set_color() but it is not changing the color property associated with the object although its appearance on the canvas has been changed to the desired color. 
```python
class Testing(Scene):
    def construct(self):
        some_text = TextMobject("This is some text")
        print("Color of the variable before applying set_color(): ",some_text.color)
        self.play(Write(some_text))
        self.wait()
        self.remove(some_text)
        some_text.set_color(GREEN_D)
        print("Color of the variable after applying set_color(): ",some_text.color)
        self.play(ShowCreation(some_text))
        self.wait()
```
Here is the output:
![Testing](https://user-images.githubusercontent.com/12208432/89587884-edb66a80-d85b-11ea-832a-cd2366078cde.gif)

![image](https://user-images.githubusercontent.com/12208432/89588659-86011f00-d85d-11ea-8907-c1b47a6b0731.png)

**Comment by Ammar34** [comment]
**UPDATE**
Upon further investigation, the changed color of the object can be retrieved using `object.get_color() ` (Other get methods work fine too). However, the color property of the object still remains unchanged. To fix this, the setters should modify the properties of the object too. I made a small change to the `set_color()` method by adding self.color = color and now it works just as intended.

```
class Testing(Scene):
    def construct(self):
        some_text = TextMobject("This is some text")
        # print("Color of the variable before applying set_color(): ",some_text.color)
        self.play(Write(some_text))
        self.wait()
        self.remove(some_text)
        some_text.set_color(GREEN_D)
        print("Color of the variable using variable.get_color() : ",\
            some_text.get_color())
        print("Color of the variable using variable.color : ",\
            some_text.color)
        self.play(ShowCreation(some_text))
        self.wait()
```
Print statement's output before making the change to `set_color(COLOR)`
![image](https://user-images.githubusercontent.com/12208432/89609260-c332d480-d890-11ea-8545-4c72f1ab7f95.png)
Print statement's output after making the change to `set_color(COLOR)`
![image](https://user-images.githubusercontent.com/12208432/89609403-2cb2e300-d891-11ea-8cab-2dfaf2c1d6aa.png)

**Comment by kilacoda** [comment]
`self.color = color` is already there though? What did you change exactly?

https://github.com/ManimCommunity/manim/blob/70c0d53a01ee6cd1da9a74c0338ed404f67b9123/manim/mobject/mobject.py#L579-L591

**Comment by Ammar34** [comment]
The vectorized M object class has its own `set_color(COLOR)` method defined where the COLOR passed is not set to the color attribute of the object. Looking at the method resolution order, TextMobject looks for the method `set_color(COLOR)` in VMobject.

https://github.com/ManimCommunity/manim/blob/70c0d53a01ee6cd1da9a74c0338ed404f67b9123/manim/mobject/types/vectorized_mobject.py#L227-L230

![image](https://user-images.githubusercontent.com/12208432/89627006-abb91300-d8b3-11ea-97a9-e179ae398569.png)

**Comment by leotrs** [comment]
@Ammar34 would you be interested in opening a PR for this? :)

**Comment by Ammar34** [comment]
> @Ammar34 would you be interested in opening a PR for this? :)

Yes sir. I was a little busy for the past two weeks. I will PR tomorrow if that is okay!

**Comment by yoshiask** [comment]
For the record, I strongly suspect that this issue is one of the big causes of the SVG rendering bugs
