### ISSUE TITLE
Preview without embed broken in jupyter notebooks.

### ISSUE THREAD

**Issue by Kiran-Raj-Dev** [ManimCommunity/manim#2590]
## Description

The embed feature seems to have broken preview in jupyter notebooks.

default:
<img width="1115" alt="Screenshot 2022-03-05 at 3 24 09 PM" src="https://user-images.githubusercontent.com/90276965/156878243-224900ac-8da2-46e5-8ee2-cc9f1852bec8.png">

with media embed:
<img width="1115" alt="Screenshot 2022-03-05 at 3 24 30 PM" src="https://user-images.githubusercontent.com/90276965/156878267-b5d77f95-7953-45e9-b155-baac8f19db35.png">

## Expected Behaviour
Should preview images even without `media_embed`

_Originally posted by @Kiran-Raj-Dev in https://github.com/ManimCommunity/manim/issues/2442#issuecomment-1059732017_

**Comment by behackl** [comment]
Does it work if you specify the `-s` flag for scenes that only render into an image? I know that video output works as expected.

**Comment by Kiran-Raj-Dev** [comment]
This
```py
%%manim -s -qh --disable_caching -v WARNING Example
class Example(Scene):
    def construct(self):
        self.play(Create(NumberPlane()))
```
and this
```py
%%manim -s -qh --disable_caching -v WARNING Example
class Example(Scene):
    def construct(self):
        self.add(NumberPlane())
```
Both don't work

**Comment by behackl** [comment]
I have identified and fixed the issue. PR incoming.
