### ISSUE TITLE
Improve font handling 

### ISSUE THREAD

**Issue by huguesdevimeux** [ManimCommunity/manim#262]
I think that the font selection for `Text` is not optimal. The current way to select a font is with `context.select_font_face` of Cairo.
According to the documentation of this (https://pycairo.readthedocs.io/en/latest/reference/context.html#cairo.Context.select_font_face), it's rudimental and not adapted  to our use : 

> Note: The select_font_face() function call is part of what the cairo designers call the “toy” text API. It is convenient for short demos and simple programs, but it is not expected to be adequate for serious text-using applications.

> It is expected that most applications will need to use a more comprehensive font handling and text layout library, (for example, pango), in conjunction with cairo.

Some ideas would be to : 
- Allow the user to select a custom font file (no idea if this is possible, but it seems logical that it is)
- Get the list of all the fonts available.
- Throw an error if the font does not exist. (It's not possible with `context.select_font_face` : 

> Cairo provides no operation to list available family names on the system

I'm not an expert on all this stuff, so if someone could take a look at this.

**Comment by leotrs** [comment]
Thanks for catching that. I am not an expert in font stuff, but my understanding it's that it's generally tricky.

Seeing that there are people working on deprecating Cairo, I would suggest we either (a) leave this as it is, or (b) look into the `pango` library, which is meant to be used alongside cairo anyways.

@eulertour your thoughts?

**Comment by eulertour** [comment]
I actually don't know anything about this either. The `Text` class was contributed out of nowhere and just worked out of the box, so we'll have to either find that person or come up with a solution on our own.

**Comment by kilacoda** [comment]
`Text` was contributed by @xy-23 afaik, and they seem to be offline for now, so we'll probably have to figure something out ourselves.

**Comment by huguesdevimeux** [comment]
> Seeing that there are people working on deprecating Cairo,

In this case, I am partial to letting it as it is and wait for improvement as `Text` completely uses Cairo.

Btw, is there A branch of this work on deprecating Cairo ? An issue ?

**Comment by leotrs** [comment]
I believe Cairo will be deprecated once we move to OpenGL. I think @eulertour is working on this?

**Comment by leotrs** [comment]
From the discussion above, this seems like a #wontfix.
