### ISSUE TITLE
Add a command line option to merge the srt file and video

### ISSUE THREAD

**Issue by woshichuanqilz** [ManimCommunity/manim#2621]
## Description of proposed feature

If use addcaption function there will be a srt file. Which I think should give a command line option to auto merge the srt file to video.

## How can the new feature be used?

Something like `manim -pql --merge xxx`  or `manim -pqlx xxx`

**Comment by behackl** [comment]
In some sense, this is against the spirit of subcaption files. If you want to render text in your video, why not simply use `Text` or `Tex`?

I'm happy to hear further arguments, and in case there is a striking use case for this feature we can reopen it -- but for now, I'll close this.
