### ISSUE TITLE
proportion_from_point is not working for some cases

### ISSUE THREAD

**Issue by mooncaker816** [ManimCommunity/manim#2627]
## Description of bug / unexpected behavior

Hello, I'm trying to get the proportion of the vertices from a triangle outline, but the result is not correct for some cases.

For easy testing purpose, I tried a regular triangle which is shifted and scaled somehow. 
The result i got was `0, 0.33333333333333337, 16336461.942820664` for the three vertices instead of `0, 0.3333333333333333, 0.6666666666666667`. 
Obviously, the proportion of the third vertex was wrong.

## Expected behavior

In the case mentioned above, i should get `0, 0.3333333333333333, 0.6666666666666667` for each vertex of any regular triangle regardless of whether it's shifted/scaled or not.

## How to reproduce the issue

Here is the code i used for testing the regular triangle case:
<details><summary>Code for reproducing the problem</summary>

## 1. Without shift and scale, the result is ok.
```py
class TestProportion(Scene):
    def construct(self):
        from math import sqrt
        A=sqrt(3)*UP
        B=LEFT
        C=RIGHT
        abc = Polygon(A,B,C)

        for p in abc.get_vertices():
            print(abc.proportion_from_point(p))

================================
output:

0.0
0.3333333333333333
0.6666666666666666
```

## 2. With shift only, the result is ok.
```py
class TestProportion(Scene):
    def construct(self):
        from math import sqrt
        A=sqrt(3)*UP
        B=LEFT
        C=RIGHT
        abc = Polygon(A,B,C)
        abc.shift(LEFT)

        for p in abc.get_vertices():
            print(abc.proportion_from_point(p))

================================
output:

0.0
0.3333333333333333
0.6666666666666666
```

## 3. With scale only, the result is ok.
```py
class TestProportion(Scene):
    def construct(self):
        from math import sqrt
        A=sqrt(3)*UP
        B=LEFT
        C=RIGHT
        abc = Polygon(A,B,C)
        abc.scale(0.8)

        for p in abc.get_vertices():
            print(abc.proportion_from_point(p))

================================
output:

0.0
0.3333333333333333
0.6666666666666666
```

## 4. With shift and scale, the result is NOT ok.
```py
class TestProportion(Scene):
    def construct(self):
        from math import sqrt
        A=sqrt(3)*UP
        B=LEFT
        C=RIGHT
        abc = Polygon(A,B,C)
        abc.shift(LEFT)
        abc.scale(0.8)
        for p in abc.get_vertices():
            print(abc.proportion_from_point(p))

================================
output:

0.0
0.33333333333333337
16336461.942820664
```

</details>

## Additional media files

<details><summary>Images/GIFs</summary>

</details>

## Logs
<details><summary>Terminal output</summary>

```
PASTE HERE OR PROVIDE LINK TO https://pastebin.com/ OR SIMILAR
```

</details>

## System specifications

<details><summary>System Details</summary>

- OS (with version, e.g., Windows 10 v2004 or macOS 10.15 (Catalina)):
- RAM:
- Python version (`python/py/python3 --version`):
- Installed modules (provide output from `pip list`):
```
PASTE HERE
```
</details>

<details><summary>LaTeX details</summary>

+ LaTeX distribution (e.g. TeX Live 2020):
+ Installed LaTeX packages:

</details>

<details><summary>FFMPEG</summary>

Output of `ffmpeg -version`:

```
PASTE HERE
```
</details>

## Additional comments

I found the wrong value '16336461.942820664' was from `proportions_along_bezier_curve_for_point`, it could be caused by the accuracy while finding the roots of the bezier polynomial. 
As per the reference of [Numpy](https://numpy.org/doc/stable/reference/generated/numpy.polynomial.polynomial.Polynomial.roots.html?highlight=roots#numpy.polynomial.polynomial.Polynomial.roots), 
>the accuracy of the roots decrease the further outside the domain they lie.

- Maybe we could do some correction on the coefficient (like we are rounding the roots) before solving the polynomial?
- Or we could bypass all the roots which do not belong to [0,1]. Not sure why this is not checked currently, any reason that i missed?

p.s. The two approaches above are roughly tested on my case and works, but maybe there are better fixes that i'm not aware of.

At last, thanks for the great library, it really helps making math video much more easily.

**Comment by behackl** [comment]
Apologies for the very late reply, and thank you for this very fine report!

> Or we could bypass all the roots which do not belong to [0,1]. Not sure why this is not checked currently, any reason that i missed?

This seems to be like a very simple solution if this really fixes the issue -- do you happen to remember which changes you applied to where exactly, or would you perhaps be willing to contribute a PR with these changes?

**Comment by mooncaker816** [comment]
Sorry for the delay, I'm glad to contribute. PR #2770 is created.
Basically, the change is in `bezier.py`, bypass the calculated root which is out of range [0,1] before returning them, details as below:

```python
def proportions_along_bezier_curve_for_point(
    point: typing.Iterable[float | int],
    control_points: typing.Iterable[typing.Iterable[float | int]],
    round_to: float | int | None = 1e-6,
) -> np.ndarray:
    ...

    roots = [[root for root in rootlist if root.imag == 0] for rootlist in roots]
    roots = reduce(np.intersect1d, roots)  # Get common roots.
    roots = np.array([r.real for r in roots if r.real <= 1 and r.real >= 0])
    return roots
```
Pls kindly review, thanks.
