### ISSUE TITLE
Bug: add_fixed_in_frame_mobjects in ThreeDScene is not working anymore

### ISSUE THREAD

**Issue by kolibril13** [ManimCommunity/manim#264]
When running this:
```python
from manim import *
class Text3D(ThreeDScene):
    def construct(self):
        axes = ThreeDAxes()
        self.set_camera_orientation(phi=75 * DEGREES,theta=-45*DEGREES)
        text=TextMobject("This is a 3D text")
        self.add_fixed_in_frame_mobjects(text)
        self.add(axes)
        self.add(text)
        self.wait()
```
I get the following error:
`AttributeError: 'tuple' object has no attribute 'sort'`
I guess that is related to the z_index implementation, #122 , @PgBiel ?

**Comment by PgBiel** [comment]
1. May you please provide a more complete log, indicating where the error occurred?
2. (Regarding your question) Does replacing `mobjects.sort(...)` (camera.py, somewhere around line 418) by `mobjects = sorted(mobjects, ...)` fix it?

**Comment by kolibril13** [comment]
Yes, it fixes it!
I will make a pull request.
