### ISSUE TITLE
[bug] Line Intersection and Difference not working as expected

### ISSUE THREAD

**Issue by fcrozatier** [ManimCommunity/manim#2647]
It seems we can't make Line Intersection or Difference like with other mobjects

This works
```py
  t = Triangle() 
  s = Square(1)
  d = Difference(t, s, color=YELLOW)
  self.add(d)
```

This does not work
```py
        l1 = Line(LEFT, RIGHT, color=RED)
        l2 = Line(ORIGIN, RIGHT, color=BLUE)
        s = Square(1)

        d1 = Difference(l1, s, color=YELLOW)
        d2 = Difference(l1, l2, color=YELLOW)
        d3 = Intersection(l1, l2, color=YELLOW)
        self.add(d1, d2, d3)
```

Nothing shows up

## Expected behavior
Ability to do line intersection and difference with other mobjects.

**Comment by behackl** [comment]
Difference only works on mobjects which have a fill; lines just consist of a stroke. You'll have to use thin rectangles to achieve the desired effect.

**Comment by fcrozatier** [comment]
Ok that will do it. Thanks !
