### ISSUE TITLE
The -i flag has confusing documentation

### ISSUE THREAD

**Issue by leotrs** [ManimCommunity/manim#267]
Calling manim with the -i flag saves the video as .gif IN ADDITION to also saving it as .mp4. I was expecting it to be saved as .gif INSTEAD of as a .mp4.

The fix would be to have the documentation and the `manim --help` text document this fact.

Also, in the following output, it is specified that the .mp4 file has been saved, but not that the .gif file has been saved:

![2020-08-10-130754_1902x226_scrot](https://user-images.githubusercontent.com/1096704/89810101-86721200-db0a-11ea-960d-b5d7c667bc43.png)

**Comment by huguesdevimeux** [comment]
> The fix would be to have the documentation and the `manim --help` text document this fact.

Mmmmh, why not fixing `-i` instead of its documentation? We could make `-i` save only `.gif`

**Comment by leotrs** [comment]
Either is fine by me, as long as (at least) it's very clear what is happening. Right now the output shown to the user is incomplete
