### ISSUE TITLE
backports-cached-property should be required only with Python<3.8

### ISSUE THREAD

**Issue by MehdiChinoune** [ManimCommunity/manim#2677]

**Comment by MehdiChinoune** [comment]
The only place where It's used is at https://github.com/ManimCommunity/manim/blob/main/manim/renderer/opengl_renderer.py#L8

**Comment by naveen521kk** [comment]
Thank you for the report, having a quick glance it looks like `backports.cached-property` is only required for python 3.8, I'll make a PR soon.

**Comment by MehdiChinoune** [comment]
> Thank you for the report, having a quick glance it looks like `backports.cached-property` is only required for python 3.8, I'll make a PR soon.

only required for python<3.8
