### ISSUE TITLE
Aligning Equations

### ISSUE THREAD

**Issue by George-Ogden** [ManimCommunity/manim#2679]
Hi

This project is great and I've been enjoying using it but there is something I'm stuck on so I hope you can help, please?

I have this equation
`f(x) &= x ^ 2 - 1\\&= x^2 - x + x - 1\\&= x(x - 1) + x - 1\\&= (x - 1)(x + 1)`
And you can see that the equals signs are all aligned. I want to animate each line at a time but I'm not sure how?

Alternatively, I could break it into a series of lines but I'm not sure how to align them.

I know there are lots of experts out there so hopefully, they can share some tips?

Thanks

**Comment by krenem** [comment]
Hello @George-Ogden,

Thank you for reaching out. The best way to help you with your problem would be through [Discord](https://discord.com/invite/bYCyhM9Kz2). 
Just post your problem there and somebody will be happy to help you out.

**Comment by behackl** [comment]
True, people usually are a bit faster to react to questions for concrete examples in our Discord. :-)

I can't check it myself right now, but in theory aligned multi-line equations should work like this:

```
eq = MathTex(r"x &= y + 1\\", r"&= z+2")
self.play(Write(eq[0]))
self.play(Write(eq[1]))
```

**Comment by George-Ogden** [comment]
Thanks - that's great
