### ISSUE TITLE
More accessible way to create Angles

### ISSUE THREAD

**Issue by behackl** [ManimCommunity/manim#2683]
## Description of proposed feature

The current way of creating `Angle` mobjects is somewhat clunky and could be improved. One way of doing so would be the introduction of a new static method `Angle.from_three_points` which takes in three points and creates one of the two possible angles.

## How can the new feature be used?

```py
A = np.array(...)
B = np.array(...)
C = np.array(...)
ang = Angle.from_three_points(A, B, C)
```

## Additional comments

The implementation might look something like this:
```py
@staticmethod
def from_three_points(A, B, C, **kwargs):
            return Angle(Line(B, A), Line(B, C), **kwargs)
```
The choice of end points (A and C) *should* make sure that as long as the `quadrant` is not modified, the correct angle (or its complement) are constructed. Documentation and tests have to be written though.

**Comment by hickmott99** [comment]
I can tackle this with @jbalpert !!!

**Comment by hickmott99** [comment]
Where would this function actually get defined? In the line.py file? @behackl

**Comment by behackl** [comment]
> Where would this function actually get defined? In the line.py file? @behackl

Go ahead! Yes, in `line.py`, as a member of the `Angle` class.

**Comment by hickmott99** [comment]
We have implemented the member function and have wrote a pytest for it. Everything looks good! We are not totally sure where to write documentation for this function though, where are these documentation files located? @behackl
