### ISSUE TITLE
Remove CameraFrame from the `moving_camera` module

### ISSUE THREAD

**Issue by behackl** [ManimCommunity/manim#2689]
## Enhancement proposal

The `CameraFrame` class is broken (`VGroup` does not have a `center` argument as pointed out in https://github.com/ManimCommunity/manim/commit/68e66dccf5b47da7656211aaafdb1acc89c806a0#r71898899) and not used anywhere else. It can be removed.

**Comment by zzzzz1st** [comment]
Hello. I deleted the class on this PR. Could you check that out ? Thank you.
