### ISSUE TITLE
ExpatError: no element found: line 1, column 0

### ISSUE THREAD

**Issue by woolpeeker** [ManimCommunity/manim#2699]
## Description of bug / unexpected behavior
A simple Table example causes error

```py
from manim import *
import numpy as np

class Test(Scene):
    def construct(self):
        data = [
            ['1.6', '-0.6', '-0.5', '-1.1'],
            ['0.9', '-2.3', '1.7', '-0.8'],
            ['0.3', '-0.2', '1.5', '-2.1']
        ]
        t0 = Table(data, include_outer_lines=True)
        self.add(t0)
        self.wait(1)
```

## System specifications

<details><summary>System Details</summary>
- OS Windows 10 21H2 19044.1645  
- RAM: 16G  
- Python version (`python/py/python3 --version`): Python 3.7.4  
- Installed modules (provide output from `pip list`):
```
Package                   Version    
------------------------- ---------  
anyio                     3.4.0  
argcomplete               1.12.3  
argon2-cffi               21.1.0  
asn1crypto                1.2.0  
attrs                     21.2.0  
Babel                     2.9.1  
backcall                  0.2.0  
backports.cached-property 1.0.1  
beautifulsoup4            4.10.0  
bleach                    4.1.0  
certifi                   2019.9.11  
cffi                      1.13.0  
chardet                   3.0.4  
charset-normalizer        2.0.12  
click                     8.1.2  
click-default-group       1.2.2  
cloup                     0.13.0  
colorama                  0.4.4  
colour                    0.1.5  
commonmark                0.9.1  
conda                     4.7.12  
conda-package-handling    1.6.0  
crcmod                    1.7  
cryptography              2.8  
cycler                    0.11.0  
debugpy                   1.5.1  
decorator                 5.1.0  
defusedxml                0.7.1  
entrypoints               0.3  
et-xmlfile                1.1.0  
fonttools                 4.28.2  
glcontext                 2.3.6  
idna                      2.8  
importlib-metadata        4.11.3  
importlib-resources       5.4.0  
ipykernel                 6.6.0  
ipython                   7.29.0  
ipython-genutils          0.2.0  
isosurfaces               0.1.0  
jedi                      0.18.1  
Jinja2                    3.0.3  
json5                     0.9.6      
jsonschema                4.2.1  
jupyter-client            7.1.0  
jupyter-core              4.9.1  
jupyter-server            1.12.1  
jupyterlab                3.2.4  
jupyterlab-pygments       0.1.2  
jupyterlab-server         2.8.2  
kiwisolver                1.3.2  
lxml                      4.6.4  
manim                     0.15.2  
ManimPango                0.4.1  
mapbox-earcut             0.12.11  
MarkupSafe                2.0.1  
matplotlib                3.5.0  
matplotlib-inline         0.1.3  
menuinst                  1.4.16  
mistune                   0.8.4  
moderngl                  5.6.4  
moderngl-window           2.4.1  
multipledispatch          0.6.0  
nbclassic                 0.3.4  
nbclient                  0.5.9  
nbconvert                 6.3.0  
nbformat                  5.1.3  
nest-asyncio              1.5.4  
networkx                  2.6.3  
notebook                  6.4.6  
numpy                     1.21.4  
opencv-python             3.4.10.35  
openpyxl                  3.0.9  
packaging                 21.3  
pandas                    1.3.4  
pandocfilters             1.5.0  
parso                     0.8.2  
pickleshare               0.7.5  
Pillow                    8.4.0  
pip                       19.3.1  
prometheus-client         0.12.0  
prompt-toolkit            3.0.22  
pycairo                   1.21.0     
pycosat                   0.6.3  
pycparser                 2.19  
pydub                     0.25.1  
pyglet                    1.5.23  
Pygments                  2.10.0  
pyOpenSSL                 19.0.0  
pyparsing                 3.0.6  
pyrr                      0.10.3  
pyrsistent                0.18.0  
PySocks                   1.7.1  
python-dateutil           2.8.2  
pytz                      2021.3  
pywin32                   223  
pywinpty                  1.1.6  
pyzmq                     22.3.0  
requests                  2.27.1  
rich                      12.3.0  
ruamel-yaml               0.15.46  
scipy                     1.7.3  
screeninfo                0.8  
Send2Trash                1.8.0  
setuptools                41.4.0  
setuptools-scm            6.3.2  
six                       1.12.0  
skia-pathops              0.7.2  
sniffio                   1.2.0  
soupsieve                 2.3.1  
srt                       3.5.2  
terminado                 0.12.1  
testpath                  0.5.0  
tomli                     1.2.2  
tornado                   6.1  
tqdm                      4.64.0  
traitlets                 5.1.1      
typing-extensions         4.0.1  
urllib3                   1.24.2  
vboxapi                   1.0  
watchdog                  2.1.7  
wcwidth                   0.2.5  
webencodings              0.5.1  
websocket-client          1.2.1  
wheel                     0.33.6  
win-inet-pton             1.1.0  
wincertstore              0.2  
zipp                      3.6.0  
```
</details>

## Logs
<details><summary>Terminal output</summary>Manim Community v0.15.2

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ c:\programs\miniconda3\lib\site-packages\manim\cli\render\commands.py:118 in render              │
│                                                                                                  │
│   115 │   │   for SceneClass in scene_classes_from_file(file):                                   │
│   116 │   │   │   try:                                                                           │
│   117 │   │   │   │   scene = SceneClass()                                                       │
│ ❱ 118 │   │   │   │   scene.render()                                                             │
│   119 │   │   │   except Exception:                                                              │
│   120 │   │   │   │   error_console.print_exception()                                            │
│   121 │   │   │   │   sys.exit(1)                                                                │
│                                                                                                  │
│ c:\programs\miniconda3\lib\site-packages\manim\scene\scene.py:222 in render                      │
│                                                                                                  │
│    219 │   │   """                                                                               │
│    220 │   │   self.setup()                                                                      │
│    221 │   │   try:                                                                              │
│ ❱  222 │   │   │   self.construct()                                                              │
│    223 │   │   except EndSceneEarlyException:                                                    │
│    224 │   │   │   pass                                                                          │
│    225 │   │   except RerunSceneException as e:                                                  │
│                                                                                                  │
│ D:\Projects\phd-thesis\答辩\ppt\res\nmPrune\manim_test.py:11 in construct                        │
│                                                                                                  │
│    8 │   │   │   ['0.9', '-2.3', '1.7', '-0.8'],                                                 │
│    9 │   │   │   ['0.3', '-0.2', '1.5', '-2.1']                                                  │
│   10 │   │   ]                                                                                   │
│ ❱ 11 │   │   t0 = Table(data, include_outer_lines=True)                                          │
│   12 │   │   self.add(t0)                                                                        │
│   13 │   │   self.wait(1)                                                                        │
│                                                                                                  │
│ c:\programs\miniconda3\lib\site-packages\manim\mobject\table.py:237 in __init__                  │
│                                                                                                  │
│    234 │   │   │   │   raise ValueError("Not all rows in table have the same length.")           │
│    235 │   │                                                                                     │
│    236 │   │   super().__init__(**kwargs)                                                        │
│ ❱  237 │   │   mob_table = self._table_to_mob_table(table)                                       │
│    238 │   │   self.elements_without_labels = VGroup(*it.chain(*mob_table))                      │
│    239 │   │   mob_table = self._add_labels(mob_table)                                           │
│    240 │   │   self._organize_mob_table(mob_table)                                               │
│                                                                                                  │
│ c:\programs\miniconda3\lib\site-packages\manim\mobject\table.py:278 in _table_to_mob_table       │
│                                                                                                  │
│    275 │   │   │   │   self.element_to_mobject(item, **self.element_to_mobject_config)           │
│    276 │   │   │   │   for item in row                                                           │
│    277 │   │   │   ]                                                                             │
│ ❱  278 │   │   │   for row in table                                                              │
│    279 │   │   ]                                                                                 │
│    280 │                                                                                         │
│    281 │   def _organize_mob_table(self, table: Iterable[Iterable[VMobject]]) -> VGroup:         │
│                                                                                                  │
│ c:\programs\miniconda3\lib\site-packages\manim\mobject\table.py:278 in <listcomp>                │
│                                                                                                  │
│    275 │   │   │   │   self.element_to_mobject(item, **self.element_to_mobject_config)           │
│    276 │   │   │   │   for item in row                                                           │
│    277 │   │   │   ]                                                                             │
│ ❱  278 │   │   │   for row in table                                                              │
│    279 │   │   ]                                                                                 │
│    280 │                                                                                         │
│    281 │   def _organize_mob_table(self, table: Iterable[Iterable[VMobject]]) -> VGroup:         │
│                                                                                                  │
│ c:\programs\miniconda3\lib\site-packages\manim\mobject\table.py:276 in <listcomp>                │
│                                                                                                  │
│    273 │   │   return [                                                                          │
│    274 │   │   │   [                                                                             │
│    275 │   │   │   │   self.element_to_mobject(item, **self.element_to_mobject_config)           │
│ ❱  276 │   │   │   │   for item in row                                                           │
│    277 │   │   │   ]                                                                             │
│    278 │   │   │   for row in table                                                              │
│    279 │   │   ]                                                                                 │
│                                                                                                  │
│ c:\programs\miniconda3\lib\site-packages\manim\mobject\text\text_mobject.py:153 in __init__      │
│                                                                                                  │
│    150 │   │   super().__init__()                                                                │
│    151 │   │                                                                                     │
│    152 │   │   lines_str = "\n".join(list(text))                                                 │
│ ❱  153 │   │   self.lines_text = Text(lines_str, line_spacing=line_spacing, **config)            │
│    154 │   │   lines_str_list = lines_str.split("\n")                                            │
│    155 │   │   self.chars = self._gen_chars(lines_str_list)                                      │
│    156                                                                                           │
│                                                                                                  │
│ c:\programs\miniconda3\lib\site-packages\manim\mobject\text\text_mobject.py:486 in __init__      │
│                                                                                                  │
│    483 │   │   │   width=width,                                                                  │
│    484 │   │   │   should_center=should_center,                                                  │
│    485 │   │   │   unpack_groups=unpack_groups,                                                  │
│ ❱  486 │   │   │   **kwargs,                                                                     │
│    487 │   │   )                                                                                 │
│    488 │   │   self.text = text                                                                  │
│    489 │   │   if self.disable_ligatures:                                                        │
│                                                                                                  │
│ c:\programs\miniconda3\lib\site-packages\manim\mobject\svg\svg_mobject.py:116 in __init__        │
│                                                                                                  │
│   113 │   │   │   fill_color=fill_color,                                                         │
│   114 │   │   │   stroke_opacity=stroke_opacity,                                                 │
│   115 │   │   │   stroke_color=stroke_color,                                                     │
│ ❱ 116 │   │   │   **kwargs,                                                                      │
│   117 │   │   )                                                                                  │
│   118 │   │   self._move_into_position(width, height)                                            │
│   119                                                                                            │
│                                                                                                  │
│ c:\programs\miniconda3\lib\site-packages\manim\mobject\types\vectorized_mobject.py:116 in        │
│ __init__                                                                                         │
│                                                                                                  │
│    113 │   │   self.shade_in_3d = shade_in_3d                                                    │
│    114 │   │   self.tolerance_for_point_equality = tolerance_for_point_equality                  │
│    115 │   │   self.n_points_per_cubic_curve = n_points_per_cubic_curve                          │
│ ❱  116 │   │   super().__init__(**kwargs)                                                        │
│    117 │   │                                                                                     │
│    118 │   │   if fill_color:                                                                    │
│    119 │   │   │   self.fill_color = fill_color                                                  │
│                                                                                                  │
│ c:\programs\miniconda3\lib\site-packages\manim\mobject\mobject.py:106 in __init__                │
│                                                                                                  │
│    103 │   │   self.color = Color(color) if color else None                                      │
│    104 │   │                                                                                     │
│    105 │   │   self.reset_points()                                                               │
│ ❱  106 │   │   self.generate_points()                                                            │
│    107 │   │   self.init_colors()                                                                │
│    108 │                                                                                         │
│    109 │   @classmethod                                                                          │
│                                                                                                  │
│ c:\programs\miniconda3\lib\site-packages\manim\mobject\svg\svg_mobject.py:156 in generate_points │
│                                                                                                  │
│   153 │   │   the SVGMobject's points from XML tags, populating self.mobjects, and               │
│   154 │   │   any submobjects within self.mobjects.                                              │
│   155 │   │   """                                                                                │
│ ❱ 156 │   │   doc = minidom_parse(self.file_path)                                                │
│   157 │   │   for node in doc.childNodes:                                                        │
│   158 │   │   │   if not isinstance(node, MinidomElement) or node.tagName != "svg":              │
│   159 │   │   │   │   continue                                                                   │
│                                                                                                  │
│ c:\programs\miniconda3\lib\xml\dom\minidom.py:1958 in parse                                      │
│                                                                                                  │
│   1955 │   """Parse a file into a DOM by filename or file object."""                             │
│   1956 │   if parser is None and not bufsize:                                                    │
│   1957 │   │   from xml.dom import expatbuilder                                                  │
│ ❱ 1958 │   │   return expatbuilder.parse(file)                                                   │
│   1959 │   else:                                                                                 │
│   1960 │   │   from xml.dom import pulldom                                                       │
│   1961 │   │   return _do_pulldom_parse(pulldom.parse, (file,),                                  │
│                                                                                                  │
│ c:\programs\miniconda3\lib\xml\dom\expatbuilder.py:911 in parse                                  │
│                                                                                                  │
│   908 │                                                                                          │
│   909 │   if isinstance(file, str):                                                              │
│   910 │   │   with open(file, 'rb') as fp:                                                       │
│ ❱ 911 │   │   │   result = builder.parseFile(fp)                                                 │
│   912 │   else:                                                                                  │
│   913 │   │   result = builder.parseFile(file)                                                   │
│   914 │   return result                                                                          │
│                                                                                                  │
│ c:\programs\miniconda3\lib\xml\dom\expatbuilder.py:211 in parseFile                              │
│                                                                                                  │
│   208 │   │   │   │   if first_buffer and self.document.documentElement:                         │
│   209 │   │   │   │   │   self._setup_subset(buffer)                                             │
│   210 │   │   │   │   first_buffer = False                                                       │
│ ❱ 211 │   │   │   parser.Parse("", True)                                                         │
│   212 │   │   except ParseEscape:                                                                │
│   213 │   │   │   pass                                                                           │
│   214 │   │   doc = self.document                                                                │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ExpatError: no element found: line 1, column 0
</details>

**Comment by zaneduffield** [comment]
Hi, I wasn't able to reproduce this issue.I was using python 3.8.10 and manim v0.15.2.

**Comment by woolpeeker** [comment]
I test the case on another machine and it has no error.
I guess maybe the reason is the environment or that the path has a special character.
