### ISSUE TITLE
Support different arrow tips / annotation options

### ISSUE THREAD

**Issue by leotrs** [ManimCommunity/manim#272]
Currently manim can only build arrows where the tip is a triangle. It would be a nice new feature if the user was able to choose what kind of tip they wanted for their arrows. For example, the image shows all the possible arrow tips available on Google Slides.

![2020-08-12-145737_80x368_scrot](https://user-images.githubusercontent.com/1096704/90056078-4f3b6680-dcac-11ea-87e9-138de9d2ed8f.png)

**Comment by kolibril13** [comment]
Good idea, and should not be too difficult to implement!

**Comment by kolibril13** [comment]
What do you think about these annotation classes:
```python
class AnnotationDot(VMobject):
    def __init__(self,color= BLUE):
        VMobject.__init__(self)
        sourunding_dot = Dot().scale(1.3).set_fill(color=WHITE).set_z_index(-1)
        innerdot = Dot().set_color(color)
        annotation_dot= VGroup(sourunding_dot,innerdot)
        self.add(annotation_dot)

class LabledDot(VMobject):
    def __init__(self, label_string):
        VMobject.__init__(self)
        labled_dot = TexMobject(r"{\large \textcircled{\small %s}} " % label_string)
        self.add(labled_dot)



class ExampleScene(Scene):
    def construct(self):
        sq = Square(fill_color =RED, fill_opacity = 1)
        self.add(sq)
        dot = AnnotationDot()
        dot1 = LabledDot(42)
        dot2 = LabledDot("a")
        dot3 = LabledDot("ii")
        dot4 = LabledDot(r"3")
        dot.next_to(sq, UP)
        dot1.next_to(sq, UL)
        dot2.next_to(sq, UR)
        dot3.next_to(sq, DL)
        dot4.next_to(sq, DR)
        self.add(dot, dot1, dot2,dot3,dot4)
        self.wait(1)
```
![ExampleScene](https://user-images.githubusercontent.com/44469195/91287061-896a3500-e78f-11ea-8d24-15f26ff4e3c4.png)

**Comment by leotrs** [comment]
Those classes look useful to me. However, I'm not seeing how they are related to the original topic of this issue (about arrow tips) :sweat_smile:

**Comment by kolibril13** [comment]
They both have the purpose of annotating something.
Should I make a pull request for AnnotationDot and LabledDot better to geometry.py?
Or do we want to make a new file called annotations.py?
Or something else?

Sorry for misusing this issue a little bit.

I had a little look at the arrow implementation, but this won't be my priority.

**Comment by leotrs** [comment]
Oh ok I see now. Yeah I think these two are better suited as part of `geometry.py`.
