### ISSUE TITLE
Transform: missing documentation of path_arc_centers keyword argument

### ISSUE THREAD

**Issue by chopan050** [ManimCommunity/manim#2724]
## Description of bug / unexpected behavior

The `Transform` constructor accepts a keyword argument, `path_arc_centers`, which is only being used once and this use is not working as intended.

Inspecting `Transform`'s `__init__` code, at line 64, there's the following code:

```python
if self.path_arc_centers is not None:
    self.path_func = path_along_circles(
        path_arc,
        self.path_arc_centers,
        self.path_arc_axis,
    )

self.path_func: Callable | None = path_func
```

As it can be seen, if `self.path_arc_centers` is not None, it is used to construct a path function which is assigned to `self.path_func`. But inmediately after this, `self.path_func` is assigned the `path_func` keyword argument in all cases, overwriting any possibly stored value in `self.path_func`.

Thus, this `path_arc_centers` keyword argument is not working as intended, and as mentioned before, it's not being used anywhere else inside `Transform`'s definition.

**Comment by behackl** [comment]
Contrary to what I thought before (and also contrary to any sort of reasonable coding practice), this is actually wrong. When we discussed this earlier, I missed that `path_func` is actually a property whose setter checks whether the value that is being assigned is `None` (and if so, the actual function is not changed).

So actually, if `path_arc_centers` is passed, a "proper" `path_func` is constructed and assigned (which the setter also does properly, as not-`None` is passed), then `self.path_func = None` is run and the setter actually *does not* change the value of the internal attribute.

Which means that this is not a bug, but just something that needs to be documented better (and I actually also think that changing the two blocks would not hurt either). I actually played around with the `path_arc_centers` argument briefly, but I'm still not entirely sure how exactly it should be used.
