### ISSUE TITLE
VMobject  get_end_anchors Wrong Documentation 

### ISSUE THREAD

**Issue by MrDiver** [ManimCommunity/manim#2733]
## Description of bug / unexpected behavior

I think the documentation [`vm.get_end_anchors()`](https://docs.manim.community/en/stable/reference/manim.mobject.types.vectorized_mobject.VMobject.html#manim.mobject.types.vectorized_mobject.VMobject.get_end_anchors) is wrong because it is a copy of `vm.get_start_anchor()`

## Expected behavior

Should probably be changed to "end" instead of start in the documentation comment

**Comment by behackl** [comment]
The documented return type is also debatable; I guess that it should be `List[np.ndarray]` or `Iterable[np.ndarray]`, but I wouldn't bet that it is just a `np.ndarray`.
