### ISSUE TITLE
TransformMatchingAbstractBase leaks transparent mobjects into scene

### ISSUE THREAD

**Issue by AndrewYY** [ManimCommunity/manim#2763]
## Description of bug / unexpected behavior
when there are unmatched targets in `TransformMatchingAbstractBase`, it appends a `FadeIn` on `fade_target.copy()`. This gets added to the scene as part of the `AnimationGroup.group` during `Scene.add_mobjects_from_animations` because `TransformMatchingAbstractBase` is not an introducer.

This bug seems to be hidden by the call to `anim.interpolate(0)` during `clean_up_from_scene`, which resets the source mobject, but also hides the copied `fade_target`s. This code hasn't changed since it was introduced in #1037

## Expected behavior
Things seem to work fine by just calling `FadeIn` on `fade_target` instead of a copy. This doesn't leak transparent mobjects into the scene, at the very least.

## How to reproduce the issue

<details><summary>Code for reproducing the problem</summary>

```py
import manim as m

class MainScene(m.Scene):
    def construct(self):
        square = m.Square()
        circle = m.Circle()
        self.add(square)
        self.play(m.TransformMatchingShapes(square, circle))
        assert len(self.mobjects) == 1, len(self.mobjects)
```

</details>

## Logs
<details><summary>Terminal output</summary>

```
Manim Community v0.15.2

[06/12/22 21:15:55] INFO     Animation 0 : Partial movie file written in '[REDACTED]\reproducer\480p15\partial_movie_files\MainScene\3163782288_2194214193_2358810818.mp4' scene_file_writer.py:504
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ C:\Python39\lib\site-packages\manim\cli\render\commands.py:118 in render                         │
│                                                                                                  │
│   115 │   │   for SceneClass in scene_classes_from_file(file):                                   │
│   116 │   │   │   try:                                                                           │
│   117 │   │   │   │   scene = SceneClass()                                                       │
│ ❱ 118 │   │   │   │   scene.render()                                                             │
│   119 │   │   │   except Exception:                                                              │
│   120 │   │   │   │   error_console.print_exception()                                            │
│   121 │   │   │   │   sys.exit(1)                                                                │
│                                                                                                  │
│ C:\Python39\lib\site-packages\manim\scene\scene.py:222 in render                                 │
│                                                                                                  │
│    219 │   │   """                                                                               │
│    220 │   │   self.setup()                                                                      │
│    221 │   │   try:                                                                              │
│ ❱  222 │   │   │   self.construct()                                                              │
│    223 │   │   except EndSceneEarlyException:                                                    │
│    224 │   │   │   pass                                                                          │
│    225 │   │   except RerunSceneException as e:                                                  │
│                                                                                                  │
│ [REDACTED]\reproducer.py:9 in construct                                                          │
│                                                                                                  │
│   6 │   │   circle = m.Circle()                                                                  │
│   7 │   │   self.add(square)                                                                     │
│   8 │   │   self.play(m.TransformMatchingShapes(square, circle))                                 │
│ ❱ 9 │   │   assert len(self.mobjects) == 1, len(self.mobjects)                                   │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
AssertionError: 2
```

</details>

## System specifications

<details><summary>System Details</summary>

- OS: Windows 10 10.0.19043 Build 19043
- Python version: Python 3.9.5
- Installed modules:
```
manim                          0.15.2
...
```
</details>

**Comment by Swiddis** [comment]
The problem with calling `FadeIn` on the raw `fade_target` is that this causes the target mobject to disappear after the animation.

I did some poking around to see if I could figure out why this was the case and came up blank. I also couldn't persuade the program to give correct behavior through various tweaks in what exactly is copied and removed. The extra object is a `VGroup[VGroup[Circle]]`, and I can't figure out what the ghost `Circle` is or where it comes from.

Here's the base script I've been using for experimentation:
```py
import manim as m

class MainScene(m.Scene):
    def construct(self):
        square = m.Square()
        circle = m.Circle()
        self.add(square)
        self.play(m.TransformMatchingShapes(square, circle))
        # Should have one Circle Mobject
        assert len(self.mobjects) == 1, len(self.mobjects)
        # Should see circle while waiting
        self.wait(0.5)
        # Should see the one circle shift with no duplication after shift
        self.play(circle.animate.shift(m.DOWN))
```

**Comment by AndrewYY** [comment]
@Swiddis the target disappears because of the call to `anim.interpolate(0)` during `clean_up_from_scene`. To patch this behaviour, I have `clean_up_from_scene` skip the `anim.interpolate` call on any instance of `FadeIn`
```python
    for anim in self.animations:
        if not isinstance(anim, m.FadeIn):
            anim.interpolate(0)
    scene.remove(*self.mobject.get_family())
    scene.remove(*self.to_remove.get_family())
    scene.add(self.to_add)
```
the `interpolate(0)` is necessary to ensure that the source mobjects of the transformation go back to being what they used to be, but `fade_target` is not a source mobject.

Another potential solution is to just delete any target mobjects of `m.FadeIn` instances in `self.animations`, and keeping `fade_target` as a copy. That would probably be safer for preserving existing behaviour, but I'm not sure.

**Comment by Swiddis** [comment]
@AndrewYY that fix looks good to me, it passes all the tests and I can't figure out any genuine uses for the transparent object if it stays. I agree that it seems fragile but I don't think it's a big deal at the moment. We should just get it under test so that it doesn't get broken in the future.

Tonight I'll see if I can write up unit tests corresponding to the three annotations in my last comment's code, if it goes well I can have a PR for this done tonight or tomorrow.
