### ISSUE TITLE
Color Gradient does not work in certain cases

### ISSUE THREAD

**Issue by StarfuryT** [ManimCommunity/manim#2764]
I'm making a plot that has quite a few color gradient lines in it, and I've discovered that gradients don't work as I would expect them to. Here is some simple code.

```py
%%manim -qm -v WARNING -s --disable_caching DrawLine

class DrawLine(Scene):
  def construct(self):
    angles = np.arange(0,360,15)
    for theta in angles:
      add_line = Line(start=[0,0,0], end = [6*np.cos(np.pi*theta/180),5*np.sin(np.pi*theta/180), 0], stroke_width=4)
      add_line.set_color_by_gradient([RED, GREEN])
      self.add(add_line)

    self.wait()
```

What I would have expected is gradients going from red to green going radially outward (note, i know there is radial gradient, I need to be able to do any arbitrary set of lines with varied coordinates, not necessarily radial)

Instead I got this:
![Screen Shot 2022-06-12 at 3 21 12 PM](https://user-images.githubusercontent.com/34049715/173249801-88527b6d-252a-4076-bda7-2d9e9e02f392.png)

**Comment by behackl** [comment]
This is not a bug; the behavior is caused by the `sheen_direction` being fixed as `UL`, i.e., `[1, -1, 0]`. If you want the direction of the linear gradient to change with the orientation of the line, you'll have to set the sheen direction accordingly: 

```py
from manim import *
import numpy as np

class DrawLine(Scene):
  def construct(self):
    angles = np.arange(0,360,15)
    for theta in angles:
      end_point = np.array([6*np.cos(np.pi*theta/180),5*np.sin(np.pi*theta/180), 0])
      add_line = Line(
          start=[0,0,0],
          end=end_point,
          stroke_width=4,
          sheen_direction=end_point / np.linalg.norm(end_point)
      )
      add_line.set_color_by_gradient([RED, GREEN])
      self.add(add_line)

    self.wait()
```

**Comment by StarfuryT** [comment]
brilliant, thank you
