### ISSUE TITLE
CLI: `manim init scene` FileNotFoundError and strange filename handling

### ISSUE THREAD

**Issue by Phosphorescentt** [ManimCommunity/manim#2869]
## Description of bug / unexpected behavior
 - Currently running `manim init scene` from a directory that doesn't have a `main.py` raises a `FileNotFoundError` even if attempting to insert the new scene into a file that does already exist.
 - Furthermore, the same two lines of code prevent users from creating new scenes from outside a directory containing a `main.py`. Adding an empty `main.py` to any directory allows the user to add scenes.

The two lines of code that affect these issues can be found [here](https://github.com/ManimCommunity/manim/blob/9a0cac7587ac80a6c060a4de8af49e6414b95d49/manim/cli/init/commands.py#L152) (lines 152-153).

 - Finally, if providing a filename for an already existing file, it appends `.py` to the filename regardless of whether a `.py` is present already and edits the file corresponding to the appended filename instead. For example: running `manim init scene new_scene scenes.py` will create a new file called `scenes.py.py` and place the boilerplate for `new_scene` in `scenes.py.py`. This the code causing this issue can be found [here](https://github.com/ManimCommunity/manim/blob/9a0cac7587ac80a6c060a4de8af49e6414b95d49/manim/cli/init/commands.py#L166) (lines 166-175)

**Comment by behackl** [comment]
Fixed via #2870
