### ISSUE TITLE
Don't show the config files every time

### ISSUE THREAD

**Issue by leotrs** [ManimCommunity/manim#287]
Currently, the first thing that manim outputs is the line "Configuration files read: [list here]". I find it a bit obnoxious, especially when rapid iterating on a scene, as this message is repeated over and over and over. Further, the paths shown are absolute paths so they take up a bit of space in the console screen. Not only that, but the first two paths will almost always be the same (library-wide and user-wide files), so this output is not super informative most of the time.

I suggest we keep that log line on a DEBUG level only. Thoughts?

**Comment by Aathish04** [comment]
> I suggest we keep that log line on a DEBUG level only. Thoughts?

Uhhh, noob question: How do we change the log level ( whether we want to see debug messages or not)?

I tried editing the `log_level` entry in `manim.cfg`, but no value I set ever worked.

**Comment by leotrs** [comment]
I think right now everything is being printed at the INFO level, so using either DEBUG or INFO would output the same thing. Using ERROR should not print anything. Is this not the case?

**Comment by Aathish04** [comment]
Well, setting `log_level = DEBUG`, `log_level = INFO`, `log_level = ERROR`, all result in the same error:

`It seems your colour configuration couldn't be parsed. Loading the default color configuration...`

**Comment by leotrs** [comment]
Ugh I think this is related to [this comment](https://github.com/ManimCommunity/manim/pull/218#issuecomment-664007015). Try using the `verbose` flag instead?

**Comment by kilacoda** [comment]
Shouldn't it just be a matter of changing a `logger.log` call to a `logger.debug` one?

**Comment by Aathish04** [comment]
> Shouldn't it just be a matter of changing a `logger.log` call to a `logger.debug` one?

No, _that_ works.

I wanted to know how I could also see those debug level messages if I wanted to.

**Comment by kilacoda** [comment]
Hmm.. maybe try `logging.DEBUG` instead of `DEBUG`?

**Comment by Aathish04** [comment]
> Hmm.. maybe try `logging.DEBUG` instead of `DEBUG`?

Nope, that also results in a `It seems your colour configuration couldn't be parsed. Loading the default color configuration...`

**Comment by Aathish04** [comment]
> Ugh I think this is related to [this comment](https://github.com/ManimCommunity/manim/pull/218#issuecomment-664007015). Try using the `verbose` flag instead?

Oookay, so setting `verbose = DEBUG` works and allows `logger.debug` messages to come through.

This was _really_ confusing to work out though; what exactly impacted what. End user might expect changing `log_level` to change, y'know, the log level, not knowing that `verbose` changes it.
This should, at the very least, be documented somewhere.

Also, what does `log_level` actually impact? I tried changing it to numbers, to strings like "VERBOSE", or "DEBUG" etc. It only seems to accept `rich` styles, but setting it to a rich style changes virtually _nothing_. What does it do? Does it even need to be there? Mentioning @naveen521kk since he PR'd the logger's config section.

**Comment by leotrs** [comment]
@Aathish04 so we can solve the title of the issue by using `logger.debug` instead of `logging.info`, and `--verbose` is the flag that allows you to see debug messages, yes?

**Comment by Aathish04** [comment]
> @Aathish04 so we can solve the title of the issue by using `logger.debug` instead of `logging.info`, and `--verbose` is the flag that allows you to see debug messages, yes?

Yup, and verbosity can be set from CFG files as well, so I can have it always be on debug, so I'm happy.

PR on this in an hour or so.

**Comment by naveen521kk** [comment]
@Aathish04  On seeing 

https://github.com/willmcgugan/rich/blob/master/rich/_log_render.py#L44-L45 

I could see log_level is for  highlighting the word `DEBUG` or `ERROR` which is shown in second column of logs.

**Comment by Aathish04** [comment]
> @Aathish04 On seeing
> 
> https://github.com/willmcgugan/rich/blob/master/rich/_log_render.py#L44-L45
> 
> I could see log_level is for highlighting the word `DEBUG` or `ERROR` which is shown in second column of logs.

@naveen521kk It seems that changing the entry (at least for me), to some other colour doesn't accomplish anything:

![image](https://user-images.githubusercontent.com/33193764/90307560-ee529f00-def4-11ea-900a-0cbaf96d4c86.png)

You can see that even though I have set it to `red`, the level information is still a dim purple.
