### ISSUE TITLE
Minimum required Pillow version has to be increased

### ISSUE THREAD

**Issue by behackl** [ManimCommunity/manim#2875]
As a byproduct of #2715 the minimum required version of `Pillow` has been increased to 9.1 (I believe). This should be reflected in our project dependencies.

https://github.com/ManimCommunity/manim/blob/7870407fdc6a5f7ced50623df8482f5a59e556d8/pyproject.toml#L34

**Comment by naveen521kk** [comment]
should we do a post-release, ie `v0.16.0.post0`, with this change because this could break for a lot of people?

**Comment by behackl** [comment]
> should we do a post-release, ie `v0.16.0.post0`, with this change because this could break for a lot of people?

I am strongly considering it given the few reports we already had. I'd probably just directly commit the fix to main and create a new release, no formatted changelog or anything.

**Comment by naveen521kk** [comment]
> I am strongly considering it given the few reports we already had. I'd probably just directly commit the fix to main and create a new release, no formatted changelog or anything.

I've some free time now, I'll just do that.
