### ISSUE TITLE
Specification of `tex_template` via CLI and config broken

### ISSUE THREAD

**Issue by sudgy** [ManimCommunity/manim#2880]
Starting in 0.16, it seems that most ways of using tex templates has stopped working.  To reproduce, use this "scene":
```python
class Test(Scene):
    def construct(self):
        t = MathTex("\\bm t")
```
with this template:
```latex
\documentclass[preview]{standalone}

\usepackage{amsmath}
\usepackage{bm}

\begin{document}

YourTextHere

\end{document}
```

When using a config file or the command line argument `--tex_template`, this works on 0.15 but not on 0.16.  It still works correctly if you manually specify the tex template to the constructor of `MathTex`.

**Comment by behackl** [comment]
Thanks for the report! Just to clarify: neither setting it in a local config file, nor passing the `--tex_template` flag via the command line interface works correctly?

As a workaround you could run `MathTex.set_default(tex_template=your_template)`. I'll try to investigate this, sorry for the inconvenience.

**Comment by sudgy** [comment]
> Thanks for the report! Just to clarify: neither setting it in a local config file, nor passing the `--tex_template` flag via the command line interface works correctly?

Yes, that's correct.

**Comment by behackl** [comment]
I think I might have a solution for this; some changes are proposed in #2888. Work in progress (but feel free to test and see whether it solves your problem).
