### ISSUE TITLE
Chapters for the docs

### ISSUE THREAD

**Issue by kolibril13** [ManimCommunity/manim#290]
At the moment we have in the docs the chapters:
> * quickstart
>* tutorial
>* configuration
>* reference
> * changelog

What do you think about changing them to

* Installation
* Documentation
* Examples
* Tutorials
* Contributing
(I got this ordering from the matplotlib docs.)

**Comment by leotrs** [comment]
I suggest:

- Installation
  - Windows
  - Linux
  - Mac OSX
  - Troubleshooting
- Tutorials
  - Getting Started (or Quickstart)
  - _more in-depth tutorials_
- ~~Documentation~~Reference
  - _one page per module_
- Examples
- Contributing

**Comment by kolibril13** [comment]
As a reference:
![4](https://user-images.githubusercontent.com/44469195/90308404-93627d00-dedf-11ea-9154-4320846ad391.png)
# **
![3](https://user-images.githubusercontent.com/44469195/90308405-93fb1380-dedf-11ea-8225-89eb0dae4e71.png)
# **
![2](https://user-images.githubusercontent.com/44469195/90308406-9493aa00-dedf-11ea-8154-d0c9bcbd986d.png)
# **
![1](https://user-images.githubusercontent.com/44469195/90308407-9493aa00-dedf-11ea-836a-e3e6c35ff85b.png)

**Comment by alphonse55** [comment]
I like matplotlibs order:

- Installation
- Documentation
- Examples
- Tutorials
- Contributing

**Comment by leotrs** [comment]
Note: we are forgetting the changelog chapter. It's not necessary to put it up front at the same level as the others, but we must provide a file with a changelog. Where should we put it? Perhaps under the installation part? We can have an installation page for each platform, as well as a "Downloads" section that says "download the latest version of manim", and "here is the changelog". All of this may go in the installation index for now.

**Comment by kolibril13** [comment]
Sorry for deleting this file.
It does not feel right for me to include this to the Installation section.
Can we maybe manually add it to the reference chapter?
Or provide a link for it in the reference index page?
eg:

# Reference

This reference manual details functions, modules, and objects included in Manim, describing what they are and what they do. For learning how to use Manim, see the quickstart and tutorial documents.  Want to see whats new? Here is the [changelog](link)

**Comment by leotrs** [comment]
@kolibril13 I like your suggestion! Let's do that

**Comment by kolibril13** [comment]
Is now implemented in #297 . 
Closed.
