### ISSUE TITLE
`OpenGLSurface` rendered on top of `ThreeDAxis`

### ISSUE THREAD

**Issue by alembcke** [ManimCommunity/manim#2908]
## Description of bug / unexpected behavior

When creating `ThreeDAxes` and adding a surface using the OpenGL renderer, the surface is rendered on top of the axes.  This does not happen when using the Cairo renderer.

## Expected behavior

Surface objects should not be rendered over the axes when plotting 

## How to reproduce the issue

<details><summary>Code for reproducing the problem</summary>

```py
from manim import *
import numpy as np


class Test(ThreeDScene):
    def construct(self):
        self.set_camera_orientation(phi=75 * DEGREES, theta=-20 * DEGREES)

        axes = ThreeDAxes(                                                
                x_range=[0, 3, 1],
                y_range=[0, 3, 1],
                z_range=[-1, 1, 1] 
            )                  

        def func(x, y):
            return np.cos(x) * np.sin(y)

        surface = axes.plot_surface(    
            function=func,          
            u_range = (0, 3),       
            v_range = (0, 3),                                
            colorscale = ['#482173', '#2e6f8e', '#29af7f', '#bddf26']
        )                                                            

        self.add(axes, surface)
```

</details>

## Additional media files

<details><summary>OpenGL Output:</summary>

![Test_ManimCE_v0 16 0 post0](https://user-images.githubusercontent.com/79891353/182047055-ec41f10d-c79e-4c58-8a25-6c9f91898497.png)

</details>

<details><summary>Cairo Output:</summary>

![Test_ManimCE_v0 16 0 post0](https://user-images.githubusercontent.com/79891353/182047565-6965024d-cac6-433f-88f8-2a2b1f7545e4.png)

</details>

It might be difficult to see due to the light reflecting off the surface, but the `ThreeDAxes` is in front of the surface for the Cairo output, but is half-covered for the OpenGL output even though that is the z-axis at the origin and the function doesn't cross the origin.

## Logs
<details><summary>Terminal output</summary>

```
PASTE HERE OR PROVIDE LINK TO https://pastebin.com/ OR SIMILAR
```

</details>

## System specifications

<details><summary>System Details</summary>

- OS (with version, e.g., Windows 10 v2004 or macOS 10.15 (Catalina)):
- RAM:
- Python version (`python/py/python3 --version`):
- Installed modules (provide output from `pip list`):
```
PASTE HERE
```
</details>

<details><summary>LaTeX details</summary>

+ LaTeX distribution (e.g. TeX Live 2020):
+ Installed LaTeX packages:

</details>

<details><summary>FFMPEG</summary>

Output of `ffmpeg -version`:

```
PASTE HERE
```
</details>

**Comment by rgreen32** [comment]
This appears to be in issue of depth_test being set to False on the opengl context. Specifically, the in ShaderWrappers for OpenGLVMobject are not being set properly.

When I manually set the depth_test values, I get the expected visual.
```python
   # For shaders
    def init_shader_data(self):
        self.fill_data = np.zeros(0, dtype=self.fill_dtype)
        self.stroke_data = np.zeros(0, dtype=self.stroke_dtype)
        self.fill_shader_wrapper = ShaderWrapper(
            vert_data=self.fill_data,
            depth_test=True,
            vert_indices=np.zeros(0, dtype="i4"),
            shader_folder=self.fill_shader_folder,
            render_primitive=self.render_primitive,
        )
        self.stroke_shader_wrapper = ShaderWrapper(
            vert_data=self.stroke_data,
            depth_test=True,
            shader_folder=self.stroke_shader_folder,
            render_primitive=self.render_primitive,
        )
```


| depth_test = False     | depth_test = True|
| ----------- | ----------- |
| ![Alt Text](https://media.giphy.com/media/wAQYmR1pZbvdz1iQi0/giphy.gif)      | ![Alt Text](https://media.giphy.com/media/PoAVBlIVcPCFKCRPKb/giphy.gif)       |

**Comment by alembcke** [comment]
I see the difference when calling with `depth_test = True`, but `OpenGLSurface` is an `OpenGLMobject`, not an `OpenGLVMobject`.  Also, `OpenGLSurface` calls the parent class `__init__()` with `depth_test = True`, so that should be flowing from `OpenGLSurface` to `OpenGLMobject` to the shader.  So I don't see how `OpenGLSurface` could be getting called with anything other than `depth_test = True`, do you?

**Comment by rgreen32** [comment]
@alembcke You are correct, OpenGLSurface  is an OpenGLMobject but ThreeDAxes is an OpenGLVMobject.

**Comment by alembcke** [comment]
@rgreen32 ah, I see!  And `OpenGLVMobject` doesn't set `depth_test` at all by default.  So to fix this there should be some logic within `OpenGLVMobject` to set `depth_test` - perhaps something that checks if the scene is 3D or 2D and set as appropriate.  Or is there a better solution?

**Comment by behackl** [comment]
Completed via #3106.
