### ISSUE TITLE
All classes should implement copy() as deepcopy

### ISSUE THREAD

**Issue by leotrs** [ManimCommunity/manim#294]
There are 6 classes that define a `copy` method:
- `geometry.Arrow`
- `brace.BraceLabel`
- `probability.BarChart`
- `mobject.Mobject`
- `image_mobject.AbstractImageMobject`
- `animation.Animation`

Of those, the only non-trivial definitions are `Mobject` and `BraceLabel`. All the others just return `deepcopy(self)`. 

This is a bit disorganized, and raises all kind of questions for developers: When does a class implement `copy`? Why or why not? When is `copy` just a renaming of deepcopy? Is this overriding a definition of a parent class? Etc.

Note also that all of these classes except for `Animation` are classes that inherit from `Mobject`. So the situation is that `Mobject` has a non-trivial definition of `copy`, and all of the others are just overriding that with `deepcopy(self)`. This is a sign of bad design, as usually you want the definitions of methods in base classes to be as general as possible. In this case, we have it the other way around. (In fact, the definition of `Arrow.copy` contains the following comment: `# TODO, should this be the default for everything?`)

I suggest we do either one of the following:
1. Define `Mobject.copy` as just `return deepcopy(self)`. In this case, none of the classes that inherit from `Mobject` would need to define `copy` again. I think this is the easiest solution, but I don't have enough familiarity with `Mobject`to determine if this change is safe.
2. Instead of having `Mobject` have a less-general definition and a bunch of its inherited classes have more-general definitions, just create a global function `manim.copy` that calls `deepcopy(mobject)` unless the object has a more especial defiinition.

@eulertour do you think (1) is possible? This would be by far the best solution.

**Comment by eulertour** [comment]
Solution 1 SGTM, I think this was just an instance of bad design early on.
