### ISSUE TITLE
SVG support as a fill pattern.

### ISSUE THREAD

**Issue by sugoidesune** [ManimCommunity/manim#2944]
## Description of proposed feature
Being able to use SVGs as fill patterns example:
![image](https://user-images.githubusercontent.com/20317691/189082288-c9a65db6-a580-447a-a1fa-925a88c20b54.png)
![image](https://user-images.githubusercontent.com/20317691/189089302-707e19f7-8eef-4aa1-9962-17c361237f8e.png)

## How can the new feature be used?
Being able to define a SVG file or an SVGMobject as fill pattern, which would have the ebenefit of being able to change svg colors.

**Comment by behackl** [comment]
Closing this issue here, we are tracking all SVG feature requests in #3709 now.
