### ISSUE TITLE
AttributeError: SVGMobject object has no attribute 'file_path'

### ISSUE THREAD

**Issue by yihuibest** [ManimCommunity/manim#2945]
When running the SVGMobject Example code in the manual, I always get an error: SVGMobject object has no attribute 'file_path'.

Manim version: Manim Community v0.16.0.post0

There seems to be no problem with the old version, is it a bug in the new version?

**Comment by sugoidesune** [comment]
Works for me. Any code you can share?

Do you do it like this?
`SVGMobject("svgfile.svg")`

**Comment by yihuibest** [comment]
@sugoidesune 
Thanks! It is possible to write a full pathname, for example: "SVGMobject (". / assets / svg_file. svg ")" But it can't be written like this: "SVGMobject (" svg_file. svg ")".

**Comment by behackl** [comment]
Can't really reproduce anymore, has perhaps been fixed since. We'll look into it more if it is reported again.
