### ISSUE TITLE
Color bar with colormap gradient

### ISSUE THREAD

**Issue by anbarief** [ManimCommunity/manim#2951]
How to add a bar with color gradient equivalent with Matlab's colorbar that shows up when we plot a surface in Matlab?

Like the image below, but vertically.  No associated surface plot needed.

![20220915_192903](https://user-images.githubusercontent.com/35247692/190403764-1ea1268d-37c6-4fc6-81bc-4ea9705416e0.jpg)

**Comment by alembcke** [comment]
You can do this using the Cairo renderer by passing in a list of colors in `colorscale`, like this:

```py
from manim import *
import numpy as np


class Test(ThreeDScene):
    def construct(self):
        resolution_fa = 42
        self.set_camera_orientation(phi=75 * DEGREES, theta=-60 * DEGREES)

        axes = ThreeDAxes(
                x_range=(-3, 3, 1),
                y_range=(-3, 3, 1),
                z_range=(-5, 5, 1)
                )

        def param_trig(u, v):
            x = u
            y = v
            z = 2 * np.sin(x) + 2 * np.cos(y)
            return z

        trig_plane = axes.plot_surface(
            param_trig,
            resolution=(resolution_fa, resolution_fa),
            u_range = (-3, 3),
            v_range = (-3, 3),
            colorscale = [BLUE, GREEN, YELLOW, ORANGE, RED],
        )

        self.add(axes, trig_plane)
```

![Test_ManimCE_v0 17 2](https://user-images.githubusercontent.com/79891353/211107800-4b8be4e5-6181-4983-a02a-ba9224df9514.png)

Just change the list of colors to match the colorscale you want.

This can also be done using the OpenGL renderer, but there is a bug.  In fact, I found this issue by searching to see if someone else logged the OpenGL bug yet.  The short explanation is that doing this in OpenGL works as long as you don't rotate or move the surface.

**Comment by alembcke** [comment]
Opened issue #3115 regarding the issues with surface `colorscale` in OpenGL.

Rereading your question, you just want the bar, not the surface.  In that case you could just create a rectangular surface using `colorscale` and not show the axes.  Does that work?

**Comment by behackl** [comment]
There is no issue here.
