### ISSUE TITLE
Installation error with clang in Mac M1

### ISSUE THREAD

**Issue by developemmanuel** [ManimCommunity/manim#2986]
#### Preliminaries

- [x] I have followed the latest version of the
      [installation instructions](https://docs.manim.community/en/stable/installation.html).
- [x] I have checked the [troubleshooting page](https://docs.manim.community/en/stable/installation/troubleshooting.html) and my problem is either not mentioned there,
      or the solution given there does not help.

## Description of error
The error shows me a error because of manimpango, I've installed as in [Manim Community](https://docs.manim.community/en/stable/installation/macos.html) Documentation, with all the dependencies and so on. But the problem comes once I run the command `brew install manim`.

## Installation logs

```
> pip3 install manim
clang: error: no such file or directory: 'manimpango/cmanimpango.c'
clang: error: no input files
error: command '/usr/bin/clang' failed with exit code 1
note: This error originates from a subprocess, and is likely not a problem with pip.
 
ERROR: Failed building wheel for manimpango
Failed to build manimpango
ERROR: Could not build wheels for manimpango, which is required to install pyproject.toml-based projects
```

## System specifications

```bash
# OS
macOS Monterey
# RAM
8 GB
# Python version
> python3 --version
Python 3.10.7
```

**FFMPEG**

Output of `ffmpeg -version`:

```
ffmpeg version 5.1.2 Copyright (c) 2000-2022 the FFmpeg developers
built with Apple clang version 14.0.0 (clang-1400.0.29.102)
```

## Additional comments
My `clang` output:
```
> clang --version
Apple clang version 14.0.0 (clang-1400.0.29.102)
Target: arm64-apple-darwin21.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**Comment by behackl** [comment]
Seems like your system is trying to build manimpango locally, in this case you need the build dependencies [mentioned here](https://github.com/ManimCommunity/ManimPango) -- in particular, run `pip3 install Cython` before trying to run `pip3 install manimpango` again.

**Comment by developemmanuel** [comment]
Yep it work, thanks. I suggest that this should be set in the community documentation as a comment
