### ISSUE TITLE
Automatically deleting a branch after merge

### ISSUE THREAD

**Issue by leotrs** [ManimCommunity/manim#30]
For the purpose of having as clean a repository as possible, I suggest we have github [delete branches that have been merged](https://help.github.com/en/github/administering-a-repository/managing-the-automatic-deletion-of-branches). 

It's not clear to me whether this will upend anybody's workflow, so I'm posting here for discussion before making the change. I'll leave this up for a couple/few days, and if I don't hear any objections I'll make the change. If there are objections, we can use this issue to reach consensus.

**Comment by yoshiask** [comment]
There should be a check mark on GitHub to delete the branch on merge

**Comment by yoshiask** [comment]
As for whether it should be deleted, that depends on what the branch was for. If it's a feature or bugfix branch, then yes, it should be deleted after it's merged.

**Comment by leotrs** [comment]
Agreed, my worry is that I'm not sure we want to delete *every single branch* that gets merged.

**Comment by leotrs** [comment]
Any input @eulertour ? This is an easy change or a wontfix, and I'm trying to close as many issues as possible.

**Comment by eulertour** [comment]
I'd prefer that we did do it since we can go to the commit to look at them anyway and we currently have to create a branch for every commit to master.

**Comment by leotrs** [comment]
Ok so there are three votes for automatic deletion of branches.

**Comment by leotrs** [comment]
If I don't hear any votes against this in the next few days, I will implement it.

**Comment by leotrs** [comment]
This has now been implemented.
