### ISSUE TITLE
LaTeX compilation error: LaTeX Error: File `standalone.cls'  not found when adding Axes() to the scene

### ISSUE THREAD

**Issue by TomasMiskov** [ManimCommunity/manim#3002]
## Description of bug / unexpected behavior
I am getting a LaTeX Error: File `standalone.cls'  not found, when I just try to add Axes object to my scene. I suspect the problem is that in the standalone.cls package is somewhere enclosed in the wrong quotations as seen in that error message output. However, I can't locate the source of the problem. I have the package installed through my MikTex distribution.

## Expected behavior

I expect to produce axes with corresponding tick labels.

## How to reproduce the issue

<details><summary>Code for reproducing the problem</summary>

```py
%%manim -qm AnimateMM

class AnimateMM(Scene):
    def construct(self):
        axes = Axes(x_range = [-0.2, 2.2, 0.25],
                    y_range = [0, 4, 1],
                    y_axis_config={"scaling": LogBase()},
                    axis_config={"include_numbers": True},
                    x_length = 5,
                    tips=False)
        self.add(axes)
```

</details>

## Additional media files

<details><summary>Images/GIFs</summary>

</details>

## Logs
<details><summary>Terminal output</summary>

```
PASTE HERE OR PROVIDE LINK TO https://pastebin.com/ OR SIMILAR
```

</details>

## System specifications

<details><summary>System Details</summary>

```
- OS: Windows 10 v21H1
- RAM: 8GB
- Python version: 3.9.12
```
</details>

<details><summary>LaTeX details</summary>

+ LaTeX distribution (e.g. TeX Live 2020): MikTex
+ Installed LaTeX packages: Default MikTex packages, the standalone.cls is installed!

</details>

<details><summary>FFMPEG</summary>

Output of `ffmpeg -version`:

```
PASTE HERE
```
</details>

**Comment by behackl** [comment]
A possible explanation for this is that you have more than one LaTeX installation on your machine, and manim is picking up one where `standalone.cls` is not installed.

Please include the full error log (both the complete terminal output and the contents of the corresponding LaTeX .log file) for us to be able to say more.

**Comment by TomasMiskov** [comment]
You're a genius! I did have TinyTex installed through R-Studio and it has been picking up on that one. Is there a way to tell manim which one to choose?

**Comment by behackl** [comment]
The one that Manim uses is the one from your PATH, i.e., the one that is used when you call `latex` from your terminal. But you should also be able to install the required packages to your TinyTex install, whichever you prefer.

I'll close this issue as this is a problem with your local setup rather than a problem with the library, and we already have [this discussion](https://github.com/ManimCommunity/manim/discussions/2810) to keep track of the requested feature of a configureable LaTeX executable path. But please feel free to keep commenting here until your problem is resolved.
