### ISSUE TITLE
Mobject.add() should perform input type validation

### ISSUE THREAD

**Issue by leotrs** [ManimCommunity/manim#305]
Currently, the implementation of `Mobject.add` seems to assume that all its arguments are of type `Mobject`, but this is never guaranteed:

```python
    def add(self, *mobjects):
        if self in mobjects:
            raise ValueError("Mobject cannot contain self")
        self.submobjects = list_update(self.submobjects, mobjects)
        return self
```

Should we add this validation? I'm leaning toward yes, but I don't want to litter the whole codebase with input validation everywhere...

**Comment by huguesdevimeux** [comment]
Correct me if I'm wrong, but isn't `Mobject.add` supposed to be a private thing? Like, people will use Groupe if they want to add mobjects together. `Mobject.add` is used only in `Group`, and there is already an input validation there (see l.1121 `mobject.py`).

**Comment by leotrs** [comment]
I think it's a matter of good OOP design and encapsulation/responsibilities.
If I `add` something to a Mobject, am I responsible for checking I'm adding the right thing, or is the Mobject responsible for telling me? I think the latter. The fact that it's only used once by one other class is incidental.

Also, I don't think this is supposed to be private since it is inherited from the parent Container class, which makes it public. Overriding it and making it private would be very very weird...

**Comment by PgBiel** [comment]
alrighty, we can just `isinstance(obj, Mobject)` and be done with it

**Comment by leotrs** [comment]
Yes, the fix is easy, but I just wanted to see if anyone had objections to adding that typecheck.

**Comment by leotrs** [comment]
If consensus is reached on #325, this should be closed.
