### ISSUE TITLE
Mobject.remove() repeatedly checks for list membership

### ISSUE THREAD

**Issue by leotrs** [ManimCommunity/manim#306]
This is a fairly edge-case optimization, so please feel free to close this if it's deemed to niche.

Currently, the definition of `Mobject.remove` does this:

```python
    def remove(self, *mobjects):
        for mobject in mobjects:
            if mobject in self.submobjects:
                self.submobjects.remove(mobject)
        return self
```

At each removed mobject, the code `mobject in self.submobjects` is executed and performs linear search over a list, which is far from optimal if `self.submobjects` is large (even if `mobjects` is small). It would be more efficient to use an object that allows for `O(1)` membership checks, like a dict or a set (or an OrderedDict).

**Comment by huguesdevimeux** [comment]
I guess that there is no case of purposeful duplicate within `self.submobjects`, as if we use `set` they will be deleted.

**Comment by leotrs** [comment]
On the one hand, there are no repeated Mobjects in a scene, Scene.mobjects could be a set, not a lost. On the other hand, the code originally used the position of each Mobject in that list to determine the drawing order. But now that is done via Mobject.z_index.

So, in principle, I think we could change Scene.mobjects to be a set, and delete a while bunch of legacy code. Can anyone think of objections?

**Comment by leotrs** [comment]
We are thinking of not using z_index anymore, so my last comment doesn't work anymore.

On the topic of this issue: I think there are deeper refactorings to be done with submobjects (#358), so whatever is done to fix the present issues would be temporary at best. Closing for now.
