### ISSUE TITLE
Feature request: Get area under a implicit function

### ISSUE THREAD

**Issue by tapyu** [ManimCommunity/manim#3076]
I am not sure if it is already available, but AFAIK it is not possible the get the area from a implicit function. This [post](https://stackoverflow.com/questions/71209521/plotting-area-betwwn-implicit-curves) seems to confirm my supposition.

My code, for instance,

```py
from manim import *

class ImplicitFunctionExample(Scene):
    def construct(self):
        ax = Axes(x_range=[1, 4], y_range=[-1, 4]).add_coordinates()
        x_label = ax.get_x_axis_label(MathTex("x"), edge=DOWN, direction=DOWN, buff=0.5)#.shift(DOWN)
        y_label = ax.get_y_axis_label(MathTex("y"), edge=LEFT, direction=LEFT, buff=0.5)#.shift(DOWN)
        graph = ax.plot_implicit_curve(lambda x, y: x*y-1, color=YELLOW)
        area = ax.get_area(graph)
        axis = VGroup(ax, x_label, y_label)
        self.add(axis, graph, area)
```

Prompt to the error

> AttributeError: ImplicitFunction object has no attribute 't_min'

**Comment by behackl** [comment]
I am not sure that it is possible, in general, to determine a suitable definition of "area under the curve" for an implicit function. What would be the area under the curve $x^2 + (y-2)^2 = 1$?

You can construct a corresponding object via something like `VMobject.set_points_as_corners`, more or less like the current implementation of the `get_area` method does for parametric functions.
