### ISSUE TITLE
Broken OpenGL Operation sequence

### ISSUE THREAD

**Issue by MrDiver** [ManimCommunity/manim#3088]
https://github.com/ManimCommunity/manim/blob/d3b96dd68c12bef84ba5ac7b3f9d83ed58bdc0e3/manim/mobject/opengl/opengl_mobject.py#L2629-L2645

#2900 has some changes which might have broken OpenGL a tiny bit because there is now a case where the refresh id function is called but no attribute exists, this is caused by not using get_shader_wrapper() before using the attribute of the object which is in iteslf really confusing because i thought there was a call in the constructor at some point.

**Comment by MrDiver** [comment]
#3072 Whoops

**Comment by MrDiver** [comment]
`'OpenGLSurface' object has no attribute 'triangle_indices'`
The issue continues, this arises now by having a call to `refresh_shader_wrapper_id` which causes a call to `get_shader_vert_indices` which is overwritten in `OpenGLSurface` which calls `self.get_triangle_indices()` which tries to return the attribute but that doesn't exist by the time the function is called

**Comment by behackl** [comment]
Undoing this particular change with the decorator (or fixing the decorator to respect uninitialized attributes) should fix all of this again.

**Comment by MrDiver** [comment]
I posted a quickfix idea because i don't think we need to undo the change. But also i think there is a big need for refactoring this part of the code, all the initializations that happen randomly outside the constructor are really confusing. I think there was a try initially to make the shader wrappers act as a singleton but it doesn't look like that was a good solution to this problem. If i come around to it i might move some things around.
