### ISSUE TITLE
Homotopy in v0.17.2

### ISSUE THREAD

**Issue by scawteedawg** [ManimCommunity/manim#3094]
## Description of bug / unexpected behavior

I'm trying to work with the Homotopy class in Animations, but every way I write my homotopy, I get the error " 'function' object has no attribute 'init_scene' "

## Expected behavior

I expect the homotopy to be applied to the Mobject "text."

## How to reproduce the issue

<details><summary>Code for reproducing the problem</summary>

```py
from manim import *

class Homotopy(Scene):
    def construct(self):
        text = Tex(r'This is a homotopy')
        homotopy = lambda x,y,z,t:(x+t,y+ t**2,z)
        self.add(text)
        self.wait()
        self.play(Homotopy(homotopy,text))
        self.wait() 
```

</details>

## Additional media files

<details><summary>Images/GIFs</summary>

https://user-images.githubusercontent.com/102690108/209581707-a48a81a3-990e-4963-9e72-21b69ff0c8af.mp4

</details>

## Logs
<details><summary>Terminal output</summary>

```
MacBook-Pro december22 % python3 -m manim -pql -v DEBUG  manimtikz3.py Homotopy       
Manim Community v0.17.2

/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py:126: RuntimeWarning: 'manim.__main__' found in sys.modules after import of package 'manim', but prior to execution of 'manim.__main__'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
Manim Community v0.17.2

[12/26/22 12:46:01] DEBUG    Animation with empty mobject     animation.py:174
                    DEBUG    Hashing ...                        hashing.py:350
                    DEBUG    Hashing done in 0.022078 s.        hashing.py:362
                    DEBUG    Hash generated :                   hashing.py:365
                             4266129954_3315967912_663239807                  
                    INFO     Animation 0 : Using cached   cairo_renderer.py:78
                             data (hash : 4266129954_3315                     
                             967912_663239807)                                
                    DEBUG    List of the first few        cairo_renderer.py:87
                             animation hashes of the                          
                             scene: ['4266129954_33159679                     
                             12_663239807']                                   
Traceback (most recent call last):
╭────────────────────────────────────────────────────────────────────────────╮
│ File                                                                       │
│"/opt/homebrew/lib/python3.10/site-packages/manim/cli/render/commands.py",  │
│line 115, in render                                                         │
│    112             try:                                                    │
│    113                 with tempconfig({}):                                │
│    114                     scene = SceneClass()                            │
│  ❱ 115                     scene.render()                                  │
│    116             except Exception:                                       │
│    117                 error_console.print_exception()                     │
│    118                 sys.exit(1)                                         │
│ File "/opt/homebrew/lib/python3.10/site-packages/manim/scene/scene.py",    │
│line 223, in render                                                         │
│     220         """                                                        │
│     221         self.setup()                                               │
│     222         try:                                                       │
│  ❱  223             self.construct()                                       │
│     224         except EndSceneEarlyException:                             │
│     225             pass                                                   │
│     226         except RerunSceneException as e:                           │
│ File "/Users/scawteedawg/Documents/monthprojects/december22/manimtikz3.py",│
│line 371, in construct                                                      │
│    368         homotopy = lambda x,y,z,t:(x+t,y+ t**2,z)                   │
│    369         self.add(text)                                              │
│    370         self.wait()                                                 │
│  ❱ 371         self.play(Homotopy(homotopy,text))                          │
│    372         self.wait()                                                 │
│    373                                                                     │
│    374                                                                     │
│ File "/opt/homebrew/lib/python3.10/site-packages/manim/scene/scene.py",    │
│line 141, in __init__                                                       │
│     138             )                                                      │
│     139         else:                                                      │
│     140             self.renderer = renderer                               │
│  ❱  141         self.renderer.init_scene(self)                             │
│     142                                                                    │
│     143         self.mobjects = []                                         │
│     144         # TODO, remove need for foreground mobjects                │
╰────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'function' object has no attribute 'init_scene' ```

<!-- Insert screenshots here (only when absolutely necessary, we prefer copy/pasted output!) -->

</details>


## System specifications

<details><summary>System Details</summary>

- OS: macOS 13.1 (Ventura)
- RAM: 16 GB
- Python version (`python/py/python3 --version`): 3.10.9
- Installed modules (provide output from `pip list`):
```
appnope                        0.1.3
asttokens                      2.0.8
azure-cognitiveservices-speech 1.24.2
backcall                       0.2.0
cairocffi                      1.4.0
certifi                        2022.9.24
cffi                           1.15.1
charset-normalizer             2.1.1
click                          8.1.3
click-default-group            1.2.2
cloup                          0.13.1
colorama                       0.4.6
colour                         0.1.5
commonmark                     0.9.1
contourpy                      1.0.5
cycler                         0.11.0
cypari                         2.4.1
Cython                         0.29.32
decorator                      5.1.1
executing                      1.1.1
fonttools                      4.38.0
FXrays                         1.3.5
glcontext                      2.3.6
gTTS                           2.3.0
humanhash3                     0.0.6
idna                           3.4
ipython                        8.5.0
isosurfaces                    0.1.0
jedi                           0.18.1
joblib                         1.2.0
kiwisolver                     1.4.4
knot-floer-homology            1.2
lxml                           4.9.1
manim                          0.17.2
manim-voiceover                0.2.1.post0
ManimPango                     0.4.1
mapbox-earcut                  1.0.0
matplotlib                     3.6.1
matplotlib-inline              0.1.6
moderngl                       5.7.0
moderngl-window                2.4.2
mpmath                         1.2.1
multipledispatch               0.6.0
mutagen                        1.46.0
networkx                       2.8.8
numpy                          1.23.4
opencv-python                  4.6.0.66
packaging                      21.3
pandas                         1.5.2
pangocairocffi                 0.4.0
pangocffi                      0.8.0
parso                          0.8.3
pexpect                        4.8.0
pickleshare                    0.7.5
Pillow                         9.2.0
pip                            22.3.1
plink                          2.4.1
progressbar                    2.5
prompt-toolkit                 3.0.31
ptyprocess                     0.7.0
pure-eval                      0.2.2
pybind11                       2.10.0
pycairo                        1.21.0
pycparser                      2.21
pydub                          0.25.1
pyglet                         2.0b2
Pygments                       2.13.0
pyobjc-core                    8.5.1
pyobjc-framework-Cocoa         8.5.1
PyOpenGL                       3.1.6
pyparsing                      3.0.9
pypng                          0.20220715.0
pyrr                           0.10.3
python-dateutil                2.8.2
python-dotenv                  0.21.0
pytz                           2022.6
PyYAML                         6.0
requests                       2.28.1
rich                           6.2.0
scikit-learn                   1.1.3
scipy                          1.9.3
screeninfo                     0.8.1
setuptools                     65.6.3
six                            1.16.0
skia-pathops                   0.7.2
sklearn                        0.0
snappy                         3.0.3
snappy-manifolds               1.1.2
sox                            1.4.1
spherogram                     2.1
srt                            3.5.2
stack-data                     0.5.1
svgelements                    1.8.4
sympy                          1.11.1
threadpoolctl                  3.1.0
tqdm                           4.64.1
traitlets                      5.5.0
typing-extensions              3.10.0.2
urllib3                        1.26.13
validators                     0.20.0
watchdog                       2.1.9
wcwidth                        0.2.5
wheel                          0.38.4
```
</details>

<details><summary>LaTeX details</summary>

+ LaTeX distribution (e.g. TeX Live 2020): 1.53 
+ Installed LaTeX packages:
<!-- output of `tlmgr list --only-installed` for TeX Live or a screenshot of the Packages page for MikTeX -->
</details>

<details><summary>FFMPEG</summary>

Output of `ffmpeg -version`:

```
ffmpeg version 5.1.2 Copyright (c) 2000-2022 the FFmpeg developers
built with Apple clang version 14.0.0 (clang-1400.0.29.202)
configuration: --prefix=/opt/homebrew/Cellar/ffmpeg/5.1.2_1 --enable-shared --enable-pthreads --enable-version3 --cc=clang --host-cflags= --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libbluray --enable-libdav1d --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librist --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-videotoolbox --enable-neon
libavutil      57. 28.100 / 57. 28.100
libavcodec     59. 37.100 / 59. 37.100
libavformat    59. 27.100 / 59. 27.100
libavdevice    59.  7.100 / 59.  7.100
libavfilter     8. 44.100 /  8. 44.100
libswscale      6.  7.100 /  6.  7.100
libswresample   4.  7.100 /  4.  7.100
libpostproc    56.  6.100 / 56.  6.100
```
</details>

## Additional comments
<!-- Add further context that you think might be relevant for this issue here. -->

**Comment by behackl** [comment]
Your scene class cannot be called `Homotopy` too, you are shadowing the homotopy animation class.
