### ISSUE TITLE
Error message redirecting to missing documentation

### ISSUE THREAD

**Issue by meator** [ManimCommunity/manim#3111]
Hi. I am working with manim for the first time and I encountered this:
```
Manim Community v0.17.2

sh: 1: dvisvgm: not found
<traceback>
ValueError: Your installation does not support converting .dvi files to SVG. Consider updating dvisvgm to at least version 2.4. If this does not solve the problem, please
refer to our troubleshooting guide at: https://docs.manim.community/en/stable/installation/troubleshooting.html
```
I tried to follow this link but it's 404. I did some investigation through git and the commit 48747a74d932cc36394c1b7a69994b51855be359 removed this page.

References to this dead page can be found in https://github.com/ManimCommunity/manim/blob/main/.github/ISSUE_TEMPLATE/installation_issue.md?plain=1#L14 and https://github.com/ManimCommunity/manim/blob/main/manim/utils/tex_file_writing.py#L247

I am new to manim so I don't feel confident making a PR to fix this. There could be more 404 links present, I'm only reporting the one I came across.

**Comment by behackl** [comment]
Thanks for spotting this!

- The link in `tex_file_writing` should be replaced with https://docs.manim.community/en/stable/faq/general.html#my-installation-does-not-support-converting-pdf-to-svg-help,
- and the link in `installation_issue.md` should be referred to as the installation FAQ and linked to https://docs.manim.community/en/stable/faq/installation.html

Would you like to prepare a contribution with these two changes? Help would be welcome. :-)

**Comment by elyanah-aco** [comment]
I'd like to work on this (and it'll be my first open-source contribution too!)

**Comment by behackl** [comment]
> I'd like to work on this (and it'll be my first open-source contribution too!)

Thank you! Do you need any help getting started? Otherwise, just go ahead and send a pull request! 👍
