### ISSUE TITLE
`Mobject.animate.rotate` does not work properly in Manim 0.17.2

### ISSUE THREAD

**Issue by bourbonut** [ManimCommunity/manim#3117]
## Description of bug / unexpected behavior

`Mobject.animate.rotate` does not work properly in Manim 0.17.2
I think the current transformation is a scaling transformation and not a rotation as it should be.
I tried also `Mobject.animate.apply_matrix(np.array([[cos(-PI), sin(-PI), 0], [-sin(-PI), cos(-PI), 0], [0, 0, 1]]))`, but it does not work.

## Expected behavior

It should rotate the `Mobject` like the `Rotate` class.

## How to reproduce the issue

<details><summary>Code for reproducing the problem</summary>

```py
from manim import *
import numpy as np

O = np.array([0., 0., 0.])
X = np.array([1., 0., 0.])
Y = np.array([0., 1., 0.])
Z = np.array([0., 0., 1.])

class Quick(Scene):

    def construct(self):
        center = Dot(O)
        line = Line(O, X)
        self.add(center)
        # With `.rotate`, it does not work
        self.play(line.animate.rotate(-PI, about_point=O, axis=Z))
        # With `Rotate`, it works fine
        # self.play(Rotate(line, angle=-PI, about_point=O, axis=Z))
```

</details>

## Additional media files

<details><summary>Images/GIFs</summary>

https://user-images.githubusercontent.com/78030392/211155293-80403b4b-b410-4b02-a7d9-fd51ef83d49c.mp4

</details>

## System specifications

<details><summary>System Details</summary>

- OS : Linux
- Python version : Python 3.10.9
- Installed modules : Manim 0.17.2, numpy 1.21.5

</details>

<details><summary>FFMPEG</summary>

Output of `ffmpeg -version`: ffmpeg version 4.2.7-0ubuntu0.1

</details>

**Comment by Papierkorb2292** [comment]
That is the correct behavior, since `.animate` only interpolates between the starting and ending state. To rotate the object, the `Rotate` class can be used instead.
See: https://docs.manim.community/en/stable/tutorials/quickstart.html#using-animate-syntax-to-animate-methods

**Comment by bourbonut** [comment]
Thanks for your answer ! I will pay more attention next time !
