### ISSUE TITLE
Not getting a circle

### ISSUE THREAD

**Issue by Alvi0101** [ManimCommunity/manim#3136]
Hey guys, I am new to manim. I am using VS code in the Anaconda environment. I am facing a problem while running the following code. It's not generating a circle, only a blank video. Please help me out. Regards.
![issue](https://user-images.githubusercontent.com/123699141/214961052-ca673aef-3be7-4b0b-aaa0-4f60abc10a73.JPG)

**Comment by linuxr** [comment]
Hi, I think you should add the circle to scene before `self.wait(2)`.

like this
```
# ... ...
self.add(circle) 
# or 
# self.play(Create(circle))
self.wait(2)
```

**Comment by Alvi0101** [comment]
Hello, thank you for your reply. However, I am getting this **Execution Returned code=1** every time. How can I fix this??

**Comment by linuxr** [comment]
I could not reproduce the `return code-1` error.
Could you install and config `ffmpeg` correctly?

**Comment by behackl** [comment]
Likely not an issue with the library; also stale.
