### ISSUE TITLE
`SVGMobject` doesn't accept `str` for `color` attribute

### ISSUE THREAD

**Issue by naveen521kk** [ManimCommunity/manim#3138]
## Description of bug / unexpected behaviour
Look at this code:
```py
class Test(Scene):
  def construct(self):
    with open('a.svg', 'w') as f:
      f.write('''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 512"><path d="M160 64c0-11.8-6.5-22.6-16.9-28.2s-23-5-32.9 1.6l-96 64C-.5 111.2-4.4 131 5.4 145.8s29.7 18.7 44.4 8.9L96 123.8V416H32c-17.7 0-32 14.3-32 32s14.3 32 32 32h96 96c17.7 0 32-14.3 32-32s-14.3-32-32-32H160V64z"/></svg>''')
    self.add(SVGMobject("a.svg", color="WHITE"))
```
[error.log](https://github.com/ManimCommunity/manim/files/10518649/error.log)
This produces the attached traceback, which is not something expected because passing colors as string works on other places like
```py
class Test(Scene):
  def construct(self):
    self.add(Square(color="RED"))

```
I think it was introduced by https://github.com/ManimCommunity/manim/pull/2898.
See also https://github.com/naveen521kk/manim-fontawesome/issues/7 where it was first reported.

## Expected behaviour

Allow passing strings for `color` keyword just like how it's on other Mobjects.

**Comment by jalajk24** [comment]
Can I work on this issue?

**Comment by naveen521kk** [comment]
> Can someone check if this is still an issue after the Color PR ?

Looks like it's fixed now on the recent version. Thanks!

**Comment by Viicos** [comment]
Even if it doesn't, the type hints need to be updated (and maybe the color parsing as well?). This will probably be tacking in typing PRs
