### ISSUE TITLE
SVG export support

### ISSUE THREAD

**Issue by Schabolon** [ManimCommunity/manim#3151]
> Yes, saving to other image formats would be nice. Right now we are limited by two main reasons: the `Camera` object only manipulates pixel arrays directly, and the `SceneFileWriter` only works by sending pixel arrays to ffmpeg.y
> In the future, once we have refactored `Camera` into a `Renderer`, and once we have refactored `SceneFileWriter` as well, this may be possible at some point.

_Originally posted by @leotrs in https://github.com/ManimCommunity/manim/issues/425#issuecomment-689834163_
            
I was trying to export SVG images and found this.
Therefore, I wanted to ask whether it will be possible to generate SVGs in the near future.
Thanks a lot.

**Comment by behackl** [comment]
There is a plugin that allows to export vectorized mobjects and groups to be exported as SVGs, you can find it here: https://pypi.org/project/manim-mobject-svg/. This is about as good as it gets for now.

Closing this for now, we can revisit the idea of SVG exports in the future, after the rendering backend has been improved substantially.

**Comment by Schabolon** [comment]
Thank you very much for your quick response.
