### ISSUE TITLE
alignment_vect argument in Mobject.align_to() method is deprecated. 

### ISSUE THREAD

**Issue by ubaldot** [ManimCommunity/manim#3162]
After getting mad to trying to figure out what such an argument does, I found this: https://github.com/3b1b/manim/issues/1353
Can that be removed from code and docs?

**Comment by elyanah-aco** [comment]
I can work on this, if others agree on this issue!

**Comment by behackl** [comment]
Help is welcome, go ahead and send a PR. 👍
