### ISSUE TITLE
`--save_last_frame` appears twice in options

### ISSUE THREAD

**Issue by dkaszews** [ManimCommunity/manim#3174]
## Description of bug / unexpected behavior

When using `manim render --help`, you can see `--save_last_frame` appearing twice, once marked as deprecated:

```
  -s, --save_last_frame
...
  -s, --save_last_frame          Save last frame as png (Deprecated).
```

This is also visible i n [reference manual](https://docs.manim.community/en/stable/guides/configuration.html#:~:text=webm%7Cmov%5D%0A%20%20%2Ds%2C%20%2D%2D-,save_last_frame,-%2Dq%2C%20%2D%2Dquality%20%5Bl).

## Expected behavior

The option appears exactly once

## How to reproduce the issue

<details><summary>Code for reproducing the problem</summary>

```bash
> manim render --help | grep 'save_last_frame'
```

</details>

## Additional media files

<details><summary>Images/GIFs</summary>

</details>

## Logs
<details><summary>Terminal output</summary>

```
PASTE HERE OR PROVIDE LINK TO https://pastebin.com/ OR SIMILAR
```

</details>

## System specifications

<details><summary>System Details</summary>

- OS (with version, e.g., Windows 10 v2004 or macOS 10.15 (Catalina)):
- RAM:
- Python version (`python/py/python3 --version`):
- Installed modules (provide output from `pip list`):
```
PASTE HERE
```
</details>

<details><summary>LaTeX details</summary>

+ LaTeX distribution (e.g. TeX Live 2020):
+ Installed LaTeX packages:

</details>

<details><summary>FFMPEG</summary>

Output of `ffmpeg -version`:

```
PASTE HERE
```
</details>

## Additional comments

This is probably a code cleanup issue, as you can clearly see the option being declared twice in [`render_options.py`](https://github.com/ManimCommunity/manim/blob/main/manim/cli/render/render_options.py):

```py
# line 61
    option("-s", "--save_last_frame", is_flag=True, default=None),
# line 125:131
    option(
        "-s",
        "--save_last_frame",
        default=None,
        is_flag=True,
        help="Save last frame as png (Deprecated).",
    ),
```

I can create a PR to remove one of them, just need info which one should be removed - the first one without help, or the second one marking it deprecated (easiest to just remove the "deprecated" keyword as it's formated nicely, and get rid of the first one).

Should I also report it as a bug in [cloup](https://github.com/janLuke/cloup) that it doesn't check for duplicates?

**Comment by MrDiver** [comment]
It is not really a bug that it doesn't check for duplicates. If you add the same command twice then it's not really cloups fault.

Just remove one of them and see if it still works as intended. If it does then make a PR!

**Comment by behackl** [comment]
The `-s` flag has been deprecated long enough, it should be removed.
