### ISSUE TITLE
`angle_between_vectors` Has Wrong Annotated Return Type

### ISSUE THREAD

**Issue by AlexKempen** [ManimCommunity/manim#3188]
## Description of bug / unexpected behavior
The annotated return type of manim's `angle_between_vectors` function is currently annotated as `np.ndarray`.
However, this is incorrect since `angle_between_vectors` actually returns a `float`, not a `np.ndarray`.

Internally, `angle_between_vectors` calls `np.arctan2`, passing two normed vectors (i.e. scalars) as arguments. As noted by the numpy documentation, `np.arctan2` returns a scalar when its arguments scalars. So, the result of this function is a `float`, not an `np.ndarray`.

[numpy documentation for `np.arctan2`](https://numpy.org/doc/stable/reference/generated/numpy.arctan2.html)
[Source code for `angle_between_vectors`](https://github.com/ManimCommunity/manim/blob/main/manim/utils/space_ops.py#L327)

## Expected behavior
The annotated return type of `angle_between_vectors` should be `float`, not `np.ndarray`.

## How to reproduce the issue
<summary>Code for reproducing the problem:</summary>

```py
from manim import *
print(angle_between_vectors(UP, LEFT)) # prints a float, not an np.ndarray
```

**Comment by behackl** [comment]
Thanks for the hint! Do you feel like sending a PR for fixinf this?
