### ISSUE TITLE
Set up workflow for pushing releases to PyPI

### ISSUE THREAD

**Issue by kilacoda** [ManimCommunity/manim#32]
Once, cleanup is done, we should begin integrating a Workflow/Action to automatically package new releases and shoot them of to PyPI.
![image](https://user-images.githubusercontent.com/65204531/82470678-45f29180-9ae3-11ea-8b99-865049ab39fc.png)

**Comment by leotrs** [comment]
One pre-requisite for this is to have automates tests with Travis - do we have an issue for that yet?

**Comment by kilacoda** [comment]
I think we do

**Comment by kilacoda** [comment]
Nope, because #22 is closed

**Comment by kilacoda** [comment]
We'll have to set up tests then, with pytest and the like. I'll open an issue for that.

**Comment by naveen521kk** [comment]
So please assign this issue to me I would be doing it while I will be working on #165

**Comment by leotrs** [comment]
Done. Out of curiosity, can you not assign yourself?

**Comment by naveen521kk** [comment]
No I didn't find an option for that.

**Comment by leotrs** [comment]
This can be done through GitHub actions, yes? @eulertour

**Comment by kilacoda** [comment]
Correct. Would require creation of a new workflow.

**Comment by naveen521kk** [comment]
Yes, I would be doing it in #165

**Comment by naveen521kk** [comment]
I am closing this as #165 is merged and we have a workflow for it.
