### ISSUE TITLE
Scene Caching must recognise changes in attributes of objects

### ISSUE THREAD

**Issue by Aathish04** [ManimCommunity/manim#320]
Currently, the Scene Caching Mechanism considers three hashes to check if a scene and its contents have changed:
1) hash corresponding to the arguments passed to scene.play (or scene.wait).
2) hash obtained with all the mobjects present in scene, including those not in the current play/wait call
3) hash obtained from camera_config.

However, using just these three hashes is not specific enough in some contexts.

Consider the following test scene:

```python
class Test(Scene):
    def construct(self):
        T1 = TextMobject("M")
        self.play(Write(T1))
```

After the first render, if the T1 TextMobject is changed to some other letter, say `Q`, the scene caching mechanism will not recognise this change, and will still show the original animation of the letter `M` being written.

A possible solution to this would be to also hash the attributes of all the mobjects present in the Scene, or at least those mobjects being animated, and add that to the list of hashes used.

cc-ing @huguesdevimeux 

**EDIT :** Original issue : 
Okay, so this works as intended for the first render, and produces the video as required, but doesn't re-render if the Vector Field is changed.

Let's take the same script I used in #302 :
```python
from manim import *

class TestVectorField(Scene):
    def four_swirls_function(self,point):
        x, y = point[:2]
        result = ((y**3 - 4 * y) * RIGHT + (x**3 - 16 * x) * UP)*0.05
        return result

    def construct(self):
        lines = StreamLines(self.four_swirls_function)
        self.add(AnimatedStreamLines(
            lines,
            line_anim_class=ShowPassingFlash
        ))
        self.wait(2)
```
It's output should be something like:

![TestVectorField](https://user-images.githubusercontent.com/33193764/90378005-73c18500-e096-11ea-9823-9a4058ce600e.gif)

If I change `four_swirls_function` to something else, like `result = ((y**2 - 4 * y) * RIGHT + (x**3 - 16 * x) * UP)*0.05`,
the output should be something like:
![TestVectorField2](https://user-images.githubusercontent.com/33193764/90378195-ae2b2200-e096-11ea-9568-dc6568a4ee2a.gif)

**But, the scene caching mechanism still uses the previous cached file.**

EDIT: I don't think this is due to the bug that this PR fixes, but a more specific case of what  I described in #320.

_Originally posted by @Aathish04 in https://github.com/ManimCommunity/manim/pull/315#issuecomment-674758281_

**Comment by huguesdevimeux** [comment]
Thanks for the report, and sorry for the answer delay !

The bug you described is super weird. In theory, scene-caching mechanism takes **_everything_** (see `hashing.py`, and more particularly `CustomEncoder.default`). So this : 
> A possible solution to this would be to also hash the attributes of all the mobjects present in the Scene,
is already done by manim.

I don't see rn where this comes, but I will take a look at that and try to fix it in a few days.

**Comment by Aathish04** [comment]
> Thanks for the report, and sorry for the answer delay !
> 
> The bug you described is super weird. In theory, scene-caching mechanism takes **_everything_** (see `hashing.py`, and more particularly `CustomEncoder.default`). So this :
> 
> > A possible solution to this would be to also hash the attributes of all the mobjects present in the Scene,
> > is already done by manim.
> 
> I don't see rn where this comes, but I will take a look at that and try to fix it in a few days.

I worked such a thing in already. I'm testing it rn :)

**Comment by huguesdevimeux** [comment]
What do you mean ? What thing ?

**Comment by Aathish04** [comment]
Ok, so currently, the scene caching mechanism takes only the __dict__ of the Animation that's being played/rendered, and does not consider the __dict__ of the Mobjects in the animation.

I have added some code that makes the mechanism recursively get the __dict__ of any objects in it that have a __dict__.

This way, it will also account for the Attributes of the Mobjects in the animation.

**Comment by Aathish04** [comment]
@huguesdevimeux Update:

So my changes fix _this_ issue, but cause a RecursionError when testing with the script in #315 

I believe this is because there are _so_ many StreamLines in the AnimatedStreamLines that going through the __dicts__ of each and every one of them occurs more than 1000 times.

Thoughts?

**Comment by huguesdevimeux** [comment]
> Ok, so currently, the scene caching mechanism takes only the **dict** of the Animation that's being played/rendered, and does not consider the **dict** of the Mobjects in the animation.

it does already if I understand correctly. See l.146 `hashing.py`. 



> I have added some code that makes the mechanism recursively get the **dict** of any objects in it that have a **dict**.

And it does already as well, as `json.dumps` is by essence recursive.

**Comment by Aathish04** [comment]
> > Ok, so currently, the scene caching mechanism takes only the **dict** of the Animation that's being played/rendered, and does not consider the **dict** of the Mobjects in the animation.
> 
> it does already if I understand correctly. See l.146 `hashing.py`.
> 
> > I have added some code that makes the mechanism recursively get the **dict** of any objects in it that have a **dict**.
> 
> And it does already as well, as `json.dumps` is by essence recursive.

Nope. I believe it doesn't do that because of:
https://github.com/ManimCommunity/manim/blob/35e9e05eec4dc091d462ca2dab8b4561497ba0f1/manim/utils/hashing.py#L71-L75


Here, it basically ignores any key in __dict__ if it has a string as its key.

In the `__dict__` of the animation (which is `obj`), the Mobject being animated has the _string_ key `mobject`, so it, and by extension, it's attributes, are ignored.

**Comment by huguesdevimeux** [comment]
> Here, it basically ignores any key in dict if it has a string as its key.

It does not ignore it. It let it as it is, and then it's hashed. 

To check if the issue is related to that, could you check if the bug with TextMobjext is happening on master ? 

I think this is related to the try expect thing, maybe.

**Comment by Aathish04** [comment]
> It does not ignore it. It let it as it is, and then it's hashed.

> To check if the issue is related to that, could you check if the bug with TextMobjext is happening on master ?
Yes, the issue with the TextMobject happens on Master too.

I'll push my changes to a new branch in about 2 mins.

**Comment by Aathish04** [comment]
@huguesdevimeux You can see my changes over here : https://github.com/Aathish04/manim/commit/bbf43fc1b35b965f4ebba15243aa90190efdbff1

**Comment by Aathish04** [comment]
@huguesdevimeux 
> It does not ignore it. It let it as it is, and then it's hashed. 

Yea, the problem is that it doesn't hash the attributes of the value of `mobject`...

The hashing mechanism just saw that there was a TextMobject there, and assumed it was the same, and used the Cached file , not recognising that the actual attributes of the TextMobject changed.

The changes I made sort of fix that, but I can't get it to work on the AnimatedStreamLines example I sent, since it throws a recursion error, probably because there are too many StreamLine mobjects to check.

**Comment by Aathish04** [comment]
@huguesdevimeux Some Updates:

Commit https://github.com/Aathish04/manim/commit/b90218c835f0d188fcb1269c121aff132146e6e1 fixes the RecursionError, but the problem I mentioned in #302 (the second problem, where the same cached file is used even if the scene is changed),  still persists. At this point I think that it might be unrelated to this issue 🤔 .

Wierdly, if I add a keyword argument to the AnimatedStreamLines(), any keyword argument, the hash changes and it regenerates the cached video file, which means it _is_ checking the attributes of the objects, but can't recognise a change in the `four_swirls_function`, for some reason...

Also, I was unable to reproduced this bug in the latest `master` with `TextMobject`, which was pretty wierd.
