### ISSUE TITLE
Angle value gets not updated

### ISSUE THREAD

**Issue by 21Manu09** [ManimCommunity/manim#3207]
Hello together,

i created a Triangle with the three inner angles. Their sizes are also shown. When one vertex of the triangle moves, the angles with their shown sizes should be updatet. For the angles themself it works fine, but not for the sizes.

Here is the critical part of my code [a,b,c are the angles and a_text, b_text, c_text are the labels(sizes)]:

```
        a.add_updater(lambda mobj: mobj.become(Angle.from_three_points(B,A,C, radius=2, other_angle=False)))
        b.add_updater(lambda mobj: mobj.become(Angle.from_three_points(C,B,A, radius=2, other_angle=False)))
        c.add_updater(lambda mobj: mobj.become(Angle.from_three_points(A,C,B, radius=2, other_angle=False)))

        a_text.add_updater(lambda mobj: mobj.become(MathTex(r"\alpha = {:.0f}^\circ".format(a.get_value()*180/PI))))
        b_text.add_updater(lambda mobj: mobj.become(MathTex(r"\beta = {:.0f}^\circ".format(b.get_value()*180/PI))))
        c_text.add_updater(lambda mobj: mobj.become(MathTex(r"\gamma = {:.0f}^\circ".format(c.get_value()*180/PI))))
```

Thanks a lot for your help!

**Comment by vaclavblazej** [comment]
@21Manu09 Can you please post a minimal (but compilable) Manim source code that courses your issue?
