### ISSUE TITLE
3D objects that are behind other objects are rendered in front

### ISSUE THREAD

**Issue by lerad** [ManimCommunity/manim#3213]
## Description of bug / unexpected behavior
I want to draw a line and a quadratic surface. As seen from the camera, the line is partially behind the surface and partially in front of it. However, the line is drawn completely in front of the surface. See the media output below.

## Expected behavior
I would have expected that the parts of the line which are behind the surface are not visible. I added also an edited image below which shows what I expected.

## How to reproduce the issue
I used the following code to create the images below:

```py
from manim import *
import math

class Test3d(ThreeDScene):
    def construct(self):
        self.set_camera_orientation(phi=70 * DEGREES, theta=-110 * DEGREES)
        axes = ThreeDAxes()
        surf = Surface(lambda phi,r: axes.c2p(math.cos(phi)*r,math.sin(phi)*r,0.5*r**2+1), u_range=[0,2*math.pi], v_range=[0,2])
        line = Line(start=axes.c2p(-0.5,-0.5,0), end=axes.c2p(-0.5,-0.5,4))
        self.add(axes, surf, line)
        self.wait(5)
```

</details>

## Additional media files

<details><summary>Images (actual)</summary>

**Default rendering by cairo**:
`manim -pqh  -s .\test_3d.py Test3d`
The line is in front of the surface, even in the middle where it should be hidden by the surface.
![cairo_Test3d_ManimCE_v0 17 3](https://user-images.githubusercontent.com/485326/230971164-ca4947f9-2dca-4f73-85a0-32f44a4fd35e.png)

When **using opengl**
`manim -pqh --renderer opengl -s .\test_3d.py Test3d`
the line is again not hidden. Here, now even the axes are not correct anymore. 

![opengl_Test3d_ManimCE_v0 17 3](https://user-images.githubusercontent.com/485326/230972646-54f1ed9e-35f8-422e-8636-2feb6cbad090.png)

I also tried different combinations of the  `--use_projection_fill_shaders` and `--use_projection_stroke_shaders`, however, I am not sure if I use them correctly, as the results are a bit strange.

`manim -pqh -s --renderer opengl --use_projection_fill_shaders .\test_3d.py Test3d`:
![fill_Test3d_ManimCE_v0 17 3](https://user-images.githubusercontent.com/485326/230973977-676fddb4-74cf-4766-a4bc-0ea9595db018.png)

`manim -pqh -s --renderer opengl --use_projection_stroke_shaders .\test_3d.py Test3d`:
![stroke_Test3d_ManimCE_v0 17 3](https://user-images.githubusercontent.com/485326/230974041-402b1cee-ef39-44f6-b87d-2f1b642d0bd3.png)

`manim -pqh -s --renderer opengl --use_projection_fill_shaders --use_projection_stroke_shaders .\test_3d.py Test3d`
![fillstroke_Test3d_ManimCE_v0 17 3](https://user-images.githubusercontent.com/485326/230974073-3a22f5ae-3566-4f67-b728-7f0e805878d2.png)

</details>

<details><summary>Images (expected)</summary>

**Expected result:** This is what I want to achieve (manually edited by paint):
![Expected Output](https://user-images.githubusercontent.com/485326/230970711-8791b231-4ef7-4097-a74a-b5e222aebc5b.png)

</details>

## System specifications

<details><summary>System Details</summary>

- OS: Windows 10
- RAM: 16 GB RAM
- Python 3.9.13
- manim version 0.17.3
</details>

<details><summary>Installed Python Packages</summary>

- certifi==2022.12.7
- charset-normalizer==3.1.0
- click==8.1.3
- click-default-group==1.2.2
- cloup==0.13.1
- colorama==0.4.6
- colour==0.1.5
- decorator==5.1.1
- glcontext==2.3.7
- idna==3.4
- isosurfaces==0.1.0
- manim==0.17.3
- ManimPango==0.4.3
- mapbox-earcut==1.0.1
- markdown-it-py==2.2.0
- mdurl==0.1.2
- moderngl==5.8.2
- moderngl-window==2.4.3
- multipledispatch==0.6.0
- networkx==2.8.8
- numpy==1.24.2
- Pillow==9.5.0
- pycairo==1.23.0
- pydub==0.25.1
- pyglet==2.0.5
- Pygments==2.15.0
- pyrr==0.10.3
- requests==2.28.2
- rich==13.3.3
- scipy==1.10.1
- screeninfo==0.8.1
- six==1.16.0
- skia-pathops==0.7.4
- srt==3.5.3
- svgelements==1.9.1
- tqdm==4.65.0
- urllib3==1.26.15
- watchdog==2.3.1
</details>

**Comment by JinchuLi2002** [comment]
Hi there, try using Line3D class instead of Line for this case, this should fix the problem.
```line = Line3D(start=axes.c2p(-0.5,-0.5,0), end=axes.c2p(-0.5,-0.5,4))```

<details>
<summary>Output</summary>
<img width="789" alt="Screen Shot 2023-04-13 at 3 02 21 PM" src="https://user-images.githubusercontent.com/63861808/231857915-68392db9-1600-4181-ad60-4da5ada6f9bf.png">
</details>

**Comment by lerad** [comment]
Thank you very much, this seems to be exactly what I searched for! I missed that these "3D" classes existed.
