### ISSUE TITLE
VDict doesn't respect order of created objects

### ISSUE THREAD

**Issue by leotrs** [ManimCommunity/manim#323]
Right now, we can create a `VDict` with 
```python
d = VDict({'circle': Circle(), 'label': TextMobject("this is a circle")})
```

And that's awesome. But then I have to manually change their z_index to guarantee that the label will display on top of the circle: `d['label'].z_index = d['circle'].z_index - 1`, or something along those lines. What would be great is if `VDict` had an underlying `OrderedDict` which kept track of the order of the elements, so that these two VDicts would display differently by default:
```python
VDict({'circle': Circle(), 'label': TextMobject("this is a circle")})
VDict({'label': TextMobject("this is a circle"), 'circle': Circle()})
```

cc. @nilaybhatia

**Comment by nilaybhatia** [comment]
Nice idea. Do you recommend fixing this on #316, which is currently ready for review, or an entirely new PR?

**Comment by leotrs** [comment]
No, it should be a totally different PR. Also, I think from python 3.8 and on, dicts are by default ordered so we might as well just wait until everyone just adopts 3.8...

**Comment by PgBiel** [comment]
Actually, seems like they're ordered by default in python 3.6+. On python 3.6, it was a CPython-specific implementation, while on 3.7+ it became a language feature (see https://stackoverflow.com/questions/39980323/are-dictionaries-ordered-in-python-3-6).

**Comment by leotrs** [comment]
Interesting. So we might just forget about it and wait until 3.7 becomes the default :shrug:
