### ISSUE TITLE
Bump pinned requirements

### ISSUE THREAD

**Issue by gothicVI** [ManimCommunity/manim#3241]
When updating installed python packages I'm getting:
```
manim 0.17.3 has requirement cloup<0.14.0,>=0.13.0, but you have cloup 2.1.0.
manim 0.17.3 has requirement networkx<3.0,>=2.5, but you have networkx 3.1.
manim 0.17.3 has requirement watchdog<3.0.0,>=2.1.6, but you have watchdog 3.0.0.
```
which blocks the update of `cloup`, `networkx`, and `watchdog`. Is There a reason for that or could those be bumped?

**Comment by MrDiver** [comment]
I think they could be bumped, if not the runners will complain so just try it out and make a PR then you will see.

**Comment by behackl** [comment]
We've bumped most dependencies in the new release, progress to make things less restricted is being made in #3376. Closing this for now.
