### ISSUE TITLE
Should Mobject be an abstract class?

### ISSUE THREAD

**Issue by leotrs** [ManimCommunity/manim#325]
The following excerpt from `camera.py` contains the functions used to render objects and put them in the Camera's `pixel_array`.

https://github.com/ManimCommunity/manim/blob/35e9e05eec4dc091d462ca2dab8b4561497ba0f1/manim/camera/camera.py#L488-L493

As you can see, Mobjects are not processed at all. This means that if I `add` a Mobject on my `Scene`, it will never be captured by the camera and not rendered on video.

Seeing as Mobjects are never being handled, should `Mobject` be an abstract class? As far as I can tell, Mobject is really only instantiated in some tests, but most (all?) of those tests could just as easily be written using VMobject instead.

EDIT: another question. Currently Mobjects are being silently ignored. Instead, the code above should (at least) issue a warning to the user "you are trying to render a Mobject, which is currently not supported. Use VMobject instead".
EDIT: regardless of whether or not Mobject is made abstract, I think `Group` should be deprecated. Nobody is using `Group`. (Nobody _can_ use Group for anything useful since it can only contain `Mobject`s.)

**Comment by Aathish04** [comment]
> Seeing as Mobjects are never being handled, should Mobject be an abstract class? 

I think that would be much better, since it can be thought of as a generic "object" just like `Container`.

> I think Group should be deprecated. Nobody is using Group. (Nobody can use Group for anything useful since it can only contain Mobjects.)

Disagree, at least until we can find some way to fit _every_ single Mobject in  VGroups. Currently, you cannot put `ImageMobjects` or `ValueTrackers` inside VGroups, since they do not inherit from VMobject.

**Comment by leotrs** [comment]
Oooh, good point on `Group` there, I forgot about that. BTW, do you know *why* `VGroup` can only contain `VMobjects`?

**Comment by huguesdevimeux** [comment]
> do you know _why_ `VGroup` can only contain `VMobjects`?

Seeing the code I would say it's because  `VGroup` inherits from `VMobject` (?).
Like, its basically a `VMobject `with submobjects.

**Comment by leotrs** [comment]
Yeah, I think it's so that you can do things like `VGroup.set_fill` and that will neatly broadcast to each submobject.

**Comment by leotrs** [comment]
I've looked at this a bit more and I've determined Mobject cannot be made an abstract base class. The reason is that it is a derived class from Container, and Container is already an abstract base class.

I still think it'd be good to raise a warning saying "you shouldn't try to render Mobjects". But this is not a priority I think.

**Comment by huguesdevimeux** [comment]
> The reason is that it is a derived class from Container, and Container is already an abstract base class.

Could you clarify this? I don't see how bother an abstract class.

**Comment by leotrs** [comment]
This was discussed over discord, but for completeness: Mobject can't derive from ABC and Container at the same time, because Container already derives from ABC.

**Comment by leotrs** [comment]
I believe Mobject can still be made into an abstract class in some other way, for example by decorating one of its methods with `@abstractmethod` (see [here](https://stackoverflow.com/questions/48336655/how-to-make-an-abstract-class-inherit-from-another-abstract-class-in-python)). However, if we do so, then each of its derived classes has to override that method. Note that Group and Vmobject both derive from Mobject, so there are not many methods that will be meaningfully overriden by both at the same time.
