### ISSUE TITLE
Does the table have a way to reset a cell? 

### ISSUE THREAD

**Issue by qywk99** [ManimCommunity/manim#3250]
## Description of proposed feature

Does the **table** have a way to reset a cell? **matrix** also need this method
such as：
|title1|title2|
|:--:|:--:|
|1|2|

Let's turn 1 into 3

|title1|title2|
|:--:|:--:|
|3|2|

## How can the new feature be used?

Use `get_cell` reutrn cell. Reset a cell text or latex.

**Comment by MrDiver** [comment]
```py
class GetCellExample(Scene):
    def construct(self):
        table = Table(
            [["1", "2"]],
            col_labels=[Text("A"), Text("B")],
        )
        cell = table.get_entries_without_labels((1, 1))
        self.add(table)
        self.play(table.animate.shift(UP))
        self.play(cell.animate.become(Text("3").move_to(cell)))
        self.play(table.animate.shift(DOWN))
 ```

https://github.com/ManimCommunity/manim/assets/17803932/373eb143-4bec-4156-89cf-64232faa626c

**Comment by MrDiver** [comment]
Keep in mind that it doesn't dynamically change the size of the table just because you replace the content. For that you want to create a new table.
```py
class GetCellExample(Scene):
    def construct(self):
        table = Table(
            [["1", "2"]],
            col_labels=[Text("A"), Text("B")],
        )
        table2 = Table(
            [["1", "BIGGER CONTENT"]],
            col_labels=[Text("A"), Text("B")],
        )
        self.add(table)
        self.play(table.animate.become(table2))
 ```


https://github.com/ManimCommunity/manim/assets/17803932/2956a98a-48a7-4d9b-8dc9-45c02a8487b6
