### ISSUE TITLE
BraceLabel text can not use chinese

### ISSUE THREAD

**Issue by Archkik** [ManimCommunity/manim#3254]
## Description of bug / unexpected behavior

I found that text is converted to tex mobject by default in BraceLabel. The default latex does not support Chinese

Therefore I use `config["tex_template"]=TexTemplateLibrary.ctex`
Switch to ctex that supports Chinese
The following error will appear

```py
IndexError                                Traceback (most recent call last)
Cell In[10], line 1
----> 1 get_ipython().run_cell_magic('manim', '-qm  Test', '\nconfig["tex_template"]=TexTemplateLibrary.ctex\nprint(config["tex_template"].tex_compiler)\nclass AcuteAngle(Scene):\n    def construct(self):\n        line_1=Line([-1,0,0],[1,0,0])\n        text=BraceLabel(line_1,text="中文")\n        self.add(line_1,text)\n')

File D:\ProgramData\anaconda\envs\manimtest\lib\site-packages\IPython\core\interactiveshell.py:2475, in InteractiveShell.run_cell_magic(self, magic_name, line, cell)
   2473 with self.builtin_trap:
   2474     args = (magic_arg_s, cell)
-> 2475     result = fn(*args, **kwargs)
   2477 # The code below prevents the output from being displayed
   2478 # when using magics with decodator @output_can_be_silenced
   2479 # when the last Python token in the expression is a ';'.
   2480 if getattr(fn, magic.MAGIC_OUTPUT_CAN_BE_SILENCED, False):

File D:\ProgramData\anaconda\envs\manimtest\lib\site-packages\manim\utils\ipython_magic.py:141, in ManimMagic.manim(self, line, cell, local_ns)
    139     SceneClass = local_ns[config["scene_names"][0]]
    140     scene = SceneClass(renderer=renderer)
--> 141     scene.render()
    142 finally:
    143     # Shader cache becomes invalid as the context is destroyed
    144     shader_program_cache.clear()

File D:\ProgramData\anaconda\envs\manimtest\lib\site-packages\manim\scene\scene.py:223, in Scene.render(self, preview)
    221 self.setup()
    222 try:
--> 223     self.construct()
    224 except EndSceneEarlyException:
    225     pass

File <string>:4, in construct(self)

File D:\ProgramData\anaconda\envs\manimtest\lib\site-packages\manim\mobject\svg\brace.py:204, in BraceLabel.__init__(self, obj, text, brace_direction, label_constructor, font_size, buff, brace_config, **kwargs)
    202     self.label = self.label_constructor(font_size=font_size, *text, **kwargs)
    203 else:
--> 204     self.label = self.label_constructor(str(text), font_size=font_size)
    206 self.brace.put_at_tip(self.label)
    207 self.add(self.brace, self.label)

File D:\ProgramData\anaconda\envs\manimtest\lib\site-packages\manim\mobject\text\tex_mobject.py:280, in MathTex.__init__(self, arg_separator, substrings_to_isolate, tex_to_color_map, tex_environment, *tex_strings, **kwargs)
    273 try:
    274     super().__init__(
    275         self.arg_separator.join(self.tex_strings),
    276         tex_environment=self.tex_environment,
    277         tex_template=self.tex_template,
    278         **kwargs,
    279     )
--> 280     self._break_up_by_substrings()
    281 except ValueError as compilation_error:
    282     if self.brace_notation_split_occurred:

File D:\ProgramData\anaconda\envs\manimtest\lib\site-packages\manim\mobject\text\tex_mobject.py:354, in MathTex._break_up_by_substrings(self)
    352     sub_tex_mob.submobjects = [VectorizedPoint()]
    353     last_submob_index = min(curr_index, len(self.submobjects) - 1)
--> 354     sub_tex_mob.move_to(self.submobjects[last_submob_index], RIGHT)
    355 else:
    356     sub_tex_mob.submobjects = self.submobjects[curr_index:new_index]

IndexError: list index out of range
```

Also I need to add that when I use the example in the documentation, the result is normal, proving that my ctex is installed correctly
```py
%%manim -qm  LaTeXTemplateLibrary

class LaTeXTemplateLibrary(Scene):
    def construct(self):
        tex = Tex('Hello 你好 \\LaTeX', tex_template=TexTemplateLibrary.ctex, font_size=144)
        self.add(tex)
```

## Expected behavior
After switching to ctex, Chinese and English are displayed normally

## How to reproduce the issue
```py
from manim import *
#Manim Community v0.17.3
```

```py
%%manim -qm  Test

config["tex_template"]=TexTemplateLibrary.ctex
print(config["tex_template"].tex_compiler)
class AcuteAngle(Scene):
    def construct(self):
        line_1=Line([-1,0,0],[1,0,0])
        text=BraceLabel(line_1,text="中文")
        self.add(line_1,text)
```

## Additional media files

<details><summary>Images/GIFs</summary>

</details>

## Logs
<details><summary>Terminal output</summary>

```
PASTE HERE OR PROVIDE LINK TO https://pastebin.com/ OR SIMILAR
```

</details>

## System specifications

<details><summary>System Details</summary>

- OS (with version, e.g., Windows 10 v2004 or macOS 10.15 (Catalina)):
- RAM:
- Python version (`python/py/python3 --version`):
- Installed modules (provide output from `pip list`):
```
PASTE HERE
```
</details>

<details><summary>LaTeX details</summary>

+ LaTeX distribution (e.g. TeX Live 2020):
+ Installed LaTeX packages:

</details>

<details><summary>FFMPEG</summary>

Output of `ffmpeg -version`:

```
PASTE HERE
```
</details>

**Comment by Archkik** [comment]
I think I may have found the point of the problem.
when using 
`
text=BraceLabel(line_1,text="Chinese")
`
tex file is like this
```
\documentclass[preview]{standalone}

\usepackage[english]{babel}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage{lmodern}
\usepackage{amsmath}
\usepackage{amssymb}
\usepackage{dsfont}
\usepackage{setspace}
\usepackage{tipa}
\usepackage{relsize}
\usepackage{textcomp}
\usepackage{mathrsfs}
\usepackage{calligra}
\usepackage{wasysym}
\usepackage{ragged2e}
\usepackage{physics}
\usepackage{xcolor}
\usepackage{microtype}
\usepackage[UTF8]{ctex}
\linespread{1}

\begin{document}

\begin{align*}
chinese
\end{align*}

\end{document}
```
and the result is correct. So on this basis, I modified the "Chinese" to "chinese中文版"

the MiKTex console will output 
```
This is XeTeX, Version 3.141592653-2.6-0.999995 (MiKTeX 23.4) (preloaded format=xelatex.fmt)
 restricted \write18 enabled.
entering extended mode
(8581c9c711b1f36b.tex
LaTeX2e <2022-11-01> patch level 1
L3 programming layer <2023-03-30>
(D:\MiKTeX\tex/latex/standalone\standalone.cls
Document Class: standalone 2022/10/10 v1.3b Class to compile TeX sub-files stan
dalone
(D:\MiKTeX\tex/latex/tools\shellesc.sty)
(D:\MiKTeX\tex/generic/iftex\ifluatex.sty
(D:\MiKTeX\tex/generic/iftex\iftex.sty))
(D:\MiKTeX\tex/latex/xkeyval\xkeyval.sty
(D:\MiKTeX\tex/generic/xkeyval\xkeyval.tex
(D:\MiKTeX\tex/generic/xkeyval\xkvutils.tex
(D:\MiKTeX\tex/generic/xkeyval\keyval.tex))))
(D:\MiKTeX\tex/latex/standalone\standalone.cfg)
(D:\MiKTeX\tex/latex/base\article.cls
Document Class: article 2022/07/02 v1.4n Standard LaTeX document class
(D:\MiKTeX\tex/latex/base\size10.clo)) (D:\MiKTeX\tex/latex/preview\preview.sty
(D:\MiKTeX\tex/latex/luatex85\luatex85.sty)
(D:\MiKTeX\tex/latex/preview\prtightpage.def)))
(D:\MiKTeX\tex/generic/babel\babel.sty (D:\MiKTeX\tex/generic/babel\xebabel.def
)
*************************************
* Local config file bblopts.cfg used
*
(D:\MiKTeX\tex/latex/arabi\bblopts.cfg)
(D:\MiKTeX\tex/latex/babel-english\english.ldf))
(D:\MiKTeX\tex/generic/babel/locale/en\babel-english.tex)
(D:\MiKTeX\tex/latex/base\inputenc.sty

Package inputenc Warning: inputenc package ignored with utf8 based engines.

) (D:\MiKTeX\tex/latex/base\fontenc.sty (D:\MiKTeX\tex/latex/lm\t1lmr.fd))
(D:\MiKTeX\tex/latex/lm\lmodern.sty) (D:\MiKTeX\tex/latex/amsmath\amsmath.sty
For additional information on amsmath, use the `?' option.
(D:\MiKTeX\tex/latex/amsmath\amstext.sty
(D:\MiKTeX\tex/latex/amsmath\amsgen.sty))
(D:\MiKTeX\tex/latex/amsmath\amsbsy.sty)
(D:\MiKTeX\tex/latex/amsmath\amsopn.sty))
(D:\MiKTeX\tex/latex/amsfonts\amssymb.sty
(D:\MiKTeX\tex/latex/amsfonts\amsfonts.sty))
(D:\MiKTeX\tex/latex/doublestroke\dsfont.sty)
(D:\MiKTeX\tex/latex/setspace\setspace.sty) (D:\MiKTeX\tex/latex/tipa\tipa.sty
(D:\MiKTeX\tex/latex/base\fontenc.sty (D:\MiKTeX\tex/latex/tipa\t3enc.def
(D:\MiKTeX\tex/latex/lm\t1lmss.fd)))) (D:\MiKTeX\tex/latex/relsize\relsize.sty)
 (D:\MiKTeX\tex/latex/base\textcomp.sty)
(D:\MiKTeX\tex/latex/jknappen\mathrsfs.sty)
(D:\MiKTeX\tex/latex/fundus-calligra\calligra.sty)
(D:\MiKTeX\tex/latex/wasysym\wasysym.sty)
(D:\MiKTeX\tex/latex/ragged2e\ragged2e.sty)
(D:\MiKTeX\tex/latex/physics\physics.sty
(D:\MiKTeX\tex/latex/l3packages/xparse\xparse.sty
(D:\MiKTeX\tex/latex/l3kernel\expl3.sty
(D:\MiKTeX\tex/latex/l3backend\l3backend-xetex.def))))
(D:\MiKTeX\tex/latex/xcolor\xcolor.sty
(D:\MiKTeX\tex/latex/graphics-cfg\color.cfg)
(D:\MiKTeX\tex/latex/graphics-def\xetex.def)
(D:\MiKTeX\tex/latex/graphics\mathcolor.ltx))
(D:\MiKTeX\tex/latex/microtype\microtype.sty
(D:\MiKTeX\tex/latex/etoolbox\etoolbox.sty)
(D:\MiKTeX\tex/latex/microtype\microtype-xetex.def)
(D:\MiKTeX\tex/latex/microtype\microtype.cfg))
(D:\MiKTeX\tex/latex/ctex\ctex.sty (D:\MiKTeX\tex/latex/ctex\ctexhook.sty)
(D:\MiKTeX\tex/latex/ctex\ctexpatch.sty) (D:\MiKTeX\tex/latex/base\fix-cm.sty
(D:\MiKTeX\tex/latex/base\ts1enc.def))
(D:\MiKTeX\tex/latex/ctex/config\ctexopts.cfg)
(D:\MiKTeX\tex/latex/ctex/engine\ctex-engine-xetex.def
(D:\MiKTeX\tex/xelatex/xecjk\xeCJK.sty
(D:\MiKTeX\tex/latex/l3packages/xtemplate\xtemplate.sty)
(D:\MiKTeX\tex/latex/fontspec\fontspec.sty
(D:\MiKTeX\tex/latex/fontspec\fontspec-xetex.sty
(D:\MiKTeX\tex/latex/base\fontenc.sty)
(D:\MiKTeX\tex/latex/fontspec\fontspec.cfg)))
(D:\MiKTeX\tex/xelatex/xecjk\xeCJK.cfg)))
(D:\MiKTeX\tex/latex/zhnumber\zhnumber.sty
(D:\MiKTeX\tex/latex/zhnumber\zhnumber-utf8.cfg))
(D:\MiKTeX\tex/latex/ctex/scheme\ctex-scheme-chinese.def
(D:\MiKTeX\tex/latex/ctex/config\ctex-name-utf8.cfg))
(D:\MiKTeX\tex/latex/tools\indentfirst.sty)
(D:\MiKTeX\tex/latex/ctex\ctex-c5size.clo)
(D:\MiKTeX\tex/latex/ctex/fontset\ctex-fontset-windows.def))
(D:\MiKTeX\tex/latex/ctex/config\ctex.cfg) (8581c9c711b1f36b.aux)
(D:\MiKTeX\tex/latex/tipa\t3cmr.fd)
Preview: Fontsize 10.53937pt
Preview: PDFoutput 1
(D:\MiKTeX\tex/latex/microtype\mt-cmr.cfg) (D:\MiKTeX\tex/latex/lm\ot1lmr.fd)
(D:\MiKTeX\tex/latex/lm\omllmm.fd) (D:\MiKTeX\tex/latex/lm\omslmsy.fd)
(D:\MiKTeX\tex/latex/lm\omxlmex.fd) (D:\MiKTeX\tex/latex/amsfonts\umsa.fd)
(D:\MiKTeX\tex/latex/microtype\mt-msa.cfg)
(D:\MiKTeX\tex/latex/amsfonts\umsb.fd)
(D:\MiKTeX\tex/latex/microtype\mt-msb.cfg)
(D:\MiKTeX\tex/latex/jknappen\ursfs.fd)

LaTeX Font Warning: Font shape `U/rsfs/m/n' in size <10.53937> not available
(Font)              size <10.95> substituted on input line 26.

(D:\MiKTeX\tex/latex/wasysym\uwasy.fd)

LaTeX Font Warning: Font shape `U/wasy/m/n' in size <10.53937> not available
(Font)              size <10.95> substituted on input line 26.

Missing character: There is no 中 in font rm-lmr10!
Missing character: There is no 文 in font rm-lmr10!
Missing character: There is no 中 in font rm-lmr10!
Missing character: There is no 文 in font rm-lmr10!
Preview: Tightpage 0 0 0 0
[1] (8581c9c711b1f36b.aux)

LaTeX Font Warning: Size substitutions with differences
(Font)              up to 0.41063pt have occurred.

 )
Output written on 8581c9c711b1f36b.pdf (1 page).
SyncTeX written on 8581c9c711b1f36b.synctex.gz.
Transcript written on 8581c9c711b1f36b.log
```
Looks like a font error.

and if  I use the tex
```py
%%manim -qm  LaTeXTemplateLibrary

class LaTeXTemplateLibrary(Scene):
    def construct(self):
        tex = Tex('你好', tex_template=TexTemplateLibrary.ctex,font_size=144)
        self.add(tex)
```
and the tex file like this:
```
\documentclass[preview]{standalone}

\usepackage[english]{babel}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage{lmodern}
\usepackage{amsmath}
\usepackage{amssymb}
\usepackage{dsfont}
\usepackage{setspace}
\usepackage{tipa}
\usepackage{relsize}
\usepackage{textcomp}
\usepackage{mathrsfs}
\usepackage{calligra}
\usepackage{wasysym}
\usepackage{ragged2e}
\usepackage{physics}
\usepackage{xcolor}
\usepackage{microtype}
\usepackage[UTF8]{ctex}
\linespread{1}

\begin{document}

**\begin{center}
你好
\end{center}**

\end{document}
```
the result is correct.

**so `{align*}` +chinese character will result in the "missing character" font error.**
I don't know latex syntax very well, so can anyone help me with this problem?

**Comment by uwezi** [comment]
> **so `{align*}` +chinese character will result in the "missing character" font error.** I don't know latex syntax very well, so can anyone help me with this problem?

even in `ctex` the Chinese characters are only supported in text mode. The labels in the `Brace()` object are typeset in math-mode. Even standard European text would end up wrongly formatted if you place it into a `MathTex()` rather than a `Tex()`.

Two solutions:
a) in `BraceLabel()` add the argument `label_constructor=Tex` in order to switch from math-mode to text-mode

b) alternatively you can place your label as `"\text{中文}"`

**Comment by Archkik** [comment]
> > **so `{align*}` +chinese character will result in the "missing character" font error.** I don't know latex syntax very well, so can anyone help me with this problem?
> 
> even in `ctex` the Chinese characters are only supported in text mode. The labels in the `Brace()` object are typeset in math-mode. Even standard European text would end up wrongly formatted if you place it into a `MathTex()` rather than a `Tex()`.
> 
> Two solutions: a) in `BraceLabel()` add the argument `label_constructor=Tex` in order to switch from math-mode to text-mode
> 
> b) alternatively you can place your label as `"\text{中文}"`
> 
> https://docs.manim.community/en/stable/reference/manim.mobject.svg.brace.BraceLabel.html?highlight=bracelabel
> 
> You are welcome to discuss questions like this on the Discord server https://discord.com/channels/581738731934056449/1019649969596153968

I have used your solution 1. It worsk well. Thank you very much.

Then I have two questions to ask: 

1. I saw in the documentation that Tex is a subclass of MathTex, so I don't think there is much difference between the two? I don't quite understand the main difference between the two modes math-mode and text-mode. Are there more reference articles?
2.  I still need to use Chinese tex in the future, such as
```py
Tex(r"$\dfrac{你好}{中文}$", font_size=28,tex_environment="center")
```
In TeXworks I use lualatex as tex_compiler to compile correctly
![Snipaste_2023-05-28_12-38-41](https://github.com/ManimCommunity/manim/assets/28565679/e0891423-7b4f-491d-8e65-b945762ddb5b)

So I specify config["tex_template"].tex_compiler="lualatex" in config
But it still makes an error in the function self._break_up_by_substrings() in manim\mobject\text\tex_mobject.py.
```py
File D:\ProgramData\anaconda\envs\ManimCommunity\Lib\site-packages\manim\mobject\text\tex_mobject.py:449, in Tex.__init__(self, arg_separator, tex_environment, *tex_strings, **kwargs)
    446 def __init__(
    447     self, *tex_strings, arg_separator="", tex_environment="center", **kwargs
    448 ):
--> 449     super().__init__(
    450         *tex_strings,
    451         arg_separator=arg_separator,
    452         tex_environment=tex_environment,
    453         **kwargs,
    454     )

File D:\ProgramData\anaconda\envs\ManimCommunity\Lib\site-packages\manim\mobject\text\tex_mobject.py:280, in MathTex.__init__(self, arg_separator, substrings_to_isolate, tex_to_color_map, tex_environment, *tex_strings, **kwargs)
    273 try:
    274     super().__init__(
    275         self.arg_separator.join(self.tex_strings),
    276         tex_environment=self.tex_environment,
    277         tex_template=self.tex_template,
    278         **kwargs,
    279     )
--> 280     self._break_up_by_substrings()
    281 except ValueError as compilation_error:
    282     if self.brace_notation_split_occurred:

File D:\ProgramData\anaconda\envs\ManimCommunity\Lib\site-packages\manim\mobject\text\tex_mobject.py:354, in MathTex._break_up_by_substrings(self)
    352     sub_tex_mob.submobjects = [VectorizedPoint()]
    353     last_submob_index = min(curr_index, len(self.submobjects) - 1)
--> 354     sub_tex_mob.move_to(self.submobjects[last_submob_index], RIGHT)
    355 else:
    356     sub_tex_mob.submobjects = self.submobjects[curr_index:new_index]

IndexError: list index out of range
```

**Comment by uwezi** [comment]
Please come over to the Discord, there is a Chinese community as well!
And it's much more convenient to answer questions there in the forum.

both `Tex()` and `MathTex()` send their arguments to the external LaTeX program to render the text. LaTeX has to principal modes of typesetting, "math mode" and "text mode". The difference between `Tex()` and `MathTex()` is whether they start in text mode or math mode (to keep it very short here). But you can switch between the two using `$...$` or `\(...\)` to invoke math mode and `\text{...}` to get to text mode.

So instead of
```python
Tex(r"$\dfrac{你好}{中文}$", font_size=28,tex_environment="center")
```
you need to do
```python
MathTex(r"\dfrac{\text{你好}}{\text{中文}}", font_size=28)
```
or
```python
Tex(r"$\dfrac{\text{你好}}{\text{中文}}$", font_size=28)
```
Even with Latin-character text one would have to use the `\text` inside a math environment (which you absolutely need for the `\frac` ) in order to get the correct typesetting of text in the nominator and denominator. 

```python
MathTex(r"\dfrac{Hello}{Chinese language}", font_size=28)
```
![Clip0001](https://github.com/ManimCommunity/manim/assets/8582807/755091b7-1b74-4dff-a0c9-6d6bba0f98ee)


```python
MathTex(r"\dfrac{\text{Hello}}{\text{Chinese language}}", font_size=28)
```
![Clip0002](https://github.com/ManimCommunity/manim/assets/8582807/9a20adf9-941e-4b58-a863-740523c17c4c)

I don't know what luatex makes differently, but if you copy the complete settings from your luatex template over to your Tex-templates in Manim, and also select luatex as the tex compiler to be used you should and will get the same result as in TexWorks, because Manim does nothing else then sending the arguments of your commands to the selected LaTeX-compiler.

[https://docs.manim.community/en/stable/faq/general.html?highlight=discord#where-can-i-find-more-resources-for-learning-manim](https://docs.manim.community/en/stable/faq/general.html?highlight=discord#where-can-i-find-more-resources-for-learning-manim)

**Comment by uwezi** [comment]
Interestingly the ctex template in Manim appears to be made for latex and not for xelatex, yet it invokes xelatex, which on my system results in metafont errors. The following code just runs fine on my system:
```python
class AcuteAngle(Scene):
    def construct(self):
        config.tex_template=TexTemplateLibrary.ctex
        config.tex_template.tex_compiler="latex"
        config.tex_template.output_format=".dvi"
        line_1=Line([-1,0,0],[1,0,0])
        text=BraceLabel(line_1,text=r"\text{中文}")
        self.add(line_1,text)
        frac =  Tex(r"$\dfrac{\text{你好}}{\text{中文}}$", font_size=50).to_edge(UP)
        self.add(frac) 
```
![image](https://github.com/ManimCommunity/manim/assets/8582807/58ace617-ecfc-47f6-8021-4b17ab7f7e8f)

**Comment by uwezi** [comment]
And now with also fonts SimHei and KeiTi installed, the script also runs with xelatex as LaTeX compiler
```python
class AcuteAngle(Scene):
    def construct(self):
        config.tex_template=TexTemplateLibrary.ctex
        line_1=Line([-1,0,0],[1,0,0])
        text=BraceLabel(line_1,text=r"\text{中文}")
        self.add(line_1,text)
        frac =  Tex(r"$\dfrac{\text{你好}}{\text{中文}}$", font_size=50).to_edge(UP)
        self.add(frac)
```
![image](https://github.com/ManimCommunity/manim/assets/8582807/c4904bb3-a882-4537-9d96-8541e9b46e58)

**Comment by Archkik** [comment]
> Interestingly the ctex template in Manim appears to be made for latex and not for xelatex, yet it invokes xelatex, which on my system results in metafont errors. The following code just runs fine on my system:
> 
> ```python
> class AcuteAngle(Scene):
>     def construct(self):
>         config.tex_template=TexTemplateLibrary.ctex
>         config.tex_template.tex_compiler="latex"
>         config.tex_template.output_format=".dvi"
>         line_1=Line([-1,0,0],[1,0,0])
>         text=BraceLabel(line_1,text=r"\text{中文}")
>         self.add(line_1,text)
>         frac =  Tex(r"$\dfrac{\text{你好}}{\text{中文}}$", font_size=50).to_edge(UP)
>         self.add(frac) 
> ```
> 
> ![image](https://user-images.githubusercontent.com/8582807/241544368-58ace617-ecfc-47f6-8021-4b17ab7f7e8f.png)

Thank you very much for your solution, it seems that I should learn more about latex. BTW I can't join you through the discord link you provided. [](https://discord.com/channels/581738731934056449/1019649969596153968) I haven't used discord before, but I think this shows that I don't have access @uwezi 
![image](https://github.com/ManimCommunity/manim/assets/28565679/902b11a3-3f3c-4146-81bb-97e38402c269)

**Comment by Archkik** [comment]
> > Interestingly the ctex template in Manim appears to be made for latex and not for xelatex, yet it invokes xelatex, which on my system results in metafont errors. The following code just runs fine on my system:
> > ```python
> > class AcuteAngle(Scene):
> >     def construct(self):
> >         config.tex_template=TexTemplateLibrary.ctex
> >         config.tex_template.tex_compiler="latex"
> >         config.tex_template.output_format=".dvi"
> >         line_1=Line([-1,0,0],[1,0,0])
> >         text=BraceLabel(line_1,text=r"\text{中文}")
> >         self.add(line_1,text)
> >         frac =  Tex(r"$\dfrac{\text{你好}}{\text{中文}}$", font_size=50).to_edge(UP)
> >         self.add(frac) 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ![image](https://user-images.githubusercontent.com/8582807/241544368-58ace617-ecfc-47f6-8021-4b17ab7f7e8f.png)
> 
> Thank you very much for your solution, it seems that I should learn more about latex. BTW I can't join you through the discord link you provided. I haven't used discord before, but I think this shows that I don't have access @uwezi ![image](https://user-images.githubusercontent.com/28565679/241698477-902b11a3-3f3c-4146-81bb-97e38402c269.png)

I have actually found the link in the Manim documentation, so there's no need for you to worry about it anymore.
