### ISSUE TITLE
Chinese/Japanese text cannot be presented

### ISSUE THREAD

**Issue by wangjia184** [ManimCommunity/manim#3256]
## Description of bug / unexpected behavior

Run the example code of multiple-font and it ended with following screenshot
![image](https://github.com/ManimCommunity/manim/assets/2765840/024b58ca-56cc-498d-89f6-d11bf8cf820a)

## Expected behavior

It should be like this one:
![image](https://github.com/ManimCommunity/manim/assets/2765840/4a18d46a-7a0b-4182-b81f-9c1a359fbab9)

## How to reproduce the issue

Manim Community v0.17.3, starting it using docker
```
docker run -it -p 8888:8888 -v "G:\\projects\\manim:/manim"  manimcommunity/manim jupyter lab --ip=0.0.0.0
```

Then run the multiple-font example code from https://docs.manim.community/en/stable/reference/manim.mobject.text.text_mobject.Text.html#multiplefonts

```py
%%manim -ql MultipleFonts 

class MultipleFonts(Scene):
    def construct(self):
        morning = Text("வணக்கம்", font="sans-serif")
        japanese = Text(
            "日本へようこそ", t2c={"日本": BLUE}
        )  # works same as ``Text``.
        mess = Text("Multi-Language", weight=BOLD)
        russ = Text("Здравствуйте मस नम म ", font="sans-serif")
        hin = Text("नमस्ते", font="sans-serif")
        arb = Text(
            "صباح الخير \n تشرفت بمقابلتك", font="sans-serif"
        )  # don't mix RTL and LTR languages nothing shows up then ;-)
        chinese = Text("臂猿「黛比」帶著孩子", font="sans-serif")
        self.add(morning, japanese, mess, russ, hin, arb, chinese)
        for i,mobj in enumerate(self.mobjects):
            mobj.shift(DOWN*(i-3))
```

## Others

There is no `TEX_USE_CTEX = True` in constants.py any more.

This [issue ](https://github.com/3b1b/manim/issues/209) from 3b1b says the following config could fix it. But seems that is not available to community edition? 

```
tex:
  executable: xelatex -no-pdf
  intermediate_filetype: xdv
  template_file: ctex_template.tex
  text_to_replace: '[tex_expression]'
```

**Comment by uwezi** [comment]
The example you use does use `Text()` and not `Tex()` therefore "ctex" has no relevance here.

`Text()` uses your system's fonts for rendering - and it seems that the font used by default is lacking CJK-characters. Not all system fonts contain a full set of unicode characters. I don't know which fonts are available inside your Docker environment.

In this parallel discussion you can see that neither `Text()` nor `Tex()` have a principle problem with CJK-fonts:
[BraceLabel text can not use chinese #3254 ](https://github.com/ManimCommunity/manim/issues/3254)

Come over to Discord - there are both Japanese and Chinese communities which will probably be able to help you:
[Where can I find more resources for learning Manim?](https://docs.manim.community/en/stable/faq/general.html?highlight=discord#where-can-i-find-more-resources-for-learning-manim)

![image](https://github.com/ManimCommunity/manim/assets/8582807/f840bb21-0bae-46b4-ae82-ccf195b4d6e1)

On my system without fine tuning the fonts, at least Japanese, Cyrillic, Arabic and Chinese work with the fonts I have installed
![image](https://github.com/ManimCommunity/manim/assets/8582807/64587095-08dd-4063-8775-1847926c0bb3)

**Comment by wangjia184** [comment]
Thanks @uwezi , I solved this problem by installing Chinese font into docker image

```
FROM manimcommunity/manim:v0.17.3

USER root
RUN apt-get install -y fontconfig fonts-wqy-zenhei
RUN fc-cache -fv

USER manimuser
```


First installs fontconfig (https://packages.debian.org/sid/fontconfig) and the Chinese Fonts (https://packages.debian.org/sid/fonts/). And then rebuilds the font cache
