### ISSUE TITLE
Review added

### ISSUE THREAD

**Issue by repo-reviews** [ManimCommunity/manim#3269]
### Thank you for building **manim**!

@pingwie created a review titled:

*Manim community review*

on [repo-reviews.github.io](https://repo-reviews.github.io) to share their experience using **manim**.

[link to review](https://repo-reviews.github.io//reviews/2023-06-22_pingwie_manimcommunity_manim)

If you would like to help your users share their experiences using your repo, add a [badge](https://github.com/repo-reviews/repo-reviews.github.io#add-badges) to your README.md.

I hope these learnings help your users **increase their productivity**.

--
Please be kind,
I’m a human!

**Comment by MrDiver** [comment]
🤔 i am not quite sure for which reason you created this issue. +I would recommend using WSL on windows and on Linux there shouldn't even be a problem in the first place. Sadly i can't say anything about Mac because personally i don't use it.
