### ISSUE TITLE
Is pip3 defaulting to an enhanced security model?

### ISSUE THREAD

**Issue by osj1961** [ManimCommunity/manim#3271]
#### Preliminaries

- [ X] I have followed the latest version of the
      [installation instructions](https://docs.manim.community/en/stable/installation.html).
- [ X] I have checked the [installation FAQ](https://docs.manim.community/en/stable/faq/installation.html) and my problem is either not mentioned there,
      or the solution given there does not help.

## Description of error

After installing dependencies, "pip3 install manim" (run in the top level of the git repo)
gives an error:

> error: externally-managed-environment
> 
> × This environment is externally managed
> ╰─> To install Python packages system-wide, try apt install
>     python3-xyz, where xyz is the package you are trying to
>     install.
>     
>     If you wish to install a non-Debian-packaged Python package,
>     create a virtual environment using python3 -m venv path/to/venv.
>     Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
>     sure you have python3-full installed.
>     
>     If you wish to install a non-Debian packaged Python application,
>     it may be easiest to use pipx install xyz, which will manage a
>     virtual environment for you. Make sure you have pipx installed.
>     
>     See /usr/share/doc/python3.11/README.venv for more information.
> 
> note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
> hint: See PEP 668 for the detailed specification.
> 

I went ahead and passed in the --break-system-packages option and the install went smoothly from there.

## System specifications

<details><summary>System Details</summary>

- OS  linux (Ubuntu 23.04)
- RAM: 32.0 GiB
- Python version (`python/py/python3 --version`): 3.11.2
- Installed modules (provide output from `pip list`):
```
Package                Version
---------------------- --------------
bcrypt                 3.2.2
blinker                1.5
Brlapi                 0.8.4
certifi                2022.9.24
chardet                5.1.0
click                  8.1.3
click-default-group    1.2.2
cloup                  0.13.1
colorama               0.4.6
colour                 0.1.5
command-not-found      0.3
cryptography           38.0.4
cupshelpers            1.0
dbus-python            1.3.2
decorator              5.1.1
defer                  1.0.6
distro                 1.8.0
distro-info            1.5
duplicity              0.8.22
fasteners              0.17.3
future                 0.18.2
glcontext              2.3.7
httplib2               0.20.4
idna                   3.3
importlib-metadata     4.12.0
isosurfaces            0.1.0
jaraco.classes         3.2.1
jeepney                0.8.0
kazam                  1.4.5
keyring                23.9.3
language-selector      0.1
launchpadlib           1.11.0
lazr.restfulclient     0.14.5
lazr.uri               1.0.6
lockfile               0.12.2
louis                  3.24.0
Mako                   1.2.4.dev0
manim                  0.17.3
ManimPango             0.4.3
mapbox-earcut          1.0.1
markdown-it-py         2.1.0
MarkupSafe             2.1.2
mdurl                  0.1.2
moderngl               5.8.2
moderngl-window        2.4.4
monotonic              1.6
more-itertools         8.10.0
multipledispatch       1.0.0
netifaces              0.11.0
networkx               2.8.8
numpy                  1.25.0
oauthlib               3.2.2
olefile                0.46
paramiko               2.12.0
pexpect                4.8.0
Pillow                 9.4.0
pip                    23.0.1
ptyprocess             0.7.0
pycairo                1.24.0
pycups                 2.0.1
pydub                  0.25.1
pyglet                 2.0.8
Pygments               2.14.0
PyGObject              3.44.1
PyJWT                  2.6.0
PyNaCl                 1.5.0
pyparsing              3.0.9
pyrr                   0.10.3
python-apt             2.5.3+ubuntu1
python-dateutil        2.8.2
python-debian          0.1.49+ubuntu2
pyxdg                  0.28
PyYAML                 6.0
reportlab              3.6.12
requests               2.28.1
rich                   13.3.1
scipy                  1.11.1
screeninfo             0.8.1
SecretStorage          3.3.3
setuptools             66.1.1
six                    1.16.0
skia-pathops           0.7.4
srt                    3.5.3
svgelements            1.9.5
systemd-python         235
tqdm                   4.65.0
ubuntu-advantage-tools 8001
ubuntu-drivers-common  0.0.0
ufw                    0.36.1
unattended-upgrades    0.1
urllib3                1.26.12
usb-creator            0.3.16
wadllib                1.3.6
watchdog               2.3.1
wheel                  0.38.4
xdg                    5
xkit                   0.0.0
zipp                   1.0.0
```
</details>

**Comment by MrDiver** [comment]
I am note quite sure why you would clone the repo and then use `pip3 install manim` that basically defeats the purpose of having the repo in the first place. So either follow the instructions on the [contributions page](https://docs.manim.community/en/stable/contributing.html) how to setup your environment if you want to use the git version or just install manim with `pip`.

Now to your problem: Your system aka Ubuntu/Debian doesn't allow you to install packages over pip anymore, i think this might've caused breakage in older systems so now the default will tell you that you need to install a package over your systems package manager. As far as i remember we do not provide such a package, so the way to go for you would be creating a virtual environment with a tool of your choice -> `venv`,`virtualenv`,`anaconda`,`miniconda`,`poetry` or whichever one you like best and install the manim package there so it doesn't affect your system packages which might cause a lot of stupid things to happen especially on ubuntu.
