### ISSUE TITLE
Set up tests with PyTest and/or Travis

### ISSUE THREAD

**Issue by kilacoda** [ManimCommunity/manim#33]
As the title says, set up tests with PyTest and/or Travis, so that we can create the workflow.

Tests may basically include a `Scene` in which the Mobject in question is `self.add`ed/`self.play`ed into the scene, rendered at `-s` or `-l`.

**Comment by leotrs** [comment]
I think one thing to discuss is which framework to use for testing. I am partial to [pytest](https://docs.pytest.org/en/latest/).

A different issue is how to automate them. I like Travis-CI for this.

A different issue is what the tests will test for. I agree that for now we should target to run some boilerplate manim code without errors. We can check for correctness later (see #34).

**Comment by leotrs** [comment]
Per #43, once we setup Travis, we will also set up pylint and black.

We still need to choose a testing framework. I suggest [pytest](https://docs.pytest.org/en/latest/) (again).

**Comment by leotrs** [comment]
#86 closed this.
