### ISSUE TITLE
MathTex uses Chinese to report errors

### ISSUE THREAD

**Issue by HenYu-Yo** [ManimCommunity/manim#3300]
## Description of bug / unexpected behavior

I use MathTex to draw Chinese and I get the following error after running:
UnicodeDecodeError: 'gbk' codec can't decode byte 0xad in position 152: illegal multibytesequence
Traceback:
╭────────────────────────── Traceback (most recent call last) ──────────────────────────╮
│ E:\anaconda\envs\manim\lib\site-packages\manim\cli\render\commands.py:115 in render   │
│                                                                                       │
│   112 │   │   │   try:                                                                │
│   113 │   │   │   │   with tempconfig({}):                                            │
│   114 │   │   │   │   │   scene = SceneClass()                                        │
│ ❱ 115 │   │   │   │   │   scene.render()                                              │
│   116 │   │   │   except Exception:                                                   │
│   117 │   │   │   │   error_console.print_exception()                                 │
│   118 │   │   │   │   sys.exit(1)                                                     │
│                                                                                       │
│ E:\anaconda\envs\manim\lib\site-packages\manim\scene\scene.py:223 in render           │
│                                                                                       │
│    220 │   │   """                                                                    │
│    221 │   │   self.setup()                                                           │
│    222 │   │   try:                                                                   │
│ ❱  223 │   │   │   self.construct()                                                   │
│    224 │   │   except EndSceneEarlyException:                                         │
│    225 │   │   │   pass                                                               │
│    226 │   │   except RerunSceneException as e:                                       │
│                                                                                       │
│ F:\Math\Project\scene.py:8 in construct                                               │
│                                                                                       │
│    5 │   def construct(self):                                                         │
│    6 │   │                                                                            │
│    7 │   │   t1 = MathTex(r'1 + 2 + 3 + \cdots = -\frac{1}{12}')                      │
│ ❱  8 │   │   t1 = MathTex(r"\mbox{自然数之和}(1 + 2 + 3 + \cdots)\mbox{等于}( )")     │
│    9 │   │   self.play(Write(t1))                                                     │
│   10 │   │   self.wait(1)                                                             │
│   11                                                                                  │
│                                                                                       │
│ E:\anaconda\envs\manim\lib\site-packages\manim\mobject\text\tex_mobject.py:295 in     │
│ __init__                                                                              │
│                                                                                       │
│   292 │   │   │   │   │   │   """,                                                    │
│   293 │   │   │   │   │   ),                                                          │
│   294 │   │   │   │   )                                                               │
│ ❱ 295 │   │   │   raise compilation_error                                             │
│   296 │   │   self.set_color_by_tex_to_color_map(self.tex_to_color_map)               │
│   297 │   │                                                                           │
│   298 │   │   if self.organize_left_to_right:                                         │
│                                                                                       │
│ E:\anaconda\envs\manim\lib\site-packages\manim\mobject\text\tex_mobject.py:274 in     │
│ __init__                                                                              │
│                                                                                       │
│   271 │   │   self.brace_notation_split_occurred = False                              │
│   272 │   │   self.tex_strings = self._break_up_tex_strings(tex_strings)              │
│   273 │   │   try:                                                                    │
│ ❱ 274 │   │   │   super().__init__(                                                   │
│   275 │   │   │   │   self.arg_separator.join(self.tex_strings),                      │
│   276 │   │   │   │   tex_environment=self.tex_environment,                           │
│   277 │   │   │   │   tex_template=self.tex_template,                                 │
│                                                                                       │
│ E:\anaconda\envs\manim\lib\site-packages\manim\mobject\text\tex_mobject.py:83 in      │
│ __init__                                                                              │
│                                                                                       │
│    80 │   │                                                                           │
│    81 │   │   assert isinstance(tex_string, str)                                      │
│    82 │   │   self.tex_string = tex_string                                            │
│ ❱  83 │   │   file_name = tex_to_svg_file(                                            │
│    84 │   │   │   self._get_modified_expression(tex_string),                          │
│    85 │   │   │   environment=self.tex_environment,                                   │
│    86 │   │   │   tex_template=self.tex_template,                                     │
│                                                                                       │
│ E:\anaconda\envs\manim\lib\site-packages\manim\utils\tex_file_writing.py:54 in        │
│ tex_to_svg_file                                                                       │
│                                                                                       │
│    51 │   if tex_template is None:                                                    │
│    52 │   │   tex_template = config["tex_template"]                                   │
│    53 │   tex_file = generate_tex_file(expression, environment, tex_template)         │
│ ❱  54 │   dvi_file = compile_tex(                                                     │
│    55 │   │   tex_file,                                                               │
│    56 │   │   tex_template.tex_compiler,                                              │
│    57 │   │   tex_template.output_format,                                             │
│                                                                                       │
│ E:\anaconda\envs\manim\lib\site-packages\manim\utils\tex_file_writing.py:200 in       │
│ compile_tex                                                                           │
│                                                                                       │
│   197 │   │   exit_code = os.system(command)                                          │
│   198 │   │   if exit_code != 0:                                                      │
│   199 │   │   │   log_file = tex_file.with_suffix(".log")                             │
│ ❱ 200 │   │   │   print_all_tex_errors(log_file, tex_compiler, tex_file)              │
│   201 │   │   │   raise ValueError(                                                   │
│   202 │   │   │   │   f"{tex_compiler} error converting to"                           │
│   203 │   │   │   │   f" {output_format[1:]}. See log output above or"                │
│                                                                                       │
│ E:\anaconda\envs\manim\lib\site-packages\manim\utils\tex_file_writing.py:267 in       │
│ print_all_tex_errors                                                                  │
│                                                                                       │
│   264 │   ]                                                                           │
│   265 │   if error_indices:                                                           │
│   266 │   │   with tex_file.open() as f:                                              │
│ ❱ 267 │   │   │   tex = f.readlines()                                                 │
│   268 │   │   for error_index in error_indices:                                       │
│   269 │   │   │   print_tex_error(tex_compilation_log, error_index, tex)              │
│   270                                                                                 │
╰───────────────────────────────────────────────────────────────────────────────────────╯
UnicodeDecodeError: 'gbk' codec can't decode byte 0xaa in position 158: illegal multibyte
sequence

(manim) F:\Math\Project>manim -pql scene.py wtext
Manim Community v0.17.3

[07/19/23 21:24:46] INFO     Writing 中文 to                       tex_file_writing.py:97
                             media\Tex\74a90a46abcce696.tex        
╭────────────────────────── Traceback (most recent call last) ──────────────────────────╮
│ E:\anaconda\envs\manim\lib\site-packages\manim\cli\render\commands.py:115 in render   │
│                                                                                       │
│   112 │   │   │   try:                                                                │
│   113 │   │   │   │   with tempconfig({}):                                            │
│   114 │   │   │   │   │   scene = SceneClass()                                        │
│ ❱ 115 │   │   │   │   │   scene.render()                                              │
│   116 │   │   │   except Exception:                                                   │
│   117 │   │   │   │   error_console.print_exception()                                 │
│   118 │   │   │   │   sys.exit(1)                                                     │
│                                                                                       │
│ E:\anaconda\envs\manim\lib\site-packages\manim\scene\scene.py:223 in render           │
│                                                                                       │
│    220 │   │   """                                                                    │
│    221 │   │   self.setup()                                                           │
│    222 │   │   try:                                                                   │
│ ❱  223 │   │   │   self.construct()                                                   │
│    224 │   │   except EndSceneEarlyException:                                         │
│    225 │   │   │   pass                                                               │
│    226 │   │   except RerunSceneException as e:                                       │
│                                                                                       │
│ F:\Math\Project\scene.py:6 in construct                                               │
│                                                                                       │
│   3 class wtext(Scene):                                                               │
│   4 │   def construct(self):                                                          │
│   5 │   │                                                                             │
│ ❱ 6 │   │   t1 = MathTex(r"中文")                                                     │
│   7 │   │   self.play(Write(t1))                                                      │
│   8 │   │   self.wait()                                                               │
│   9                                                                                   │
│                                                                                       │
│ E:\anaconda\envs\manim\lib\site-packages\manim\mobject\text\tex_mobject.py:295 in     │
│ __init__                                                                              │
│                                                                                       │
│   292 │   │   │   │   │   │   """,                                                    │
│   293 │   │   │   │   │   ),                                                          │
│   294 │   │   │   │   )                                                               │
│ ❱ 295 │   │   │   raise compilation_error                                             │
│   296 │   │   self.set_color_by_tex_to_color_map(self.tex_to_color_map)               │
│   297 │   │                                                                           │
│   298 │   │   if self.organize_left_to_right:                                         │
│                                                                                       │
│ E:\anaconda\envs\manim\lib\site-packages\manim\mobject\text\tex_mobject.py:274 in     │
│ __init__                                                                              │
│                                                                                       │
│   271 │   │   self.brace_notation_split_occurred = False                              │
│   272 │   │   self.tex_strings = self._break_up_tex_strings(tex_strings)              │
│   273 │   │   try:                                                                    │
│ ❱ 274 │   │   │   super().__init__(                                                   │
│   275 │   │   │   │   self.arg_separator.join(self.tex_strings),                      │
│   276 │   │   │   │   tex_environment=self.tex_environment,                           │
│   277 │   │   │   │   tex_template=self.tex_template,                                 │
│                                                                                       │
│ E:\anaconda\envs\manim\lib\site-packages\manim\mobject\text\tex_mobject.py:83 in      │
│ __init__                                                                              │
│                                                                                       │
│    80 │   │                                                                           │
│    81 │   │   assert isinstance(tex_string, str)                                      │
│    82 │   │   self.tex_string = tex_string                                            │
│ ❱  83 │   │   file_name = tex_to_svg_file(                                            │
│    84 │   │   │   self._get_modified_expression(tex_string),                          │
│    85 │   │   │   environment=self.tex_environment,                                   │
│    86 │   │   │   tex_template=self.tex_template,                                     │
│                                                                                       │
│ E:\anaconda\envs\manim\lib\site-packages\manim\utils\tex_file_writing.py:54 in        │
│ tex_to_svg_file                                                                       │
│                                                                                       │
│    51 │   if tex_template is None:                                                    │
│    52 │   │   tex_template = config["tex_template"]                                   │
│    53 │   tex_file = generate_tex_file(expression, environment, tex_template)         │
│ ❱  54 │   dvi_file = compile_tex(                                                     │
│    55 │   │   tex_file,                                                               │
│    56 │   │   tex_template.tex_compiler,                                              │
│    57 │   │   tex_template.output_format,                                             │
│                                                                                       │
│ E:\anaconda\envs\manim\lib\site-packages\manim\utils\tex_file_writing.py:200 in       │
│ compile_tex                                                                           │
│                                                                                       │
│   197 │   │   exit_code = os.system(command)                                          │
│   198 │   │   if exit_code != 0:                                                      │
│   199 │   │   │   log_file = tex_file.with_suffix(".log")                             │
│ ❱ 200 │   │   │   print_all_tex_errors(log_file, tex_compiler, tex_file)              │
│   201 │   │   │   raise ValueError(                                                   │
│   202 │   │   │   │   f"{tex_compiler} error converting to"                           │
│   203 │   │   │   │   f" {output_format[1:]}. See log output above or"                │
│                                                                                       │
│ E:\anaconda\envs\manim\lib\site-packages\manim\utils\tex_file_writing.py:267 in       │
│ print_all_tex_errors                                                                  │
│                                                                                       │
│   264 │   ]                                                                           │
│   265 │   if error_indices:                                                           │
│   266 │   │   with tex_file.open() as f:                                              │
│ ❱ 267 │   │   │   tex = f.readlines()                                                 │
│   268 │   │   for error_index in error_indices:                                       ││   269 │   │   │   print_tex_error(tex_compilation_log, error_index, tex)              ││   270                                                                                 │╰───────────────────────────────────────────────────────────────────────────────────────╯

## Expected behavior

Write out Chinese

## How to reproduce the issue

<details><summary>Code for reproducing the problem</summary>

from manim import *

class wtext(Scene):
    def construct(self):
        
        t1 = MathTex(r"中文")
        self.play(Write(t1))
        self.wait()

</details>

## Additional media files

<details><summary>Images/GIFs</summary>

[74a90a46abcce696.log](https://github.com/ManimCommunity/manim/files/12095508/74a90a46abcce696.log)
![image](https://github.com/ManimCommunity/manim/assets/116161568/3bdf5fc3-bc97-4e6c-b256-b3d22491d008)
![image](https://github.com/ManimCommunity/manim/assets/116161568/601ebc4d-28fa-438f-8c2c-69e6cc8505e1)

</details>

## Logs
<details><summary>Terminal output</summary>

```
PASTE HERE OR PROVIDE LINK TO https://pastebin.com/ OR SIMILAR
```

                             media\Tex\74a90a46abcce696.tex        
╭────────────────────────── Traceback (most recent call last) ──────────────────────────╮
│ E:\anaconda\envs\manim\lib\site-packages\manim\cli\render\commands.py:115 in render   │
│                                                                                       │
│   112 │   │   │   try:                                                                │
│   113 │   │   │   │   with tempconfig({}):                                            │
│   114 │   │   │   │   │   scene = SceneClass()                                        │
│ ❱ 115 │   │   │   │   │   scene.render()                                              │
│   116 │   │   │   except Exception:                                                   │
│   117 │   │   │   │   error_console.print_exception()                                 │
│   118 │   │   │   │   sys.exit(1)                                                     │
│                                                                                       │
│ E:\anaconda\envs\manim\lib\site-packages\manim\scene\scene.py:223 in render           │
│                                                                                       │
│    220 │   │   """                                                                    │
│    221 │   │   self.setup()                                                           │
│    222 │   │   try:                                                                   │
│ ❱  223 │   │   │   self.construct()                                                   │
│    224 │   │   except EndSceneEarlyException:                                         │
│    225 │   │   │   pass                                                               │
│    226 │   │   except RerunSceneException as e:                                       │
│                                                                                       │
│ F:\Math\Project\scene.py:6 in construct                                               │
│                                                                                       │
│   3 class wtext(Scene):                                                               │
│   4 │   def construct(self):                                                          │
│   5 │   │                                                                             │
│ ❱ 6 │   │   t1 = MathTex(r"中文")                                                     │
│   7 │   │   self.play(Write(t1))                                                      │
│   8 │   │   self.wait()                                                               │
│   9                                                                                   │
│                                                                                       │
│ E:\anaconda\envs\manim\lib\site-packages\manim\mobject\text\tex_mobject.py:295 in     │
│ __init__                                                                              │
│                                                                                       │
│   292 │   │   │   │   │   │   """,                                                    │
│   293 │   │   │   │   │   ),                                                          │
│   294 │   │   │   │   )                                                               │
│ ❱ 295 │   │   │   raise compilation_error                                             │
│   296 │   │   self.set_color_by_tex_to_color_map(self.tex_to_color_map)               │
│   297 │   │                                                                           │
│   298 │   │   if self.organize_left_to_right:                                         │
│                                                                                       │
│ E:\anaconda\envs\manim\lib\site-packages\manim\mobject\text\tex_mobject.py:274 in     │
│ __init__                                                                              │
│                                                                                       │
│   271 │   │   self.brace_notation_split_occurred = False                              │
│   272 │   │   self.tex_strings = self._break_up_tex_strings(tex_strings)              │
│   273 │   │   try:                                                                    │
│ ❱ 274 │   │   │   super().__init__(                                                   │
│   275 │   │   │   │   self.arg_separator.join(self.tex_strings),                      │
│   276 │   │   │   │   tex_environment=self.tex_environment,                           │
│   277 │   │   │   │   tex_template=self.tex_template,                                 │
│                                                                                       │
│ E:\anaconda\envs\manim\lib\site-packages\manim\mobject\text\tex_mobject.py:83 in      │
│ __init__                                                                              │
│                                                                                       │
│    80 │   │                                                                           │
│    81 │   │   assert isinstance(tex_string, str)                                      │
│    82 │   │   self.tex_string = tex_string                                            │
│ ❱  83 │   │   file_name = tex_to_svg_file(                                            │
│    84 │   │   │   self._get_modified_expression(tex_string),                          │
│    85 │   │   │   environment=self.tex_environment,                                   │
│    86 │   │   │   tex_template=self.tex_template,                                     │
│                                                                                       │
│ E:\anaconda\envs\manim\lib\site-packages\manim\utils\tex_file_writing.py:54 in        │
│ tex_to_svg_file                                                                       │
│                                                                                       │
│    51 │   if tex_template is None:                                                    │
│    52 │   │   tex_template = config["tex_template"]                                   │
│    53 │   tex_file = generate_tex_file(expression, environment, tex_template)         │
│ ❱  54 │   dvi_file = compile_tex(                                                     │
│    55 │   │   tex_file,                                                               │
│    56 │   │   tex_template.tex_compiler,                                              │
│    57 │   │   tex_template.output_format,                                             │
│                                                                                       │
│ E:\anaconda\envs\manim\lib\site-packages\manim\utils\tex_file_writing.py:200 in       │
│ compile_tex                                                                           │
│                                                                                       │
│   197 │   │   exit_code = os.system(command)                                          │
│   198 │   │   if exit_code != 0:                                                      │
│   199 │   │   │   log_file = tex_file.with_suffix(".log")                             │
│ ❱ 200 │   │   │   print_all_tex_errors(log_file, tex_compiler, tex_file)              │
│   201 │   │   │   raise ValueError(                                                   │
│   202 │   │   │   │   f"{tex_compiler} error converting to"                           │
│   203 │   │   │   │   f" {output_format[1:]}. See log output above or"                │
│                                                                                       │
│ E:\anaconda\envs\manim\lib\site-packages\manim\utils\tex_file_writing.py:267 in       │
│ print_all_tex_errors                                                                  │
│                                                                                       │
│   264 │   ]                                                                           │
│   265 │   if error_indices:                                                           │
│   266 │   │   with tex_file.open() as f:                                              │
│ ❱ 267 │   │   │   tex = f.readlines()                                                 │
│   268 │   │   for error_index in error_indices:                                       │
│   269 │   │   │   print_tex_error(tex_compilation_log, error_index, tex)              │
│   270                                                                                 │
╰───────────────────────────────────────────────────────────────────────────────────────╯
UnicodeDecodeError: 'gbk' codec can't decode byte 0xad in position 152: illegal multibyte
sequence

(manim) F:\Math\Project>manim -pql -v DEBUG scene.py wtext 
Manim Community v0.17.3

╭────────────────────────── Traceback (most recent call last) ──────────────────────────╮
│ E:\anaconda\envs\manim\lib\site-packages\manim\cli\render\commands.py:115 in render   │
│                                                                                       │
│   112 │   │   │   try:                                                                │
│   113 │   │   │   │   with tempconfig({}):                                            │
│   114 │   │   │   │   │   scene = SceneClass()                                        │
│ ❱ 115 │   │   │   │   │   scene.render()                                              │
│   116 │   │   │   except Exception:                                                   │
│   117 │   │   │   │   error_console.print_exception()                                 │
│   118 │   │   │   │   sys.exit(1)                                                     │
│                                                                                       │
│ E:\anaconda\envs\manim\lib\site-packages\manim\scene\scene.py:223 in render           │
│                                                                                       │
│    220 │   │   """                                                                    │
│    221 │   │   self.setup()                                                           │
│    222 │   │   try:                                                                   │
│ ❱  223 │   │   │   self.construct()                                                   │
│    224 │   │   except EndSceneEarlyException:                                         │
│    225 │   │   │   pass                                                               │
│    226 │   │   except RerunSceneException as e:                                       │
│                                                                                       │
│ F:\Math\Project\scene.py:6 in construct                                               │
│                                                                                       │
│   3 class wtext(Scene):                                                               │
│   4 │   def construct(self):                                                          │
│   5 │   │                                                                             │
│ ❱ 6 │   │   t1 = MathTex(r"中文")                                                     │
│   7 │   │   self.play(Write(t1))                                                      │
│   8 │   │   self.wait()                                                               │
│   9                                                                                   │
│                                                                                       │
│ E:\anaconda\envs\manim\lib\site-packages\manim\mobject\text\tex_mobject.py:295 in     │
│ __init__                                                                              │
│                                                                                       │
│   292 │   │   │   │   │   │   """,                                                    │
│   293 │   │   │   │   │   ),                                                          │
│   294 │   │   │   │   )                                                               │
│ ❱ 295 │   │   │   raise compilation_error                                             │
│   296 │   │   self.set_color_by_tex_to_color_map(self.tex_to_color_map)               │
│   297 │   │                                                                           │
│   298 │   │   if self.organize_left_to_right:                                         │
│                                                                                       │
│ E:\anaconda\envs\manim\lib\site-packages\manim\mobject\text\tex_mobject.py:274 in     │
│ __init__                                                                              │
│                                                                                       │
│   271 │   │   self.brace_notation_split_occurred = False                              │
│   272 │   │   self.tex_strings = self._break_up_tex_strings(tex_strings)              │
│   273 │   │   try:                                                                    │
│ ❱ 274 │   │   │   super().__init__(                                                   │
│   275 │   │   │   │   self.arg_separator.join(self.tex_strings),                      │
│   276 │   │   │   │   tex_environment=self.tex_environment,                           │
│   277 │   │   │   │   tex_template=self.tex_template,                                 │
│                                                                                       │
│ E:\anaconda\envs\manim\lib\site-packages\manim\mobject\text\tex_mobject.py:83 in      │
│ __init__                                                                              │
│                                                                                       │
│    80 │   │                                                                           │
│    81 │   │   assert isinstance(tex_string, str)                                      │
│    82 │   │   self.tex_string = tex_string                                            │
│ ❱  83 │   │   file_name = tex_to_svg_file(                                            │
│    84 │   │   │   self._get_modified_expression(tex_string),                          │
│    85 │   │   │   environment=self.tex_environment,                                   │
│    86 │   │   │   tex_template=self.tex_template,                                     │
│                                                                                       │
│ E:\anaconda\envs\manim\lib\site-packages\manim\utils\tex_file_writing.py:54 in        │
│ tex_to_svg_file                                                                       │
│                                                                                       │
│    51 │   if tex_template is None:                                                    │
│    52 │   │   tex_template = config["tex_template"]                                   │
│    53 │   tex_file = generate_tex_file(expression, environment, tex_template)         │
│ ❱  54 │   dvi_file = compile_tex(                                                     │
│    55 │   │   tex_file,                                                               │
│    56 │   │   tex_template.tex_compiler,                                              │
│    57 │   │   tex_template.output_format,                                             │
│                                                                                       │
│ E:\anaconda\envs\manim\lib\site-packages\manim\utils\tex_file_writing.py:200 in       │
│ compile_tex                                                                           │
│                                                                                       │
│   197 │   │   exit_code = os.system(command)                                          │
│   198 │   │   if exit_code != 0:                                                      │
│   199 │   │   │   log_file = tex_file.with_suffix(".log")                             │
│ ❱ 200 │   │   │   print_all_tex_errors(log_file, tex_compiler, tex_file)              │
│   201 │   │   │   raise ValueError(                                                   │
│   202 │   │   │   │   f"{tex_compiler} error converting to"                           │
│   203 │   │   │   │   f" {output_format[1:]}. See log output above or"                │
│                                                                                       │
│ E:\anaconda\envs\manim\lib\site-packages\manim\utils\tex_file_writing.py:267 in       │
│ print_all_tex_errors                                                                  │
│                                                                                       │
│   264 │   ]                                                                           │
│   265 │   if error_indices:                                                           │
│   266 │   │   with tex_file.open() as f:                                              │
│ ❱ 267 │   │   │   tex = f.readlines()                                                 │
│   268 │   │   for error_index in error_indices:                                       │
│   269 │   │   │   print_tex_error(tex_compilation_log, error_index, tex)              │
│   270                                                                                 │
╰───────────────────────────────────────────────────────────────────────────────────────╯
UnicodeDecodeError: 'gbk' codec can't decode byte 0xad in position 152: illegal multibyte
sequence
</details>

## System specifications

<details><summary>System Details</summary>

- OS (with version, e.g., Windows 10 v2004 or macOS 10.15 (Catalina)):win11
- RAM:16GB
- Python version (`python/py/python3 --version`):3.8.16
- Installed modules (provide output from `pip list`):
```
PASTE HERE
```
appdirs              1.4.4
attrs                22.1.0
brotlipy             0.7.0
build                0.10.0
CacheControl         0.12.11
certifi              2023.5.7
cffi                 1.15.1
charset-normalizer   2.0.4
cleo                 2.0.1
click                8.0.4
click-default-group  1.2.2
cloup                0.13.1
colorama             0.4.6
colour               0.1.5
crashtest            0.4.1
cryptography         39.0.1
decorator            5.1.1
distlib              0.3.6
dulwich              0.21.3
filelock             3.9.0
future               0.18.3
glcontext            2.3.7
html5lib             1.1
idna                 3.4
importlib-metadata   6.0.0
installer            0.6.0
isosurfaces          0.1.0
jaraco.classes       3.2.1
jsonschema           4.17.3
keyring              23.13.1
lockfile             0.12.2
manim                0.17.3
ManimPango           0.4.3
mapbox-earcut        1.0.0
markdown-it-py       2.2.0
mdurl                0.1.0
mkl-fft              1.3.6
mkl-random           1.2.2
mkl-service          2.4.0
moderngl             5.8.2
moderngl-window      2.4.1
more-itertools       8.12.0
msgpack              1.0.3
multipledispatch     0.6.0
networkx             2.8.4
numpy                1.25.0
packaging            23.0
pexpect              4.8.0
Pillow               9.4.0
pip                  23.1.2
pkginfo              1.9.6
platformdirs         2.5.2
poetry               1.4.0
poetry-core          1.5.1
poetry-plugin-export 1.3.0
pooch                1.4.0
ptyprocess           0.7.0
pycairo              1.23.0
pycparser            2.21
pydub                0.25.1
pyglet               1.5.27
Pygments             2.15.1
pyOpenSSL            23.0.0
pyproject_hooks      1.0.0
pyrr                 0.10.3
pyrsistent           0.18.0
PySocks              1.7.1
pywin32-ctypes       0.2.0
PyYAML               6.0
rapidfuzz            2.13.7
requests             2.29.0
requests-toolbelt    0.9.1
rich                 13.3.5
scipy                1.10.1
screeninfo           0.8.1
setuptools           67.8.0
shellingham          1.5.0
six                  1.16.0
skia-pathops         0.7.4
srt                  3.5.2
svgelements          1.9.5
tomli                2.0.1
tomlkit              0.11.1
tqdm                 4.65.0
trove-classifiers    2023.3.9
typing_extensions    4.6.3
urllib3              1.26.16
virtualenv           20.16.2
watchdog             2.1.6
webencodings         0.5.1
wheel                0.38.4
win-inet-pton        1.1.0
zipp                 3.11.0

</details>

<details><summary>LaTeX details</summary>

+ LaTeX distribution (e.g. TeX Live 2020):MikTex 4.9
+ Installed LaTeX packages:

</details>

<details><summary>FFMPEG</summary>

Output of `ffmpeg -version`:
ffmpeg version 4.2.2 Copyright (c) 2000-2019 the FFmpeg developers
built with gcc 9.2.1 (GCC) 20200122
configuration: --disable-static --enable-shared --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt
libavutil      56. 31.100 / 56. 31.100
libavcodec     58. 54.100 / 58. 54.100
libavformat    58. 29.100 / 58. 29.100
libavdevice    58.  8.100 / 58.  8.100
libavfilter     7. 57.100 /  7. 57.100
libswscale      5.  5.100 /  5.  5.100
libswresample   3.  5.100 /  3.  5.100
libpostproc    55.  5.100 / 55.  5.100
```
PASTE HERE
```
</details>

**Comment by uwezi** [comment]
LaTeX does not support Chinese characters in math mode, only in text mode (`Tex(r"")` or `MathTex(r"\text{}")`). This is not a limitation of Manim, but of LaTeX.
Also of course you need to have the appropriate fonts and multilanguage support installed in your external LaTeX application. The predefined LaTeX template `ctex` makes sure that the correct settings are loaded into the LaTeX scripts

```python
class chineseLaTeX(Scene):
    def construct(self):

        t1 = Tex(
            r"中文",
            tex_template=TexTemplateLibrary.ctex
        ).scale(3)
        self.play(Write(t1))
        self.wait() 
```
![bild](https://github.com/ManimCommunity/manim/assets/8582807/5eaa5630-37fb-4d38-970c-70d5a3cceb57)
```python
class chineseLaTeX(Scene):
    def construct(self):

        t1 = MathTex(
            r"\text{中文}\\ E=mc^2",
            tex_template=TexTemplateLibrary.ctex
        ).scale(3)
        self.play(Write(t1))
        self.wait()  
```

![bild](https://github.com/ManimCommunity/manim/assets/8582807/6f2a38e1-569d-4fd4-8b4f-256dc2e301ce)

**Comment by behackl** [comment]
Closing as invalid.
