### ISSUE TITLE
Could not import extension manim.utils.docbuild.manim_directive

### ISSUE THREAD

**Issue by edrx** [ManimCommunity/manim#3309]
#### Preliminaries

- [x] I have followed the latest version of the
      [installation instructions](https://docs.manim.community/en/stable/installation.html).
- [x] I have checked the [installation FAQ](https://docs.manim.community/en/stable/faq/installation.html) and my problem is either not mentioned there,
      or the solution given there does not help.

## Description of error
Long story short: when I run "cd docs; make html" I get this error:
```
Running Sphinx v5.0.2
Manim Community v0.11.0


Extension error:
Could not import extension manim.utils.docbuild.manim_directive (exception: No module named 'manim.utils.docbuild')
make: *** [Makefile:33: html] Error 2
```

Long story long: I'm on Debian 11.7 ("Bullseye"), and I have Manim installed and running here. But when I try to build Manim from the git repository with the commands below the "make html" in the last step gives the error above...
```
rm -Rfv ~/usrc/manim/
cd      ~/usrc/
git clone https://github.com/ManimCommunity/manim
cd      ~/usrc/manim/
poetry install
cd      ~/usrc/manim/docs/
pip3 install -r     requirements.txt
pip3 install -r rtd-requirements.txt
make
make html
```

**Comment by jsonvillanueva** [comment]
Based on your output from `cd docks; make html`, it seems your poetry environment is setup incorrectly and installing a fairly old version of Manim (v0.11.0 from October of 2021). You should ensure that you are inside the poetry virtual environment created (using `poetry shell`) before running `make html`. 

You'll know it's you're in the correct environment when the output of `manim --version` outputs v0.17.3 (the current version as of this comment).

**Comment by edrx** [comment]
Perfect, thanks! =)
