### ISSUE TITLE
Failing tests due to Cairo 1.17.8 subpixel antialiasing update

### ISSUE THREAD

**Issue by MrDiver** [ManimCommunity/manim#3310]
In Cairo Version [1.17.8](https://www.cairographics.org/news/cairo-1.17.8/) there was new subpixel antialiasing introduced based on the changes in 1.17.4. This breaks the behavior of manim because it changes the output of the tests so many tests will fail due to different pixels at the border of mobjects.

One solution might be to increase the error ratio or update the test data. This will most likely break the tests for people using the older cairo version.

**Comment by naveen521kk** [comment]
FYI, there's a new stable release of Cairo out now https://cairographics.org/news/cairo-1.18.0/
