### ISSUE TITLE
VSCode not able to recognize manim packages

### ISSUE THREAD

**Issue by shunnnli** [ManimCommunity/manim#3313]
## Description of bug / unexpected behavior
I successfully installed manim in anaconda and loaded it in VSCode. 
The code works when running the manim -pql scene.py XX but vscode says it can't recognize file. 
I double checked that my python interpreter is using the conda one, and manim-sideview can successfully render my file. But vscode insisted that manim can't be resolved, and it will say module not found if I clicked run in vscode.

## Expected behavior
VScode should not issue error of package not recognize

</details>

## Additional media files
<details><summary>Images/GIFs</summary>

<img width="1195" alt="image" src="https://github.com/ManimCommunity/manim/assets/44044548/47c5f5d7-7883-4a6b-8100-9451e3372c26">
</details>

## Logs
<details><summary>Terminal output</summary>

```
Traceback (most recent call last):
  File "/Users/shunli/Downloads/sabalab/Manim/scene.py", line 1, in <module>
    from manim import *
ModuleNotFoundError: No module named 'manim'
```

</details>

## System specifications

<details><summary>System Details</summary>

- OS (macOS 13.4.1 (Ventura)):
- RAM:
- Python version (`python3.11.4 `):
- Installed modules (provide output from `pip list`):
```
PASTE HERE
```
</details>

<details><summary>LaTeX details</summary>

+ LaTeX distribution (e.g. TeX Live 2020):
+ Installed LaTeX packages:

</details>

<details><summary>FFMPEG</summary>

Output of `ffmpeg -version`:

```
PASTE HERE
```
</details>

**Comment by MrDiver** [comment]
This is not a problem with manim is it? But in any way, if you have installed it inside of a conda environment you also have to open vscode in that said environment. So open your terminal, activate the conda environment and then open vscode in the curreent folder by typing `code .` this should automatically trigger vscode to recognize the correct environment. This can also be verified by the terminal inside vscode automatically starting the conda environment.
Please make also sure that you checked that your vscode actually uses the interpreter for typechecking. Depending on the extension you use you might find a setting like this: 
![grafik](https://github.com/ManimCommunity/manim/assets/17803932/c083b8e0-c42f-4ebe-987d-20f14c99b26c)
So please check which extension you use.

**Comment by MrDiver** [comment]
Note: if you want a little bit better support for such problems, instead of opening a github issue and adding to the backlog of things we have to look after you might consider joining the discord server, were we have a lot of people that are willing to help with such things.
https://manim.community/discord
