### ISSUE TITLE
Using classmethods for constants

### ISSUE THREAD

**Issue by huguesdevimeux** [ManimCommunity/manim#332]
I don't know if it would be a good idea, or if this has been already brought up  (I think @leotrs mentioned a similar idea in #310 ). 

The idea would be to change the way all the constants are implemented into something that would be similar to namespaces. 
My idea would be, for example, for the colors, to do something like : 
```python 
class Color : 
    ...
    @classmethod
    def red(self):
        return <color red>
```

Thus, one could access the red colour by simply doing `Color.red()` instead of the ugly `RED`

Similar reasoning could be applied for every item within `constants.py`. So we would have, for example, `Message.not_setting_font()`.
We could even go further, by implementing all constants utils within these classes. (for example, `utils.interpolate_color`)

A major advantage would be that everything would be much better organized and more, I think, clean. The constants would be well arranged by classes (and so we could get auto-completion ;D), On the other hand, it would be a little bit more long to use, as you would have to access to Color every time. 

**NOTE :** I took inspiration on how colors are implemented on the discord python API, but I can"'t find a link to the file :/

**Comment by leotrs** [comment]
So what I gather from this discussion is the following:

1. Use `Enum` for constant colors.
2. Use integers (specified in hex) for colors, instead of strings.
3. There should be a `Color` class that inherits from `colour.Colour`.

I think this issue pertains (1). The other two should be separate issues IMO.

**Comment by cobordism** [comment]
Can I put in a word for having colour be a synonym of color?
You have no idea how often this causes errors for people like me :)

**Comment by leotrs** [comment]
You mean alias every instance of `color` as `colour`?

**Comment by leotrs** [comment]
Also, point number 1 [here](https://github.com/ManimCommunity/manim/issues/332#issuecomment-678817090) is already implemented in #488. Please open new issues for points number 2 or 3 when necessary.

**Comment by cobordism** [comment]
> You mean alias every instance of color as colour?

Is that not doable?
If not let's rename color to colour and annoy the other half for a change ;)

**Comment by leotrs** [comment]
Yes it should! I was just making sure I understood correctly. Also, can you please open a new issue for that? This one has ran its course.
