### ISSUE TITLE
Extra curly bracket in section Extra LaTeX Packages of documentation

### ISSUE THREAD

**Issue by hunter1749** [ManimCommunity/manim#3330]
Exact part of documentation in section [Extra LaTeX Packages](https://docs.manim.community/en/stable/guides/using_text.html#extra-latex-packages).

Line containing `r"$\mathscr{H} \rightarrow \mathbb{H}$}",` doesn't need the extra curly bracket.

**Comment by u7481690** [comment]
I have opened a PR for this issue.

**Comment by behackl** [comment]
Fixed via #3389
