### ISSUE TITLE
Inconsistent Formatting in Building_Blocks

### ISSUE THREAD

**Issue by ANekhai** [ManimCommunity/manim#3369]
I'm working through the tutorials and was wondering if the inconsistent formatting when creating mobjects `ExampleRotation` is intentional? E.g. `m1a = ...` vs `m2a= ...`. Thanks!

**Comment by uwezi** [comment]
do you just mean the missing space in front of the equal sign?

![image](https://github.com/ManimCommunity/manim/assets/8582807/27519d8d-e1a6-4f50-aff8-03ee8ff24628)

**Comment by MrDiver** [comment]
Just a formatting issue
