### ISSUE TITLE
Installation error during manim: `Package pangocairo was not found`

### ISSUE THREAD

**Issue by Pratboihmm** [ManimCommunity/manim#3390]
#### Preliminaries
 
I followed the installation process given in the manim readme.md file. 
However installation has failed

## Description of error

The error happends in the collection of mainmpango which results in a subprocess-exited-with-error

## Installation logs

The installation logs are as such,

<details><summary>Terminal output</summary>

Collecting manim
  Using cached manim-0.17.3-py3-none-any.whl (530 kB)
Collecting Pillow<10.0,>=9.1
  Using cached Pillow-9.5.0-cp311-cp311-manylinux_2_28_x86_64.whl (3.4 MB)
Requirement already satisfied: Pygments<3.0.0,>=2.10.0 in ./.venv/lib/python3.11/site-packages (from manim) (2.16.1)
Collecting click<=9.0,>=7.2
  Using cached click-8.1.7-py3-none-any.whl (97 kB)
Collecting click-default-group<2.0.0,>=1.2.2
  Using cached click_default_group-1.2.4-py2.py3-none-any.whl (4.1 kB)
Collecting cloup<0.14.0,>=0.13.0
  Using cached cloup-0.13.1-py2.py3-none-any.whl (51 kB)
Collecting colour<0.2.0,>=0.1.5
  Using cached colour-0.1.5-py2.py3-none-any.whl (23 kB)
Requirement already satisfied: decorator<6.0.0,>=5.0.7 in ./.venv/lib/python3.11/site-packages (from manim) (5.1.1)
Collecting isosurfaces==0.1.0
  Using cached isosurfaces-0.1.0-py3-none-any.whl (10 kB)
Collecting manimpango<0.5.0,>=0.4.0.post0
  Using cached ManimPango-0.4.4.tar.gz (4.1 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [28 lines of output]
      Package 'pangocairo' was not found
      Traceback (most recent call last):
        File "<string>", line 136, in check_min_version
        File "/usr/lib/python3.11/subprocess.py", line 413, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['pkg-config', '--print-errors', '--atleast-version', '1.30.0', 'pangocairo']' returned non-zero exit status 1.
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/home/amnesiac/.venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/amnesiac/.venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/amnesiac/.venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-51qc2r9w/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 355, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-51qc2r9w/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 325, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-51qc2r9w/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 203, in <module>
        File "<string>", line 139, in check_min_version
      RequiredDependencyException: pangocairo >= 1.30.0 is required
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

```
PASTE HERE OR PROVIDE LINK TO https://pastebin.com/ OR SIMILAR
```

</details>

## System specifications

<details><summary>System Details</summary>

- OS: Debian 12 Bookworm with gnome 43.5
- RAM: 16 Gigs of ram
- Python version : Python 3.11.2
- Installed modules :
```
Package                   Version
------------------------- ---------
aiohttp                   3.8.5
aiosignal                 1.3.1
anyio                     4.0.0
argon2-cffi               23.1.0
argon2-cffi-bindings      21.2.0
arrow                     1.3.0
asttokens                 2.4.0
async-lru                 2.0.4
async-timeout             4.0.3
attrs                     23.1.0
autobahn                  21.11.1
Babel                     2.12.1
backcall                  0.2.0
beautifulsoup4            4.12.2
bitarray                  2.8.1
bitstring                 4.1.2
bleach                    6.0.0
bs4                       0.0.1
certifi                   2023.7.22
cffi                      1.16.0
charset-normalizer        3.3.0
comm                      0.1.4
contourpy                 1.1.1
cryptography              41.0.4
cycler                    0.12.0
debugpy                   1.8.0
decorator                 5.1.1
defusedxml                0.7.1
ecdsa                     0.18.0
esptool                   4.6.2
executing                 2.0.0
fastjsonschema            2.18.0
fonttools                 4.43.0
fqdn                      1.5.1
frozenlist                1.4.0
hyperlink                 21.0.0
idna                      3.4
ipykernel                 6.25.2
ipython                   8.16.0
ipython-genutils          0.2.0
ipywidgets                8.1.1
isoduration               20.11.0
jedi                      0.19.0
Jinja2                    3.1.2
json5                     0.9.14
jsonpointer               2.4
jsonschema                4.19.1
jsonschema-specifications 2023.7.1
jupyter_client            8.3.1
jupyter-console           6.6.3
jupyter_core              5.3.2
jupyter-events            0.7.0
jupyter-lsp               2.2.0
jupyter_server            2.7.3
jupyter_server_proxy      4.1.0
jupyter_server_terminals  0.4.4
jupyterlab                4.0.6
jupyterlab-pygments       0.2.2
jupyterlab_server         2.25.0
jupyterlab-widgets        3.0.9
kiwisolver                1.4.5
MarkupSafe                2.1.3
matplotlib                3.8.0
matplotlib-inline         0.1.6
mistune                   3.0.2
multidict                 6.0.4
nbclient                  0.8.0
nbconvert                 7.8.0
nbformat                  5.9.2
nest-asyncio              1.5.8
notebook                  7.0.4
notebook_shim             0.2.3
numpy                     1.26.0
overrides                 7.4.0
packaging                 23.1
pandocfilters             1.5.0
parso                     0.8.3
pexpect                   4.8.0
pickleshare               0.7.5
Pillow                    10.0.1
pip                       23.0.1
platformdirs              3.10.0
prometheus-client         0.17.1
prompt-toolkit            3.0.39
psutil                    5.9.5
ptyprocess                0.7.0
pure-eval                 0.2.2
pycparser                 2.21
Pygments                  2.16.1
pyparsing                 3.1.1
pyserial                  3.5
python-dateutil           2.8.2
python-json-logger        2.0.7
PyYAML                    6.0.1
pyzmq                     25.1.1
qtconsole                 5.4.4
QtPy                      2.4.0
reedsolo                  1.7.0
referencing               0.30.2
requests                  2.31.0
rfc3339-validator         0.1.4
rfc3986-validator         0.1.1
rpds-py                   0.10.3
Send2Trash                1.8.2
setuptools                66.1.1
simpervisor               1.0.0
six                       1.16.0
sniffio                   1.3.0
soupsieve                 2.5
stack-data                0.6.3
terminado                 0.17.1
tinycss2                  1.2.1
tornado                   6.3.3
traitlets                 5.10.1
txaio                     23.1.1
types-python-dateutil     2.8.19.14
uri-template              1.3.0
urllib3                   2.0.5
wcwidth                   0.2.8
webcolors                 1.13
webencodings              0.5.1
websocket-client          1.6.3
widgetsnbextension        4.0.9
yarl                      1.9.2
```
</details>

**Comment by naveen521kk** [comment]
Have you installed the required system dependencies as described in the [docs](https://docs.manim.community/en/stable/installation/linux.html#apt-ubuntu-mint-debian)? The error means that the `pangocairo` system dependency is not found and can be installed with
```sh
sudo apt install libpango1.0-dev
```

**Comment by behackl** [comment]
Cannot reproduce when following the documentation.

**Comment by connorferster** [comment]
> Have you installed the required system dependencies as described in the [docs](https://docs.manim.community/en/stable/installation/linux.html#apt-ubuntu-mint-debian)? The error means that the `pangocairo` system dependency is not found and can be installed with
> 
> sudo apt install libpango1.0-dev

I am surprise this is not in the docs anywhere.
