### ISSUE TITLE
ReplacementTransform issue with the copy() method in Manim

### ISSUE THREAD

**Issue by JasonMendoza2008** [ManimCommunity/manim#3393]
## Description of bug / unexpected behavior
When attempting to replace a Text object using ReplacementTransform with another Text object that was created using the copy() method, the text does not get replaced as expected. Instead, the original text remains on the screen. A possible workaround is to create a new instance of the Text object and set its position to match the original. However, this behavior is not intuitive.
 
## Expected behavior
The original Text object should be replaced by the new Text object during the transformation.

## How to reproduce the issue

<details><summary>Code for reproducing the problem</summary>

```py
from manim import *

class ReplaceTextBug(Scene):
    def construct(self):
        # Initial text
        original_text = Text("Original Text").move_to(ORIGIN)
        self.play(Write(original_text))
        self.wait(1)

        # Attempting to replace using a copied object (This will not work as expected)
        new_text_wrong = original_text.copy()
        new_text_wrong.text = "New Text (Wrong)"
        self.play(ReplacementTransform(original_text, new_text_wrong))
        self.wait(2)

        # Proper way to replace the text
        new_text_correct = Text("New Text (Correct)").move_to(original_text.get_center())
        self.play(ReplacementTransform(new_text_wrong, new_text_correct))
        self.wait(2)
```

</details>

## Additional comments
Everything can be reproduced on the discord server directly (https://discord.com/channels/581738731934056449/780234936980078602/1160575907048718376)

**Comment by JasonMendoza2008** [comment]
Using a deepcopy will not solve the issue.

**Comment by uwezi** [comment]
The problem is not the `ReplacementTransform` function, but your attempt to modify a text object after it had been created.

```python
        # Attempting to replace using a copied object (This will not work as expected)
        new_text_wrong = original_text.copy()
        new_text_wrong.text = "New Text (Wrong)"
        self.play(ReplacementTransform(original_text, new_text_wrong))
        self.wait(2)
```
You cannot change the contents of a `Text()`, `Tex()`, `MathTex()` object in this way. The string which is given when you first define the object is only once rendered into a graphical representation by either the Pango-library (`Text()`) or by the external LaTeX application.

Afterwards the rendered graphical representation will not be changed, when you try to modify the object. Tht's just how it is...

**Comment by JasonMendoza2008** [comment]
Ok I understand, so modifying the attribute `.text` has no effect? Maybe adding a warning to the user when the attribute `.text` is set to something else should be outputted?

**Comment by uwezi** [comment]
> Ok I understand, so modifying the attribute `.text` has no effect? Maybe adding a warning to the user when the attribute `.text` is set to something else should be outputted?

The same is true for many attributes... just recognize that in general, you cannot change the shape, form, size of Manim objects by their respective attributes.

**Comment by JasonMendoza2008** [comment]
Oh yes I guess most attributes cannot be changed, makes sense.
