### ISSUE TITLE
manim isn't working even with their official examples

### ISSUE THREAD

**Issue by amcoolkid** [ManimCommunity/manim#3401]
### Describe the error
I am looking at the example https://3b1b.github.io/manim/getting_started/example_scenes.html#textexample

Shorttening it, I have the bare minimum

```
class TextExample(Scene):
    def construct(self):
        # To run this scene properly, you should have "Consolas" font in your computer
        # for full usage, you can see https://github.com/3b1b/manim/pull/680
        text = Text("Here is a text", font="Arial", font_size=90)
        difference = Text(
            """
            The most important difference between Text and TexText is that\n
            you can change the font more easily, but can't use the LaTeX grammar
            """,
            font="Arial", font_size=24,
            # t2c is a dict that you can choose color for different text
            t2c={
                "Text": BLUE, "TexText": BLUE, "LaTeX": ORANGE
            }
        )
        VGroup(text, difference).arrange(DOWN, buff=1)
        self.play(Write(text))
        self.play(FadeIn(difference, UP))
        self.wait(3)
```
This

```
        t2c={
            "Text": BLUE, "TexText": BLUE, "LaTeX": ORANGE
        }
```
would cause an error

```
text_mobject.py:678, in Text._merge_settings(self, left_setting, right_setting, default_args)
    676     default = default_args[arg]
    677     if left != default and getattr(right_setting, arg) != default:
--> 678         raise ValueError(
    679             f"Ambiguous style for text '{self.text[right_setting.start:right_setting.end]}':"
    680             + f"'{arg}' cannot be both '{left}' and '{right}'."
    681         )
    682     setattr(right_setting, arg, left if left != default else right)
    683 return new_setting


ValueError: Ambiguous style for text 'Text':'color' cannot be both '#58C4DD' and '#58C4DD'.
```
Even after I commenting that line out, I got another error

```
mobject.py:430, in Mobject.add(self, *mobjects)
    428 for m in mobjects:
    429     if not isinstance(m, Mobject):
--> 430         raise TypeError("All submobjects must be of type Mobject")
    431     if m is self:
    432         raise ValueError("Mobject cannot contain self")

TypeError: All submobjects must be of type Mobject
```

### Environment
**OS System**: MacOS
**manim version**: Manim Community v0.17.3
**python version**: 
3.10.8 (main, Oct 12 2022, 03:26:28) [Clang 13.0.0 (clang-1300.0.29.30)]

**Comment by UnMolDeQuimica** [comment]
Let's talk about the first error. 

Here you are saying you want to color `Text` as BLUE and `TexText` also as BLUE:

```
t2c={
            "Text": BLUE, "TexText": BLUE, "LaTeX": ORANGE
        }
```

Manim will try to find `TexText` and interpret as both `TexText` and `Text`, raising the error you found. 

In your case both are BLUE and you could simply change the code to:

```
t2c={
            "Text": BLUE, "Tex": BLUE, "LaTeX": ORANGE
        }
```
That should do the trick.

**Comment by UnMolDeQuimica** [comment]
About the second error, the class `FadeIn` will take all parameterers as objects to FadeIn unless they are named parameters. 

That means, when you are doing `self.play(FadeIn(difference, UP))`, manim thinks you are trying to draw in the screen the objects "difference" and "UP". As UP is a np.ndarray and not a VMObject, it waises an error. 


Change your FadeIn code to the following and it should work:

```
self.play(FadeIn(difference, shift=UP))
```

**Comment by behackl** [comment]
> I am looking at the example https://3b1b.github.io/manim/getting_started/example_scenes.html#textexample

You are looking at the `manimlib` documentation, not [ours](https://docs.manim.community). These two versions of the library are not compatible with each other. Learn more here: https://docs.manim.community/en/stable/faq/installation.html#why-are-there-different-versions-of-manim
