### ISSUE TITLE
NumberLine call `get_labels` doesn't work

### ISSUE THREAD

**Issue by chrisyy2003** [ManimCommunity/manim#3402]
## Expected behavior
get the tick label at number

## How to reproduce the issue
call `get_labels`

<details><summary>Code for reproducing the problem</summary>

```py
n_line = NumberLine(
            x_range=[0, 10 + 1, 1],
            length=12,
            include_tip=True,
            # include_numbers=True,
        ).shift(DOWN * 2)
n_line.get_labels()
```

</details>

## Additional media files

<img width="702" alt="image" src="https://github.com/ManimCommunity/manim/assets/63803385/d58266dd-84ea-4a3b-be18-16806b2c42d6">

</details>

## Logs
<details><summary>Terminal output</summary>

```
PASTE HERE OR PROVIDE LINK TO https://pastebin.com/ OR SIMILAR
```

</details>

## System specifications

<details><summary>System Details</summary>

- OS (with version, e.g., Windows 10 v2004 or macOS 10.15 (Catalina)):
- RAM:
- Python version (`python/py/python3 --version`):
- Installed modules (provide output from `pip list`):
```
PASTE HERE
```
</details>

<details><summary>LaTeX details</summary>

+ LaTeX distribution (e.g. TeX Live 2020):
+ Installed LaTeX packages:

</details>

<details><summary>FFMPEG</summary>

Output of `ffmpeg -version`:

```
PASTE HERE
```
</details>

**Comment by behackl** [comment]
What output do you expect for a `NumberLine` that has no labels?

**Comment by chrisyy2003** [comment]
Hi, here is my full code, the `get_labels` can't accept any params or  call directly, I just want to indicate the tick of some index
```
%%manim -qm -v WARNING Scene6
from manim import *
class Scene6(Scene):
    def construct(self):
        n_line = NumberLine(
            x_range=[0, 10 + 1, 1],
            length=12,
            include_tip=True,
            # include_numbers=True,
        ).shift(DOWN * 2)
        self.play(Create(n_line))

        n_line.add_labels(dict_values={
            5: MathTex('Tick_{1}'),
            8: MathTex('Tick_{2}'),
            10: MathTex('Tick_{3}')
        })
        # self.play(Indicate(n_line.get_labels()))
        self.wait(3)
```

<img width="1185" alt="image" src="https://github.com/ManimCommunity/manim/assets/63803385/7e64b341-5358-412e-840a-bb860d96eec2">

**Comment by uwezi** [comment]
not necessarily logical and there seems to be the usual problem that labels exist in 2 copies on numberlines, but this works somewhat:

```python
class Scene6(Scene):
    def construct(self):
        n_line = NumberLine(
            x_range=[0, 10 + 1, 1],
            length=12,
            include_tip=True,
            # include_numbers=True,
        ).shift(DOWN * 2)
        self.play(Create(n_line))

        n_line.add_labels(dict_values={
            5: MathTex('Tick_{1}'),
            8: MathTex('Tick_{2}'),
            10: MathTex('Tick_{3}')
        })
        self.play(Indicate(n_line.labels[0]))
        self.wait()
        self.play(Indicate(n_line.labels[1]))
        self.wait()
        self.play(Indicate(n_line.labels[2]))
        self.wait(3)
```
