### ISSUE TITLE
Improve handling of specified font name

### ISSUE THREAD

**Issue by behackl** [ManimCommunity/manim#3413]
Currently our documentation build throws several warnings like
```
[10/22/23 18:12:47] WARNING  Font monospace not in [...]
[10/22/23 18:14:58] WARNING  Font sans not in [...]
[10/22/23 18:15:00] WARNING  Font sans-serif not in [...]
```

See https://readthedocs.org/api/v2/build/22307289.txt for the complete log of a recent build.

There are two issues here:
- The font `sans-serif` should probably also be referred to as `sans`.
- Miscapitalized fonts are currently not registered correctly: in the examples above, `Monospace` and `Sans` are actually included by the list returned by `manimpango.list_fonts()`. I think it would be a good idea to automatically correct this user input error: if the specified font is not included in the list, manim should check whether the capitalized version is there -- and if so, use that value instead.

**Comment by staghado** [comment]
Can I take a stab at this?

**Comment by behackl** [comment]
> Can I take a stab at this?

Sure, much appreciated! Feel free to ask questions here or in the development-chat in our Discord -- but otherwise just submit a PR with your proposed changes.

**Comment by staghado** [comment]
I have added a PR!
