### ISSUE TITLE
Replace manim's implementation of `binary_search` with `bisect` from Python's standard library

### ISSUE THREAD

**Issue by behackl** [ManimCommunity/manim#3437]
See title: the implementation of `manim.utils.simple_functions.binary_search` should be removed, and wherever it is used we should try and use `bisect` from Python's native `bisect` module -- if possible.

**Comment by Sumit112192** [comment]
In the current binary_search function, what we are doing is search for what value of x is our function equal to the target. And the bisect function works on an array. So, how to make the bisect function work on an function? @behackl

**Comment by behackl** [comment]
True, I've not checked the function closely enough when creating the issue. After more careful investigation, the only way of using `bisect` more or less directly here would be if we evaluated the function on all points of a sufficiently fine mesh -- which is overkill.

Thanks for taking a closer look, I'll close this issue.
