### ISSUE TITLE
Last frame of animation is not rendered into video file unless a `wait()` is added

### ISSUE THREAD

**Issue by hzeller** [ManimCommunity/manim#3464]
## Description of bug / unexpected behavior

Consider the following, which I expect to print a number animation from `-1.00000 ... 1.00000`

```Python
class PrintValue(Scene):
    def construct(self):
        k = ValueTracker(-1)
        print_value = always_redraw(
            lambda: DecimalNumber(num_decimal_places=5,
                                  font_size=120).set_value(k.get_value())
        )
        self.add(print_value)
        self.play(k.animate.set_value(1))
 ```

With manim v0.18.0 rendering:
```
manim --renderer cairo -t -r320,200 --format=webm -ono-wait printvalue.py PrintValue
```

This results in the following output:

[no-wait.webm](https://github.com/ManimCommunity/manim/assets/140937/6e1af147-0037-414c-aaeb-1af6eb6aab62)

Note the missing last value `1.00000`

Interestingly, asking to emit the last frame as image with `-s`, this _does_ result in the expected frame with that value
```
manim --renderer cairo -s -t -r320,200 -ono-wait experiment.py PrintValue
```

![no-wait](https://github.com/ManimCommunity/manim/assets/140937/21175060-763f-4137-8334-eb6d837187c4)

The rendering is fixed by the following workaround, adding a wait that is at least the length of one frame at the end:

```Python
class PrintValue(Scene):
    def construct(self):
        k = ValueTracker(-1)
        print_value = always_redraw(
            lambda: DecimalNumber(num_decimal_places=5,
                                  font_size=120).set_value(k.get_value())
        )
        self.add(print_value)
        self.play(k.animate.set_value(1))
        self.wait(0.1)   # <- this apparently makes the last frame flush
```

... now, the resulting animation is complete

[with-wait.webm](https://github.com/ManimCommunity/manim/assets/140937/fbe90894-6fea-4d5d-8916-83f9d838b3b4)

## Expected behavior

My expectation would be that the annimation would emit all the frames to the video output without a `self.wait()` call.

## How to reproduce the issue and media

See scripts above.

## System specifications

<details><summary>System Details</summary>

- manim version: 0.18.0
- OS: Linux (recent nixos):
- RAM: 64G
- Python version (`python/py/python3 --version`): 3.11.6
- Installed modules (provide output from `pip list`): No extra modules installed

<details><summary>FFMPEG</summary>

Output of `ffmpeg -version`:

```
ffmpeg version 6.0 Copyright (c) 2000-2023 the FFmpeg developers
built with gcc 12.3.0 (GCC)
configuration: --disable-static --prefix=/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-ffmpeg-6.0 --target_os=linux --arch=x86_64 --pkg-config=pkg-config --enable-gpl --enable-version3 --disable-nonfree --enable-shared --enable-pic --disable-small --enable-runtime-cpudetect --disable-gray --enable-swscale-alpha --enable-hardcoded-tables --enable-safe-bitstream-reader --enable-pthreads --disable-w32threads --disable-os2threads --enable-network --enable-pixelutils --datadir=/nix/store/w5p9l98zyhvmcdic2b3gs4a3zf0vmwhf-ffmpeg-6.0-data/share/ffmpeg --enable-ffmpeg --disable-ffplay --enable-ffprobe --bindir=/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-ffmpeg-6.0-bin/bin --enable-avcodec --enable-avdevice --enable-avfilter --enable-avformat --enable-avutil --enable-postproc --enable-swresample --enable-swscale --libdir=/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-ffmpeg-6.0-lib/lib --incdir=/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-ffmpeg-6.0-dev/include --enable-doc --enable-htmlpages --enable-manpages --mandir=/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-ffmpeg-6.0-man/share/man --enable-podpages --enable-txtpages --docdir=/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-ffmpeg-6.0-doc/share/doc/ffmpeg --enable-alsa --enable-bzlib --disable-libcelt --disable-cuda --disable-cuda-llvm --enable-libdav1d --disable-libfdk-aac --disable-libflite --enable-fontconfig --enable-libfreetype --disable-frei0r --disable-libfribidi --disable-libgme --enable-gnutls --disable-libgsm --disable-ladspa --enable-libmp3lame --disable-libaom --enable-libass --disable-libbluray --disable-libbs2b --disable-libdc1394 --enable-libdrm --enable-iconv --disable-libjack --disable-libmfx --disable-libmodplug --disable-libmysofa --enable-libopus --disable-librsvg --enable-libsrt --enable-libssh --disable-libtensorflow --enable-libtheora --enable-libv4l2 --enable-v4l2-m2m --enable-vaapi --enable-vdpau --enable-libvorbis --disable-libvmaf --enable-libvpx --disable-libwebp --disable-xlib --disable-libxcb --disable-libxcb-shm --disable-libxcb-xfixes --disable-libxcb-shape --disable-libxml2 --enable-lzma --enable-cuvid --enable-nvdec --enable-nvenc --disable-openal --disable-opencl --disable-libopencore-amrnb --disable-opengl --disable-libopenh264 --disable-libopenjpeg --disable-libopenmpt --enable-libpulse --disable-librav1e --enable-libsvtav1 --disable-librtmp --enable-sdl2 --enable-libsoxr --enable-libspeex --disable-libvidstab --disable-libvo-amrwbenc --enable-libx264 --enable-libx265 --disable-libxavs --enable-libxvid --disable-libzmq --enable-libzimg --enable-zlib --disable-vulkan --disable-libglslang --disable-libsmbclient --disable-debug --enable-optimizations --disable-extra-warnings --disable-stripping
libavutil      58.  2.100 / 58.  2.100
libavcodec     60.  3.100 / 60.  3.100
libavformat    60.  3.100 / 60.  3.100
libavdevice    60.  1.100 / 60.  1.100
libavfilter     9.  3.100 /  9.  3.100
libswscale      7.  1.100 /  7.  1.100
libswresample   4. 10.100 /  4. 10.100
libpostproc    57.  1.100 / 57.  1.100
```
</details>

**Comment by behackl** [comment]
Thanks for your report! This is a problem that is rooted quite deeply, and I do not think that we will change this behavior any time soon. Essentially, this is because

- we want the animation completion rate to progress nicely in steps proportional to the frame rate,
- and we want the produced video to have the correct length and frame rate.

When rendering a 1s-animation in 30fps, this means that we can show 30 frames in the output, where the j-th frame corresponds to animation completion rate (j-1)/30, as we need to show the initial, unmodified state in the beginning for one frame. This leaves no space (or actually better, no time) for displaying the final state of the animation; we are exactly one frame short. The state of the mobjects and everything is stored correctly, which is why manually adding any amount of time at the end "fixes" this problem.

Fixing this requires us to abandon one of the two principles above (and if we ever do so, it is most likely the proportional scaling of the animation completion with the frame rate) -- but for now, this is out of scope.
