### ISSUE TITLE
`SpiralIn` is not working with the first Element

### ISSUE THREAD

**Issue by MrDiver** [ManimCommunity/manim#3514]
`SpiralIn` doesn't show the first Element sometimes, for examples just visit the current documentation of `SpiralIn`

- [ ] Tests are needed for SpiralIn to prevent this from happening again
- [ ] Implementation needs to be fixed

**Comment by Gixtox** [comment]
Started looking into this issue. Here is an example that fails to show the test object when I run `manim -pqh test.py`:

```python
class SpiralInBugExample(Scene):
    def construct(self):
        test = MathTex(r"\pi").scale(5)
        # test = Tex('test').scale(5) # Uncomment to test Tex
        # test = SingleStringMathTex(tex_string='test').scale(5) # Uncomment to test SingleStringMathTex
        # test = Circle() # Uncomment to test Circle
        shapes = VGroup(test)
        self.play(SpiralIn(shapes))
```
In the above example, you can uncomment any of the test lines to see the behavior of that object. They all behave the same. 

Something interesting I found was the issue occurs or goes away depending on whether or not you run another play before running SpiralIn. Here are the following orders with their results after running `manim -pqh test.py`. To see these results, replace the last line in my first example with one of these groups.
```python
self.play(SpiralIn(shapes)) # Will not show
self.play(DrawBorderThenFill(shapes)) # Will not show
self.play(ShowSubmobjectsOneByOne(shapes)) # Will show
```
```python
self.play(SpiralIn(shapes)) # Will not show
self.play(ShowSubmobjectsOneByOne(shapes)) # Will show
self.play(DrawBorderThenFill(shapes)) # Will show
```
```python
self.play(ShowSubmobjectsOneByOne(shapes)) # Will show
self.play(DrawBorderThenFill(shapes)) # Will show
self.play(SpiralIn(shapes)) # Will show
```
```python
self.play(ShowSubmobjectsOneByOne(shapes)) # Will show
self.play(SpiralIn(shapes)) # Will show
self.play(DrawBorderThenFill(shapes)) # Will show
```
```python
self.play(DrawBorderThenFill(shapes)) # Will show
self.play(ShowSubmobjectsOneByOne(shapes)) # Will show
self.play(SpiralIn(shapes)) # Will show
```
```python
self.play(DrawBorderThenFill(shapes)) # Will show
self.play(SpiralIn(shapes)) # Will not show
self.play(ShowSubmobjectsOneByOne(shapes)) # Will show
```
Each of the above groups behaved the same for each object type I tested. Another note, if SpiralIn isn't the first play, the SpiralIn play will cause the object to just fade in. It will not spiral. I don't know if this is expected. 

Going to continue looking into this the bug.

**Comment by acremers22** [comment]
I'm working on a solution for this issue.
