### ISSUE TITLE
Dev Install Issue: Cairo must be installed from source to match CI version (1.18)

### ISSUE THREAD

**Issue by jeertmans** [ManimCommunity/manim#3521]
#### Preliminaries

- [x] I have followed the latest version of the
      [installation instructions](https://docs.manim.community/en/stable/installation.html).
- [x] I have checked the [installation FAQ](https://docs.manim.community/en/stable/faq/installation.html) and my problem is either not mentioned there,
      or the solution given there does not help.

## Description of error

This is more a documentation issue, but CI is using Cairo 1.18, while Ubuntu users (at least using 22.04) can only install Cairo 1.16 from `apt`.

Not using Cairo 1.18 will mean that `pytest` will skip a lot of tests locally, but that may fail in the CI. This is an issue because users will have to trust the CI to pass tests, and possibly wait a long time to check if a patch fixed changes.

## TODO

Document this potential issue (only important for dev I guess) and how to build Cairo from source (requires `ninja` and `meson`).

## System specifications

- OS: Uubuntu 22.04

**Comment by behackl** [comment]
Adding a remark about this to the developer installation guide is probably a good idea. The restriction was -- unfortunately -- necessary as the new cairo version introduced some minor changes to the graphical output which resulted in failed tests. You can find the corresponding issues / PRs by checking the latest changelog.
