### ISSUE TITLE
Full Latex Compiler inside manim

### ISSUE THREAD

**Issue by JohnyMarley** [ManimCommunity/manim#3523]
## Description of proposed feature
Adding full latex compiler capabilities into manim. In that way you could simply import your latex code and for example create static figures with tikzpicture. I would imaging that manim then could be a superset of latex beamer. Where you both have the awesome animation capabilites of manim and the static image generation techniques from latex (pgfplots,tikzpicture..etc)

## How can the new feature be used?
Could be used in places where animation not strictly are necessary and a static image is useful. 

What do you guys think?

**Comment by JasonGrace2282** [comment]
LaTeX is a very large thing to add into manim. If there were any python bindings to it, then it might be worth considering - for now it is a very large task that is mostly out of the scope for manim.
