### ISSUE TITLE
Succession does not work as expected

### ISSUE THREAD

**Issue by youginil** [ManimCommunity/manim#3536]
```python
class Test(Scene):
    def construct(self):
        txt1 = Text("1", color=BLACK)
        txt2 = Text("2", color=BLACK)
        self.play(
            Succession(
                FadeIn(txt1, shift=UP),
                FadeOut(txt1, shift=DOWN),
                FadeIn(txt2, shift=UP),
                FadeOut(txt2, shift=DOWN),
            )
        )
        self.wait(1)
```
I want to show some mobjects one by one, it seems out of control: "2" shows first

https://github.com/ManimCommunity/manim/assets/11213808/2ddf2078-eb6c-4d38-a697-2518a7828b2e

**Comment by MrDiver** [comment]
It works as intended but using it on 2 different mobjects will not work as you want it to.

What you want to have is S(S(t1), S(t2))
i.e. two different successions un succession
