### ISSUE TITLE
``VGroup`` should parse iterables

### ISSUE THREAD

**Issue by JasonGrace2282** [ManimCommunity/manim#3540]
See #3365

**Comment by JasonGrace2282** [comment]
CC @MrDiver

**Comment by oscjac** [comment]
Is this issue still open? I would love to contribute if it is!

**Comment by JasonGrace2282** [comment]
Of course, feel free too! If you have any questions, let me know :)

**Comment by JasonGrace2282** [comment]
Inspiration can be taken from Grant's commit:
https://github.com/3b1b/manim/commit/1372cf101cc6e97a863c0eb2a58a46155bd3a225

**Comment by NikhilaGurusinghe** [comment]
Hey I'm keen to code this up into a pull request — is this issue still open? :)

**Comment by JasonGrace2282** [comment]
Feel free too :)

**Comment by NikhilaGurusinghe** [comment]
Hey, I made a pull request for this issue (see https://github.com/ManimCommunity/manim/pull/3966), would appreciate any and all feedback! 😄
