### ISSUE TITLE
Tests for SVGMobject

### ISSUE THREAD

**Issue by yoshiask** [ManimCommunity/manim#355]
At the moment, there are no tests for checking that SVGs are being parsed and rendered properly using SVGMobject. Note that tests for the text-related Mobjects should be separate (e.g. TexMobject, TextMobject, Text...). These tests would help with PR #108 and prevent future bugs relating to SVG rendering.

**Comment by huguesdevimeux** [comment]
I completely agree. More tests is better that no tests. 

Unfortunatly, I'm not an expert on SVG on manim. What implementation would require SVG tests ?

**Comment by leotrs** [comment]
As we have currently no one working on improving SVG support, and it is not one of our current priorities, I am closing this issue for the time being.

This issue will be reopened when someone takes on the challenge to improve SVG support.

All issues (open or closed) related to SVG support can be found [in the SVG project board](https://github.com/ManimCommunity/manim/projects/8#card-49797664).

**Comment by MrMallIronmaker** [comment]
I've collected 14 SVGs from the Discord to develop SVG tests upon. I had planned to upload the SVGs, but Github issues didn't support that, so I've instead attached them to my fork of Manim. I hope it's not too much of a mess for someone else to download if they need to. https://github.com/ManimCommunity/manim/commit/303b8c2b88f7d1601419ce3010976139fa74c665
