### ISSUE TITLE
Rectangular Hyperbola is getting plotted with its asymptotes

### ISSUE THREAD

**Issue by Adidev-KGP** [ManimCommunity/manim#3551]
## Description of bug / unexpected behavior

When trying to plot a rectangular hyperbola, along with the hyperbola its asymptotes are also getting plotted and this happens in both cartesian parameters as well as polar parameters

## Expected behavior

Expected behaviour is just to see the rectangular hyperbola

## How to reproduce the issue

<details><summary>Code for reproducing the problem</summary>

```py
from manim import *

def getCurveInParametricForm(t):
     return np.array((1/np.cos(t), np.tan(t), 0))


class PlotAnyCurve(Scene):
    def construct(self):
        axis = Axes(x_range=[-8,8,1],
                    y_range=[-8,8,1],
                    x_length=12,
                    y_length=12,
                    axis_config={"include_numbers": True})
        curve1 = ParametricFunction(getCurveInParametricForm, t_range=[-4,4], discontinuities=[-0.5*PI, 0.5*PI])
        self.play(Create(axis))
        self.play(Create(curve1))

```

</details>

## Additional media files

<details><summary>Images/GIFs</summary>

</details>

## Logs
<details><summary>Terminal output</summary>

```
PASTE HERE OR PROVIDE LINK TO https://pastebin.com/ OR SIMILAR
```

</details>

## System specifications

<details><summary>System Details</summary>

- OS (with version, e.g., Windows 10 v2004 or macOS 10.15 (Catalina)):
- RAM:
- Python version (`python/py/python3 --version`):
- Installed modules (provide output from `pip list`):
```
PASTE HERE
```
</details>

<details><summary>LaTeX details</summary>

+ LaTeX distribution (e.g. TeX Live 2020):
+ Installed LaTeX packages:

</details>

<details><summary>FFMPEG</summary>

Output of `ffmpeg -version`:

```
PASTE HERE
```
</details>

**Comment by 0x13b** [comment]
Those extra 'lines' are not a buggy appearance of the asymptotes but a drawing feature due to using curves too close to discontinuities. Just pass `dt=0.1` to `ParametricPlot`. [RTFM](https://docs.manim.community/en/stable/reference/manim.mobject.graphing.functions.ParametricFunction.html?highlight=ParametricFunction#discontinuousexample) for details. You also may try `dt=0.001` and watch what happens.

**Comment by Adidev-KGP** [comment]
Thanks! That worked.
