### ISSUE TITLE
Multiplication of e.g. DOWN by a scalar is a type error on unreleased main branch

### ISSUE THREAD

**Issue by dandavison** [ManimCommunity/manim#3563]
## Description of bug / unexpected behavior
Multiplication of `DOWN` by a float is a type error on `main`

![image](https://github.com/ManimCommunity/manim/assets/52205/37cc592e-e257-4f50-8d46-754fd76978f2)

This is because `DOWN` is a `Vector3D` and on `main` this is a union type including a tuple type:

```python
Vector3D: TypeAlias = Point3D
Point3D: TypeAlias = Union[InternalPoint3D, tuple[float, float, float]]
```

whereas on `v0.18.0` it is a `Vector3`:

```python
Vector3: TypeAlias = npt.NDArray[PointDType]
```

## Expected behavior
Multiplication of `DOWN` by a float should not be a type error.

## System specifications
VSCode Insiders Version: 1.86.0-insider
Commit: 9621add46007f7a1ab37d1fce9bcdcecca62aeb0

**Comment by chopan050** [comment]
Hello, I made that change in an attempt to make vector type aliases more consistent with point type aliases, which were also an union between NumPy ndarrays and tuples of floats.
However, I see that this was not the correct move, so I just reverted that in a PR.
Thanks for submitting this issue!
