### ISSUE TITLE
PyLance doesn't import all symbols from manim

### ISSUE THREAD

**Issue by JasonGrace2282** [ManimCommunity/manim#3564]
See [this](https://discord.com/channels/581738731934056449/1023550532914266142/1191042075387506740) discussion on discord.

![image](https://github.com/ManimCommunity/manim/assets/110117391/3b47a116-abc7-4ce1-bd21-24c01a5dd006)
Source: https://code.visualstudio.com/docs/python/settings-reference#_code-analysis-settings at `packageIndexDepths`

We should probably add a `__all__`  or encourage VS Code users to modify their settings to accomodate this.

**Comment by JasonGrace2282** [comment]
Should be fixed after #3484 because of the `__all__`'s added? Someone will have to test, as I no longer use VS Code

**Comment by behackl** [comment]
How exactly can I check whether this is resolved?

**Comment by JasonGrace2282** [comment]
I'm not fully sure I remember. It's been a while since I used VS Code and experienced the issue. My best guess would be to start typing something nested deeply in manim and see if autocomplete picks it up.

**Comment by behackl** [comment]
![image](https://github.com/ManimCommunity/manim/assets/11851593/28d2c32a-7173-4191-b6ce-f3d23143a25f)

Seems fine to me?

**Comment by JasonGrace2282** [comment]
Yup, lgtm. We can close this issue now :)
