### ISSUE TITLE
3D Rendering With Overlapping Mobjects

### ISSUE THREAD

**Issue by sudgy** [ManimCommunity/manim#357]
Consider the following scene:

```python
class Issue3DRender(ThreeDScene):
    def construct(self):
        square1 = Square(
            shade_in_3d = True,
            fill_color = BLUE,
            fill_opacity = 0.5,
            stroke_width = 0
        )
        square2 = Square(
            shade_in_3d = True,
            fill_color = GREEN,
            fill_opacity = 0.5,
            stroke_width = 0
        )
        square1.rotate_about_origin(TAU/8, axis=UP)
        square2.rotate_about_origin(-TAU/8, axis=UP)
        self.add(square1, square2)
```

I would hope that on one side the green square would be on top and on the other side the blue square would be on top, but one is always drawn on top of the other:

![Issue3DRender](https://user-images.githubusercontent.com/20936595/91350120-1b2b6f80-e79b-11ea-92b3-e32304da1dc4.png)

Looking at the code, I realize that this seems basically impossible with the current state of things, but it would be nice if this could eventually get fixed.

**Comment by sudgy** [comment]
If anybody cares, I found an article that describes a way to deal with this particular problem: https://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.18.9286&rep=rep1&type=pdf.  It is OpenGL-specific, but the algorithm described there could probably be used in other situations.  The issue is that it's slow, but I know I would be willing to sacrifice speed for correctness.

**Comment by huguesdevimeux** [comment]
Very interesting. 
Unfortunately, I think we won't fix that right now as we prefer to fix the whole codebase first before doing this kind of things.  

> Looking at the code, I realize that this seems basically impossible with the current state of things, but it would be nice if this could eventually get fixed.

But, out of curiosity, could you develop that point?

**Comment by sudgy** [comment]
> Unfortunately, I think we won't fix that right now as we prefer to fix the whole codebase first before doing this kind of things.

I recognized that while making the issue, but I thought it would be nice to have this here for the future.
 
> > Looking at the code, I realize that this seems basically impossible with the current state of things, but it would be nice if this could eventually get fixed.
> 
> But, out of curiosity, could you develop that point?

There are two solutions that I can see to this issue:
1. Something like depth peeling, which would involve large changes in how things are rendered
2. Automatic splitting of Mobjects into chunks that don't overlap
Both of these solutions are quite complicated, and I know that there are already plans for rendering that make the first option impossible, at least for now.

**Comment by leotrs** [comment]
Unfortunately, I believe this is not within the realm of our possibilities in the near or medium future. Once we have better support for 3D stuff and/or have an OpenGL renderer, we can reopen this.

**Comment by leotrs** [comment]
Marking as wontfix for now
