### ISSUE TITLE
StopIteration Exception in earclip_triangulation

### ISSUE THREAD

**Issue by VerboseOutput** [ManimCommunity/manim#3570]
https://github.com/ManimCommunity/manim/blob/286f366a3584ae84d29d13c2a2c1f70b43752f95/manim/utils/space_ops.py#L758

if `len(detached_rings) == 1` it's possible for `j == ring[-1]`. In this case filter will return nothing and `next` will throw an exception.

**Comment by behackl** [comment]
Closed via #3574
