### ISSUE TITLE
Increasing Latex compatibility to make Manim more powerful

### ISSUE THREAD

**Issue by manimator-code** [ManimCommunity/manim#3577]
1. Can the original color and style of the Latex code be used?
2. Can /includegraphics be supported? ([support tikz,tikz-cd,includegraphics](https://github.com/3b1b/manim/pull/2058))
3. Can animation with Latex be supported? Like using xskak package to animate chess games.

**Comment by behackl** [comment]
1. Indirectly, yes -- the easiest way to do so would be to prepare your tex document outside of manim and compile it, turn the resulting dvi or pdf into an svg, and then import the svg via `SVGMobject`.
2. Images in SVGs are currently not supported. The workaround is to include the images yourself using `ImageMobject`, but this would be nice to have direct support for eventually. We are now tracking this in #3709.
3. Animations in PDFs are cursed and I don't think that we'll try to support importing animations from them, or exporting manim-generated output to them directly. (You can still, of course, work with GIFs yourself.)
