### ISSUE TITLE
MarkupText documentation: ul-tag should be changed to u-tag

### ISSUE THREAD

**Issue by dandavison** [ManimCommunity/manim#3578]
## Description of bug / unexpected behavior
This fails with `ValueError: Unknown tag 'ul' on line 1 char 13`
```python
class MarkupExample(Scene):
    def construct(self):
        text = MarkupText("<ul>underlined</ul>")
        self.add(text)
```

## Expected behavior
The docstring in the code indicates that it should produce underlined text: https://github.com/ManimCommunity/manim/blob/9a84ec6a45f2ff4254d2243116f84bac074db551/manim/mobject/text/text_mobject.py#L897

Note that this does work:

```python
class MarkupExample(Scene):
    def construct(self):
        text = MarkupText('<span underline="single">underlined</span>')
        self.add(text)
```

## System specifications
```
Manim Community v0.18.0
```

**Comment by uwezi** [comment]
According to the Pango documentation (Pango is the external python library used here), it should be `<u>...</u>` which actually works
```py
class MarkupExample(Scene):
    def construct(self):
        text = MarkupText("<u>underlined</u>")
        self.add(text)
```
