### ISSUE TITLE
ModuleNotFoundError: No module named 'pkg_resources'

### ISSUE THREAD

**Issue by quantomjona** [ManimCommunity/manim#3585]
#### Preliminaries

- [ ] I have followed the latest version of the
      [installation instructions](https://docs.manim.community/en/stable/installation.html).
- [ ] I have checked the [installation FAQ](https://docs.manim.community/en/stable/faq/installation.html) and my problem is either not mentioned there,
      or the solution given there does not help.

## Description of error

so i have installed it by using scoop, and when i run it on on visual studio code its doesn't find pkg_resources.
i tried reinstalling multiple times but it doesn't work.

## Installation logs

<details><summary>Terminal output</summary>

```
PASTE HERE OR PROVIDE LINK TO https://pastebin.com/ OR SIMILAR
```

</details>

## System specifications

<details><summary>System Details</summary>

- OS (with version, e.g., Windows 10 v2004 or macOS 10.15 (Catalina)):
- RAM:
- Python version (`python/py/python3 --version`):
- Installed modules (provide output from `pip list`):
```
PASTE HERE
```
</details>

<details><summary>LaTeX details</summary>

+ LaTeX distribution (e.g. TeX Live 2020):
+ Installed LaTeX packages:

</details>

<details><summary>FFMPEG</summary>

Output of `ffmpeg -version`:

```
PASTE HERE
```
</details>

**Comment by uwezi** [comment]
It's a Python package which is used by Manim and is not automatically pre-installed in some versions of Python.
It should be easily installable by using the following command on the terminal:
```pip install setuptools```

**Comment by emima94** [comment]
I am trying to install Manim community edition on my Mac (Apple M2 Pro chip). I have followed the guide for installation https://docs.manim.community/en/stable/installation/macos.html but I get the same error when running 

`manim -pql scene.py CreateCircle`
in the terminal i get

`Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/bin/manim", line 5, in <module>
    from manim.__main__ import main
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/manim/__init__.py", line 6, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'`

It looks like the module 'pkg_resources' is not found. I have tried to run:

`pip3 install setuptools`

and setuptools is also seen in `pip3 list`:

Package                Version
--------------- -----------
certifi                2023.11.17
charset-normalizer     3.3.2
click                  8.1.7
click-default-group    1.2.4
cloup                  2.1.2
Cython                 3.0.8
decorator              5.1.1
glcontext              2.5.0
idna                   3.6
isosurfaces            0.1.0
manim                  0.18.0
ManimPango             0.5.0
mapbox-earcut          1.0.1
markdown-it-py         3.0.0
mdurl                  0.1.2
moderngl               5.10.0
moderngl-window        2.4.4
multipledispatch       1.0.0
networkx               3.2.1
numpy                  1.26.3
Pillow                 9.5.0
pip                    23.3.2
pybind11               2.11.1
pycairo                1.25.1
pydub                  0.25.1
pyglet                 2.0.10
Pygments               2.17.2
pyobjc-core            10.1
pyobjc-framework-Cocoa 10.1
pyrr                   0.10.3
requests               2.31.0
rich                   13.7.0
scipy                  1.12.0
screeninfo             0.8.1
**setuptools             69.0.3**
skia-pathops           0.7.4
srt                    3.5.3
svgelements            1.9.6
tqdm                   4.66.1
typing_extensions      4.9.0
urllib3                2.1.0
watchdog               3.0.0
wheel                  0.42.0

When I run `pip3 -V`I get
`pip 23.3.2 from /opt/homebrew/lib/python3.11/site-packages/pip (python 3.11)`

which is also what I am supposed to get according to the installation tutorial note.

Thx for your help :)

**Comment by emima94** [comment]
Okay - after closing the terminal and opening a new terminal window, apparently it worked :p

**Comment by slrslr** [comment]
> Beginning Feb 8th, 2026 with setuptools>=82, pkg_resources has been [removed](https://github.com/pypa/setuptools/pull/5007).
> The quick fix is you should pin your setuptools to an older version - consider `pip install setuptools==81.0.0`

https://stackoverflow.com/a/79888812/

**Comment by flying-sheep** [comment]
why not just update `manim` instead, it doesn’t rely on `pkg_resources since [0.18.1](https://github.com/ManimCommunity/manim/releases/tag/v0.18.1)

**Comment by vladvisan** [comment]
> > Beginning Feb 8th, 2026 with setuptools>=82, pkg_resources has been [removed](https://github.com/pypa/setuptools/pull/5007).
> > The quick fix is you should pin your setuptools to an older version - consider `pip install setuptools==81.0.0`
> 
> https://stackoverflow.com/a/79888812/

Not all heroes wear capes

**Comment by danieltsoftware** [comment]
> > Beginning Feb 8th, 2026 with setuptools>=82, pkg_resources has been [removed](https://github.com/pypa/setuptools/pull/5007).
> > The quick fix is you should pin your setuptools to an older version - consider `pip install setuptools==81.0.0`
> 
> https://stackoverflow.com/a/79888812/

Wow thank you so much!

`pip install setuptools==81.0.0` did fix it on MacOS. (Edit: and also on Ubuntu! Sooo awesome)
