### ISSUE TITLE
Re-implement JSON encoder.

### ISSUE THREAD

**Issue by huguesdevimeux** [ManimCommunity/manim#361]
Mostly a reminder for myself. 

After long discussions with @Aathish04, we are going to try to implement our own JSon encoder for scene cahing. 
We used before the built-in one but it causes some un-fixable issues (without touching the builtin implementation), as #302 and some more. 

The pros are that it will be easier to debug and closer to the scene caching needs. 

Buuut it will be written in python, not in C (as in theory the builtin one is in theory the C version, (you can choose between both)), maybe it will be a little bit slower. I will benchmark.

**Comment by leotrs** [comment]
Are we sure this is the only possible path forward for the scene caching component? Before rewriting a piece of stdlib ourselves we would do well to consider all our options. I would like to know how it was decided that this was the path forward :)

**Comment by huguesdevimeux** [comment]
We've tried pretty much all libraries, without success. 
We won't rewrite the whole thing, there is just some piece of code that needs to be added to be fittable to our use. This is pretty quickly, as the JSon encoder is not very complex (even pretty simple)

And, it's just a try, not for the moment a real thing. If it is working, then all good, but I will be careful.

**Comment by huguesdevimeux** [comment]
Closing this. I found a workaround, not optimal though
