### ISSUE TITLE
Suppressing long terminal messages with from "DEBUG"  channel

### ISSUE THREAD

**Issue by kolibril13** [ManimCommunity/manim#363]
When I run this script, I get a quit long log from the terminal: 
```python
class Final(Scene):
    def construct(self):
        img1= ImageMobject("temp.png")
        self.add(img1)
```
```console
DEBUG     STREAM b'IHDR' 16 13                             PngImagePlugin.py:153
DEBUG     STREAM b'sBIT' 41 4                              PngImagePlugin.py:153
DEBUG     b'sBIT' 41 4 (unknown)                           PngImagePlugin.py:660
DEBUG     STREAM b'tEXt' 57 25                             PngImagePlugin.py:153
DEBUG     STREAM b'IDAT' 94 8192                           PngImagePlugin.py:153
```
This log is caused by this line  `image = Image.open(path).convert(self.image_mode)` in image_mobject.py
When working with lots of images, this is a lot of spam in the output console.
Any ideas to suppress this?

When working with one or two images, I think this is really not that much of an issue, but when working with 200-500 images, e.g. like here:
```py
import matplotlib.pyplot as plt


def get_image(image_name):
    img = ImageMobject(image_name).scale(4.5)
    return img


def my_function(amplitude, x):
    return amplitude * np.sin(x)


def get_image_plot(amplitude, x):
    plt.cla()
    plt.rcParams['figure.dpi'] = 400
    plt.ylim(-1, 1)
    plt.plot(x, my_function(amplitude, x))
    plt.savefig("tmp.png", dpi=400)
    img = get_image("tmp.png")
    return img


class ConnectingMatplotlib(Scene):
    def construct(self):
        x_values = np.linspace(0, 30, 400)

        amp1 = 0.5
        amp2 = 1
        tr_amplitude = ValueTracker(amp1)
        image = get_image_plot(amp1, x_values)
        self.add(image)

        def update_image(mob):
            new_mob = get_image_plot(
                tr_amplitude.get_value(),
                x_values
            )
            mob.become(new_mob)

        image.add_updater(update_image)

        self.play(tr_amplitude.set_value, amp2, run_time=3)
```
This gets a little annoying.

**Comment by leotrs** [comment]
Do these messages appear only on a DEBUG level?

**Comment by kolibril13** [comment]
Yes.
It does.
Is there an option to mute the DEBUG level?

**Comment by leotrs** [comment]
The default should be INFO, I don't know why you are seeing debug-level messages. @naveen521kk?

**Comment by naveen521kk** [comment]
Don't blame me as I just did the colour output and nothing else. @azarzadavila was the one who created verbose. I think this would be a quick PR.

**Comment by leotrs** [comment]
I'm not blaming you, I'm asking you for your opinion.

**Comment by kolibril13** [comment]
I was also only surprised by the long output messages and I am glad that the two of you responded!

> I think this would be a quick PR.
 
 @naveen521kk : As I don't know much of logging,  do you mind making this PR? That would be great!

**Comment by kolibril13** [comment]
Update: 
One can use e.g. `-v INFO ` as a flag to suppress the manim DEBUG messages, however side packages will still show you their debug messages. They can be e.g. suppressed when adding in the logger file:
```
logging.getLogger("PIL").setLevel(logging.INFO)
logging.getLogger("matplotlib").setLevel(logging.INFO)
```
