### ISSUE TITLE
Hope to add real-time rendering and preview functions

### ISSUE THREAD

**Issue by MarkHoo** [ManimCommunity/manim#3636]
## Description of proposed feature

I hope to add real-time rendering and preview functions. For details, please refer to the following video example.

## How can the new feature be used?

https://github.com/ManimCommunity/manim/assets/30554560/700be241-80bf-4ffc-8d1e-f451f805a242

**Comment by uwezi** [comment]
Have a look at Manim-sideview ([https://github.com/Rickaym/Manim-Sideview#readme](https://github.com/Rickaym/Manim-Sideview#readme)) and the interactivity of the opengl-renderer in this video: [https://youtu.be/KeXBLPC1tns?si=HW-UdW1R6kUDieHV](https://youtu.be/KeXBLPC1tns?si=HW-UdW1R6kUDieHV)
