### ISSUE TITLE
Add a picture in the scene, the picture position changed incorrectly when the camera was moving

### ISSUE THREAD

**Issue by tianmaoyu** [ManimCommunity/manim#3646]
## Description of bug / unexpected behavior

Add a picture in the scene, the picture position changed incorrectly when the camera was moving

You can watch my video

```py
class AddImage(ThreeDScene):
    def construct(self):
        axes = ThreeDAxes()
        img = ImageMobject("images/test.jpg")
        img.shift(UP * 3 + RIGHT * 3)
        center= img.get_center()
        print(center)
        self.add(axes, img)
        self.move_camera(phi=85 * DEGREES, theta=30 * DEGREES, frame_center=np.array([-3, 3, 0]), run_time=3)
        
with tempconfig({"preview": True,  "quality": "low_quality", "renderer": "cairo"}):
    AddImage().render()
```

https://github.com/ManimCommunity/manim/assets/10215431/c11997e8-59a8-44f0-92f8-2cc5475d2a99

![test](https://github.com/ManimCommunity/manim/assets/10215431/b561c26a-f42b-428a-b767-f06702a67bfd)

**Comment by chopan050** [comment]
Closing this issue, initially because the "buggy 3D rotation" part is a duplicate of #2412. However, I noticed that there's also a "buggy movement" part, which is a different issue and also a duplicate of #3146.
