### ISSUE TITLE
Implementing structured logs in JSON format

### ISSUE THREAD

**Issue by huguesdevimeux** [ManimCommunity/manim#365]
This is mostly for the tests. The idea is to output all the logs in a JSON format, so it will be much much easier to compare them (we won't have to deal with the log_widht, etc). 

This is fairly easy to implement. See https://docs.python.org/3/howto/logging-cookbook.html#implementing-structured-logging

**Comment by leotrs** [comment]
It sounds like a Good Idea (TM), but also I don't think we want to be outputting JSONs all over the console for the user to read those. Can we have the logs be JSONs but print them to console with a nice __repr__?

**Comment by huguesdevimeux** [comment]
The idea thing would be to not touch the things printed in the console, and in the meantime saving the logs in a `.json`.
