### ISSUE TITLE
Incorrect Output settings documentation

### ISSUE THREAD

**Issue by JasonGrace2282** [ManimCommunity/manim#3651]
The docs at [Manim's Output Settings](https://docs.manim.community/en/stable/tutorials/output_and_config.html#some-command-line-flags) are outdated. A couple examples:
> When executing the command `manim -pql scene.py SquareToCircle` it was necessary to specify which Scene class to render.

>  If you want your animations in .gif format instead, use the -i flag.

**Comment by HairlessVillager** [comment]
Hello! I'd glad to be responsible for improving this outdated document. I would like to confirm with you that you have added an anchor for `#some-command-line-flags-in-the-link`. Does this mean that this issue is only considering fixing this section?

**Comment by JasonGrace2282** [comment]
Hey hey hey, thanks for taking on this issue!

> Does this mean that this issue is only considering fixing this section?

Not necessarily, no. If you find anything wrong in any of the other sections, feel please correct that, too!
