### ISSUE TITLE
Difference between pixel width, pixel hiegth, frame_widht, frame_height, frame_size etc.

### ISSUE THREAD

**Issue by Srikar-Ganta** [ManimCommunity/manim#3658]
can someone explain the difference b/w 
pixel_width
pixel_heigth
media_width
frame_y_radius
frame_x_radius
frame_width
frame_height
frame_size
frame_rate
aspect_ratio

can someone explain these in detail

**Comment by uwezi** [comment]
Why are you not using the help-forum on Discord to which you were pointed?

What you are posting here is not **issues** but simply questions about the existing functionality in Manim.
