### ISSUE TITLE
Matrix with Mathtex

### ISSUE THREAD

**Issue by Srikar-Ganta** [ManimCommunity/manim#3661]
I tried to include mathtex in matrix it is not working
I tried adding x^2 then I am getting compilation error 
```
class MatrixWithMathtex(Scene):
    def construct(self):
        X = MathTex(r'x^2')
        m0 = Matrix(
            [[X,1], [2,2]],
            left_bracket="[",
            right_bracket="]"
            ).to_edge(LEFT)
        self.add(m0)
```
When I replace 
`X = MathTex(r'x^2')`
 with 
`X = MathTex(r'5x')`
 getting ouput as below. 

![image](https://github.com/ManimCommunity/manim/assets/25774984/1f17cd03-839f-4474-b6cc-d1dc838025dc)

How to include a MathTex in the matrix.
Can someone help me.

**Comment by uwezi** [comment]
again - this was never an **issue** but just a user question...
