### ISSUE TITLE
Graph labels not working as expected when passing "vertex_config"

### ISSUE THREAD

**Issue by seanpden** [ManimCommunity/manim#3662]
## Description of bug / unexpected behavior

When creating a Graph object and setting the "labels" argument as "True", the labels render as expected. However, when you add any value to the "vertex_config" argument, the resulting render only uses the final value of the "vertices" argument and is not formatted correctly. 

## Expected behavior

The graph should render as normal, only making changes to the specified keys in the "vertex_config" argument.

## How to reproduce the issue

<details><summary>Code for reproducing the problem</summary>

```py
import manim as mn

 class KonigsbergBridgeWorking(mn.Scene):
    def construct(self):
        self.camera.background_color = mn.DARKER_GREY

        title_text = mn.Text(text="KonigsbergBridgeWorking", color=mn.WHITE).shift(
            mn.UP * 3.5
        )

        vertices: list = [0, 1, 2, 3]
        edges: list = [(0, 1), (0, 2), (0, 3), (1, 0), (1, 2), (2, 3), (3, 0)]

        graph = mn.Graph(
            vertices=vertices,
            edges=edges,
            labels=True,
            edge_type=mn.Line,
            edge_config=dict.fromkeys(
                edges, {"path_arc": mn.PI / 4, "color": mn.WHITE}
            ),
        )

        self.play(mn.AddTextLetterByLetter(title_text))

        self.play(mn.Create(graph))

        self.wait(3)


class KonigsbergBridgeNotWorking(mn.Scene):
    def construct(self):
        self.camera.background_color = mn.DARKER_GREY

        title_text = mn.Text(text="KonigsbergBridgeNotWorking", color=mn.WHITE).shift(
            mn.UP * 3.5
        )

        vertices: list = [0, 1, 2, 3]
        edges: list = [(0, 1), (0, 2), (0, 3), (1, 0), (1, 2), (2, 3), (3, 0)]

        graph = mn.Graph(
            vertices=vertices,
            edges=edges,
            labels=True,
            vertex_config=dict.fromkeys(vertices, {"color": mn.PINK, "radius": 0.1}),
            edge_type=mn.Line,
            edge_config=dict.fromkeys(
                edges, {"path_arc": mn.PI / 4, "color": mn.WHITE}
            ),
        )

        self.play(mn.AddTextLetterByLetter(title_text))

        self.play(mn.Create(graph))

        self.wait(3)


class KonigsbergBridgeNotWorkingAlt(mn.Scene):
    def construct(self):
        self.camera.background_color = mn.DARKER_GREY

        title_text = mn.Text(
            text="KonigsbergBridegNotWorkingAlt",
            color=mn.WHITE,
            font="JetBrainsMono NFM Medium",
        ).shift(mn.UP * 3.5)

        vertices: list = [0, 1, 2, 3]
        edges: list = [(0, 1), (0, 2), (0, 3), (1, 0), (1, 2), (2, 3), (3, 0)]
        labels = "0123"
        label_dict = {i: label for i, label in zip(vertices, labels)}
        print(label_dict)

        graph = mn.Graph(
            vertices=vertices,
            edges=edges,
            layout="circular",
            labels=label_dict,
            vertex_type=mn.LabeledDot,
            vertex_config=dict.fromkeys(
                vertices,
                {"color": mn.PINK},  # , "radius": 0.1}
            ),
            edge_type=mn.Line,
            edge_config=dict.fromkeys(
                filter(lambda edge: edge != (0, 2), edges),
                {"path_arc": mn.PI / 4, "color": mn.WHITE},
            )
            | {(0, 2): {"color": mn.WHITE}},
        )

        self.play(mn.AddTextLetterByLetter(title_text))

        self.play(mn.Create(graph))

        self.wait(3)


class KonigsbergBridge(mn.Scene):
    def construct(self):
        self.camera.background_color = COLORS.base.hex

        title_text = mn.Text(
            text="Konigsberg Bridge",
            color=COLORS.text.hex,
            font="JetBrainsMono NFM Medium",
        ).shift(mn.UP * 3.5)

        vertices: list = [0, 1, 2, 3]
        edges: list = [(0, 1), (0, 2), (0, 3), (1, 0), (1, 2), (2, 3), (3, 0)]
        labels = "0123"
        label_dict = {i: label for i, label in zip(vertices, labels)}
        print(label_dict)

        graph = mn.Graph(
            vertices=vertices,
            edges=edges,
            layout="circular",
            labels=label_dict,
            vertex_type=mn.LabeledDot,
            vertex_config=dict.fromkeys(
                vertices,
                {"color": COLORS.pink.hex},  # , "radius": 0.1}
            ),
            edge_type=mn.Line,
            edge_config=dict.fromkeys(
                filter(lambda edge: edge != (0, 2), edges),
                {"path_arc": mn.PI / 4, "color": COLORS.text.hex},
            )
            | {(0, 2): {"color": COLORS.text.hex}},
        )

        self.play(mn.AddTextLetterByLetter(title_text))

        self.play(mn.Create(graph))

        self.wait(3)


if __name__ == "__main__":
    scene = KonigsbergBridgeWorking()
    scene.render(True)

    scene = KonigsbergBridgeNotWorking()
    scene.render(True)

    scene = KonigsbergBridgeNotWorkingAlt()
    scene.render(True)

```

</details>

## Additional media files

<details><summary>Images/GIFs</summary>

Working:
![image](https://github.com/ManimCommunity/manim/assets/61769940/cfb4169d-54b0-453c-ad14-9497d126902b)

Not Working:
![image](https://github.com/ManimCommunity/manim/assets/61769940/daed4bd3-3bb6-4ffd-bf67-42f66defd4de)

Not Working Alternative:
![image](https://github.com/ManimCommunity/manim/assets/61769940/cfbdb585-2453-4dd7-b502-ca3926f0f591)

</details>

## Logs
<details><summary>Terminal output</summary>

```
https://pastebin.com/8dDRJMNJ
```

</details>

## System specifications

<details><summary>System Details</summary>

- OS (with version, e.g., Windows 10 v2004 or macOS 10.15 (Catalina)): Windows 11 Enterprise 23H2
- RAM: 32GB
- Python version (`python/py/python3 --version`): 3.12.2
- Installed modules (provide output from `pip list`):
```
catppuccin==2.2.0
certifi==2024.2.2
charset-normalizer==3.3.2
click==8.1.7
click-default-group==1.2.4
cloup==2.1.2
colorama==0.4.6
decorator==5.1.1
glcontext==2.5.0
idna==3.6
isosurfaces==0.1.0
manim==0.18.0
ManimPango==0.5.0
mapbox-earcut==1.0.1
markdown-it-py==3.0.0
mdurl==0.1.2
moderngl==5.10.0
moderngl-window==2.4.4
multipledispatch==1.0.0
networkx==3.2.1
numpy==1.26.4
Pillow==9.5.0
pycairo==1.26.0
pydub==0.25.1
pyglet==2.0.14
Pygments==2.17.2
pyrr==0.10.3
requests==2.31.0
rich==13.7.1
scipy==1.12.0
screeninfo==0.8.1
setuptools==69.2.0
skia-pathops==0.8.0.post1
srt==3.5.3
svgelements==1.9.6
tqdm==4.66.2
typing_extensions==4.10.0
urllib3==2.2.1
watchdog==3.0.0
```
</details>

<details><summary>LaTeX details</summary>

+ LaTeX distribution (e.g. TeX Live 2020):MiKTeX Console 4.12
+ Installed LaTeX packages:

Mode  Size Date Modified Name
-a---  32k  6 Jun  2021  ∩à¢ amsfonts.tpm
-a--- 1.8k 16 Jun  2023  ∩à¢ amsmath.tpm
-a--- 9.0k 20 Jan 06:44  ∩à¢ arabi.tpm
-a--- 1.0k  6 Jun  2021  ∩à¢ atbegshi.tpm
-a--- 1.1k  6 Jun  2021  ∩à¢ atveryend.tpm
-a--- 1.3k  6 Jun  2021  ∩à¢ babel-english.tpm
-a---  51k 10 Feb 14:17  ∩à¢ babel.tpm
-a--- 1.0k 17 Mar  2023  ∩à¢ biber-windows-x64.tpm
-a--- 8.9k 24 Jan  2014  ∩à¢ cm.tpm
-a--- 3.4k  5 Feb  2020  ∩à¢ dvips.tpm
-a--- 1.2k 16 Feb 11:19  ∩à¢ fontspec.tpm
-a--- 1.2k  7 Feb  2022  ∩à¢ iftex.tpm
-a--- 1.9k 20 Feb  2021  ∩à¢ knuth-lib.tpm
-a--- 1.4k 17 Mar 05:01  ∩à¢ l3backend.tpm
-a--- 2.1k 17 Mar 05:02  ∩à¢ l3kernel.tpm
-a--- 1.6k 17 Mar 05:02  ∩à¢ l3packages.tpm
-a--- 1.3k  8 Mar 10:58  ∩à¢ latex-firstaid.tpm
-a--- 3.4k 30 Jun  2009  ∩à¢ latex-fonts.tpm
-a--- 2.7k 23 Nov  2023  ∩à¢ latex-tools.tpm
-a--- 6.4k 20 Jan 06:21  ∩à¢ ltxbase.tpm
-a---  818  6 Jun  2021  ∩à¢ luatex85.tpm
-a---  813 10 Mar 02:57  ∩à¢ miktex-arctrl-bin-x64-2.9.tpm
-a--- 1.1k 10 Mar 02:57  ∩à¢ miktex-asymptote-bin-x64-2.9.tpm
-a--- 1.7k 10 Mar 02:57  ∩à¢ miktex-autosp-bin-x64-2.9.tpm
-a--- 1.1k 10 Mar 02:57  ∩à¢ miktex-axohelp-bin-x64-2.9.tpm
-a---  958 10 Mar 02:57  ∩à¢ miktex-bibarts-bin-x64-2.9.tpm
-a---  845 10 Mar 02:57  ∩à¢ miktex-bibtex-bin-x64-2.9.tpm
-a---  926 10 Mar 02:57  ∩à¢ miktex-bibtex8bit-bin-x64-2.9.tpm
-a---  860 10 Mar 02:57  ∩à¢ miktex-bzip2-bin-x64-2.9.tpm
-a--- 1.8k 10 Mar 02:57  ∩à¢ miktex-cairo-bin-x64-2.9.tpm
-a---  857 10 Mar 02:57  ∩à¢ miktex-chktex-bin-x64-2.9.tpm
-a--- 1.2k 10 Mar 02:57  ∩à¢ miktex-cjkutils-bin-x64-2.9.tpm
-a--- 2.9k 15 Apr  2023  ∩à¢ miktex-config-2.9.tpm
-a---  908 10 Mar 02:57  ∩à¢ miktex-console-bin-x64-2.9.tpm
-a--- 1.8k 10 Mar 02:57  ∩à¢ miktex-curl-bin-x64-2.9.tpm
-a--- 1.1k 10 Mar 02:57  ∩à¢ miktex-cweb-bin-x64-2.9.tpm
-a---  875 10 Mar 02:57  ∩à¢ miktex-devnag-bin-x64-2.9.tpm
-a---  857 10 Mar 02:57  ∩à¢ miktex-dvicopy-bin-x64-2.9.tpm
-a---  900 10 Mar 02:57  ∩à¢ miktex-dvipdfmx-bin-x64-2.9.tpm
-a--- 1.1k 10 Mar 02:57  ∩à¢ miktex-dvipng-bin-x64-2.9.tpm
-a---  884 10 Mar 02:57  ∩à¢ miktex-dvips-bin-x64-2.9.tpm
-a---  760  9 Apr  2017  ∩à¢ miktex-dvips.tpm
-a--- 1.4k 10 Mar 02:57  ∩à¢ miktex-dvisvgm-bin-x64-2.9.tpm
-a---  860 10 Mar 02:57  ∩à¢ miktex-epstopdf-bin-x64-2.9.tpm
-a--- 1.1k 10 Mar 02:57  ∩à¢ miktex-expat-bin-x64-2.9.tpm
-a---  856 10 Mar 02:57  ∩à¢ miktex-findtexmf-bin-x64-2.9.tpm
-a---  873 10 Mar 02:57  ∩à¢ miktex-fmt-bin-x64-2.9.tpm
-a--- 1.3k 10 Mar 02:57  ∩à¢ miktex-fontconfig-bin-x64-2.9.tpm
-a---  749  4 Nov  2016  ∩à¢ miktex-fontconfig.tpm
-a---  842 10 Mar 02:57  ∩à¢ miktex-fonts-bin-x64-2.9.tpm
-a---  942 10 Mar 02:57  ∩à¢ miktex-freeglut-bin-x64-2.9.tpm
-a--- 1.1k 10 Mar 02:57  ∩à¢ miktex-freetype2-bin-x64-2.9.tpm
-a---  880 10 Mar 02:57  ∩à¢ miktex-fribidixetex-bin-x64-2.9.tpm
-a--- 1.3k 10 Mar 02:57  ∩à¢ miktex-gd-bin-x64-2.9.tpm
-a--- 1.4k 25 Sep  2018  ∩à¢ miktex-ghostscript-bin-x64.tpm
-a--- 1.3k 10 Mar 02:57  ∩à¢ miktex-graphite2-bin-x64-2.9.tpm
-a--- 1.1k 10 Mar 02:57  ∩à¢ miktex-gregorio-bin-x64-2.9.tpm
-a---  837 10 Mar 02:57  ∩à¢ miktex-gsf2pk-bin-x64-2.9.tpm
-a--- 1.1k 10 Mar 02:57  ∩à¢ miktex-harfbuzz-bin-x64-2.9.tpm
-a---  984 10 Mar 02:57  ∩à¢ miktex-hitex-bin-x64.tpm
-a--- 1.1k 10 Mar 02:57  ∩à¢ miktex-hunspell-bin-x64-2.9.tpm
-a--- 1.1k 28 Dec  2023  ∩à¢ miktex-icu-bin-x64.tpm
-a---  890 10 Mar 02:57  ∩à¢ miktex-jpeg-bin-x64-2.9.tpm
-a---  877 10 Mar 02:57  ∩à¢ miktex-kpathsea-bin-x64-2.9.tpm
-a---  869 10 Mar 02:57  ∩à¢ miktex-lacheck-bin-x64-2.9.tpm
-a--- 1.4k 10 Mar 02:57  ∩à¢ miktex-lcdf-typetools-bin-x64-2.9.tpm
-a--- 1.0k 10 Mar 02:57  ∩à¢ miktex-libressl-bin-x64-2.9.tpm
-a--- 1.0k 10 Mar 02:57  ∩à¢ miktex-log4cxx-bin-x64-2.9.tpm
-a--- 1.5k 10 Mar 02:57  ∩à¢ miktex-lua53-bin-x64-2.9.tpm
-a--- 1.3k 10 Mar 02:57  ∩à¢ miktex-luatex-bin-x64-2.9.tpm
-a---  833 10 Mar 02:57  ∩à¢ miktex-lzma-bin-x64-2.9.tpm
-a--- 1.0k 10 Mar 02:57  ∩à¢ miktex-m-tx-bin-x64-2.9.tpm
-a---  896 10 Mar 02:57  ∩à¢ miktex-makeindex-bin-x64-2.9.tpm
-a---  870 10 Mar 02:57  ∩à¢ miktex-md5-bin-x64-2.9.tpm
-a---  854 10 Mar 02:57  ∩à¢ miktex-metafont-bin-x64-2.9.tpm
-a---  847 10 Mar 02:57  ∩à¢ miktex-metapost-bin-x64-2.9.tpm
-a---  932 10 Mar 02:57  ∩à¢ miktex-mfware-bin-x64-2.9.tpm
-a--- 1.6k  8 Mar 10:58  ∩à¢ miktex-misc.tpm
-a--- 1.1k 10 Mar 02:57  ∩à¢ miktex-mktex-bin-x64-2.9.tpm
-a---  914 10 Mar 02:57  ∩à¢ miktex-mo-bin-x64-2.9.tpm
-a---  891 10 Mar 02:57  ∩à¢ miktex-mpmcli-bin-x64-2.9.tpm
-a---  928 10 Mar 02:57  ∩à¢ miktex-mspack-bin-x64-2.9.tpm
-a---  838 10 Mar 02:57  ∩à¢ miktex-mthelp-bin-x64-2.9.tpm
-a---  846 10 Mar 02:57  ∩à¢ miktex-mtprint-bin-x64-2.9.tpm
-a--- 1.1k 10 Mar 02:57  ∩à¢ miktex-omegaware-bin-x64-2.9.tpm
-a---  781 10 Mar 02:57  ∩à¢ miktex-patgen-bin-x64.tpm
-a---  935 10 Mar 02:57  ∩à¢ miktex-pdftex-bin-x64-2.9.tpm
-a---  837 10 Nov  2016  ∩à¢ miktex-pdftex.tpm
-a--- 1.0k 10 Mar 02:57  ∩à¢ miktex-pixman-bin-x64-2.9.tpm
-a--- 1.3k 10 Mar 02:57  ∩à¢ miktex-pmx-bin-x64-2.9.tpm
-a---  978 10 Mar 02:57  ∩à¢ miktex-png-bin-x64-2.9.tpm
-a--- 1.5k 10 Mar 02:57  ∩à¢ miktex-poppler-bin-x64-2.9.tpm
-a--- 1.0k 10 Mar 02:57  ∩à¢ miktex-popt-bin-x64-2.9.tpm
-a---  961 10 Mar 02:57  ∩à¢ miktex-posix-bin-x64-2.9.tpm
-a---  829 10 Mar 02:57  ∩à¢ miktex-ps2pk-bin-x64-2.9.tpm
-a--- 1.1k 10 Mar 02:57  ∩à¢ miktex-psutils-bin-x64-2.9.tpm
-a--- 1.1k 10 Mar 02:57  ∩à¢ miktex-ptex-bin-x64.tpm
-a--- 1.2k 27 Jan 08:47  ∩à¢ miktex-qt6-bin-x64.tpm
-a--- 1.9k 10 Mar 02:57  ∩à¢ miktex-runtime-bin-x64-2.9.tpm
-a---  852 10 Mar 02:57  ∩à¢ miktex-synctex-bin-x64-2.9.tpm
-a---  867 10 Mar 02:57  ∩à¢ miktex-tdsutil-bin-x64.tpm
-a---  877 10 Mar 02:57  ∩à¢ miktex-teckit-bin-x64-2.9.tpm
-a---  831 10 Mar 02:57  ∩à¢ miktex-tex-bin-x64-2.9.tpm
-a---  864 10 Mar 02:57  ∩à¢ miktex-tex2xindy-bin-x64-2.9.tpm
-a---  900 10 Mar 02:57  ∩à¢ miktex-tex4ht-bin-x64-2.9.tpm
-a---  834 10 Mar 02:57  ∩à¢ miktex-texify-bin-x64-2.9.tpm
-a---  947 10 Mar 02:57  ∩à¢ miktex-texware-bin-x64-2.9.tpm
-a---  893 10 Mar 02:57  ∩à¢ miktex-texworks-bin-x64-2.9.tpm
-a---  946 10 Mar 02:57  ∩à¢ miktex-ttf2pk2-bin-x64-2.9.tpm
-a--- 3.1k  5 Dec  2021  ∩à¢ miktex-ucrt-bin-x64.tpm
-a---  837 10 Mar 02:57  ∩à¢ miktex-upmendex-bin-x64.tpm
-a--- 1.0k 10 Mar 02:57  ∩à¢ miktex-uriparser-bin-x64-2.9.tpm
-a--- 1.6k  5 Dec  2021  ∩à¢ miktex-vc140-bin-x64.tpm
-a---  816 10 Mar 02:57  ∩à¢ miktex-web-bin-x64-2.9.tpm
-a---  856 10 Mar 02:57  ∩à¢ miktex-xetex-bin-x64-2.9.tpm
-a---  676 19 Jun  2015  ∩à¢ miktex-xindy-bin-x64.tpm
-a---  871 10 Mar 02:57  ∩à¢ miktex-xml2pmx-bin-x64.tpm
-a---  930 10 Mar 02:57  ∩à¢ miktex-yap-bin-x64-2.9.tpm
-a--- 1.1k 12 Jan  2018  ∩à¢ miktex-zip-bin-x64.tpm
-a--- 1.1k 10 Mar 02:57  ∩à¢ miktex-zlib-bin-x64-2.9.tpm
-a---  876 10 Mar 02:57  ∩à¢ miktex-zzip-bin-x64-2.9.tpm
-a--- 1.4k 28 Jul  2023  ∩à¢ pdftex.tpm
-a--- 1.4k 20 Jan 06:22  ∩à¢ preview.tpm
-a--- 1.5k 17 Oct  2022  ∩à¢ standalone.tpm
-a--- 2.5k  3 Nov  2016  ∩à¢ tetex.tpm
-a--- 1.7k 23 Nov  2023  ∩à¢ tex-ini-files.tpm
-a--- 2.5k 22 Sep  2023  ∩à¢ unicode-data.tpm
-a--- 1.6k 26 Jun  2022  ∩à¢ xkeyval.tpm
</details>

<details><summary>FFMPEG</summary>

Output of `ffmpeg -version`:

```
ffmpeg version 6.1.1-full_build-www.gyan.dev Copyright (c) 2000-2023 the FFmpeg developers
built with gcc 12.2.0 (Rev10, Built by MSYS2 project)
configuration: --enable-gpl --enable-version3 --enable-static --pkg-config=pkgconf --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libaribb24 --enable-libaribcaption --enable-libdav1d --enable-libdavs2 --enable-libuavs3d --enable-libzvbi --enable-librav1e --enable-libsvtav1 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libaom --enable-libjxl --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-libharfbuzz --enable-liblensfun --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-dxva2 --enable-d3d11va --enable-libvpl --enable-libshaderc --enable-vulkan --enable-libplacebo --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libcodec2 --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
libavutil      58. 29.100 / 58. 29.100
libavcodec     60. 31.102 / 60. 31.102
libavformat    60. 16.100 / 60. 16.100
libavdevice    60.  3.100 / 60.  3.100
libavfilter     9. 12.100 /  9. 12.100
libswscale      7.  5.100 /  7.  5.100
libswresample   4. 12.100 /  4. 12.100
libpostproc    57.  3.100 / 57.  3.100
```
</details>

**Comment by behackl** [comment]
That's a fun one -- and actually not really the fault of `Graph`; it's a consequence of the behavior of `dict.fromkeys`. You can check that this version (after slightly increasing the vertex radius):

```py
import manim as mn
class KonigsbergBridgeNotWorking(mn.Scene):
    def construct(self):
        self.camera.background_color = mn.DARKER_GREY

        title_text = mn.Text(text="KonigsbergBridgeNotWorking", color=mn.WHITE).shift(
            mn.UP * 3.5
        )

        vertices: list = [0, 1, 2, 3]
        edges: list = [(0, 1), (0, 2), (0, 3), (1, 0), (1, 2), (2, 3), (3, 0)]

        graph = mn.Graph(
            vertices=vertices,
            edges=edges,
            labels=True,
            vertex_config={v: {"color": mn.PINK, "radius": 0.3} for v in vertices},
            edge_type=mn.Line,
            edge_config={e: {"path_arc": mn.PI / 4, "color": mn.WHITE} for e in edges},
        )

        self.play(mn.AddTextLetterByLetter(title_text))

        self.play(mn.Create(graph))

        self.wait(3)
```

The issue with `dict.fromkeys` is that if you use a dictionary (as a complex data type) as a value, the separate values will actually just be shallow copies of each other; they reference the same dict under the hood. Here is a plain example illustrating this behavior:

```py
>>> conf = {'x': 1, 'y': 2}
>>> dct = dict.fromkeys([7, 8], conf); dct
{7: {'x': 1, 'y': 2}, 8: {'x': 1, 'y': 2}}
>>> dct[7]['x'] = 42
>>> dct
{7: {'x': 42, 'y': 2}, 8: {'x': 42, 'y': 2}}
```

The `Graph` mobject doesn't have any safeguards to fix this internally, the identical config dicts appear to mess things up in a weird way. You can check that by printing the value of `graph._vertex_config`; its entries will all be the exact same dict.

**Comment by seanpden** [comment]
Wow, just looked at the [docs](https://docs.python.org/3/library/stdtypes.html#dict.fromkeys) and your example - you're totally right. You learn something new every day. With the fault being ```dict.fromkeys``` passing a reference to the same instance, I'd wager that it's not worth it to put a check in the ```Graph``` constuctor. 

Thanks for the help! You think this one can be closed out?
