### ISSUE TITLE
USE GPU to render

### ISSUE THREAD

**Issue by semikernel** [ManimCommunity/manim#3663]
## Description of proposed feature

In order to enhance the render speed, can we use GPU to render?
## How can the new feature be used?

In the command line, we can use GPU to speed up rendering
## Additional comments

Maybe only opengl can do that.

**Comment by krebsnebel4441** [comment]
As far as I know there is an opengl renderer included in manim.
```manim -pql  --renderer opengl file.py Scene```

**Comment by MrDiver** [comment]
We already have a OpenGL renderer.
