### ISSUE TITLE
Add params / flags for `scene.render()`

### ISSUE THREAD

**Issue by ReneTC** [ManimCommunity/manim#3665]
## Description of proposed feature
Instead of the terminal, it is possible to use 
```
  manim_scene = MyScene()
  manim_scene.render()
```
and execute the python file. This is extremely useful for me, enabling me to use manim in a custom python package.

However, it is not possible to render the videos transparent this way. Like
```
  manim_scene = MyScene()
  manim_scene.render(transparent=True)
```
I know it is possible with the terminal, and you add the `-t` flag

I've been advised in the discord that you an use
```
    with tempconfig({"quality": "low_quality", 
                     "preview": False, 
                     "transparent": True,
                     "disable_caching": False
                     }):
        manim_scene = MyScene()
        manim_scene.render()
```
somehow, but I haven't had luck implemented that in my project.

**Comment by MrDiver** [comment]
What is the issue? Any more details on what doesn't work ?

**Comment by JasonGrace2282** [comment]
No response from OP
