### ISSUE TITLE
Manim doesn't find the scene inside of the driver file when I run manim -qpl main.py (Is something wrong or outdated?)

### ISSUE THREAD

**Issue by shyamalschandra** [ManimCommunity/manim#3667]
## Description of bug / unexpected behavior
Manim doesn't find the scene instead of the driver file when I run manim -qpl main.py (Is something wrong or outdated?)

## Expected behavior
The program, manim, should just work fine.

## How to reproduce the issue
pip3 install manim
... (yada yada yada)
manim -qpl main.py 

<details><summary>Code for reproducing the problem</summary>

```py
from manim import *
class FourQuadrantScene(Scene):
    def construct(self):
        # Quadrant Lines
        line1 = Line(3 * UP, 3 * DOWN).shift(LEFT)
        line2 = Line(3 * LEFT, 3 * RIGHT)

        # Quadrant Text Labels
        label_NW = Text("NW Quadrant").next_to(line1, UP).next_to(line2, LEFT)
        label_NE = Text("NE Quadrant").next_to(line1, UP).next_to(line2, RIGHT)
        label_SW = Text("SW Quadrant").next_to(line1, DOWN).next_to(line2, LEFT)
        label_SE = Text("SE Quadrant").next_to(line1, DOWN).next_to(line2, RIGHT)

        # Example Shapes (Customize these!)
        shape_NW = Circle(radius=0.5).next_to(label_NW, DOWN) 
        shape_NE = Square(side_length=0.8).next_to(label_NE, DOWN)

        # Create and Animate 
        self.play(Create(line1), Create(line2))
        self.play(Write(label_NW), Write(label_NE), Write(label_SW), Write(label_SE))
        self.play(Create(shape_NW), Create(shape_NE))
        self.wait() 
```
(Code generated by Gemini Advanced) 

</details>

## Additional media files

<details><summary>Images/GIFs</summary>

N/A (Nothing is rendered)

</details>

## Logs
<details><summary>Terminal output</summary>

```
(myenv) shyamaluser@Shyamals-iMac example_scenes % manim -qpl opengl.py            
Media will be written to /Users/shyamaluser/DDS/manim/example_scenes/media/. You can change this behavior with the --media_dir flag.

   There are no scenes inside that module


```

N/A

</details>

## System specifications

<details><summary>System Details</summary>

- OS (with version, e.g., Windows 10 v2004 or macOS 10.15 (Catalina)):
- RAM:
- Python version (`python/py/python3 --version`):
- Installed modules (provide output from `pip list`):
```
macOS Sonoma 14.4.1
```
</details>

<details><summary>LaTeX details</summary>

+ LaTeX distribution (e.g. TeX Live 2020):
+ Installed LaTeX packages:

</details>

<details><summary>FFMPEG</summary>

Output of `ffmpeg -version`:

```
N/A
```
</details>

## Additional comments

None, please find out the Easter egg.

**Comment by MrDiver** [comment]
`-pql` ?

**Comment by shyamalschandra** [comment]
> `-pql` ?

No, I just tried it again with different order.  I might need to compile it from the latest source.

Anything else I might try, @MrDiver?

**Comment by JasonGrace2282** [comment]
Check to make sure you've saved the file, and that you're in the same directory in your terminal as `main.py`.

**Comment by shyamalschandra** [comment]
It still doesn't work.  Thank you, @JasonGrace2282!

**Comment by shyamalschandra** [comment]
I tried to the master tree with tags from the current to 0.1.0 and they all don't work with linux colab on Google Colab Pro.
This is strange because the advertisement says it works flawlessly.

I get the following error:

```
Collecting git+https://github.com/ManimCommunity/manim.git@v0.1.0
  Cloning https://github.com/ManimCommunity/manim.git (to revision v0.1.0) to /tmp/pip-req-build-4u6kxigx
  Running command git clone --filter=blob:none --quiet https://github.com/ManimCommunity/manim.git /tmp/pip-req-build-4u6kxigx
  Running command git checkout -q 14bfaab0a9296a88ca39b38e210cf2dd552ee532
  Resolved https://github.com/ManimCommunity/manim.git to commit 14bfaab0a9296a88ca39b38e210cf2dd552ee532
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: Pillow in /usr/local/lib/python3.10/dist-packages (from manimce==0.1.0) (9.4.0)
Collecting cairocffi<2.0.0,>=1.1.0 (from manimce==0.1.0)
  Downloading cairocffi-1.6.1-py3-none-any.whl (75 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 75.1/75.1 kB 2.5 MB/s eta 0:00:00
Requirement already satisfied: colour in /usr/local/lib/python3.10/dist-packages (from manimce==0.1.0) (0.1.5)
Requirement already satisfied: grpcio in /usr/local/lib/python3.10/dist-packages (from manimce==0.1.0) (1.62.1)
Collecting grpcio-tools (from manimce==0.1.0)
  Downloading grpcio_tools-1.62.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.8/2.8 MB 37.5 MB/s eta 0:00:00
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from manimce==0.1.0) (1.25.2)
Collecting pangocairocffi<0.4.0,>=0.3.0 (from manimce==0.1.0)
  Downloading pangocairocffi-0.3.2.tar.gz (21 kB)
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (setup.py) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by JasonGrace2282** [comment]
Why are you trying to install manim v0.1.0? The current version is 0.18.0.

`pip3 install manim==0.18.0`
Might work?

**Comment by behackl** [comment]
Did you check the documentation, specifically [this FAQ answer](https://docs.manim.community/en/stable/faq/general.html#why-does-manim-say-that-there-are-no-scenes-inside-that-module)?

It looks to me as if `manim` points to the `manimgl` executable which mixes the two available versions of manim.

Also, the pip-package is just called `manim`, not `manimce` -- the latter one is outdated and should not be used.
