### ISSUE TITLE
Suggestion: Default Video resolution to 1080p

### ISSUE THREAD

**Issue by kolibril13** [ManimCommunity/manim#368]
Hi, when I run this simple script:
```py
from manim import *

class Test1(Scene):
    def construct(self):
        dot = Dot().set_color(GREEN)
        self.add(dot)
        self.wait(1)

from pathlib import Path
if __name__ == "__main__":
    script = f"{Path(__file__).resolve()}"
    os.system(f"manim " + script)
```
I get a video resolution of `1440p60`. Can we change the default video resolution to 1080p? 
I think that the great majority of the users will have 1080p displays and with 1080p as default, video rendering is much faster.
Even one of the biggest youtube explanation channels (kurzgesagt) https://www.youtube.com/watch?v=ck4RGeoHFko
is still using 1080p, so I think it is reasonable to make this the default.
Lately, I saw a tv-documentation about the big tech companies, and they also test if all their new features look nice on cellphones/computers that are >8 years because only a small percentage of users have the newest technology.
With this said, maybe 1440p60 could be moved to a flag like -wqhd.

**Comment by huguesdevimeux** [comment]
I agree, I think 1080p is fine for a default value. It will make the render faster when one forget to specify the resolution.

**Comment by leotrs** [comment]
Fair. Also, I just realized that the default resolution is neither low, medium, high, or 4k. We should give it a name and a CLI flag.

Having said that, changing the default is as easy as changing the 89-91 of `default.cfg`.

**Comment by huguesdevimeux** [comment]
> Fair. Also, I just realized that the default resolution is neither low, medium, high, or 4k. We should give it a name and a CLI flag.

What do you mean ? Isn't 1080p high ?

> Having said that, changing the default is as easy as changing the 89-91 of default.cfg.

So, sounds like an easy PR ;) Added label in consequence.

**Comment by leotrs** [comment]
high is 1080, but the default is 1440, which is neither low, medium, high, or 4k
