### ISSUE TITLE
Working with Manim in Jupyer Notebook

### ISSUE THREAD

**Issue by hesamsheikh** [ManimCommunity/manim#3682]
So my situation is that I've been trying to use manim within my jupyter notebook. 
I have installed manim, ffmpeg and my jupyter is running inside Pycharm.
However when trying to render an animation and see it in my jupter, I get an empty video.

The video DOES get rendered and saved locally in the media folder, but I cannot see it here in jupyter.

```
%%manim -ql SquareToCircle

class SquareToCircle(Scene):
    def construct(self):
        circle = Circle()
        square = Square()
        square.flip(RIGHT)
        square.rotate(-3 * TAU / 8)
        circle.set_fill(PINK, opacity=0.5)

        self.play(Create(square))
        self.play(Transform(square, circle))
        self.play(FadeOut(square))
```
![image](https://github.com/ManimCommunity/manim/assets/41022652/a787cac5-ce9a-492c-aa49-9e56294693de)

**Comment by behackl** [comment]
This is a known limitation of PyCharm, see https://youtrack.jetbrains.com/issue/PY-51778/Cant-play-video-in-jupyter-notebook. There is nothing we can do on our end.

**Comment by LizzieSpace** [comment]
This issue can be circumvented by setting `config.format` to "webm"
or adding the `--format "webm"` option
