### ISSUE TITLE
Fraction line disappears when use polyglossia in tex preambula

### ISSUE THREAD

**Issue by leobreslav** [ManimCommunity/manim#3700]
## Description of bug / unexpected behavior

When using a custom TexTemplate in Manim that incorporates the fontspec and polyglossia packages, the fraction line in LaTeX-rendered expressions disappears from the video output after the animation completes. Although the fraction line is visible during the animation and correctly appears in the SVG files generated by LaTeX, it vanishes once the animation stops. This issue occurs without involving any right-to-left text settings and is reproducible with basic mathematical expressions.

## Expected behavior

The fraction line in mathematical expressions, such as $\frac{1}{2}$, should remain visible throughout the video, including after the completion of animations. The rendered content should consistently display all mathematical notations correctly, maintaining visibility without any elements disappearing post-animation.

## How to reproduce the issue

Below is a minimal code snippet that illustrates the issue of the disappearing fraction line when using a custom LaTeX preamble in Manim. This problem is observed under configurations using the fontspec and polyglossia packages.

<details><summary>Code for reproducing the problem</summary>

```py
from manim import *

class FractionLineDisappearScene(Scene):
    def construct(self):
        # Setting up a custom TexTemplate
        new_template = TexTemplate()
        new_template.reset()
        new_template.add_to_preamble(r"\usepackage{fontspec}")
        new_template.add_to_preamble(r"\usepackage{polyglossia}")
        new_template.add_to_preamble(r"\setdefaultlanguage{english}")

        # Creating a text object with a fraction
        solution = Tex(r"$\frac{1}{2}$", tex_template=new_template)

        # Animating the text
        self.play(Write(solution))
        self.wait(2)

if __name__ == "__main__":
    scene = FractionLineDisappearScene()
    scene.render()
```

</details>

## System specifications

<details><summary>System Details</summary>

```
- OS: Win 11
- Python version: 3.10
 - Manim 0.18
```

**Comment by uwezi** [comment]
this code works fine on my system using ManimCE 0.18.0.post0:
```py
class FractionLineDisappearScene(Scene):
    def construct(self):
        # Setting up a custom TexTemplate
        new_template = TexTemplate(
	        tex_compiler="xelatex",
            output_format='.xdv',
        )
        # new_template.reset() where does this come from?
        new_template.add_to_preamble(r"\usepackage{fontspec}")
        new_template.add_to_preamble(r"\usepackage{polyglossia}")
        new_template.add_to_preamble(r"\setdefaultlanguage{english}")

        # Creating a text object with a fraction
        solution = Tex(r"$\frac{1}{2}$", tex_template=new_template)

        # Animating the text
        self.play(Write(solution))
        self.wait(2)
```

You need to use xelatex when using fontspec, also where did you get `new_template.reset()` from?

![image](https://github.com/ManimCommunity/manim/assets/8582807/1ade49e1-8315-43d1-8398-fa33e22cfe1d)
![image](https://github.com/ManimCommunity/manim/assets/8582807/33292a7e-f352-4429-9dca-9004874220a7)

**Comment by behackl** [comment]
Closing this as wontfix: `fontspec` requires xelatex, and the code suggested by @uwezi works for me too.
