### ISSUE TITLE
add_subcaption does not work as expected 

### ISSUE THREAD

**Issue by lskenkf** [ManimCommunity/manim#3714]
when I run this script from the examples:
`

class SubcaptionExample(Scene):
    def construct(self):
        square = Square()
        circle = Circle()
        self.add_subcaption("Hello square!", duration=1)
        self.play(Create(square))
        self.play(
            Transform(square, circle),
            subcaption="The square transforms."
        )

`

I expect the subcaption to be shown. But it did not. Do you guys know why, I also tried with manim voiceover example to add subtitle, but still it did not work.

**Comment by behackl** [comment]
Depends on where you expected it to be shown: `add_subcaption` does not create burned-in subcaptions. It writes them to a separate `.srt` file which is read and processed by proper video players like VLC.
