### ISSUE TITLE
Fix setup-ffmpeg - unable to fetch

### ISSUE THREAD

**Issue by JasonGrace2282** [ManimCommunity/manim#3726]
Until #3501 is merged, [this](https://github.com/federicocarboni/setup-ffmpeg/issues/19#issuecomment-2063798309) may be a suitable "fix" for "failed to fetch" errors in `setup-ffmpeg@v3`

**Comment by behackl** [comment]
The macos runners apparently have changed to arm architecture too, the action just fails for them. Not sure whether x86-runners can be requested explicitly, and otherwise one more reason to work on #3501.

**Comment by JasonGrace2282** [comment]
x86 runners for MacOS are no longer available.
Related: #3729
