### ISSUE TITLE
Google Colab: Video data is no longer automatically embedded in the notebook

### ISSUE THREAD

**Issue by mathriddle** [ManimCommunity/manim#3741]
Previously, running the command "from manim import *" all by itself in a Colab  cell would result in the output "Manim Community v0.18.0". Then the manim code to make a video could be run in additional cells. With v0.18.1, however, no output is generated running that import command, but the "Manim Community v0.18.1" appears as the output **after** rendering a manim snippet in a subsequent cell, along with the message about "no video with supported format and MIME type found".

Adding the line config.media_embed=True to the cell with the import command does resolve the issue, but the "Manim Community v0.18.1" output still appears as the output along with the now functioning video.

**Comment by behackl** [comment]
The version spash shown on import has been disabled by default.

As for the video: it actually is being generated, Colab can just not display it if it is not directly embedded into the notebook source. The default behavior of this config option (`config.media_embed`) has been changed; it is `False` now by default, `None` is no longer an allowed value.

The corresponding code that needs to be updated is here:
https://github.com/ManimCommunity/manim/blob/31f189519b1e887803be67b76d61e4dc35655252/manim/utils/ipython_magic.py#L172-L176

We should change this such that `media_embed` is `True` whenever the IPython magic is run on Colab.

**Comment by 21-kunal** [comment]
Hi, I would like to work on this issue.

**Comment by antoinebou12** [comment]
My fix
```
url = "media/videos/content/720p30/example.mp4"
import os

current_directory = os.getcwd()
print(current_directory)

directory_contents = os.listdir(current_directory)
print(directory_contents)

video_path = os.path.join(current_directory, url)
print(video_path)

from IPython.display import HTML
from base64 import b64encode
mp4 = open(video_path,'rb').read()
data_url = "data:video/mp4;base64," + b64encode(mp4).decode()
HTML("""
<video width=1080 controls>
      <source src="%s" type="video/mp4">
</video>
""" % data_url)
```

**Comment by behackl** [comment]
> My fix

This replicates manually what `config.media_embed = True does automatically.

The issue has already been fixed on the main branch an will be available with the upcoming release.

**Comment by antoinebou12** [comment]
Thank
