### ISSUE TITLE
Underline markup tag for MarkupText should be documented as <u></u> not <ul></ul>.

### ISSUE THREAD

**Issue by anagorko** [ManimCommunity/manim#3744]
## Description of bug / unexpected behavior

Documentation at https://docs.manim.community/en/stable/reference/manim.mobject.text.text_mobject.MarkupText.html lists "&lt;ul>underline&lt;/ul>" in a list of supported tags.

## Expected behavior

It should be "&lt;u>underline&lt;/u>".

**Comment by behackl** [comment]
Duplicate of #3578
