### ISSUE TITLE
FadeOut on DiGraph does not work smoothly

### ISSUE THREAD

**Issue by uwezi** [ManimCommunity/manim#3749]
## Description of bug / unexpected behavior
ManimCE v0.18.1

Using `self.play(Fadeout())` on a `DiGraph()` object does not correctly fade out the edges, only the nodes and arrow tips. Removing the individual subobjects works.

Link to the [Discord discussion](https://discord.com/channels/581738731934056449/1236723849937158145/1236723849937158145)

## Expected behavior
All elements of a `DiGraph()` should fade smoothly out.

## How to reproduce the issue
<details><summary>Code for reproducing the problem</summary>

```py
class IntroductionToGraphs(Scene):
    def construct(self):
        vertexs = [num for num in range(1,7)]
        arestes = [(1,2), (3,1), (1,5), (1,6), (5,1), (5,6), (3,4)]
        layout = "circular"

        graf_arestes1 = Graph(vertexs, arestes, labels = True, layout = layout)
        graf_arestes2 = DiGraph(vertexs, arestes, labels = True, layout = layout)
        graf_arestes3 = graf_arestes2.copy()

        graf_arestes1.scale_to_fit_width(14/3).to_edge(LEFT, buff=0)
        graf_arestes2.scale_to_fit_width(14/3)
        graf_arestes3.scale_to_fit_width(14/3).to_edge(RIGHT, buff=0)

        self.play(
            Create(graf_arestes1),
            Create(graf_arestes2),
            Create(graf_arestes3),
        )
        self.wait()
        self.play(
            FadeOut(graf_arestes1),
            FadeOut(graf_arestes2),
            FadeOut(*[obj for obj in graf_arestes3])
        )
```
</details>

## Additional media files
<details><summary>Images/GIFs</summary>

https://github.com/ManimCommunity/manim/assets/8582807/20f06405-6c81-453c-ac62-c6d32f16635c

</details>

## System specifications

<details><summary>System Details</summary>
irrelevant - the problem occurs on both Windows 10 and Manimator
</details>

**Comment by Nikhil-42** [comment]
This is an issue with the edge updater in the DiGraph. I'll take a look at it.
