### ISSUE TITLE
Need a `Variable` class for intuitively using continuously updated values 

### ISSUE THREAD

**Issue by nilaybhatia** [ManimCommunity/manim#375]
### Feature request
Right now, creating a continuously updating variable say `x = ...` is very cumbersome. First you have to create the label `x =` as Tex(t)Mobject, then a `ValueTracker` object for tracking the value and then finally a `DecimalNumber` object for displaying the value of the variable, An example is [here](https://github.com/Elteoremadebeethoven/AnimationsWithManim/blob/32271a83b8a87c310b72292b301040c227683d00/English/update_successions/value_tracker_examples.py#L9). 

It would be nice to wrap this functionality together so that user has to take care of just updating the value and rest of the things are done automatically in the background.

**Comment by leotrs** [comment]
Would love to see a PR that implements this!
