### ISSUE TITLE
Collecting Example Scenes

### ISSUE THREAD

**Issue by kolibril13** [ManimCommunity/manim#379]
For new contributors, having straight forward examples is a very good resource for quickly learning manim.

Therefore, here are some guidelines for creating the examples (these are currently only my ideas, so please give feedback, I will then continuously update this list):
* Examples should be as minimal as possible --> easy to understand
* There should be a balance of animated and non-animated examples.
    * as manim is there to make animations, we should, of course, include lots of animated examples
    * HOWEVER: I think that lots of examples (like the size of a plot-axis, making an area, annotation stuff, setting opacities, making texts) will also work very well as images. For people that read the docs, it will be a lot more convenient to look at an example and immediately see what they want to see, instead of having an animation, that has also the time component and therefore one more abstraction level. So animations should be avoided when they are not necessary. 
* Examples should not have uncommented code or comments -> this can go into the markdown files. 
* Examples can be organized into chapters and subchapters
* Please record which version of manim was used to generate this example

For now, we can collect examples in a markdown pad where one can drag and drop images/gifs that are automatically uploaded: https://pad.gwdg.de/Kyv7fYxfTKC4NVxbNw2cbQ
As soon as this pad grows too large, it can be split into sub-pads.

**Comment by kolibril13** [comment]
And here is an idea how we could structure the folders:
* Shapes
* Annotations
* Plots
* Text
* Formulas
* Updater
* 3D 
* Animations
    * Transformations
    * Updates
* AdvancedProjects

**Comment by leotrs** [comment]
General suggestion: once you are happy with the guidelines we have gathered on this issue, let's close this issue and put these guidelines somewhere in the documentation.

Suggestion for new guideline: Please record which version of manim was used to generate this example. (If necessary, please provide the commit hash and date.)

I like the structure you are suggesting! I also want to suggest adding a "Neat projects" or "Neat examples" chapter. These may be simple but neat, so they are not necessarily the same as "Advanced Projects".

**Comment by kolibril13** [comment]
Closed in favour of 
https://github.com/ManimCommunity/manim/wiki/Guide-to-contribute-Examples-to-docs
and
https://github.com/ManimCommunity/manim/wiki/Docs-Example-Ordering
