### ISSUE TITLE
Documentation host or domain

### ISSUE THREAD

**Issue by PgBiel** [ManimCommunity/manim#38]
We've been discussing where should we host our documentation and what its domain should be.

Options for host:
1. Host using GitHub pages;
2. Host with ReadTheDocs;
3. Host on a private server. (More can be added here as the discussion goes)

Options for domain:
1. Use the GitHub pages domain (Note: could be too long: manimcommunity.github.io/manim ...)
2. Use the ReadTheDocs domain
3. Use a free domain acquired online

Ideas? Suggestions?

**Comment by safinsingh** [comment]
We could create a GitHub pages site and a Freenom doman (12 months free; it's not a scam, I use it all the time). This way, we can all contribute to the GH Pages branch of this repository, which auto-deploys to GH pages itself. The domain is just a DNS forward to the GH pages site.

**Comment by leotrs** [comment]
I *think* I like this. But this opens the huge can of worms which is: how to name that website. Which in turn opens the can of worms of whether we want to change the name of the library itself.

**Comment by naveen521kk** [comment]
How about an [js.org](https://js.org) subdomain. We can host using GitHub Pages and use their subdomain.

**Comment by Aathish04** [comment]
> How about an [js.org](https://js.org) subdomain. We can host using GitHub Pages and use their subdomain.  

Using a .js.org domain would imply that this is a JavaScript library, which is not true.

**Comment by leotrs** [comment]
This issue was about a domain *for documentation*, and I don't see anyone being against ReadTheDocs. So I'm closing this for now. For discussion on a separate domain (whether it would point to documentation or not), please open a separate issue.
