### ISSUE TITLE
How do I set the background color of code in Manim?

### ISSUE THREAD

**Issue by TheSlugInTub** [ManimCommunity/manim#3859]
I want to set the background color of a code text in Manim, is there any way to do that
Or at least remove the background
```
        code_text = Code(
            "object.cpp",
            tab_width=4,
            insert_line_no=False,
            language="cpp",
            background_stroke_width=0,
            background_stroke_color=WHITE,
            background_color='#2d2d2d' #something like this
        )
```

**Comment by uwezi** [comment]
`Code()` uses the pygments library for highlighting. You can change easily to many predefined styles with light or dark background, as well as make your own styles:

https://pygments.org/docs/styles/

The following code and video were made by Abulafia over there at the [Discord server ](https://docs.manim.community/en/stable/faq/general.html?highlight=discord#where-can-i-find-more-resources-for-learning-manim)


https://github.com/user-attachments/assets/7ac9f692-4ec2-4c78-b34e-a8f452f95ff3
