### ISSUE TITLE
Axes and the unit_size

### ISSUE THREAD

**Issue by TueNguyen2006** [ManimCommunity/manim#3892]
## Description of bug / unexpected behavior

```py
class test(Scene):
    def construct(self):
        self.graph_plane_config = {
            "x_range": [0, 4.3 * PI, PI],
            "y_range": [-2, 2, 1],

            "x_axis_config": {
                "unit_size": 2, #try another number and it's similar
            },
            "y_axis_config": {
                "unit_size": 1, #try another number and it's similar
            },
        }
        a = Axes(**self.graph_plane_config)
        self.add(a)
```

In the class Axes(), in the "x_axis_config" and "y_axis_config", when i change "unit_size" or "length", the result doesn't change

## How to reproduce the issue

<details><summary>Code for reproducing the problem</summary>

```py
```

</details>

## Additional media files

<details><summary>Images/GIFs</summary>

</details>

## Logs
<details><summary>Terminal output</summary>

```
PASTE HERE OR PROVIDE LINK TO https://pastebin.com/ OR SIMILAR
```

</details>

## System specifications

<details><summary>System Details</summary>

- OS (with version, e.g., Windows 10 v2004 or macOS 10.15 (Catalina)):
- RAM:
- Python version (`python/py/python3 --version`):
- Installed modules (provide output from `pip list`):
```
PASTE HERE
```
</details>

<details><summary>LaTeX details</summary>

+ LaTeX distribution (e.g. TeX Live 2020):
+ Installed LaTeX packages:

</details>

**Comment by uwezi** [comment]
Just set the lengths of the axes in the main object's parameters.

The `axis_config` are mostly meant for cosmetic changes to the looks of the axes, not to their scaling.

```py
class test(Scene):
    def construct(self):
        self.graph_plane_config = {
            "x_range": [0, 4.1 * PI, PI],
            "y_range": [-2, 2, 1],
            "x_length": 4.1*PI,
            "y_length": 4,
            "tips":False,
            "x_axis_config": {
                "decimal_number_config": {"num_decimal_places":2},
             },
        }

        a = Axes(**self.graph_plane_config).add_coordinates()
        self.add(a)
```
![bild](https://github.com/user-attachments/assets/32b01f00-acf3-46f2-850b-ea88e8647369)

**Comment by TueNguyen2006** [comment]
Thanks you
