### ISSUE TITLE
apply_complex_function HELP

### ISSUE THREAD

**Issue by guiwenfeng** [ManimCommunity/manim#3920]
I wanted to turn the circle into an irregular shape by random scaling, as shown in Figure 1, but it didn't turn out what I wanted. Anyone can help me？

```py
from manim import *
import random

class Test(Scene):

    def construct(self):
        circle = Circle()

        # circle.apply_complex_function(
        #     lambda z: z*2
        # )

        circle.apply_complex_function(
            lambda z: z*2*random.uniform(0.75, 1.25)
        )

        self.add(circle)
```

Figure 1
<img width="220" alt="WechatIMG266" src="https://github.com/user-attachments/assets/bfed8109-3618-4e0e-b0d3-150a5dbdefc7">

Result
![Test3_ManimCE_v0 17 3](https://github.com/user-attachments/assets/a361a805-a7a4-486e-b2bf-6deba236e6f6)

**Comment by uwezi** [comment]
I don't completely understand what happens here, but if you scale down the amplitude of your randomness it gets better. Also a parametric curve for your circle seems to be a better choice, since a circle object in Manim does not contain many points.

```py
class Test(Scene):

    def construct(self):
        #circle = Circle()
        circle = ParametricFunction(
            lambda t: np.array([np.cos(t),np.sin(t),0]),
            t_range=[0,2*PI,0.2]
        )
        # circle.apply_complex_function(
        #     lambda z: z*2
        # )

        circle.apply_complex_function(
            lambda z: z*np.random.uniform(1.975, 2.025)
        )

        self.add(circle)
```

![image](https://github.com/user-attachments/assets/20f2354b-0deb-46ca-9ac4-26b0cc5d0287)

**Comment by guiwenfeng** [comment]
Thanks @uwezi ，My purpose is to generate an irregular shape, and now I've found a way.


```py
from manim import *
import random


class IrregularShapeDemo(Scene):
    stroke_color = TEAL
    fill_color = BLUE_E
    fill_opacity = 1
    height = 2

    def construct(self):
        plane = NumberPlane()

        blob = VMobject()
        blob.set_points_as_corners([
            (1 + 0.3 * random.random()) * p
            for p in compass_directions(12)
        ])
        blob.close_path()
        blob.set_fill(self.fill_color, self.fill_opacity)
        blob.set_stroke(self.stroke_color)
        blob.set(height=self.height)
        blob.make_smooth()
        blob.center().shift(UP+RIGHT)

        self.add(plane, blob)
```

![IrregularShapeDemo_ManimCE_v0 17 3](https://github.com/user-attachments/assets/d35a4e00-90af-4f97-aa20-51ae4f10910c)

**Comment by uwezi** [comment]
looks nice!

I didn't know that already `VMobject()`  had the method `.make_smooth()`
