### ISSUE TITLE
Issues with Text and Cairo

### ISSUE THREAD

**Issue by ViolaBuddy** [ManimCommunity/manim#393]
This is probably a bug with Cairo rather than ManimCE so this might not be something you can really fix, but there are at least a couple oddities that happen when trying to use the `Text` command:

- Characters in the Supplemental Planes (i.e. with Unicode code points 0x10000 or more) are taken to be mod 0x10000 instead. For example, characters 0x20100 and 0x10100 both display as Ā, whose code point is 0x100.
- Right-to-left text isn't supported. For example, if Arabic text is given, every character is in its isolated form, written from left to right.

**Comment by naveen521kk** [comment]
Maybe you can open an issue in pycairo?
https://github.com/pygobject/pycairo
If you surely know it is because of Pycairo.

**Comment by naveen521kk** [comment]
I could clearly read from pycairo documentation that https://pycairo.readthedocs.io/en/latest/reference/text.html#text

> The functions with text in their name form cairo’s toy text API. The toy API takes UTF-8 encoded text and is limited in its functionality to rendering simple left-to-right text with no advanced features. That means for example that most complex scripts like Hebrew, Arabic, and Indic scripts are out of question. No kerning or correct positioning of diacritical marks either. The font selection is pretty limited too and doesn’t handle the case that the selected font does not cover the characters in the text. This set of functions are really that, a toy text API, for testing and demonstration purposes. Any serious application should avoid them.

SO we should as soon as possible look over other possible solutions for this. One thing we can do is use [freetype-py](https://pycairo.readthedocs.io/en/latest/integration.html#freetype-py-cairo) or any other library which handles and requires rework.

**Comment by ViolaBuddy** [comment]
Ah so that explains things like right-to-left text and Arabic letters always only being in their isolated forms. I'm surprised, though, if they use UTF-8, that the "mod 0x10000" thing is happening - I mean, it makes some sense (in UTF-8, characters less than 0x10000 take three bytes or less while characters 0x10000 or greater take four) but if you're supporting a variable one, two, or three-byte character, I don't know why you would stop there without also allowing four-byte characters.

Regardless, it indeed claims to be only for toy examples rather than final applications so yeah, reconsidering a different text engine is probably the best idea.

**Comment by leotrs** [comment]
Fully agreed. It's a shame that manim can't currently support right-to-left text. Cairo is going away at _some point_* but if anyone has time right now, [Pango](https://pango.gnome.org/) seems to be the way to go here. It is meant to play well with Cairo.

\* There are plans to replace Cairo with other renderers, but it's unclear to me at this point when this will be made concrete. It _might_ be worth it to implement Pango before that happens, if anyone is in a burning hurry for better text support.

**Comment by naveen521kk** [comment]
> It might be worth it to implement Pango before that happens,

Whatever we do we should make it cross platform (especially on windows).

**Comment by leotrs** [comment]
The Pango description says that it supports native font handling in all of windows, mac, and linux. But that may be too much work, and we may just want to wait until Cairo is out...

**Comment by naveen521kk** [comment]
I am taking over implementing Pango with Manim using binding 
pangocffi https://pangocffi.readthedocs.io/en/latest/
pangocairocffi https://pangocairocffi.readthedocs.io/en/latest/
