### ISSUE TITLE
OpenGl resolution option invalid

### ISSUE THREAD

**Issue by Shree-bytes** [ManimCommunity/manim#4002]
## 'Resolution option invalid' while rendering with OpenGL

While rendering a scene using the **-renderer opengl** command, I get a 'Resolution option is invalid' error.

Just this morning everything was fine until I started encountering this issue. Usually running this command along with **-p** command opens a small interactive window which played the animation.

I have already tried specifying the quality and resolution, both manually by editing the config file and using the **-q** and **-r** commands. I have uninstalled and reinstalled Manim multiple times by using **pip** and **Chocolatey** as well to try and get it to work again.

I really like OpenGL as it gives me a faster preview without cluttering my screen too much by opening the media player every time I make any adjustments.

<details><summary>CMD commands</summary>

```py
manim -renderer opengl -pqm fy.py
```

**Comment by behackl** [comment]
On the CLI the renderer flag needs to be passed with two dashes: `manim --renderer opengl ...`, otherwise your command is interpreted as passing the option "enderer" to the `-r` flag, which is the resolution.
