### ISSUE TITLE
 problem in effect

### ISSUE THREAD

**Issue by S3nshimasked** [ManimCommunity/manim#4029]
I'm a beginner in manim and I'm trying to make a scene where I use a color change effect on the background from black to white so that I can get the effect of lightning, but I can't place this effect at any point in the animation, or it appears at the end or only at the beginning. How do I get this effect anywhere in the animation? can anyone help me?

**Comment by JasonGrace2282** [comment]
You might find more luck asking in our platforms for getting help.
See the FAQ for a link: https://docs.manim.community/en/stable/faq/help.html#how-do-i-animate-x-why-do-i-get-error-y-can-someone-help-me
