### ISSUE TITLE
`self.remove()` does not take effect immediately when called within an `updater` function

### ISSUE THREAD

**Issue by ChungLeeCN** [ManimCommunity/manim#4040]
## Description of bug / unexpected behavior

I noticed that in updater functions, `self.remove()` does not take effect immediately but only after the `self.wait()` function has completed or other "code_pause_point". (Testing shows that self.add() takes effect immediately.) Is this a bug or a feature?

## Expected behavior

`self.remove()` will take effect immediately.

## How to reproduce the issue

```py
from manim import *

class DelayRemoveTest(Scene):
    def delay_remove(self, *args, delay: float = 0):
        start_time = self.renderer.time
        mob_for_test = Circle(2)

        def update(dt):
            if self.renderer.time - start_time >= delay:
                self.remove(*args)
                self.add(mob_for_test)
                self.remove_updater(update)

        self.add_updater(update)

    def construct(self):
        # time info for test
        whole_time = 7
        n = NumberLine(include_numbers=True, x_range=[0, whole_time]).to_edge(DOWN)
        progress_bar = Line(n.n2p(0), n.n2p(whole_time)).set_stroke(color=YELLOW, opacity=0.5, width=20)
        self.add(n, progress_bar)
        turn_animation_into_updater(Create(progress_bar, run_time=whole_time, rate_func=linear))
        # test code begin
        circle_01 = Circle(0.5).move_to(UP)
        circle_02 = Circle(0.5).move_to(DOWN)
        square = Square(0.5)
        self.add(circle_01, circle_02, square)
        self.delay_remove(circle_01, circle_02, delay=2)
        self.wait(4)
        self.wait(3)
```

## Additional media files

https://github.com/user-attachments/assets/f7e25449-f4c4-488a-a2dc-8ab197634b81

## Logs
<details><summary>Terminal output</summary>

```
PASTE HERE OR PROVIDE LINK TO https://pastebin.com/ OR SIMILAR
```

</details>

## System specifications

<details><summary>System Details</summary>

- OS (with version, e.g., Windows 10 v2004 or macOS 10.15 (Catalina)):
- RAM:
- Python version (`python/py/python3 --version`):
- Installed modules (provide output from `pip list`):
```
PASTE HERE
```
</details>

<details><summary>LaTeX details</summary>

+ LaTeX distribution (e.g. TeX Live 2020):
+ Installed LaTeX packages:

</details>

**Comment by behackl** [comment]
In every play/wait call, Manim tries to detect which objects might be modified. For those objects that it thinks remain unchanged, it paints them to the background (that is only rendered at the beginning of a call) -- which also makes it look like the object remains there until the end of the wait call.

This only happens when objects do not know that they might be modified, which in this case Manim does not detect. A simple solution is attaching the removal-updater to individual mobjects instead of to the scene; mobjects with attached time-based updaters are never considered static.

It is probably not worth it to invest time into trying to make the detection whether a mobject is static more intelligent as this mechanism does not exist any longer in the reworked renderer, as far as I know.

**Comment by ChungLeeCN** [comment]
> In every play/wait call, Manim tries to detect which objects might be modified. For those objects that it thinks remain unchanged, it paints them to the background (that is only rendered at the beginning of a call) -- which also makes it look like the object remains there until the end of the wait call.
> 
> This only happens when objects do not know that they might be modified, which in this case Manim does not detect. A simple solution is attaching the removal-updater to individual mobjects instead of to the scene; mobjects with attached time-based updaters are never considered static.
> 
> It is probably not worth it to invest time into trying to make the detection whether a mobject is static more intelligent as this mechanism does not exist any longer in the reworked renderer, as far as I know.

After testing, placing `remove()` inside an updater of mobjects still does not make `remove()` take effect immediately. And this issue occurs regardless of whether Cairo or OpenGL is used.

The code:
```python
from manim import *

class DelayRemoveTest(Scene):
    def construct(self):
        # time info for test
        whole_time = 7
        n = NumberLine(include_numbers=True, x_range=[0, whole_time]).to_edge(DOWN)
        progress_bar = Line(n.n2p(0), n.n2p(whole_time)).set_stroke(color=YELLOW, opacity=0.5, width=20)
        self.add(n, progress_bar)
        turn_animation_into_updater(Create(progress_bar, run_time=whole_time, rate_func=linear))
        # test code begin
        circle_01 = Circle(0.5).move_to(UP)
        circle_02 = Circle(0.5).move_to(DOWN)
        square = Square(0.5)
        self.add(circle_01, circle_02, square)
        start_time = self.renderer.time
        mob_for_test = Circle(2)
        def remove_update(mob, dt):
            if self.renderer.time - start_time >= 2:
                self.remove(mob)
                self.add(mob_for_test)
                mob.remove_updater(remove_update)
        circle_01.add_updater(remove_update)
        self.wait(4)
        self.wait(3)
```

The output mp4 file:

https://github.com/user-attachments/assets/146b32a3-1c76-490a-afd5-6e629bd4cd1a

**Comment by ChungLeeCN** [comment]
> In every play/wait call, Manim tries to detect which objects might be modified. For those objects that it thinks remain unchanged, it paints them to the background (that is only rendered at the beginning of a call) -- which also makes it look like the object remains there until the end of the wait call.
> 
> This only happens when objects do not know that they might be modified, which in this case Manim does not detect. A simple solution is attaching the removal-updater to individual mobjects instead of to the scene; mobjects with attached time-based updaters are never considered static.
> 
> It is probably not worth it to invest time into trying to make the detection whether a mobject is static more intelligent as this mechanism does not exist any longer in the reworked renderer, as far as I know.

After testing, placing `remove()` inside an updater of mobjects still does not make `remove()` take effect immediately. And this issue occurs regardless of whether Cairo or OpenGL is used.

The code:
```python
from manim import *

class DelayRemoveTest(Scene):
    def construct(self):
        # time info for test
        whole_time = 7
        n = NumberLine(include_numbers=True, x_range=[0, whole_time]).to_edge(DOWN)
        progress_bar = Line(n.n2p(0), n.n2p(whole_time)).set_stroke(color=YELLOW, opacity=0.5, width=20)
        self.add(n, progress_bar)
        turn_animation_into_updater(Create(progress_bar, run_time=whole_time, rate_func=linear))
        # test code begin
        circle_01 = Circle(0.5).move_to(UP)
        circle_02 = Circle(0.5).move_to(DOWN)
        square = Square(0.5)
        self.add(circle_01, circle_02, square)
        start_time = self.renderer.time
        mob_for_test = Circle(2)
        def remove_update(mob, dt):
            if self.renderer.time - start_time >= 2:
                self.remove(mob)
                self.add(mob_for_test)
                mob.remove_updater(remove_update)
        circle_01.add_updater(remove_update)
        self.wait(4)
        self.wait(3)
```

The output mp4 file:

https://github.com/user-attachments/assets/146b32a3-1c76-490a-afd5-6e629bd4cd1a

**Comment by behackl** [comment]
Very interesting, thanks for the thorough investigation! In this case it might be possible that something else is responsible.

It is possible that while `remove` does remove the mobject immediately from the scene, it is not removed from the list of mobjects that are being processed by the renderer.

As a workaround, you could replace
```py
self.remove(mob)
```
with
```py
mob.set_fill(opacity=0)
mob.set_stroke(opacity=0)
self.remove(mob)
```
which *should* be reflected immediately when rendering.

I actually find it very odd that adding mobjects does seem to work mid-animation then. Something very weird is going on here.
