### ISSUE TITLE
-w flag enabled by default

### ISSUE THREAD

**Issue by huguesdevimeux** [ManimCommunity/manim#41]
I just noticed an issue with the CLI arguments, and more particular concerning the `-w` (`write_to_movie`) flag. 
It appears that when `-s` (`save_last_frame`) is False (most of the time, I think), `write_to_movie `is set True even though -w hasn't been placed. (that's why for example in the `README `just` -pl` is used instead of `-plw`).

That is shown at l. 166 of `config.py`: 
`"write_to_movie": args.write_to_movie or not args.save_last_frame,`

This may cause issues when one wants to get the last frame AND the video. 

Should we fix it or let -w enabled by default (even though it's not very _rigorous_) ?

**Comment by leotrs** [comment]
Good catch. I think we want to allow for four different behaviors:
1. write to movie ONLY
2. generate last frame ONLY
3. do both
4. do neither

Right now, option 1. is the default, no arguments necessary, 2. requires `-s`, and 3. is impossible. Is 4. possible? I think this can be useful for dry runs (for example for testing purposes).

O fail to see how your suggestion allows the support for all 4 (or 3) of these? Can you please clarify?  How would each of these be invoked?

**Comment by huguesdevimeux** [comment]
The 4 is impossible but the 3 is possible. It requires `-sw`  
So my thought was just to modify a little bit to make `-w` mandatory when wanting a video as output, like this : 

1. `-w`
2. `-s`
3. `-sw`
4. `nothing`

I will of course add a warning message saying that nothing has been selected to avoid any confusion.

**Comment by eulertour** [comment]
Since manim is mostly used to generate video it makes sense that it would do that by default, so I'd consider it a mistake for it do nothing by default. And since the purpose of generating the last frame was to see progress quickly without waiting for video to render, it also makes sense that video is disabled when the last frame is requested.

It seems to me like the only things to do are to ensure there's an intuitive way to both create video and save the last frame and to do a dry run for testing.

**Comment by leotrs** [comment]
How about this:

1. video only: `-w` OR nothing
2. last frame only: `-s`
3. both: `-ws`
4. neither: `-d` (for dry run, but this can be anything else)

**Comment by raghavg123** [comment]
I don't see why someone would want to render both the video and image at the same time though?

**Comment by leotrs** [comment]
Maybe they want to use the image as a thumbnail or some such? Regardless of how it'd be used, I think this is a low-maintenance easy-to-implement feature so we might as well have it.

Also, the point is that it's really easy to support both in a single run, while doing them separately would require two different CLI calls.

**Comment by huguesdevimeux** [comment]
I agree 

> How about this:
> 
> 1. video only: `-w` OR nothing
> 2. last frame only: `-s`
> 3. both: `-ws`
> 4. neither: `-d` (for "dry run", or any other available letter)

The first three are already implemented in the code. To me adding a new flag is a good idea. But since a few people will use a dry test maybe we could just set `--dry_test` as the flag ?

**Comment by leotrs** [comment]
Agreed. Let's say `--dry-run`.

Also, I thought 3. (both at the same time) wasn't possible with the current code base?

**Comment by huguesdevimeux** [comment]
The 3 is possible with `-ws`

**Comment by leotrs** [comment]
Ok we seem to have converged. I think we need a PR that allows number 4 and fix the original bug that opened this issue.

Now, I would *reallly* like to see this PR add tests for all of these flags... is that possible at the moment?

**Comment by eulertour** [comment]
It wouldn't be very stable. It'd have to run the commands and check the filesystem to ensure the right things were created, but with #12 still open that's likely to change.

**Comment by leotrs** [comment]
Fair. Let's revisit this once #12 is closed. @huguesdevimeux

**Comment by huguesdevimeux** [comment]
Oh no I had finished :/ 
But yes its a good idea to wait

**Comment by leotrs** [comment]
@huguesdevimeux if it is ready for merging, then go ahead. We can always add tests later*.

* Famous last words.
