### ISSUE TITLE
VGroup and VDict should implement `del`

### ISSUE THREAD

**Issue by leotrs** [ManimCommunity/manim#411]
`del vgroup[0]` or `del vdict['key']` should just call `.remove()` on the appropriate elements

**Comment by huguesdevimeux** [comment]
Sorry if i'm missing something, but what if one wants to remove an element from a VDict and not from the Scene ? Are you talking of `scene.remove ?`

**Comment by leotrs** [comment]
```
class VDict():
def __del__(self, key):
    self.remove(key)
```

**Comment by nilaybhatia** [comment]
Similar: Implementing `in` for a `VDict` to check if key is in `vdict`. To make `VDict` as close as possible to python dict, it would be great to support the methods listed [here](https://www.w3schools.com/python/python_ref_dictionary.asp). Maybe "VDict 2.0" after attrs is merged?

**Comment by leotrs** [comment]
Agreed. But also, `Container` should implement `in`...

**Comment by leotrs** [comment]
Also, the easiest way of doing this is to have VDict inherit from `collections.abc.Mapping` or `collections.abc.MutableMapping`
