### ISSUE TITLE
Black Check Fails as it looks for Deleted/Moved Files

### ISSUE THREAD

**Issue by Aathish04** [ManimCommunity/manim#413]
See : https://github.com/ManimCommunity/manim/runs/1070158057?check_suite_focus=true#step:6:423

`manim/config.py` had been moved to `manim/config/config.py` in commit 9845998bec03ac6316beb837b3e6d7469e6475eb, yet the `black` checker still tries to check for its formatting.

cc @naveen521kk @leotrs

**Comment by naveen521kk** [comment]
Looks like adding a condition can fix this easily.

**Comment by Aathish04** [comment]
> Looks like adding a condition can fix this easily. 

If you're able to, please open a PR for this.
