### ISSUE TITLE
Deprecate streaming settings?

### ISSUE THREAD

**Issue by leotrs** [ManimCommunity/manim#418]
Currently, `default.cfg` contains a few options relating to "streaming". These were ported directly from the previous configuration, but I have _no idea_ what they do or what they refer to or how they are supposed to be used. The entire codebase makes no reference to them.

Does anybody know what is their intended purpose?

If we can't figure this out, we should delete/deprecate them.

**Comment by behackl** [comment]
It seems that the streaming mode (which, if I understand correctly, does not render into a file but rather creates a live stream showing whatever is being executed in the input prompt) was broken at some point early last year in 3b1b's version, and that some amount of work is required to get it running again there. See https://github.com/3b1b/manim/pull/786 for a PR that claims to do it.

I have no idea whether the approach from this PR is still compatible with the changes made in the community maintained version. In case this is still somewhat compatible, bringing it back to life does not seem completely hopeless.

**Comment by leotrs** [comment]
Thanks @behackl , good sleuthing work.

The example in that PR is actually enlightening, I never really understood what the streaming was meant to do. It is an attractive idea, but I'm not sure how much work it would take for us to fully support it.

Do we think it would be a widely used feature? It seems like it would be useful for rapid prototyping/testing videos.

**Comment by huguesdevimeux** [comment]
I think it would be a VERY instersting feature. It would open the door to many other stuff related to live rendering. Couldn't we take this PR and apply it on manimCommunity ? 

Pinging @sas5580, the author if the fix (sorry if the ping is inappropriate)

**Comment by behackl** [comment]
I can also see myself using this feature; it might even be interesting in a teaching context. +1 for trying to bring it back. :-)

**Comment by huguesdevimeux** [comment]
Some update on this : it appears that streaming functions have been removed by @eulertour in https://github.com/3b1b/manim/pull/985 

So, a the moment we can deprecate streaming settings at it does not make any sense to have them, but this is definetly a feature that I would love to see. I will look up

**Comment by leotrs** [comment]
Closing this in favor of #441
