### ISSUE TITLE
`--save_pngs` does not work when caching is enabled

### ISSUE THREAD

**Issue by leotrs** [ManimCommunity/manim#420]
This is the scene I used
```
from manim import *
class MyScene(Scene):
    def construct(self):
        self.play(DrawBorderThenFill(Square()), run_time=1)
```
The first time I render it with `manim -pl scene.py --save_pngs` does not create any png files. A second (or third...) time also does not generate the image files. However, executing `manim -pl scene.py --save_pngs --disable_caching` does generate the image files.

**Comment by huguesdevimeux** [comment]
Interesting. Thanks for the report. 

I think the best fix is to disable scene caching when this option is enabled.

**Comment by huguesdevimeux** [comment]
Should we close this in favor of #425 ?

**Comment by leotrs** [comment]
#425 seems like a separate issue, no=

**Comment by huguesdevimeux** [comment]
Yes, but #425 is about reimplementing and fixing this flag. So, I thought we should close this one and use #425 to discuss about the future of `--save_pngs` (with renaming it, oc)

**Comment by leotrs** [comment]
Ok, but let's keep caching in mind when fixing #425
