### ISSUE TITLE
remove animation.update 

### ISSUE THREAD

**Issue by huguesdevimeux** [ManimCommunity/manim#421]
Bsically the title. this method is useless. See the code and the comment : 
https://github.com/ManimCommunity/manim/blob/5dd7bfe644e57d428deaad18f0ab8d3772d1ad01/manim/animation/animation.py#L115-L120

**Comment by leotrs** [comment]
We should add a deprecation warning

**Comment by musabkilic** [comment]
I think adding a warning for a while to give people some time to update is a better idea, similar to:
https://github.com/ManimCommunity/manim/blob/97de34692de7442845f9b935c6d1481784a739d4/manim/mobject/svg/tex_mobject.py#L334-L349

**Comment by huguesdevimeux** [comment]
> I think adding a warning for a while to give people some time to update is a better idea, similar to:
> 
> https://github.com/ManimCommunity/manim/blob/97de34692de7442845f9b935c6d1481784a739d4/manim/mobject/svg/tex_mobject.py#L334-L349

Yes (that's basically what @leotrs said lol)

**Comment by musabkilic** [comment]
I can add one with:

"animation.update(alpha) has been deprecated (due to its confusing name) " 
"in favour of animation.interpolate(alpha). Please use interpolate() instead!" 
let me know if it sounds good.

**Comment by leotrs** [comment]
"animation.update() has been deprecated. Please use animation.interpolate() instead."

Fewer words, same meaning.

**Comment by meanmachin3** [comment]
Can I take this up ?

**Comment by leotrs** [comment]
Yes, thanks!

**Comment by musabkilic** [comment]
Sorry, I didn't see @meanmachin3 comment. Should I sent a pull request anyway?

**Comment by meanmachin3** [comment]
@musabkilic It's okay :)
I'll work on something else. You could take it

**Comment by musabkilic** [comment]
@meanmachin3 Thanks! :)

**Comment by cobordism** [comment]
closed due to #503
