### ISSUE TITLE
Reworking --save_pngs

### ISSUE THREAD

**Issue by huguesdevimeux** [ManimCommunity/manim#425]
Now, --save_pngs save each frame of the video as .png. 

The flag name is not explicit enough, I think. 

We should change it to, I don't know, `--save_each_frame` ?

**Comment by kolibril13** [comment]
Sounds reasonable!
My English is not perfect, but I have the feeling that frames should be singular  `--save_each_frame`.
Or with plural maybe like this:  `--save_all_frames`.

**Comment by huguesdevimeux** [comment]
Yeeea that's embarassing. I will change to `--save_each_frame`

I take the input, but `all` is I think less explicit compare to `each`.

**Comment by huguesdevimeux** [comment]
@leotrs No, but it could. I don't think it would be that hard to implement. 

Not sure if I have time to take the PR tho

**Comment by huguesdevimeux** [comment]
Update : This is seemingly easy to implement. We have just to touch this : 
https://github.com/huguesdevimeux/manim/blob/481156288d8671f9657afcc87066786845998f17/build/lib/build/lib/build/lib/build/lib/build/lib/manim/scene/scene_file_writer.py#L329-L344

```python
    def write_frame(self, frame):
        """
        Used internally by Manim to write a frame to
        the FFMPEG input buffer.

        Parameters
        ----------
        frame : np.array
            Pixel array of the frame.
        """
        if self.write_to_movie:
            self.writing_process.stdin.write(frame.tostring())
        if self.save_pngs:
            path, extension = os.path.splitext(self.image_file_path)
            Image.fromarray(frame).save(f'{path}{self.frame_count}{extension}')
            self.frame_count += 1
```
BUT my concern is how to test this. So, we have to implement a way to test images before implementing this.  
```

**Comment by kolibril13** [comment]
But this is something one can already do, see the flag -n
```
  -n FROM_ANIMATION_NUMBER, --from_animation_number FROM_ANIMATION_NUMBER
                        Start rendering at the specified animation index, instead of the first animation. If you pass in two comma separated
                        values, e.g. '3,6', it will end the rendering at the second value
```
E.g. this script:
```py
from manim import *

class Hello(Scene):
    def construct(self):
        dot = Dot().set_color(GREEN)
        self.add(dot)
        self.wait()
        self.play(dot.set_color,RED)
        self.play(dot.set_color,BLUE)

import os ; import sys
from pathlib import Path
if __name__ == "__main__":
    project_path = Path(sys.path[1]).parent
    script_name = f"{Path(__file__).resolve()}"
    os.system(f"manim  -l --custom_folders  --disable_caching -s -p -n 0,1 -c 'BLACK' --config_file '{project_path}/manim_settings.cfg' " + script_name)
```
gives me this image of the green dot:
![Hello](https://user-images.githubusercontent.com/44469195/92617073-39c35780-f2bf-11ea-9861-e0087b6010c2.png)

**Comment by huguesdevimeux** [comment]
@kolibril13 Yes, but it's _hacky_., and it does only save the last frame of the `self.wait` invocation (in your example)

**Comment by kolibril13** [comment]
> Yes, but it's hacky

I agree with that.

**Comment by leotrs** [comment]
TBH I think we should just wait until the config system is refactored, which is going to massively simplify what SceneFileWriter needs to do.

**Comment by leotrs** [comment]
As for this issue, I suggest --save_all_frames.

**Comment by kolibril13** [comment]
What just comes to my mind, what would be really beautiful:
A flag that enables you to output a frame as an SVG file.
I had situations where  I used manim content in a document and I wanted to adjust some small things by eye, however that was not possible as png. 
Also, an SVG output would enable you to get to know your scene better.
E.g. deleting the top layer of shapes in Inkscape and realizing: Oh, there are still Mobjects hidden under it.

**Comment by leotrs** [comment]
Yes, saving to other image formats would be nice. Right now we are limited by two main reasons: the `Camera` object only manipulates pixel arrays directly, and the `SceneFileWriter` only works by sending pixel arrays to ffmpeg.

In the future, once we have refactored `Camera` into a `Renderer`, and once we have refactored `SceneFileWriter` as well, this may be possible at some point.

**Comment by huguesdevimeux** [comment]
Soo, at the moment what do we do ? Just temporarly remove this flag, waiting for a new one ?

**Comment by leotrs** [comment]
I think exporting to SVG is out of the question currently.

As for the original topic of this issue: I'm happy to change save_pngs to save_all_frames for the time begin
