### ISSUE TITLE
Prepare documentation for translation

### ISSUE THREAD

**Issue by behackl** [ManimCommunity/manim#426]
We should look into setting up https://www.sphinx-doc.org/en/master/usage/advanced/intl.html and document the steps required for adding translations.

**Comment by JPTIZ** [comment]
Since I'm in Software Internationalization class in my university, I would like to help with this. Could help me with studies :)

**Comment by naveen521kk** [comment]
I am assigning you @JPTIZ

**Comment by MysaaJava** [comment]
I also want to help with this issue. I can manage servers and software things if you want (even though you may be more qualified to do this than me). I've looked around and found Pootle software that made possible community translation (without spending a penny). What do you think of this ? Do you have other plans ?

**Comment by leotrs** [comment]
I don't think we have decided upon what tools or frameworks we will use.

Could you please write a short blurb of why we should use Pootle instead of any other tools?

I suggest @MysaaJava and @JPTIZ work in tandem over discord :)

**Comment by JPTIZ** [comment]
Thanks a lot for the assign (and the help wish)!

@leotrs Okay :) Just joined the discord server.

**Comment by MysaaJava** [comment]
Pootle is only an interface for the translation. It is not part of the source code. It is sphynx that will manage the translated docs, pootle will only be a web UI for translating .pot files (untranslated) to .po files (translated in one language). 

Why pootle ? Because it is free unlike many translation interfaces, and it is the one that sphynx proposes on its [Documentation about translation](https://www.sphinx-doc.org/en/master/usage/advanced/intl.html).
The workflow is described on the page, through this drawing ![Screenshot_20201008-143432_Firefox.jpg](https://user-images.githubusercontent.com/33335046/95459096-7001fe80-0973-11eb-968b-3fe08474fca6.jpg)
Again, there is no need for choosing another framework as sphinx already supports internationalization. We only need to setup a web UI in order to make the translating process easier for community translators.

(JPITZ what is your discord name ?)

**Comment by JPTIZ** [comment]
> (JPITZ what is your discord name ?)

Just renamed myself to `jptiz` there to make things easier :)

**Comment by leotrs** [comment]
Yeah, if this is what is supported and recommended by sphinx then we should use this.

**Comment by leotrs** [comment]
Any updates on this? Eager to see the translation move forward :)

**Comment by MysaaJava** [comment]
Well, i'm experimenting with the pootle server. The docs build fine with multiple languages and pootle seems to be usable.
I understood how to make translations on readTheDocs, see [My clone of the docs](https://manimdummyforintl.readthedocs.io/en/latest/), you can change the languages between english and french (i only translated the first paragraph into french). You can look at the [internationalization branch of my personnal fork](https://github.com/MysaaJava/manim/tree/internationalization) if you want to check.

The last think i have to do is to link pootle with github, so pootle will be aware of github pushes, and github aware of pootle new translations. I also need to find a host for the pootle server (i can do it, but i don't have a very stable internet connection), but i will address this issue on Discord.

Also feel free do DM or ping mi if you want updates, or have questions

**Comment by leotrs** [comment]
Thanks a ton @MysaaJava, all your efforts do not go unnoticed. Please let us know if there's anything we need to setup on the GitHub side to keep moving this forward.

Also, the hosting for the pootle server sounds like a devops task to me #622. Cc @cobordism does the www.manim.community domain come with hosting? Or could we use github pages somehow?

**Comment by MysaaJava** [comment]
Updates, we may be able to use transifex, which is a paid service, but is free for open-source projects.
I made a copy (not a fork) of manim community on which i will try to setup transifex. I also need to se if people can do anonymous translations.

**Comment by MysaaJava** [comment]
Updates, we may be able to use transifex, which is a paid service, but is free for open-source projects.
I made a copy (not a fork) of manim community on which i will try to setup transifex. I also need to see if people can do anonymous translations.
I'll also write something in the docs, on the contribute page, to explain how to help with translating.

**Comment by MysaaJava** [comment]
Hello ©ManimCommunity ! I'm making an update on the progress on the internationalization (i18n) thing. Please tell us what you think about how we planned to setup things. I will give you links to the dummy clones I made so you can check how it renders. If you read everything and you agree, please react with :thumbs_up: .
We are planning to use Transifex (https://www.transifex.com) to have a nice UI to make the job easier for translators. Transifex is a paid service, which offers free subscription to open-source projects (like manim). We can setup it so the translated documentation is automatically built and sent to readthedocs and github.
The website have a «reviewing» system, on which translated texts need to be validated by at least one trusted reviewer.
To submit translations, you need to create an account. This prevent anonymous users from translating, but it allows to manage roles for the team (Translator, Reviewer, Language Coordinator, Project Maintainer ,…). Furthermore, you can connect directly with you GitHub account.


*How does the translation process work* ?
You can call `make gettext` on sphinx documentation, which create `.pot` files, which are «ready for translation» text files. Those .pot files are sent to Transifex interface, which convert them to `.po` files, one for each language and `.pot` file. Then, you can build the docs with sphinx specifying the language and sphinx will automatically search for filled `.po` files.


*Two questions for you*
First, Transifex offers two way of sending the translated po files to github: The first one is by making PRs, the second is by commiting directly.
The problem with PRs, is that it creates a loooooot of PRs (one for each translated files). Commiting directly seems great but it is still a lot of updates on the main branch. So I present three solutions.
1 -> A lot of PRs to master, you have to accept them all
2 -> Commiting directly to master
3 -> Commiting directly to another branch (i18n), this branch can be on my personnal fork if you don't want to pollute the main repository. And every n days (for example one week before each release), i will make a PR for merging everything that has been translated so far.

Another problem is that, when you modify the docs, you have to update the `.pot` files, so Transifex knows about the new translations. I will make a `make i18n` command to do it more quickly. I think i will make a test (like black) that blocks merging if the command has not been run. I can also setup git hooks, like EulerTour proposed in #589, so it is run automatically. And finally, I think that `make html` should also build the `.pot` files, (it doesn't make the build process longer).
4 -> Another solution would be that no one runs the `make i18n` command (so transifex is not synchronized with github), and I will manually update the .pot files every month. What do you think ?

We will also write a section under «Contributing» in the docs, showing how to help with translating the docs. We will also check that all the text in the docs is actually exported and translatable.
We will also try to make the docs build process as fast as possible (for now, exporting PO files renders every manim video, which is useless).

The transifex organisation: https://www.transifex.com/manim-community/
My github fork's branch: https://github.com/MysaaJava/manim/tree/i18n
The documentation: 
en -> https://manimdummyforintl.readthedocs.io/en/latest/
fr -> https://manimdummyforintl.readthedocs.io/fr/latest/

Thanks for reading !

This post will be send on both Github and Discord, feel free to answer with the one you prefer, and don't bother pinging me !

**Comment by leotrs** [comment]
Just a quick update from the Discord discussion: I believe we should have some kind of procedure that allowed us to mark certain documents as "ready for translation". Since the codebase is undergoing major changes continuously, we don't want to have the translators do some work that will have to be scrapped if a major change occurs. This raises the question of priorities. I believe we should try to have the installation and basic tutorials always up to date, and start translating those. The docstrings and reference manual can wait until the library reaches a more stable state.

@MysaaJava is there a way to "mark" certain documents as "ready"? Perhaps we may go as far as generating .po files only for those documents marked as ready?

Thanks @MysaaJava @JPTIZ for all the hard work here.

**Comment by MysaaJava** [comment]
Well, the simplest way i found to avoid everyone from having to update .po files by hand is to generate them every month by hand (of course, i will make script to automate the process).
How will my script work: it will first use sphinx to generate all the po files. Then, i will filter out strings that are not translatable (for example Class names). I'll do a script with sed/awk/regexes. Then in this process, i can easily filter parts that are not ready. I suggest three ways of doing that:
- adding a WIP text in every paragraph when the text is not ready for translation.
- Have a ready_for_intl.list file that lists the files that are ready, and we can mark files to be ready here.
- Put a special character sequence in ready paragraphs, So the script detects when the text is ready. But i don't know if it is possible.

Which is better ? Also, if you have other ideas, feel free to propose.

**Comment by leotrs** [comment]
I like the second one, maintaining a curated list of documents/paragraphs that are ready.
