### ISSUE TITLE
Choose a linter and formatter

### ISSUE THREAD

**Issue by eulertour** [ManimCommunity/manim#43]
In case you aren't familiar:
A *formatter* ensures all code is formatted in the same way
A *linter* ensures that all code follows best practices

A bunch of popular ones are listed [here](https://books.agiliq.com/projects/essential-python-tools/en/latest/linters.html#pylint).

Personally I don't really care as long as we choose a good one, but if nobody has a strong opinion either way I'll nominate black + pylint.

After we get Travis CI running we can enforce them for each merge.

**Comment by leotrs** [comment]
+1 black and +1 pylint

**Comment by naveen521kk** [comment]
:+1: for black and pylint

**Comment by leotrs** [comment]
@naveen521kk what is codacy for?

**Comment by naveen521kk** [comment]
[Codacy](https://www.codacy.com/) is a Code Quality checker.

**Comment by raghavg123** [comment]
It's paid though I think?

**Comment by naveen521kk** [comment]
Its free for Open source. So how about adding it. It checks every PR whether it is well formatted or not.

**Comment by Aathish04** [comment]
> Its free for Open source. So how about adding it. It checks every PR whether it is well formatted or not. 

Sadly, it's only free for teams of 4 people or smaller. We have eleven people who'd like to continue to work on the Manim Community repo.

https://support.codacy.com/hc/en-us/articles/208942945-Plans-and-Billing

It's stated at the very bottom of the linked page.

**Comment by naveen521kk** [comment]
> > Its free for Open source. So how about adding it. It checks every PR whether it is well formatted or not.
> 
> Sadly, it's only free for teams of 4 people or smaller. We have at least eleven people who'd like to continue to work on the Manim Community repo.
> 
> https://support.codacy.com/hc/en-us/articles/208942945-Plans-and-Billing
> 
> It's stated at the very bottom of the linked page.

Checking it out, its for people who want Codacy for a private repository there is a 4 people and for an OS there is nothing so. And also they say number of people who manage the codacy page and not number of *collaborators* who contribute to this repository. It's free for OS.

**Comment by Aathish04** [comment]
> Checking it out, its for people who want Codacy for a private repository there is a 4 people and for an OS there is nothing so. And also they say number of people who manage the codacy page and not number of *collaborators* who contribute to this repository. It's free for OS.

_Users are developers contributing to the repository and any team member with access to the code analysis results on the Codacy UI. Your organization should have as many users as your repositories have contributors._

I may be understanding this wrongly, but they say that all the people who are _contributers_ are also _Users_ and all users will get access to the analysis results on the Codacy UI.

**Comment by leotrs** [comment]
What would be the benefits of using Codacy *on top of* black and pylint?

**Comment by naveen521kk** [comment]
Codacy help in checking PR who may have not use pylint while writing code. It uses pylint or something similar to check the code in cloud. @leotrs .

**Comment by leotrs** [comment]
I think running black on Travis CI achieves the same.

**Comment by eulertour** [comment]
Whatever we use to check aside, it looks like black and pylint are the ones to go with.

**Comment by leotrs** [comment]
It seems like we have chosen a linter and a formatter, so this issue has ran its course. We can continue discussion in #33 for travis setup.

**Comment by yoshiask** [comment]
For anyone still confused about whether Codacy is free for OS, it looks like it is:
![image](https://user-images.githubusercontent.com/7549325/82630602-03df5380-9ba8-11ea-9198-76dd5d49db87.png)

**Comment by leotrs** [comment]
@yoshiask sounds good. TBH it's still not clear to me what it would offer on top of pylint + black. If there is still a need for it then let's open a different issue focusing on codacy :)
