### ISSUE TITLE
Latex and Sphinx are not yet functioning together.

### ISSUE THREAD

**Issue by kolibril13** [ManimCommunity/manim#432]
This example is working on sphinx:
```
.. manim:: DotScene1
    :quality: low
    :save_last_frame:

        class DotScene1(Scene):
            def construct(self):
                dot = Dot().set_color(GREEN)
                self.add(dot)
                self.wait(1)
```
However, when I have something tex related, it throws an error:
```
.. manim:: TextExample
    :quality: medium
    :save_last_frame:
    
    class TextExample(Scene):
        def construct(self):
            t = TextMobject("Hello World")
            self.add(t)
```
> Exception occurred:
  File "/home/k/projects/manim-community/manim/utils/tex_file_writing.py", line 32, in generate_tex_file
    with open(result, "w", encoding="utf-8") as outfile:
FileNotFoundError: [Errno 2] No such file or directory: 'media/Tex/7d1ec941f0e30957.tex'
The full traceback has been saved in /tmp/sphinx-err-4zdxhjgt.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
make: *** [Makefile:26: html] Error 2

A similar error message comes e.g. for this example:
```
.. manim:: Plot1
    :quality: medium
    :save_last_frame:

    class Plot1(GraphScene):
       def construct(self):
           self.setup_axes()
           my_func = lambda x: np.sin(x)
           func_graph=self.get_graph(my_func)
           self.add(func_graph)
```

**Comment by behackl** [comment]
I've identified the underlying issue for this as well, preparing a PR in a moment.
