### ISSUE TITLE
REFACTOR : _run_config() should not return file_writer_config.

### ISSUE THREAD

**Issue by huguesdevimeux** [ManimCommunity/manim#443]
Now, `_run_config` returns that : 
https://github.com/ManimCommunity/manim/blob/1a516dbc64b0f105914e5a9be6d66aa839cec964/manim/config/config_utils.py#L536

4 things, including file_writer_config. 

I do think `file_writer_config` should be computed outside this function, as now there are several others config type (in particular `cfg` subcommand, logger, and later `livestream` subcommand). 

file_writer_config should use `config_parser` like the other configs, outside of `_run_config()` 

Cc @leotrs

**Comment by leotrs** [comment]
I'm working on #337 which is going to make this problem go away.

I never liked having separate `file_writer_config` and `config`. The former was meant to be used only internally, and the latter was meant to be exposed to the user. But they ended up being pretty similar. In the future, I'm planning on removing `file_writer_config` and having a single `config` dict. The `config` dict will be used (almost always) internally, and the user will have access to another object, a `frame`, which contains things like `pixel_width` and `pixel_height`, which are the config options most used by users, but also things like `UP` and `LEFT_SIDE`, which refer to the geometry of the frame.

Also in the future, the whole mess of cfg subcommands, logger, config, _run_config, _parse_cli etc etc etc will be refactored so nothing is really parsed twice.

**Comment by leotrs** [comment]
Done. See #337
