### ISSUE TITLE
Issue Saving Log files

### ISSUE THREAD

**Issue by naveen521kk** [ManimCommunity/manim#453]
https://github.com/ManimCommunity/manim/blob/e011f640cf085879b67cce7bc0dc08450ba92d3b/manim/config/config.py#L158-L165
Here it defines that scene name will be log file name.  But a problem is when I tried with no scene name and entered it at runtime. The log file a saved in `media/logs/.log` which is weird and should not happen.

**Comment by huguesdevimeux** [comment]
Yes, and the why is indicated in the comment. 
I think this should be changed, and follow @leotrs suggestion that is to set log name as the name of the file containing the scene.

**Comment by charlie4fun** [comment]
Hi, I want to contribute, but not sure how to reproduce the issue: `manim scene.py SquareToCircle -pl` does not produce any logs

**Comment by leotrs** [comment]
Try `manim scene.py SquareToCircle -pl --log_to_file`.

**Comment by charlie4fun** [comment]
I don't know how to rerun particular tests in CI. As they show `GitHub Actions has encountered an internal error when running your job.` When i was rerunning them altogether they show same error as mentioned above for a different set of tests

**Comment by charlie4fun** [comment]
So finally all the checks passed, I guess build server was too busy yesterday, that's why those internal error appear. Please review

**Comment by leotrs** [comment]
@charlie4fun I'm a little confused - I see you have a branch on your fork for fixing this, but did you open a PR on this fork?
