### ISSUE TITLE
Should livestreaming use partial movie files ? 

### ISSUE THREAD

**Issue by huguesdevimeux** [ManimCommunity/manim#461]
The title;

The way that livestream used to be implemented was to directly output the resulting stream created by ffmpeg to the dedicated URL. No partial movie files was created and combined, as everything was redirected.  It works like a charm, does not create any file, etc. 

**BUT :**
I thought we could change that. We could make manim use partial movie file system.
It would enable us to : 
- Go back (or further) from x scene during the live, which is pretty cool. 
- Load a scene, or partial movie files from a scene. 
- Use scene caching, which can be a big deal buuut .. I doubt it would be useful for a livestreaming feature ? Will people often run the exact same scene ?, and  the time-saving argument does not work here as it's streaming. 

Negative points : 
- It will create partial movie files, and potentially take some space. 
- It won't generate the stream frame-per-frame, but rather partial movie file per partial movie file. So, if if a scene is uncached, there will be some delay before showing up on the screen _and_ starting the rendering process. (Unless it's possible to either output the frames to a stream and to an .mp4 with FFMpeg ? I don't know. 

Please share your thoughts. Basically yes/no 

@ManimCommunity/core

**Comment by leotrs** [comment]
I think to answer this question we need to determine what is the intended use of the livestreaming feature.

**Comment by eulertour** [comment]
Implementing it this way would eliminate any potential for interactivity, so if it is done it would only work well for the de-facto CairoRenderer. But that aside, it'd be better in the long term to work toward a real-time renderer than try to get Cairo to behave like one.

**Comment by huguesdevimeux** [comment]
Livestreaming as I'm implementing (and as possible) is not really "interactive". It uses scene.play() and scene.wait() methods to make something appear on the screen. I think partial movie files are a smart move here, as it will enable some cool feature sucha s loop through an animation, repeat, go back, etc. 

Concerning a real time renderer, I completely agree, but this is not really the aim of live streaming (at least, as I conceive it, and as it used to be implemented).

**Comment by eulertour** [comment]
> Livestreaming as I'm implementing (and as possible) is not really "interactive". It uses scene.play() and scene.wait() methods to make something appear on the screen. I think partial movie files are a smart move here, as it will enable some cool feature sucha s loop through an animation, repeat, go back, etc.

This is true, but as I said such an implementation will only be useful while rendering with Cairo.

> Concerning a real time renderer, I completely agree, but this is not really the aim of live streaming

I would actually consider this to be the primary aim of livestreaming. Doing it with a real time renderer would allow for creating interactive visualizations, which would pave the way for the possibility of creating self-contained interactive lessons.

**Comment by huguesdevimeux** [comment]
Closing this, for the same reason as #441 .
