### ISSUE TITLE
Implement standard easing functions (as rate_func library)

### ISSUE THREAD

**Issue by cobordism** [ManimCommunity/manim#474]
### Context:
Manim has rate functions that determine the rate that animations run at. A nice video of the included functions is here:
https://youtu.be/FO-vi92R8i8?t=119
To use them you write `scene.play(animation, rate_func=XXX)`. They are located in `utils/rate_functions.py`.

### Problems with the current setup:
The functions work fine, but their names are confusing and not descriptive. For example `linger` might be better called `pause_at_end`, and `rush_into` sounds like it might start quickly but in fact does the opposite, `running_start` pauses at the start and so on...
Moreover, there is a somewhat standard collection of easing functions that we should include but currently do not. Take a look at https://easings.net/

### Suggestion:
Leave the current rate functions as they are for purposes of backward compatibility, but add the standard library of easings. Perhaps from here:  https://github.com/semitable/easing-functions/blob/master/easing_functions/easing.py

**Comment by leotrs** [comment]
Excellent idea. We should deprecate the current ones, and change their names, as well as add the new ones. This doesn't sound like a difficult PR, no?

**Comment by cobordism** [comment]
agreed.
sounds relatively simple to do.
perhaps you can tag it with "good first issue" to entice newcomers to try?

**Comment by nilaybhatia** [comment]
I think I'll be able to take this up next week, so temporarily assigning myself. If it turns out I can't, will edit this message and un-assign.
