### ISSUE TITLE
Sector.get_arc_center() is broken.

### ISSUE THREAD

**Issue by AkashKarnatak** [ManimCommunity/manim#480]
Sector.get_arc_center() does not work and always returns a warning message.
```sh
UserWarning: Can't find Arc center, using ORIGIN instead
 warnings.warn("Can't find Arc center, using ORIGIN instead")
```
Above error can be reproduced using the below code.
```py
from manim import *
class Test(Scene):
    def construct(self):
        sec = Sector(start_angle=0, angle=5*PI/3).move_to([1,0,0])
        print(sec.get_arc_center())
```

**Comment by leotrs** [comment]
Thanks for the report. Something tells me that this *might* even be the desired behavior, but the way it is handled right now, it's impossible to be certain. Cc @ManimCommunity/geometry any takers?

**Comment by AkashKarnatak** [comment]
@leotrs  I have solved this issue and I'll soon send a PR
