### ISSUE TITLE
Removing temp ffmpeg's temp-files 

### ISSUE THREAD

**Issue by huguesdevimeux** [ManimCommunity/manim#486]
Before partial movie files are generated by ffmpeg, scenefilewriter creates temp partial movie file and then move them and rename them with their definitive name (which is the hash of the animation). 
Why ? Why not rendering directly partial movie files? 
I think we should, if there is no objection, remove this and make ffmpeg directly render partial movie files.

**Comment by leotrs** [comment]
No objection here.

**Comment by farahash** [comment]
Is this still open? If it is, I would like to look into it.

**Comment by leotrs** [comment]
@farahash yes! Please feel free to discuss here or open a PR.

**Comment by huguesdevimeux** [comment]
@farahash and to assign yourself on this issue if you work on it ;)

**Comment by farahash** [comment]
@huguesdevimeux it doesn't seem like I can do that myself. Do I need to be added as a collaborator to the repo to get access? 
(you can go ahead and assign it to me if that works too)

**Comment by huguesdevimeux** [comment]
Sorry. I thought you could. 

Now you are assigned !
