### ISSUE TITLE
Install via choco fails 

### ISSUE THREAD

**Issue by csrabak** [ManimCommunity/manim#495]
In a Windows 10 64 bit machine with pristine conditions WRT to manim.

I mean a) no Python version at all. b) Pending LaTeX installation as per Readthedocs directions.

Issuing

```
choco install manim
```
fails.

The error message in the Powershell shows that the script attempted to call PIP but the installation of Python as requirement doesn't install pip.

I don't believe the massive log needs to be attached, but if this becomes non reproduceble by the dev team. I'll add the required reports, etc.

**Comment by naveen521kk** [comment]
I definitely need those error logs that to in debug mode, `-debug -verbose` with parameters. Make sure you remove personally identifiable details from that. Possibly a gist would help instead of pasting here.

> The error message in the Powershell shows that the script attempted to call PIP but the installation of Python as requirement doesn't install pip.

You are wrong here. It's windows and not Linux. The default python installer includes `pip` by default and chocolatey uses that.  It must be the case I think that you had a python installation previously that didn't have `pip`. If that's the case you would have to manually install `pip` or reinstall python and then run chocolatey. 
Ref: 
- https://chocolatey.org/packages/python3#notes
- https://docs.python.org/3/using/windows.html#installation-steps

**Comment by csrabak** [comment]
You're absolutely right about « It's windows and not Linux. » ‼️ 

I don't have an account in GitLab to post a gist, is it possible to attach here zipped?

Also, another friend attempted to install, and his results are as dismaying as mine:

This the capture of the cmd shell (notice the need to elevate rights):
```
16:31 30/09/2020

C:\WINDOWS\system32>cd \Users\manimuser\

C:\Users\manimuser>ver

Microsoft Windows [versão 10.0.19041.508]

C:\Users\manimuser>choco install manim
Chocolatey v0.10.15
Installing the following packages:
manim
By installing you accept licenses for the packages.
Progress: Downloading manim 1.0... 100%

sox.portable v14.4.1
sox.portable package files install completed. Performing other installation steps.
The package sox.portable wants to run 'chocolateyInstall.ps1'.
Note: If you don't run this script, the installation will fail.
Note: To confirm automatically next time, use '-y' or consider:
choco feature enable -n allowGlobalConfirmation
Do you want to run the script?([Y]es/[A]ll - yes to all/[N]o/[P]rint): A

WARNING: Write-ChocolateySuccess is deprecated and will be removed in v2. If you are the maintainer, please remove it from your package file.
 ShimGen has successfully created a shim for play.exe
 ShimGen has successfully created a shim for rec.exe
 ShimGen has successfully created a shim for sox.exe
 ShimGen has successfully created a shim for soxi.exe
 The install of sox.portable was successful.
  Software install location not explicitly set, could be in package or
  default install location if installer.

ffmpeg v4.3.1.20200831 [Approved]
ffmpeg package files install completed. Performing other installation steps.
Extracting 64-bit C:\ProgramData\chocolatey\lib\ffmpeg\tools\ffmpeg-4.3.1-win64-static_x64.zip to C:\ProgramData\chocolatey\lib\ffmpeg\tools...
C:\ProgramData\chocolatey\lib\ffmpeg\tools
ERROR: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Access to the path 'C:\ProgramData\chocolatey\lib\ffmpeg\tools\ffmpeg-4.3.1-win64-static' is denied.
The install of ffmpeg was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\ffmpeg\tools\chocolateyInstall.ps1'.
 See log for details.
```

An interesting thing to observe is the user of this machine has ImageMagick installed (which has a ffmpeg executable) but chocolatey ignores a system wide existing program. . .

He sent the extract of the log, but not with the switches as you request, so I think I'm not able to report in the detail you require.

I think the discussion you put about the issues in installing Python via chocolatey and the insistence of this tools on creating a subsystem of binaries is enough for me.

I'm abandoning chocolatey and will wait a release for PIP and go from there.

Thanks for your attention, and please close this bug as it seems the environments are too much unstable to be able to create a machine for reproducing thing short of a fresh install of SO, which is not feasible for any useful use of manimce.

Another subtle issue occurs in Windows machines that don't have Python installed [Who put Python in the Windows 10 May 2019 Update?](https://devblogs.microsoft.com/python/python-in-the-windows-10-may-2019-update/), and since the only way I could go back to this state in the machine would be restoring a "restore point", which is also unfeasible, at least for me right now, this issue would have to find another "guinea pig" machine to test this possible interaction

**Comment by csrabak** [comment]
I noticed I can myself close this issue.

I leave it as non reproducible or hard to reproduce...

**Comment by naveen521kk** [comment]
From the logs I could infer two things 
- You haven't elevated the shell I think. This could be the possible issue.
- The install fail for `ffmpeg` which is not under my control. So, you should be contacting `ffmpeg`'s maintainers [here](https://chocolatey.org/packages/ffmpeg)

Also, that python update includes pip as mentioned in the article. So there is no reason to change the current installer.

**Comment by leotrs** [comment]
What does "elevate the shell" mean, and how would they go about doing it?

**Comment by naveen521kk** [comment]
"elevate the shell" is similar to giving `sudo` permissions to linux terminal commands. Here, users would be doing something like the below post
https://www.howtogeek.com/194041/how-to-open-the-command-prompt-as-administrator-in-windows-8.1/

Chocolatey pretty much all the run in elevated shell or it gives warning.
