### ISSUE TITLE
ValueTracker must support increment also using +=

### ISSUE THREAD

**Issue by nilaybhatia** [ManimCommunity/manim#507]
Just what the title says. Here's an example 
```python
class Test(Scene):
    def construct(self):
        tracker = ValueTracker(0.0)
        tracker.set_value(2.0)
        print(tracker.get_value()) # -> 2.000
        tracker.increment_value(3.0)
        print(tracker.get_value()) # -> 5.000
        tracker += 4.0 # NEW proposed feature
        print(tracker.get_value()) # -> 9.000
```

**Comment by huguesdevimeux** [comment]
Very good idea. I would love to see a PR :) #

**Comment by SamMinkowicz** [comment]
Hey, @huguesdevimeux I can take this if it's still open.

**Comment by nilaybhatia** [comment]
Hi @SamMinkowicz,
We all appreciate your willingness to help the Manim Community out, but unfortunately I already started working on it and just opened a PR a minute ago before seeing your comment. You can still help us out by maybe giving suggestions on that PR :)

**Comment by huguesdevimeux** [comment]
@naveen521kk Please please assign yourself when you're working on an issue.

**Comment by nilaybhatia** [comment]
Yeah @huguesdevimeux , I forgot, my bad. Will keep it in mind now.

**Comment by naveen521kk** [comment]
> @naveen521kk Please please assign yourself when you're working on an issue

I'm not working on this. I think you have pinged me wrongly.
