### ISSUE TITLE
Add  Encoding declarations to Library

### ISSUE THREAD

**Issue by naveen521kk** [ManimCommunity/manim#51]
Add [ Encoding declarations](https://docs.python.org/3/reference/lexical_analysis.html#encoding-declarations) which is considered as python standart to all the files(.py *files*) in the library(*manimlib*). 
See
https://docs.python.org/3/reference/lexical_analysis.html#encoding-declarations

**Comment by PgBiel** [comment]
What's the need for this? Do other libraries do this?

**Comment by leotrs** [comment]
If I'm not mistaken, this helps our files be ran (compiled?) cross-platform. It's a good addition, and it doesn't really change the actual code base. Unless I'm wrong. I've been known to be wrong in the past.

**Comment by PgBiel** [comment]
It's probably not gonna have any effect, considering that basically none of our deps do it

**Comment by naveen521kk** [comment]
Shall I take up this issue.

**Comment by leotrs** [comment]
TBH, I'm not sure how necessary this is... for example I don't see these on numpy's code base. What do you think @eulertour ?

**Comment by eulertour** [comment]
I don't think it's necessary either.

**Comment by leotrs** [comment]
@naveen521kk to be quite honest, I think your time and expertise can be best used tending to other open issues :)
