### ISSUE TITLE
REFACTOR : Removing sounds features (NOT sound added to videos)

### ISSUE THREAD

**Issue by huguesdevimeux** [ManimCommunity/manim#511]
By "sound not added to videos" I mean all the sounds feature that used to be played when an animation render was finished. 
Example, here 
https://github.com/huguesdevimeux/manim/blob/037c9be804a73915d73106167ff4274f04d39576/manim/__main__.py#L168-L179

```python
            try:
                # By invoking, this renders the full scene
                scene = SceneClass()
                open_file_if_needed(scene.file_writer)
                if sound_on:
                    play_finish_sound() # HERE 
            except Exception:
                print("\n\n")
                traceback.print_exc()
                print("\n\n")
                if sound_on:
                    play_error_sound()
```

There are countless stuff related in the basecode, and I thinl it should be removed.

**Comment by eulertour** [comment]
I agree, this should be removed.

**Comment by jvdoorn** [comment]
I can do this unless @huguesdevimeux is working on it? I assume we want to remove all `play_*()` functions but keep `get_full_sound_file_path()` as it is used by `add_sound()` in [`scene_file_writer_.py`](https://github.com/ManimCommunity/manim/blob/41f6f054e0fce79d8a34b64d93cf9dfd9a134bf2/manim/scene/scene_file_writer.py#L276-L300). Maybe to keep the code clean we should move the function to that file?

**Comment by huguesdevimeux** [comment]
@jvdoorn _Please_ do, I'm not working on this ! 

Concerning your question, I prefer to not touch [`scene_file_writer_.py`](https://github.com/ManimCommunity/manim/blob/41f6f054e0fce79d8a34b64d93cf9dfd9a134bf2/manim/scene/scene_file_writer.py#L276-L300), as it is very messy and will be refactored in a relatively near future. 

Maybe what you could do is let it in `sounds.py`, but add a comment stating that this is used in `add_sound` function in `scene_file_writer.py`. 
Furthermore, I think all of the sound feature will be completly removed, as I'm not even sure if it is working, and it is pretty useless IMO. 

cc @leotrs

**Comment by leotrs** [comment]
Please remove play_error_sound and play_finish_sound, and whatever code is used to support those calls. There is some code in scene_file_writer that allows the user to add sound to a video. That's a different thing, please leave that in.

@jvdoorn thanks for all your contributions BTW. Are you on Discord? That's where a lot of the discussion happens as well. (It's not necessary to participate in discord to keep contributing, I just thought I'd invite you :) )

**Comment by jvdoorn** [comment]
As far as I can tell the `sox` library/dependency is only used for `play_*_sound` and not for adding sound to video. Is it safe to remove this as a dependency?

Also, I just joined 😄

**Comment by leotrs** [comment]
> As far as I can tell the `sox` library/dependency is only used for `play_*_sound` and not for adding sound to video. Is it safe to remove this as a dependency?

Yes

**Comment by naveen521kk** [comment]
Is it done? Can the issue be close?

**Comment by jvdoorn** [comment]
Yes!
