### ISSUE TITLE
Add the "hacktoberfest" topic

### ISSUE THREAD

**Issue by jvdoorn** [ManimCommunity/manim#518]
### If this is a feature request:
Hacktoberfest now requires repositories to include the "hacktoberfest" topic for PRs to count. Assuming we want this repository to count for Hacktoberfest we should add this topic. See https://hacktoberfest.digitalocean.com/details#details. Alternatively the label `hacktoberfest-accepted` could be added to PRs.

**Comment by naveen521kk** [comment]
Done! 🎉
