### ISSUE TITLE
Option for 2D vectors

### ISSUE THREAD

**Issue by kolibril13** [ManimCommunity/manim#539]
At the moment, vectors have to be always 3D like [2,3,0] or np.array([2,3,0]).
What do you think of an automated behaviour, that adds a 0 to a 2D vector automatically, when a user gives a 2D vector?

**Comment by leotrs** [comment]
I have also found this to be annoying in the past. However, note that if we are going to make *every* function accept either 2D or 3D vectors, we should do so carefully so that we don't incur in runtime penalties.

**Comment by kolibril13** [comment]
Good point.
We could also make 2D vectors default, and add the optional flag `three_d_vector= False`, which can be set to true when going with 3d scenes
