### ISSUE TITLE
requirements.txt is incomplete. `pip install` is broken

### ISSUE THREAD

**Issue by cobordism** [ManimCommunity/manim#542]
**Describe the bug**
The requirements.txt file is missing some entries.
This means manim is not currently installable through pip

**To Reproduce**
An a clean system, run `pip3 install -r ./requirements.txt` and then try to run manim to compile a scene.

**Output**
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.8/runpy.py", line 144, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/home/cobordism/.local/lib/python3.8/site-packages/manim/__init__.py", line 45, in <module>
    from .mobject.svg.text_mobject import *
  File "/home/cobordism/.local/lib/python3.8/site-packages/manim/mobject/svg/text_mobject.py", line 13, in <module>
    import pangocairocffi
ModuleNotFoundError: No module named 'pangocairocffi'

```

**Comment by naveen521kk** [comment]
Remove requirements.txt from repo. That is not required. Also, you can do `pip install .` to get the correct one.

**Comment by leotrs** [comment]
@naveen521kk thanks for your response. That's kind of what I thought.

@cobordism may I ask you to go over [this page](https://manimce.readthedocs.io/en/latest/installation/for_dev.html) and see if that solves your issue? This will hopefully fix your issue, but also you will be helping us by troubleshooting this documentation page :)

**Comment by cobordism** [comment]
My issue was solved by 
```
   pip3 install pangocffi
   pip3 install pangocairocffi
   pip3 install cairocff
```

I honestly don't want to have to learn about poetry and virtual environments right now.

**Comment by leotrs** [comment]
That's fair.

**Comment by naveen521kk** [comment]
You could get it by just running 
```sh
poetry export -f requirements.txt --output requirements.txt
```
and then use it as you like. But I think that file should not be there on the repo.
Ref: https://python-poetry.org/docs/cli/#export

**Comment by kolibril13** [comment]
I was reinstalling manim yesterday, what worked for me was:
```
conda install -c conda-forge poetry
sudo apt-get install libcairo2-dev libjpeg-dev libgif-dev
pip install pycairo
poetry install
```

**Comment by cobordism** [comment]
Ok. I make a pr to delete requirements.txt
