### ISSUE TITLE
 [BUG-General] Terminal output not formatted and uses ASCII in windows

### ISSUE THREAD

**Issue by naveen521kk** [ManimCommunity/manim#552]
**Describe the bug**
I am on Windows and command prompt and I `cd` into example_scenes directory and run 
```sh
manim basic.py
``` 
and I get a output like below.
![teminal-format](https://media.discordapp.net/attachments/581738732646957057/766319441209327728/unknown.png)
I should get in green colour though.

**To Reproduce**
Just running the one in example_scene in enough.

**Expected behavior**
The ill formatted thing should be in green colour.

**Logs**
<details><summary>Terminal output (Screenshots acceptable)</summary>

![teminal-format](https://media.discordapp.net/attachments/581738732646957057/766319441209327728/unknown.png)

</details>

**System Specifications**

<details><summary>System Details</summary>

- OS (with version, e.g Windows 10 v2004 or macOS 10.15 (Catalina)): Windows 7
- Python version (`python/py/python3 --version`): 3.8

**Comment by huguesdevimeux** [comment]
Isn't rich's fault ?

**Comment by naveen521kk** [comment]
Yeah it is rich. What we can do is to lock a stable version say v5. I know it works correctly on v5 but not on v8.

**Comment by huguesdevimeux** [comment]
That's a shame. 
Maybe we should open an issue on rich's repo and lock to a stable version, as you said.

**Comment by naveen521kk** [comment]
Done https://github.com/willmcgugan/rich/issues/393

Also, I will make a PR to make sure we use rich version<=7.0.0.

**Comment by naveen521kk** [comment]
Fixed in rich v9.0.1 but anyhow I am gonna wait till the version is locked by #573

**Comment by huguesdevimeux** [comment]
> I am gonna wait till the version is locked by

What do you mean by that ?

**Comment by naveen521kk** [comment]
> What do you mean by that ?

We should force installation of rich to `^6.0.0` and not any version.
