### ISSUE TITLE
Improve error reporting with PDF format and LaTeX

### ISSUE THREAD

**Issue by PhilippImhof** [ManimCommunity/manim#555]
Currently, if users have an old version of `dvisvgm` (older than 2.4 from May 2018) or if their `dvisvgm` is not configured correctly (e.g. missing `libgs` from Ghostscript), video rendering just fails and the users sees `unknown option --pdf` in their output.

We could improve this:

- do a test call to `dvisvgm --pdf` one time and check the exit status
- if it fails, raise an exception and output something along the lines of "Your installation does not support converting PDF to SVG. Consider updating `dvisvgm` to at least 2.4. If this does not solve the problem, please refer to our documentation."
- add some information in our docs 
  - On Mac, people must have Ghostscript **and** `libgs` installed; installing MacTex does not, by default, install the latter. It is a separate package.
  - Sometimes, `libgs` is installed, but cannot be found by `dvisvgm`. In this case, the user must execute `export LIBS=<path>` prior to running manim

**Comment by cobordism** [comment]
alternately, we can check if `pdf2svg` is installed and only if that also fails .... 

...on second thoughts, let's just print a warning message :D

**Comment by naveen521kk** [comment]
I think it would be better to write a small test on this, say bash or python, to check this.

**Comment by PhilippImhof** [comment]
That's fine for us. But it does not help the user who has an old (or no) version of `dvisvgm` installed.

**Comment by naveen521kk** [comment]
> Ah sorry, I think misunderstood. But IMHO users would not run a test. They run manim and see an obscure error.

I think there was an issue on that previoiusly. We can add that script to the [Troubleshooting](https://manimce.readthedocs.io/en/latest/installation/troubleshooting.html) section and say if they run into an there is a way to fix it.

**Comment by PhilippImhof** [comment]
Adding this to the troubleshooting section is a good idea. However, I still think we should improve the error message, i.e. not just spit out the error from a child process. At the moment, the user can not even see what child process causes that error. But with your idea, the message could just say that calling `dvisvgm` failed and the user should check the troubleshooting section.

**Comment by leotrs** [comment]
"Your installation does not support converting PDF to SVG. Consider updating dvisvgm to at least 2.4. If this does not solve the problem, please refer to LINK_IN_TROUBLESHOOTING_SECTION_HERE."

**Comment by PhilippImhof** [comment]
So after all, I suggest we use `subprocess.run` instead of `os.system` for running `dvisvgm`. This allows us to easily capture STDERR. We can then output 
> "Your installation does not support converting PDF to SVG: <original_error_message>. Consider updating dvisvgm to at least 2.4. If this does not solve the problem, please refer to LINK_IN_TROUBLESHOOTING_SECTION_HERE."

Capturing just the exit code is not enough, because I get `returncode=0` even if I cause the process to fail. But checking whether STDERR is empty should work on any platform. (We can also use `-v1` as a parameter. In that case, `dvisvgm` gives no output on success, but prints error messages. That makes it even more flexible for platforms that would not cleanly separate STDOUT and STDERR.)

I will try to come up with a patch in the next days.

**Comment by leotrs** [comment]
Was this closed by #561 ?

**Comment by PhilippImhof** [comment]
I would say so, yes.
