### ISSUE TITLE
remove "alignment" attribute in LaTeX

### ISSUE THREAD

**Issue by cobordism** [ManimCommunity/manim#556]
Centering Text in LaTeX
--------------------------------
If you want to center text in latex you can do this
```
\begin{center}
Lorem Ipsum
\end{center}
```
or you can do this
```
\centering Lorem Ipsum
```

The alignment and tex_environment keyword arguments
--------------------------------------------------------------------------
In vanilla manim (i.e. without user interference) we only use two alignments. Namely `\centering` for Tex() and "" for MathTex().

We also have the tex_environment keyword argument. Again we only use two:
In Tex() we use tex_environment=None and in MathTex we use tex_environment="align*" -- because everything in an align* environment is assumed to be in maths mode.

Suggested change
-------------------------
Make the default tex_environment for Tex() be "center" and get rid of alignment altogether.

This has the added benefit that if someone changes the tex_environment on their Tex object to something like tabular, they don't get an unexpected "\centering" in their tex code.

**Comment by cobordism** [comment]
@PhilippImhof let's take this opportunity to also enable environments that have a different begin and end.

eg
`\begin{tabular}{cccl}` ends with `\end{tabular}` 

easiest (and backward compatible) hack would be to say tex_environment="tabular}{cccl" and make the end-environment command stop at the first closing brace it encounters.

**Comment by PhilippImhof** [comment]
Wouldn't it also preserve compatibility if we used `tex_environment` and an additional `environment_end`, defaulting to `None`. If no `environment_end` is given, we use `\end{<tex_environment>}`. 

In any case, we should document the possibility to have an environment `tabular}{cccl` with no closing brace, explaining that this text is put verbatim between `\begin{` and `}`.

**Comment by cobordism** [comment]
> In any case, we should document the possibility to have an environment tabular}{cccl with no closing brace, explaining that this text is put verbatim between \begin{ and }.

agreed.

I'm going to assume that this is a very niche usecase. (Both changing the environment manually and then especially changing it to something where the begin and end commands are different.

Remember, it is already now possible to use tex_environment=None and then use the string
```
r"""\begin{my-environment}{whatever=I-want}
blablabla
\end{my-environment}"""
```
The _only_ thing I cannot do, is "break", "up", "the", "tex content into multiple pieces". Essentially I would be limited to a SingleStringTex() mobject and would need to use things like `mymobject[0][25:72]` to address the sub-parts, and that requires a lot of counting of characters - or a lot of trial and error.

Having a tex_environment_end might be cleaner than stopping the end command on a brace, but it introduces yet another keyword... My suggestion, while admittedly a little hacky, enables "multi" "string" "use" for all environments without introducing any new arguments at all. And if we're being good, we'll actually write it so that all of the following work:

tex_environment = "align*"
tex_environment = "{align*}"
tex_environment = "\begin{align*}"
tex_environment = "{tabular}{cccl}"

as they say for APIs - be liberal in what you accept, be conservative in what you produce.

**Comment by cobordism** [comment]
Note: It is always possible to determine the correct `\end{environment}` command from the `\begin{environment}{options}` command and therefore I think it should not be a separate keyword argument.

**Comment by leotrs** [comment]
Any updates on this one?

**Comment by PhilippImhof** [comment]
I'd say this can be closed. The linked PR resolves it, IMHO. Let's see if @cobordism agrees.

**Comment by cobordism** [comment]
yes. this one is done in PR 567
