### ISSUE TITLE
new feature: animation slideshow

### ISSUE THREAD

**Issue by mathmerizing** [ManimCommunity/manim#563]
## Motivation
Currently manim animations are mostly being used to create videos in which mathematical concepts are being explained. However, many people might benefit from an option where the manim user can navigate through the animations with the left and right arrows. Possible use cases for this are presentations, lectures, ...
This way it is easier to pause and explain some concept and then proceed with the next animation. Additionally, this should enable the presenter to go back and reference an old slide /frame of an animation.

## Current features in manim
- each animation is rendered as a separate video
- 'save-last-frame' option can be enabled 

## What needs to be done
- create outline of presentation from video animations and corresponding frames (which file should be played/shown when?)
- create a simple GUI (or maybe even only a key logger) which recognizes when the right and left arrow have been clicked and plays the correct video animation, at the end of the video the last frame is being shown

**Comment by leotrs** [comment]
This is a great idea and something I would love to see in manim. @yoshiask even has a PPT-exporter functionality already!

My personal problem is that I don't use PPT, so I was never able to use @yoshiask add-on. So I had to make my own. My version works by making manim render the .mp4 video of each individual animation, *as well as a .png of the first frame of each animation*. Then with a single .html document I can load all of that into a browser. Using a bit of JS/CSS I can use the arrow keys to present the animations. The png of the first frame of each animation is used as a thumbnail for each "slide" of the presentation. This is just a description of how mine works, but I don't mean to say this is how it *should* work!

I have a working version of this on my local setup. It's not in a state that can be PR'd right now, and it was developed with an old version of manim so I don't think it will work correctly anymore. The main problem is that the partial movie files now have different names (previously they were ordered but now they have their has in their names) Cc @ManimCommunity/scene-caching.

In any case, let's discuss how this would look like and let's implement it after the release of v0.1.

**Comment by huguesdevimeux** [comment]
Hi!
This is typically something that could be achieve in the livestreaming feature. see #441, but it's not the first purpose. 

Otherwise, I think that putting the partial movie files in order as @leotrs did is the probably the best idea. The best is probably to directly use a stream to do that, and that's why I mentionned livestreaming. 

If you have any suggestion, feel free :D

**Comment by yoshiask** [comment]
As useful as a feature like this would be, I don't really see why it has to be specific to Manim. Also, this could be implemented entirely as an add-on, so if users don't want it they don't have to download it.

**Comment by behackl** [comment]
You can also make use of the slideshow creation capabilities of Jupyter notebooks when making use of an extension like https://github.com/krassowski/jupyter-manim for a very straightforward way of including/showing videos. (Not sure whether you can manage to show the videos fullscreen then, though -- but it might be worth investigating.)

(jupyter-manim does not support the community version of manim. yet. :-))

**Comment by cobordism** [comment]
> Also, this could be implemented entirely as an add-on

Indeed many things could be... 

...but here is what manim itself should be able to do at a minimum:
1. Create an initial image
2. create one video file per animation
3. save the last frame of each animation
4. Copy all images and videos into one folder with a naming system that makes sense (like: numbered)


From that point on this data can be worked into different presentation softwares. We could talk about an in-browser html-based presentation or compiling a ppt or an applewhatever file. This is the point where add-ons might come in.


Bonus: 
Point 2 but where it is not one video per animation, but where the breaks happen at points that the user specifies in the scene - i.e. allow the user to bundle a few animations into one transition.

**Comment by leotrs** [comment]
> As useful as a feature like this would be, I don't really see why it has to be specific to Manim. Also, this could be implemented entirely as an add-on, so if users don't want it they don't have to download it.

Yes. This is another reason why I haven't PR'd anything.

**Comment by mathmerizing** [comment]
> As useful as a feature like this would be, I don't really see why it has to be specific to Manim. Also, this could be implemented entirely as an add-on, so if users don't want it they don't have to download it.

I mean you are probably right. It would be nice to have access to such a feature one way or the other though. Since it is a useful feature, it should then be transparent for the user, where these add-ons can be found. Especially if they are of interest for many people. Maybe you could include a list of useful add-ons in the sphinx documentation of manim?

**Comment by leotrs** [comment]
I believe an MVP for this is fairly easy to implement. I'm just waiting to close #183 before moving on to this one. If anyone else cares, go ahead!

**Comment by behackl** [comment]
I have a toy implementation that seems pretty close to the feature that has been requested here, see https://gist.github.com/behackl/c92b467aec723cc6f06bd4dd2527c009 -- after adding some sort of (python) webserver as an optional dependency, that approach could probably be implemented as a CLI subcommand (`manim slideshow file.py SomeScene`...).

(Personally, I would find that useful because I'd then use the html-slideshow as a browser source in OBS, which I find a lot more comfortable than including a video.)

**Comment by behackl** [comment]
Closing this since there is a plugin, https://github.com/galatolofederico/manim-presentation, which does more or less what is discussed here.
