### ISSUE TITLE
Render Latex without spaces between the segments

### ISSUE THREAD

**Issue by kolibril13** [ManimCommunity/manim#566]
```py
class Example1LaTeX(Scene):
    def construct(self):
        tex = Tex(r'$\xrightarrow{Hello}$ \LaTeX').scale(3)
        self.add(tex)
```
this example produces the following output:
![image](https://user-images.githubusercontent.com/44469195/96361154-9bc77600-1123-11eb-8ffa-c5628e386072.png)
Note that the arrow is not completely continuous, but has some black lines in between.
I think it would be nice when there would be a solution to print it continiously

**Comment by kolibril13** [comment]
Same e.g. here:

```python
class ABC(Scene):
    def construct(self):
        text = MathTex(r" S_1(",r"t",r")= R \left( \begin{array}{c} "
                                     r"cos(\omega t) "
                                     r"\\ sin(\omega t)"
                                     r"\\ bt \end{array} \right)")
        self.add(text)
        self.wait(1)
```
![ABC](https://user-images.githubusercontent.com/44469195/96361306-d847a180-1124-11eb-8e4b-875bd15c5e1f.png)

**Comment by cobordism** [comment]
ugh! 
That's not good at all.

Is this also in the SVG images? Or does it only show up in manim?

**Comment by kolibril13** [comment]
Screenshot of the svg, that looks good:
![ccd](https://user-images.githubusercontent.com/44469195/96447352-0e168400-1212-11eb-9047-69d466dc9edb.png)

**Comment by kolibril13** [comment]
I could solve it! :)
See #570
