### ISSUE TITLE
Further examples for the documentation

### ISSUE THREAD

**Issue by kolibril13** [ManimCommunity/manim#591]
This issue can be used to get track of the current tasks of the documentation (ping to @ManimCommunity/docs )
Please edit this first message of the thread so it stays up to date. As soon as one point is done, please ~cross out~ that point.

## Reference
Note: There is really a LOT more, these three ones are only a starting point.

* Image for NumberLine
* Image for FunctionGraph
* Image for Brace

## Examples
* 10 most common shapes in "Shapes and Positions"
* Image: How to use arrow vectors
* Image: How to use curved arrows
* Image: How to set fonts
* Image: How to add Bezier Curves
* Image: How to use text to annotate things
* Image: Show how to label specific variables in certain colours and their limitations (e.g. that it was not possible to colour variables that are written in a tex vector (note from @kolibril13 ))
* Video: Sort the updater Section
* Image of CodeMobject
## Further things
* ~~At one point in future, import statements should be explicitly visible in the example gallery section.~~ #593 
* ~~merge this wiki page: https://github.com/ManimCommunity/manim/wiki/Guide-to-contribute-examples-to-docs into the docs here: https://manimce.readthedocs.io/en/latest/contributing.html#further-useful-guidelines and then delete the wiki page~~ #594

**Comment by behackl** [comment]
Let's make this issue a bit more atomic and factor out the last two points mentioned under "Further things".

**Comment by leotrs** [comment]
I'm trying to hunt for guidelines to determine what goes in gallery/reference/tutorials. 

What do y'all think about "If this piece of documentation answers a "how" question, then it goes in the reference"?  On the other hand, if the purpose of a piece of documentation is to illustrate a complicated/advanced/involved/neat feature, then it goes in the examples gallery. For example:

- if a piece of documentation contains a scene that illustrates *how to set fonts*, it goes in the reference.
- if a piece of documentation contains a scene that illustrates *the usage of many fonts in the same scene, in conjunction with other features such as changing color or animating text*, then it goes in the gallery. 

Comments?

**Comment by behackl** [comment]
I like the direction of this suggestion! I think the suggestion that @cobordism made in #595 also fits very well: the example section should be "close to human", while the examples in the reference section can be "close to code" (for the illustration of how to use a single given function/class/keyword/ ...). I don't think that there should be "large" examples in the reference manual, they should all rather be short and sweet.

This holds in particular for the docstrings of classes and methods. I'd like to see better structured explanations/introductions in the module docstrings, though -- this is also why I opened #595: structured introductions like https://manimce.readthedocs.io/en/stable/examples/tex.html should not be in the example gallery. (But I think they fit very well for the module docstring.)

**Comment by leotrs** [comment]
Ok, so.

* Reference: close to code, each example illustrates a single method/keyword. Stand alone examples.
* Gallery: close to human, little/no narrative, Stand alone examples. Each example illustrates more than one feature or class. (Note I'm using "feature" to mean "more than a single method/keyword". E.g being able to change latex fonts is a feature, but the actual keyword argument used to do so is not.) 
* Tutorials: **closer** to human, mostly narrative. Examples build upon each other (not necessarily stand-alone).
* ** Module docstring: ???**

**Comment by behackl** [comment]
> * Gallery: close to human, little/no narrative, Stand alone examples. Each example illustrates more than one feature or class. (Note I'm using "feature" to mean "more than a single method/keyword". E.g being able to change latex fonts is a feature, but the actual keyword argument used to do so is not.)

While I don't think that making our videos the size of thumbnails, we could draw some inspiration from https://matplotlib.org/3.1.1/gallery/index.html

> * ** Module docstring: ???**

I'd see module docstrings as semi-structured introductions/explanations of what can be done with a module. Like the LaTeX section in https://manimce.readthedocs.io/en/stable/examples/tex.html#latex does for `manim.mobject.svg.tex_mobject`. The module docstring renders into https://manimce.readthedocs.io/en/stable/reference/manim.mobject.svg.tex_mobject.html#module-manim.mobject.svg.tex_mobject (and currently only consists of "Mobjects representing text rendered using LaTeX.", which is not particularly helpful.)

See also https://matplotlib.org/3.1.1/api/transformations.html or https://doc.sagemath.org/html/en/reference/constants/sage/symbolic/constants.html for an idea of what I am aiming for.

**Comment by leotrs** [comment]
These are good examples. I'm just having trouble condensing them into a few succinct keywords/guidelines, like I did for the others :thinking:

**Comment by behackl** [comment]
> These are good examples. I'm just having trouble condensing them into a few succinct keywords/guidelines, like I did for the others

I think that something like "Overview over functionalities of an entire module; narrative is welcome but not required" could work. :-)

**Comment by kolibril13** [comment]
Just as a collection of what still could come into the docs:
```python
class MoveAlongPath1(Scene):
    def construct(self):
        circle = Circle(radius=4)
        square = Square()
        square.move_to(2 * RIGHT)
        self.add(square)
        self.add(circle)
        self.play(MoveAlongPath(square, circle), run_time=5.0)
        self.play(MoveAlongPath(square, circle))
```

```python
class Grid(Scene):
    """
    Manim uses a grid to place elements. At the center of the image is the origin, coordinate (0, 0, 0).
    This example demonstrates the size of the grid.
    """

    def construct(self):
        for x in range(-7, 8):
            for y in range(-5, 6):
                annotation = TexMobject(f'P({x}, {y}, 0)', height=1.5, fill_opacity=.5)
                self.add(annotation)
                dot = Dot(point=(x, y, 0))
                self.add(dot)
                self.wait(.1)
                self.remove(annotation)
```

```python
class MyDotGrid(VMobject):
    def __init__(self):
        VMobject.__init__(self)
        dot1 = Dot(fill_color=GREEN).shift(LEFT)
        dot2 = Dot(fill_color=BLUE)
        dot3 = Dot(fill_color=RED).shift(RIGHT)
        self.dotgrid = VGroup(dot1, dot2, dot3)
        self.add(self.dotgrid)

    def update_dot(self):
        self.dotgrid.become(self.dotgrid.shift(UP))


class ExampleScene(Scene):
    def construct(self):
        dot = MyDotGrid()
        dot2 = MyDotGrid()
        dot2.update_dot()
        self.add(dot)
        self.wait(1)
        self.play(Transform(dot, dot2), rate_func=linear)
        self.wait(1)
```

**Comment by leotrs** [comment]
What is the status of this after #687 has been merged?
