### ISSUE TITLE
New and smaller frame for reference examples?

### ISSUE THREAD

**Issue by kolibril13** [ManimCommunity/manim#592]
As the examples in the reference have the purpose of only showing minimal functionality, I think the size of the images could get reduced.
Advantages:
* Improves the readability of the reference page as the content is tighter
* Faster building of the docs and faster loading of the reference page.

Disadvantage:
* One more thing to implement and maintain.
* The user won't get the exact same output when s/he runs the example. (However, as the reference is meant to be for people only looking up things, thats not a big contra. )
Here is a screenshot of what I mean:
![bitmap](https://user-images.githubusercontent.com/44469195/96858949-33e59800-1461-11eb-9ade-ce7215301a2c.png)
@ManimCommunity/docs : What do you think?

**Comment by behackl** [comment]
> Improves the readability of the reference page as the content is tighter

I've been thinking about this as well. We could make these elements a bit more interactive as well; say, we could have the videos in a collapsed state and add a button that has to be clicked in order for the video to show.

At the same time, I kind of like to see what an example will look like at once; I am undecided.

> Faster building of the docs and faster loading of the reference page.

Reducing the size the image is displayed in is possible without changing the resolution it is rendered in -- and I might be wrong, but I don't think that there will be a big performance increase (if at all!) if we decrease the output resolution.

I think I've tried this at some point locally and could not observe a notable difference in the documentation build time.

**Comment by leotrs** [comment]
I am torn here. In principle, I don't think there's anything really wrong with having a lot of whitespace. OTOH, having smaller frames would speed up the docs build.

**Comment by leotrs** [comment]
I count two undecideds and one in favor. I believe this is the entirety of the current docs team right here.

I vote we close this for lack of consensus for now and move one (unless anyone wants to add anything?)
