### ISSUE TITLE
Add import statements to examples in documentation

### ISSUE THREAD

**Issue by behackl** [ManimCommunity/manim#593]
See title.

The examples in the documentation should also include the `from manim import *` at the very least, and actually we could provide best-practice examples where we dont do a *-import, but rather import classes/functions separately.

This can of course be an iterative process: start with adding `from manim import *` first, and become more specific later.

**Comment by kolibril13** [comment]
In my opinion, the import statement should only be present in the example gallery, I think the reference example do not need it.
Do you agree?
Just a reference to an issue where this was discussed before: https://github.com/ManimCommunity/manim/issues/454

**Comment by behackl** [comment]
Hmm.

I would like it, if users could take any rendered example in our documentation, and copy/paste the code without modification so that they get the same result. That probably rather speaks for adding them everywhere, but I am not fully decided about it.

**Comment by leotrs** [comment]
Agree with Ben.

I see no argument in favor of not having the importa statements, other than
gaining 1-2 lines per example. I think having complete examples is more
important than saving up a bit of space.

**Comment by kolibril13** [comment]
ok, then we can do it with import statements everywhere.
