### ISSUE TITLE
Merge the wiki entry on contributing examples to the documentation with the contribution guide in the documentation

### ISSUE THREAD

**Issue by behackl** [ManimCommunity/manim#594]
- [ ] Merge this wiki page: https://github.com/ManimCommunity/manim/wiki/Guide-to-contribute-examples-to-docs into the docs here: https://manimce.readthedocs.io/en/latest/contributing.html#further-useful-guidelines 
- [ ] and then delete the wiki page

**Comment by jsonvillanueva** [comment]
Closing in favor of #1373 and to bump this as a good first issue
