### ISSUE TITLE
Example Gallery: Text and LaTeX --> Reference manual

### ISSUE THREAD

**Issue by behackl** [ManimCommunity/manim#595]
See https://manimce.readthedocs.io/en/latest/examples/tex.html, this page currently contains much more than just a gallery of examples.

Guided explanations on how to use `Tex` and `Text`, respectively, should be located in the reference manual (I'd suggest the module docstrings of `tex_mobject.py` and `text_mobject.py`).

The example gallery should link prominently (details not fully clear yet, see #448) to the module documentation. As a first triage, this could be done with a SEEALSO-block.

**Comment by leotrs** [comment]
I'm trying to hunt for guidelines that help us define what goes in the gallery/reference/tutorials.

What do y'all think about "anything that has a narrative does not belong in the examples gallery".?

**Comment by cobordism** [comment]
Perhaps the reference section should be terse and systematic - have one example per keyword argument, method, or flag - while the examples section could combine more attributes as they might be used in the wild -eg create a text, scale it, move it, change its colour, transform it to another text...

It's tricky. What I mean is that the reference section should be closer to the code and the examples section should be closer to the human. 
Reference is encyclopedic. While examples and tutorials have a narrative.

**Comment by behackl** [comment]
Let's keep this discussion in one place: #591
