### ISSUE TITLE
Make `Code` Mobject  accept strings

### ISSUE THREAD

**Issue by kolibril13** [ManimCommunity/manim#602]
It would be nice to have a script like this working:
```py
class ABC(Scene):
    def construct(self):
        code ="""
            import matplotlib.pyplot as plt
            import numpy as np
            """
        c=Code(code_content=code)
        self.add(c)
````
therefore codemobject.py should be modified a bit, I thought of something like this:
```py
 def __init__(self, file_name=None, code_content= None, **kwargs):
        if code_content != None:
            f = open("temp_code.py", "w")
            f.write(code_content)
            f.close()
            file_name = "temp_code.py"
        VGroup.__init__(self, **kwargs)
```
This works, but it pretty rudimentary, If someone is interested, please feel free to tinker with this :)

**Comment by huguesdevimeux** [comment]
I'm going to work on this

**Comment by kolibril13** [comment]
Any updates on this?

**Comment by huguesdevimeux** [comment]
woops. Totally forgot. 
So, given the circonstances, I won't be able to work on this. Sorry, 100% my fault, I shouldn't have commited.

**Comment by PradipNichite** [comment]
Hi @kolibril13, is there anyone working on it? I would like to work on it.

**Comment by naveen521kk** [comment]
This was done by #948 so closing it.
