### ISSUE TITLE
Factor between stroke width and differences in coordinates

### ISSUE THREAD

**Issue by ponmike92** [ManimCommunity/manim#606]
Let's say I want to make thick line and show it's width by another line.
I found FACTOR between stroke_width and difference in coordinates.
It is 1 / 100. It can be illustrated by this code.

```python
from manim import *

class ShowStrokeWidth(Scene):
    def construct(self):

        width = 50
        # stroke width to dist factor
        FACTOR = 0.01
        lower_edge = np.array([0, -width / 2 * FACTOR, 0])
        upper_edge = np.array([0, width / 2 * FACTOR, 0])

        line = Line(stroke_width = width, stroke_color = RED)
        width_line = Line(start = lower_edge, end = upper_edge)

        self.play(FadeIn(line), FadeIn(width_line))
```

I can't find any mentions of this factor in VMobject class. Any suggestions? 
Anyway, won't it be easier to remove this factor? so code could be..

```python
from manim import *

class ShowStrokeWidth(Scene):
    def construct(self):

        width = 50
        lower_edge = np.array([0, -width / 2, 0])
        upper_edge = np.array([0, width / 2, 0])

        line = Line(stroke_width = width, stroke_color = RED)
        width_line = Line(start = lower_edge, end = upper_edge)

        self.play(FadeIn(line), FadeIn(width_line))
```

**Comment by leotrs** [comment]
Hello @ponmike92 , thanks for reporting this.

If I understand correctly, you are bringing up the fact that the width of a line is given in different units the length. And you have found out that one is 1/100th of the other. Is this correct?

If this is indeed what you are bringing up, I don't particularly have a problem with it being this way, though I agree this should be documented somewhere. Possibly in the class docstring of `Line`. cc @ManimCommunity/docs 

This also has is related to #530

**Comment by ponmike92** [comment]
Hi @leotrs, yes it is correct. Furthermore, it relates to any object for which we can set stroke width. (Arc for example)

Thank you for #530! I've read this issue and found that not only me forced with different length units. It is better to relate this issue to #530.

**Comment by leotrs** [comment]
Yeah, in that case, we could add something like `WidthUnit()` once #530 has seen more progress :) cc @jvdoorn

**Comment by leotrs** [comment]
Depends on #530

**Comment by MrDiver** [comment]
Stale
