### ISSUE TITLE
Use Pipfile instead of requirements.txt

### ISSUE THREAD

**Issue by safinsingh** [ManimCommunity/manim#61]
We should take advantage of using the new pipfile standard to manage python dependencies. This is also able to install `.whl` files off the internet, which eliminates the need for any external installation outside of Python itself. However, this requires pipenv, which may be hard to use for newcomers. Any thoughts?

**Comment by naveen521kk** [comment]
I think it is better to use [Python Poetry](https://python-poetry.org/) which AFAIK is beginner friendly and has similar features as pipenv.

**Comment by leotrs** [comment]
@safinsingh could you describe a) which files would be changed or deleted, and b) what would be the installation steps for a newcomer?

**Comment by safinsingh** [comment]
@leotrs Essentially, the `requirements.txt` file would be the only one to go, and it would be replaced with a `Pipfile`, which contains TOML for packages to be installed and allows you to select an external source. The installation instructions would be altered to show how to create a `pipenv` and execute the `Pipfile`.

**Comment by leotrs** [comment]
So this would require all users to create a virtual environment? Not sure how I feel about that...

**Comment by safinsingh** [comment]
Yeah, it was just an idea; I wanted to hear your guys' opinion on it.

**Comment by XorUnison** [comment]
I mean at some point we want to converge on some proper package management, whether that's standard with better install routines, poetry or venvs with pipfiles.

My biggest beef with venvs is actually cairo though, so...
If we can concoct such a mythical pipfile and get it to work with all those things (in all these OSes, mind you), such that we can breakdown the installation process into something like this:
1. Set up venv. That is with simple instructions **quickly** set up a venv.
2. Clone/Download the Repo into the venv
3. Run pipfile
4. Profit

I'm all for that. The question is, can it actually be done that easy?
Or are there going to be some rotten rat tails somewhere like having to customize the venv to the os, having to figure out this and that argument by yourself, having to customize the pipfile before install etc.
Also just being able to grab a file off of the internet isn't necessarily the holy grail yet. Can we get it to persistently grab the right cairo without user intervention?

**Comment by eulertour** [comment]
A few thoughts:
* Poetry looks cool, but the number of bugs on the repo gives me pause
* pipenv + pipfile don't seem to require users to do anything differently, but the developers will have to learn pipenv. From what I've seen of it I think it would be worth it, but we don't have to make the switch now.
* I don't know of any pure python solution to handle non-python dependencies like latex and ffmpeg. What we've been doing so far by just telling people to download them somehow has worked okayish.

**Comment by leotrs** [comment]
Did we already move to poetry? If so, let's close this. If not, what's holding us up?

**Comment by naveen521kk** [comment]
Still, PR #165 has not been merged. Some work need to be done.

**Comment by naveen521kk** [comment]
Closing this issue is correct I think as we have poetry now.
