### ISSUE TITLE
 [BUG-General]  Code mobject colors are broken 

### ISSUE THREAD

**Issue by huguesdevimeux** [ManimCommunity/manim#625]
See the picture : 
![image](https://user-images.githubusercontent.com/36239975/97277574-ec805280-1838-11eb-97de-7074e2e75925.png)
As you can see, it does not look good. 

**To Reproduce**
code : 
```python
class Test(Scene):
    def construct(self):
            listing = Code(
                r"/path/to/helloworld.cpp",
                )
            self.play(ShowCreation(listing))
 ```
helloworld.cpp : 
```cpp
#include <iostream>

int main() {
    std::cout << "Hello World!";
    return 0;
}
```

This is just for myself and to eventually know if someone else has encountered the same issues.
I'm currently working on a fix and a small refactor of codeMobbject.

**Comment by leotrs** [comment]
> I'm currently working on a fix and a small refactor of codeMobbject.

This is great news, as CodeMobject needs a lot of work..

**Comment by behackl** [comment]
The issue with this is -- unfortunately -- Pango, and the way it handles spaces.

Simple comparison:

```py
>>> t = Text("from manim import *")
>>> t.original_text, len(t.original_text)
('from manim import *', 19)
>>> len(t.submobjects)
16
>>> t = CairoText("from manim import *")
>>> t.original_text, len(t.original_text)
('from manim import *', 19)
>>> len(t.submobjects)
19
```

CairoText adds invisible Dots as submobjects in the place of whitespace, thus ensuring that the number of submobjects corresponds to the length of the string. Text, i.e., our Pango renderer, does not do that anymore (it has no `gen_chars` method).

I can't decide what behavior makes more sense, we could adapt the outcome either way: if we want to keep the number of submobjects in text the same as the string length, then we change the behavior of Text -- and if we want it to stay as-is (because now it represents the actual number of SVG elements) we need to adapt how `Code` applies the color.

**Comment by leotrs** [comment]
Keeping len(submobjects) == len(string contents) sounds more convenient to me.

**Comment by huguesdevimeux** [comment]
I think we should keep `Text` behavior but change how text is actually colored. 

Colors are currently applied by finding the substrings to color, with a for loop interating through the whole `Paragraph`.

https://github.com/huguesdevimeux/manim/blob/84b3dee8ac447660446e496cd8ff115fe8fa8e98/manim/mobject/svg/code_mobject.py#L271-L303

```python
    def gen_colored_lines(self):
        """Function to generate code.

        Returns
        -------
        :class:`~.Paragraph`
            The generated code according to parameters.
        """
        lines_text = []
        for line_no in range(0, self.code_json.__len__()):
            line_str = ""
            for word_index in range(self.code_json[line_no].__len__()):
                line_str = line_str + self.code_json[line_no][word_index][0]
            lines_text.append(self.tab_spaces[line_no] * "\t" + line_str)
        code = Paragraph(
            *[i for i in lines_text],
            line_spacing=self.line_spacing,
            tab_width=self.tab_width,
            font=self.font,
            stroke_width=self.stroke_width
        ).scale(self.scale_factor)
        for line_no in range(code.__len__()): <------ HERE ------------------
            line = code.chars[line_no]
            line_char_index = self.tab_spaces[line_no]
            for word_index in range(self.code_json[line_no].__len__()):
                print(self.code_json[line_no])
                line[
                    line_char_index : line_char_index
                    + self.code_json[line_no][word_index][0].__len__()
                ].set_color(self.code_json[line_no][word_index][1])
                line_char_index += self.code_json[line_no][word_index][0].__len__()
        return code

```

My idea was to change this, and to use color feature of `Text` instead. Text can color some substring in them, which make is perfect for this case. 
By that, I mean to pass some parameters to Paragraph to color come char in certain lines, which are `Text` objects. (IIRC there is no such option in Paragraph yet, but it is definitely something that I'm planning to implement). 
Like this, we would get rid of this thing working with indexes, and it will eventually fix this issue.

**Comment by leotrs** [comment]
Fixing #704 would fix this, correct? If yes, we should close this as duplicate. If no, can someone please clarify what would be left to do after fixing #704?
