### ISSUE TITLE
Drawing.py and a Sample File Gallery Structure

### ISSUE THREAD

**Issue by jsonvillanueva** [ManimCommunity/manim#628]
Currently [drawing.py](https://github.com/ManimCommunity/manim/blob/master/manim/mobject/svg/drawings.py) contains classes that rely on vectorized images that are NOT provided by default. This requires user to create/find their own vector images in order to use the classes provided within ManimCE.

This issue is to open discussion on two items:
### What should happen to drawing.py (and perhaps other ManimCE py files requiring external files) that are protected under the MIT license? Options I see are:

1. Provide the required svg images under a default assets directory.
2. Remove the objects within drawings.py that rely on external files (Lightbulb, Guitar, AoPSLogo, Headphones, SpeechBubble, etc...) and keep those that don't (Laptop, Clock, etc...).
3. Like option 2, but add in a couple minimal files that are used in example_scenes/basic.py to demonstrate how to use .svg/.png/.mp3 files in your own projects.
4. Remove it all.

### Should ManimCE provide a Sample File Gallery Structure (and if so, should it contain sample audio/images)? Options I see are:

1. Provide a structure, minimal content for example_scenes/basic.py (add .gitignore to allow people to use this structure and not commit to this repo).
2. Provide a structure, no content (add .gitignore).
3. Neither, this is more of an add-on/plugin.

**Comment by jsonvillanueva** [comment]
There's definitely more possibilities than those I listed, please add your own thoughts on the matter.

I favor options 3 and 1, respectively. I believe option 3 removes many of the classes that are too specific (like BitcoinLogo), but 1  or 2 files for SVGMobject/ImageMobject/AudioSegment can shows users how they can create their own specific classes. Eventually though the ones they create should be considered add-ons/plugins and not be included in drawings.py/ core ManimCE.

Meanwhile, option 1 gives a basic file structure for storing content, so users have a default place they can put their 3rd party files, and just enough files from core ManimCE to run some example_scenes/learn to use ManimCE. Maybe use the ManimCELogo for both SVGMobject/ImageMobject and a sine wave for a minimal gallery?

**Comment by leotrs** [comment]
Some loose thoughts:

* I don't understand what you mean by "provide a structure".
* I am against shipping empty directories ("provide a structure, not content").
* I'd be happy to see manim CE provide a few basic shapes that users can make use of - especially if they are related to mathematics.
* Not sure why we need files AND classes. (I have never really even read drawings.py - don't know how it works)
* If we provide some files or classes, I'd be in favor of seeing that as an add-on

**Comment by jsonvillanueva** [comment]
>     * I don't understand what you mean by "provide a structure".
Sorry, by "structure" I meant a folder/directory structure as Manim looks in `./*, ./assets/*, and ./assets/svg_images/*` for vector images specifically (assuming media_dir isn't configured). 
>     * I am against shipping empty directories ("provide a structure, not content").

Same.

>     * Not sure why we need files AND classes. (I have never really even read drawings.py - don't know how it works)

You're right, we don't need both. It would be enough to just do `SVGMobject("filename")` in a sample scene to demonstrate its use. Although with a class, you could do some neat things under the hood like accessing the submobjects, changing colors, adding stuff to the config, all of which could function as a more advanced tutorial.

>     * If we provide some files or classes, I'd be in favor of seeing that as an add-on

Where does this add-on exist if ManimCE provides the file? Is it in a separate project from ManimCE?

**Comment by jsonvillanueva** [comment]
#665 Drawing.py is now irrelevant, and a sample file gallery structure IMO would fall under a plugin/addon #42.

Closing this issue as it is more of something to be provided outside of core manim perhaps installable via pip. Will try to reference any such future plugin in this issue when the time comes.
