### ISSUE TITLE
Remove the --background_opacity flag

### ISSUE THREAD

**Issue by leotrs** [ManimCommunity/manim#629]
For most users, I can see two possible values for the background opacity: 1 (fully opaque) or 0 (fully transparent). The former is the default, and the latter can be activated by passing the `-t` flag. Therefore, I see no reason to also support a separate `--background_opacity` flag. If the user *actually* needs a value in between 0 and 1, they can use a .cfg file.

What do you think?

**Comment by kolibril13** [comment]
I think background_opacity is something really specific, that does not need its own flag.
So yes, we can remove it.

**Comment by behackl** [comment]
+1 for removing the CLI flag.
