### ISSUE TITLE
QUESTION : Strange regex in Text

### ISSUE THREAD

**Issue by huguesdevimeux** [ManimCommunity/manim#634]
While digging down in Text mobject, I found this strange regex undocumented : 
https://github.com/huguesdevimeux/manim/blob/84b3dee8ac447660446e496cd8ff115fe8fa8e98/manim/mobject/svg/text_mobject.py#L733-L748

```python
    def find_indexes(self, word: str, text: str):
        """Internally used function. Finds the indexes of ``text`` in ``word``."""


       temp = re.match(r"\[([0-9\-]{0,}):([0-9\-]{0,})\]", word) # <--- HERE <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<


        if temp:
            start = int(temp.group(1)) if temp.group(1) != "" else 0
            end = int(temp.group(2)) if temp.group(2) != "" else len(text)
            start = len(text) + start if start < 0 else start
            end = len(text) + end if end < 0 else end
            return [(start, end)]
        indexes = []
        # if the word in text is not found, then index = -1. 
        index = text.find(word)
        while index != -1:
            indexes.append((index, index + len(word)))
            index = text.find(word, index + len(word))
        return indexes
```

Could someone explain me : what does this regex do ? (here is some explanation https://regex101.com/r/teNNjr/1, but I still don't see what it is supposed to do) 

~ cc @naveen521kk, as git blame said you worked on this ~
EDIT : This has been implemented here https://github.com/3b1b/manim/pull/680 
So, cc @xy-23

**Comment by naveen521kk** [comment]
It parse the user passed colouring options. See https://docs.manim.community/en/latest/reference/manim.mobject.svg.text_mobject.Text.html#manim.mobject.svg.text_mobject.Text for example, the Google coloured one.

**Comment by huguesdevimeux** [comment]
Thanks for the explanation !
