### ISSUE TITLE
 [BUG-General] t2s not working with Text

### ISSUE THREAD

**Issue by naveen521kk** [ManimCommunity/manim#636]
**Describe the bug**
Something because of Pango renderer. `Text2Slant`(t2s) isn't working, which would style individual words or characters before. I happened to notice this in the docs.

**To Reproduce**

<details><summary>Problematic Code</summary>

```py
class TextItalicAndBoldExample(Scene):
    def construct(self):
        text0 = Text('Hello world', slant=ITALIC)
        text1 = Text('Hello world', t2s={'world':ITALIC})
        text2 = Text('Hello world', weight=BOLD)
        text3 = Text('Hello world', t2w={'world':BOLD})
        self.add(text0,text1, text2,text3)
        for i,mobj in enumerate(self.mobjects):
            mobj.shift(DOWN*(i-1))
```

</details>
It produces output like 

![pango-text-error](https://docs.manim.community/en/latest/_images/TextItalicAndBoldExample-1.png)

where the `world` is missing in line 2 and 4.

**Expected behavior**
Full `Hello World` should be shown in all four lines.

**Output Media Files**

<details><summary>Images/GIFs</summary>

![pango-text-error](https://docs.manim.community/en/latest/_images/TextItalicAndBoldExample-1.png)

</details>

**System Specifications**

<details><summary>System Details</summary>
Readthedocs build
</details>

<details>
<summary>Latex details</summary>
Readthedocs build
</details>

**Comment by huguesdevimeux** [comment]
Follows #673 

for the record : 
If a text has different style among it, pangoText will cut it into several part, each part corresponding to a style. 
Next, pango places the different parts, in theory side to side, but fails here for some reasons. 
So, I think the issue is here : 
https://github.com/huguesdevimeux/manim/blob/d668fc1eda19bce97e9cfda522717496d00f03ae/manim/mobject/svg/text_mobject.py#L917-L923

```python
            context.move_to(
                START_X + offset_x, START_Y + line_spacing * setting.line_num
            )
            layout.set_text(text)
            logger.debug(f"Setting Text {text}")
            pangocairocffi.show_layout(context, layout)
            offset_x += layout.get_extents()[0].x # <------------- HERE 
```
`offset_x` is set to the size of the Pango object, but exprimed in pango pixel units, not in manim ones. Thus, text is considerably shifted to the right. 
Changing offset_x to be incremented to 80 (arbitrary value) instead of layout.get_extents()[0].x seems to confirm this : 
![image](https://user-images.githubusercontent.com/36239975/97980278-d04c5a80-1dd0-11eb-861c-14073576c935.png)

**Comment by naveen521kk** [comment]
Simply converting from PangoUnit would be simple I think. https://pangocffi.readthedocs.io/en/latest/modules.html?highlight=pango_units_from#pangocffi.units_from_double

Also, what values does `layout.get_extents()[0].x` get? In above example?

**Comment by huguesdevimeux** [comment]
Adding print `print(layout.get_extents()[0].x)` at the above example, in l. 924 shows : 
```
393
747
```

**Comment by huguesdevimeux** [comment]
On second thought ( I didn't investigate further) I don't think it's related to Manim pixel units in any way, as offset_x is only used to position things within the Text SVG, before it is added to the scene. 

So, it's just offset_x that takes a wrong value for some reason.

**Comment by huguesdevimeux** [comment]
And, I was digging into Pango docs and was wondering, is there a particular reason you split the text with different styles into several svg ? Isn't possible to do it only in a whole one SVG with pango ?

**Comment by naveen521kk** [comment]
Hmm, it is as a whole SVG as far as I know. Only that, Pango is called multiple times to draw on Cairo context.

**Comment by huguesdevimeux** [comment]
Yes, this was my question. Why is pango called multiple times?

**Comment by naveen521kk** [comment]
This is the problem IMO. I think it would be better to let pango do its work and lets not make it do like it. I think there should be a way where pango does it. I find markups (something like html syntax more helpful), so we should allow pass those markups also. I will look into this soon, if i get any time.

**Comment by huguesdevimeux** [comment]
I think it's the best solution. 

It would shorten Text source code so much!
