### ISSUE TITLE
Support conda install

### ISSUE THREAD

**Issue by leotrs** [ManimCommunity/manim#637]
Someone on discord was just trying to do `conda install manimce`, with no success. I was under the impression that pushing to pypi would be enough for this to work?

**Comment by qorrect** [comment]
No they have their own repos , https://conda-forge.org/#add_recipe .  Personally I think pypi would be enough for anyone using the package.

**Comment by leotrs** [comment]
I don't understand. You say that a package published in pypi cannot be installed with conda. But you also say that we shouldn't publish on conda and that pypi is enough.

How can pypi be enough if conda users cannot access it? Am I missing anything?

**Comment by qorrect** [comment]
pypi and conda are not mutually exclusive, people often mix both package managers.  But totally up to you.

**Comment by leotrs** [comment]
Given that there has been only one instance of this problem, I think this has very low priority. Let's revisit if more people have this problem.
