### ISSUE TITLE
y axis label misplacement in certain cases

### ISSUE THREAD

**Issue by PhilippImhof** [ManimCommunity/manim#663]
**Describe the bug**

While creating a test for #661 I realized that the y axis label was sometimes misplaced, e.g. when there is "not enough space" above or below the axis.

**To Reproduce**

```py
from manim import *

class Axes(GraphScene):
    CONFIG = {
        "x_min": -5,
        "x_max": 5,
        "y_min": -3,
        "y_max": 3,
        "x_axis_config": {
            "add_start": .5,
            "add_end": .5,
            "include_tip": True,
        },
        "y_axis_config": {
            "add_start": 0.25,
            "add_end": 0.5,
            "include_tip": True,
        },
        "x_axis_visibility": True,
        "y_axis_visibility": True,
        "y_label_position": UP,
        "x_label_position": RIGHT,
        "graph_origin": ORIGIN,
        "axes_color": WHITE,
    }

    def construct(self):
        self.setup_axes(animate=True)
        l=Line(start=self.y_axis.get_corner(DOWN)+LEFT,end=self.y_axis.get_corner(UP)+LEFT,color=RED)
        self.add(l);
        txt=MathTex("y",color=RED);
        txt.next_to(self.y_axis.get_corner(UP),UP,buff=SMALL_BUFF)
        self.add(txt);
        self.wait()
```

**Expected behavior**

Placement of the label is done in lines 160-170 of `manim/scene/graph_scene.py`:

```py
        if self.y_axis_label:
            y_label = Tex(self.y_axis_label)
            y_label.next_to(
                y_axis.get_corner(self.y_label_position),
                self.y_label_position,
                buff=SMALL_BUFF,
                aligned_edge=-self.y_label_position,
            )
            y_label.shift_onto_screen()
            y_axis.add(y_label)
            self.y_axis_label_mob = y_label
```

The red line shows that `get_corner` works as expected. The red label shows that `next_to` would work as expected even when we are near the upper limit of the viewport. Removing the part `aligned_edge=-self.y_label_position` does not change the behavior or makes it even worse.

**Output Media Files**

![image](https://user-images.githubusercontent.com/52650214/97814841-6a55bb00-1c8a-11eb-91bf-6d0c7c54c5cd.png)

**Comment by leotrs** [comment]
Thanks for reporting. I *think* this is something we should fix. However, I think this is dangerously close to becoming a typesetting problem. As of right now, manim is not a typesetting or a plotting library, so we should be careful not to open a can of worms unless we are sure we want to go down some rabbit holes that are very very deep.

**Comment by PhilippImhof** [comment]
I have just found the culprit: `y_label.shift_onto_screen()` shifts the label down, because it is less than `DEFAULT_MOBJECT_TO_EDGE_BUFFER` away from the edges. This approach is fine as long as the label is not directly above/below the axis (or left/right for the x axis).

IMHO the best option to fix it is to check whether the label and the axis overlap after `shift_onto_screen`. If this is the case, we push the label to the left (for y) or the top (for x).

**Comment by PhilippImhof** [comment]
> Again, we should fix this one, but we should also ask the user to take care of where they place their mobjects on the scene instead of doing it ourselves.

Reconsidering this, it might obviously be easier for us. But this means that if the user wants to place the label above the axis, they will just see the label and the axis overlap. Then they will have to change the placement to `UP+LEFT` or `UP+RIGHT`. As a consequence, that should be documented somewhere.

I wonder if it wouldn't be a better error to simply not `shift_onto_screen` so the user sees their label is placed where they wanted, but does not fit on the screen. It then becomes obvious that they have to choose another position. The current behavior, although well intended, makes it look as if the positioning option was not considered.

**Comment by EnergyWaves** [comment]
Hi! I have similar issue. When I shift the axes up, the labels are not in a correct place, even though there is a planty of space after scalling the scene. It is definetely is a unexpected behaviour.
```
class Scene_one(MovingCameraScene):
    def construct(self):
        self.play(self.camera.frame.animate.scale(2))
        ax = Axes(x_range=(0, 8), y_range=(0, 5), x_length=8, y_length=5).shift(UP*3)
        y_label = ax.get_y_axis_label(
            Tex("$y$-values").scale(0.65),
            edge=UR,
            direction=UR,
            buff=0.3,
        )
        self.add(ax, y_label)
        self.wait()
```
and it looks like this:

![axes label](https://user-images.githubusercontent.com/107758695/174444367-1ecd658f-5af8-42f8-9223-7ecc4cf1b97e.jpg)

**Comment by uwezi** [comment]
> Hi! I have similar issue. When I shift the axes up, the labels are not in a correct place, even though there is a planty of space after scalling the scene. It is definetely is a unexpected behaviour.

While I can reproduce the problem in the current version of Manim 0.18.1, I don't think that this is related to the old issue from 2020, and thus you should have opened a new issue.

However, I myself don't use the predefined labeling functions, because I find that a simple placement like in the following code provides me with much more flexibility:
```py
class Scene_one(MovingCameraScene):
    def construct(self):
        self.play(self.camera.frame.animate.scale(2))
        ax = Axes(x_range=(0, 8), y_range=(0, 5), x_length=8, y_length=5).shift(UP*3)
        y_label = Tex("$y$-values").scale(0.65).next_to(ax.c2p(0,5),UR,buff=0.3)
        self.add(ax, y_label)
        self.wait()
```
![image](https://github.com/user-attachments/assets/e9ad0cb9-3515-4fbd-bf6b-c43349f8b1fc)
