### ISSUE TITLE
CircleIndicate is extremely unpredictable

### ISSUE THREAD

**Issue by leotrs** [ManimCommunity/manim#679]
I was trying to use CircleIndicate for an animation, but I cannot for the life of me figure out how it's supposed to work.

Read the following code and try to predict what each animation will do. Then watch the rendered animation and see if it matches your expectation.

```python
from manim import *

SHIFT = 2.5 * DOWN

class MyScene(Scene):
    def construct(self):
        sq = Square()
        tx = Text('good: circle always yellow').shift(SHIFT)
        self.add(sq, tx)
        self.wait(1)
        self.play(CircleIndicate(sq), run_time=5)

        self.remove(tx)
        tx = Text('bad: circle starts yellow, turns red').shift(SHIFT)
        self.add(tx)
        self.wait(1)
        self.play(CircleIndicate(sq, color=RED), run_time=5)

        self.remove(tx)
        tx = Text('good: circle always red').shift(SHIFT)
        self.add(tx)
        self.wait(1)
        anim = CircleIndicate(sq, color=RED, circle_config={'color': RED})
        self.play(anim, run_time=5)

        self.remove(tx)
        tx = Text('bad: circle starts red, turns yellow').shift(SHIFT)
        self.add(tx)
        self.wait(1)
        anim = CircleIndicate(sq, circle_config={'color': RED})
        self.play(anim, run_time=5)

        self.remove(tx)
        tx = Text('using fill opacity just makes things worse').shift(SHIFT)
        self.add(tx)
        anim = CircleIndicate(sq, circle_config={
            'color': RED, 'fill_color': BLUE, 'fill_opacity': 0.5})
        self.play(anim, run_time=5)
```

![MyScene](https://user-images.githubusercontent.com/1096704/98384076-50660080-201b-11eb-82de-2c8f7aab0969.gif)

**Comment by huguesdevimeux** [comment]
I think it shouldn't too hard to refactor `CircleIndicate`,  it is only a circle well-placed. 

Concerning the fill_opacity, yes it works weirdly but in theory one is not supposed to fill it. I don't think CircleIndicate should accpet as parameter `circle_config`, because by essence it is supposed to be well, just a yellow circle indicating something (although the color can change!)

**Comment by leotrs** [comment]
I agree with both points: we should remove circle_config, and we should make sure it works perfectly when the fill opacity is zero.

Additionally, if we could *also* make it work with fill_opacity > 0 that'd be great.
