### ISSUE TITLE
[BUG-General] Certain combination of values causes AnimationGroup to add all objects at once (or does it? yes it does. or does it?)

### ISSUE THREAD

**Issue by MulleDK19** [ManimCommunity/manim#709]
**Describe the bug**

If AnimationGroup has lag_ratio set exactly to 1, the objects do animate one by one, however, they're all added to the scene at the beginning of the animation.

However, there's more to it than that. I'm not sure of the exact cause, but it's a combination of various things that does it.
For example, if all objects have scale 1, lag_ratio is 1 and run_time is 5, they're all added at once.
However, change one of these values to anything else, and they're not.

Other factors as well. For example, with those values, the bug occurs with --low_quality, but not --medium_quality.

&nbsp;

**To Reproduce**

Render the below scene with these settings
```batch
manim main.py TestScene -c '#111111' --low_quality -p
```

```py
class TestScene(MovingCameraScene):
    def construct(self):
        s = Square()
        c = Circle()
        t = Triangle()
        self.play(
            AnimationGroup(
                Write(s),
                Write(c),
                Write(t),
                lag_ratio=1
            ),
            run_time = 5)
        self.wait()
```

&nbsp;

**Expected behavior**

The square, circle and triangle appear one by one.

&nbsp;

**Additional context**

Furthermore, remove the `-c '#111111'` from the command line, and it also behaves correctly on `--low_quality`
However, on `--medium_quality` it works fine with the `-c '#111111'`

**Comment by behackl** [comment]
Have you tried running manim with the  `--disable_caching` flag?

**Comment by MulleDK19** [comment]
> Have you tried running manim with the `--disable_caching` flag?

Just tried. No difference.

**Comment by leotrs** [comment]
Glad it worked!

In the future, you can delete the cache by using the `--flush_cache` flag.

**Comment by behackl** [comment]
This probably still hints at some underlying issue regarding caching when using `AnimationGroup`; but this would need to be investigated separately.

**Comment by huguesdevimeux** [comment]
Yes, maybe this got closed prematurely. 

Just to be sure, @MulleDK19 Does everything works now?

**Comment by MulleDK19** [comment]
> Yes, maybe this got closed prematurely.
> 
> Just to be sure, @MulleDK19 Does everything works now?

I haven't seen it after removing the cache and all the media.
That's not to say it's not a bug, though. But I have no idea what causes it, other than it must be related to caching.

**Comment by leotrs** [comment]
If we find a way to replicate this, then we should reopen it. If we don't find a way to replicate it, there's no way to fix the bug.
