### ISSUE TITLE
Concurrent ApplyMethod calls fail for Mobject

### ISSUE THREAD

**Issue by Reantric** [ManimCommunity/manim#722]
## Description of bug / unexpected behavior

self.play only works for the last argument of concurrent ApplyMethod calls. 

## Expected behavior

The Mobject in question is supposed to act on all concurrent *ApplyMethod calls but it only works for the last one supplied. 

## How to reproduce the issue

<details><summary>Code for reproducing the problem</summary>

```py
r = Rectangle()
self.play(ShowCreation(r))
self.play(ApplyMethod(r.set_height,6,True),ApplyMethod(r.set_opacity,1),ApplyMethod(r.set_color,RED))
self.wait()
# Only the last call works, none of the other 2 work.
```

</details>

## Additional media files

<details><summary>Images/GIFs</summary>

![Alt Text](https://i.imgur.com/Xypimop.gif)
</details>

## Logs
<details><summary>Terminal output</summary>

```
https://pastebin.com/JFJuJ99s
```

</details>

## System specifications

<details><summary>System Details</summary>

- Windows 10 Build 19041
- RAM: 12 Gb
- Python version (`python/py/python3 --version`): 3.9
- Installed modules (provide output from `pip list`): 
```
Package           Version
----------------- -------
cairocffi         1.2.0
cffi              1.14.3
colorama          0.4.4
colour            0.1.5
commonmark        0.9.1
grpcio            1.33.2
grpcio-tools      1.33.2
manimce           0.1.0
numpy             1.19.3
pangocairocffi    0.3.2
pangocffi         0.6.0
pathtools         0.1.2
Pillow            8.0.1
pip               20.2.4
progressbar       2.5
protobuf          3.13.0
pycairo           1.20.0
pycparser         2.20
pydub             0.24.1
Pygments          2.7.2
rich              9.2.0
scipy             1.5.4
setuptools        50.3.2
six               1.15.0
tqdm              4.51.0
typing-extensions 3.7.4.3
watchdog          0.10.3
```
</details>

<details><summary>LaTeX details</summary>

+ LaTeX distribution (e.g. TeX Live 2020): TeX 3.14159265 (TeX Live 2020/W32TeX)
+ Installed LaTeX packages: manim-latex

</details>

<details><summary>FFMPEG</summary>

Output of `ffmpeg -version`:

```
ffmpeg version 4.3.1 Copyright (c) 2000-2020 the FFmpeg developers
built with gcc 10.2.1 (GCC) 20200726
configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libsrt --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libgsm --enable-librav1e --disable-w32threads --enable-libmfx --enable-ffnvcodec --enable-cuda-llvm --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt --enable-amf
libavutil      56. 51.100 / 56. 51.100
libavcodec     58. 91.100 / 58. 91.100
libavformat    58. 45.100 / 58. 45.100
libavdevice    58. 10.100 / 58. 10.100
libavfilter     7. 85.100 /  7. 85.100
libswscale      5.  7.100 /  5.  7.100
libswresample   3.  7.100 /  3.  7.100
libpostproc    55.  7.100 / 55.  7.100
```
</details>

**Comment by MulleDK19** [comment]
Possibly related to #713

**Comment by leotrs** [comment]
Unfortunately this is not going to work without a _major_ rework of `ApplyMethod`. The way `ApplyMethod(obj.method, args)` works is by first obtaining the _final_ or target object by calling `obj.method(*args)` and then gradually interpolating `obj` into that final/target at each frame.

So each `ApplyMethod` object in your code is interpolating the same object into a different target. But because of the way things are setup, only the last one is shown at each frame.

I believe that the only way of fixing this is by creating a new class `ApplyMethods` that accepts multiple methods at once.

**Comment by Pragyaan-6988** [comment]
I made [these](https://github.com/Pragyaan-6988/ManimCE/commit/0c96215723f9daae2be844c1bba3f5839834fb5f) changes and it works. I haven't tested it enough to conclude it's the solution though. Any thoughts on these changes?
The idea is to generate a new target to the `mobject` only if its attribute `target` is `None` (which means there are no targets generated so far). If `mobject.target` is not `None`, meaning a target was previously set, that target will be used.

**Comment by leotrs** [comment]
@Pragyaan-6988 thanks for the PR! :tada: let's continue conversation there.

**Comment by behackl** [comment]
Chaining methods with `.animate` is the intended way of applying multiple methods. We might be more flexible at some point in the future, but currently the intended solution is good enough.
