### ISSUE TITLE
Confusion between the two manim libraries

### ISSUE THREAD

**Issue by dakyion** [ManimCommunity/manim#728]
## Description of bug / unexpected behavior

When running the following command:
`manim file.py`
There is an exchange of the library used, it should use manimce, but instead of that, it is using the original manim
(I have installed both of them)
the error

>  Media will be written to ./media\. You can change this behavior with the --media_dir flag.
> 
>    There are no scenes inside that module

The solution to this problem was to switch to the calling syntax of the original manim 
`python -m manim file.py`
which have called the manimce version ( sometimes  it works, sometimes it does not!)

## Expected behavior

In the last days, I used to use those syntaxes

- `manim file.py` for manimce
- `python -m manim file.py` for original manim

## Information
The Code editor used is VS code with the terminal inside it .

## Suggestion
I think that renaming the `manim` to `manimce` in the syntax called in the Terminal would solve this confusion for both the system and the developer!
it should be like this:
`manimce file.py`

**Comment by naveen521kk** [comment]
FYI! You can call manim using `manimce` command also.

**Comment by kilacoda** [comment]
> I think that renaming the manim to manimce in the syntax called in the Terminal would solve this confusion for both the system and the developer!
it should be like this:
manimce file.py

You can already do that. Manim creates two entry points (aka terminal commands) on install, namely `manim` and `manimce`.

**Comment by leotrs** [comment]
Thanks @naveen521kk and @kilacoda.

I'm closing this as the suggestion is already implemented. @dakyion please feel free to open new issues if you encounter other problems :slightly_smiling_face:

**Comment by dakyion** [comment]
@leotrs 
Is it implemented in the 0.1.0 release?
Because it is not working for me, should I add something to the PATH manually?

> 'manimce' n’est pas reconnu en tant que commande interne
ou externe, un programme exécutable ou un fichier de commandes.

it says that the term `manimce` is not known as an internal command or external or and an executable file or a command

**Comment by naveen521kk** [comment]
On `v0.1.0`  is was `manimcm`, which was changed to `manimce` in the master branch.

**Comment by leotrs** [comment]
Weird. This is inside VSCode, correct? Can you please try on a standalone terminal, outside VSCode?

**Comment by dakyion** [comment]
> Weird. This is inside VSCode, correct? Can you please try on a standalone terminal, outside VSCode?

@leotrs 
I have tried in both of them, the same error 

> On v0.1.0 is was manimcm, which was changed to manimce in the master branch.

@naveen521kk 
Thanks, that worked for me now!

---
I will wait for the next stable release for the new syntax
Thanks for you all!

**Comment by leotrs** [comment]
Thank you for reporting!
