### ISSUE TITLE
make clean for Makefile in docs broken

### ISSUE THREAD

**Issue by behackl** [ManimCommunity/manim#737]
## Description of bug / unexpected behavior
The command removes content of the directory `../build`.

## Expected behavior
It should remove content of `build`. This is caused by a recent change (#699) of the corresponding paths.

**Comment by MysaaJava** [comment]
Indeed ... I will make a PR to quickly fix this. When i will make a PR for i18n, i will refactor make a bit and add tests for docs build.

**Comment by MysaaJava** [comment]
Well ......... @behackl Isn't it supposed to do that ? Every doc building process is done in the source/ folder, and build files are at ../build, relative to this folder. Do you have files that are not cleared ? Because, on my computer, it seems like everything is done correctly.

**Comment by behackl** [comment]
Let me check again later to make sure, but I think my `build` directory was not emptied when I used it earlier. Will report back.

**Comment by cobordism** [comment]
what about `./source/media`? Should that not be cleared as well? 

On a related note, if you have one version of manim in your local working directory and another version installed, then `make html` will generate a hybrid Frankenstein's Documentation -- namely, Sphinx takes the local directory for the local .rst files, but the module docstrings will be taken from the installed manim version ...

**Comment by behackl** [comment]
> what about `./source/media`? Should that not be cleared as well?
> 
> On a related note, if you have one version of manim in your local working directory and another version installed, then `make html` will generate a hybrid Frankenstein's Documentation -- namely, Sphinx takes the local directory for the local .rst files, but the module docstrings will be taken from the installed manim version ...

I am not sure that there is a way around that -- and I don't think we should start supporting having multiple installations of manim next to each other.

**Comment by cobordism** [comment]
This is not a feature request. All I am saying is that typing `make html` inside a github-checked-out manim/docs directory does _not_ compile docs from within that directory... and that was not clear to me and caused me headaches earlier today.

**Comment by behackl** [comment]
I see. We should probably document it somewhere!

**Comment by MysaaJava** [comment]
I'll see if i can do something about it this week-end. (I'm adding this to my big docs PR todolist ^^)

**Comment by behackl** [comment]
There must have been some other issue with me using the makefile, it does clean the correct directory for me.

Sorry for the noise.
