### ISSUE TITLE
Shapes with cutouts

### ISSUE THREAD

**Issue by XorUnison** [ManimCommunity/manim#739]
Another feature request I'll write down here to take care of eventually myself, probably after `ArcPolygon`. While I was working on the Hadwiger-Nelson problem I created the highly complex class `ExclusionZone`, and while I was worrying that their appearance of a roughly annulus shaped zone with a central cutout wouldn't render nicely, I did in fact find manim to be able to render them perfectly. Using `Write` on these zones causes first the outer boundary to be drawn, then the inner boundary, then the area in between is filled out. A class to basically cut one area out from another bigger would be handy to have, and should only require a miniscule amount of code.

**Comment by leotrs** [comment]
This was merged already, no?

**Comment by behackl** [comment]
Yes: #760
