### ISSUE TITLE
Can't set frame_width / frame_height via .cfg file

### ISSUE THREAD

**Issue by ponmike92** [ManimCommunity/manim#749]
It seems strange but I can't change frame_width or frame_height via .cfg file.
I use the latest version of code from master branch. But it as well the same if I use Manim as lib.

I have this structure:
```
tests/manim.cfg
tests/main.py
```

manim.cfg
```cfg
[CLI]  
background_color = WHITE
frame_width = 2
frame_height = 4
```

main.py
```python
from manim import *

print(config.background_color)
print(config.frame_width)
print(config.frame_height)
```

OUTPUT
```shell
white
14.222222222222221
8.0
```

However, if I change values programmatically, not through .cfg file (if it comes to frame_width or frame_height) manim successfully change these config values as said in documentation.

**Comment by leotrs** [comment]
Hi @ponmike92. Could you please use the rest of the issue tempalte? To be able to help you, we need to know what is the version you are using, as well as how you determined that this didn't work. A code snippet would help a lot. Thanks.

**Comment by ponmike92** [comment]
I have also noticed: 
'frame_x_radius' duplicates behaviour of 'frame_width' 
'frame_y_radius' duplicates behaviour of 'frame_height'

This config options seem to be redundant, aren't they?

**Comment by leotrs** [comment]
Thank you @ponmike92. You are right that the `frame_width` and `frame_height` cannot currently be changed via config file. I am preparing a PR as we speak. Thanks for reporting!

Yes, frame_*_radius is redundant with frame_*. These are kept mostly for backwards compatibility. Perhaps we should deprecate them soon.

**Comment by ponmike92** [comment]
@leotrs no problem

as well as that I noticed that there was these settings in default.cfg file in v0.1.0 of Manim

```
# These override the previous by using -k, --four_k
[fourk_quality]
pixel_height = 2160
pixel_width = 3840
frame_rate = 60

# These override the previous by using -e, --high_quality
[high_quality]
pixel_height = 1440
pixel_width = 2560
frame_rate = 60

# These override the previous by using -m, --medium_quality
[medium_quality]
pixel_height = 720
pixel_width = 1280
frame_rate = 30

# These override the previous by using -l, --low_quality
[low_quality]
pixel_height = 480
pixel_width = 854
frame_rate = 15
```

But in current newest branch these settings were removed. Now I can't figure out how user can override these settings (pixel_height/pixel_width/frame_rate for different qualities) through user-wide or folder-wide .cfg file. Is this feature unavailable anymore?

**Comment by leotrs** [comment]
pixel_height, pixel_width, and frame_rate are still present in the default.cfg file, under the [CLI] section. A user can change them in the same way, by placing them in the [CLI] section of user-wide or folder-wide files.

The sections you point out were not really used for any configuration, but for default values that are used when the *quality flags are present. These are now stored elsewhere.
