### ISSUE TITLE
Document and test the '-' file name command line argument

### ISSUE THREAD

**Issue by leotrs** [ManimCommunity/manim#75]
The `get_module` function in `extract_scene.py` allows the user to input the code for a Scene from stdin, but only when the argument passed as file name is `-`. This should be documented somewhere. At the very least, the `-h` flag should mention this possibility.

**Comment by huguesdevimeux** [comment]
That's weird, but it could be very useful
We should implement that but with a proper new flag

**Comment by leotrs** [comment]
TBH I think that refactoring this into something usable, alongside with the necessary documentation and testing is going to be much more hassle than it's worth. It's unclear to me that the use cases merit the work needed here.

**Comment by leotrs** [comment]
It's been two weeks and I don't hear anyone making arguments in favor of keeping this. If no one speaks up in a few more days, I'll write a PR to remove it.

**Comment by Aathish04** [comment]
> It's been two weeks and I don't hear anyone making arguments in favor of keeping this. If no one speaks up in a few more days, I'll write a PR to remove it.

@leotrs Can we please keep it in? It would make some applications (say, like writing a Discord Manim rendering bot) a lot easier...

**Comment by leotrs** [comment]
You're right in that it'd be nice to have, but you're also right in that it's broken.

For bot/application purposes, it'd be simpler to store the code in a temporary file and then send that to manim, no?

I'm in favor of deleting it.

**Comment by Aathish04** [comment]
> You're right in that it'd be nice to have, but you're also right in that it's broken.
So it actually _is_ broken? No point in keeping it then.

> For bot/application purposes, it'd be simpler to store the code in a temporary file and then send that to manim, no?

Well, that's what my Manim rendering bot currently does, but if this feature worked, it would have made the load on the host a lot less...

> I'm in favor of deleting it.
Agreed. No use in having something that doesn't work.

**Comment by leotrs** [comment]
@ManimCommunity/core anyone against removing this?

**Comment by Aathish04** [comment]
@leotrs I just managed to figure out how it works. 

You need to import the built-in types module in `main.py`
You use this as the input file's name, and then you type in your code as necessary. After that, you type an EOF (which was a ctrl+D for me) and it renders just like any other scene.

It doesn't appear to be buggy or anything like that and it doesn't conflict with any of the other flags as well, and just seems to work. I'm now in favour of keeping this in the codebase.

PR fixing it : https://github.com/ManimCommunity/manim/pull/203

**Comment by leotrs** [comment]
Closed as #203 is a fix.
