### ISSUE TITLE
PangoText should issue a warning if the font is not found

### ISSUE THREAD

**Issue by leotrs** [ManimCommunity/manim#757]
## Description of bug / unexpected behavior
When requesting a font that is not found, `PangoText` just uses the default font without issuing a warning or error.

## Expected behavior
The user should be warned if the font is not found.

## How to reproduce the issue

<details><summary>Code for reproducing the problem</summary>

```py
import manim as mn

class MyScene(mn.Scene):
    def construct(self):
        # note this is from the current master on this date, in which
        # Text is PangoText
        text = mn.Text('foobar', font='dddddd')
        self.add(text)
        self.wait()
```

</details>

## System specifications

<details><summary>System Details</summary>

- Description:	Ubuntu 20.04.1 LTS
- Python 3.8.5

<details><summary>FFMPEG</summary>

Output of `ffmpeg -version`:

```
ffmpeg version 4.2.4-1ubuntu0.1 Copyright (c) 2000-2020 the FFmpeg developers
built with gcc 9 (Ubuntu 9.3.0-10ubuntu2)
configuration: --prefix=/usr --extra-version=1ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
libavutil      56. 31.100 / 56. 31.100
libavcodec     58. 54.100 / 58. 54.100
libavformat    58. 29.100 / 58. 29.100
libavdevice    58.  8.100 / 58.  8.100
libavfilter     7. 57.100 /  7. 57.100
libavresample   4.  0.  0 /  4.  0.  0
libswscale      5.  5.100 /  5.  5.100
libswresample   3.  5.100 /  3.  5.100
libpostproc    55.  5.100 / 55.  5.100
```
</details>

## Additional comments
Forked from #487

**Comment by naveen521kk** [comment]
I get a warning like
![image](https://user-images.githubusercontent.com/49693820/99892689-61f70b80-2c9d-11eb-830a-4cf44fb23162.png)
on windows.

**Comment by leotrs** [comment]
Interesting! I get nothing on Linux, even with `-v DEBUG`.

**Comment by naveen521kk** [comment]
> Interesting! I get nothing on Linux, even with `-v DEBUG`.

That's actually not passed from Manim though. Pango directly issues a waning from its process and that is what displayed there. Maybe try some lower level of terminal (for example cmd in windows).

**Comment by leotrs** [comment]
Well, the purpose of this issue is to make sure that the warning reaches the user regardless of the terminal they are using.

**Comment by naveen521kk** [comment]
> Well, the purpose of this issue is to make sure that the warning reaches the user regardless of the terminal they are using.

I don't think we would be able to do that unless we have access to their C API, or maybe a good wrapper which convert these warning to python's warning.

**Comment by leotrs** [comment]
Yeah I think you are right.

**Comment by naveen521kk** [comment]
See https://github.com/leifgehrmann/pangocffi/issues/26

**Comment by naveen521kk** [comment]
I opened an issue on Pango's repo where when using fontconfig backend this warning gets hidden or gets lost somewhere. While the same when using Win32 backend(the one in windows) this doesn't happen. Maybe let's see what reply we get from them.
https://gitlab.gnome.org/GNOME/pango/-/issues/523

**Comment by naveen521kk** [comment]
Reply from upstream https://gitlab.gnome.org/GNOME/pango/-/issues/523#note_1019006

> I don't think we want to warn about font fallback. It is is a normal phenomenon.
The win32 fontmap only emits this "ugly output" warning when it can't find any matching font. That never happens with fontconfig, due to the way it works. As long as any fonts are installed on your system, we get a font returned (even if it is not a great match).

**Comment by naveen521kk** [comment]
Users can check for the fonts visible for Pango using the new API provided by ManimPango>=0.2.0.
```py
>>> import manimpango
>>> manimpango.list_fonts()
[...]
```
See https://manimpango.readthedocs.io/en/latest/reference/manimpango.list_fonts.html for more information.
