### ISSUE TITLE
Animation of ParametricFunction (related to copying Mobject)

### ISSUE THREAD

**Issue by protonlaser91** [ManimCommunity/manim#761]
## Description of bug / unexpected behavior

Copying a mobject fails when trying to graph a ParametricFunction. 

## Expected behavior

The copying is successful and the ParametricFunction is successfully graphed.

## How to reproduce the issue

<details><summary>Code for reproducing the problem (inside </summary>

```py
Class RandomlyObscureScene(Scene):
     def func(self, t):
        x = 12*t-6
        y = np.sin(x)
        return x*LEFT+y*UP

    def construct(self):
        funk = ParametricFunction(function=self.func,x_min=-3,x_max=3)
        self.play(ShowCreation(funk))
        self.wait()
```

</details>

## Additional media files

<details><summary>Images/GIFs</summary>

</details>

## Logs
<details><summary>Terminal output</summary>

```
https://pastebin.com/FVZTMRZT
```

</details>

## System specifications

<details><summary>System Details</summary>

- OS Win 10
- RAM: 12 GB
- Python version (`python/py/python3 --version`): Python 3.9
- Installed modules (provide output from `pip list`): 
```
Package           Version
----------------- -------
cairocffi         1.2.0
cffi              1.14.3
colorama          0.4.4
colour            0.1.5
commonmark        0.9.1
grpcio            1.33.2
grpcio-tools      1.33.2
manimce           0.1.0
numpy             1.19.3
pangocairocffi    0.3.2
pangocffi         0.6.0
pathtools         0.1.2
Pillow            8.0.1
pip               20.2.4
progressbar       2.5
protobuf          3.13.0
pycairo           1.20.0
pycparser         2.20
pydub             0.24.1
Pygments          2.7.2
rich              9.2.0
scipy             1.5.4
setuptools        50.3.2
six               1.15.0
tqdm              4.51.0
typing-extensions 3.7.4.3
watchdog          0.10.3
```
</details>

<details><summary>LaTeX details</summary>

+ LaTeX distribution (e.g. TeX Live 2020): TeX Live 2020
+ Installed LaTeX packages: manim-latex

</details>

<details><summary>FFMPEG</summary>

Output of `ffmpeg -version`: 

```
ffmpeg version 4.3.1 Copyright (c) 2000-2020 the FFmpeg developers
built with gcc 10.2.1 (GCC) 20200726
configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libsrt --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libgsm --enable-librav1e --disable-w32threads --enable-libmfx --enable-ffnvcodec --enable-cuda-llvm --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt --enable-amf
libavutil      56. 51.100 / 56. 51.100
libavcodec     58. 91.100 / 58. 91.100
libavformat    58. 45.100 / 58. 45.100
libavdevice    58. 10.100 / 58. 10.100
libavfilter     7. 85.100 /  7. 85.100
libswscale      5.  7.100 /  5.  7.100
libswresample   3.  7.100 /  3.  7.100
libpostproc    55.  7.100 / 55.  7.100
```
</details>

## Additional comments
This is related to Mobject.copy() and possibly the lack of a __deepcopy__ magic method.

**Comment by huguesdevimeux** [comment]
Hi, thanks so much for the report. 

I don't see where/how you are trying to copy something. Am i Missing something? 

On another hand, could you please try to run the same scene with `--disable_caching`?

**Comment by protonlaser91** [comment]
No problem! I am not intrinsically trying to copy anything, but I combed through the traceback and found the error to be with the Mobject.copy() method. I tried running the same scene with the flag --disable_caching and the result was not different. Thank you for your help!

**Comment by protonlaser91** [comment]
Ah I figured something out, changing func to a staticmethod without the self parameter fixes the issue. This is very interesting and I'll look into it more.

**Comment by leotrs** [comment]
@protonlaser91 thanks for reporting this.

Mobject defines the `copy()` method, which executes the same code as in your stacktrace: `copy.deepcopy(self)`. There are other parts of the codebase that use this method, so it seems like this is not necessarily the culprit.

Since your `func` does not require access to `self` I suggest defining it outside of the class (not even as a static method of the class). Please let us know if that solves your problem.

**Comment by protonlaser91** [comment]
This does! Thank you.
