### ISSUE TITLE
Revamp GraphScene

### ISSUE THREAD

**Issue by protonlaser91** [ManimCommunity/manim#775]
## Enhancement proposal

In its current state, GraphScene is incredibly obfuscated and difficult to use. It is also out of date. To keep in accordance with conventions, it should be renamed to TwoDScene and its obsolete methods should be recategorized under different classes or removed entirely.

For example, the get_slope_of_tangent method that is currently in GraphScene should be delegated to the ParametricFunction class.
```python
def derivative(self,t,dt=0.01):
    """
       Returns the slope of the tangent line to the plotted curve
       at a particular t-value.

       Parameters
       ----------
       t : int, float
           The t value at which the tangent must touch the curve.

       dt : int, float, optional
           The small change in t with which a small change in the parametric function to get dy/dx
           will be compared in order to obtain the tangent.

       Returns:
       The derivative at that point
    """

    functionAtTimestep = self.evaluate(t+dt)
    functionAtT = self.evaluate(t)
    return (functionAtTimestep[1]-functionAtT[1]) / (functionAtTimestep[0] - functionAtT[0])
```

I recommend that it extends NumberPlane and makes use of inherited methods such as get_graph and get_coordinate_labels.
The config should also be updated apropos of the aforementioned changes. Many of the kwargs can be omitted completely as they are redundant compared to the config for NumberPlane and Axes.
`class TwoDScene(Scene,NumberPlane):`

I envision a config looking like 

```python
CONFIG = {
        "center_point": 2.5 * DOWN + 4 * LEFT,
        "axis_config": {
            "stroke_color": LIGHT_GREY,
            "stroke_width": 2,
            "include_ticks": True,
            "line_to_number_buff": 0.2,
            "label_direction": DOWN,
            "number_scale_val": 0.8,
            "color": LIGHT_GREY,
            "exclude_zero_from_default_numbers": True,
        },
        "x_axis_config": {
                "x_min": -1,
                "x_max": 5,
                "unit_size": 1,
                "color": LIGHT_GREY,
                "tick_frequency": 1,
                       },
        "y_axis_config": {
            "label_direction": LEFT,
            "x_min": -1,
            "x_max": 10,
            "unit_size": 1,
            "color": LIGHT_GREY,
            "tick_frequency": 1,
        },
    }
``` 

## Additional comments

If this were to be implemented, the GraphScene class should be considered deprecated.

**Comment by leotrs** [comment]
@protonlaser91 thanks for your writeup. Indeed, there are many many many classes that are outdated and need a lot of work. The refactors that you propose seem good to me in general. Are you preparing a PR for this? Or is there anything in particular you want to discuss before preparing a PR?

One note: we are working hard to get rid of CONFIG dicts completely. So in your refactoring of this class, please do not add new keys to the CONFIG dict. Instead, use `__init__` arguments.

**Comment by protonlaser91** [comment]
I did want to discuss reimplementation of every method in GraphScene. Does every single method in GraphScene need to be reimplemented in TwoDScene or is it alright to have a base class with some methods absent? (Which can be added in later with additional commits).

In my refactoring, I will not add any additional keys, but I was wondering if it is alright to make use of the original config dicts that are present in the coordinate_system.py file.

**Comment by leotrs** [comment]
In case you want to propose methods for removal, please deprecate them instead.

If you think a base class and a derived class is the best way of refactoring this, then that makes sense. The base class doesn't need to have all the methods.

Yes, please use any existing CONFIG dicts and their keys, but try not to add any new ones :slightly_smiling_face:

**Comment by leotrs** [comment]
Hi @protonlaser91 , since #788 was closed, can this issue be closed?

**Comment by protonlaser91** [comment]
Yes
