### ISSUE TITLE
Text: t2c is bogus

### ISSUE THREAD

**Issue by PhilippImhof** [ManimCommunity/manim#776]
## Description of bug / unexpected behavior
```python
from manim import *

class Text(Scene):

    def construct(self):
        txt=Text("foo and bar",t2c={"o": RED, "a": BLUE})
        self.add(txt)
        self.wait()
``` 
yields 
![image](https://user-images.githubusercontent.com/52650214/100349821-4e270e80-2fe9-11eb-98dc-8bc392d86aaa.png)

## Expected behavior
The letter `n` should definitely not be blue. One would expect both `a`'s to be BLUE. (It could be nice to have a way of defining that only one `o` or only one `a` is colored.) This is related to #741

**Comment by PhilippImhof** [comment]
Just as a comparison:

```python
from manim import *

class Text(Scene):

    def construct(self):
        txt=Text("foo and bar",t2w={"o": BOLD, "a": BOLD})
        self.add(txt)
        self.wait()
```
yields
![image](https://user-images.githubusercontent.com/52650214/100350424-284e3980-2fea-11eb-95d6-83bb691497d9.png)

So, the decomposition of the string works in other cases.

**Comment by leotrs** [comment]
Sounds like a duplicate of #625 

It is good to know that t2w is working though.

**Comment by PhilippImhof** [comment]
After checking again, I think you are right. Both seem to be linked to the fact that a space counts to the string length but not to the number of submobjects. I suspected that this was not the source of the problem here, but changing the test case showed me I was wrong....
