### ISSUE TITLE
Keep Some Mobjects in Fixed Place in MovingCameraScene

### ISSUE THREAD

**Issue by baljeetrathi** [ManimCommunity/manim#779]
There is a `add_fixed_in_frame_mobjects` method to keep mobjects in a fixed place in `ThreeDScene` class. However, it is not available in the `MovingCameraScene` class.

How can I keep an object fixed in the frame while the camera position moves around? Just like the `position:fixed` property in CSS while we scroll up and down the page.

Thanks.

**Comment by leotrs** [comment]
Hi @baljeetrathi! Thanks for asking this. Unfortunately I don't have an answer. In fact, it may very well be impossible. For more discussion, I suggest you go to our discord server and use one of the #help chanells. I'm sure more people there will be able to help you.

**Comment by behackl** [comment]
`MovingCameraScene` doesn't support this, but `ThreeDScene` does and can be used. A workaround would be to create a group with the camera frame and whichever mobjects should be fixed, and then move the group. Not sure whether the workaround is required though, just use `ThreeDScene`.

Closing.
