### ISSUE TITLE
FFMpeg hardware acceleration

### ISSUE THREAD

**Issue by Dabada** [ManimCommunity/manim#786]
Is there a way to make the encoder parameter configurable? This could make rendering time much faster. 
For AMD GPU user's they could use h264_amf or hevc_amf  encoder.

https://github.com/ManimCommunity/manim/blob/1cc64848e58d3975274e5ce960aea942c543a7af/manim/scene/scene_file_writer.py#L375

**Comment by leotrs** [comment]
Hello @Dabada! Thanks for your question. There is no way to change the codec right now. Have you been able to change the codec and use GPU acceleration? 

This would be a welcome addition BTW!

**Comment by huguesdevimeux** [comment]
Yes, I'm totally in favof of doing this if it could fast the process. 

I think this should be a parameter living in the .cfg file. 
Feel free to open a PR :)

**Comment by kolibril13** [comment]
@Dabada : Good suggestion!
If you have some time, feel free to open a pr!

**Comment by rosalogia** [comment]
Hi! If no one else is working on this right now I would be happy to. Is it as simple as changing what comes after `-vcodec`?

**Comment by leotrs** [comment]
@rosalogia you are now assigned to this ticket. Thanks for volunteering!

Unfortunately, I don't have enough experience with FFMPEG to answer your question, but perhaps @Dabada has ideas.

**Comment by rosalogia** [comment]
In the meanwhile I'll add a configuration option to make configuring what I described above possible. If this is incorrect or insufficient it shouldn't be too hard to fix :slightly_smiling_face:

**Comment by behackl** [comment]
Duplicate of #1145 (which has a better description of the feature to be implemented). Closing.
