### ISSUE TITLE
Enhance -n (allow to render intervals of animations)

### ISSUE THREAD

**Issue by XorUnison** [ManimCommunity/manim#79]
As the title says, simple issue. Right now `-n` can be used to start at a specific animation (and thus skip the prior ones). We should extend it to be able to render a specific interval of animations, so allowing it to stop rendering at a specific animation too.

Also... `--start_at_animation_number` is not just going to be deprecated then, it's also just obnoxiously long. What should it be called afterwards though? Keeping `-n` is fine but if we keep the long form... `--interval`? `--animation_interval`? `--animate_interval`?

**Comment by raghavg123** [comment]
You can already do that by providing two comma separated values.
`-n <start>, <stop>`

**Comment by XorUnison** [comment]
Is that so? Hm... yeah looks like it. We should at least fix the confusing indications. Stuff like `--start_at_animation_number`.

**Comment by raghavg123** [comment]
Agreed.

**Comment by kilacoda** [comment]
Should this be closed? The title is misleading apparently.

**Comment by leotrs** [comment]
@XorUnison I will add a `--from_animation_number` to my PR on rewriting the config/constants setup.
