### ISSUE TITLE
Easy way to change background color of LabledDot

### ISSUE THREAD

**Issue by kolibril13** [ManimCommunity/manim#801]
At the moment, it is possible to use a LabledDot:
https://docs.manim.community/en/latest/reference/manim.mobject.geometry.LabeledDot.html?highlight=dot#manim.mobject.geometry.LabeledDot
Buut when one wants to change the backgroundcolor, it fails:
```py
class SeveralLabeledDots(Scene):
    def construct(self):
        dot1 = LabeledDot(Tex("42", color=RED)).scale(6)
        dot1.set_color(GREEN)
        self.add(dot1)
```
Therefore, I am suggesting to have a further style item that enables to change the background and the foreground colour of the lableddot independently.
![image](https://user-images.githubusercontent.com/44469195/100746464-06d1c100-33e1-11eb-9507-9d36a4343dc4.png)

**Comment by leotrs** [comment]
This sounds like a duplicate of #213 . I would rather fix that general bug than add a new functionality just for labeled dot

**Comment by kolibril13** [comment]
okay!
