### ISSUE TITLE
Setting Filename using cfg file

### ISSUE THREAD

**Issue by naveen521kk** [ManimCommunity/manim#805]
## Description of proposed feature
Having a `manim.cfg` in a folder should be enough for manim to run. For example, users can run `manim .` in that folder and the `.cfg` file should contain the file name. Also, running `manim some.cfg` should also work. Doing this would simply make it so that people no need to remember the file name 😉 instead they would move to their workspace (say a folder) and then run `manim .` which should get the file name from the `manim.cfg` present in the folder and render that. This would help me a lot though.

## How can the new feature be used?
Supporting the command
```sh
manim .
```
and
```sh
manim
```
also 
```sh
manim my.cfg
```
for passing custom configuration files.

## Additional comments
I have seen this it the `pip` tries to do when we do `pip install .`.

**Comment by leotrs** [comment]
There are three things to do here:

1. Right now, the input file name is a obligatory command line argument. For this to work, it should be optional. (This will add to our argparse woes...)

2. The ManimConfig should hold a reference to the input file. [This is already possible](https://docs.manim.community/en/latest/reference/manim._config.utils.ManimConfig.html#manim._config.utils.ManimConfig.input_file).

2. `__main__.py` must read the input file from the ManimConfig, and not from the command line arguments.

**Comment by naveen521kk** [comment]
I am marking this as "good first issue".

**Comment by omriShneor** [comment]
@leotrs @naveen521kk Im planning on doing this as a first issue(if that's fine by you?).

**Comment by naveen521kk** [comment]
assigning you :)

**Comment by Darylgolden** [comment]
Unassigned due to inactivity.

**Comment by fatkaratekid** [comment]
I'll give it a go
