### ISSUE TITLE
Do we really need to add every color to locals()?

### ISSUE THREAD

**Issue by leotrs** [ManimCommunity/manim#81]
Currently, `constants.py` is adding every color inside `COLOR_MAP` to the `locals()` dictionary. This is usually frowned upon in Python in general.

If we want to keep exposing all colors to the end user without any namespace access (like `manim.colors.RED` or some such), then we can carefully import all colors inside `__init__.py`. This could be done for the purpose of backward compatibility.

**Comment by leotrs** [comment]
I would love some feedback here.

I think the only problem with removing all colors from `locals()` is that this *could* be a breaking change for some users. Maybe we could deprecate it before removing them completely.

**Comment by PgBiel** [comment]
Could probably use some `Color` class in order to be able to accept multiple formats as well

**Comment by leotrs** [comment]
So the problem right now is that the colors can be accessed in at least three different ways: `constants.COLOR_MAP['BLACK']`, simply as `BLACK` , and `PALETTE`. The latter one is only ever used once in the code and I think should be deprecated. Right now, we are manipulating `locals` in order to dump the contents of `COLOR_MAP` into the scope of `constants`. Not sure if we want to do that. I don't think the code uses `COLOR_MAP` at all, so why not just define all its contents as variables from the start? These could be either hex strings, or `Color` instances, as @PgBiel suggests

**Comment by leotrs** [comment]
I still think we should move all colors to something like `manim.colors`, and turn them all into `Colour` instances too. We can easily do this in a backwards-compatible way.

**Comment by leotrs** [comment]
#488 implements this.
