### ISSUE TITLE
Swiching from manimce to manim in pypi

### ISSUE THREAD

**Issue by kolibril13** [ManimCommunity/manim#818]
At the moment, we have two repos at PyPI:
https://pypi.org/project/manimce/ (Version 0.1.1)
and 
https://pypi.org/project/manim/ (Version 0.1.0)

And I think we discussed that we want to stay with manim and not with manimce.

I have very little experience with packaging, so can maybe someone with more expertise take over my PR where I also altered python-publish.yml ? (see https://github.com/ManimCommunity/manim/pull/794 )
@naveen521kk , @eulertour  , @leotrs   ?

**Comment by leotrs** [comment]
I don't know how to fix this, but we should find a way to fix it :thinking: 

In our last call we discussed making `manimce` a dummy package that just asks the user to install the correct package instead.

**Comment by naveen521kk** [comment]
This is done. On release next time it will be released to `manim` but @eulertour would need to update the token.
