### ISSUE TITLE
Document removal of CONFIG

### ISSUE THREAD

**Issue by behackl** [ManimCommunity/manim#819]
## Enhancement proposal

As a follow-up to the recent removal of CONFIG dictionaries via #783, these changes should be very clearly and explicitly documented.

To discuss:
- Should something happen if a user tries to set a CONFIG variable? Can we even reasonably do something about that?
- Should there be just a very explicit changelog entry, or a full page/section for dealing with migrating from CONFIG to passing arguments?

**Comment by cobordism** [comment]
We should also change the "Plotting with manim" examples.  See here: https://docs.manim.community/en/latest/examples.html#plotting-with-manim

Currently, in keeping with the systematic removal of CONFIG, the variables previously in CONFIG are now keyword arguments to `__init__()`. However this is not really user friendly in the case of plotting where implementing your own init function is more complicated than just specifying a dictionary.

According to https://github.com/ManimCommunity/manim/issues/7#issuecomment-736012926 it might be a simple case of documenting it better - i.e. no custom __init__() is actually needed when using these classes.

**Comment by leotrs** [comment]
> However this is not really user friendly in the case of plotting where implementing your own init function is more complicated than just specifying a dictionary.

Can you clarify what you mean by this?

**Comment by leotrs** [comment]
I feel tired just by saying this because it's more on my plate, but: I think we should do two things. First, have all our classes reject the existence of any `CONFIG` attribute. Second, write a full document detailing how to migrate from CONFIG to the new style classes.

The first step can be just this:
```python
class Scene():
    def __init__(self, ...):
        if hasattr(self, CONFIG):
            print("NOPE")
```

**Comment by cobordism** [comment]
> Can you clarify what you mean by this?

just compare https://docs.manim.community/en/latest/examples.html#plotting-with-manim
to https://docs.manim.community/en/v0.1.1/examples.html#plotting-with-manim

>  think we should do two things. First, have all our classes reject the existence of any CONFIG attribute. 

done. This was already in the PR 
https://github.com/ManimCommunity/manim/blob/master/manim/container.py#L28-L31
https://github.com/ManimCommunity/manim/blob/master/manim/animation/animation.py#L50-L54

**Comment by leotrs** [comment]
> > Can you clarify what you mean by this?
> 
> just compare https://docs.manim.community/en/latest/examples.html#plotting-with-manim
> with https://docs.manim.community/en/v0.1.1/examples.html#plotting-with-manim
> 

No need to mess around with init. I believe we should encourage either one of the following instead:

```python
class SinAndCosFunctionPlot(GraphScene):

    def construct(self):
        # make sure to set all these _before_ calling setup_axes()
        self.x_min=-10
        self.x_max=10.3
        self.num_graph_anchor_points=100
        self.y_min=-1.5
        self.y_max=1.5
        self.graph_origin=ORIGIN
        self.axes_color=GREEN
        self.x_labeled_nums=range(-10, 12, 2)
        self.function_color = RED
        self.setup_axes(animate=False)

        # plotting code here
```

OR, the following:

```python
class SinAndCosFunctionPlot(GraphScene):

    def setup(self):
        # make sure to set all these _before_ calling setup_axes()
        self.x_min=-10
        self.x_max=10.3
        self.num_graph_anchor_points=100
        self.y_min=-1.5
        self.y_max=1.5
        self.graph_origin=ORIGIN
        self.axes_color=GREEN
        self.x_labeled_nums=range(-10, 12, 2)
        self.function_color = RED
        super().setup()
        self.setup_axes(animate=False)

    def construct(self):
        # plotting code here
```

**Comment by naveen521kk** [comment]
On the side note, we should start typing (https://docs.python.org/3/library/typing.html ) everything we could see in `__init__`.

**Comment by behackl** [comment]
> > > Can you clarify what you mean by this?
> > 
> > 
> > just compare https://docs.manim.community/en/latest/examples.html#plotting-with-manim
> > with https://docs.manim.community/en/v0.1.1/examples.html#plotting-with-manim
> 
> No need to mess around with init. I believe we should encourage either one of the following instead:
> 
> ```python
> class SinAndCosFunctionPlot(GraphScene):
> 
>     def construct(self):
>         # make sure to set all these _before_ calling setup_axes()
>         self.x_min=-10
>         self.x_max=10.3
>         self.num_graph_anchor_points=100
>         self.y_min=-1.5
>         self.y_max=1.5
>         self.graph_origin=ORIGIN
>         self.axes_color=GREEN
>         self.x_labeled_nums=range(-10, 12, 2)
>         self.function_color = RED
>         self.setup_axes(animate=False)
> 
>         # plotting code here
> ```
> 
> OR, the following:
> 
> ```python
> class SinAndCosFunctionPlot(GraphScene):
> 
>     def setup(self):
>         # make sure to set all these _before_ calling setup_axes()
>         self.x_min=-10
>         self.x_max=10.3
>         self.num_graph_anchor_points=100
>         self.y_min=-1.5
>         self.y_max=1.5
>         self.graph_origin=ORIGIN
>         self.axes_color=GREEN
>         self.x_labeled_nums=range(-10, 12, 2)
>         self.function_color = RED
>         super().setup()
>         self.setup_axes(animate=False)
> 
>     def construct(self):
>         # plotting code here
> ```

Semantically, I would kind of expect to be able to set all of these parameters as keywords of `self.setup_axes`. Any thoughts about that?

**Comment by leotrs** [comment]
Oh, that actually makes more sense!

**Comment by cobordism** [comment]
> Oh, that actually makes more sense!

yes. let's implement and document that. Should be pretty straightforward and methodical to implement.

**Comment by behackl** [comment]
I've added an example similar to the one @cobordism suggested on Discord to the changelog; also our documentation has been updated accordingly.

I think this issue can be closed for now.
