### ISSUE TITLE
(CI) Setting Up Caching For MacOS

### ISSUE THREAD

**Issue by naveen521kk** [ManimCommunity/manim#824]
Currently, Windows CI uses caching 
https://github.com/ManimCommunity/manim/blob/f4edcfa5fcc44b7858e2957a1e64d636da59d483/.github/workflows/ci.yml#L71-L77
something similar must be done for macOS and Linux also because it sometimes takes a lot of time to Install and increases the test time. The things which need to be cached is Latex(maybe use TinyTeX as it portable and like windows CI) and things installed using brew ie) ffmpeg.
Depends on #823

**Comment by RickyC0626** [comment]
I guess I can look into this after fixing the macOS CI pipeline error.
