### ISSUE TITLE
Improve Uncreate Animation

### ISSUE THREAD

**Issue by ponmike92** [ManimCommunity/manim#841]
## Enhancement proposal
Uncreate Animation can be enchanted in four options:

1. If user want to change rate_func of this animation right now he will need to pass something like this: 
- lambda t: smooth(1-t)
- lambda t: linear(1-t)
and so on. Why not simply smooth, linear etc. ?

2. Make ability to change direction of destruction.
3. Why it is inherited from ShowCreation? It is logically can be more referred to ShowPartial class.
4.  To avoid ambiguity I would rename it to ShowDestruction. The main reason - opposite of this animation is ShowCreation. To don't break user code - two names can be possible (old and new)

## How it is animating right now
```python
class Destruction1(Scene):
    def construct(self):
        mob = Line()

        self.play(
            ShowCreation(mob),
            rate_func=linear,
        )

        self.play(
            Uncreate(mob),
            rate_func=lambda t: 1 - linear(t),
        )
```

![Destruction1](https://user-images.githubusercontent.com/64367553/101438855-543fb800-3924-11eb-8d05-19b0b3fe69c6.gif)

## How it could be animated in more logical way
```python
class ShowDestruction(ShowPartial):
    def __init__(self, mobject, lag_ratio=1, remover=True, **kwargs):
        super().__init__(mobject, lag_ratio=lag_ratio, remover=remover, **kwargs)

    def _get_bounds(self, alpha):
        return (alpha, 1)


class Destruction2(Scene):
    def construct(self):
        mob = Line()

        self.play(
            ShowCreation(mob),
            rate_func=linear,
        )
        
        self.play(
            ShowDestruction(mob),
            rate_func=linear,
        )
```
![Destruction2](https://user-images.githubusercontent.com/64367553/101438865-5b66c600-3924-11eb-88d1-82db9cd64e79.gif)

## How can we keep both variants possible

Create flag like  invert_destruction. Implementation could be like this:

```python
class ShowDestruction(ShowPartial):

    def __init__(
        self, mobject, rate_func=smooth, remover=True, invert_destruction=False, **kwargs
    ):

        rate_f = lambda t: rate_func(1-t) if invert_destruction else rate_func
        self.invert_destruction = invert_destruction

        super().__init__(mobject, rate_func=rate_f, remover=remover, **kwargs)

    def _get_bounds(self, alpha):
        if self.invert_destruction:
            return (0, alpha)
        else:
            return (alpha, 1)
```

However, I have bugs in when invert_destruction=True. Need to discuss this idea.

**Comment by leotrs** [comment]
> 1. If user want to change rate_func of this animation right now he will need to pass something like this:
> 
> * lambda t: smooth(1-t)
> * lambda t: linear(1-t)
>   and so on. Why not simply smooth, linear etc. ?

Agreed.
 
> 1. Make ability to change direction of destruction.

Agreed.

> 2. Why it is inherited from ShowCreation? It is logically can be more referred to ShowPartial class.

What difference would it make to the end user if this inheritance was changed?

> 3. To avoid ambiguity I would rename it to ShowDestruction. The main reason - opposite of this animation is ShowCreation. To don't break user code - two names can be possible (old and new)

I would suggest we change `ShowCreation` to `Create` and leave `Uncreate` intact.

> ## How it could be animated in more logical way

I like how the code looks like with your proposal, but I am neutral as to what is the "logical" direction for the animation. I think we should support both, but neither direction sounds like it is better than the other. In fact, if possible, I would like to keep the current direction as the default one so that rendered scenes are not changed.

> Create flag like invert_destruction. Implementation could be like this:

I'd suggest calling it simply `invert`. Sounds less redundant. 

> However, I have bugs in when invert_destruction=True. Need to discuss this idea.

What bugs? Can you expand please? @XorUnison does this have anything to do with direction?

**Comment by ponmike92** [comment]
For me it is hard to understand why. I will leave log:

I  run this:
```py
class Test_ShowDestruction(Scene):
    def construct(self):
        mob = Line()

        self.play(ShowCreation(mob))
        self.play(ShowDestruction(mob)
```

OUTPUT:
```bash
Traceback (most recent call last):
  File "/Users/mihail/Disk_Google/1_Maths/ponomi_math/CODE/manim/manim/__main__.py", line 92, in main
    scene.render()
  File "/Users/mihail/Disk_Google/1_Maths/ponomi_math/CODE/manim/manim/scene/scene.py", line 99, in render
    self.construct()
  File "test_ArcPinnedToThreePoints.py", line 93, in construct
    ShowDestruction2(mob, rate_func=lambda t: smooth(1-t))
  File "/Users/mihail/Disk_Google/1_Maths/ponomi_math/CODE/manim/manim/scene/scene.py", line 742, in play
    self.renderer.play(self, *args, **kwargs)
  File "/Users/mihail/Disk_Google/1_Maths/ponomi_math/CODE/manim/manim/renderer/cairo_renderer.py", line 12, in wrapper
    func(self, scene, *args, **kwargs)
  File "/Users/mihail/Disk_Google/1_Maths/ponomi_math/CODE/manim/manim/utils/caching.py", line 52, in wrapper
    func(self, scene, *args, **kwargs)
  File "/Users/mihail/Disk_Google/1_Maths/ponomi_math/CODE/manim/manim/renderer/cairo_renderer.py", line 40, in wrapper
    func(self, scene, *args, **kwargs)
  File "/Users/mihail/Disk_Google/1_Maths/ponomi_math/CODE/manim/manim/renderer/cairo_renderer.py", line 77, in play
    scene.play_internal(*args, **kwargs)
  File "/Users/mihail/Disk_Google/1_Maths/ponomi_math/CODE/manim/manim/scene/scene.py", line 791, in play_internal
    animation.begin()
  File "/Users/mihail/Disk_Google/1_Maths/ponomi_math/CODE/manim/manim/animation/animation.py", line 80, in begin
    self.interpolate(0)
  File "/Users/mihail/Disk_Google/1_Maths/ponomi_math/CODE/manim/manim/animation/animation.py", line 133, in interpolate
    self.interpolate_mobject(self.rate_func(alpha))
  File "/Users/mihail/Disk_Google/1_Maths/ponomi_math/CODE/manim/manim/animation/animation.py", line 149, in interpolate_mobject
    sub_alpha = self.get_sub_alpha(alpha, i, len(families))
  File "/Users/mihail/Disk_Google/1_Maths/ponomi_math/CODE/manim/manim/animation/animation.py", line 162, in get_sub_alpha
    value = alpha * full_length
TypeError: unsupported operand type(s) for *: 'function' and 'int'
```

**Comment by XorUnison** [comment]
> What bugs? Can you expand please? @XorUnison does this have anything to do with direction?

@leotrs Well actually yes. The result in the OP can actually be gotten by simply using `mob.reverse_direction()` before `Uncreate`. This should actually hold for any and all cases. Whenever you want to reverse creation/uncreation, my direction methods should do the trick.

**Comment by leotrs** [comment]
@ponmike92 could you please try the `reverse_direction` method as suggested by @XorUnison ?

**Comment by ponmike92** [comment]
>  could you please try the reverse_direction method as suggested by @XorUnison ?

Main idea of any Animation is to do operations under passed mobject.
1. Won't we break the logic if modify mobject first? 
2. If I'm not mistaken we will do additional operations over points of mobject. Will it be slower implementation rather than overriding get_bounds() method?

**Comment by ponmike92** [comment]
> What difference would it make to the end user if this inheritance was changed?

```py
class MyAnimation(Uncreate):
    pass

isinstance(MyAnimation, Uncreate) # okay
isinstance(MyAnimation, Create) # stange for user
isinstance(MyAnimation, ShowPartial) # okay
```

If Uncreate will be inherited from ShowPartial:
```py
class MyAnimation(Uncreate):
    pass

isinstance(MyAnimation, Uncreate) # okay
isinstance(MyAnimation, Create) # okay
isinstance(MyAnimation, ShowPartial) # okay
```

**Comment by kilacoda** [comment]
> For me it is hard to understand why. I will leave log:
> 
> I run this:
> 
> ```python
> class Test_ShowDestruction(Scene):
>     def construct(self):
>         mob = Line()
> 
>         self.play(ShowCreation(mob))
>         self.play(ShowDestruction(mob)
> ```
> 
> OUTPUT:
> 
> ```shell
>   File "test_ArcPinnedToThreePoints.py", line 93, in construct
>     ShowDestruction2(mob, rate_func=lambda t: smooth(1-t))
> ```

The code you posted and the traceback in the log don't match up?

**Comment by leotrs** [comment]
> > could you please try the reverse_direction method as suggested by @XorUnison ?
> 
> @leotrs I can but first have some questions
> 
> Main idea of any Animation is to do operations under passed mobject.
> 
> 1. Won't we break the logic if modify mobject first? (even in Animation **init** method)
> 2. If I'm not mistaken we will do additional operations over points of mobject. Will it be slower implementation rather than overriding get_bounds() method?

You're right, it might be slower if the mobject has many points. Let's do it your way.

I do insist in keeping the current behavior as the default, and having the new one optionally.

Please address @kilacoda 's question when you get the chance :slightly_smiling_face:

**Comment by ponmike92** [comment]
> The code you posted and the traceback in the log don't match up?
@kilacoda only in namings. I have my own ShowCreation function. But for tests I created another one with name ShowCreation2.

**Comment by ponmike92** [comment]
>You're right, it might be slower if the mobject has many points. Let's do it your way.
I do insist in keeping the current behavior as the default, and having the new one optionally.

@leotrs Yeah, it is a good idea to keep current behaviour. I will have more time next week to test it. Any other suggestions or I can prepare PR?

**Comment by kilacoda** [comment]
> > The code you posted and the traceback in the log don't match up?
> 
> @kilacoda only in namings. I have my own ShowCreation function. But for tests I created another one with name ShowCreation2. 

That's... not what I meant. In the code you said wasn't working, there was no mention of rate_func, however the traceback does, which may be responsible for varying outputs, and is thus not a clear indication of the issue.

**Comment by ponmike92** [comment]
@kilacoda ok, thank you! I will look deeper in rate_func and for further tests

**Comment by behackl** [comment]
The implementation of `Uncreate` has been improved via #2597, and as far as I can tell all points initially mentioned are now possible more or less naturally. Closing.
