### ISSUE TITLE
Improve FadeIn Animation

### ISSUE THREAD

**Issue by ponmike92** [ManimCommunity/manim#842]
## Enhancement proposal
Logically FadeIn animation should just change opacity of object from 0 to object's opacity. However, in addition to that it enlarges object's stroke width. That leads to ambiguity. My suggestion is to add enlarge_stroke flag to handle this case.

## How it is right now
```python
class TestFadeIn1(Scene):
    def construct(self):
        mob = Line(stroke_width=30)

        self.play(
            FadeIn(mob),
        )
```

![FadeIn1](https://user-images.githubusercontent.com/64367553/101445893-58270680-3933-11eb-9d03-78981f731675.gif)

## How it could be
```python
class FadeIn(Transform):
    def __init__(self, vmobject, lag_ratio=DEFAULT_FADE_LAG_RATIO, enlarge_stroke=True, **kwargs):
        self.enlarge_stroke=enlarge_stroke
        super().__init__(vmobject, lag_ratio=lag_ratio, **kwargs)

    def create_target(self):
        return self.mobject

    def create_starting_mobject(self):
        start = super().create_starting_mobject()
        start.fade(1)
        if isinstance(start, VMobject):
            if self.enlarge_stroke:
                start.set_stroke(width=0)
            start.set_fill(opacity=0)
        return start

class TestFadeIn2(Scene):
    def construct(self):
        mob = Line(stroke_width=30)

        self.play(
            FadeIn(mob, enlarge_stroke=False),
        )
```
![FadeIn2](https://user-images.githubusercontent.com/64367553/101446169-c966b980-3933-11eb-8763-b9270ed3f201.gif)

**Comment by leotrs** [comment]
This makes sense to me in general. Could you please post an example of how this looks like when using your version of FadeIn on a Mobject that has both stroke and fill? (lines only have stroke) A circle with fill_opacity=1.0 should work. Thanks!

**Comment by ponmike92** [comment]
@leotrs , yeah, of course! 

My results seems to be weird. Is white stroke during creation is normal? It comes with both animations. Old one and mine.
I tested with this code:

## Current FadeIn
```py
class TestFadeIn1(Scene):
    def construct(self):
        mob = Circle(radius=1.5, stroke_width=100, fill_opacity=1, stroke_color=BLUE)

        self.play(
            FadeIn(mob),
            run_time=2,
        )
```
![TestFadeIn1](https://user-images.githubusercontent.com/64367553/101521002-462a7f80-3996-11eb-8659-537ff3074e6a.gif)


## Suggested FadeIn
```py
class TestFadeIn2(Scene):
    def construct(self):
        mob = Circle(radius=1.5, stroke_width=100, fill_opacity=1, stroke_color=BLUE)

        self.play(
            FadeIn(mob, enlarge_stroke=False),
            run_time=2,
        )
```
![TestFadeIn2](https://user-images.githubusercontent.com/64367553/101521027-4dea2400-3996-11eb-890d-2b9d97483b9c.gif)

**Comment by leotrs** [comment]
I believe this is probably the "background_stroke", can you please try disabling that?

**Comment by ponmike92** [comment]
> I believe this is probably the "background_stroke", can you please try disabling that?

@leotrs I did but results are the same. 

```py
class TestFadeIn1(Scene):
    def construct(self):
        mob = Circle(radius=1.5, stroke_width=100, fill_opacity=1, stroke_color=BLUE,
            background_stroke_width=0, background_stroke_opacity=0)

        self.play(
            FadeIn(mob),
            run_time=2,
        )
```

**Comment by leotrs** [comment]
In that case, since the current FadeIn is also showing this strange white line, then let's move forward with your PR

**Comment by behackl** [comment]
The described behavior regarding stroke width is no longer present. Closing.
