### ISSUE TITLE
scene.play() method passes rate_func to animations not correctly

### ISSUE THREAD

**Issue by ponmike92** [ManimCommunity/manim#844]
## Description of bug / unexpected behavior

scene.play() method passes rate_func to animations not correctly. For example:

1. let's create simple animation (some args were omitted to better show problem)

```py
class UserAnimation(Animation):
    def __init__(self, rate_func=None, **kwargs):
        print("rate_func passed: ", rate_func)

        super().__init__(VMobject(), **kwargs)
```

2. Now, call this animation via scene.play() method

```py
class TestPassRateFuncFail(Scene):
    def construct(self):

        self.play(
            UserAnimation(),
            rate_func=there_and_back
        )
```

```shell
rate_func passed:  None
```

3. We see that rate_func is not passed to Animation via scene.play(). How to fix? Directly add rate_func as arg in user animation.

```py
class TestPassRateFuncSuccess(Scene):
    def construct(self):

        self.play(
            UserAnimation(rate_func=there_and_back),
        )
```

OUTPUT:
```shell
rate_func passed:  <function there_and_back at 0x7fe82be8c8c8>
```

## Conclusion
This is weird behaviour. We can't rely on rate_func which is set via scene.play() method. I haven't checked run_time. Maybe is is the same.

## Additional comments
I came up with idea that we can pass via scene.play() other args apart from rate_func, run_time, lag_ratio, etc. For example, user want to create my_attr1, my_attr1. So he could use both of these variants:

Option 1:
```py
        self.play(
            UserAnimation(mob, run_time=2, my_attr1=True, my_attr2=1.5)
        )
```

Option 2:
```py
        self.play(
            UserAnimation(mob),
            run_time=2,
            my_attr1=True,
            my_attr2=1.5,
        )
```

What if we call two animations at the same time? One of which will have custom attributes and other not? So scene.play() method will apply attributes only for animations which contain that attributes. Illustration in code below:

```py
        self.play(
            FadeIn(mob1),
            UserAnimation(mob2),
            run_time=2,
            my_attr1=True,
            my_attr2=1.5,
        )
```
will be equal to:

```py
        self.play(
            FadeIn(mob1, run_time=2),
            UserAnimation(mob2, run_time=2, my_attr1=True, my_attr2=1.5),
        )
```

**Comment by eulertour** [comment]
The `rate_func` argument isn't supposed to be passed to the animation, it's passed to `Scene.play()`. Why do you want it passed to the animation in the first place?
