### ISSUE TITLE
Add metadata to the videofile

### ISSUE THREAD

**Issue by kolibril13** [ManimCommunity/manim#848]
At the moment, the video metatdata looks like this:
![image](https://user-images.githubusercontent.com/44469195/101507773-36e80980-3977-11eb-9927-115289070dfe.png)
I think we can add some useful things from here:
https://wiki.multimedia.cx/index.php/FFmpeg_Metadata
to our ffmpeg pipeline in order to include some more info.
So e.g. resolution and framerate, but also probably author, title and date

**Comment by Hari-07** [comment]
I'd like to take this up if no one else is working on it

**Comment by kolibril13** [comment]
@Hari-07 : 
Thanks for your interest!
That would be a very welcome contribution!
I am an ubuntu user, so maybe you can beforehand check if your properties are as empty as mine, so that we know that this is not only an ubuntu related problem.

**Comment by Hari-07** [comment]
On windows rendered using WSL ,running the code in the quickstart section,both the 1080p 60fps and 480p 15 fps displays data rate, bitrate , frame size and frame rate. All the other details are blank though

**Comment by kolibril13** [comment]
I just loaded one video to kdenlive, and there the info is shown:
![image](https://user-images.githubusercontent.com/44469195/102716929-494f3500-42df-11eb-9df3-1b59d4870b17.png)
As this seems to be an ubuntu file browser related issue with not showing the frame rate, and resolution , I am closing this issue, but feel free  @Hari-07 , if you would like to add metadata like year, name etc.
