### ISSUE TITLE
"Semi-video" image option for testing and previewing a scene

### ISSUE THREAD

**Issue by kolibril13** [ManimCommunity/manim#849]
I have an idea to overlay videoframes from certain timestamps above each other, e.g. from this scene:
```python
from manim import *

class ABC(Scene):
    def construct(self):
        sq = Circle().set_color(YELLOW_C).shift(4*LEFT).scale(0.6)
        self.add(sq)
        rec = Square().shift(4*RIGHT).scale(0.6).set_fill("#87CEEB",1)
        self.play(Transform(sq,rec),run_time=3)
        self.wait(1)
``` 
![ABC](https://user-images.githubusercontent.com/44469195/101552139-99123000-39b2-11eb-9555-7910c83e16e8.gif)

Which can be converted into this:
![image](https://user-images.githubusercontent.com/44469195/101552214-ba731c00-39b2-11eb-982f-7a84b6f4c44b.png)
to create this specific example, I used the script you can see at the bottom.
This is only a first prototype but in a more advanced approach, one could further include parameters how many frames will be overlaid, what the time interval will be, and further, it would be nice to make the latter images higher opacity than to the former images. 
This can be a very useful tool for creating manim scenes, without the necessity to see the video, but to have the time projection into two dimensions, and further, it could be a great addition for our test section, as we do not yet support video testing.
A starting point to implement this could be something like this:
```python
nums_of_steps= 4
for timestemp in np.linspace(0,2,nums_of_steps):
    image += scene.renderer.get_frame(pos= timestemp) #does not exist yet
```

And here the prototype code for the above image example:

```python
import numpy as np
import matplotlib.pyplot as plt
url="/home//Downloads/pngs/"
from imageio import imread
image = np.array(imread(url+ "ABC0.png"))
image += np.array(imread(url+ "ABC80.png"))
image += np.array(imread(url+ "ABC100.png"))
image += np.array(imread(url+ "ABC210.png"))
plt.axis('off')
plt.imshow(image, interpolation='nearest', cmap='gray')
plt.show()
```

**Comment by eulertour** [comment]
I actually don't think there are many uses for this. It'd be an imprecise and difficult-to-debug way to implement video tests and won't be useful for scenes where mobjects transform in place.
