### ISSUE TITLE
Lambda needed for add_updater

### ISSUE THREAD

**Issue by protonlaser91** [ManimCommunity/manim#850]
## Description of bug / unexpected behavior

add_updater doesn't work with a function* passed in as an argument unless it is in lambda form

*that is part of the class and has the self argument

## Expected behavior

add_updater successfully working without throwing an error and not needing to use a lambda as an intermediary.

## How to reproduce the issue

<details><summary>Code for reproducing the problem</summary>

```py
class A(Scene):
    def updatingFunction(self, t):
        t.set_height(self.value.get_value())

    def construct(self):
        r = Rectangle().add_updater(self.updatingFunction) # does not work
      # r = Rectangle().add_updater(lambda t: self.updatingFunction(t)) does work
        self.value = ValueTracker(r.get_height())
        self.play(ShowCreation(r))
        self.play(self.value.set_value,10)

```

</details>

## Additional media files

<details><summary>Images/GIFs</summary>

</details>

## Logs
<details><summary>Terminal output</summary>

```
https://pastebin.com/8sCPtuED
```

</details>

## System specifications

<details><summary>System Details</summary>

- OS Win 10
- RAM: 12 GB
- Python version (`python/py/python3 --version`): Python 3.9
- Installed modules (provide output from `pip list`): 
```
Package           Version
----------------- -------
cairocffi         1.2.0
cffi              1.14.3
colorama          0.4.4
colour            0.1.5
commonmark        0.9.1
grpcio            1.33.2
grpcio-tools      1.33.2
manimce           0.1.0
numpy             1.19.3
pangocairocffi    0.3.2
pangocffi         0.6.0
pathtools         0.1.2
Pillow            8.0.1
pip               20.2.4
progressbar       2.5
protobuf          3.13.0
pycairo           1.20.0
pycparser         2.20
pydub             0.24.1
Pygments          2.7.2
rich              9.2.0
scipy             1.5.4
setuptools        50.3.2
six               1.15.0
tqdm              4.51.0
typing-extensions 3.7.4.3
watchdog          0.10.3
```
</details>

<details><summary>LaTeX details</summary>

+ LaTeX distribution (e.g. TeX Live 2020): TeX Live 2020
+ Installed LaTeX packages: manim-latex

</details>

<details><summary>FFMPEG</summary>

Output of `ffmpeg -version`: 

```
ffmpeg version 4.3.1 Copyright (c) 2000-2020 the FFmpeg developers
built with gcc 10.2.1 (GCC) 20200726
configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libsrt --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libgsm --enable-librav1e --disable-w32threads --enable-libmfx --enable-ffnvcodec --enable-cuda-llvm --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt --enable-amf
libavutil      56. 51.100 / 56. 51.100
libavcodec     58. 91.100 / 58. 91.100
libavformat    58. 45.100 / 58. 45.100
libavdevice    58. 10.100 / 58. 10.100
libavfilter     7. 85.100 /  7. 85.100
libswscale      5.  7.100 /  5.  7.100
libswresample   3.  7.100 /  3.  7.100
libpostproc    55.  7.100 / 55.  7.100
```
</details>

## Additional comments

Very similar to #761

**Comment by leotrs** [comment]
Thanks @protonlaser91. I *believe* this is because the `r.updaters` list contains a direct reference to the object's method, and apparently that cannot be `deepcopy`ed effectively. Using the lambda fixes this because then the `r.updaters` list contains a reference to an entirely different function instead.

I don't see how to fix this other than completely changing the way that updaters work. In my ideal world, updaters would not just be a list stored in the object itself, but we would use some sort of event-based system instead.

Perhaps @kolibril13 has some other thoughts

**Comment by eulertour** [comment]
I actually can't get either version of the code to work. Both fail with `AttributeError: 'DraftScene' object has no attribute 'value'`. But that aside it doesn't seem like the code would work properly even if that was fixed, because the first argument to an updater is supposed to be the mobject being updated.

**Comment by leotrs** [comment]
> I actually can't get either version of the code to work. Both fail with `AttributeError: 'DraftScene' object has no attribute 'value'`. But that aside it doesn't seem like the code would work properly even if that was fixed, because the first argument to an updater is supposed to be the mobject being updated.

Where did DraftScene come from?

**Comment by eulertour** [comment]
I just always give my Scenes that name so I can easily reuse command lines.

**Comment by leotrs** [comment]
I confirm I can run the code in the OP and I get a similar error to @protonlaser91.

@eulertour are you on latest master? It sounds like the updater is being called before the ValueTracker has been created. In the past, each updater was ran once as soon as it was added, but that changed a while ago I think.

**Comment by eulertour** [comment]
@leotrs That was true, there was some path resolution running an old version. The first argument to an updater has to be the mobject being updated (not a Scene), so this version of the code works.
```python
from manim import *


class DraftScene(Scene):
    def construct(self):
        def updatingFunction(r):
            r.set_height(self.value.get_value())

        r = Rectangle().add_updater(updatingFunction)  # does not work
        # r = Rectangle().add_updater(lambda t: self.updatingFunction(t))  # does work
        self.value = ValueTracker(r.get_height())
        self.play(ShowCreation(r))
        self.play(self.value.set_value, 10)
```
