### ISSUE TITLE
manim does not add svg text to the movie

### ISSUE THREAD

**Issue by mohammadsaleh40** [ManimCommunity/manim#863]
I want to add persian text to my video.I want to use the SVG file but the text inside is not displayed. [This is](https://svgshare.com/s/SHu) my sample file

this is my python code:
`from manimlib.imports import *

class aa(Scene):
    def construct(self):

        a=SVGMobject(r"/home/lpp/programing/manim/khodesh/svgfile")
        a.set_color("#00FFFf")
        self.add(a)
        self.wait()`

[https://i.stack.imgur.com/uj3QT.png](and this is the last frame)
how can i add text to my video?

**Comment by naveen521kk** [comment]
**Please follow the issue template while opening the issue.** 

Thanks for opening this issue. We know that the SVG parser isn't that Good.
On seeing the import statement, I could infer that it is 3b1b's version of Manim. Did you try the same on community version before opening an issue?
Also, on the community version we have [Text](https://docs.manim.community/en/v0.1.1/reference/manim.mobject.svg.text_mobject.Text.html#manim.mobject.svg.text_mobject.Text). Did you try that?

Also, for me, the link you posted doesn't https://svgshare.com/s/SHu, suggest you to upload to Github putting it in a zip file.

**Comment by naveen521kk** [comment]
Closing this because of no response.
