### ISSUE TITLE
tipa Package Breaks \implies

### ISSUE THREAD

**Issue by sudgy** [ManimCommunity/manim#866]
When trying to run this simple scene:
```python
class Test(Scene):
    def construct(self):
        test = MathTex("\\implies")
```
the LaTeX compiling fails with the error `LaTeX Warning: Command \; invalid in math mode on input line 27.`  Removing the `tipa` package from the preamble fixes the issue, so it seems to be related to that.  Here is the full LaTeX log:
 [a96029e05ff38351.log](https://github.com/ManimCommunity/manim/files/5718500/a96029e05ff38351.log)

<details><summary>System Details</summary>
- OS: Arch Linux
</details>

<details><summary>LaTeX details</summary>

+ LaTeX distribution TeX Live 2020/Arch Linux
+ Installed LaTeX packages: I have no idea, tlmgr didn't work, and pacman installed everything for me.
</details>

## Additional comments

I'm not the only one with this issue, it was first brought up on Discord [here](https://discord.com/channels/581738731934056449/582403919754297363/789623865188810752).

**Comment by eulertour** [comment]
I can reproduce the problem with `MathTex("\\implies")`, but `MathTex("x \\imples y")` or just `MathTex("\\imples y")` works as expected. It seems to be [this problem](https://tex.stackexchange.com/a/505705) and the solution described there, using `\usepackage[safe]{tipa}`, makes the first example work.

If you ctrl-f "safe" in [the tipa documentation](http://texdoc.net/texmf-dist/doc/fonts/tipa/tipaman.pdf) you'll see a list of commands that tipa had secretly been overwriting but `\\implies` isn't listed there, which means there's a good chance tipa may be changing even more commands without our knowledge.

It should be okay to change the line to `\usepackage[safe]{tipa}` and leave it at that, but looking more at the documentation it seems like tipa is actually a pretty niche package in the first place. It'd make more sense to me to delegate inclusion of tipa to an opt-in API and stick with the other packages.

**Comment by behackl** [comment]
I agree that `tipa` should be removed from the default LaTeX template. I think dealing with this would be a good first contribution.

**Comment by behackl** [comment]
I think this can be closed since tipa has been removed from the TeX template we use by default.
