### ISSUE TITLE
Removing artifacts in default.cfg and new option to change frame rate

### ISSUE THREAD

**Issue by kolibril13** [ManimCommunity/manim#870]
https://github.com/ManimCommunity/manim/blob/c560ab397de70065dfae8af8474fe598158b464f/manim/_config/default.cfg#L98-L103
I think the sentence "overriding values are found in the corresponding sections" does not make sense anymore.
Further, let's say I want to have a video with 2 fps.
How do I do this at the moment?
Because when I run this script:
```python
class Test(Scene):
    def construct(self):
        config.frame_rate=2
        dot = Dot().set_color(GREEN)
        self.add(dot)
        self.wait(1)
```
I have a video that is 30 seconds long. So it actually changed to 2 fps, but self.wait(1) corresponds not to 1 second anymore, but to 30 seconds.

Update:
When changing the frame rate here: https://github.com/ManimCommunity/manim/blob/c560ab397de70065dfae8af8474fe598158b464f/manim/constants.py#L156
self.wait(1) is working properly with one second.

**Comment by leotrs** [comment]
These two sound like entirely different things to me - am I missing anything? What is the reason to report these two in the same issue?

**Comment by kolibril13** [comment]
It is both related to frame_rate from the config class.
But I can also make a seperate issue for the second problem with the changing scene length if that would simplify the discussion

**Comment by leotrs** [comment]
It setting frame_rate = 2 actually gives you 2 frames per second then this sounds like there is a problem with self.wait. cc @eulertour

**Comment by behackl** [comment]
Setting `config.frame_rate = 2` inside of `construct` is "too late"; global settings like that should be made outside of the scene – and then `self.wait` behaves as expected.
