### ISSUE TITLE
Multiple play arguments not working with the new syntax introduced with #881

### ISSUE THREAD

**Issue by ChristianCoenen** [ManimCommunity/manim#885]
## Description of bug / unexpected behavior
Was just starting to refactor my code base to match the new syntax introduced in #881 (great improvement btw, l like it!) when I saw that only the first animation is executed while the second is completely ignored.

## Expected behavior
To rotate and move the object at the same time.

## How to reproduce the issue
```py
from manim import *

class Test(Scene):
    def construct(self):
        r = Rectangle()
        r2 = Rectangle().to_corner(RIGHT + UP)
        self.play(r.animate.move_to(r2), r.animate.rotate(-PI / 2))
```

**Comment by behackl** [comment]
Thank you for your report! I can confirm that this was possible before #881, seems like we might need to bring back some logic in `Scene.compile_animations`.

I'd consider this a blocker; if possible I'd like to avoid releasing `v.0.2.0` with this bug present.

/CC @eulertour

**Comment by friedkeenan** [comment]
Oh, this might be because every time the .animate attribute is used, it generates a new target for the mobject

**Comment by behackl** [comment]
I've proposed a fix in #887. Locally, it seemed to solve the problem; please check it out @friedkeenan @ChristianCoenen

**Comment by ChristianCoenen** [comment]
@behackl Thanks for the quick fix, solves the problem for me.

**Comment by eulertour** [comment]
I don't like the idea of playing two animations on the same mobject simultaneously in the same play call. It makes the behavior of every animation dependent on the animations it's animated with.

I'm fine with syntax like `r.animate().move_to(...).rotate(...)` returning a single animation so that we avoid relying on intermediate states of an individual play call.

**Comment by ChristianCoenen** [comment]
This would also be a solution that works for my codebase.

Just want to raise awareness that animations like the following might be problematic in the future (currently, this isn't working as intended anyway, so it's not a big deal):

```python
from manim import *

class Test(Scene):
    def construct(self):
        r = Rectangle()
        r2 = Rectangle().to_corner(RIGHT + UP)
        self.play(
            AnimationGroup(r.animate.move_to(r2), Indicate(r2), r.animate.rotate(-PI / 2), lag_ratio=0.5, run_time=5)
        )
```

**Comment by eulertour** [comment]
Yes, there should probably be a check somewhere that the same mobject isn't animated twice in one play call.

**Comment by eulertour** [comment]
On second thought I don't know if it makes sense to add a check for that since it would require searching all of the mobjects in the scene including submobjects. It's probably more effort than it's worth.

**Comment by behackl** [comment]
With #889 we have implemented a different sytax able to handle this.
