### ISSUE TITLE
Previous issues

### ISSUE THREAD

**Issue by leotrs** [ManimCommunity/manim#9]
There are a number of open issues on the [original manim repo](https://github.com/3b1b/manim/issues). A good way to determine a path moving forward for this community fork is to go over those issues and copy them here (the useful ones at least) so that they can be assigned to someone and we can do something about them.

This will also signal to end users that there is a lot of activity on this repository.

**Comment by eulertour** [comment]
The low hanging fruit here is a way to verify the manim install. Basically something to dry-run a Scene, ensure that the bare minimum to render successfully is actually installed, and give a helpful error like LaTeX/FFmpeg isn't installed, media directory isn't writable, etc.

**Comment by leotrs** [comment]
@eulertour good suggestion, forked it into its own issue. 

Please keep suggesting here old issues that should be copied into the manim-community repo.

**Comment by safinsingh** [comment]
Possible PRs to look into:
 - Fixing a broken stroke width for ZoomedScene: https://github.com/3b1b/manim/pull/1073
 - Add custom CTeX capabilities: https://github.com/3b1b/manim/pull/745
 - Add option to fix SVGs with Cairo: https://github.com/3b1b/manim/pull/330
 - Fix NumberPlane construction: https://github.com/3b1b/manim/pull/909
 - Add Physics Engine support (possibly as an add-on?): https://github.com/3b1b/manim/pull/818
 - Add dependency check script: https://github.com/3b1b/manim/pull/636

**Comment by Tony031218** [comment]
> Possible PRs to look into:
> 
>  - Fixing a broken stroke width for ZoomedScene: https://github.com/3b1b/manim/pull/1073
> 
>  - Add custom CTeX capabilities: https://github.com/3b1b/manim/pull/745
> 
>  - Add option to fix SVGs with Cairo: https://github.com/3b1b/manim/pull/330
> 
>  - Fix NumberPlane construction: https://github.com/3b1b/manim/pull/909
> 
>  - Add Physics Engine support (possibly as an add-on?): https://github.com/3b1b/manim/pull/818
> 
>  - Add dependency check script: https://github.com/3b1b/manim/pull/636

Also 3b1b#1071 This pr fixes some serious bugs of `Text()` and `Code()`, but the effect of some of the latter commits is not good.  Can we keep only the part of the commits that fixed the bugs before?

**Comment by NavpreetDevpuri** [comment]
> Also [3b1b#1071](https://github.com/3b1b/manim/pull/1071) This pr fixes some serious bugs of `Text()` and `Code()`, but the effect of some of the latter commits is not good. Can we keep only the part of the commits that fixed the bugs before?

which commit's effect is not good ?

**Comment by Tony031218** [comment]
> which commit's effect is not good ?

The last few are to resolve Transform's commits.
I don't think they are necessary, and they are more difficult to understand and not easy to use.

**Comment by NavpreetDevpuri** [comment]
I think they are necessary because 
* Resolve Transforms
* Open a ability to access chars differently as visible sub-mobjects.
* Open new modifications something like `Text.words` and `Text.lines`. I will do that. 
* Add for functionalities to `Text()`

As you said "more difficult to understand" i want to ask you that what if [Grant Sanderson](https://github.com/3b1b) thinks the same Did he able to make manim? there are so many things that seems difficult to understand.

Is using `Text.chars` or `remove_invisible_chars()` seems difficult ?

**Comment by leotrs** [comment]
Thanks everyone for bringing up all these previous issues. I think this issue has achieved the purpose of gathering all of these. So I'm going to ask the participants @NavpreetDevpuri @safinsingh @eulertour @Tony031218 to feel free to take any of those issues you have listed and open them again here in this repo. We can come back to this list for future reference. But I'm closing this for now.

In particular, @Tony031218 and @NavpreetDevpuri please continue your discussion in a new issue dedicated to 3b1b#1071  :)

**Comment by alxmz2** [comment]
manim 0.17.3 does not recognize the function remove_invisible_chars.

There is a bug in text_mobject.py

I fixed it by adding it in line 52:

__all__ = ["Text", "Paragraph", "MarkupText", "register_font", "remove_invisible_chars"]
