### ISSUE TITLE
Sound in manimce

### ISSUE THREAD

**Issue by Analytical1703** [ManimCommunity/manim#902]
I want to add sound to my video in manimce like manim by 3b1b 

I use the following code -: 

`self.add_sound(" sound file name in assets folder", gain = value)`

But it's giving an error in manimce

![20210102172136](https://user-images.githubusercontent.com/76893489/103471739-ab14a200-4da9-11eb-978d-74ff95788ee5.jpg)

I think there will be some other syntax in manimce.

Please resolve this!!

**Comment by leotrs** [comment]
Hello @Analytical1703 and thanks for reporting.

Could you please use the rest of the issue template? In particular, we *need* to know what version of manim (and its dependencies) you are using. Otherwise there is no way of helping you.
