### ISSUE TITLE
Feature request: Subtitle timings

### ISSUE THREAD

**Issue by clarfonthey** [ManimCommunity/manim#910]
## Description of proposed feature

It would be fairly useful to have animation options that aren't for actually displaying anything, but for marking the timestamps in an animation with text that can be used to export subtitles.

Since a lot of videos made in manim are intended to include additional voiceover, this would make timing subtitles, or at least adding subtitles for the intended script to videos, a lot easier. Even if the actual voiceover doesn't 100% match the script, it's a lot easier to tweak the words and the timing than to make them from scratch.

Alternatively, folks who don't do voiceover but want to add subtitles as an alternative can still do so.

## How can the new feature be used?

I'm imagining an implementation similar to:

1. Animations can set the subtitle text or clear it (e.g. end the latest subtitle), which would happen as soon as the animation starts.
2. There is a dedicated animation `Subtitle(text)` which sets the subtitle to the given string, or clears it if passed `None`.
3. Alternatively, there could be dedicated `set_subtitle` and `clear_subtitle` methods since setting a subtitle takes zero time.

This way, you can still use the existing animation system to leverage adding subtitles, e.g. `wait` still works as expected and adding a subtitle animation alongside other animations would set it as soon as those animations are started.  

## Additional comments

The output would probably make the most sense as an srt file since the videos are output as MP4. This is a relatively simple format where each line includes a start/end timestamp for a subtitle and the text. The lines could be written out whenever a subtitle is cleared or changed, or the video ends.

**Comment by leotrs** [comment]
Hello and thanks for the suggestion!

I must say that my position is a "soft no". I am not an expert, but I believe there are ways of adding subtitles that are external to how the video is rendered. For example, in most playback software that accepts subtitles, you have the option to turn subtitles off and on. However, in what you propose, there is no way of turning subtitles off and on once the video is rendered with subtitles. So if anyone is really serious about adding subtitles, I would encourage them to look for other ways of adding them after the video is rendered.

However, if others think this would be useful, I could see this being a manim plugin.

**Comment by clarfonthey** [comment]
To clarify, this would specifically be for closed subtitles (i.e. not directly rendered) rather than open subtitles (rendered onto the video itself). Since it'd be storing the subtitles in a separate file the main benefit is to export timing information from the rendered animation.

**Comment by leotrs** [comment]
Oh okay, that makes more sense. 

If I'm not mistaken, this would depend on the underlying renderer. For example, I would assume there is a way of telling ffmpeg to add closed captions and/or telling ffmpeg about the timing information for the closed captions. If that's the case, then this would probably be more than a plugin as it would have to change how the rendering step happens...

**Comment by clarfonthey** [comment]
(I also suggest in the post that it could just output as a .srt file, which is just a text file and super easy to do by hand. Most video players nowadays will automatically read this if it's in the same folder.)

**Comment by leotrs** [comment]
Is that all that needs to be done? Or does the actual mp4 file need to include some information as well? (Sorry I didn't see that part first!)

**Comment by clarfonthey** [comment]
No worries! I am also guilty of commenting without reading everything first. :p 

And… yeah, pretty much. There are more complicated video containers like mkv that can include the subtitles with the video, but in a lot of cases it's sufficient to just output an SRT file next to the video with the same name and the extension replaced with .srt.

I wasn't 100% right on the timings just being individual lines, but it's still extremely straightforward. Since it's just text you don't need any fancy code to generate it, just a few print statements. See this page on wikipedia: https://en.wikipedia.org/wiki/SubRip#File_format

**Comment by leotrs** [comment]
In that case, then I do think we can make this part of the core library. 

I agree with you that the interface should look like an Animation.

The part that needs a bit of thinking would be the actual writing of the file. I suggest we create a new class SRTWriter or CCWriter or something like that. And all of the functionality can be imported as `from manim import captions` and then do `captions.clear()`, or something similar.
