### ISSUE TITLE
Manim cannot render scenes with latex in it

### ISSUE THREAD

**Issue by aman17009** [ManimCommunity/manim#911]
## Description of bug / unexpected behavior
I downloaded ManimCE and Manim-Latex using Chocolatey in my Windows 10 64 bit machine by following the steps given in manim.community website. Unfortunately, I am not able to render any  video which has Latex in it. If the code does not contain any latex then everything works fine.

Whenever I try to render a video which has Latex, the file manim/utils/tex_file_writing.py raises - "ValueError : Latex error converting to dvi. See the log output above or in the lig file : media/Tex/{name of the file}.log". When I go to the given file location there is no log file there. There are three files there - a text document, a tex document and an AUX file. I discovered this issue while trying to render the MovingFrameBox example given in the example gallery of manim.community website.

## Expected behavior
Manim should have rendered the animation.

## How to reproduce the issue
First of all install ManimCE and Manim-latex using Chocolatey on Windows 10 and then try to render MovingFrameBox example given in the example gallery of manim.community website.

<details><summary>Code for reproducing the problem</summary>

```py
class MovingFrameBox(Scene):
    def construct(self):
        text=MathTex(
            "\\frac{d}{dx}f(x)g(x)=","f(x)\\frac{d}{dx}g(x)","+",
            "g(x)\\frac{d}{dx}f(x)"
        )
        self.play(Write(text))
        framebox1 = SurroundingRectangle(text[1], buff = .1)
        framebox2 = SurroundingRectangle(text[3], buff = .1)
        self.play(
            ShowCreation(framebox1),
        )
        self.wait()
        self.play(
            ReplacementTransform(framebox1,framebox2),
        )
        self.wait()
```

</details>

## Additional media files

<details><summary>Images/GIFs</summary>

</details>

## Logs
<details><summary>Terminal output</summary>

```
PASTE HERE OR PROVIDE LINK TO https://pastebin.com/ OR SIMILAR
```

</details>

## System specifications

<details><summary>System Details</summary>

- OS (with version, e.g Windows 10 v2004 or macOS 10.15 (Catalina)):
- RAM:
- Python version (`python/py/python3 --version`):
- Installed modules (provide output from `pip list`):
```
PASTE HERE
```
</details>

<details><summary>LaTeX details</summary>

+ LaTeX distribution (e.g. TeX Live 2020):
+ Installed LaTeX packages:

</details>

<details><summary>FFMPEG</summary>

Output of `ffmpeg -version`:

```
PASTE HERE
```
</details>

**Comment by behackl** [comment]
Sounds like there is a problem with your LaTeX installation. Can you please post the full traceback returned by Manim when you try to render the scene above?

What does `where dvisvgm` return when run within `cmd.exe`?

**Comment by aman17009** [comment]
Today, I uninstalled the Manim-Latex package by running the command - "choco uninstall manim-latex' and then installed the package again by running the "choco install manim-latex " command. I got the following errors while doing so. When I installed the package for first time a few days back I got these exact same errors.
![hola 1](https://user-images.githubusercontent.com/77117373/104034073-68fabe80-51f6-11eb-9d25-4c22fa89ec2f.PNG)
![hollalala 2](https://user-images.githubusercontent.com/77117373/104034114-787a0780-51f6-11eb-9b54-9947b23d27fd.PNG)
![holalal 3](https://user-images.githubusercontent.com/77117373/104034138-82036f80-51f6-11eb-9818-e9af14b6ba86.PNG)

When I ran the command "where dvisvgm" I got the following response from cmd.exe "C:\tools\TinyTeX\bin\win32\dvisvgm.exe"

However, despite these error, for some reason, the problem was solved. Manim is finally rendering the MovingFrameBox animation.

**Comment by leotrs** [comment]
cc @naveen521kk

**Comment by behackl** [comment]
It looks red and scary, but the output actually is not an error: you can see the return code ("0") in the end, indicating that everything is okay.

Maybe @naveen521kk can have a short look whether everything is okay with the way manim-latex is installing -- but then this can be closed.

**Comment by naveen521kk** [comment]
Yeah chocolatey mixing stdout and stderr and this happens. It's kinda expected for this to happen but as @behackl pointed out there is a `0` at the end which says this are working no worries.
