### ISSUE TITLE
Bipartite graph mobject

### ISSUE THREAD

**Issue by noamzaks** [ManimCommunity/manim#913]
## Enhancement proposal
Add support for bipartite graphs in the Graph mobject (or create a BipartiteGraph mobject) which lays out the vertices in two columns, e.g.

https://user-images.githubusercontent.com/63877260/104060416-8718ec80-51ff-11eb-9a1f-47487da8c162.mp4

## Additional comments
I was able to implement this in two ways: either create a Graph mobject from a networkx graph while retaining the data, like so (this is in the mobject/graph.py file):
```python
def __init__(
        self,
        vertices: List[Hashable],
        edges: List[Tuple[Hashable, Hashable]],
        labels: bool = False,
        label_fill_color: str = BLACK,
        layout: Union[str, dict] = "spring",
        layout_scale: float = 2,
        layout_config: Union[dict, None] = None,
        vertex_type: "Mobject" = Dot,
        vertex_config: Union[dict, None] = None,
        edge_type: "Mobject" = Line,
        nx_graph: nx.classes.graph.Graph = None, # ADDED optional parameter to retain the bipartite data
        edge_config: Union[dict, None] = None,
    ) -> None:
        VMobject.__init__(self)
        if nx_graph is None:
            nx_graph = nx.Graph()
            nx_graph.add_nodes_from(vertices)
            nx_graph.add_edges_from(edges)
            self._graph = nx_graph
        else:
            self._graph = nx_graph
```
and add the "bipartite" layout option like so (the my_bipartite_pos_func is exactly a layout matching from nodes to positions):
```python
elif layout == "bipartite":
    def my_bipartite_pos_func(G: nx.classes.graph.Graph) -> dict:
        result = {}

        left = {n for n, d in G.nodes(data=True) if d["bipartite"] == 0}
        right = {n for n, d in G.nodes(data=True) if d["bipartite"] == 1}  # = set(G) - left

        left_jumps = 1 / len(left)
        right_jumps = 1 / len(right)

        i = 0
        for l in left:
            result[l] = -RIGHT-UP + 2 * UP * i * left_jumps
            i += 1

        i = 0
        for r in right:
            result[r] = RIGHT-UP + 2 * UP * i * right_jumps
            i += 1

        return result

    self._layout = my_bipartite_pos_func(nx_graph)
else:
    raise ValueError(
        f"The layout '{layout}' is neither a recognized automatic layout, "
        "nor a vertex placement dictionary."
    )
```
then in the construct method:
```python
G = nx.Graph()
G.add_nodes_from([0, 1, 2], bipartite=0)
G.add_nodes_from([3, 4, 5], bipartite=1)
G.add_edges_from([(0, 3), (1, 5), (1, 4)])
graph = Graph(list(G.nodes), list(G.edges), nx_graph=G, layout="bipartite")
```

Perhaps a neater way would be like so:
```python
class BipartiteGraph(Graph):
    def __init__(self, nx_graph: nx.classes.graph.Graph):
        def my_bipartite_pos_func(G: nx.classes.graph.Graph) -> dict:
            result = {}

            left = {n for n, d in G.nodes(data=True) if d["bipartite"] == 0}
            right = {n for n, d in G.nodes(
                data=True) if d["bipartite"] == 1}  # = set(G) - left

            left_jumps = 1 / len(left)
            right_jumps = 1 / len(right)

            i = 0
            for l in left:
                result[l] = -RIGHT + 2 * UP * i * left_jumps
                i += 1

            i = 0
            for r in right:
                result[r] = RIGHT + 2 * UP * i * right_jumps
                i += 1

            return result
        super().__init__(list(nx_graph.nodes), list(nx_graph.edges), layout=my_bipartite_pos_func(nx_graph))
```
which in turn results in the construct method:
```python
G = nx.Graph()
G.add_nodes_from([0, 1, 2], bipartite=0)
G.add_nodes_from([3, 4, 5], bipartite=1)
G.add_edges_from([(0, 3), (1, 5), (1, 4)])
graph = BipartiteGraph(G)
```

Another possible implementation would be similar to the new @staticmethod from_networkx:
```python
@staticmethod
def from_bipartite(nxgraph: nx.classes.graph.Graph, **kwargs) -> "Graph":
    """Build a :class:`~.Graph` with a 2-column layout from a given ``networkx`` bipartite graph.
    
    Parameters
    ----------
    
    nxgraph
        A ``networkx`` graph.
    **kwargs
        Keywords to be passed to the constructor of :class:`~.Graph`.
    
    Examples
    --------
    
    .. manim:: ImportBipartiteGraph
    
        import networkx as nx
    
        nxgraph = nx.Graph()
        nxgraph.add_nodes_from([0, 1, 2], bipartite=0)
        nxgraph.add_nodes_from([3, 4, 5], bipartite=1)
        nxgraph.add_edges_from([(0, 3), (1, 5), (1, 4)])
    
        class ImportBipartiteGraph(Scene):
            def construct(self):
                G = Graph.from_bipartite(nxgraph, layout_scale=3.5)
                self.play(ShowCreation(G))

    """
    return Graph(list(nxgraph.nodes), list(nxgraph.edges), **kwargs)
```

**Comment by behackl** [comment]
Thank you for your proposal, I definitely think we should support something like that.

If we go for extending the original constructor to support `layout="bipartite"`, I would prefer to add a keyword `partitions=None` from which the partition data is read instead of passing a networkx graph; then we can either communicate the partitions to networkx to build the layout for us, or we simply do it ourselves. (Probably the former is better.)

This also reminds me that I would really like to see support for a hierarchical layout (for trees). I feel that for those, expanding the constructor of `Graph` once again to allow for `layout="tree"`, and then an additional keyword `root_vertex=None` to specify the root would be the most natural interface...

Another, completely different approach would be a factory-type approach, where we provide an interface like `graphs.bipartite_graph(partition1, partition2, edges, **kwargs)` (which could then house also several other special graphs and graph classes; e.g. `graphs.complete_graph(n)`, `graphs.complete_partite_graph(k, [n1, n2, ..., nk])`, `graphs.petersen_graph()`, and so on). But I somehow feel that these factory-type interfaces are somewhat nicer for special graphs where there is no need for specifying the edges; so `graphs.complete_partite_graph` would be fine, but I feel `graphs.bipartite_graph(...)` is a bit clunky -- I also would not really want to see `graphs.tree(...)`. So, for your proposal I am leaning towards modifying the `Graph` constructor.

What do you think? Would you also be okay with having `Graph` look at a passed `partitions` vertex list, instead of passing the entire networkx graph?

**Comment by noamzaks** [comment]
Thanks for the quick reply!
After searching again for networkx bipartite layouts, it turns out there is a built in one.
Here's the modified code for the Graph mobject constructor (also available with diff highlighting [here](https://github.com/noamzaks/manim/commit/64bfa7fca72229d568dfe16dd2b16a520377a16c)):
```python
def __init__(
        self,
        vertices: List[Hashable],
        edges: List[Tuple[Hashable, Hashable]],
        labels: bool = False,
        label_fill_color: str = BLACK,
        layout: Union[str, dict] = "spring",
        layout_scale: float = 2,
        layout_config: Union[dict, None] = None,
        vertex_type: "Mobject" = Dot,
        vertex_config: Union[dict, None] = None,
        edge_type: "Mobject" = Line,
        partitions: List[List[Hashable]] = None,
        edge_config: Union[dict, None] = None,
    ) -> None:
        VMobject.__init__(self)

        nx_graph = nx.Graph()
        nx_graph.add_nodes_from(vertices)
        nx_graph.add_edges_from(edges)
        self._graph = nx_graph

        automatic_layouts = {
            "circular": nx.layout.circular_layout,
            "kamada_kawai": nx.layout.kamada_kawai_layout,
            "planar": nx.layout.planar_layout,
            "random": nx.layout.random_layout,
            "shell": nx.layout.shell_layout,
            "spectral": nx.layout.spectral_layout,
            "bipartite": nx.layout.bipartite_layout,
            "spiral": nx.layout.spiral_layout,
            "spring": nx.layout.spring_layout,
        }

        if layout_config is None:
            layout_config = {}

        if isinstance(layout, dict):
            self._layout = layout
        elif layout in automatic_layouts and layout != "random":
            if layout == "bipartite":
                if not partitions or len(partitions) == 0:
                    raise ValueError(
                        "The bipartite layout requires specification of all the vertices in one side"
                    )
                layout_config["nodes"] = partitions[0]
            self._layout = automatic_layouts[layout](
                nx_graph, scale=layout_scale, **layout_config
            )
            self._layout = dict(
                [(k, np.append(v, [0])) for k, v in self._layout.items()]
            )
        elif layout == "random":
            # the random layout places coordinates in [0, 1)
            # we need to rescale manually afterwards...
            self._layout = automatic_layouts["random"](
                nx_graph, **layout_config)
            for k, v in self._layout.items():
                self._layout[k] = 2 * layout_scale * (v - np.array([0.5, 0.5]))
            self._layout = dict(
                [(k, np.append(v, [0])) for k, v in self._layout.items()]
            )
        else:
            raise ValueError(
                f"The layout '{layout}' is neither a recognized automatic layout, "
                "nor a vertex placement dictionary."
            )
```
It works with the following example:
```python
from manim import *
import networkx as nx

G = nx.Graph()
G.add_nodes_from([0, 1, 2, 3], bipartite=0)
G.add_nodes_from([4, 5, 6, 7], bipartite=1)
G.add_edges_from([(0, 4), (0, 6), (1, 6), (2, 5), (3, 7)])


class Test(Scene):
    def construct(self):
        graph = Graph(list(G.nodes), list(G.edges), layout="bipartite", partitions=[
                      {n for n, d in G.nodes(data=True) if d["bipartite"] == 0}])
        self.play(ShowCreation(graph))
```

I also added documentation (is it formatted correctly?) in the end of the Graph documentation 
```
    You can also lay out a bipartite graph on two columns by specifying 
    a list of the vertices on one side and choosing the bipartite layout.

    .. manim:: BipartiteGraph
        :save_last_frame:

        class BipartiteGraph(Scene):
            def construct(self):
                G = nx.Graph()
                G.add_nodes_from([0, 1, 2, 3], bipartite=0)
                G.add_nodes_from([4, 5, 6, 7], bipartite=1)
                G.add_edges_from([(0, 4), (0, 6), (1, 6), (2, 5), (3, 7)])
                graph = Graph(list(G.nodes), list(G.edges), layout="bipartite", partitions=[
                      {n for n, d in G.nodes(data=True) if d["bipartite"] == 0}])
```

It still remains to implement more than 2 partitions and the trees. If there were 3, would you lay them in 3 columns or in a triangle? 

About the other special graphs, I'm guessing networkx has these nice constructors; For example [here](https://networkx.org/documentation/stable//reference/generated/networkx.generators.classic.complete_graph.html) and many many more [here](https://networkx.org/documentation/stable//reference/generators.html). What do you think?

**Comment by noamzaks** [comment]
After another quick scan of networkx documentation, [this](https://networkx.org/documentation/stable/reference/drawing.html#module-networkx.drawing.layout) might be worthwhile (specifically multipartite_layout for more than 2 partitions). Looks to me like it's the 3 column approach, and not the triangle (apropos in the example they use the method `nx.complete_multipartite_graph(28, 16, 10)`).

**Comment by behackl** [comment]
I was not suggesting that we should include all of that at once; I think a pull request enabling `layout="bipartite"` would be fine as a first step (and probably easier to review and merge, anyways :-)).

At a first glance, both the code and the example look very good to me. Can I ask you to send a pull request from your repository to ours containing these changes? I'll take a closer look at it then (and thank you for your contribution in advance!) --  I'd probably just simplify the example a little bit, but that is easier to discuss on a pull request.

Excellent work!
