### ISSUE TITLE
More details in the Breaking Changes

### ISSUE THREAD

**Issue by dbitouze** [ManimCommunity/manim#918]
## Enhancement proposal
Give more details in the Breaking Changes of the [0.2.0 version](https://docs.manim.community/en/v0.2.0/changelog.html#v0-2-0) of Community Manim.

For instance, with this version, this [animation](https://github.com/Elteoremadebeethoven/MyAnimations/blob/master/logo_scene/2d_graph_scene.py) provided by Elteoremadebeethoven doesn't compile any more. I guess this is due to the removal of the "old syntax for animating `mobject` methods by passing the methods and arguments to `self.play"` but I have absolutely no idea on how to adapt to the new syntax e.g. [these lines](https://github.com/Elteoremadebeethoven/MyAnimations/blob/f4504958c87a8b28fc0dadbb8c3eedf6e753dbf8/logo_scene/2d_graph_scene.py#L86-L88).

**Comment by behackl** [comment]
> but I have absolutely no idea on how to adapt to the new syntax e.g. these lines.

Not at all. As described in our changelog, only calls like `self.play(my_mobject.method, method_arg)` do not work any longer and have to be written using the new `.animate` syntax. In the code you posted, there is just one such play call, namely

https://github.com/Elteoremadebeethoven/MyAnimations/blob/f4504958c87a8b28fc0dadbb8c3eedf6e753dbf8/logo_scene/2d_graph_scene.py#L169

should become

```py
            input_tracker_p2.animate.set_value(input_tracker_p1.get_value()),
```

All other play calls look fine to me.

If you have an explicit suggestion how the description in the breaking changes section can be improved, I'm happy to discuss it -- but from your current proposal it is not clear to me what exactly you would like to have improved.

**Comment by dbitouze** [comment]
> should become
> 
> ```python
>             input_tracker_p2.animate.set_value(input_tracker_p1.get_value()),
> ```

Unfortunately, it still returns an error:

```python
manim 2d_graph_scene.py Thumbnail      
[01/09/21 16:23:02] ERROR                                                                                                                                                                         \module_ops.py\:65
                                There are no scenes inside that module
```

>If you have an explicit suggestion how the description in the breaking changes section can be improved, I'm happy to discuss it -- but from your current proposal it is not clear to me what exactly you would like to have improved.

To be honest, I haven't any suggestion because I was (I am) a bit lost:  I still have absolutely no idea on how to adapt to the new syntax in the general cases: in the current one, I had the impression all the `self.play` had to be changed (not "[a]ll other play calls look fine to me." :smile:) and, in the one line 168, I wouldn't have guessed the line 169 was the one to adapt.

**Comment by behackl** [comment]
Did you change the import line to `from manim import *` as well? It seems to me that there might be a problem with different Manim versions or so.

The breaking change just concerns calls to play that passed first the method of an mobject, and then the corresponding arguments -- because the logic for handling a call like `self.play(ShowCreation(my_circle), my_square.shift, LEFT)` was very complicated. Now all arguments in `self.play` have to be animations (`self.play(ShowCreation(my_circle), my_square.animate.shift(LEFT)`) which makes the underlying logic a lot easier, and the interface cleaner.

**Comment by dbitouze** [comment]
> Did you change the import line to `from manim import *` as well?

Sorry, I don't see what you're talking about. At the beginning of the [`2d_graph_scene.py`](https://github.com/Elteoremadebeethoven/MyAnimations/blob/master/logo_scene/2d_graph_scene.py), I see:
```python
from manimlib.imports import *
```
but I guess that's not what you mean.

> It seems to me that there might be a problem with different Manim versions or so.

Highly possible, and I don't know how to clean up my computer :confused: 

> The breaking change just concerns calls to play that passed first the method of an mobject,

I guess what I'm missing is what "method of an mobject" does mean. If you have some pointers, they would be very welcome.

> and then the corresponding arguments -- because the logic for handling a call like `self.play(ShowCreation(my_circle), my_square.shift, LEFT)` was very complicated. Now all arguments in `self.play` have to be animations (`self.play(ShowCreation(my_circle), my_square.animate.shift(LEFT)`) which makes the underlying logic a lot easier, and the interface cleaner.

If you say so :grin:

**Comment by behackl** [comment]
> > Did you change the import line to `from manim import *` as well?
> 
> Sorry, I don't see what you're talking about. At the beginning of the [`2d_graph_scene.py`](https://github.com/Elteoremadebeethoven/MyAnimations/blob/master/logo_scene/2d_graph_scene.py), I see:
> 
> ```python
> from manimlib.imports import *
> ```
> 
> but I guess that's not what you mean.
> 

That *is* what I mean: if you want to run this code with the community version of Manim, you will have to change this line to `from manim import *`.

> > It seems to me that there might be a problem with different Manim versions or so.
> 
> Highly possible, and I don't know how to clean up my computer 😕
> 

You could visit our Discord and post in one of the manim-help channels -- it is a bit easier to figure out what is wrong there.

> > The breaking change just concerns calls to play that passed first the method of an mobject,
> 
> I guess what I'm missing is what "method of an mobject" does mean. If you have some pointers, they would be very welcome.
> 

Methods are special functions that are, in some sense, attached to instances of classes. In the example above, `my_square` is an instance of the Mobject class, and `my_square.shift` is one of the objects methods -- which you can run in order to shift the object in the scene.

I don't know what your background in programming is, but it might be a good idea to revisit object-oriented programming in Python, then the terminology should be a bit clearer. :-)

**Comment by dbitouze** [comment]
> That _is_ what I mean: if you want to run this code with the community version of Manim, you will have to change this line to `from manim import *`.

Ah, OK. It does compile now and the animations are created, despite an error and some warnings (see below). The error is also related to the Breaking Changes:

> ERROR    CONFIG has been removed from ManimCommunity. Please use keyword arguments instead.

And, indeed, the file contains:
```python
class Thumbnail(GraphScene):
    CONFIG = {
        "y_max": 8,
        "y_axis_height": 5,
    }
```
but I must admit the hint in the Changelog:

>Remove all `CONFIG` dictionaries and all calls to `digest_config` and allow passing options directly to the constructor of the corresponding classes (pull request 783).
>
> Practically, this means that old constructions using `CONFIG` like:
>
>```python
>class SomeMobject(Thing):
>   CONFIG = {
>        "my_awesome_property": 42
>    }
>```
>where corresponding objects were then instantiated as `my_mobject = SomeMobject()` should now be created simply using `my_mobject = SomeMobject(my_awesome_property=42)`.

is not that clear for me: what "`my_mobject" for e.g. `"y_max": 8` and where should it be used in the rest of the file?

One of the warning is:

> WARNING  Option -l is deprecated please use the --quality/-q flag.

So I guess the command line in [the "Your first Scene" section](https://docs.manim.community/en/v0.2.0/tutorials/quickstart.html#your-first-scene) of the Manim Community Overview should be changed, but I'm not sure where I should report this.

> > > It seems to me that there might be a problem with different Manim versions or so.
> > 
> > Highly possible, and I don't know how to clean up my computer confused
> 
> You could visit our Discord

Sigh... not a big fan of Discord (privacy issues, etc.)

>  and post in one of the manim-help channels -- it is a bit easier to figure out what is wrong there.

Ah?! Why?

> > > The breaking change just concerns calls to play that passed first the method of an mobject,
> > 
> > I guess what I'm missing is what "method of an mobject" does mean. If you have some pointers, they would be very welcome.
> 
> Methods are special functions that are, in some sense, attached to instances of classes. In the example above, `my_square` is an instance of the Mobject class, and `my_square.shift` is one of the objects methods -- which you can run in order to shift the object in the scene.
> 
> I don't know what your background in programming is,

In LaTeX, quite reasonable :smile:. In Python, I'm a hobbyist.

> but it might be a good idea to revisit object-oriented programming in Python, then the terminology should be a bit clearer. :-)

OK, thanks!

**Comment by behackl** [comment]
> > where corresponding objects were then instantiated as `my_mobject = SomeMobject()` should now be created simply using `my_mobject = SomeMobject(my_awesome_property=42)`.
> 
> is not that clear for me: what "`my_mobject" for e.g. `"y_max": 8` and where should it be used in the rest of the file?

The interface for passing keyword arguments to the scene itself is, unfortunately, not the cleanest yet. Have a look at how this is done in our example gallery: https://docs.manim.community/en/v0.2.0/examples.html#plotting-with-manim

> 
> One of the warning is:
> 
> > WARNING  Option -l is deprecated please use the --quality/-q flag.
> 
> So I guess the command line in [the "Your first Scene" section](https://docs.manim.community/en/v0.2.0/tutorials/quickstart.html#your-first-scene) of the Manim Community Overview should be changed, but I'm not sure where I should report this.
> 

This has already been fixed and will be included in the next release: https://docs.manim.community/en/latest/tutorials/quickstart.html

> > You could visit our Discord
> 
> Sigh... not a big fan of Discord (privacy issues, etc.)
> 

Fair, it is of course not required. 

> > and post in one of the manim-help channels -- it is a bit easier to figure out what is wrong there.
> 
> Ah?! Why?

There are way fewer people providing support here than on Discord, and especially for operating system depending questions (like how to clean up your installs), I probably can't really help.

**Comment by behackl** [comment]
Given that there is no explicit enhancement proposal in this issue, I'll mark it as wontfix and close it.

**Comment by dbitouze** [comment]
> The interface for passing keyword arguments to the scene itself is, unfortunately, not the cleanest yet. Have a look at how this is done in our example gallery: https://docs.manim.community/en/v0.2.0/examples.html#plotting-with-manim

OK. In this case, replacing:

```python
    CONFIG = {
        "y_max": 8,
        "y_axis_height": 5,
    }
```
by:
```python
    def __init__(self, **kwargs):
        GraphScene.__init__(
            self,
            y_max=8,
            y_axis_height=5,
            **kwargs)
```
did the trick.

 
> This has already been fixed and will be included in the next release: https://docs.manim.community/en/latest/tutorials/quickstart.html

Nice!
 
> There are way fewer people providing support here than on Discord, and especially for operating system dependent questions (like how to clean up your installs), I probably can't really help.

Okay (I'm using Linux).

Thanks!
