### ISSUE TITLE
MoveAlongPath, .animate, .rotate not working in case of square and circle

### ISSUE THREAD

**Issue by Analytical1703** [ManimCommunity/manim#919]
# code_1
```
square= Square(color=BLUE, fill_opacity=1)

  self.play(

         FadeIn(square)

  )

  self.play(

        square.animate.set_fill(ORANGE)

 )

  self.play(

        square.animate.rotate(1.0)

 )
```

#code_2

```
circle = Circle(color=PINK, radius=1)

dot = Dot()

self.play(

      Transform(square, circle)

)

self.play(

       dot.MoveAlongPath(dot, circle)

)
```

#Error 
Dot has no attribute 'MoveAlongPath'

Square has no attribute 'animate'.

**Comment by behackl** [comment]
Please use the issue template when reporting bugs; we need to have the complete console output to help.

In this case: for `MoveAlongPath`, have a look at our documentation: https://docs.manim.community/en/v0.2.0/reference/manim.animation.movement.MoveAlongPath.html?highlight=movealongpath#manim.animation.movement.MoveAlongPath -- it is not used in the way you are trying to use it.

The second error sounds like you are not using the latest version of Manim's community edition.

I'll close this issue for now as there is no way to properly investigate the situation further; we can reopen it once you provide further information and have made sure that you are on the latest version.
