### ISSUE TITLE
n x 1 DecimalMatrix seems broken

### ISSUE THREAD

**Issue by ChristianCoenen** [ManimCommunity/manim#924]
## Description of bug / unexpected behavior
Decimal numbers are split into their chars and each char is rendered as its own column.

## How to reproduce the issue
```py
from manim import *

class Test(Scene):
    def construct(self):
        self.add(DecimalMatrix([0.1]))
        self.wait(2)
```

</details>

## Additional media files
<img width="713" alt="Screenshot 2021-01-11 at 09 48 12" src="https://user-images.githubusercontent.com/22744609/104160922-3ae1ce00-53f2-11eb-9cca-e77f1ecdb23b.png">

**Comment by ChristianCoenen** [comment]
Investigating further, I figured out that it was my bad. The following syntax works.
```py
DecimalMatrix([[0.13]])
```

However, I would've expected the code above to produce the same result. Especially since it is inconsistent with a Matrix object as seen below:

```py
from manim import *

class Test(Scene):
    def construct(self):
        m1 = DecimalMatrix([0.1])
        self.add(DecimalMatrix([0.1]))

        m2 = Matrix([0.1]).next_to(m1, DOWN)
        self.add(m2)

        self.wait(2)
```
Produces:
<img width="563" alt="Screenshot 2021-01-11 at 10 31 36" src="https://user-images.githubusercontent.com/22744609/104164447-36201880-53f8-11eb-9db6-7c0916b49318.png">

**Comment by ChristianCoenen** [comment]
What fixes the problem for me is changing line 100 in ```matrix.py```
```py
matrix = np.array(matrix, ndmin=1)
```
to
```py
matrix = np.array(matrix, ndmin=2)
```

What ```ndmin``` does, is appending a dimension if the min dimension is not reached. 
So a vector of shape ```(2)``` would be changed to ```(2, 1)```.

I also think it is better to ensure a consistent 2dim shape when creating a Matrix. Otherwise, the code has to differentiate between 1d numpy shapes ```(X, )``` and 2d numpy shapes ```(X, Y)```

**Comment by leotrs** [comment]
Hello @ChristianCoenen and thanks for the report.

I think the way to go here is to fix `Matrix` and make it issue a warning (or outright fail) when being constructed with a 1-dimensional array. After all, a matrix should always have two dimensions.

**Comment by ChristianCoenen** [comment]
I agree that this should be prevented or warned. If the decision is to throw a warning, I'd recommend merging the PR to have consistency if someone uses a vector as input. Otherwise, my PR can be deleted. It would be interesting what others think about whether to throw an error or raise a warning.

**Comment by behackl** [comment]
I'd go for raising an error. If someone wants a matrix, they should specify a matrix.
