### ISSUE TITLE
Better Changelog handling

### ISSUE THREAD

**Issue by kolibril13** [ManimCommunity/manim#927]
The current way with the one-line summary into the changelog + copy&paste to the wiki requires a lot of manual work, and there might be better solutions.
Here https://github.com/KiloKilo/changelog is one project that might be useful for us.

**Comment by behackl** [comment]
I don't necessarily see a reason for using an external tool, git combined with explicit merge messages already produces a pretty neat result (which can also be formatted further):

```
$ git log --oneline --first-parent 8a673946..HEAD
c25b89c2 (HEAD -> master, origin/master, origin/HEAD) Bugfix: allow new-style method animation to be used in animation groups (#906)
2ed00b6b removed deprecated command line arguments from documentation (#908)
0dccec95 Tiny grammar improvements (#903)
1655da47 Added blank line between imports and class example (#904)
daf50697 Convenience method for creating a graph from a networkx graph (#893)
ae0122dc ci: fix publish workflow (#898)
```

**Comment by leotrs** [comment]
@behackl are you suggesting that the output of the command you posted replace the current changelog?

**Comment by behackl** [comment]
Not as-is, but a formatted version of it. It would not be too hard to reformat the output above (automatically) as a list that reads something like

```
- :pr:`906`: Bugfix: allow new-style method animation to be used in animation groups
- :pr:`908`: removed deprecated command line arguments from documentation
- :pr:`903`: Tiny grammar improvements
- :pr:`904`: Added blank line between imports and class example
- :pr:`893`: Convenience method for creating a graph from a networkx graph
- :pr:`898`: ci: fix publish workflow
```

And in addition to this, breaking changes should still get a special section in the changelog. But otherwise: yes. While this approach does not really support categorization any longer (except if someone wants to take this automatically generated list and split it into categories like bugfix / enhancement / documentation / other changes -- which I don't really want to volunteer for), it is much more consistent and easier to maintain than the automatically updated list in the wiki.

**Comment by leotrs** [comment]
Agreed!

For the categorization problem, we can try to actually start enforcing [these tags](https://www.conventionalcommits.org/en/v1.0.0/), or some version of it. In this way, we can simply `grep` the log and automate everything. On the other hand, this spreads out the burden across people and time.

**Comment by kolibril13** [comment]
But someone has to have this sorting burden: A) one person in the end, or B) all people together during the process.
I tend to go for B.

**Comment by behackl** [comment]
While I agree that it should be a group effort to get things right, I also think that classifying by commit message will be terribly unforgiving, especially if we want to automate it.

Here is a suggestion: we can introduce a set of labels on GitHub that we can tag PRs with. A script could then:
- generate the unformatted changelog as above, and in particular find the PR number for every line,
- query the API to get the labels,
- and based on those, generate a categorized and formatted changelog.

**Comment by leotrs** [comment]
That sounds like a good compromise. Also, in this way anyone can tag a PR with the appropriate label, while only the author can set the commit message (without some major git-ing).

OTOH, what happens if a PR's labels are changed after the fact? In this case there could be cases where the changelog changes in unexpected/undesired ways.

**Comment by kolibril13** [comment]
> OTOH, what happens if a PR's labels are changed after the changelog has been published? In this case there could be cases where the changelog changes in unexpected/undesired ways.

For each release, there could be an own changelog file that is created in a way so that they can not be changed anymore afterward.  The final changelog can then be constructed from all these subfiles.

**Comment by leotrs** [comment]
That's a good idea actually.

**Comment by kolibril13** [comment]
Nice!
What do you think about this, @behackl ?
Do we maybe want to start with this maybe already for this release?
In case we want to do it like this, I think we can already by now start to redesign the pr message:
```
Motivation
Overview / Explanation for Changes
Oneline Summary of Changes
- Added new feature ... / Fixed bug ... / ... (:pr:`PR NUMBER HERE`)
Testing Status
Further Comments
Acknowledgements
 I have read the Contributing Guidelines
Reviewer Checklist
 Newly added functions/classes are either private or have a docstring
 Newly added functions/classes have tests added and (optional) examples in the docs
 Newly added documentation builds, looks correctly formatted, and adds no additional build warnings
 The oneline summary has been included in the wiki
```
