### ISSUE TITLE
Rename NumberLine.n2p and NumberLine.p2n to something else

### ISSUE THREAD

**Issue by aman17009** [ManimCommunity/manim#930]
## Enhancement proposal
These two methods are some of the most important methods of the class NumberLine. But I think their names are too short and confusing and thus they should be renamed to something more descriptive such as - number_to_point and point_to_number or something similar. I think the default naming strategy of Manim to make the names as self explanatory as possible is very good and these two methods should also follow it.

**Comment by kilacoda** [comment]
`point_to_number` and `number_to_point` already exist.

https://github.com/ManimCommunity/manim/blob/99c79e92ac138255a903585e5e8bb9d049adc8e7/manim/mobject/number_line.py#L145-L163
