### ISSUE TITLE
Setting limits of ThreeDAxes

### ISSUE THREAD

**Issue by tirthasheshpatel** [ManimCommunity/manim#940]
## Description of bug / unexpected behavior

Currently, `ThreeDAxes` has no direct way of setting the `x` and `y` axis limits. The only way to do it is through `x_axis_config` and `y_axis_config` dictionaries. The `x_max` and `x_min` keys of the config dictionary are used by `Axes` to set the limits of the axes. The naming convention is very subtle and nuanced here. For example, a user would very well expect the following code to work:

```python
class Cool3DScene(ThreeDScene):
    def construct(self):
        axes = ThreeDAxes(z_min=-0.1, z_max=1,
                          z_axis_config={"preserve_tip_size_when_scaling": False,
                                         "tip_length": 0.2},
                          x_axis_config={"x_min": -3.5,
                                         "x_max": +3.5,
                                         "preserve_tip_size_when_scaling": False,
                                         "tip_length": 0.2},
                          y_axis_config={"y_min": -3.5,
                                         "y_max": +3.5,
                                         "preserve_tip_size_when_scaling": False,
                                         "tip_length": 0.2})
        axes.scale([1, 1, 3])
        self.set_camera_orientation(phi=75*DEGREES, theta=45*DEGREES)
        self.add(axes)
```

but this doesn't set the limits of the `y` axis properly.

![image](https://user-images.githubusercontent.com/43181252/104837017-e77eec80-58d7-11eb-9475-3a1877da8a86.png)

## Expected behavior

I would expect the constructor of `ThreeDAxes` to take `x_min`, `x_max`, `y_min`, and `y_max` as parameters or to just use the `min` key (instead of `x_min`) of the config dictionary to set the limits.

## How to reproduce the issue

<details><summary>Code for reproducing the problem</summary>

```py
class Cool3DScene(ThreeDScene):
    def construct(self):
        axes = ThreeDAxes(z_min=-0.1, z_max=1,
                          z_axis_config={"preserve_tip_size_when_scaling": False,
                                         "tip_length": 0.2},
                          x_axis_config={"x_min": -3.5,
                                         "x_max": +3.5,
                                         "preserve_tip_size_when_scaling": False,
                                         "tip_length": 0.2},
                          y_axis_config={"y_min": -3.5,
                                         "y_max": +3.5,
                                         "preserve_tip_size_when_scaling": False,
                                         "tip_length": 0.2})
        axes.scale([1, 1, 3])
        self.set_camera_orientation(phi=75*DEGREES, theta=45*DEGREES)
        self.add(axes)
```

</details>

## Additional media files

<details><summary>Images/GIFs</summary>

![image](https://user-images.githubusercontent.com/43181252/104837084-5eb48080-58d8-11eb-9b3c-49ac19efee66.png)

</details>

## Additional comments

Changing the config dict keys without a deprecation warning would be catastrophic. Meanwhile, an easier fix would be to add the `x_min`, `x_max`, `y_min`, and `y_max` as parameters.

**Comment by kolibril13** [comment]
Closing this in favor of #941
