### ISSUE TITLE
Division by zero upon instancing of PointCloudDot

### ISSUE THREAD

**Issue by 104-105-114-101-032-109-101** [ManimCommunity/manim#946]
### Unexpected Behavior
Instantiating a `PointCloudDot` results in a division by zero. The problematic line can be found [here](https://github.com/ManimCommunity/manim/blob/fc754fa7f60a7b49840628311f809840c98cdceb/manim/mobject/types/point_cloud_mobject.py#L239).

### Analysis
The variable `r` is defined at `r in np.arange(0, self.radius, self.epsilon)`. Since `np.arange()` includes the lower bound, `r` will assume the value zero and thus leads to a division by zero in the next line. To avoid that division, it's enough to change the lower bound of `np.arange()` to `self.epsilon`. `r=0` does not occur anymore, while other values of `r` remain unchanged.

### Minimal Example
```py
class PointCloudDotTest(ThreeDScene):
    def construct(self):
        p = PointCloudDot()
        self.play(FadeIn(p))

PointCloudDotTest().render()
```

**Comment by leotrs** [comment]
Thanks for reporting. Sounds like an easy PR :wink:
