### ISSUE TITLE
remove media_dir.txt

### ISSUE THREAD

**Issue by leotrs** [ManimCommunity/manim#95]
I don't think it's used anywhere in the code base.

**Comment by XorUnison** [comment]
I nuked it already... except there were 2. One in the manim folder and there really is one left in the scene folder.

Yeah I'm certain we don't need that anymore either. Nuke away.
I guess that's just the kind of thing that happens without the repo search that I'd have normally fired after stuff like media_dir to make sure its purged for good. I really hope GitHub addresses that soon.

**Comment by leotrs** [comment]
Wait I can't find it anymore - where was it?

**Comment by XorUnison** [comment]
As I said, manim/scene still contains one. The one in the manim main folder was removed by my PR.

**Comment by leotrs** [comment]
Closed via #99
