### ISSUE TITLE
Adding simple sound asserts to manim library

### ISSUE THREAD

**Issue by kolibril13** [ManimCommunity/manim#962]
Adding sounds in manim involves quite some steps: it is searching for a sound on the internet, bringing it to the right location, and then copy the path of it to `add_sound`

## Motivation why more sounds in videos are beneficial:

When it comes to scenes where recognizing small time intervals is important, our human brains are much better with hearing than with our eye vision.
See e.g. here: https://youtu.be/HEfHFsfGXjs?t=124

So my idea is to add some basic sounds to the library (which can be even useful for debugging and timing in a video editor.)
It could be e.g. a beep, a click, a clack, and a tick, all in all, probability less than an MB.

First, it might feel a bit strange to have sound files in the library, however, other repos (e.g. scikit-image: https://scikit-image.org/docs/stable/auto_examples/data/plot_general.html) have asserts as well.

And we could get the sound from a free online sound library:  https://freesound.org/

If there is interest, I would do a pr.

**Comment by leotrs** [comment]
> Adding sounds in manim involves quite some steps: it is searching for a sound on the internet, bringing it to the right location, and then copy the path of it to add_sound

I don't think this is too bad. This is literally the same amount of steps to include any kind of asset on any kind of project.

Having said that, I'm not opposed to adding some basic audio files to the main library, as long as there are few of them and we keep the overall size low.

**Comment by kolibril13** [comment]
This is implemented in #926, so I am closing this issue.
