### ISSUE TITLE
How to use `Bezier` splines in manim

### ISSUE THREAD

**Issue by kolibril13** [ManimCommunity/manim#963]
The current (and not so nice) answer is, like this:
```py
class BezierSpline(Scene):
    def construct(self):
        np.random.seed(42)
        area = 4
        p1 = np.array([-3, 1, 0])
        p1b = p1 + [1, 0, 0]
        d1 = Dot(point=p1).set_color(BLUE)
        l1 = Line(p1, p1b)
        self.add(l1, d1)
        p2 = np.array([3, -1, 0])
        p2b = p2 - [1, 0, 0]
        d2 = Dot(point=p2).set_color(RED)
        l2 = Line(p2, p2b)
        self.add(l2, d2)
        l1.add_cubic_bezier_curve(p1b, p1b + 3 * RIGHT, p2b - 3 * RIGHT, p2b)
```
However, this is not very pretty, it would be nice to have something like a `Bezier` class, that is meant to be used by users.
Me and @huguesdevimeux had a conversation about it here: https://github.com/ManimCommunity/manim/pull/961/files#r563942279

Should this be implemented or is this feature unnecessary, as this is already possible by now?

**Comment by huguesdevimeux** [comment]
Hi, there is `CubicBezier` for this, I think.

This is basically a VMobject but with given points.

**Comment by kolibril13** [comment]
Nice!
Should I tweak this above example a bit and then push it to your open pr?

**Comment by huguesdevimeux** [comment]
I don't understand, what are you proposing?

**Comment by kolibril13** [comment]
That we add the example 
```py
class BezierSplineExample(Scene):
    def construct(self):
        np.random.seed(42)
        p1 = np.array([-3, 1, 0])
        p1b = p1 + [1, 0, 0]
        d1 = Dot(point=p1).set_color(BLUE)
        l1 = Line(p1, p1b)
        p2 = np.array([3, -1, 0])
        p2b = p2 - [1, 0, 0]
        d2 = Dot(point=p2).set_color(RED)
        l2 = Line(p2, p2b)
        bezier=CubicBezier([p1b, p1b + 3 * RIGHT, p2b - 3 * RIGHT, p2b])
        self.add(l1, d1,l2, d2,bezier)
```
to the class `CubicBezier`.

**Comment by huguesdevimeux** [comment]
It seems good to me, (but why using randomness?)

**Comment by kolibril13** [comment]
no, reason, was an artefact from a previous script, I ll do a pr.
