### ISSUE TITLE
Impossible to use preview with Scene().render()

### ISSUE THREAD

**Issue by huguesdevimeux** [ManimCommunity/manim#966]
## Description of bug / unexpected behavior
The title. For example : 
```python
class Test(ThreeDScene):
    def construct(self):
         # cool scene goes there

Test().render()
```
and a config file with `preview = True`. 
The config file is detected by manim, and the preview flag is introduced in config dict.

## Expected behavior
The scene should open in a preview windows as it normally does with `-p` flag in CLI

## How to reproduce the issue
See above.

## Additional comments
The preview logic is run in [main](https://github.com/huguesdevimeux/manim/blob/bf6c56e73a7a3132587c2c804d10c140d1929b92/manim/__main__.py#L49-L50), which is called in [__main__()](https://github.com/huguesdevimeux/manim/blob/bf6c56e73a7a3132587c2c804d10c140d1929b92/manim/__main__.py#L102-L103). 
The issue is when not using `manim`command, __main__ is not called. 

A potential fix would be to move this logic into the renderer.

**Comment by leotrs** [comment]
The `preview` config option in the config file is meant to change the behavior of the `-p` flag when called from the command line. If you are not using manim from the command line, it won't do anything, so this is expected behavior. (As a matter of fact, the original purpose of the `[CLI]` title of the config file was precisely to determine that the options contained therein will affect the command line, and not other parts of manim.)

Having said that, my opinion is that we shouldn't call an external program from the core library. My explanation is [here](https://github.com/ManimCommunity/manim/issues/829#issuecomment-739290741) cc @kolibril13 . I could be convinced otherwise if enough people feel this is an important feature.

**Comment by huguesdevimeux** [comment]
It makes sense, 

> I could be in favor of implementing something like Scene.preview() or Scene.show(), but I honestly don't think that's necessary.

I believe this is an excellent idea, and can be useful for people don't use CLI, for some reason (as an example, I personnaly prefer running a scene directly from my IDE). Futhermore, PIL, matplotlib, etc have such a feature, it would make sense that manim has it to. 

I'll try to work on something like this.

**Comment by leotrs** [comment]
Like I said, I'm not opposed to it, but I would be weary of feature creep. By this I mean that it would be fine to have a simple `show()` method, but I believe it should be kept simple and straightforward. Remember manim is not a plotting/video-showing library, it is a rendering library. (At least for now!)

**Comment by huguesdevimeux** [comment]
I see. So, before going any further, I would like to have the opinion of @ManimCommunity/core : 
Here are the words of @leotrs :

> >   2. It is not yet possible to use the preview flag -p from the comment line, that is why I currently used matplotlib.
> 
> I am against implementing the preview flag in this way. The reason is that the preview flag has nothing to do with manim itself and it just asks another application to run a file created by manim. This is what the command line command is important: to interface between manim and other applications. I could be in favor of implementing something like Scene.preview() or Scene.show(), but I honestly don't think that's necessary.
> 
> EDIT: the reason why I don't think it's necessary is because implementing such a method would remove only two lines from the script you have posted. It makes much more sense to me to explicitly call matplotlib with two lines of code) than to have the core manim codebase do that for you.

What are your thoughts? Should the user be able to preview a scene directly from a python file (not from the CLI)? Or should one use like `Scene.preview()` ?

**Comment by kilacoda** [comment]
IIRC, all the CLI `-p` option does internally is call the function `open_file_if_needed` right? Why not add a boolean `preview` keyword parameter to `Scene.render` which does exactly that?

On the topic of opening external applications via manim, we already sort of do this with `Mobject.show`, no?

**Comment by sparshg** [comment]
why not do a poll for this?..

**Comment by leotrs** [comment]
> IIRC, all the CLI `-p` option does internally is call the function `open_file_if_needed` right? Why not add a boolean `preview` keyword parameter to `Scene.render` which does exactly that?
> 
> On the topic of opening external applications via manim, we already sort of do this with `Mobject.show`, no?

I would sooner remove Mobject.show than implement more functionality that depends on external applications.

**Comment by behackl** [comment]
I don't think that it is very unusual to ask the operating system to open a generated file with the corresponding default viewer. For MacOS and Windows, this should be covered by `open` or `start` -- and for UNIXoid systems that use a window managers which is a part of freedesktop.org (which is certainly all of the mainstream ones like Gnome and KDE), there is `xdg-open`. (Actually, we are already using said logic in `open_file` in `utils/file_ops.py`.)

I don't really think that when making a call to any of these, that we introduce a dependency on an external application (although I *can* relate to @leotrs's worries of feature creep). Given the popularity of the `-p` flag (judging from questions on Discord), I can see how people who like to render within the script would find a similar functionality for there useful.

Personally, I wouldn't mind adding a keyword argument to `render` which calls the existing `open_file` function.

**Comment by kilacoda** [comment]
To what benefit exactly? If it works and provides a convenience to users I don't see why we shouldn't. Calling render directly from the script may prove beneficial in debugging as well and in the case of manim this heavily involves viewing the output of a rendered scene, hence why I think the option of previews should not be limited to the command line.

**Comment by leotrs** [comment]
I can get behind using xdg-open, but I would be _very much_ against using something like matplotlib (see [here](https://github.com/ManimCommunity/manim/issues/829)). And even then, if someone asks for a different application, or to add more features to the preview function, I would be very much against it.

But a simple clean call to xdg-open seems fine.
