### ISSUE TITLE
Wrong orientation of vector tip

### ISSUE THREAD

**Issue by sparshg** [ManimCommunity/manim#968]
## Description of bug / unexpected behavior

Orientation of tips of some vectors are wrong

## How to reproduce the issue
```py
class Vectors(ThreeDScene):
    def construct(self):
        self.add(Vector(RIGHT), Vector(UP), Vector(OUT))
        self.set_camera_orientation(phi=PI/3, theta=PI/6)
        self.begin_ambient_camera_rotation(rate=2)
        self.wait(PI)
```

## Additional media files
![Vectors](https://user-images.githubusercontent.com/43041139/106003681-71993300-60d8-11eb-8351-b1d956566258.gif)

**Comment by icedcoffeeee** [comment]
Fixed in #1924
