### ISSUE TITLE
Paragraph and Code mobjects do not obey line_spacing

### ISSUE THREAD

**Issue by hgoldstein95** [ManimCommunity/manim#987]
## Description of bug / unexpected behavior
The `line_spacing` parameter passed to `Paragraph` mobjects (and by extension, `Code` mobjects) is ignored.

## Expected behavior
Passing different values of `line_spacing` will properly change the spacing between lines in a paragraph/code listing.

## How to reproduce the issue
Rendering the following `Code` object results in a code listing with default-spaced lines.

<details><summary>Code for reproducing the problem</summary>

```python
listing = Code(
    "helloworldcpp.cpp",
    tab_width=4,
    background_stroke_width=1,
    background_stroke_color=WHITE,
    insert_line_no=True,
    style=Code.styles_list[15],
    background="window",
    language="cpp",
    line_spacing=0.7,
)
```

</details>

## Additional comments
As per a conversation on discord, @behackl believes the issue can be solved by modifying `text_mobject.py` on line 446 and properly forwarding the `line_spacing` parameter to the `Text` constructor.

**Comment by naveen521kk** [comment]
Does passing the `line_spacing` parameter actually fixes this?

**Comment by behackl** [comment]
It did when I tried it locally.

**Comment by naveen521kk** [comment]
So, did that fix that?
