### ISSUE TITLE
I cannot run scenes by importing modules from other files.

### ISSUE THREAD

**Issue by tinfungster** [ManimCommunity/manim#992]
## Description of bug / unexpected behavior
I wanted to have something like a CONFIG dictionary, where there are some parameters to change and the animation would change based on the parameters. However, I am unable to make the animation. I am also aware the CONFIG dictionaries are now deprecated in Manim Community now. I checked Manim Docs, but the code did not work.

## Expected behavior
When I ran my code, it gave me an error that said that the module was not found. However, in Grant's Manim, it worked.

## How to reproduce the issue
In Grant's version of Manim, you would have 2 files and it was something like this:
File where I import modules (Import_Module.py)
--------------------------------------
```
from manimlib.imports import *
from My_Code.Module import *

class Scene_Name(Module_Scene):
    CONFIG = {
        "number": 4 
    }
```
-------------------------------------
Module File (Module.py)
-------------------------------------
```
from manimlib.imports import *
from My_Code.file import *

class Module_Scene(Scene):
    def construct(self):
        number = self.number

        self.add(TextMobject(str(number)))
```
----------------------------------------------
Then you would run the first file in the terminal, like this:
python3 manim.py My_Code/Import_Module.py -p
----------------------------------------------
I would assume that something similar would happen in Manim Community. I checked the documentation, but it didn't work. The Manim Docs is here:
https://docs.manim.community/en/latest/changelog.html#v0-2-0
-----------------------------------------------
The code would look something like this:
File where I import modules (Import_Module.py)
--------------------------------------
```
from manim import *
from My_Code.Module import *

class Scene_Name(Module_Scene):
    Scene_Name(number=4)
```
-------------------------------------
Module File (Module.py)
-------------------------------------
```
from manim import *
from My_Code.file import *

class Module_Scene(Scene):
    def construct(self):
        number = self.number

        self.add(Tex(str(number)))
```
----------------------------------------------
Then you would run the first file in the terminal, like this:
manim My_Code/Import_Module.py -p -ql 

But it gave me this error:
Traceback (most recent call last):
number = self.number
AttributeError: 'Scene_Name' object has no attribute 'number'.

## Additional comments
I hope you understand what the error is. Could you please explain how I could fix this problem? Thank you!

**Comment by tinfungster** [comment]
Note: I don't know how to have indents/tabs in markdown. That's why the formatting is quite weird. Sorry!

**Comment by behackl** [comment]
> Note: I don't know how to have indents/tabs in markdown. That's why the formatting is quite weird. Sorry!

Put code blocks into blocks of three backticks, like this:

\`\`\`
your code goes here
\`\`\`

Otherwise, this is unfortunately pretty hard to read.

**Comment by tinfungster** [comment]
Oh. Thank you!

**Comment by tinfungster** [comment]
The formatting is better now!

**Comment by Aathish04** [comment]
What are the contents of `My_code.file`?

In your example, you import everything from it, yet nothing from it is used.

This is fine:
```py
from manim import *
from My_Code.file import *
```

And here, you define Module_Scene by inheriting from `Scene`, which is a core manim object. Did you redefine `Scene` in `My_code.file`?

```py
class Module_Scene(Scene):
```

**Comment by behackl** [comment]
Closing this issue due to lack of a response.
