### ISSUE TITLE
Remove 'MovingCameraScene.camera_frame' and 'MovingCameraScene.setup'

### ISSUE THREAD

**Issue by mondeja** [ManimCommunity/manim#999]
## Enhancement proposal

[`MovingCameraScene.setup` method](https://github.com/ManimCommunity/manim/blob/2faa89e3d367c370fd101893f03efab63109ceb0/manim/scene/moving_camera_scene.py#L94-L104) only sets the attribute `camera_frame` into the `Scene` instance, pointing to `renderer.camera.frame`, but since the property [`camera` exists in `Scene` class](https://github.com/ManimCommunity/manim/blob/57f228b8eb96f9c99517a7fdb8756b0c4969d7ff/manim/scene/scene.py#L101-L103), the object `renderer.camera.frame` can be accesed using `camera.frame`.

Changing `camera_frame` by `camera.frame` and removing the useless `setup` method, the example `FollowingGraphCamera` could be rewritten as:

```python
class FollowingGraphCamera(GraphScene, MovingCameraScene):
    def setup(self):
        GraphScene.setup(self)

    def construct(self):
        self.camera.frame.save_state()
        self.setup_axes(animate=False)
        graph = self.get_graph(lambda x: np.sin(x),
                               color=BLUE,
                               x_min=0,
                               x_max=3 * PI
                               )
        moving_dot = Dot().move_to(graph.points[0]).set_color(ORANGE)

        dot_at_start_graph = Dot().move_to(graph.points[0])
        dot_at_end_graph = Dot().move_to(graph.points[-1])
        self.add(graph, dot_at_end_graph, dot_at_start_graph, moving_dot)
        self.play(self.camera.frame.animate.scale(0.5).move_to(moving_dot))

        def update_curve(mob):
            mob.move_to(moving_dot.get_center())

        self.camera.frame.add_updater(update_curve)
        self.play(MoveAlongPath(moving_dot, graph, rate_func=linear))
        self.camera.frame.remove_updater(update_curve)

        self.play(Restore(self.camera.frame))
```

Studying the original example, I was confused as to why accessing `camera.frame` was done using` camera_frame`.

### Additional comments

The `setup` method [made sense in the original implementation](https://github.com/ManimCommunity/manim/blame/2981fa2b32f0b3827317efc75df56c0585c6c0f0/scene/moving_camera_scene.py#L11-L17) but with the changes that have happened since then it's just dead code now.

**Comment by huguesdevimeux** [comment]
Thanks for this very good report ! 

I do agree that the attribute should be removed. 
But if you remove setup, it will remove the type check on the camera object. Is it ok?

**Comment by mondeja** [comment]
> But if you remove setup, it will remove the type check on the camera object. Is it ok?

I think so. Since the inherited class is `MovingCameraScene`, does haven't sense to check if the camera is instance of `MovingCamera`. If someone want another camera, just inherit from another scene or change the camera in place, doing their own typechecks if needed.
